### ISSUE TITLE
overlay in collection mode and zero margins 

### ISSUE THREAD

**Issue by fer-marino** [openseadragon/openseadragon#1011]
hi,
I'm struggling with osd mostly because I have poor javascript abilities. 
Please have a look at this:
http://fiddle.jshell.net/fmarino/0ntdnz5a/3/

I have a set of satellite images that goes from north to south, so I've decided to show them using collection mode into a single column. Now those images are actually contiguous so I want them to be stitched together settings collectionTileMargin to zero, but apparently it ignores my attempts. Why?

I also want to show over each image some metadata (when it was acquired and where it was processed) using overlays, but I'm also failing at this just following the examples in the documentation. 

I apologies for the simple question but I'm bad at this.

Regards,
Fernando

**Comment by iangilman** [comment]
Welcome to OpenSeadragon! 

To lay out your image you probably need to specify the locations yourself; collection mode isn't nuanced enough to support your scenario. Here's an example:

http://fiddle.jshell.net/d99w2neL/2/

If you need to do a lot of them, I can give you tips on doing it via code (rather than hand coding the y values). 

That example includes an overlay as well. Let me know if you have questions!

**Comment by fer-marino** [comment]
Hi Ian,
thank you for your help, this is exactly what I need!

Yes, I have to do a lot of them so I need a way to automate things. Investigating your solution my concern is how to calculate the viewport coordinate of my images. I found this method in the doc:
https://openseadragon.github.io/docs/OpenSeadragon.TiledImage.html#imageToViewportCoordinates

But I'm not sure where to call it as in your solution the TiledImage is built in the constructor. A way around would be to fetch the dzi descriptor, parse it using xpath and convert its coordinates before declaring the osd viewer, but maybe there is a better way.

**Comment by iangilman** [comment]
Sure, here's how you would do it automatically:

http://fiddle.jshell.net/d99w2neL/3/

**Comment by fer-marino** [comment]
thank you very much!

I'm almost out of the woods thank to you ;)

One last question, if I put a clickable link into the overlay somehow it does not seems to works. How can I do this?

**Comment by iangilman** [comment]
Yes, unfortunately that's a little tricky; you have to use OpenSeadragon.MouseTracker. Here's an example:

http://codepen.io/iangilman/pen/mEkKaY
