### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [openseadragon/openseadragon#1012]
Hello @mikolalysenko ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
I think the main file is `build/openseadragon/openseadragon.js` on [npm](https://www.npmjs.com/package/openseadragon), and is necessary to add `build/openseadragon/images/`?
Please help me confirm that.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8811

**Comment by iangilman** [comment]
Wonderful! We'd love to be on cdnjs but haven't gotten around to submitting.

The latest stable release is actually in a different repository... this is the folder: 

https://github.com/openseadragon/site-build/tree/master/built-openseadragon/openseadragon

Everything in that folder is needed, and that's the whole package.

Let me know if you need any more info, and let me know when it's in so we can promote it on our site!

**Comment by kennynaoh** [comment]
Thanks!
Because there are just `v1.1.1`~`v2.2.1` [here](https://github.com/openseadragon/site-build/tree/master/built-openseadragon/openseadragon), how about the older version [here](https://github.com/openseadragon/openseadragon)?
Like `v0.9.124`~`v1.1.0`, which files need to be grab in these older version?
Please help me confirm that.
Thanks for your help!

**Comment by iangilman** [comment]
You can get all the historic versions back to 0.9.124 here:

https://github.com/openseadragon/openseadragon/releases

The site-build location will be a reliable place to get all future versions.

**Comment by kennynaoh** [comment]
Thanks!
What I mean is I am not certainly sure which files are necessary to grab between these old version `v0.9.124`~`v1.1.0` on [github](https://github.com/openseadragon/openseadragon).
I speculate that there are two parts I need to grab are`src/openseadragon.js` and `images/`, right?
Thanks for your help!

**Comment by iangilman** [comment]
Hmm... does it need to be from github? For CDN hosting you would just want the built files, but for versions v0.9.124~v1.1.0 we didn't check the built files in anywhere... what you see is the source. The only place you can find the built files for those versions is in the zip archives in the [releases](https://github.com/openseadragon/openseadragon/releases).

Would it help if we pulled those archives out and hosted them in a repo somewhere? Or can you use them directly? Or should we punt on those early versions?

**Comment by maruilian11** [comment]
Thank you! We have built files for old versions and open a PR here: https://github.com/cdnjs/cdnjs/pull/11204
You can take a look and check if anything is missed. 😃

**Comment by iangilman** [comment]
@maruilian11 Wow, that's very thorough! Looks like you've got everything as far as I can tell! Thank you for doing this :)

**Comment by maruilian11** [comment]
@iangilman It's my pleasure. I will notify you once it is done 👍

**Comment by iangilman** [comment]
@maruilian11 Looks like the patch has landed! Congratulations :) Thank you again for all the hard work on this!

So is it available now, or is there still another deploy step or something? How do we access the script and images on the cdn? Is it possible to specify a specific version or a range of versions (such as 2.2.x)? Sorry if these questions are basic; I haven't used cdnjs very much. 

Also, is there any ongoing maintenance necessary, or will it just automatically pick up the new releases as we release them?

**Comment by maruilian11** [comment]
@iangilman Please take a look on the following link. 
https://cdnjs.com/libraries/openseadragon

Because our auto-update mechanism depend on `git tags`, just remember to update git tag for every future version, the new release will be on the site (It may take few hours to update the release on the site after it released on GitHub). Feel free to open an issue if you have any question. 😃

It would be appreciated if you could also mention `CDNJS` in http://openseadragon.github.io/#download 😄

**Comment by iangilman** [comment]
@maruilian11 Beautiful, thank you! And yes, we'll continue to use tags on upcoming releases. 2.3.0 should be soon, so we can make sure everything works then. 

I've updated http://openseadragon.github.io/#download ...please take a look and make sure I did it right :)

I've also tweeted it: 

https://twitter.com/openseadragon/status/865620056025079808

Exciting to have this in place! :)
