### ISSUE TITLE
Initial image view loads tiles sequentially

### ISSUE THREAD

**Issue by CaptainCodeman** [openseadragon/openseadragon#1013]
It looks like the initial view of an image loads the tiles sequentially, never in parallel. Once they are loaded then zooming in loads additional tiles in parallel as expected. I've tried setting various combinations of `immediateRender`, `imageLoaderLimit`, `sequenceMode` etc... but none seem to change the initial behavior.

Here's the network trace for the homepage demo which mirrors what I'm seeing in my own app:

<img width="958" alt="screen shot 2016-08-24 at 2 39 05 pm" src="https://cloud.githubusercontent.com/assets/304910/17947267/377807fc-6a09-11e6-890f-3040add86fcc.png">

Is this expected?

**Comment by iangilman** [comment]
Interesting... no, that's not expected. I'm not sure why it would do that, but I see the same results you're seeing.

Would you be up for investigating?

**Comment by CaptainCodeman** [comment]
Yeah, I started having a look through the codebase but still getting familiar / up-to-speed with it. I wanted to check if I wasn't just missing some setting first or it isn't by design.

**Comment by iangilman** [comment]
Excellent... let me know if you need any help finding your way around the code!
