### ISSUE TITLE
Tiles disappear before they go out of view

### ISSUE THREAD

**Issue by CaptainCodeman** [openseadragon/openseadragon#1015]
I think https://github.com/openseadragon/openseadragon/pull/987 may have introduced an issue where the tiles close to going out of the view are removed too early (only on master).

Here's an example with debugMode enabled:

<img width="430" alt="screen shot 2016-08-25 at 2 18 57 pm" src="https://cloud.githubusercontent.com/assets/304910/17984576/12ff97d4-6acf-11e6-9ad3-ab58dbc27747.png">

As the image is panned left the ones on the edge vanish before they are actually out of view:

<img width="412" alt="screen shot 2016-08-25 at 2 19 12 pm" src="https://cloud.githubusercontent.com/assets/304910/17984596/2803f7ec-6acf-11e6-8b6f-4fee6352b2a1.png">

It also happens on the top edge as well (bottom and right seem OK). The distance grows as you move further from the top / left of the image where it's less noticeable.

**Comment by VoidVolker** [comment]
Provide code to reproduce, please.

**Comment by CaptainCodeman** [comment]
Use master.
Run `grunt dev`.
Goto http://localhost:8000/test/demo/iiif.html
Zoom in towards the bottom / right of the image.
Pan and look at the top - left edges as tiles are close to leaving the viewport.

**Comment by iangilman** [comment]
That repro works for me... I see the bug. @VoidVolker have you been able to repro it?

I can also repro with the duomo image (the test pattern image is too shallow to repro with), by modifying the code of basic.html to:

```
        var duomo = {
            Image: {
                xmlns: "http://schemas.microsoft.com/deepzoom/2008",
                Url: "http://openseadragon.github.io/example-images/duomo/duomo_files/",
                Format: "jpg",
                Overlap: "2",
                TileSize: "256",
                Size: {
                    Width:  "13920",
                    Height: "10200"
                }
            }
        };

        var viewer = OpenSeadragon({
            debugMode: true,
            id: "contentDiv",
            prefixUrl: "../../build/openseadragon/images/",
            tileSources: duomo,
            showNavigator:true
        });
```

**Comment by avandecreme** [comment]
This should be fixed in master.

**Comment by CaptainCodeman** [comment]
Confirmed
