### ISSUE TITLE
Spreading tile loads across multiple subdomains?

### ISSUE THREAD

**Issue by allanw1** [openseadragon/openseadragon#1021]
Since browsers will only open a limited number of connections per domain, has anyone experimented with round-robin or randomizing the use of subdomains which all point to the same image files to speed up tile loading?

**Comment by CaptainCodeman** [comment]
Yes, I use a hashing function so each tile is predictably loaded from the same sharded domain. It makes a difference for ye-olde browsers but is going to be less necessary when the world has moved to HTTP/2

**Comment by CaptainCodeman** [comment]
Here's an example, suppose you have 4 sharded domains (e.g. using CNAMEs in DNS):

* img1.myservice.com
* img2.myservice.com
* img3.myservice.com
* img4.myservice.com

The get-tile URL will spread the requests out but consistently (which helps improve potential hits with any CDN / proxy caching):
```
var url = 'http://img$.myservice.com';
_getTileUrl: function (level, x, y) {
  var shard = 1;
  if (x % 2) shard += 2
  if (y % 2) shard += 1
  return url.replace(/\$/, shard) + '/image_id/' + x +'_' + y + '.jpg';
}
```

**Comment by cleverlight** [comment]
I'd like to experiment with this approach.  I'm working on a canvas of dynamically generated tiles (200ms+/tile), but I need to horizontally scale the generation across multiple servers.  Can anyone offer any advice on how to do it please?  I'm happy to (try to) code up a plugin to replace the `ImageTileSource.getTileUrl` function if that's the way?  Any docs/pointers appreciated.

**Comment by iangilman** [comment]
I think it may be as simple as the code example above from @CaptainCodeman. Take a look at http://openseadragon.github.io/examples/tilesource-custom/ for an example of where the `getTileUrl` function fits in.

**Comment by cleverlight** [comment]
> Take a look at http://openseadragon.github.io/examples/tilesource-custom/ for an example of where the `getTileUrl` function fits in.

That looks great.  Is the tilesource-custom approach compatible with `IIIFTileSource`?  I'm trying to implement the 'monkey patch' [advocated here in this SO answer](https://stackoverflow.com/questions/57269944/how-to-build-tile-url-as-per-loris-standard).

```
    var tileSource = {
        "@context": "http://iiif.io/api/image/2/context.json",
        "@id": `{{ tile_source }}`,
        "width": {{ width }},
        "height": {{ height }} ,
        "profile": ["http://iiif.io/api/image/2/level2.json"],
        "protocol": "http://iiif.io/api/image",
        "tileOverlap": 0,
        "tiles": [{
           "scaleFactors": [1, 2, 4, 8, 16, 32],
           "width": 256
        }],
        "getTileUrl": function( level, x, y ) {
            return $.IIIFTileSource.prototype.getTileUrl.call(this, level, x, y);
        }
    };
    zoomviewer.init([tileSource]);
```

but the instant I specify the `getTileUrl` element, I get a start-up error:

```
[TileSource.getTileSize] is deprecated. Use TileSource.getTileWidth() and TileSource.getTileHeight() instead
```

**Comment by iangilman** [comment]
Hmm... as it turns out, including `getTileUrl` in the tile source flags it as being a custom tile source, so it doesn't actually activate the IIIF code. Because of that, you should load the IIIF tile source as normal but then monkey patch it afterwards. This should do it: 

```
var tileSource = {
   "@context": "http://iiif.io/api/image/2/context.json",
   "@id": `{{ tile_source }}`,
   "width": {{ width }},
   "height": {{ height }} ,
   "profile": ["http://iiif.io/api/image/2/level2.json"],
   "protocol": "http://iiif.io/api/image",
   "tileOverlap": 0,
   "tiles": [{
      "scaleFactors": [1, 2, 4, 8, 16, 32],
      "width": 256
   }]
};

var tileImageSpec = {
  tileSource: tileSource,
  success: function(event) {
    var tiledImage = event.item;
    tiledImage.source.getTileUrl = function( level, x, y ) {
      return OpenSeadragon.IIIFTileSource.prototype.getTileUrl.call(this, level, x, y);
    }
  }
}

zoomviewer.init([tileImageSpec]);
```
