### ISSUE TITLE
Thumbnails not displaying

### ISSUE THREAD

**Issue by nhart** [openseadragon/openseadragon#1023]
Hi, I am using your viewer for displaying paged content (books, newspapers, etc). On some books, the thumbnails are not displaying in the reference strip.

eg: https://digitalcollections.barnard.edu/object/1342/barnard-lawyers-committee-some-topics-be-discussed-1971

Why is this happening?

Thanks in advance,
Nelson

**Comment by iangilman** [comment]
I actually don't know that much about the reference strip, but it looks like each thumbnail is actually a mini OSD viewer. Perhaps the tile source you're using doesn't like being that small? What tile source are you using? Maybe it's not generating tiles for that size (although it is for the navigator which is also a mini OSD viewer and not much bigger than the thumbnails).

**Comment by nhart** [comment]
The reference strip works for some books. eg: https://digitalcollections.barnard.edu/object/844/draft-report-task-force-barnard-and-educated-woman-april-1971Some books are only missing 2 or 3 thumbnails and have 10+ working images

We are using Adore Djatoka for the source. I am only seeing 2 requests in the log, one for each image. Based on that, it appears it's using the same image for both the large OSD and the thumbnail.

**Comment by iangilman** [comment]
Well, I'm guessing it has something to do with the tile source, particularly at that size.

I did an experiment with https://digitalcollections.barnard.edu/object/1342/barnard-lawyers-committee-some-topics-be-discussed-1971 by making the viewer tiny (100px by 50px) and zooming out, and sure enough the image disappeared. It looks like the image at the very tip of the pyramid is empty somehow. This is either a problem with the actual data on the server or the "tile source" object that you're using to access it. 

 Is this the tile source code you're using? 

https://github.com/Islandora/islandora_openseadragon

It might be worth checking with that project.
