### ISSUE TITLE
load local dzi: works with Firefox, IE. Not on chrome

### ISSUE THREAD

**Issue by murbano89** [openseadragon/openseadragon#1036]
Working with first setup of openseadragon after becoming fed-up with google maps API for pyramid image display. Trying to serve a local file from windows file system. Here is my simple index.hml code...

```
<html lang="en" class="no-js">
    <head>
                <title>First Try openseadragon</title>

</script><div id="openseadragon1" style="width: 800px; height: 600px;"></div>
<script src="openseadragon/openseadragon.min.js"></script>
<script type="text/javascript">
    var viewer = OpenSeadragon({
        id: "openseadragon1",
                prefixUrl: "openseadragon/images/",
                                tileSources: "dzi/histology01.dzi",
    });
</script>
```

I have a file called histology01.dzi file under a subdirectory called dzi and a file with component files (histology01_files). What mystifies me: opening my index.html loads pyramid image in Internet Explorer and Firefox but not Chrome. I did try running chrome with chrome --allow-file-access-from-files, but images still did not display. I think openseadragon and associated javascript is working since button icons load with functionality (and the viewer window), but the content never makes it to be displayed.

Any ideas would be much appreciated. Thank you very much. - murbano

**Comment by KTGLeiden** [comment]
I have had this problem as well. Do you get the 404 as well? Are you sure the mime-type for .dzi files is set correctly? I had to adjust that last one and then it worked :) i guess i made it XML typed, something like that. You can alsof try plain text i guess. I am not at a PC right now but mimetype might push you in the right direction (i hope).

~Koen

**Comment by avandecreme** [comment]
Surprising it does not work with --allow-file-access-from-files.
What you can try is to avoid doing any Ajax request by opening your pyramid like this:

```javascript
OpenSeadragon({
    ...
    tileSources:   {
        Image: {
            xmlns:    "http://schemas.microsoft.com/deepzoom/2008",
            Url:      "example-images/highsmith/highsmith_files/",
            Format:   "jpg", 
            Overlap:  "2", 
            TileSize: "256",
            Size: {
                Height: "9221",
                Width:  "7026"
            }
        }
    }
    ...
});
```
You will need to replace the different values with the ones you have in your dzi file.

**Comment by murbano89** [comment]
Dear Koen and avandecreme,

I appreciate the feedback and help!. avandecreme, placing the parameter directly into the index.html file (as you suggested) removed the cross-browser insufficiency (it opened in chrome, firefox, and IE splendidly). Any ideas why the dzi file is not acting as expected? Here is the dzi code:

<?xml version="1.0" encoding="UTF-8"?>
<Image xmlns="http://schemas.microsoft.com/deepzoom/2008"
  Format="jpeg"
  Overlap="1"
  TileSize="254"
  >
  <Size
    Height="48816"
    Width="58496"
  />
</Image>

I have tried formatting with both .dzi and .xml file extensions, but not change in ability to open on chrome. 

Again, my many thanks to both of you. - murbano

**Comment by avandecreme** [comment]
> Any ideas why the dzi file is not acting as expected?

My guess would be that Chrome developers decided to remove that flag entirely. I can't find anything confirming that though.
