### ISSUE TITLE
Gallery with thumbs

### ISSUE THREAD

**Issue by macdorli** [openseadragon/openseadragon#1037]
Can I make a page with a gallery with thumbnails that open up to full screen? There are some examples online? I do not know anything about javascript... :(

Thanks

**Comment by comrade2sun** [comment]
#### Moin
I am tinkering around with a image gallery plus thumbnail scroller.

Experimental example:
<a href="http://homepage.o2mail.de/nixneues/cojp/utamaro.html">Kitagawa Utamaro - Gallery</a>

I dont know if this is what you are looking for? 
Let me know if this might be helpful for you and/or I could provide you a better readable code with some comments. Just to make it easier for you _(or someone else)_ to dig through the code.

**Comment by macdorli** [comment]
Dear @comrade2sun  really well done, I'd try to use it. I waiting some indication. Thank you :)

**Comment by comrade2sun** [comment]
Hi macdorli

Just take a peek at the code of this version:

<a href="http://homepage.o2mail.de/nixneues/cojp/test.html">OSD Image Gallery - TEST</a>

The html-file contains the necessary JavaScript and dont forget to have a look at the "OSD-style.css". I hope,  the comments inside the code are understandable and make sense for you.

Keep in mind that I am not a programmer at all! 
This is still in early stage and needs a lot of improvement. So dont shoot me 🔫  (or blame your neighbor and kick his cat) if nothing works as expected.

If this is helpful for you, go ahead at your own risk.

**Comment by macdorli** [comment]
Sorry I was away from home, thanks I'll try and let you know. :)
