### ISSUE TITLE
Create an interface for providing tiles without using URLs

### ISSUE THREAD

**Issue by eriksjolund** [openseadragon/openseadragon#1038]
It would be good if OpenSeadragon would have an interface for
providing image tiles without the use of URLs. So something like

function getTile(level, x, y)

The function would return a canvas with the tile painted on it.
This interface would fit different use cases, such as remote
downloading (e.g. from SQL or byte ranges over HTTP) but also for
dynamically creating image tiles (for instance Mandelbrot fractals).

This idea was discussed here before:
https://github.com/openseadragon/openseadragon/issues/944#issuecomment-225698985
https://github.com/openseadragon/openseadragon/issues/944#issuecomment-225739869

**Comment by avandecreme** [comment]
We actually now sort of have something like this in [ImageTileSource.getContext2D](https://github.com/openseadragon/openseadragon/blob/master/src/imagetilesource.js#L190)
This API could certainly be improved but maybe that is already enough for your use case?

**Comment by eriksjolund** [comment]
Thanks, maybe it would work. 
Do you need to implement both
[ImageTileSource.getContext2D](
https://github.com/openseadragon/openseadragon/blob/master/src/imagetilesource.js#L190)
and
[ImageTileSource.getTileUrl](https://github.com/openseadragon/openseadragon/blob/master/src/imagetilesource.js#L176)
to use this interface?
Does every tile have to have its own unique URL?

**Comment by avandecreme** [comment]
You shouldn't need to implement `getTileUrl` (or just returning null should be enough).
