### ISSUE TITLE
[Feature Request] Allow for url redirect to determine image format

### ISSUE THREAD

**Issue by awagner-mainz** [openseadragon/openseadragon#1042]
Hi all,
I had a problem when the image of a legacy-image-pyramid would be delivered after content negotiation/redirection only. The problem was that OpenSeadragon did check the image format before the actual download and hence before the resolution of the redirection (with regexes on either the url/filename or the mimetype). Since the actual image was not known before content negotiation, I had neither a telling url nor a mimetype.

As a quick hack, when I made the filename check pass always - by simply changing the regex from "/^.\*\\.(png|jpg|jpeg|gif)$/" to "/^.\*$/" (without the quotes) -, it worked. I am not so sure that this is the way this should be handled. Maybe someone else has a more proper way.

If yes, this may be an improvement for a future version.

PS. I am not sure, maybe some backslash escapes in the regexes above got eaten by the styling...

**Comment by avandecreme** [comment]
I am not sure why we have this regex at all (link for the record: https://github.com/openseadragon/openseadragon/blob/master/src/legacytilesource.js#L208)
Let wait for @iangilman's opinion.

**Comment by iangilman** [comment]
Yeah, kind of doesn't seem like we need it... if we load a bad image, we'll get an error which we can handle, so we don't need to pre-vet the images.

@awagner-mainz Are you up for making a patch to remove it?

**Comment by awagner-mainz** [comment]
Uh. I have forked, branched, edited and committed a fix (https://github.com/awagner-mainz/openseadragon/commit/e50beb435bc3c2f00665600952a36895968de8f1). However, currently I don't have the time to go through the setup and testing steps. So I am reluctant to file a pull request.
Is it useful to you as is?

**Comment by iangilman** [comment]
@awagner-mainz Just making that a pull request should be fine... the tests will run automatically when you push it, and you shouldn't have to do any additional setup.

**Comment by iangilman** [comment]
Fixed by #1056. 

@awagner-mainz just a little PR feedback for you: it's good to mention the issue you're fixing in the description of your PR, so it's easier to close it once the PR is merged. :)
