### ISSUE TITLE
question: trigger function from two different custom buttons

### ISSUE THREAD

**Issue by michaelw3** [openseadragon/openseadragon#1044]
Hi everyone,
i'm trying to trigger the 'next' and 'previous' function to move to next image or prev. through two different buttons, one above the viewer and one one the side.
as you can see here - http://viewetest.kehilot.netai.net/
is there a way of accomplishing that?

thanks for any help!

**Comment by KTGLeiden** [comment]
Here you go: https://openseadragon.github.io/examples/ui-binding-custom-buttons/ ;)

**Comment by michaelw3** [comment]
@KTGLeiden is it possible to make two entry's in the same property i.e. -
 nextButton:    { "nextbutton1","nexrbutton2"},?
because i successed with one but not two

**Comment by KTGLeiden** [comment]
Ah, now I understand what you were asking ;)
It is actually pretty simple, if you are able to grab a hold of your viewer object:
viewer.goToPage(<PAGE>) should do the trick, and the current page number is requestable by viewer.currentPage().
Let me know if it worked!

~Koen

**Comment by michaelw3** [comment]
Yep!
works like a charm, thanks!
