### ISSUE TITLE
Question: Sequence mode "flicker"

### ISSUE THREAD

**Issue by harukizaemon** [openseadragon/openseadragon#1047]
When viewing pages in sequence mode, there is slight lag - which os understandable. The default behaviour is that the new page "fades in".

In my application this is less than ideal as users want to flick back and forth between pages to compare them. Instead, I have turned fading off so now there is a brief "flicker" while the old image is replaced with the new.

Is there a way to hold the existing page in place until the new page has loaded? This doesn't remove the lag, however it does remove the visual irritation of the flicker.

**Comment by adgoncal** [comment]
It sounds like you need some sort of double buffering. I am also interested in a way to do this.

**Comment by avandecreme** [comment]
This is unfortunately not possible at the moment but there is already a discussion about it there: #961
Would anyone of you be willing to implement such a plugin?
If so, please say so in #961.
