### ISSUE TITLE
Printing Overlays ?

### ISSUE THREAD

**Issue by davexp** [openseadragon/openseadragon#1049]
Hi Guys,
I hope this hasnt been covered or resolved elsewhere, if it is, please direct me to the link. I have tried to find a fix for it myself but havent been successful so far.

So i have followed instructions here
https://github.com/openseadragon/openseadragon/issues/477

And have been able to get my DZI image loading well. Also have a nice scalable SVG Translucent circle OVERLAY working. And zooming works well right to the point i need.

Im doing this

<pre>
viewer.addHandler('open', function() {              
                $("#btn_print").on("click", function() {
                                                            
                    var img = viewer.drawer.canvas.toDataURL("image/png");
                    //$("#themapcode").val(img);
                    $("#img-id").attr('src',img);
                    
                });             
});
</pre>

If i zoom the original Map and click the Print button, the resultant "#img-id", shows the correct png image but WITHOUT the OVERLAY.

What i want to do, is post the imgcode to another page which generates a PDF with the image in it.
That works but without the OVERLAY.

Is there some simple fix to this that I am missing ? Or will i have to Fix the images using "addSimpleImage" ? 

Any alternative options of getting the Map with Overlay converted to PDF would be appreciated.

Thanks

**Comment by avandecreme** [comment]
The SVG overlay is never drawn on the canvas.

Could your PDF generator blend the SVG and the canvas data URI?

**Comment by davexp** [comment]
All I am doing is passing the canvas data URI to a PHP HTML to PDF converter which converts the <img> tag to the image.
Is there a function to merge/blend the overlay into the canvas before posting ?

If not, I can try to attach a simple image of the overlay on the desired coordinates on the canvas or try to blend the overlay later as you suggest which might be harder to calculate where to put it.

Just wondering if there is a simpler solution already available before trying something else.

**Comment by davexp** [comment]
Will using a different type of overlay make any difference ? Like a PNG instead of SVG ?

**Comment by iangilman** [comment]
OSD doesn't have a mechanism for drawing the overlay directly into the canvas, so yes, you'll need to copy your overlay into the canvas before printing. I think there are mechanisms for rendering an SVG into a canvas, and yes, PNG would work as well. You could also use the canvas overlay plugin: 

https://github.com/altert/OpenSeadragonCanvasOverlay

...but you'd still have to copy that canvas into your canvas.  Anyway, some things to try...

**Comment by davexp** [comment]
Good to know. 
I'll have a fiddle around and see what I can turn up with.

Thanks
