### ISSUE TITLE
support for "zoom to 100%"?

### ISSUE THREAD

**Issue by nicolasfranck** [openseadragon/openseadragon#1051]
I haven't been able to find a control in the viewer or an event that allows to you
to zoom to "100%", although the API supports it:

```
viewer.viewport.zoomTo( viewer.viewport.imageToViewportZoom( 1.0 ) )
```

This should be handy: zooming to exactly 100% is often hard because a user does not know the zoom steps (e.g. 33% -> 66% -> 99% -> 132% )

**Comment by iangilman** [comment]
What are you asking for? Another button or something? 

Note that you can set `maxZoomPixelRatio: 1` on creation, and then when the user zooms all the way in they are at 100%. 

Another approach, if your app needs it, would be to have a zoom slider with 100% at one end.

**Comment by nicolasfranck** [comment]
I was indeed asking for an extra button next to the existing controls "zoom in", "zoom out" ..
There is already a "home button" that "fits to window", so "expand" would be a logical choice.
Basic image viewers have this button already.

But I think setting the maxZoomPixelRatio will do for the moment. 

Thanks!

**Comment by nicolasfranck** [comment]
Does the maxZoomPixelRatio override the maxZoomLevel restriction? I want users to be able to zoom to full width, but not beyond (which gives a stretched image in canvas).

Setting maxZoomLevel too low disables 100%,
but setting maxZoomLevel to e.g. 256 leads to zooming above 100%,
even with the maxZoomPixelRatio set to 1.0.

Any idea?

**Comment by iangilman** [comment]
Yes, maxZoomLevel overrides maxZoomPixelRatio; you should just leave it off and rely on maxZoomPixelRatio.

As for adding another zoom button, we want to keep the core OSD simple, but it's certainly possible to expand the toolbar with an additional button for your project. One could even make a plugin that does it.
