### ISSUE TITLE
Dropping irregularly shaped edge tiles

### ISSUE THREAD

**Issue by thejohnhoffer** [openseadragon/openseadragon#1052]
Hi all- there's an edge case that causes unexpected behavior in builds from the master branch after [TileSource :getTileAtPoint was changed on July 29.](https://github.com/openseadragon/openseadragon/commit/6f6207412c68d6111e96f303d037ad11378722a7#diff-3) **Reverting those changes  to `getTileAtPoint` are enough to eliminate the unexpected behaviors.** Those changes were originally made in [pull request 987](https://github.com/openseadragon/openseadragon/pull/987) in response to [issue 555](https://github.com/openseadragon/openseadragon/issues/555).

If the `tileSource` height and width are not integer multiples of the tileSource `tileSize`, each right or bottom edge `Tile` loads with height and/or width less than `tileSize`. This is the correct expected behavior. **After the July 29 fix, however, zooming the viewport inward toward any right or bottom edge `Tile` causes the `tileSize`-sized upper-left tiles to disappear completely.** 

For my custom `tileSource` of `tileSize: 512`, the error happens both for height and width 520 or 1250, but but not for 512 or 1024. The error only happens if the `tileSize` is not a factor of the height or width.

Here is my custom `tileSource:getTileUrl`
```
  function create_ts(z) {
      return {
            height: g_height,
            width:  g_width,
            tileSize: 512,
            minLevel: 0,
            maxLevel: Math.ceil(Math.log2(g_width/512)),

            getTileUrl: function( level, x, y ){

                return "http://" + server_name + "/data/?datapath=" + data_path +
                       "&start=" + x*512 + "," + y*512 + "," + z + "&mip=" + (this.maxLevel - level) +
                       "&size=" + 512 + "," + 512 + ",1";
            }
      }
  }
```

- Here is [my custom tileSource running on the master branch.](https://thejohnhoffer.github.io/2016-08-OSD-Diffs/index.html)
![bad](https://cloud.githubusercontent.com/assets/9781588/19564323/2c4ed444-96b1-11e6-9937-e9815df4b110.png)

- Here is [the same thing with changes to getTileAtPoint reverted](https://thejohnhoffer.github.io/2016-08-OSD-Diffs/fix0.html)
![good](https://cloud.githubusercontent.com/assets/9781588/19564321/291f0596-96b1-11e6-97c9-91b6eab28329.png)

**Comment by avandecreme** [comment]
I made yet another change to `getTileAtPoint` in #1006: https://github.com/openseadragon/openseadragon/pull/1006/files#diff-ed844244d3e5dcb6dfd56445d430efdaL347
Would you mind testing this implementation?

**Comment by thejohnhoffer** [comment]
@avandecreme -- Sure- I'll test the new implementation and post a new url.
- Here is [my custom tileSource running on the master branch.](https://thejohnhoffer.github.io/2016-08-OSD-Diffs/index.html)
- Here is [the same thing with changes to getTileAtPoint reverted](https://thejohnhoffer.github.io/2016-08-OSD-Diffs/index.html)

**Comment by iangilman** [comment]
Great to see this is fixed already (at least in an inflight patch)!

@avandecreme Does your change in #1006 still honor the fix to #555?

Should we add a test to cover this new case?

**Comment by avandecreme** [comment]
> @avandecreme Does your change in #1006 still honor the fix to #555?

Not yet, I will have a look this week end hopefully.
Yes, I think we should add test for this method.

**Comment by iangilman** [comment]
@avandecreme Cool, thank you :)

**Comment by avandecreme** [comment]
This should now be fixed in master. The wrapping should works as well.

**Comment by iangilman** [comment]
@thejohnhoffer Can you verify?

I'll close this issue assuming it's good, but if you find a regression we can open it again.
