### ISSUE TITLE
Not using Viewport Coordinates when calling addTiledImage

### ISSUE THREAD

**Issue by Edminsson** [openseadragon/openseadragon#1053]
I'm starting with fetching a iiif-resource - an info.json and then I call addTiledImage using the content of the info.json as the tileSource like this:

```
viewer.addTiledImage({
    tileSource: info,
    x: info.x,
    y: info.y,
    height: info.height,
    success: function(i) {
        console.log('BEFORE ',viewer.viewport.getBounds());
        viewer.viewport.goHome(true);
        console.log('AFTER ',viewer.viewport.getBounds());
    } 
});
```

In this case the height is not specified in Viewport Coordinates as the spec says, but in actual pixels. The outcome of the BEFORE console.log is in ViewPort Coordinates but not the second. The second seems to be in Image Coordinates. From now on you can use Image Coordinates when calling fitBound and it all seems to work.
Is this a feature or something that should be avoided?

**Comment by iangilman** [comment]
Good question! As mentioned here: 

http://openseadragon.github.io/examples/viewport-coordinates/

...viewport coordinates are arbitrary, and based on the height or width you give when adding the image, so if you choose to give the actual number of pixels as your height, then viewport and image coordinates will be the same. This is a fine choice.

**Comment by iangilman** [comment]
Well, technically it is in viewport coordinates... it just so happens that in your case you've chosen a viewport coordinate system that exactly matches your image coordinates. 

I understand all of these coordinate systems (especially one as flexible as the viewport coordinates) can be confusing!
