### ISSUE TITLE
How to Hide Part of Overlay behind TileSource and How to Change Overlay Text Size when Zoom

### ISSUE THREAD

**Issue by AliceBump** [openseadragon/openseadragon#1054]
Hi All,

I'm using openSeaDragon for a project and I'm facing some difficulties. The sketch is like this:
![overlay](https://cloud.githubusercontent.com/assets/8366607/19581440/d687768e-96e1-11e6-985c-61b2eebaa7d5.png)

I'm stuck by some issues:
1. I'm placing the tileSources by x, y which is the viewport coordinates. There should be some backgrounds for each tileSource. I'm thinking of use the overlay but it'll cover the images.
2. I need to put text label for each tileSource. I'm also thinking of use overlay. But the text size doesn't change when I zoom although the div element size get changed correctly.
3. *Optional problem. How can I get a navigator for each tileSource image when I zoom in and get the viewport filled with single image. Currently I only get the navigator for all the tileSources together.
Is it possible that I can get part of the navigator?

Any idea or suggestions would be great. Thank you.

**Comment by iangilman** [comment]
1. Do you need the backgrounds to zoom with the images? And you want them behind the images? If so, they should just be additional images that you place behind the foreground images.
1. If you want the text size to change as you zoom, consider using https://github.com/openseadragon/svg-overlay
1. We don't have a navigator that supports that, but the navigator is just a little OSD viewer... you can make your own that does what you want. Take a look at the navigator code for ideas: https://github.com/openseadragon/openseadragon/blob/master/src/navigator.js Incidentally, we'd love for the navigator to graduate to plugin status, and for there to be a variety of navigator plugins for different scenarios.
