### ISSUE TITLE
Problem Using Overlays and Openseadragon selection

### ISSUE THREAD

**Issue by PharaunMizzrym** [openseadragon/openseadragon#1058]
Hello All.
I'm using openSeaDragon for a project and I'm facing some difficulties.
The main idea of my project is use OpenSeaDragon to check out images. When the image has any failure, OpenSeaDragonSelection is used to select the part of the picture that contains the faillure. Then I'm trying to use Overlays Interface element to highligh the selected section but it isn't working.

This is the function that im trying to implement to resolve this issue:

[imageloader.txt](https://github.com/openseadragon/openseadragon/files/551729/imageloader.txt)

This is the ccs style where I reference the object "runtime-overlay"

`#runtime-overlay{
        outline-color: red;
        outline-width: 30px
      }`

I'll apreciate all your help, thanks in advance.

**Comment by iangilman** [comment]
In `addOverlay` I believe the `location` needs to be in viewport coordinates. In your example that should be a number between 0 (the left side) and 1 (the right side) horizontally and 0 (the top) and `height / width` (the bottom). For more information about viewport coordinates, see: 

http://openseadragon.github.io/examples/viewport-coordinates/

**Comment by PharaunMizzrym** [comment]
Thanks a lot for your response Ian. It worked for me changing the location to viewport coordinates and establishing an outline style on the css. I didn't notice that is mandatory if I want to draw the overlay.

Thanks a lot
