### ISSUE TITLE
Define the set of supported browsers

### ISSUE THREAD

**Issue by bgilbert** [openseadragon/openseadragon#106]
Without an explicit list, it's difficult to know which constructs are safe to use.

**Comment by julmot** [comment]
What's the current list of supported browsers?

**Comment by iangilman** [comment]
I guess we still haven't explicitly defined it. 2.3.0 was our last release with IE8 support. Based on https://caniuse.com/usage_table.php it seems we can skip forward to IE11, since 9 and 10 have less usage than 8 does. 

As for the other browsers, I figure the last few versions of the major ones seems reasonable. That said, it's probably good for us to be a little conservative, as OpenSeadragon is used by a lot of big institutions with a wide user base. 

From a practical standpoint, IE8 was the big one, since it was missing a lot of features. I'm not sure what the next feature is that we're hoping to take advantage of.

Anyway, it still would be good to make an official statement somewhere on the website...

**Comment by julmot** [comment]
> Anyway, it still would be good to make an official statement somewhere on the website...

Totally agree. From the point of view of my company we have a rule of browser compatibility that applies to all new projects and currently there's no other way to integrate OpenSeadragon it and hope that it works in the required browsers/versions 😄

**Comment by iangilman** [comment]
Just out of curiosity, what browsers does your company seek to support?

**Comment by julmot** [comment]
Let me quote (translated to English):

* The browser version of a manufacturer must have more than 25% spread of all versions of this manufacturer
* The total spread of the browser on the market must be min. 10%

Whereas these two links are the basis:

* https://www.browser-statistik.de/statistiken/
* https://www.browser-statistik.de/statistiken/versionen/

**Comment by iangilman** [comment]
Cool. Well, based on that, looks like you need to support Chrome, Firefox, and Safari; IE doesn't even make the cut (unless you lump it together with Edge, which you probably should). For the big 3 it looks like you need to support the two most recent versions, and for IE it's just 11, and for Edge it's the latest two versions. 

Although OpenSeadragon doesn't have an official page on this topic (beyond this issue), we definitely support a broader range than that, especially considering that we just recently dropped IE8.

**Comment by julmot** [comment]
> IE doesn't even make the cut (unless you lump it together with Edge, which you probably should)

Even though IE isn't included theoretically, I'm actively testing with IE11 to statisfy everyone ;-)

> especially considering that we just recently dropped IE8.

Good to know. Then I guess specifying at least the list of versions you've mentioned in the docs would be great, even if it probably supports more.

**Comment by iangilman** [comment]
Sounds good.

**Comment by pearcetm** [comment]
Any updates on which browsers are currently supported? Relates to https://github.com/openseadragon/openseadragon/pull/2282#issuecomment-1412712352

**Comment by iangilman** [comment]
@pearcetm Good question! I've started a new issue to discuss: https://github.com/openseadragon/openseadragon/issues/2286

Also, yeah, maybe we should actually take care of this issue and document the list somewhere!

**Comment by iangilman** [comment]
One nice thing for documenting which browsers we support would be if we include which versions we dropped certain browsers at (for instance, we dropped IE < 11 in 3.0.0 with https://github.com/openseadragon/openseadragon/issues/1863).

**Comment by iangilman** [comment]
I've added a note in the downloads section now (https://github.com/openseadragon/site-build/pull/278). I think at this point that's all we need.
