### ISSUE TITLE
Animate rotation

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/openseadragon#1060]
We should be able to animate both viewport and tiled image rotation.
There are some interesting discussion in #1006 about it.

**Comment by iangilman** [comment]
If possible it would be good to get this in (tiled image rotation at least) for the next release, since otherwise it would probably require an API change. Viewport rotation is already in, so it will likely need an API change somehow.

**Comment by iangilman** [comment]
Okay, image rotation now has animation! Viewport rotation animation can wait for later, since it's already in the API the way it is.
