### ISSUE TITLE
For certain image dimensions, some tiles are not rendered

### ISSUE THREAD

**Issue by Beechwell** [openseadragon/openseadragon#1065]
Hello,
this does not concern the current stable release, but the master-branch of OpenSeadragon.
Some IIIF-TileSources do not show the lower row(s) of tiles in the viewer if completely zoomed out. The same happens when zooming in at the bottom edge of the image.
sample code:
```
<div id="openseadragon"></div>
var viewer = OpenSeadragon( {
            id: "openseadragon",
            prefixUrl: "http://openseadragon.github.io/openseadragon/images/",
            tileSources: "http://digi.landesbibliothek.at/viewer/iiif/image/AC06735253_1927/00000037.tif/info.json",
        } );
```
The reason seems to be a rounding error in TileSource.getTileAtPoint(). For the bottom-right point of the image, point.y is ~10^-14 less than the inverse of TileSource.aspectRatio, and the "Fix for wrapping" yields
`Math.floor( point.x * this.aspectRatio ) = Math.floor(0.9999999...) = 0`
If I round both point.y and this.aspectRatio to 14 decimal digits it works - at least for the geometries I tried. But I haven't been able to figure out a better solution so far.

**Comment by iangilman** [comment]
I assume this is after #1006 landed? @avandecreme can you take a look?

**Comment by Beechwell** [comment]
> I assume this is after #1006 landed?

I checked out openseadragon-master to try out #1006. That's when I noticed it.
Thanks for taking a look at it
