### ISSUE TITLE
Maintain overlay sizes on screen while OSD zooming

### ISSUE THREAD

**Issue by bayucandra** [openseadragon/openseadragon#1067]
Hi, any idea how to maintain an object sizes on screen ( width & height ) for OSD overlay object while OSD is zooming in/out. For my case i am trying to keep Fabric JS object sizes on screen for the overlay.

What i have done is calculate a ratio of current OSD zoom level divided by the zoom level for 1:1 of image:viewport. And the result of those ratio used as denominator of a number that i just define, for example 500 or something. Here is the sample of code how i get the ratio for denominator:

`self.zoomRatio = event.eventSource.viewport.getZoom() / self.viewer.viewport.imageToViewportZoom(1);`

Thos `zoomRatio` i use as denominator for the sizes to produce new sizes of width & height.

As the result which is not really work well, i have a live demo at : [http://biqdev.com/demo/bfabric-polygon/](http://biqdev.com/demo/bfabric-polygon/) , there is a red rectangle which i hope it will maintain the width & height on the screen while OSD zoom in/out.

**Comment by iangilman** [comment]
It looks like you're using https://github.com/altert/OpenseadragonFabricjsOverlay correct? I think you don't need to change the size of your objects with that; I think it handles zooming and panning the fabric for you. Is that not the case? If you're having trouble with it, you might try asking the author (@altert) over at:

https://github.com/altert/OpenseadragonFabricjsOverlay/issues

**Comment by bayucandra** [comment]
Hi @iangilman , thank you for your response. The example i have made using FabricJs overlay, that is true. However, actually i am not having problem with zooming or fabric JS. Instead i am trying to make the overlay objects ( fabricJS, SVG or anything ) looks not zooming. In other word, i am trying to maintain the pixel sizes on screen based on OSD ratio.

Actually i will need to draw line on top of OSD which i hope it looks not zoom in/out when OSD zooming. It must be maintain the thickness when OSD zooming. Imagine when we drawing 'path' on Photoshop, the line will not zooming when we zoom the image. But for starting, i just playing with a simple object like Rectangle to maintain the size on screen.

Please let me know if you have an idea to achieve it. Thanks in advance.

**Comment by iangilman** [comment]
I see. Sounds like maybe you should put a canvas or SVG object on top of the viewer without connecting it to OSD at all.

**Comment by bayucandra** [comment]
You are right, actually i was put that way in my last option. However, since seem i can't get more idea it is now my only option :). Thanks a lot for your response.

**Comment by bayucandra** [comment]
Hi @iangilman i was imagine that i can copy events received by element above OSD. But seem i have problem. When user click on the element above OSD i have tried to using something like `$('#osd').trigger('click')` but seem it is not pass the event to the OSD canvas event. Actually it is only simple test, i need more to do with scroll and 'mousemove' event to 'drag' and 'zoom' the OSD image based on event received at the element above OSD.
Can you please kindly give your advice regarding this problem? thanks in advance.

**Comment by iangilman** [comment]
Do you just want the events to pass through? If so, use `pointer-events: none` on the elements above.

Otherwise, if you want to catch them sometimes or process them somehow, how are you catching them? Have you tried using MouseTracker? Are you making sure that you are catching them?

As for triggering a click on the OSD, I'm not sure what the best way would be. You might experiment with events like mousedown and mousemove. You also might need to construct your event properly. You could also try fiddling with the viewer's MouseTracker. You can also take a look at how we simulate clicks for our tests: 

https://github.com/openseadragon/openseadragon/blob/master/test/helpers/test.js#L8
