### ISSUE TITLE
Overlay Help

### ISSUE THREAD

**Issue by cmalexander** [openseadragon/openseadragon#1070]
Hello all,

I'm working on a project right now for a museum and I'm new to OSD. There is an interactive that uses OpenSeaDragon to zoom in on a very detailed map of the Belgium and the Netherlands in the 1600s. You can view it here: [http://web.stanford.edu/~cmalex/woel](http://web.stanford.edu/~cmalex/woel). I need to add an overlay on top of this map that shows the exact borders of the Dutch Republic )basically a line). Is there a way to add an overlay that uses a .dzi image? If so, where do I add it? Is this the best way to go? 

I currently have an image overlaying (not the one I will use in the end) added as a CSS background image. This is the code I currently have set up for OSD:

```
<script type="text/javascript">
    var viewer = OpenSeadragon({
        id: "openseadragon",
        prefixUrl: "scripts/images/",
        tileSources: 
        	"openseadragon/map.dzi",
        overlays: [{
            id: 'overlay',
            x: 0.20, 
            y: 0.50, 
            width: 0.2, 
            height: 0.25,
            className: 'highlight'
        }],
		zoomInButton: 'zoom_in',
        zoomOutButton: 'zoom_out',
        homeButton: 'reset',
		showNavigator:  true,
        navigatorPosition: "ABSOLUTE",
        navigatorTop:      "10px",
        navigatorLeft:     "10px",
        navigatorHeight:   "145px",
        navigatorWidth:    "125px",
   	 	visibilityRatio: 1.0,
    	constrainDuringPan: true
    });
</script>
```
Any help would be greatly appreciated!

Chris

**Comment by iangilman** [comment]
Cool project... I love the map!

Do you want the overlay to stay registered with the image and zoom and pan with it? Assuming so, you have a few options. You could add it as a separate image on top of the base image. If it's big, you could make it a DZI as well, or if it's small, you could use ImageTileSource. If it needs to have transparency, make it a png. 

If you just want some borders and you have them available as an SVG, you can add them with this plugin:

https://github.com/openseadragon/svg-overlay

Let me know if you need any help with the above suggestions. Also, when your project is done, we'd love to have it added to the list: 

http://openseadragon.github.io/examples/in-the-wild/

**Comment by cmalexander** [comment]
Hi Ian,

Thanks for getting back to me. Yes, I'd like for it to stay registered with the map. I'm making a large outline of the dutch republic in a photoshop layer over the map. Then I was going to save that image as a transparent png and convert it to a dzi. I'm just not sure how to add it as the dzi on top? 

I'd love to have it listed on your In the Wild page when it's done. 

Thanks for you help!

Chris

**Comment by iangilman** [comment]
Sounds good... I assume it's something you want to be able to turn on and off? Otherwise you could just bake it into your original DZI. 

For information about adding the second image, check out:

http://openseadragon.github.io/examples/multi-image/

**Comment by cmalexander** [comment]
Correct. Thanks! I'll check out the link and let you know if I have any questions.

**Comment by cmalexander** [comment]
Hi Ian,

Well, I was able to overlay the dzi on top of the image, but when zooming in it disappears (see link in initial email). Any thoughts? Also is there a way to tie a class or ID to the image to use CSS to hide and display that layer?

Thanks again for all the help! really appreciate it.

**Comment by iangilman** [comment]
The disappearing when it zooms in sounds like #1029. Are you on Safari? Have you tried with the latest OSD master? It looks like you've updated your code, as I don't see an overlay at all on it at the moment.

As for controlling the image visibility, it's all drawn in canvas so there's no CSS. Assuming it's the second image, you can make it invisible like so:

```
viewer.world.getItemAt(1).setOpacity(0);
```

**Comment by cmalexander** [comment]
Sorry, I was trying some stuff last night. The overlay is restored now, but it only shows when you zoom out a bit, but zoom in makes it disappear again. I am on Safari. So, if I'm reading the #1029  correctly setting the opacity to 1 should help? Or is there a way to go back to 2.1.0?

Thanks for the image visibility control.

**Comment by cmalexander** [comment]
A little more info. It works perfectly fine in Chrome - both images show up. I tried going back to previous versions and still couldn't get it to work in Safari. I want to try changing the opacity, but I'm unsure where to. Do I add it to viewer.addTiledImage?

**Comment by cmalexander** [comment]
Yay! Figured out how to compile the latest master and everything works now in Safari and iOS. Thanks for your help. Now I need to add the button to hide and show the outline. I'll let you know if I hit any other roadblocks.

**Comment by iangilman** [comment]
Excellent, glad you got it sorted out!
