### ISSUE TITLE
Hello opensedragoners! Voice control plugin

### ISSUE THREAD

**Issue by selko** [openseadragon/openseadragon#1072]
Hi all!

I´m really new on working here so a little help would be appreciated.

I´m working in a plug-in for openseadragon for voice control over the viewer.

https://github.com/selko/OpenseadragonVoiceControl

Thanks all this community for that great support!!!

Kind regards!

**Comment by iangilman** [comment]
Wonderful! What sort of help are you looking for?

When you're ready to share the plug-in more widely, you can make up will request here to add it to our list of plug-ins:

https://github.com/openseadragon/site-build/blob/master/www/index.html#L148

**Comment by selko** [comment]
If you try a demo in https://selko.github.io/ and then you select the micro button and then voice control. You can interact tell for example Go home. But i get some errors triyn callin to the function goHome().
By the other hand , sppech button works perfect

**Comment by iangilman** [comment]
For going home are you using `viewer.viewport.goHome()`? There is no plain `goHome()` exposed that's not attached to the viewport.
