### ISSUE TITLE
faster/more synchronous tracking on image drag

### ISSUE THREAD

**Issue by albell** [openseadragon/openseadragon#1077]
When I go to the home page, click on the church and zoom in, and then drag around a little bit, the canvas repaint always lags appreciably far behind where the current mouse delta is. I appreciate that you want to show smooth animated transition, but it just feels very laggy out of the box. I feel like modern users except something snappier. The position is always trailing the mouse position by a very noticeable amount. It's almost like a trailing effect.

Can this update duration be customized via the API? I've looked through the docs and it's not at all clear to me.

**Comment by seanich** [comment]
You can customise this by increasing the `springStiffness` property or decreasing the `animationTime` property in [OpenSeadragon.Options](http://openseadragon.github.io/docs/OpenSeadragon.html#.Options). Note, however, that this will also affect the zoom animation.

You can accomplish this effect for panning only setting `flickEnabled` to `true` and `flickMomentum` to 0 for your desired input device. Leaving the `flickMomentum` at the default of 0.25 creates a nice momentum effect after releasing the mouse (similar to Google Maps).

**Comment by albell** [comment]
Thank you for the quick reply.

I feel like the question of inertial scrolling (aka "momentum") and the lag I'm describing are possibly separate issues. One concerns what happens after a user drag ends (a residual velocity). The other deals with a position lag on the canvas refresh _during_ a drag.

Agreed that Google Maps is a great model for this sort of thing. As with GM, I'd like to have:

- brisk animated transition transitions on click zoom
- synchronous repaint on pinch zoom with minimal lag
- inertial panning/scrolling, but with with strong drag coefficient so that things don't go flying
- No trailing effect during a pan/drag

It unfortunately sounds like I can't have all of these simultaneously. Am I understanding correctly?

**Comment by seanich** [comment]
With the settings below I achieve a similar feel to Google Maps on my system. I experience about the same lag behind the mouse cursor while dragging as I do with Google Maps. The inertial panning effect can be given a stronger drag coefficient by reducing the `flickMomentum` property from its default of 0.25.

I also experience minimal lag with pinch to zoom when tested on my phone.

```javascript
var myViewer = OpenSeadragon({
  gestureSettingsMouse: {
    flickEnabled: true,
    clickToZoom: false,
    dblClickToZoom: true
  },
  zoomPerSecond: 0.5,
  zoomPerScroll: 1.3
});
```

**Comment by albell** [comment]
Thanks for the recipe. That is a bit closer to the mark.

I respectfully but strongly disagree with your characterization of these as being "about the same". Pan on drag in Google Maps does not have any perceptible delay. Here's a GM screen recording, made just now. Jerky, quick drag/pans are instantaneous. There is no trailing. I think this is what modern users expect in a panning program. Zooms should be transitioned, pans should not. Get the interface to reflect the latest pointer location, as immediately as possible, in all cases.

[GM-screen-recording.mov.zip](https://github.com/openseadragon/openseadragon/files/584468/GM-screen-recording.mov.zip)

I'm pushing on this because lag time is a really big deal in terms of user experience. Graphics engineers go to insane lengths to reduce touch drag latency by ~5%, the bar has been raised to 60fps everywhere, and milliseconds matter. Playing with a touch screen that lags behind the pointer is a totally different experience from playing with one that doesn't. Lag time is the enemy. Deliberately building lag time into a panning interface is to me just nuts. I know my client is going to object to this during QA, and I'm hesitant to go down this road on a project knowing that zoom/pan transitions are tightly coupled, and there isn't going to be an easy way to fix one without breaking the other. I hope this feedback is helpful to you.

I want to be able to have transitioned click-zoom events without introducing any lagging effect on pan/drag. What's more, I think this should be the default setting. If there's no way to do this currently, please consider it a feature request?

**Comment by seanich** [comment]
Could you record a video of the behaviour you see with OpenSeadragon using the settings I provided? On my system panning behaves exactly as it does in Google Maps with the settings I provided. 

When `flickEnabled` is set to true there is no animation or "lag time" added to the panning. You can see this for yourself by tracing the execution path from the drag event handler [here](https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2545). This is the default behaviour on touch screens for the reasons you stated (see #357). `flickEnabled` also has no effect on zoom animations, so it is an easy way to fix panning without breaking zoom.

If you are experiencing lag with these settings then it is a performance issue rather than a design issue.

I also prefer the immediate response of GM to the default settings of OSD, which is why I use the settings I described in my own projects. However, since this desired behaviour is easily accomplished by tweaking a couple options I don't see a reason to change the defaults. 

Perhaps @iangilman or another core contributor could weigh in on this?

**Comment by albell** [comment]
Wait.. I'm confused... `flickEnabled` is `false` by default according to the docs. But I see dramatic inertial scrolling on the <a href="http://openseadragon.github.io">home page</a>, which says it is configured using the default settings, when I do quick, jerky pans with a mouse. Here's a screen recording.

[lagging-on-home-page.mov.zip](https://github.com/openseadragon/openseadragon/files/584599/lagging-on-home-page.mov.zip)

Am I misreading the terminology? Why am I seeing flick behavior if it's disabled?

Is there a live site where I can see your settings above in action? Or demo page somewhere in a public repo? I haven't built a project yet, I'm still just researching viewers.

**Comment by seanich** [comment]
Sorry, I may have been a bit unclear. `flickEnabled` is false by default for mouse input, but it is true by default for touch input. If you try out the demo on the home page on a touch device you will see the difference.

Here's a quick demo with those settings applied to mouse input as well: http://output.jsbin.com/hikekaroxa

**Comment by albell** [comment]
Ah. Much better. Thank you very much for your patience!

+1 for those JSBIN settings being the future default. This was not obvious (to me personally, at least), and I can't think of any use case when the current default behavior would be better.

**Comment by seanich** [comment]
No problem! Glad I could help :)

Regarding the default settings I have seen arguments for both sides, so it might be worth opening an issue to get a discussion going if you'd like to do that.

**Comment by albell** [comment]
ok, opened #1078 for future discussion.
