### ISSUE TITLE
RELOAD TILESOURCE

### ISSUE THREAD

**Issue by selko** [openseadragon/openseadragon#1082]
I have a basic question. If i loaded an image in tileSources, is there a function to reload tileSources with other image to change the image in the viewer?
THx

**Comment by michaelw3** [comment]
you could use `viewer.close()` to unload all existing images and then `viewer.open(tileSourceArray)`

**Comment by makoychan** [comment]
Hi can this work on .jpg? i am trying to reload but my files are jpg, i followed the steps here but its not working

**Comment by iangilman** [comment]
@makoychan I've answered your question here: https://github.com/openseadragon/openseadragon/issues/587#issuecomment-380243339
