### ISSUE TITLE
Some problems handling failed attempt with Cantaloupe image server

### ISSUE THREAD

**Issue by devanonyme** [openseadragon/openseadragon#1086]
I dont have all the information on this one  or easy reproducible steps) but here is an overview of the problem I had :

While working / testing with an integration with Cantaloupe Image server we had a few unexpected errors (my coworker opened a issue here : https://github.com/medusa-project/cantaloupe/issues/74). I noticed that there where scenarios where the json descriptor file was returned in error and OpenSeadragon was reusing the version from client cache (the failed one) so the the solution I was planing to use to recover was not usable (do a reopen on open failed event for x attemp by exemple). I'm not 100% if client cache is from the ajax request settings or caused by cantaloup that should not return cache header in case failed request.

The secondary type of error was likely related (bad answer from Cantaloupe)  but was not on descriptor level but more on the image level (empty image response?). In that case, the last time I checked I had the impression that there was no simple way to force a a new load attemp at the tile level.

Should OpenSeadragon be able to do these reattemps or it is assumed that it is context specific and we should handle it in the integration code?

**Comment by iangilman** [comment]
OSD doesn't have a retry mechanism, but you can probably hack it in. To get around the browser cache, you could add some cache busting (e.g. `?foo=1234`) to the URLs (assuming your server will just ignore the extra URL params). In the case of the descriptor file, you can look for the `open-failed` (or `add-item-failed` if you're doing multi-image) event and re-add the image with a cache-busted URL. In the case of tiles, look for the `tile-load-failed` event and update the tile's URL and reset its "tried but failed" flags. I don't know the details, but that's the general idea.

**Comment by devanonyme** [comment]
Thanks! Yes, using bust cache would definitively help in that case, I should have tought about this one. I will give a second look when I work again on this. We have decided to keep getting the main image from Cantaloupe but to get secondary images (thumnails) from the current existing system (pre-generated thumnails), the failed load are less an issue now (but I still think it would be more user friendly to have a least one automatic retry).

**Comment by devanonyme** [comment]
#https://github.com/medusa-project/cantaloupe/issues/84
