### ISSUE TITLE
Looking for some guidance

### ISSUE THREAD

**Issue by rtomkins** [openseadragon/openseadragon#1092]
I am having some difficulty moving from version 1.1.1. to 2.2.1.

I dropped version 2.2.1 onto my website and there were problems.

1. The defaultZoomLevel no longer increased the size of the image to fill the viewer when the page loaded.
2. The wrapHorizontal gets stuck at a fixed point in the image, I can scroll further but when I release the mouse button the image springs back.
3. Here is the website, http://neuron-tech.ca/osd/osd.html - working 1.1.1 version
4. I feel like I missed a critical change somewhere between the two versions and I cannot figure out what it is.

 

This is the JavaScript in my HTML 1.1.1.

<script type="text/javascript">

function init() {
	
	var viewer = new OpenSeadragon({
	id: "openseadragon1",
	prefixUrl: "/img/",
	tileSources: ["/GeneratedImages/dzc_output.xml"]
	});
	
	viewer.wrapHorizontal = true;
	viewer.autoHideControls = true;
	viewer.constrainDuringPan = true;
	viewer.minZoomImageRatio = 0.7;
	viewer.controlsFadeDelay = 1500;
	viewer.controlsFadeLength = 1000;
	viewer.visibilityRatio = 0;
        viewer.defaultZoomLevel = 4;
    	};
	OpenSeadragon.addEvent(window, "load", init);
</script>

**Comment by rtomkins** [comment]
I have set up a demonstration of the problem. Same source image tiles, same HTML, only the OpenSeaDragon library version is different.
http://neuron-tech.ca/osdprob/osd111.html - good version
http://neuron-tech.ca/osdprob/osd210.html - bad version
http://neuron-tech.ca/osdprob/osd221.html - bad version

In the bad versions, the initial image load is too short and I cannot get it to go bigger and the continuous horizontal scroll does not work.

**Comment by iangilman** [comment]
Looks like the problem is setting the viewer options after creation, rather than during creation. This fixes your issues: 

```
viewer = new OpenSeadragon({
  id: "openseadragon1",
  prefixUrl: "img/",
  tileSources: ["GeneratedImages/dzc_output.xml"],
  wrapHorizontal: true,
  autoHideControls: true,
  constrainDuringPan: true,
  minZoomImageRatio: 0.7,
  controlsFadeDelay: 1500,
  controlsFadeLength: 1000,
  visibilityRatio: 0,
  defaultZoomLevel: 4
});
```

Interesting that setting the options afterwards worked in 1.1.1! 

Here's a codepen with the fix in action:

http://codepen.io/iangilman/pen/PbLpdy?editors=0010

**Comment by rtomkins** [comment]
The problem demonstration on my website has been removed as the guidance/solution presented by Ian works like a charm.
Thank you for pointing out what I did wrong and how to fix it.

**Comment by iangilman** [comment]
Happy to help... glad that fixed it :)

**Comment by leesei** [comment]
I suppose this can be closed?

**Comment by rtomkins** [comment]
Yes, this issue can be closed. I don't know how that is done, but I figured that be thanking someone for their guidance would effectively indicate the issue had been resolved.
Will the text remain here for use by folks in the future with the same question?

**Comment by leesei** [comment]
Either you or the admin should see an "Close" button.
Yes, this issue is still searchable.
