### ISSUE TITLE
iOS dissappearing png in collection mode

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#1093]
I've found a strange issue with displaying a png tilesource (with transparency) in collection mode.

The tilesource will blink out during zooming or panning. But not if it's in the first position.

I built a demo here that loads 6 png tilesources, then you can select other options showing how jpg tilesources don't behave that way.

[http://deepzoomchattanooga.com/plainvanillatest](http://deepzoomchattanooga.com/plainvanillatest)

This only happens on an iPhone or iPad, and only if a png is not loaded first.

Any ideas on the cause and a way to avoid this behavior?  Thank you.

**Comment by iangilman** [comment]
Sounds similar to the issue fixed by #1035, which affected Safari as well as IE. Can you build the latest master from this repository and try that?

**Comment by SamHall** [comment]
Forgive my lack of Github savviness - is the the same as a pull request?
I'm on Windows and have the Github desktop client available with the project cloned.

**Comment by iangilman** [comment]
No, not like a pull request (where you contribute new code)... I'm just suggesting you grab the latest code, build it, and try it in your project. If you've already got it cloned, that's the first step. Make sure you pull the latest (I think that's "sync" in the desktop client) and that you're on the master branch, then check out the "first time setup" and "building from source" sections of:

https://github.com/openseadragon/openseadragon/blob/master/CONTRIBUTING.md

Once it's built, you can find openseadragon.js in the `build/openseadragon` folder. You can grab that and drop it into your test project. 

Let me know if you have trouble along the way!

**Comment by SamHall** [comment]
Happy to report I managed to build from source and tested on the previously shared link.
It appears to resolve the issue.

THANK YOU!

**Comment by iangilman** [comment]
Excellent, good to hear! Thank you for confirming. :)
