### ISSUE TITLE
Where are the other images from?

### ISSUE THREAD

**Issue by rtomkins** [openseadragon/openseadragon#1095]
I am looking at the following web page, https://openseadragon.github.io/examples/ui-reference-strip/.
In looking at "Horizontal Scrolling Image Reference Strip", I see 13 different images, as I scroll the strip.
Looking at the page source, I can see 7 image references, that collectively cover only the first two images on the "Horizontal Scrolling Image Reference Strip", one of these is a gif, why? and where do all the remaining images come from, 11 different images in total are missing from the JavaScript for the use of OpenSeadragon?
Thank you in advance for helping me to understand this.

**Comment by iangilman** [comment]
OpenSeadragon can open a variety of tiled image formats. When you give it a `tileSources` array, it can be a mixture of any of those formats. In the case of the examples on that page, for some reason we're using both LegacyTileSource and DziTileSource. The LegacyTileSources are specified inline, whereas the DziTileSources are just URLs. Here's the code (starting at line 85 of that page's source):

```
tileSources:    [{
    type: 'legacy-image-pyramid',
    levels:[{
        url: '/example-images/rbc/rbc0001/2003/2003rosen1799/0001q.jpg',
        height: 889,
        width:  600
    },{
        url: '/example-images/rbc/rbc0001/2003/2003rosen1799/0001r.jpg',
        height: 2201,
        width:  1485
    },{
        url: '/example-images/rbc/rbc0001/2003/2003rosen1799/0001v.jpg',
        height: 4402,
        width:  2970
        
    }]
},{
    type: 'legacy-image-pyramid',
    levels:[{
        url: '/example-images/rpbaasm/0900/0908/090801t.gif',
        height: 150,
        width:  116
    },{
        url: '/example-images/rpbaasm/0900/0908/090801q.jpg',
        height: 400,
        width:  310
    },{
        url: '/example-images/rpbaasm/0900/0908/090801r.jpg',
        height: 860,
        width:  667
    },{
        url: '/example-images/rpbaasm/0900/0908/090801v.jpg',
        height: 1650,
        width:  1279
        
    }],
},
    "/example-images/highsmith/highsmith.dzi",
    "/example-images/pnp/ppmsca/05900/05954/05954.dzi",
    "/example-images/pnp/ppmsca/05900/05954/05955.dzi",
    "/example-images/pnp/ppmsca/05900/05954/05956.dzi",
    "/example-images/pnp/ppmsca/05900/05954/05957.dzi",
    "/example-images/pnp/ppmsca/05900/05954/05958.dzi",
    "/example-images/pnp/ppmsca/05900/05954/05959.dzi",
    "/example-images/pnp/ppmsca/05900/05954/05960.dzi",
    "/example-images/pnp/ppmsca/05900/05954/05961.dzi",
    "/example-images/pnp/ppmsca/05900/05954/05962.dzi",
    "/example-images/pnp/ppmsca/05900/05954/05963.dzi"
]
```

As you can see, the first LegacyTileSource consists of three JPEGs, each bigger than the next. The second LegacyTileSource has four tiles, the first one a GIF and the others JPEGs. I don't know why this would be, except that that's just how the sample tiles were encoded in this case. At any rate, OpenSeadragon doesn't mind if you mix file types like that. 

Does that answer your question?

**Comment by rtomkins** [comment]
There are thirteen different images in the first strip in the top viewport.
The three .jpg and then the single .gif and three more .jpg URLs account for only the first two images in the viewport.
I want to know where the remaining eleven different images come from.
When I navigate to the dzi files, save them and then open them with an editor, I don't see any image references or URLs in the DZI files.

**Comment by iangilman** [comment]
Each of the thirteen images is not just a single image file, but a "tiled image"... each image has been broken up into multiple tiles, and each tile is saved as a separate image file. In the case of the first image, there are just three tiles, specified right there. In the case of the second image, there are four tiles. All the remaining images are in DZI format. That format specifies an XML file (with the .dzi extension, though .xml is accepted) that tells OpenSeadragon about the structure. The format also specifies where to find the tiles: in a folder next to the .dzi file. In the case of the third tiled image in the example (http://openseadragon.github.io/example-images/highsmith/highsmith.dzi) the tile folder is at:

http://openseadragon.github.io/example-images/highsmith/highsmith_files/

That folder is further broken down into numbered folders for tile level, and inside of each of those are a number of individual image files (the individual tiles). You can explore this structure in the example-images repository (in its gh-pages branch):

https://github.com/openseadragon/example-images/tree/gh-pages/highsmith/highsmith_files

The same goes for the remaining 10 files specified above.

If you'd like to learn more about the DZI format, this page has a lot of info:

https://msdn.microsoft.com/en-us/library/cc645077(VS.95).aspx

**Comment by rtomkins** [comment]
I knew that, "NOT!", he says sheepishly. Thank you for dragging me into the light.
I realize now that there is a deeper level of understanding I had entirely failed to follow.
This information and the Microsoft link should go a long way to a better understanding by me.
Many thanks again.

**Comment by iangilman** [comment]
Happy to help :)
