### ISSUE TITLE
2 instances of zoom images

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1105]
HI . is it possible to add 2 seadragon object to the page and control  the zoom on both from any of them.
 
so any object will be affect accordingly from the controls or external controls.
there are any examples for that? 

thx a lot

**Comment by avandecreme** [comment]
Hi, yes this is definitely possible but there is no code available as far as I know.
Ideally, this could be implemented as some sort of plugin.

Anyway, you should have all the infos on how to implement this in https://github.com/openseadragon/openseadragon/issues/213.

**Comment by johnico** [comment]
I managed to do something like the following and its working for on of the canvas and affect on the second viewer  :

```
      	viewer1.addHandler("animation", function() {

          					viewer2.viewport.zoomTo(viewer1.viewport.getZoom(true),true);
          					viewer2.viewport.panTo(viewer1.viewport.getCenter(true),true);


            });

```
but if i add the same for the second viewer  they will stuck together 

any suggestion how can I solve it ?

**Comment by iangilman** [comment]
Good point. Well, I don't know if this is the best technique or not, but this is what comes to mind:

```
var viewer1Leading = false;
var viewer2Leading = false;

viewer1.addHandler('zoom', function() {
    if (viewer2Leading) {
        return;
    }

    viewer1Leading = true;
    viewer2.zoomTo(viewer1.getZoom());
    viewer1Leading = false;
});

viewer2.addHandler('zoom', function() {
    if (viewer1Leading) {
        return;
    }

    viewer2Leading = true;
    viewer1.zoomTo(viewer1.getZoom());
    viewer2Leading = false;
});
```

Of course you'd want to do the same for pan as well.

**Comment by johnico** [comment]
thx
I got maximze call stack error

i tried this but the zoom is stuck (only 1 handle works for 1 of the zoom)

`             var viewer1Leading = false;
             var viewer2Leading = false;

          	viewer1.addHandler("animation", function() {
                  if (viewer2Leading) {
                       return;
                   }
                   viewer1Leading = true;

          					viewer2.viewport.zoomTo(viewer1.viewport.getZoom(true),true);
          					viewer2.viewport.panTo(viewer1.viewport.getCenter(true),true);
                    viewer1Leading = false;

            });
            viewer2.addHandler("animation", function() {
                  if (viewer1Leading) {
                       return;
                   }
                   viewer2Leading = true;

                    viewer1.viewport.zoomTo(viewer2.viewport.getZoom(true),true);
                    viewer1.viewport.panTo(viewer2.viewport.getCenter(true),true);
                    viewer2Leading = false;

            });`



how can i fix it ? even dirty for now
thx

**Comment by johnico** [comment]
I got the error with your and my code :) @iangilman

**Comment by iangilman** [comment]
Okay, now that I've actually tried my code, looks like there are a few mistakes, most notably forgetting to add `viewport`. Also I've gone ahead and added in pan support. Here's a working prototype:

http://codepen.io/iangilman/pen/BpwBJe

**Comment by johnico** [comment]
thx a lot , Im using it in angular directive but for 1 images it still working  so i am not sure its matter

here is my code: 


Uncaught RangeError: Maximum call stack size exceeded
    at a.Viewport.zoomTo (viewport.js:835)
    at Object.viewer2Handler [as handler] (directive.js:51)


`          var tileSource={
                type: 'image',
                url:  img url,
          }
          console.log(scope.$parent.vm);
          var tileSource2 ={
            type: 'image',
            url:  img2 url,
          }

          viewer1.open(tileSource);
          viewer2.open(tileSource2);



          var viewer1Leading = false;
          var viewer2Leading = false;

          var viewer1Handler = function() {
            if (viewer2Leading) {
              return;
            }

            viewer1Leading = true;
            viewer2.viewport.zoomTo(viewer1.viewport.getZoom());
            viewer2.viewport.panTo(viewer1.viewport.getCenter());
            viewer1Leading = false;
          };

          var viewer2Handler = function() {
            if (viewer1Leading) {
              return;
            }

            viewer2Leading = true;
            viewer1.viewport.zoomTo(viewer2.viewport.getZoom());
            viewer1.viewport.panTo(viewer2.viewport.getCenter());
            viewer2Leading = false;
          };

          viewer1.addHandler('zoom', viewer1Handler);
          viewer2.addHandler('zoom', viewer2Handler);
          viewer1.addHandler('pan', viewer1Handler);
          viewer2.addHandler('pan', viewer2Handler);`

**Comment by Medwar** [comment]
Big thanks from me as well, for both the question and the answer!  I tried to invent exaclty the same myself for several evenings, but failed.  A very useful feature indeed.
