### ISSUE TITLE
Navigator not updated on Rotating Tiles in Collection mode

### ISSUE THREAD

**Issue by sandyrao** [openseadragon/openseadragon#1106]
I am trying to get the enhancement working for Rotation & collection mode #978 . Works great, but the image in the navigator do not rotate along with the image at the Viewport.

**Comment by avandecreme** [comment]
Yes, I fixed that in #1100 which is still work in progress.
You can cherry-pick the relevant lines from navigator.js here: https://github.com/openseadragon/openseadragon/pull/1100/files

**Comment by iangilman** [comment]
#1100 has landed.
