### ISSUE TITLE
Keep zoom while change image

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1107]
Hi  onclick event I do smth like this: 

     var tileSource2={
        type: 'image',
        url:  'img url',
    	}
	  viewer2.open(tileSource2);

how can I keep the zoom params before I use open tileSource ?  so how I make the "new image" start from the same zoom
thx a lot for the awesome plugin

**Comment by iangilman** [comment]
Include `preserveViewport: true` in your options when creating the viewer, and it should leave the zoom and pan alone when you open new images.

**Comment by iangilman** [comment]
Yeah, `preserveViewport` is a property of `OpenSeadragon.Viewer` so you can flip it on and off whenever you want just with `viewer.preserveViewport = true` or whatever.

**Comment by johnico** [comment]
wow! thx its working
