### ISSUE TITLE
Remove bounds but keep the pan functionality

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1110]
How can I remove the bounds - i mean that the user will not be able to play with the image and move the image between the white spaces, and the image will be at the middle or take the div place
I m using simple image url 

In addition I'd like to keep the ability to use the pan with the mouse 

thx for amazing library again

**Comment by iangilman** [comment]
I'm not quite sure what you're asking for. Do you mean you want to allow the user to drag the image off of the viewer? Or do you mean you don't want them to drag it at all when it's zoomed out? Or do you mean you want less white space to appear around the image when it's zoomed out?
