### ISSUE TITLE
Double simple image in newest openseadragon version

### ISSUE THREAD

**Issue by jetic83** [openseadragon/openseadragon#1113]
Seems to be a bug:
I updated my openseadragon.min.js and grunted it. Then I experienced that my OSD shows double images when the tilesource is a simple image (sometimes even quadro-images). The image is then just repeated left of the original image.

See the plunk as an example: use the "local" openseadragon.js which is a current grunt of openseadragon and which has the error. Use the "http://... openseadragon.js" which works fine.

http://plnkr.co/edit/4EVUN0Zq3yMIU9k4tEVp?p=preview

**Comment by iangilman** [comment]
Good catch! 

@avandecreme Any theories? Seems like it might have something to do with the fixes that relate to image wrapping?
