### ISSUE TITLE
Show cropped tilesource

### ISSUE THREAD

**Issue by radpet** [openseadragon/openseadragon#1114]
Hello, is there a way to effectively show only part of given tilesource. I checked the API but did not find anything useful for the moment. I want to draw only a portion of the whole tilesource, but don't want to have the cropped image as static overlay.

**Comment by iangilman** [comment]
Have you tried TiledImage.setClip()? 

http://openseadragon.github.io/docs/OpenSeadragon.TiledImage.html#setClip

**Comment by radpet** [comment]
Seems as a solution, I haven't tried it yet. Thank you!

**Comment by kaij** [comment]
Is there a performance penalty when using setClip (e.g. on mobile devices)? The documentation mentions canvas, which might be an expensive operation for very large images.

I'd like to show a cropped image from a IIIF2 server and thought it might merely need some coordinate tweaking on the request of the IIIF tiles. Or is there a good way to implement this functionality?

**Comment by avandecreme** [comment]
If you are using a pyramid tile source (which I believe IIIF2 is), only the tiles within the clip are fetched and rendered. So there should be no performance penalty.

It seems to be exactly the functionality you are looking for.

**Comment by iangilman** [comment]
Actually, I don't think we're taking the clip into account when deciding which tiles to load. Because of this, the performance should be the same as if you weren't clipping at all.

As for Canvas, we use it regardless of whether you're clipping, but we only draw the pixels you need, so it's efficient even for giant images.

**Comment by avandecreme** [comment]
This line should prevent unnecessary tiles to load I believe: https://github.com/openseadragon/openseadragon/blob/master/src/tiledimage.js#L932-L933
I just checked and it is also available in the latest release.

**Comment by kaij** [comment]
Thanks for the clarification. Sounds good, I'm going to give this a try.

**Comment by iangilman** [comment]
@avandecreme Good point! Thank you for pointing that out :) I stand corrected...

**Comment by robhicks** [comment]
I can't get setClip to work. 

If anyone wants to help me understand why, here's a [plunk](https://plnkr.co/edit/wrHrYhNsItlKNuCYcUfz?p=preview) showing my attempt. It will need to be run in Chrome or Safari. 

In the plunk, I attempt to set the clip to half of the size of image (viewport coordinates).

**Comment by iangilman** [comment]
@robhicks `setClip` uses image coordinates, not viewport coordinates (I believe the documentation mentions that, but maybe it's too subtle). You want something like this:

```
const imageSize = this.tiledImage.getContentSize(); // this is in image coordinates
const rect = new OpenSeadragon.Rect(0, 0, imageSize.x / 2, imageSize.y / 2);
this.tiledImage.setClip(rect);
```

**Comment by robhicks** [comment]
@iangilman Thanks! You're right it does say image pixels, now that I read it again. Maybe we could add: Hey Rob, it really is image pixels, not viewport coordinates to the docs. :blush:

**Comment by robhicks** [comment]
@iangilman Is is possible to clip an image and then center and zoom the clipped area? I have tried:
```
tiledImage.setClip(rect);
tiledImage.fitBounds(tiledImage.getClippedBounds());
```

**Comment by iangilman** [comment]
That certainly seems like it should work... I assume it doesn't? What does it do instead?

**Comment by robhicks** [comment]
It doesn't do anything. Here's a [plunkr showing the attempt](https://plnkr.co/edit/wrHrYhNsItlKNuCYcUfz?p=preview).

**Comment by iangilman** [comment]
Oh, I see the mistake... It should be `viewer.viewport.fitBounds` not `tiledImage.fitBounds` (assuming your Viewer is called `viewer`).

**Comment by robhicks** [comment]
Ok, thanks! I updated the plunkr and it works great.
