### ISSUE TITLE
Preventing zoom on click?

### ISSUE THREAD

**Issue by intelcoder** [openseadragon/openseadragon#1115]
I would like to disable zoom in on click on some conditions. 

I tried to prevent zoom in with click event listeners with 
```
 e.preventDefault();
 e.stopPropagation();
 e.stopImmediatePropagation();
```
However, it did not stop event.
I know clickToZoom can disable click event but it disables permanently I believe.

**Comment by iangilman** [comment]
Do you know before the click whether you want the zoom disabled? If so, one trick is to say `viewer.zoomPerClick = 1` when you want it disabled and `viewer.zoomPerClick = 2` when you want it enabled.

**Comment by intelcoder** [comment]
Thanks but I need to disable zoom after click. Currently, it zoom-in when overlay is clicked, which I do not want to do.
And clicking the overlay opens up side window and close on clicking outside of side window. 
I would like to prevent clickToZoom when side window is open.

I know I can prevent those zoom in with OpenSeadragonViewerInputHook plugin but I feel its overkill to have plugin just for one function.

**Comment by iangilman** [comment]
Take a look at this example for the overlay click:

http://codepen.io/iangilman/pen/mEkKaY

...and then when the side window is open you can prevent the click to zoom with the `zoomPerClick` trick.

**Comment by intelcoder** [comment]
This is the way I used

```
this.viewer.gestureSettingsMouse.clickTo
Zoom
```

**Comment by iangilman** [comment]
Cool, that works too. :)

**Comment by intelcoder** [comment]
Thank you for providing example !!

**Comment by danomatika** [comment]
I'd suggest adding this as one of the official examples on the OSD website. After doing some searching and trying a couple things out, this was the exact answer for what I needed.

**Comment by iangilman** [comment]
Yeah, there is so much info it's hard to know how to make it best available to answer people's questions! Any thoughts on where it should go?

**Comment by danomatika** [comment]
@iangilman I think the [Overlays example section](https://openseadragon.github.io/examples/ui-overlays/) of the website works. That's where I first looked. I see now the "Overlaying Complex HTML" example has the event handler, so it's partially showing this but for a slightly different use case. Maybe this could be a simpler example beforehand showing overlay click events.

**Comment by iangilman** [comment]
Cool, it makes sense. BTW, with https://github.com/openseadragon/openseadragon/pull/1872 coming we may not need to document the overlay click workaround, since it may be no longer necessary.
