### ISSUE TITLE
How to restrict zoom out area

### ISSUE THREAD

**Issue by intelcoder** [openseadragon/openseadragon#1118]
I have a horizontally long image and I am trying to zoom out programmatically using panTo and zoomTo. However, I do not want to see the black area which is outsize of contents.
I can move to centerY using below code
```
 let homeCenterCoordY = this.viewer.viewport.homeBounds.getCenter().y;
 let currentCoord = this.viewer.viewport.getCenter();
 currentCoord.y = homeCenterCoordY;

this.viewer.viewport
        .panTo(currentCoord)
       .zoomTo(this.viewer.viewport.getHomeZoom());
```
It works fine near the center of the image but it shows black area if I use that code on the far right or left.

That black area seems to go off automatically when pan event raise with mouse or touch. Is there anyway I can mock that event or better way to prevent to black area

**Comment by intelcoder** [comment]
Sorry I found a way 

```
viewer.viewport
        .zoomTo(defaultZoom)
        .applyConstraints();
```
applyConstraints() was the key !

**Comment by iangilman** [comment]
Great, glad you found the solution!
