### ISSUE TITLE
Please tell me how to connect this tool? 

### ISSUE THREAD

**Issue by vladkuraev84** [openseadragon/openseadragon#1121]
I need to cut the images? Or is it makes the utility itself? If we take, for example, or simply html deepzoom.

**Comment by iangilman** [comment]
Well, it depends on how big the images are. If they are more than a few thousand pixels wide, you'll definitely want to convert them into a tiled image format like DZI. There are a number of tools that can do this: 

http://openseadragon.github.io/examples/creating-zooming-images/

I like VIPS, but it just depends on what environment you're comfortable with.

If your image is smaller than a few thousand pixels wide, you can use the Simple Image tile source:

http://openseadragon.github.io/examples/tilesource-image/
