### ISSUE TITLE
Troubles plugging server-side DZI creator

### ISSUE THREAD

**Issue by Medwar** [openseadragon/openseadragon#1122]
First, many thanks for offering Openseadragon to all of us.  It's really great, it's a masterpiece of programming. I will be happy to thank you again once I finish myproject, but now I am experiencing some difficulties.

I am trying to plug 
https://github.com/jeremytubbs/deepzoom 
into my PHP project (to create tiles and DZIs on server side after each image is loaded).

Contrary to the plugins I've been using previosly, this one seem not to contain every library it refers to, and there's neither description nor examples of joining any additional files in the readme. 
I will appreciate any advice on how to make it work. 

Currently I don't know what to do with this in DeepzoomFactory.php:
use InvalidArgumentException;
use Intervention\Image\ImageManager;
use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;

Does it mean that I have to download each of these libraries ( Intervention Image, League Flysystem)  additionaly and place each of them into separate folder? I tried to do so, but it still doesn't work. 
Do I have to include every ".php" file from this libraries into DeepZoom.php?  Seems like I am on the wrong way and missing something about importing namespaces. 

Sorry if the question sounds lame or is an offtop to the seadragon topic. If you know any easier solution how to create the DZIs via server script, it would also be great to hear it.   

Best Regards,
Pavel.

**Comment by iangilman** [comment]
Unfortunately I know little about PHP development; perhaps someone else here can help.  Looks like you're getting some help in https://github.com/jeremytubbs/deepzoom/issues/6, so that's good.

If you can't get it to work, looks like we have another PHP library listed in http://openseadragon.github.io/examples/creating-zooming-images/.
