### ISSUE TITLE
console.debug BUG and FIX

### ISSUE THREAD

**Issue by jetic83** [openseadragon/openseadragon#1124]
in strings.js, there is a code line

     `$.console.debug( "Untranslated source string:", prop );`

console.debug is deprecated (use .log() instead) and OSD does not work in IE10. Changing it to

`$.console.log( "Untranslated source string:", prop );`

solves the issue.

**Comment by iangilman** [comment]
Sounds good... would you be up for making this change in a pull request?

**Comment by jetic83** [comment]
Yes, but I cant submit the pull request, since I dont have the rights?

**Comment by iangilman** [comment]
You just have to fork this repository and make a pull request from your fork to this one. More info here:

https://github.com/openseadragon/openseadragon/wiki/Making-a-Pull-Request

Let me know if you have questions!

**Comment by iangilman** [comment]
Fixed by #1129
