### ISSUE TITLE
lost the center zoom 

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1128]
Hi . thx a  lot for the support 

I using sample image url  and user preserve zoom option between page
the problem is when I click on other view to see the new image (with viewer.open) Im set preserve=false  but the image start as a small image unless you click on the image and its comes to the center 
tried to use "zoomTo" . with get center . but its not working .

how can I fix it 

```

var viewer1 = OpenSeadragon({
             maxZoomPixelRatio:6,
           defaultZoomLevel: 	0.75,
           minZoomLevel: 	0.75,
           visibilityRatio: 	1,
             preserveViewport:true, // this for keep the zoom while open new image
             preserveImageSizeOnResize : true,
             prefixUrl: "url",
   });
```

**Comment by iangilman** [comment]
I don't think I understand what you're trying to accomplish. Can you share a link or a codepen along with a description or image of what you're trying to get it to do?
