### ISSUE TITLE
How to get the specific tile url from a collection of tiles after annotation?

### ISSUE THREAD

**Issue by sumedhvdatar** [openseadragon/openseadragon#1136]
I have a whole slide image. It is being chopped into a collection of tiles with specific size. I am using openseadragon to load all the tile images. I am also able to annotate region of interest. I need a way to store the image url of the region which I annotate.

**Comment by iangilman** [comment]
Are you saying you want to be able to export a specific sub-view of your slide after it's been annotated? Or are you saying you want to be able to store the annotation data and positioning information so the user can come back to it later? 

Also, what annotation system are you using?

**Comment by sumedhaindra** [comment]
Hi thanks for you're reply, I need a way to get the specific tile URL from the entire collection of Deep Zoom Images. Currently I am able to mark the region of interest and store the coordinates.I also want to store the specific tile image url. Is there a way where I can store the tile URL?

**Comment by iangilman** [comment]
You might be better off exporting the current view than trying to use a specific tile. For instance, what if the annotated area is right on the edge between two tiles? Which tile would you choose? 

To export the current view, you should be able to do `view.drawer.canvas.toDataURL()` and store the result or convert it into an image file to save. 

As for figuring out which actual tiles you're looking at, OSD doesn't really have a mechanism for that. You can use `debugMode: true` in the viewer options to get a sense for how the tiles are laid out. You can also get the TiledImage (e.g. `var tiledImage = viewer.world.getItemAt(0)` and look through its array of currently visible tiles, `lastDrawn`. You could pick whichever one takes up the most screen space, for instance. 

I hope these ideas help!
