### ISSUE TITLE
How to handle Double Click Event in Navigator and Check which TileSource is Double Clicked

### ISSUE THREAD

**Issue by AliceBump** [openseadragon/openseadragon#1137]
Hi,

For viewer we can use scope.osd.addHandler('canvas-double-click', function(e)  to get the event source.

But how could we handle such event in navigator? Thanks

**Comment by iangilman** [comment]
`scope.osd.navigator.addHandler('canvas-double-click', function(e) ` should work.

To find out which TiledImage is hit, you'll have to get them all from the `scope.osd.navigator.world` and loop through them comparing their `getBounds()` to the click location; we don't have a hit test function yet. Anyway, a navigator is basically just another Viewer, so the same APIs apply.
