### ISSUE TITLE
Image compositing missed a pixel

### ISSUE THREAD

**Issue by cuong1014** [openseadragon/openseadragon#1139]
Hi!

Currently, we have a project using your platform. It works very well, but now we are being a little bug.

Our project is an online new paper in Japan and we have 3-level image, level 1 and level 2 is fine but level 3  our customers discovered it missed a pixel(you can look at the photos, please notice because it's very small to see). We have tried so many ways but has not yet fixed it.

So if you have any solution please suggest to us.
And if you need any information from our project, please let us know.

Thanks.

![lv3 image](https://cloud.githubusercontent.com/assets/25996022/23347216/19a239c0-fcd3-11e6-9bce-91dccc18d272.png)

Url: https://s4.postimg.org/bz8g8zdbx/Lv3_image.png

**Comment by iangilman** [comment]
Seems like maybe a problem with your tiles. Have you examined the tiles for that section? What are you using to convert them?

**Comment by cuong1014** [comment]
Hi iangilman!

Thanks for your reply, but i think my information is still incomplete(sorry about that):

I think the tiles that our customers provide is precisely because it is being used on a different platform(Flash), of course it is working fine.

When we zoom in, the bug will no longer(You can look from photo). The bug appears only when the image is in transition from level-2 to level-3. 

... So I guess the algorithm of framework(Math.ceil or Math.floor) has missed a pixel when calculating because I feel it looks like the image has been superimposed.

Hope you will have a solution for our problem.

Thanks.

![m](https://cloud.githubusercontent.com/assets/25996022/23389193/2b580bd8-fd99-11e6-9801-72c80f50f319.png)

**Comment by iangilman** [comment]
Looks like it may just be the image scaling smashing the pixel. Do you know if that's on a tile edge or not? You can use the `debugMode: true` option to find out. 

At any rate, you might try playing with the `minPixelRatio` option. By default it's 0.5, but try setting it to 0.1 or 1.0 and things in between and see if any of those help. Here's what the Docs say for that option:

> The higher the minPixelRatio, the lower the quality of the image that is considered sufficient to stop rendering a given zoom level. For example, if you are targeting mobile devices with less bandwith you may try setting this to 1.5 or higher.

...which will affect the image stretching.

**Comment by cuong1014** [comment]
Hi!

It's not working, we have chosen edit directly in framework.

Anyway, thanks for your reply.
