### ISSUE TITLE
adding div to Toolbar is not workoing

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1140]
```
var viewer1 = OpenSeadragon({
             id: "mainImage",
             maxZoomPixelRatio:6,
            toolbar:"toolbarDiv",
            panVertical: 	false,
           defaultZoomLevel: 	0.75,
           minZoomLevel: 	0.75,
           visibilityRatio: 	1,
             preserveViewport:true, /
             preserveImageSizeOnResize : true,
             prefixUrl: "img",
   });

```

when I add the toolbar(as in this example: http://openseadragon.github.io/examples/ui-toolbar/) properties I get an error 
Cannot read property 'appendChild' of null

I just want to add a div to the buttons to controlling their margin/padding

**Comment by iangilman** [comment]
Do you have an element on your page with the id `toolbarDiv`? If not, you'll get that error.

**Comment by johnico** [comment]
Thanks a lot
