### ISSUE TITLE
Viewport with zoom not centered but zoomed to the TOP of the image

### ISSUE THREAD

**Issue by bogdanr** [openseadragon/openseadragon#1144]
Hello,

I have this page: http://heatmaps.nimblex.net/tiles/100-200-Bucharest-March-2017.html

And when it loads I would like to have it display the middle TOP part of the image, instead of the center of the image. How would I be able to accomplish this?

**Comment by iangilman** [comment]
Interesting image... what is it of?

Anyway, if you want to start people at a specific location, I recommend `Viewport.fitBounds()`. Something like this:

```
viewer.addHandler('open', function() {
  var viewBounds = viewer.viewport.getBounds();
  var viewAspect = viewBounds.height / viewBounds.width;
  var imageBounds = viewer.world.getItemAt(0).getBounds(); // Assuming just a single image
  var newViewWidth = imageBounds.width * 0.5;
  var newBounds = new OpenSeadragon.Rect((imageBounds.width - newViewWidth) * 0.5, 0, newViewWidth, newViewWidth * viewAspect);
  viewer.viewport.fitBounds(newBounds, true);
});
```

**Comment by bogdanr** [comment]
Thanks! This works as expected.

The image is a heatmap of radio signals. On the Y axis you have the time and on the X axis you have the radio frequency. In [this](http://heatmaps.nimblex.net/) page I just published a bunch of these heatmaps.

**Comment by iangilman** [comment]
Fascinating! Can we add that page to http://openseadragon.github.io/examples/in-the-wild/ ?

**Comment by bogdanr** [comment]
Absolutely! You have some great examples in there.

**Comment by iangilman** [comment]
Great! I've added it to the ticket:

https://github.com/openseadragon/site-build/issues/159

Hopefully someone will get around to taking care of that one of these days... feel free to add it yourself if you'd like.
