### ISSUE TITLE
how to configure with dzi file at my C: (can't move it since the images are huge)

### ISSUE THREAD

**Issue by 1ankit8** [openseadragon/openseadragon#1145]
i have about 43 dzi file at a folder location in my c:. How do i use it in my project?

**Comment by iangilman** [comment]
You'll have to set up a local server on your machine. Do you know how to do that? There are a variety of ways. If you have Python installed, you can do `python -m SimpleHTTPServer 8888` from the command line. You can also build a simple server with Node, or use the "connect" module for Grunt. There are also things like XAMPP: 

https://www.apachefriends.org/index.html

At any rate, once you have the local server, you'll need to arrange your files in a folder, like so:

```
project
  image.dzi
  image_files
    ...
  index.html
  openseadragon
    openseadragon.min.js
    images
      ...
```
      
Then, in your index.html you can do something like so:

```
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="openseadragon/openseadragon.min.js"></script>
    <style type="text/css">
        #openseadragon1 {
            width: 800px;
            height: 600px;
        }
    </style>
</head>
<body>
    <div id="openseadragon1"></div>
    <script type="text/javascript">
        var viewer = OpenSeadragon({
            id: "openseadragon1",
            prefixUrl: "openseadragon/images/",
            tileSources: "image.dzi"
        });
    </script>
</body>
</html>
```

**Comment by 1ankit8** [comment]
Hi Ian,

Thanks for the help. Highly appreciated.

But i have multiple .dzi files. I tried placing them as :

...
tileSources: ["image1.dzi", "image2.dzi", "image3.dzi"]
...

But only the last image gets displayed.

i need them aligned in line with each other.

Regards
Ankit Kumar

**Comment by iangilman** [comment]
I see. Yes, by default they are all stacked on top of each other. You probably want collection mode:

http://openseadragon.github.io/examples/tilesource-collection/

**Comment by 1ankit8** [comment]
hi Ian

I have been following as per your instructions, and have made great
progress.

Can you please guide me on how to crop images in OSD.

As of now i am able to get the coordinates and size of the image. But i
have a collection of images, and i have no idea from which exact image i
have the viewports.

Moreover, why don't you get a video series on youtube, or something
similar, about OpenSeadragon (just a suggestion :) ).

Regards
Ankit Kumar

**Comment by iangilman** [comment]
Thanks for the youtube suggestion... I'll give it some thought!

When you say you want to crop the images, in what way do you want them cropped? TiledImage does have a crop facility: 

http://openseadragon.github.io/docs/OpenSeadragon.TiledImage.html#setClip

...but maybe you really mean you want to set how you zoom into them? Or where they're placed?

At any rate, it might be helpful for you to look at all the TiledImages in your World and get their viewport coordinates. Here's how you would get the first one:

```
viewer.world.getItemAt(0).getBounds();
```

...and it might be helpful to learn about the different coordinate systems:

http://openseadragon.github.io/examples/viewport-coordinates/

I hope this helps!
