### ISSUE TITLE
3d image on the viewer ? 

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1146]
Hi is there any support of 3d image on the viewer ? 
I have 3d images that I want to include in the viewer instead of regular images.

Thx

**Comment by johnico** [comment]
For example using threeJS library

**Comment by iangilman** [comment]
Interesting... what would be the purpose of using OpenSeadragon? Three.js already provides good zooming support.

**Comment by johnico** [comment]
hmm , for example - sync zoom between 2 images , full screen,  overlays ., replace images .. etc

**Comment by iangilman** [comment]
Cool... I can see that those would be nice things to have in a 3d world, but 3d is different enough that you'd probably have to build it fresh instead of using what OpenSeadragon has. At any rate, OSD doesn't have 3d support.
