### ISSUE TITLE
Keep the image position at the center

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1155]
Hi - I dont know if its related to this issue that solve with nice solution :)
https://github.com/openseadragon/openseadragon/issues/1141 

but when I change image and and replace image with close and open I would like to make sure that the image is in the center of the viewer.
sometimes after I zooming between 2 images  and then I move to new image by click the new image is replaced but the image little is out of the limits 

so what I would like to achive is some of reset that not affect from previous image, reset exactly when I refresh the page 

thx

**Comment by iangilman** [comment]
Seems like the simplest thing is to do `viewer.viewport.goHome()` whenever you switch images.

**Comment by johnico** [comment]
Thank you ! 👍

**Comment by iangilman** [comment]
I think the fix for this may be what I recommended/did in http://codepen.io/iangilman/pen/BWKKxQ where you keep a separate variable for the zoom.

**Comment by johnico** [comment]
thx 
and should I call to maintainzoom while switch image ? 
for now Im using viewer.close and viewer.open

**Comment by iangilman** [comment]
Sure, if you want it to have the same zoom as the last one.

**Comment by johnico** [comment]
Hi @iangilman   
what can I do in case of difference images  ? 
for example: first image dimension: 1920X1080
and the second image dimension is the  opposite , for instance .- 1920 is the height  and not the width.
in this case  the first image show up  on bottom instead center because it take the center zoom from the second image .

**Comment by iangilman** [comment]
If the images aren't the same shape it seems like disabling the zoom/pan sync would be the best choice. One way to do that would be to have a `syncEnabled` flag that you check at the top of viewer1Handler, viewer2Handler, and maintainZoom.

**Comment by johnico** [comment]
@iangilman  thx .  - i added : 
               var sync= false;
              var viewer1Leading = false;
              var viewer2Leading = false;

              var viewer1Handler = function() {
                if (viewer2Leading || **sync ==false**) {
                  return;
                }



i put it also on viewer2handler 

and on click I set sync = true 
on hide i set sync = false 
it work on refres but when hide/show  multiple time it's not keep and return to cente of the viewer 1 zoom 

also i wrap the maintainzoom with if sync ==false

maybe should i need to add something else?

its not working - because if i zoom on the second image and I can go to situation that we can not see the first  and then close the images. in this case the first image keep the zoom and this is still cause the problem.



example:

http://codepen.io/anon/pen/mWooLN

**Comment by johnico** [comment]
I think the solution is to calculate the width and height and if the difference is 20-30% (for example width=300 and width2 = 600 )  just to disable the maintain zoom option . 
If you have any suggestion it would be great

**Comment by iangilman** [comment]
Apologies for the delayed response... I was out of town. At any rate, I don't know that I have any specific suggestions. You'll have to play around with it until you find a combination that works for your needs.
