### ISSUE TITLE
Calculate width and height to take all frame

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1157]
Hi . i have OSD area  with 100% width and 600px height . (or higher-depends the screen resolution) 

the images are not equal each other.
So my question is How can I calculate the width/height  or  How can I know how much "defaultZoomLevel" the viewer will be set to.
The image should take the all available height space  , and if  it is possible it also take all the width, 
but if the image height is higher then OSD area so i will get empty space at the side and its ok .

If I increase the defaultZoom . it can cut the image from top and buttom 

using this prporties:
           maxZoomPixelRatio:6,
           defaultZoomLevel: 	0.75,
           minZoomLevel: 	0.75,
           visibilityRatio: 	1,

thx for the support

**Comment by iangilman** [comment]
I'm not sure I understand what you're asking for here. By default the OSD viewer will start with the image as big as possible, so it should already be doing what you want (unless your image is wider than the viewer, in which case the blank space will be at the top and bottom). How is it not working for you?

**Comment by johnico** [comment]
hi 
I meant that if I have image height bigger than div height , how can I calculate the default zoom  to take all image in the frame , so the zoom will start from 0.2 for example instead 0.7

**Comment by iangilman** [comment]
So you want to cut off the top of the image? You might look into `homeFillsViewer: true` (you'll need to disable `defaultZoomLevel` and `minZoomLevel`). 

If you're looking to calculate something more specific, you might use the code at the bottom of https://github.com/openseadragon/openseadragon/issues/1177
