### ISSUE TITLE
Showing the same location on two different images

### ISSUE THREAD

**Issue by mgiacomelli** [openseadragon/openseadragon#1160]
I saw this example using Openseadragon to show two images synchronized to one another

http://codepen.io/r3nya/pen/RopLdd/

and was immediately interested in trying to use it to visualize different representations of the same image data.  I hacked up a quick demo to try it out using some data I had:

http://18.62.11.24/SideBySide/sidebyside.html

However, the viewer is extremely glitchy.  The zoom amount with the middle mouse button is semi-random, and occasionally the display starts ping-ponging.  This is particularly noticeable if you try to zoom in and then hit the home button.  Often it'll zoom out and then immediately zoom back in.  

I assume this is because of how how the handler is attached to the zoom function.  I tried increasing the time on the debounce function which improves things a little, but it still behaves erratically if an input happens to overlap with the other frame updating.  Is there a better way to accomplish this than debouncing the 'zoom' handler?  It seems like there should be some way to update the second viewport without disrupting actions happening in the first.

**Comment by iangilman** [comment]
Take a look at these examples for more ideas:

http://codepen.io/iangilman/pen/BpwBJe

http://codepen.io/iangilman/pen/BWKKxQ

… As well as the discussion in these issues:

https://github.com/openseadragon/openseadragon/issues/1141

https://github.com/openseadragon/openseadragon/issues/1155

**Comment by mgiacomelli** [comment]
Wow that was fast, and the fix so simple:

http://18.62.11.24/SideBySide/sidebysidenew.html

I'll take a look at those other discussions for ideas as well.  Thanks!
