### ISSUE TITLE
pls I need to download files examples (zip)

### ISSUE THREAD

**Issue by idanka** [openseadragon/openseadragon#1161]
Pls. I need to download examples files (zip), I do not understand that you can replace the use of Silverlight (Image Composite Editor to Save As Deep Zoom Image).

current files and content: 
[Sample](http://www.idstudio.tk/media/1570-lazio-wolfgango/1570-lazio-wolfgango_v1.html)

**xy.html**

```
<script type="text/javascript" src="http://www.idstudio.tk/HDView2.js"></script>
<script type="text/xml" id="hdvxmlembed">
<?xml version="1.0"?>
<root>
	<imageset
		url="1570-lazio-wolfgango_stitch_files/{l}/{c}_{r}.png"
		levels="14"
		width="8165"
		height="5836"
		projection="perspective"
		alphaBlend="1"
		maxZoom="2.000000"
		tileWidth="254"
		tileHeight="254"
		tileOverlap="1"
	/>
</root>
</script>
</head>

<body style="margin: 0; height:100%">

<div id="hdvDiv" style="background-color: black; text-align: center; height:100%">
    <script type="text/javascript">
        var args;
        if ( top.location.search == "" )  {
            args = 'FileName=#hdvxmlembed&BackgroundColor=0&Viewer=2';
        }
        else {
            args = top.location.search.substring(1);
        }
        hdv = new hdvHost("hdvControl", "hdvDiv", "100%", "100%", top.location.href, args);
    </script>
</div>
</body>
```

**HDViewSL.xap**
`never mind`

**xy.xml**
```
<?xml version="1.0"?>
<Image TileSize="254" Overlap="1" Format="png" xmlns="http://schemas.microsoft.com/deepzoom/2008">
  <Size Width="8165" Height="5836"/>
</Image>
```

**xy_hdv.xml**
```
<?xml version="1.0"?>
<root>
	<imageset
		url="1570-lazio-wolfgango_stitch_files/{l}/{c}_{r}.png"
		levels="14"
		width="8165"
		height="5836"
		projection="perspective"
		alphaBlend="1"
		maxZoom="2.000000"
		tileWidth="254"
		tileHeight="254"
		tileOverlap="1"
	/>
</root>
```

Thank you very much.
(Sorry Google translate)

**Comment by avandecreme** [comment]
Hi,

It looks like you have a pyramid in HDView format. Unfortunately, HDView is currently not supported by OpenSeadragon. We have issue https://github.com/openseadragon/openseadragon/issues/497 open about it but nobody took the time to implement it.

So you have two options:
- implement the HDView tilesource
- convert your HDView pyramid to a supported pyramid format

You can get the list of supported formats [here](http://openseadragon.github.io/#examples-and-features) in the `Supported Tile Sources` section.
