### ISSUE TITLE
How do I load very large images?

### ISSUE THREAD

**Issue by BecomingProgrammer** [openseadragon/openseadragon#1164]
How do I load large images? The picture has 9000 * 170000 pixels.
What is the specific way to load a custom tile map?
Can I load this big picture with a custom tile map?

**Comment by iangilman** [comment]
For an image that size you'll want to convert it into a tile set. There are a variety of tools available for this: 

http://openseadragon.github.io/examples/creating-zooming-images/

Once you have your image converted, you should be able to follow the "Getting Started" to load it into OpenSeadragon: 

http://openseadragon.github.io/docs/

**Comment by BecomingProgrammer** [comment]
@iangilman   Thank you for your reply, but I am doing this project now, my client refused to add DZI to my server. He gave me an API that could crop the entire image and cut it in pieces. So I now use a custom tile sources, but I am not in the process of using the getTileUrl function of the Level, x, y is how the assignment into the function？ because I was a newcomer in javascript, getTileUrl function is how to work of?

This is the example：
 tileSources:   {
        height: 512*256,
        width:  512*256,
        tileSize: 256,
        minLevel: 8,
        getTileUrl: function( level, x, y ){
            return "http://s3.amazonaws.com/com.modestmaps.bluemarble/" +
                    (level-8) + "-r" + y + "-c" + x + ".jpg";
        }
    }

**Comment by iangilman** [comment]
That looks reasonable to me. Are you running into trouble with it? If so, what kind of trouble? Can you share an example of the problem?
