### ISSUE TITLE
Recommendation for hosting OpenSeadragon

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#1166]
I've run my webiste deepzoomchattanooga.com on a couple of hosting provider sites.
Now looking for a new host, and have run into something previously wasn't an issue.
INODES
Apparently, CloudLinux is all the rage for hosting companies - and there are built-in limits on number of files. Most limit to 250,000 or less.
Well, my site has a lot of zooms, and is up to over a million.
This is also just a hobby, so I'm looking to limit to a reasonable expense. 

What type of hosting would be appropriate for a low-traffic, high number of files site?

Thanks,

**Comment by iangilman** [comment]
Good question! Hopefully more people chime in, but here are my thoughts: I think Amazon's S3 is a popular choice for this sort of thing; I'm not sure what the cost would be though. Another option would be to use GitHub Pages, which is free and can handle surprisingly large amounts of files... if you do run into a limit, you can start a second repository.

At any rate, my recommendation would be to host your site wherever you want, and then find a different place for the image tiles. This gives you the most flexibility.

**Comment by johnico** [comment]
Amazon s3 is good choice if you need a full control on your hosting and doing by yourself(create a machine by yourself)  
You may use only the amazon CDN   for the files  and other  rapid hosting for the site and it depends  your site bandwidth , you may need a VPS for that.

**Comment by SamHall** [comment]
I managed to get Github pages up and running to test hosting the DZI files. Whether it's this, or another 3rd party solution like Amazon S3 - I realize I don't have a complete understanding of how to get the files to work when hosted remotely.

I often utillize mutiple tilesources make them selectable via click functions. I've found formatting the dzi file info like below pulls the remote files, but I cannot make them selectable via the same method used for local DZI files.

_(First, showing how I make them selectable)_
```
          $('.pg00').click(function() {
            viewer.goToPage(0);
          });
		  
          $('.pg01').click(function() {
            viewer.goToPage(1);
            });
```

**Local example:**

```
tileSources: [
              "/zoom/600market.dzi",
              "/zoom/700market.dzi"
            ],
```

**REMOTE example:** (Only the first tilesource is loaded)

```
 tileSources: ({
                Image: {
                xmlns:    "http://schemas.microsoft.com/deepzoom/2008",
                Url:      "http://SamHall.github.io/600market_files/",
                Format:   "jpeg", 
                Overlap:  "1", 
                TileSize: "254",
                Size: {
    Height: "6897",
    Width: "32395"
                }
            },
			
                Image: {
                xmlns:    "http://schemas.microsoft.com/deepzoom/2008",
                Url:      "http://SamHall.github.io/700market_files/",
                Format:   "jpeg", 
                Overlap:  "1", 
                TileSize: "254",
                Size: {
    Height: "3776",
    Width: "40050"
                }
            }		
}),	
```

**Comment by avandecreme** [comment]
This is because you use `(` and `)` instead of `[` and `]`.

```javascript
 tileSources: [{
                Image: {
                xmlns:    "http://schemas.microsoft.com/deepzoom/2008",
                Url:      "http://SamHall.github.io/600market_files/",
                Format:   "jpeg", 
                Overlap:  "1", 
                TileSize: "254",
                Size: {
    Height: "6897",
    Width: "32395"
                }
            },
			
                Image: {
                xmlns:    "http://schemas.microsoft.com/deepzoom/2008",
                Url:      "http://SamHall.github.io/701market_files/",
                Format:   "jpeg", 
                Overlap:  "1", 
                TileSize: "254",
                Size: {
    Height: "3776",
    Width: "40050"
                }
            }		
}],
```

**Comment by SamHall** [comment]
I had suspected that, and tried it - but it didn't seem to work.
I need to test more to see if there is another issue - perhaps Github links... not sure.
Ideally, I could link to the .dzi file, but I understand there are cross-domain issues. This can be dealt with via CORS(?), however, I have not figured out how to make that work yet.

Thanks.

**Comment by iangilman** [comment]
The technique where you provide all the info shouldn't require CORS; in fact, that's exactly why you would do that. 

Sounds like you got it working though?

**Comment by SamHall** [comment]
Yes, I really didn't want to have to re-format all my links, so using CORS is a better solution.
It took some experimenting - but did get it working. Now I'm looking at Amazon S3, as Github pages has some limits that would require me to split up my files somewhat.

Thanks.

**Comment by iangilman** [comment]
Excellent, glad to hear you found a good solution :)
