### ISSUE TITLE
I have a question, How to get fabric overlay coordinates of a tiled image?

### ISSUE THREAD

**Issue by sreekanthssr** [openseadragon/openseadragon#1167]
I tried in this code to draw a fabric rectangle on the place of the tiled image 

               var image = viewer.world.getItemAt(1),
                bounds = image.getBounds();
               
                var xy = viewer.viewport.viewportToViewerElementCoordinates(bounds.getTopLeft());
                var xy2 = viewer.viewport.viewportToViewerElementCoordinates(bounds.getBottomRight());
              viewer.fabricjsOverlay().fabricCanvas().add(new fabric.Rect({
                        width: xy2.x-xy.x,
                        height:xy2.y-xy.y,
                        left: xy.x,
                        top: xy.y,
                        stroke: '#ff0000',
                        fill: '#00ff00'
                    })).renderAll();

Rectangle not in the place and proper zoom level. 
Please help me in this issue.

**Comment by iangilman** [comment]
Have you tried using the bounds without converting it? I think the OSD Fabric plugin might use viewport coordinates. You could also try asking the author, @altert.
