### ISSUE TITLE
Online exhibitions

### ISSUE THREAD

**Issue by eg272** [openseadragon/openseadragon#1168]
Hi, I was wondering if anyone might have any suggestions for something similar to the online exhibitions which are hosted on Google Arts & Culture?  We are currently using Open Seas Dragon to make zoomable digital interpretation for our exhibitions, but are keen to get our exhibitions online in a similar manner to those on Google Arts & Culture.  Can anyone recommend anything?

Many thanks.

**Comment by iangilman** [comment]
Hopefully someone can chime in with suggested frameworks/libraries for building such a thing. The sites I know of like that are custom built.
