### ISSUE TITLE
OpenSeadragon and Azure storage

### ISSUE THREAD

**Issue by DrumrollPlease** [openseadragon/openseadragon#1170]
Has anyone blogged about their experiences with OpenSeadragon utilizing cloud storage?  My TileSource is located in Azure blob storage with anonymous access, and I'm able to successfully navigate to that url with my browser.  However, when attempting to open a viewer with that TileSource, I receive an "Unable to open [object Object]: HTTP 0 attempting to load TileSource."  Any link to such a discussion would be welcomed help.

Thanks!

**Comment by iangilman** [comment]
Hopefully someone can add their experiences with Azure... I don't have direct experience, but it sounds like you're dealing with cross-site restrictions. Is it possible to set up CORS on Azure? This would allow you to access the tile source file from your site.

If not, another option would be to store the tile source information locally but keep the tiles themselves on Azure. See http://codepen.io/iangilman/pen/bdgWBz for an example.

**Comment by SamHall** [comment]
Your example works, but I would much rather enable CORS on the remote server hosting the tilesources. I've visited the enable-cors.org site, but it's a deep-dive. 

The PHP example works, but of course, the DZI file is not a php file. How do I enable CORS within a DZI, or better yet - for the whole remote site? The simpler, the better.  Thank you.

```
<?php
 header("Access-Control-Allow-Origin: *");
 ?>
```

**Comment by DrumrollPlease** [comment]
I just wanted to follow-up with a solution I discovered for this issue:

Yes, I had CORS set up in Azure and was successful to in navigating to any image in blob storage by simply typing the url in the browser address bar.

I was having problems opening the Deep Zoom Composer project file (.xml) that was also located in the cloud, so I resorted to this:

  var viewer = OpenSeadragon({
    id: "openseadragon1",
    prefixUrl: "/openseadragon/images/",
    showNavigator: true,
    crossOriginPolicy: "Anonymous",
    tileSources: {
      Image: {
        xmlns: "http://schemas.microsoft.com/deepzoom/2009",
        Url: "https://myblobstorage/dzc_output_files/",
        Format: "png",
        Overlap: "1",
        TileSize: "256",
        Size: {
          Height: "893496",
          Width: "853933"
        }
      }
    },
  });

…and it worked.

Turns out, I later Googled up a code fragment that seemed so close to what I was intentionally failing to do, and this worked as well:

  var viewer = OpenSeadragon({
    id: "openseadragon1",
    prefixUrl: "/openseadragon/images/",
    showNavigator: true,
    crossOriginPolicy: "Anonymous",
    tileSources: https://myblobstorage/dzc_output.xml
  })

I’m good.  Thank you.

**Comment by iangilman** [comment]
Great, thank you for letting us know!

**Comment by Triosysit** [comment]
Hi, i have same issue i wants to display dzi from azure blob storage can anyone help me on that

**Comment by iangilman** [comment]
@Triosysit What problem are you having? Have you tried the solution above?
