### ISSUE TITLE
ReferenceStrip not freeing resources

### ISSUE THREAD

**Issue by VipSaran** [openseadragon/openseadragon#1172]
With no ReferenceStrip, a tab in both FF and Chrome is around 300 MB.

With RS, it continually builds up used memory when changing content with viewer.open().

Beta online for your verification:
http://photolapse.fr/timelapse/index.php?project_name=lidl

Viewer init:
```
viewer = OpenSeadragon({
    id: "openseadragon1",
    prefixUrl: "images/",
    defaultZoomLevel: 1,
    visibilityRatio: 1,
    preserveViewport: true,
    showNavigator: true,
    navigatorId: "osdNavigator",
    sequenceMode: true,
    previousButton: "osdButtonPrev",
    nextButton: "osdButtonNext",
    zoomInButton: "osdButtonZoomIn",
    zoomOutButton: "osdButtonZoomOut",
    homeButton: "osdButtonHome",
    fullPageButton: "osdDummyButtonFullScreen",
    showReferenceStrip: true,
    referenceStripSizeRatio: 0.1,
    referenceStripScroll: 'vertical'
  });
```

Day change:
```
      var strDate = formatDateToString(date);
      currentDayTileSources = getTileSourcesForDate(strDate);
      viewer.close().open(currentDayTileSources);
      if (forcedInitial) {
        forcedInitial = false;
        viewer.goToPage(currentDayTileSources.length - 1);
      }
```

**Comment by iangilman** [comment]
That's no good! 

The reference strip is actually a bunch of little Viewers, and it looks like those viewers aren't being closed when the reference strip is being destroyed (which happens every time you do a new `open` on your main viewer). 

Seems like it'd be worth trying that as a first step: keep track of all the `miniViewer` objects created  in: 

https://github.com/openseadragon/openseadragon/blob/master/src/referencestrip.js#L424

...and call their `destroy` functions when the reference strip is destroyed here:

https://github.com/openseadragon/openseadragon/blob/master/src/referencestrip.js#L295

Would you be up for making a patch to this effect?

**Comment by VipSaran** [comment]
> Would you be up for making a patch to this effect?

Is that your signature or what? ;)

**Comment by VipSaran** [comment]
Implemented as per your suggestion. Change is online (on the same site) and it works.

I could submit a patch if you like...

**Comment by iangilman** [comment]
Glad to hear it works, and yes, a patch would be lovely!

> Is that your signature or what? ;)

LOL it definitely should be! Just trying to make sure everyone knows this is a self-service project :)

**Comment by iangilman** [comment]
Fixed by #1175

**Comment by marcosocamargo** [comment]
What is the data structure for the tileSources option so it takes the DZI file for the regular viewer and the referenceStripThumbnailUrl for the reference strip?
Would it be something like this?
```
    tileSources: [
      {
        type: 'dzi',
        url:  'image0.dzi',
        referenceStripThumbnailUrl:  'thumb0.jpg'
      }.
      {
        type: 'dzi',
        url:  'image1.dzi',
        referenceStripThumbnailUrl:  'thumb1.jpg'
      }
]
```

**Comment by iangilman** [comment]
I think that might work. I don't think you need the `type`.

**Comment by marcosocamargo** [comment]
It fails while executing this code:
$.TileSource.determineType = function( tileSource, data, url ){
    var property;
    for( property in OpenSeadragon ){
        if( property.match(/.+TileSource$/) &&
            $.isFunction( OpenSeadragon[ property ] ) &&
            $.isFunction( OpenSeadragon[ property ].prototype.supports ) &&
            OpenSeadragon[ property ].prototype.supports.call( tileSource,
data, url )
        ){
            return OpenSeadragon[ property ];
        }
    }

    $.console.error( "No TileSource was able to open %s %s", url, data );

    return null;
};

tilesource.js:984 No TileSource was able to open undefined [object Object]
$.TileSource.determineType @ tilesource.js:984
(anonymous) @ viewer.js:2584
setTimeout (async)
getTileSourceImplementation @ viewer.js:2544
addTiledImage @ viewer.js:1657
doOne @ viewer.js:710
open @ viewer.js:715
open @ viewer.js:577
$.Viewer @ viewer.js:483
(anonymous) @
rp.cgi?directory=/Brasil/S%C3%A3o%20Paulo/Jundia%C3%AD/Nossa%20Senhora%20do%20Desterro/%C3%93bitos%201744-1787/Imagens&image_name=IMG_007_0025.JPG:148

**Comment by marcosocamargo** [comment]
In this function. shouldn't the raiseevent be at the beginning of the function instead at the end so one can add a handler before the page is open?

    goToPage: function( page ){
        if( this.tileSources && page >= 0 && page < this.tileSources.length ){
            this._sequenceIndex = page;
            this._updateSequenceButtons( page );
            this.open( this.tileSources[ page ] );
            if( this.referenceStrip ){
                this.referenceStrip.setFocus( page );
            }

            /**
             * Raised when the page is changed on a viewer configured with multiple image sources (see {@link OpenSeadragon.Viewer#goToPage}).
             *
             * @event page
             * @memberof OpenSeadragon.Viewer
             * @type {Object}
             * @property {OpenSeadragon.Viewer} eventSource - A reference to the Viewer which raised the event.
             * @property {Number} page - The page index.
             * @property {?Object} userData - Arbitrary subscriber-defined object.
             */
            this.raiseEvent( 'page', { page: page } );
        }

        return this;
    },
```

**Comment by msalsbery** [comment]
> In this function. shouldn't the raiseevent be at the beginning of the function instead at the end so one can add a handler before the page is open?
> 
> ```
> goToPage: function( page ){
>     if( this.tileSources && page >= 0 && page < this.tileSources.length ){
>         this._sequenceIndex = page;
>         this._updateSequenceButtons( page );
>         this.open( this.tileSources[ page ] );
>         if( this.referenceStrip ){
>             this.referenceStrip.setFocus( page );
>         }
> 
>         /**
>          * Raised when the page is changed on a viewer configured with multiple image sources (see {@link OpenSeadragon.Viewer#goToPage}).
>          *
>          * @event page
>          * @memberof OpenSeadragon.Viewer
>          * @type {Object}
>          * @property {OpenSeadragon.Viewer} eventSource - A reference to the Viewer which raised the event.
>          * @property {Number} page - The page index.
>          * @property {?Object} userData - Arbitrary subscriber-defined object.
>          */
>         this.raiseEvent( 'page', { page: page } );
>     }
> 
>     return this;
> },
> ```

Sometimes it would be handy to have the event raised first, especially if the event had a way to cancel the default handling. I've added that type of functionality to a lot of other events, but this one I feel like I missed.

For backward compatibility, we usually don't want to move the raiseEvent() calls, but in my opinion, a pre=page event could be a useful feature

**Comment by marcosocamargo** [comment]
Thanks for the response. Is there a version of OSD that uses fetch()
instead of xmlhttprequest?
Thanks,
-Marcos

**Comment by marcosocamargo** [comment]
Why i[image: image.png]
s there so much space between the thumbnails? How do I control that? I
tried adjusting the height of the strip but nothing changed. The ratio
changes and the spacing remains the same.
