### ISSUE TITLE
i want to get [annotations and the coordinate of annotations ]

### ISSUE THREAD

**Issue by zhuyinjing** [openseadragon/openseadragon#1176]
okay...
i want to get [annotations and the coordinate of annotations ] on openseadragon
how can i get the annotations coordinate ???
thanks a lot!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by iangilman** [comment]
You can make simple annotations with the overlay feature: 

http://openseadragon.github.io/examples/ui-overlays/

... or you can use one of the other overlay plugins, such as SVG, Fabric, or Canvas:

http://openseadragon.github.io/#plugins

None of these provide interaction for the user to add new annotations; they're just a way to display existing overlays. 

I guess if you don't know which to pick you might as well start with the built in overlays.

**Comment by zhuyinjing** [comment]
haha i really have a little trouble～do you have wechat？发自网易邮箱 iPhone 版
            在2017年04月28日 00:42，Ian Gilman 写道:You can make simple annotations with the overlay feature:
http://openseadragon.github.io/examples/ui-overlays/
... or you can use one of the other overlay plugins, such as SVG, Fabric, or Canvas:
http://openseadragon.github.io/#plugins
None of these provide interaction for the user to add new annotations; they're just a way to display existing overlays.
I guess if you don't know which to pick you might as well start with the built in overlays.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openseadragon/openseadragon","title":"openseadragon/openseadragon","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/openseadragon/openseadragon"}},"updates":{"snippets":[{"icon":"PERSON","message":"@iangilman in #1176: You can make simple annotations with the overlay feature: \r\n\r\nhttp://openseadragon.github.io/examples/ui-overlays/\r\n\r\n... or you can use one of the other overlay plugins, such as SVG, Fabric, or Canvas:\r\n\r\nhttp://openseadragon.github.io/#plugins\r\n\r\nNone of these provide interaction for the user to add new annotations; they're just a way to display existing overlays. \r\n\r\nI guess if you don't know which to pick you might as well start with the built in overlays."}],"action":{"name":"View Issue","url":"https://github.com/openseadragon/openseadragon/issues/1176#issuecomment-297771687"}}}

**Comment by zhuyinjing** [comment]
@iangilman thank you very much!!!
