### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by zhuyinjing** [openseadragon/openseadragon#1179]
when i npm install openseadragon-annotations
and i use `import "openseadragon-annotations/dist/openseadragon-annotations.js"; `
its error!! the error is `Uncaught TypeError: Super expression must either be null or a function, not undefined`
how should i do?
i really want to know!!!
And i use VUE.js in my project...
help me!!!! please
thanks so much!!!

**Comment by iangilman** [comment]
Does your OpenSeadragon work in this scenario if you don't import `openseadragon-annotations`? If so, sounds like it's a problem with the plugin in that configuration. It may not be compatible with whatever you're using to bundle (browserify? webpack?). Hopefully you'll get a response at https://github.com/Emigre/openseadragon-annotations/issues/11 but if not, you might look at the `openseadragon-annotations` code and see about adding bundling support yourself.

**Comment by zhuyinjing** [comment]
@iangilman  thank you so much!!!
