### ISSUE TITLE
Option to modify tiles after loading

### ISSUE THREAD

**Issue by cskwg** [openseadragon/openseadragon#118]
Hi,

currently there is no option to modify tiles after they have been loaded from the source, but this is required by my application.

So within the method Drawer.onTileLoad, I added the following code:

// AFTER these 2 existing lines:
tile.loaded = true;
tile.image = image;

// NEW:
if (drawer.fixTile) {
	drawer.fixTile(drawer, tile);
}

This initially is only a fast way to do nothing, because fixTile is not defined.

By adding the following code, the client-site tile modification becomes possible.

	window.OpenSeadragon.Drawer.prototype.fixTile = Xxxx.prototype.fixTile;

But my fixTile method produced a canvas context instead of the original image. So another change was needed.

This is within Drawer.drawCanvas.
The original code was producing a canvas context from the image anyway. Now this is done earlier, so a slight modification is required:

if (!TILE_CACHE[this.url]) {
<b>	// Is this already a canvas context ?
	if (this.image && this.image.lineTo) {
		rendered = this.image;
	} else {
</b>		canvas = document.createElement('canvas');

		canvas.width = this.image.width;

		canvas.height =  this.image.height;

		rendered = canvas.getContext('2d');

		rendered.drawImage(this.image, 0, 0);
	}

	TILE_CACHE[this.url] = rendered;
                //since we are caching the prerendered image on a canvas

                //allow the image to not be held in memory

	this.image = null;
}

Kind regards
Karl

**Comment by iangilman** [comment]
This now exists (see #348).
