### ISSUE TITLE
Could we get a new release?

### ISSUE THREAD

**Issue by acorncom** [openseadragon/openseadragon#1181]
It's been a while since the last release, would it be possible to get a new one cut?  There are some bug fixes in here we'd love to start using 😀 

Thanks!

**Comment by iangilman** [comment]
Yes, I think we're overdue! The main thread for this topic is https://github.com/openseadragon/openseadragon/issues/1094.

The big thing I've been waiting on is some sort of resolution to https://github.com/openseadragon/openseadragon/issues/1020... I don't really want to release with that bug unresolved.
