### ISSUE TITLE
Image Viewer - get rid of unnecessary animations when using fadein/fadeout

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1182]
Hi when using fade in /out in jquery and replace image or move between images by click on button for example , the image came from bottom to the top .( kind of jumps/animation)  ,or to the zoom point.

I think it happens because of using fadein/fade out with jQuery .
is there any way to disable at all the animation ? just the image will show up. 

example : 
http://codepen.io/anon/pen/NjgQMy

**Comment by iangilman** [comment]
You can use jQuery's hide/show instead of fadein/fadeout to disable the animation...

**Comment by johnico** [comment]
the show/hide make the image disappear and also don't make the same effect as fadein/fadeout

i tried to demonstrate it via codepen . [](https://codepen.io/anon/pen/YVEXpW) 
 click show and then replace 
here you see some jumps , this is one of the issues .  but the second in my project is the animation from top to bottom

**Comment by iangilman** [comment]
Hmm... I'm not sure what the best solution would be. You're definitely going far beyond the typical use for OSD! You may have to do some experimentation. One option might be to do the fading with your own code instead of jQuery; that might give you more control.
