### ISSUE TITLE
Add Id to navigator red frame  , and fadeout on load

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1183]
Hi  , starting to work with the navigator 

2 issues:

1 - How do I add an id to the navigator to make the red frame more bolder? because its not clear enough  

2- using      navigatorAutoFade:  true,
  is there simple way that the fade will be on load . and only if the mouse on the canvas  the auto fade will start as now ? 

thanks

**Comment by iangilman** [comment]
For number 1 you can change the border styling with CSS:

```
.openseadragon .displayregion {
  border: 4px solid #900 !important;
}
```

...or you can do it with JavaScript like so:

```
viewer.navigator.displayRegion.style.border = '4px solid #900';
```

For number 2, you want the navigator to not be visible until the user mouses over the canvas? I don't think we have a feature like that, so you'd probably have to modify the OSD code to support it. That said, you might try this at startup:

```
viewer.navigator.setOpacity(0);
```
