### ISSUE TITLE
Convert coordinates from web to image coordinates independent of zoom level

### ISSUE THREAD

**Issue by sandyrao** [openseadragon/openseadragon#1185]
Hi,

I am trying to convert a Rectangle drawn on fabric Overlay (Red rectangle) to Image Coordinates on Viewer in collection mode and back. This is so that we can persist the rectangle coordinates relative to the image, independent of zoom and pan values. (The images may move to another location within the viewport on user action.)

In the sample, the red rectangle is the FabricJS rectangle we need to redraw.
I convert it to web coords, then to Image coordinates. Later on clicking the second button I use the image coordinates to convert back to web and Fabric Coordinates.

**I find that at different zoom values the image coordinates of the same rectangle differs.**

Here is the link to the CodePen we have created to solve this issue. 
[Sample coordinate conversion](http://codepen.io/sreekanthssr/full/LyjKwM)

Steps to replicate:
1. Click Draw Fabric Rect- Red Rectangle is drawn
2. Zoom to a different level
3. Click Redraw Fabric Rect from image.
 The conversion back from Image coordinates is inaccurate.
4. Click Draw Fabric Rect. Same Red Rect is drawn correctly. But on debugging, I can see that the image coordinates have changed now.

```
function fabricToImage()
{
image1 = viewer.world.getItemAt(0);
var rect = new fabric.Rect({
  fill:'red',
  left: 600, top: 1000,  width: 4000, height: 4000
});
canvas.add(rect);
canvas.renderAll();
var webPoint = new OpenSeadragon.Point(canvas._objects[0].oCoords.tl.x, canvas._objects[0].oCoords.tl.y);
imagePoint = image1.windowToImageCoordinates(webPoint);
var webPoint1 = new OpenSeadragon.Point(canvas._objects[0].oCoords.br.x, canvas._objects[0].oCoords.br.y);
imagePoint1 = image1.windowToImageCoordinates(webPoint1);
imageRect = {                  //---------Not accurate. Values change with zoom.
x : imagePoint.x,
y : imagePoint.y,
width : imagePoint1.x-imagePoint.x,
height : imagePoint1.y-imagePoint.y
};

}
function imageToFabric()
{
var osdRectOfTL = new OpenSeadragon.Point(imageRect.x, imageRect.y);
var osdRectOfBR = new OpenSeadragon.Point(imagePoint1.x,imagePoint1.y);
var imageToViewportCoordinatesTL = image1.imageToWindowCoordinates(osdRectOfTL);
var imageToViewportCoordinatesBR = image1.imageToWindowCoordinates(osdRectOfBR);
var width = imageToViewportCoordinatesBR.x-imageToViewportCoordinatesTL.x;
var height = imageToViewportCoordinatesBR.y-imageToViewportCoordinatesTL.y;
canvasOffset=oly._canvasdiv.getBoundingClientRect();
origin = new OpenSeadragon.Point(0, 0);
var image1WindowPoint = image1.imageToWindowCoordinates(origin);
var x=Math.round(image1WindowPoint.x);
var y=Math.round(image1WindowPoint.y);
point = new fabric.Point(canvasOffset.left - x , canvasOffset.top - y );
factor = 1/canvas.getZoom();

var rect1 = new fabric.Rect({
   fill:'green',
   left: (imageToViewportCoordinatesTL.x+point.x)factor,
   top: (imageToViewportCoordinatesTL.y+point.y)factor,
   width: widthfactor,
   height: heightfactor
});

canvas.add(rect1);
canvas.renderAll();
}
```

Please give inputs why this doesn't work and how it can be fixed.

**Comment by iangilman** [comment]
Looking at the Fabric overlay plugin code, it appears that it maintains as its coordinate system the image coordinates of the first image in the collection:

https://github.com/altert/OpenseadragonFabricjsOverlay/blob/master/openseadragon-fabricjs-overlay.js#L109

This doesn't seem ideal to me; I would think that the viewport coordinates would be better. At any rate, it means that for the first image, it's already in image coordinates so you don't need to do any conversion. For the other images, however, you'd need to convert from the first image's coordinate system (where the fabric coordinates are) to some neutral coordinate system and then into the other image's coordinate system (for storage), and then back again for redrawing. 

I recommend using the viewport coordinate system as your neutral base for conversion, rather than the window system, so you don't have to worry about the offset on the page.

**Comment by sandyrao** [comment]
Thanks Ian,

I was able to get the correct image coordinates by passing true to the function calls. The issue I was facing was that image coordinates were wrong on converting from web coordinates.

The reason I am sticking to Image coordinates is because the backend of the application works with respect to the image coordinates. 

```
var viewportPoint = _this.osdCanvas.viewport.pointFromPixel(osdPointOfFabric,true);
var imagePoint = selectedImage.viewportToImageCoordinates(viewportPoint.x,viewportPoint.y,true);
```
                    
Though I am not facing any issues so far on using Image coordinates I will keep your inputs in mind and migrate my code when the FabricOverlay code gets updated to Viewport coordinates.

Thanks a lot for your prompt response. I really appreciate your help and effort on this. :)

**Comment by iangilman** [comment]
Sounds good; glad you found a solution that works!
