### ISSUE TITLE
How to display an image that is being extended with 1 column every second

### ISSUE THREAD

**Issue by buszkiraly86** [openseadragon/openseadragon#1186]
Hi, 

I'm displaying an image that is ~9000x600 pixels. It works fine with a static size, however I don't get the image in its final size, I have to create it by adding small, 1x600 pixel images to it every second.  

I'd like to display the image in its current form all the time. 

What I've tried so far is to convert every incoming image strip into a dzi and add it with addTiledImage. To avoid having every column of the image in a separate dzi I could group the last N columns into 1 dzi, remove the previous ones and add the new one. 
Also I'm having trouble with the zoom when I add a tile. Each time it resets the zooming level.

Anyone ever encountered something similar? Is there a better way to do this?

Thanks!

**Comment by iangilman** [comment]
Wow, that's a pretty wild requirement! Can you tell us more about what the scenario is that's driving this?

If you have to add a new strip every second, it seems like it makes sense not to bother with DZI and just send each strip as a single image. And yes, once you have N columns, you could certainly swap out a bunch of 1px strips for a single N px strip, but still as a single image. 

If you don't need zooming, this could all be done without OSD. If you want zooming, you could use simple image tile sources for the strips:

http://openseadragon.github.io/examples/tilesource-image/

As for resetting the zoom level, how are you adding tiles? It shouldn't reset, depending on what you're doing.

**Comment by buszkiraly86** [comment]
I have acoustic measurement data coming in from an optical fibre and the X axis is time.

Right now I'm adding the image strips as png, not dzi. It works but I'd like to swap out the individual strips for a single N px strip in a way that can't be seen without any flickering. Is it possible to draw over the individual ones and remove them after drawing? 

I've managed to fix the zooming issue with seetting the preserveVIewport to true.

**Comment by iangilman** [comment]
If you need to use preserveViewport, sounds like you're calling `open` every time. You should switch to using the "multi-image" functionality of `addTiledImage`. You can learn more here:

http://openseadragon.github.io/examples/multi-image/

To load the new Npx strip, use `addTiledImage` to load it on top of the old strips. Once it's loaded, you can remove the old strips (using `viewer.world.removeItem`).

**Comment by buszkiraly86** [comment]
Thanks, I can retain the zoom level now and I'm able to replace the images, however I still have some flickering. I'm replacing the old strips in the addTiledImage's success callback after adding the Npx strip. I'd like to remove them when the Npx strip has been drawn completely. I've tried doing it in a listener to the tile-drawn event, but that is called when the image is not fully loaded and it draws a blurred image initially.

**Comment by iangilman** [comment]
It draws it blurred initially even though you're not using DZI? That seems odd to me. 

If you are using DZI, you can use the new "fully loaded" API that's on master (not yet released, though hopefully soon), like so:

```
viewer.addTiledImage({
  ..., // tileSource, etc.
  index: 0, // So it's below the other images
  success: function(event) {
    var tiledImage = event.item;
    
    var fullyLoadedHandler = function() {
      if (tiledImage.getFullyLoaded()) {
        tiledImage.removeHandler('fully-loaded-change', fullyLoadedHandler);
        // Remove other images here
      }
    };
    
    tiledImage.addHandler('fully-loaded-change', fullyLoadedHandler);
  }
});
```

If you're getting the blurring with the simple image tile source, maybe it just needs a couple frames to fade in... you could still load it behind the others and then give it a small setTimeout before removing the others.

**Comment by buszkiraly86** [comment]
I'm using DZI, because I need the zooming.

Thanks, that sounds perfect!

**Comment by iangilman** [comment]
You only need DZI if your image is too large to load in a single tile. The zooming works regardless of what sort of format you're using.

9000x600 is definitely big enough to warrant DZI. 1x600 certainly doesn't need to be DZI. If you're replacing your 1x strips with, say, 600x600 patches, they wouldn't need to be DZI either. Anyway, whatever works. :)

**Comment by buszkiraly86** [comment]
A single 600x600 patch does not need to be a DZI, but if I have the 9000x600 made out of these patches then isn't like having the whole images as a png?

**Comment by iangilman** [comment]
True, so I guess it's just a matter of figuring out how best to make the transition. Probably easiest is to periodically rebuild the entire 9000x600 DZI and reload it under the old one, switching once it's fully loaded. Sorry if I'm adding confusion with all the options!

**Comment by buszkiraly86** [comment]
No worries, it's all clear now :) Thank you for your help!
