### ISSUE TITLE
Virtual Images

### ISSUE THREAD

**Issue by cskwg** [openseadragon/openseadragon#119]
Hi,

is there a way to produce tiles completely from memory?

I already investigated the loadTile/loadImage methods.
They always expect a source string and directly want to load the image from that source.

But I've got a special case where the complete image information is already known (levels, dimensions).
And the pixel information also is already available in the client browser.

I would have to put something into TILE_CACHE, that's no big problem, an artificial URL would be the key.
And tilesMatrix would have to be filled, by level, x and y.

But would it be possible to trick the system into not trying to load images at all and doing a repaint from the already existing images?
What would be the best way to accomplish this?

Kind regards
Karl

**Comment by avandecreme** [comment]
UP. I have been looking into that.
We are currently heavily tied on the tileSource having a url so that is not trivial to get rid of it.

However, there is a dirty (slow) workaround using data URL.

Providing, we modify legacyTileSource to accept urls of the form data:image/, one could load an image from memory.
I tested it with png and svg. However, svg is not zoomable indefinitely this way (pixelization occurs).

Should I make a pull request for this?

**Comment by iangilman** [comment]
@avandecreme Sure, I'd love to check it out.

Here is an idea for bypassing data URLs: what if virtual tile sources produce special URLs from `getTileUrl`, like `'virtual://1-2-3'`. They need to be unique (because we use URLs as cache keys), but otherwise can be opaque. Then, in `loadTile` in tiledimage.js, we check for the `virtual://` in the URL and if present, we call some new "generate your image" method on the tile. 

As for zooming SVGs, probably this is the way to go: 

https://github.com/openseadragon/svg-overlay

**Comment by avandecreme** [comment]
>Here is an idea for bypassing data URLs: what if virtual tile sources produce special URLs from getTileUrl, like 'virtual://1-2-3'. They need to be unique (because we use URLs as cache keys), but otherwise can be opaque. Then, in loadTile in tiledimage.js, we check for the virtual:// in the URL and if present, we call some new "generate your image" method on the tile. 

The goal here is to generate the tiles just when they are needed, correct?
That looks like a hack as well but would provide better performances than encoding/decoding with data URLs.

>As for zooming SVGs, probably this is the way to go:
https://github.com/openseadragon/svg-overlay

Nice plugin! What about having a SvgTileSource as well? That would allow to have a svg under another image in the viewer (and probably other features I can't think of).

**Comment by iangilman** [comment]
Yeah, generate them just when needed. Hmm...I suppose to be really robust we would want the "generate your image" method to be async, so you could do some lengthy process if you needed to without hanging up the animations. 

Seems like the only hack in my proposal is using the `virtual://` URLs as cache keys. I suppose this would be a reasonable first step, and then we could sort out the cache keying later. Of course by then people will have written virtual tile sources that use those URLs...

How would you make an SvgTileSource? Would it render to canvas tiles? Seems a little odd, but I guess that's what you would have to do to get it to go under other images. In your test, how did that work? You said it pixelates, but I suppose it's just a matter of picking your "image size" to match the other content.

**Comment by avandecreme** [comment]
>Seems like the only hack in my proposal is using the virtual:// URLs as cache keys.

Yes, I just don't like the idea to have a URL when actually none is needed. However, I like the fact that it would be easy to implement. :)

>How would you make an SvgTileSource? Would it render to canvas tiles? Seems a little odd, but I guess that's what you would have to do to get it to go under other images.

Yes the svg would be drawn into the canvas.

>In your test, how did that work? You said it pixelates, but I suppose it's just a matter of picking your "image size" to match the other content.

In my tests I just used a legacy pyramid with a svg data url (`data:image/svg+xml;utf-8,<svg>...</svg>`) so there was no logic on the zoom level.

**Comment by acdha** [comment]
@avandecreme Is it really arbitrary if the URL is a serialization of the data needed to generate each tile? Even without the need for a cache-key, it seems like a valuable debugging cue.

**Comment by avandecreme** [comment]
My understanding is it wouldn't be a serialization of the data.
The VirtualTileSource would hold the data, avoiding lengthy serialization/deserialization processes.

**Comment by iangilman** [comment]
Yeah, I don't think we'd want to require that it contain all of the information necessary to generate the tile. It should be unique enough that there won't be cache collisions, though. Bonus points if different tiles with identical content get keyed the same...for instance if you are creating a Mandlebrot tile source, many tiles would be just a single color; ideally those tiles would all have the same URL/cache key. 

>>How would you make an SvgTileSource? Would it render to canvas tiles? Seems a little odd, but I guess that's what you would have to do to get it to go under other images.

>Yes the svg would be drawn into the canvas.

I think we're saying different things here; I'm asking whether the svg would be broken into individual pixelated tiles, and you're saying it would be drawn directly to the viewer canvas, right? Really I think drawing directly to the canvas would be the best approach (and would maybe make that plug-in obsolete), but then I don't think it would be a TileSource; instead it would be a sibling to TiledImage...maybe called SvgImage or something.

**Comment by avandecreme** [comment]
Regarding using data URLs, I just realized that it is already working providing that you specify the mime type like this:

```javascript
tileSources: {
    type: 'legacy-image-pyramid',
        levels: [ {
            url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==',
            width: 5,
            height: 5,
            mimetype: 'image/png'
        } ]
},
```

**Comment by iangilman** [comment]
Nice. Seems like it would be a pretty quick change to detect the `data:` and parse the `image/png` from the URL as a MIME type. 

Supporting data URIs is probably a good thing to do regardless of whether we do a more in-depth virtual tile source. Also, I don't know that I would worry that much about data URIs being inefficient...in terms of what OSD does, loading a new tile isn't the speed bottleneck, and data URIs are already more efficient than loading something from a server.

**Comment by jwcharp** [comment]
I have the Deep Zoom pyramid structure in a database as base64 jpeg strings.
How would I or where would I implement @avandecreme Solution to use dataURL.
I tried to write a custom getTileUrl function to return the base64 string from mySQL DB but that didn't seem to do the trick. any advice? thanks guys.

**Comment by avandecreme** [comment]
Could you detail what requests are you server expecting (is it GET /example-images/highsmith/highsmith_files/level/row_col.jpg ?) and what are his answer (my understanding is base64 strings).

Just curious, any reason to store your pyramids in a database instead of the file system? I would expect it to slow things down.

**Comment by crazyscot** [comment]
Note to anyone coming across this old issue now: a custom tile source may be what you want. See https://openseadragon.github.io/examples/advanced-data-model/

**Comment by iangilman** [comment]
@crazyscot Good point! Thank you for making the connection.

In fact, I think we can close this issue now that that feature exists.
