### ISSUE TITLE
Custom dzi folder structure

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1190]
Hi - while using microsoft software to create dzi its working good and create a 14 folder with 0_1.jpg , 0_2.jpg and so on.

now i m trying to do the dzi from php script but the php create a folder with all the images like the following structure :
0-0-0.jpg
1-0-0.jpg 
1-1-0.jpg 

but without parent folder(1,2...14)

and now the OSD looking for folders like 14/0_2.jpg  

how can I configure the tilesource to take the format the php has created for me ? 

my code now is: 

```
var tileSource =   {
                            Image: {
                                xmlns:    "http://schemas.microsoft.com/deepzoom/2009",
                                Url:      obj.url,
                                Format:   obj.format,
                                Overlap:  obj.overlap,
                                TileSize: obj.tileSize,
                                Size: {
                                    Height: obj.height,
                                    Width:  obj.width,
                                }
                            }
                      };

                openViewer(viewerId,tileSource);
```
thx a lot

**Comment by iangilman** [comment]
If you want to stick with the PHP folder structure, you'll have to make a custom tile source, like so:

http://openseadragon.github.io/examples/tilesource-custom/

Another option, of course, is to make another script that just re-organizes your files from the PHP structure to the regular DZI structure (if you can't modify the PHP script itself to output in a different way).
