### ISSUE TITLE
Rendering large layer images on top of main pyramid

### ISSUE THREAD

**Issue by DrumrollPlease** [openseadragon/openseadragon#1202]
I’m having difficulties finding the proper approach to applying LARGE “layer” images on top the main pyramid.  Initially, I used overlays and it works fine…..for smaller images.

I’m using Microsoft Edge.

  function addOverlay(id, path, originX, originY, width, height, opacity)
  {
    var elt = document.createElement("div");
    elt.id = "div" + id.toString();
    var image = document.createElement("img");

    image.id = "img" + id.toString();
    image.src = path;
    calculateScale();
    image.width = width / scale;
    image.height = height / scale;
    image.style.opacity = opacity;

    elt.appendChild(image);

    viewer.addOverlay({
      element: elt,
      px: originX,
      py: originY,
    });
  }

  function calculateScale() {
    var fullImageWidth = viewer.source.dimensions.x;
    var boundsWidth = viewer.viewport.getBounds().width;
    var shownImageWidth = fullImageWidth * boundsWidth;
    var containerWidth = viewer.viewport.getContainerSize().x;
    scale = shownImageWidth / containerWidth;
  }

…this works fine for smaller images.  But, when the images are large, this approach pretty-much freezes the browser.

I tried this:

  var viewer = OpenSeadragon({
    id: "openseadragon1",
    prefixUrl: "/openseadragon/images/",
    showNavigator: true,
    crossOriginPolicy: "Anonymous",
    tileSources: "https://myblobstorage/mainimage/dzc_output.xml"
  });

  // on a button click...
  function addLayer() {

    viewer.addTiledImage({
      tileSource: "https://myblobstorage/layerimage/dzc_output.xml",
    });
  }

From this, I receive an IndexSizeError.  The new image appears in the navigator but not on the main image.  I can’t pan or zoom.  That’s a wrap.

I added an x and y…

  function addLayer() {

    viewer.addTiledImage({
      tileSource: "https://myblobstorage/layerimage/dzc_output.xml",
      x: 1,
      y: 1
    });
  }

… and the image then appears on row 1, column 1 in the world view, not on top of the main image offset by 1 pixel x & y.  I can zoom a bit and pan a bit, until that dreaded IndexSizeError occurs, and that’s a wrap.

My question is how can I overlay pyramid on top of another pyramid….not side by side.  I have several layers that can be toggled on top of the main image that are very large and should be treated as pyramids as well.

Any help, links to examples, or approach ideas would be greatly appreciated.

Thank you.

**Comment by iangilman** [comment]
You're absolutely on the right track. Regarding positioning, you have to use viewport coordinates, which are basically arbitrary, but all of your images need to agree with each other. Here's more on the coordinate systems:

http://openseadragon.github.io/examples/viewport-coordinates/

In your code you're providing an x and y (but not a width) for the second image, but not for the first. You can also provide coordinates for the first image (the one in your call to `OpenSeadragon`) like so: 

```
  tileSources: {
    tileSource: "https://myblobstorage/mainimage/dzc_output.xml",
    x: 0,
    y: 0,
    width: 1
  }
```

As for the IndexSizeError, that's probably #1033, which has been fixed on master but not released yet. Can you try building the latest from master to verify? Note that if that doesn't fix it there's also #1069, but that doesn't sound like what you've got.

**Comment by DrumrollPlease** [comment]
Thank you for your guidance.  It’s been a great help.  I do have a couple of follow-up questions:

I realize there is a canvas issue in IE/Edge that is throwing a IndexSizeError, and you mentioned there is a fix in the latest master.  Is there a plan to release OSD soon?  If not, what is the process of "building the latest from master"


? (I’m a GitHub noob).

Second, I have a “layering” capability complete with my current implementation.  It goes basically something like this:

    viewer.open(baseMapPath);

    for (var i = 0; i < layerCount; i++) {
      if (layerVisible[i] === "True") {
        viewer.addTiledImage({
          tileSource: layerPath[i],
          opacity: layerOpacity[i]
        });
      }
    }

It seems as though calling this logic is the only viable route I can take when doing something as trivial as removing a tileSource (layer) from the viewer, or even changing the opacity or z-order for a given tileSource.  Is this a correct assumption, using this big hammer approach?  It would be nice if someday there were maybe a removeTileSource.  Also, calling viewer.open returns the viewer to its “Home” view, losing the zoom level and position.  I know I can return the viewer with a fitBounds, but that appears a bit visually awkward.

Thanks, again.

**Comment by iangilman** [comment]
We're close to a new release, but it may still be a few weeks. Here's the milestone we're working on:

https://github.com/openseadragon/openseadragon/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.3.0

To build it yourself, you'll have to grab the latest code, which you can do with git or you can even just download a zip of it from the front page of this repository: 

https://github.com/openseadragon/openseadragon

Once you have the latest code, you can build it following these instructions:

https://github.com/openseadragon/openseadragon/blob/master/CONTRIBUTING.md

As for modifying the tiled images after they've been added, no problem. There are a number of ways of accessing the tiled images. This example goes through the complete set of images and sets their opacity to 0.5:

```
var count = viewer.world.getItemCount();
var i, tiledImage;
for (i = 0; i < count; i++) {
  tiledImage = viewer.world.getItemAt(i);
  tiledImage.setOpacity(0.5);
}
```

You can also remove them once you have a tiled image like so:

```
viewer.world.removeItem(tiledImage);
```

**Comment by DrumrollPlease** [comment]
Perfect!  Thanks again for your help!
