### ISSUE TITLE
best way to start full-screen?

### ISSUE THREAD

**Issue by chconnor** [openseadragon/openseadragon#1204]
Hi -- I was wondering what the best/smartest way to open a viewer in full screen mode would be.

I tried calling viewer.setFullScreen(true) but I'm apparently calling it before the viewer is ready (right after it is created). Calling it manually from the developer console (after the image has loaded) works fine.

I could run setFullScreen() after a delay, but I have a feeling I should be waiting for some appropriate event, or maybe there is an option I can pass at the creation of the viewer?

Thanks for any ideas! And thanks for the great software, too.

**Comment by iangilman** [comment]
The browser's fullscreen API (`requestFullScreen`) requires that it be initiated by a user gesture (such as a click). Evidently calling it in the console counts as a user gesture. At any rate, as far as I'm aware there's no way to start a page in fullscreen without some sort of user interaction. This is a security restriction in the browser unrelated to OpenSeadragon.

**Comment by chconnor** [comment]
I see; thanks for the response! It sounds from this like you believe that calling from a script with a delay would not work. Please correct me if I've misunderstood.

**Comment by iangilman** [comment]
Yes, that's my understanding from reading about the browser's full screen API, and from some quick experimentation. Feel free to experiment as well, but be sure to try it on multiple browsers!

Here's some more info if you want to dig deeper: 

https://stackoverflow.com/questions/19355370/how-to-open-a-web-page-automatically-in-full-screen-mode
