### ISSUE TITLE
Zoomout when image width > screen width

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1205]
Hi . how could I retrieve the real  image height and width after the viewer is loaded ?
is viewport provide any helpers for that ? 

the problem is as follows:
The OSD got new image but the image width is 4000px with 1400px height for example . -  the OSD div is 600px height and screen =1920px width.
 
In that case I'd like to zoomout  in some way (with a sample formula or changing the defaultzoomlevel)   to  get the whole image in the container .
for now I can not set a default zoom 0.4 or even 0 to fit to the viewer for example because there are images that comes with different height and width . and I need to scroll to see the whole image or zoom out manually.

thanks a lot for your support

**Comment by iangilman** [comment]
For that sort of thing you can just work entirely in viewport coordinates (without worrying how big the div is in web coordinates or how big the image is in image coordinates). For more info, see:

http://openseadragon.github.io/examples/viewport-coordinates/

To find the viewer bounds in viewport coordinates, use:

```
var viewerBounds = viewer.viewport.getBounds();
```

To find the image bounds in viewport coordinates (assuming you want the first image in your collection), use:

```
var imageBounds = viewer.world.getItemAt(0).getBounds();
```

To zoom to a particular area, set up a rectangle however you'd like and use fitBounds:

```
viewer.viewport.fitBounds(rect);
```

**Comment by johnico** [comment]
HI thanks
var imageBounds = viewer.world.getItemAt(0).getBounds();  
how can I use that variable and how can I build an rectangle object to send him to the fitbounds function ?


thanks

**Comment by iangilman** [comment]
Yes, there's an `open` event you can use, and the second parameter to fitBounds skips the animation. Like so: 

```
viewer.addHandler('open', function() {
  viewer.viewport.fitBounds(rect, true);
});
```

You could probably detect if it's already fitting, but you don't need to bother since fitBounds itself basically does that detection as well.

**Comment by johnico** [comment]
HI @iangilman    its not throw an error buy sometimes on click or moving between the images. (closing and opening the viewer) its not working  , and its working great only on refresh

and when I add timeout its working but with animation (the image make animation to fit the viewer)

thanks

**Comment by iangilman** [comment]
What happens when you remove the setTimeout? What if you change it to just a 1 millisecond timeout?

**Comment by johnico** [comment]
with 1 ms - its working like without - sometimes works and sometime no (in click/refresh )

**Comment by iangilman** [comment]
So 1 millisecond is the same as no timeout, but 100 milliseconds is different? Good to know.

I still don't understand what happens with no timeout though.

**Comment by johnico** [comment]
with DZI/tif images its takes 50-80 ms to get the images and then i have to set timeout  and this is looking bad because there is some jumps until the fits working 

without timeout you will need to zoom out  to see the whole image

**Comment by johnico** [comment]
im trying to detect when the image or tile is loaded  then to fit the bounds without timeout 

        ```
  var tileSources = {tileSource:"http://localhost/cgi-bin/ImageServer.cgi/test.tif.dzi"};

           openViewer(viewerId,tileSources);
              
           viewer1.addHandler('tile-loaded', function(eventSource, item, user) {
    
                 var imageBounds =viewer1.world.getItemAt(0).getBounds();
                 viewer1.viewport.fitBounds(imageBounds, true);  

           });
```

this is work but in zoom it make the event again so i tried to remove the handler  like that but it also needs a timeout  and not working if you internet is slow for exmaple


`  viewer1.addHandler('open', function() {
        setTimeout(function () {
            viewer1.removeAllHandlers('tile-loaded');
        },400);
    });`



how can I fix it ? 
thanks

**Comment by iangilman** [comment]
This should work:

```
var tileSources = {tileSource:"http://localhost/cgi-bin/ImageServer.cgi/test.tif.dzi"};

openViewer(viewerId,tileSources);
  
var tileLoadedHandler = function(eventSource, item, user) {
  viewer1.removeHandler('tile-loaded', tileLoadedHandler);
  var imageBounds =viewer1.world.getItemAt(0).getBounds();
  viewer1.viewport.fitBounds(imageBounds, true);  
};

viewer1.addHandler('tile-loaded', tileLoadedHandler);
```

**Comment by johnico** [comment]
Hi thanks  @iangilman 
its works better but it looks like  sometimes when i refresh a few or change images it not working as it should
is there any way to make sure that the tileLoaded will works after and the image will be fit to bounds ?

**Comment by iangilman** [comment]
Strange. I'd have to see a repro to understand what's going on.

**Comment by johnico** [comment]
Seems like it's working better with jpg then  tif/dzi
Is any other function to make sure the tif is fully loaded ?
I will try to provide example with tif( with cgi)
