### ISSUE TITLE
Dinamically show ReferenceStrip?

### ISSUE THREAD

**Issue by VipSaran** [openseadragon/openseadragon#1210]
Is it possible to show a reference strip aftert Viewer is created?

E.g. for first "page" (of tiles) I don't want it shown, but when I use Viewer.open() afterwards, I want also to enable the RS.

Re-creating the Viewer with different options needed or I can do it some other way?

**Comment by iangilman** [comment]
It looks like you can leave `showReferenceStrip` false when you first create the viewer and then change it afterwards: 

```
viewer.showReferenceStrip = true;
```

...but nothing will happen until you call `viewer.open`, at which point it'll create a reference strip for you. Looks like you can do the same in reverse as well... the key is that the change only takes effect after calling open. This isn't exactly documented behavior, but it's what it looks like the code will do.

**Comment by iangilman** [comment]
...of course it could be nice to have an actual API for creating/removing the reference strip.

**Comment by iangilman** [comment]
Fixed by #1213
