### ISSUE TITLE
Improve discovery for "options" documentation [was Q: eliminate 'full page' button?]

### ISSUE THREAD

**Issue by jrochkind** [openseadragon/openseadragon#1217]
Is there a way to turn off the "full page" button so it doesn't appear at all?

I don't want this button. I've been having trouble figuring out how to disable it, so it no longer appears at all.

**Comment by matthew-jack** [comment]
Adding `showFullPageControl: false` to your viewer options should do it! Like so:
```javascript
      var viewer = OpenSeadragon({
          id: "openseadragon",
          prefixUrl: "openseadragon/images/",
          showFullPageControl: false
      });
```

**Comment by jrochkind** [comment]
Thanks, that does work!

Do you know if this is doc'd anywhere? Believe it or not, I spent a few hours trying to find this in docs and source code, but I could just be a bad searcher. 

It might be good to list it on https://openseadragon.github.io/examples/ui-binding-custom-buttons/, as that's what google mainly wanted to take me to trying to google for this.

**Comment by matthew-jack** [comment]
I checked as well and didn't see anything in the homepage docs. However that seems to be more of a quickstart guide and when you really start getting into OpenSeadragon you're going to have to work with the API docs (https://openseadragon.github.io/docs/).

I don't know who to tag about this but I've seen @avandecreme work on documentation issues? Maybe he can make a judgement about this or point someone else here.

**Comment by jrochkind** [comment]
I def spent quite a bit of time with the API docs without finding this, but like I said, maybe I'm just a poor searcher.

**Comment by jrochkind** [comment]
at any rate, now this issue is there for someone googling or searching GH issues. :)

**Comment by jrochkind** [comment]
It is there in the API docs, now that I know what to search for, at the very bottom of this page:

https://openseadragon.github.io/docs/OpenSeadragon.html

In a section headered "Options", where it's unclear exactly what those options apply to if you're trying to skim/browse/search. That's a _long_ page.

**Comment by jrochkind** [comment]
I had seen that API doc page, but I don't think I ever realized there was an "Options" section waiting for me all the way at the bottom haha. Now I know, cool!

**Comment by iangilman** [comment]
@jrochkind Thanks for alerting us to the documentation issue! It's hard to know what's intuitive when I'm already used to where everything is. 

FYI, the "options" section is linked from the intro text on the front page of https://openseadragon.github.io/docs/ but I suppose it could be made more prominent, since it is very important. 

It might also make sense to link to the options section from the various intro pages like https://openseadragon.github.io/examples/ui-binding-custom-buttons/.

For anyone who wants to make these modifications, the doc front page is located here:

https://github.com/openseadragon/site-build/blob/master/doc-home.md

...and the example pages are here:

https://github.com/openseadragon/site-build/tree/master/www

Note that they're both in the "site-build" repository, not this one.

**Comment by jrochkind** [comment]
thanks! All might be fine how it is, with so many options and so much API, some people are just going to miss some things. Thanks for the quick answer here @matthew-jack; that's one workaround to people (or at least me) not finding the docs!

I'll consider a doc PR though, thanks for the repo pointer.

**Comment by jrochkind** [comment]
Hey, about just a rotate-right button, but not a rotate-left button? Can't find this as an option.

**Comment by iangilman** [comment]
True. You can turn the rotate buttons on or off, but you can't have only one of them.

I suppose it could be hacked, by using the custom button binding feature:

http://openseadragon.github.io/examples/ui-binding-custom-buttons/

Bind the rotate left button to an empty div or something, so it's essentially invisible. 

`rotateLeftButton: 'my-empty-div-id'`

**Comment by jrochkind** [comment]
Cool thanks. That's pretty much what I ended up doing as a workaround. 

~~~js
  // we only want a rotate-right, not rotate-left. Can't figure
  // out how to get OSD to do that, and not try to fetch rotate-left
  // images, except giving it a fake rotate-left
  // button, sorry!
  var dummyRotateLeft = document.createElement("div");
  dummyRotateLeft.id ='dummy-osd-rotate-left';
  dummyRotateLeft.style.display = 'none';
  document.body.appendChild(dummyRotateLeft);

  this.viewer = OpenSeadragon({
   // ... 
    rotateLeftButton:   "dummy-osd-rotate-left",
