### ISSUE TITLE
Sometimes doesn't process ready items in queue if another item fails.

### ISSUE THREAD

**Issue by imagolive** [openseadragon/openseadragon#1218]
If you add multiple images by passing DZITileSources to addTiledImage and one of the fails then some of these other images get stuck in the queue and are not processed correctly.

I've got a fix waiting in a branch but this is my first time submitting to a public project. Not sure about the right etiquette. 

When I tried to push the branch into the repository and create a pull request, it was denied "remote: Permission to openseadragon/openseadragon.git denied to endevea.".

How do you become a collaborator? Can somebody help with the right steps?

**Comment by iangilman** [comment]
Good catch! We'd love to have a patch for that! 

To submit a pull request, you need to make a fork of this project into your own account. Then you can make a pull request from your fork back to this repository. For more information on making forks and pull requests, see:

https://github.com/openseadragon/openseadragon/wiki/Making-a-Pull-Request

I'm looking forward to seeing your patch!

**Comment by iangilman** [comment]
Fixed by #1229
