### ISSUE TITLE
Q: proxying keyboard events

### ISSUE THREAD

**Issue by jrochkind** [openseadragon/openseadragon#1219]
So I have an openseadragon panel embedded in my own app-like interface. 

openseadragon's keyboard event handlers of course require the openseadragon-canvas to be browser-focused, because of course that's how DOM keyboard events work. 

I would love to be able to sort of 'proxy' keyboard events, so even if openseadragon-canvas isn't focused, but my own UI is, and catches keyboard events from the user, I can send them on to the openseadragon-canvas, to take advantage of the great OSD keyboard event handlers, in my own UI. 

But I haven't been able to figure out any way to do that. I've tried just sending events to the openseadragon-canvas object with JQuery trigger; doesn't seem to work. I've looked at the API and source code for the MouseTracker (which actually handles keyboard events too), and realized it's available from osd_object.viewer.innerTracker, but still haven't been able to figure anything out. 

Any ideas? Is this possible?

**Comment by michaelw3** [comment]
hi,
why not use the `window.addEventListener("keydown", function(ev){}):` and bind it to whatever 
function you trying to do in OSD?
I did navigation with the keyboard arrows this way, and need no focus on the viewer this way.

**Comment by jrochkind** [comment]
Thanks @michaelw3 . Aha, that's probably the right way to do it! 

I wasn't sure if the MouseTracker had any special code for accelerating based on length of time between keydown/keyup etc that I didn't want to have to duplicate. The built-in pan works very well. But I'm not super familiar with keydown/keypress handling in dom/js -- and if it worked for you, that's a good sign I should just do that!

Can you give me any hints as to where I find the relevant OSD functions and how to call them for pan and zoom? Or if you wanted to share your code for handling keyboard arrows like you say, it would def be helpful to me!

**Comment by jrochkind** [comment]
I found the relevant functions in OSD for handling keyboard events. They don't do anything _too_ fancy, but it would be nice to be able to call them directly to just proxy functionality to them. Haven't figured out a way yet, still working on it, not sure if they are lost in a closure inaccessible or not. 

https://github.com/openseadragon/openseadragon/blob/e81e30c81cd8be566a4c8011ad7f592ac1df30d3/src/viewer.js#L2414-L2499

**Comment by jrochkind** [comment]
Aha, I did it! Here's how you can proxy keyboard events to standard OSD keyboard handling. This example using JQuery. 

~~~js
    var osd; // assume thing returned from OpenSeadragon constructor
    $(my_container).on("keypress", function(event) {
      osd.viewer.innerTracker.keyPressHandler(event);
    });
    $(my_container).on("keydown", function(event) {
      osd.viewer.innerTracker.keyHandler(event);
    });
~~~

**Comment by jrochkind** [comment]
hmm, except now that's not quite working for me. I swear I had it working! Anyway, I will leave this issue closed, but try to remember to post here when I have it fully working, for anyone else searching and looking for a solution. I was close!

**Comment by michaelw3** [comment]
lets say i take the key `z` for zooming 
then i would after creation of the viewer add a function like this - 
```
function zoomInFunction(){
  var currentZoom = viewer.viewport.getZoom(true);
  var zoomTo = currentZoom + 0.2;
  viewer.viewport.zoomTo(zoomTo);
}
```
i added 0.2 steps of zooming you could change to your needs-

which i would trigger inside the event-listener like so
```
window.addEventListener("keydown", function(ev){
  switch (ev.keyCode) {
    case 90: //z
        zoomInFunction();
      break;
  }
});
```
which will trigger the function above and zoom as long as you press the key.

as for panning I think its going to be a bit more complex, because you need to choose a point where you pan to, if I understood correct.

**Comment by jrochkind** [comment]
Ah, I see, there's private stuff that normalizes browser events to OSD events. 

https://github.com/openseadragon/openseadragon/blob/master/src/mousetracker.js#L1543-L1623

It's private, can't really call it myself. Could copy and paste stuff. But at this point, might as well just copy and paste the implementations I found at https://github.com/openseadragon/openseadragon/blob/e81e30c81cd8be566a4c8011ad7f592ac1df30d3/src/viewer.js#L2414-L2499 , to get equivalent behavior. 

Okeydoke!

Theoretically, I think it would be useful if the MouseTracker onKeyPress, onKeyDown, and onKeyUp functions were exposed, so you could just proxy to them or otherwise call them to trigger keyboard events "just as if the user had done them when the canvas was focused". But they ain't, and the implementation isn't so hard to copy.

**Comment by iangilman** [comment]
@jrochkind I think that's about the size of it. Exposing the implementations you found (rather than keeping them locked in closure confinement) is the subject of https://github.com/openseadragon/openseadragon/issues/489. If you're up for taking a whack at it, it would be a great addition.
