### ISSUE TITLE
viewport coordinates for multi image

### ISSUE THREAD

**Issue by shanealsingh** [openseadragon/openseadragon#1220]
Hi,

I have a series of dzi's. Each are different sizes and have a x and y value. Example:

![screen shot 2017-06-14 at 3 54 14 pm](https://user-images.githubusercontent.com/1868594/27158057-bb28e204-5119-11e7-8c9f-52b6c8dc148d.png)

```    
1.  0, 0, 2000, 3000
2.  2352, 304, 2000, 1680
3.  0, 3520, 1000, 1680
4. 1500, 3520, 1000, 1680
5. 2880, 2368, 1352, 1152
6. 4592, 2160, 2000, 1680
```
I'd like to position the tiles using the the original x and y values above instead of arbitrary viewport coordinates. I've tried:

```
        var i, tiledImage;
        var count = viewer.world.getItemCount();
        var tilesData = [...];

        for (i = 0; i < count; i++) {
          var tileData = tilesData[i];
          var imagePoint = new OpenSeadragon.Point(tileData.x, tileData.y);
          const viewerPoint = tiledImage.imageToViewportCoordinates(imagePoint);

          tiledImage = viewer.world.getItemAt(i);
          tiledImage.setPosition(viewerPoint);
        }
```

This works great and positions everything correctly except when my dzi's have different width and  height values. Looking at the code inside TiledImage it looks like _viewportToImageDelta uses the source width and height to calculate a ratio which is never relative to an origin say {0, 0}.

Is there a way I can position tiles that are different sizes using the x, y values defined above?

Any help will be much Appreciated!

**Comment by shanealsingh** [comment]
I've found `viewport.deltaPointsFromPixels`, but the positioning is still not correct

**Comment by shanealsingh** [comment]
Update: `viewport.deltaPointsFromPixels` does place the tiles in the correct location. It was throwing me off because I didn't realize that I also have to set the width. So using `viewport.deltaPointsFromPixels` and resetting the width on the tile displays correctly.

**Comment by iangilman** [comment]
Glad you found a good solution! Another option is to use your original x and y values as your viewport coordinates. Because viewport coordinates are arbitrary, you can choose for them to be whatever you want. By default they go from 0 to 1, but they could just as easily go from 0 to 10,000. 

Anyway, sounds like you've got things working :)

**Comment by IrisLiuCY** [comment]
@iangilman where can i set the viewport coordinates, say from 0 to 10.000? I am looking for ways to convert the image pixels to the viewport coordinates.

**Comment by iangilman** [comment]
@IrisLiuCY The viewport coordinates are implied by how you lay the images out. For instance, in your case you would do: 

```
var viewer = OpenSeadragon({
  ...
  tileSources: {
    tileSource: url,
    width: 10
  }
});
```

...which specifies that your image will stretch from 0 to 10, and therefore your viewport coordinates go from 0 to 10.
