### ISSUE TITLE
how to zoom into a specific area and play this video of the area?

### ISSUE THREAD

**Issue by lihan2016nju** [openseadragon/openseadragon#1233]
i want to make  multi-frame images  zoom in and zoom out , and play them like a video. now i can play a video and when i stop playing ,i can zoom in and zoom out the image. here is the example:  http://cite.nju.edu.cn/resize.html
i wanna ask how to work on switching between video and zoom while keeping the zoom constant and also getting a better focused image, so i can zoom into a arae and play the video of this arae?

**Comment by iangilman** [comment]
Looks like you've made some progress on this and the conversation continues in #1238, correct?
