### ISSUE TITLE
Support for Squarespace?

### ISSUE THREAD

**Issue by jadoff630** [openseadragon/openseadragon#1235]
Hello,

I am wondering if anyone has had success embedding into squarespace? They have custom code embedding.

thanks

**Comment by iangilman** [comment]
I've done it before, so it's certainly possible. I don't remember the details. I believe we had to store the images on a different server, since Squarespace doesn't have the sort of file storage where you can maintain a folder structure (this is assuming you're using tiled images). Beyond that, it's just a matter of sticking the appropriate JavaScript somewhere on your Squarespace page.

Are you running into particular issues?

**Comment by jadoff630** [comment]
Thanks. 

I think my questions are as follows:
- how can I link the openseadragon script when I cannot store openseadragon.min.js on Squarespace directly?
- After placing the images on a different server, I would just link them with their URL correct? 
- Lastly, would there be a way to build the viewer in an html editor on my machine, pushing it to Github and then embedding the code from github into Squarespace?

**Comment by jadoff630** [comment]
Still having issues getting the JS onto my site. I tried placing it in the custom code under settings and it doesn't work. Beyond that, I am not sure what would be a good place to store image folder. 

As I mentioned before, would I be able to link to the JS and Image folder if I place them in a Git repository? Also, for images, would I need to store the images that come in the zip of Openseadragon?

Thanks

**Comment by abrlam** [comment]
Does Squarespace support iframe?  If so, you can host your images on our site and then embed them back to your website.  http://zoomable.ca/

**Comment by iangilman** [comment]
You do need to link to both the OpenSeadragon script and the images that come with OpenSeadragon. Your best bet is to link to the CDN hosted versions. You can pick from jsDelivr and CDNJS. You can find the links here: 

http://openseadragon.github.io/#download

And yes, when you host your content images on another server, you link to them with their URL. One complication is that ideally you'll make sure that server has CORS set up so you can link directly to the DZI file (assuming you're using DZI). If you can't set up CORS on the server (or the server doesn't already have CORS set up), there are workarounds I can help you with. 

If you want to build your viewer in GitHub and host it there, you can use GitHub Pages for that. You could then link to just the JavaScript hosted on GitHub Pages, or you could use an iframe to embed the whole GitHub Page viewer. For that matter, you could use GitHub Pages to host your images if you want.

**Comment by jadoff630** [comment]
If I want to host the viewer on github pages and then pull the whole thing into squarespace as an iFrame, how would I go about doing that, as that seems like the best bet. I created this simple test in Dreamweaver and it seems to work... https://github.com/jadoff630/Zoomableimages_squarespace/blob/master/index.html. I uploaded the entire folder to a repository on github. 

What would the next step be?

thanks

**Comment by jadoff630** [comment]
Update, I got my test up on gitpages (https://jadoff630.github.io/Zoomableimages_squarespace/) but now there is an error for the images - the file displays correctly within Dreamweaver. how can I rectify this error and then use iframe to bring into Squarespace?

Thanks for all your help

**Comment by iangilman** [comment]
Looks like you got the images to load now? Do you have it working in square space yet? Looks like it's definitely possible based on a quick google search: 

https://www.google.com/search?q=squarespace+embed+iframe

You'll just want to add something like so wherever square space allows HTML code: 

```
<iframe src="https://jadoff630.github.io/Zoomableimages_squarespace/" width="800" height="800">
```

**Comment by jadoff630** [comment]
Thank you, I did get it all to work and embedded into Squarespace. I forgot to update this. 

thank you for all your help!

**Comment by iangilman** [comment]
Excellent; good to hear!
