### ISSUE TITLE
using fully-loaded event in 2.2.1  (UPDATE: not working in 2.3.0)

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1247]
Hi how can I use fully=loaded event in 2.2.1 version  without merge?
I tried to take the tiledImage.js to the openseadragon.js  but it throws errors ,
I tried to take the changes from the commit itself but the event is  not fired  

thanks

**Comment by lihan2016nju** [comment]
@johnico Maybe you want to use `fully-loaded`event to play multi-images continuously, or make the zoom smoother, right? If not, can you describe what functions do you want to achieve?

**Comment by iangilman** [comment]
The fully loaded event is on master, so you could build from this repository. We should be releasing it along with 2.3.0 tomorrow though (see https://github.com/openseadragon/openseadragon/issues/1094), so you can wait for that. 

Note that we don't support TIFF files, and that at least two major browsers (Chrome and Firefox) don't support TIFF either. You should stick with JPEG or PNG.

**Comment by johnico** [comment]
Is TIFF with cgi-bin will no longer works on latest chrome version ? What is the alternative for tiff   (30MB size of image )

**Comment by michaelw3** [comment]
@johnico why do you need TIFF? i don't see any advantage of it over JPG in web-based environment

**Comment by iangilman** [comment]
@johnico How big in pixels is the image? If it's less than 2000px wide, you can just convert it into a single JPEG and use that. Otherwise you'll want to tile it into DZI or Zoomify, which also consist of JPEG.

**Comment by johnico** [comment]
15000px, high resolution 
I meant I'm using IIPIMAGE server , I think it's convet tiff to small jpegs
Is the new version supports that feature ?

**Comment by lihan2016nju** [comment]
@johnico The fully-loaded-change event works,right? I also should use it, but it seems that i did not call the event correctly. how do you use the fully-loaded event?
`viewer.addHandler('fully-loaded-change', function(){
		  setTimeout(function() {
            viewer.world.removeItem(viewer.world.getItemAt(1));
            addFrame();            
          }, 100);`
thx!

**Comment by johnico** [comment]
@iangilman   Hi the envets are not fired at all

```
    viewer1.addHandler('fully-loaded-change',function(a){
            console.log("x");
    });

    viewer1.addHandler('fully-loaded',function(a){
            console.log("y");
    });
```

**Comment by iangilman** [comment]
Apologies if the documentation wasn't clear! The `fully-loaded-change` event is fired on the individual TiledImage, not on the Viewer. This will work, for instance: 

```
        viewer.world.addHandler('add-item', function(addItemEvent) {
            var tiledImage = addItemEvent.item;
            tiledImage.addHandler('fully-loaded-change', function(fullyLoadedChangeEvent) {
                console.log('fully loaded', fullyLoadedChangeEvent.fullyLoaded);
            });
        });
```

And yes, @johnico having IIPImage image convert your TIFF into JPEG tiles is great; that's definitely supported.

**Comment by iangilman** [comment]
Note that `fully-loaded-change` fires every time the "fully loaded" status changes, either from false to true or vice versa (which will happen when the user navigates). You can also find out the current status of the image by calling `getFullyLoaded()` on it... remember, that's a call for the TiledImage as well.

**Comment by johnico** [comment]
hi @iangilman  thanks , the additem event you described here give me the option to know when the last tile is loaded? for example while using IIPImage i would like to know when its totally loaded

**Comment by iangilman** [comment]
It's the `fully-loaded-change` event that tells you when the image is fully loaded. I'm just using the `add-item` event to make sure we're watching all of the tiled images.
