### ISSUE TITLE
How to change Image URL of multi-image dynamically?

### ISSUE THREAD

**Issue by abhisb** [openseadragon/openseadragon#1250]
I need to change the image URL of a tiledImage dynamically which should change the image as well without triggering zoom or any other events.  Also the zoom level and position of viewport shouldn't change while changing the image URL. I have seen that `viewer.preserveViewport = true;` let it persist the zoom level. Is there a way to change the tiledImage URL without replacing a new tiledImage with the current one?

**Comment by iangilman** [comment]
It seems to me that the cleanest way to get this effect is to add a new tiled image and remove the old one. You can see an extreme example of that here: 

https://codepen.io/iangilman/pen/PjdyGv

To maintain the image location, you'll want to get the bounds of the old image and specify the same x, y, width for the new image.

Using this technique the zoom and pan won't change at all. You don't need `preserveViewport`.

**Comment by abhisb** [comment]
Thanks @iangilman It worked :+1: 

One more question:

Can we load a tiled image by setting opacity 0 or positioning behind other tiles in-order to seamlessly show that tiled Image immediately without lag after removing another tiled Image?

**Comment by iangilman** [comment]
Yes, with the new `preload` flag from 2.3.0 you can indeed! I've updated https://codepen.io/iangilman/pen/PjdyGv to include preload usage.
