### ISSUE TITLE
Fitbounds() is not working while split the screen and keep the zoom 

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1252]
Hi , I have a wired issue while I using fitBounds 

```
 var tileLoadedHandler = function(eventSource, item, user) {
        viewer1.removeHandler('tile-loaded', tileLoadedHandler);
        var imageBounds =viewer1.world.getItemAt(0).getBounds();
        viewer1.viewport.fitBounds(imageBounds, true);
    };

    viewer1.addHandler('tile-loaded', tileLoadedHandler);
```

The center image is working great while loading , but when you click  on "Show" button (and split the screen to present 2 images in 50% width) , the images are not fit to the bounds and the zoom is too far (it should take the all blank space as in the center because in that case we loose some areas).

When you zoom in a little bit and then go back to full image the zoom is too close , 
so the problem is that there is no correlation between the full image and when I split them.

To demonstrate that you can uncomment the line 144/145 in the JS section(codepen), then show/hide the image and you will see now the bounds fit correctly and looks good(take the all available place depends the image height) , but it is not possible to fit bounds while click because we are losing the zoom .

this is my codepen :

https://codepen.io/anon/pen/PjgzXV 

How can I fix that    maybe on of the option is to save the zoom , do a fitbounds and set zoom again ? iI think the problem is in the maintainzoom() function and  foreceRedraw()  but don't know how to solve it 

Screenshot for the initial zoom : http://imgur.com/a/ls7ab 
Screenshot for the how it should looks like when split  : http://imgur.com/a/L09jO

thank a lot for your support

**Comment by iangilman** [comment]
I'm sorry, I don't quite understand. It seems that uncommenting lines 144/145 fixes the problem... what's the issue with doing that?

**Comment by johnico** [comment]
@iangilman   why getBounds is undefined when I call it after viewer.open() ?  is any option to do it without timeout ?

**Comment by iangilman** [comment]
viewer.open is asynchronous, so the tiled image doesn't exist right away. You have to wait until the `open` event, like so:

```
viewer.addHandlder('open', function() {
  var tiledImage = viewer.world.getItemAt(0);
  var bounds = tiledImage.getBounds();
});
```

**Comment by johnico** [comment]
Hi thanks,I added this block along with the tile-image event 

    viewer1.addHandler('open', function() {
        var tiledImage = viewer1.world.getItemAt(0);
        var bounds = tiledImage.getBounds();
        viewer1.viewport.fitBounds(bounds, true);
    });


working but sometime it still did not make the fitBounds (on few refresh) ,

**Comment by iangilman** [comment]
Sounds like something in your code is fighting with something else. Try disabling things temporarily to isolate the problem. 

Btw, if you're just doing a fitBounds with the image's bounds, that should be the same as `viewer.viewport.goHome`, which should be happening automatically with `open` (unless you have `preserveViewport` turned on).
