### ISSUE TITLE
[OpenSeadragon.Spring.springTo] target must be non-zero for exponential springs

### ISSUE THREAD

**Issue by ozgunlu** [openseadragon/openseadragon#1254]
I was using v2.1 to view the JP2K images with IIP ImageServ. I could see the tile edges, so i try to update my openseadragon to v2.2.1, but i got some errors. Then i waited to v2.3.0.

Today i updated my viewer to v2.3.0. It works well, but when i try to zoom with mouse wheel or double click to image, image disappear. When i watch the console, i got an error :
Assertion failed: [OpenSeadragon.Spring.springTo] target must be non-zero for exponential springs

I can zoom on the image using standart buttons, only mouse events has problem. Also i couldn t see zoom factor. 

And last think i still see the TILE EDGES. Are there any option to hide them ?

**Comment by iangilman** [comment]
Interesting! I assume you don't have the same issue when you go to http://openseadragon.github.io and play with that image? Can you share a link to yours?
