### ISSUE TITLE
Reference Error: $ is not defined -while loading the DZI xml file -OpenSeaDragon

### ISSUE THREAD

**Issue by shivarajub2010** [openseadragon/openseadragon#1255]
![image](https://user-images.githubusercontent.com/29970059/28270909-ba162190-6b24-11e7-923e-5e0530e781ea.png)

Below is the code snippet that iam using to load and display DZI xml files. I am getting reference error:$ is not defined. 
`  var dziFilesUrl = '//DZI//dzc_output_files//';

    // Change this to the contents of the .dzi file from your server. 
    var dziData = '<?xml version="1.0" encoding="utf-8"?><Collection MaxLevel="8" TileSize="256" Format="jpg" NextItemId="1" xmlns="http://schemas.microsoft.com/deepzoom/2008"><Items><I Id="0" N="0" Source="dzc_output_images/worldmap.xml"><Size Width="5000" Height="3752" /><Viewport Width="1" X="-0" Y="-0" /></I></Items></Collection>';

    // This converts the XML into a DZI tile source specification object that OpenSeadragon understands. 
    var tileSourceFromData = function (data, filesUrl) {
        var $xml = $($.parseXML(data));
        var $image = $xml.find('Image');
        var $size = $xml.find('Size');

        var dzi = {
            Image: {
                xmlns: $image.attr('xmlns'),
                Url: filesUrl,
                Format: $image.attr('Format'),
                Overlap: $image.attr('Overlap'),
                TileSize: $image.attr('TileSize'),
                Size: {
                    Height: $size.attr('Height'),
                    Width: $size.attr('Width')
                }
            }
        };

        console.log(dzi);
        return dzi;
    };

    // This creates the actual viewer. 
    var viewer = OpenSeadragon({
        id: 'openseadragon1',
        prefixUrl: '//DZI/',
        tileSources: tileSourceFromData(dziData, dziFilesUrl)
    });`

```
Please let me know what I need to correct.
Iam using latest OpenSeaDragon Version 2.3.0 and Asp.NET MVC5 to fetch the DZI xml file.

Below is the DZI xml file data
`<?xml version="1.0" encoding="utf-8"?>
<Collection MaxLevel="8" TileSize="256" Format="jpg" NextItemId="1" xmlns="http://schemas.microsoft.com/deepzoom/2008">
<Items>
<I Id="0" N="0" Source="dzc_output_images/worldmap.xml">
<Size Width="5000" Height="3752" />
<Viewport Width="1" X="-0" Y="-0" />
</I>
</Items>
</Collection>`

**Comment by shivarajub2010** [comment]
I resolved the issue as I added the script link shown below:
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

However I have new issue - "Unable to open [Object Object]:Unable to load TileSource" when I load the same xml as mentioned in the issue.

**Comment by iangilman** [comment]
Yes, I suppose I should mention that that example requires jQuery. Glad you got that sorted.

Looks like the DZI file you're using is actually a DZC file (Deep Zoom Collection). OpenSeadragon does not support DZC files (See https://github.com/openseadragon/openseadragon/issues/67). You'll need to export a single DZI instead and use that.
