### ISSUE TITLE
How to loading screen in Openseadragon?

### ISSUE THREAD

**Issue by alibaver** [openseadragon/openseadragon#1262]
Hi, I have a problem. I would like to display the uploading of images in openseadragon with the loading screen. how can I do it. I'm happy if you help me.Sorry for my english thank you

**Comment by iangilman** [comment]
By default OpenSeadragon draws your image in low resolution while it's loading the high resolution tiles. Sounds like instead of that, you want it to say "Loading" until it's done loading everything, is that correct? 

By the way, are you loading a single image or a bunch of them? For a single image you could do something like so: 

```
// Assuming you have functions called showLoading and hideLoading

var viewer = OpenSeadragon(options);

showLoading();

viewer.addHandlder('open', function() {
  var tiledImage = viewer.world.getItemAt(0);
  if (tiledImage.getFullyLoaded()) {
    hideLoading();
  } else {
    tiledImage.addOnceHandler('fully-loaded-change', hideLoading);
  }
}
```

**Comment by alibaver** [comment]
The first thing I want to do is do not load the picture and show the loading screen after I press the button.

**Comment by iangilman** [comment]
Cool. The code above should work for that. Let me know if you have questions about it.

**Comment by makoychan** [comment]
also this is my code to load another image to replace to old one, i want to show a loading progress bar while the next drawing is being loaded

var tileSource = {
                        type: 'image',
                        url: imgURL,
                    }
                    viewer.open(tileSource) ;

**Comment by iangilman** [comment]
`getFullyLoaded` indicates whether tiles are missing for the image in question. In the case of the "image" tileSource which you're using, there's only one tile, and I think it's already loaded by the time the "open" event is fired. It looks like `getFullyLoaded` is giving the wrong result in that case... I've filed #1456 for that now.

At any rate, as long as you're just using "image" tile sources, you can just ignore `getFullyLoaded` and rely on the "open" event.
