### ISSUE TITLE
Overlays with links example isn't working

### ISSUE THREAD

**Issue by Riclim** [openseadragon/openseadragon#1263]
In the example [Overlaying Complex HTML](http://openseadragon.github.io/examples/ui-overlays/) the link "Preceding Tiles" doesn't work. In all browsers I've tested, clicking on it behaves like a regular zoom click. The target address is correctly shown on the status area, though. Am I missing anything, or would you have a working example? Thanks.

**Comment by iangilman** [comment]
Good point! We should fix that example; thank you for reporting it. 

Here's an example of it working: 

https://codepen.io/iangilman/pen/mEkKaY

**Comment by Riclim** [comment]
Thank you very much for the example!

**Comment by iangilman** [comment]
This is now fixed by: https://github.com/openseadragon/site-build/pull/177
