### ISSUE TITLE
Drag Stuck with setMouseNavEnabled

### ISSUE THREAD

**Issue by pipriles** [openseadragon/openseadragon#1264]
Hello, i have an issue when disabling panning with this line of code

```typescript
this.viewer.setMouseNavEnabled(!state);
```

Sometime works good sometimes not, if the first thing you click is the Sketch button and then disable it and you try to drag the image, the image sticks with the mouse.

I think it has something to do with #518. But i can't still figure out what can i do here.
Is there another way to disable panning or i am missing something?

Here is a [demo](https://ng-osd.firebaseapp.com/)

Thank you.

**Comment by pipriles** [comment]
Ok i fixed my problem i had this:

```typescript
new OpenSeadragon.MouseTracker({
			element: viewer.drawer.element,
			moveHandler: (e) => {

				/* Disable Mouse tracker for mobile */
				if(!e.isTouchEvent && this._line !== undefined) {
	
					pos = e.position;
					pos = viewer.viewport.pointFromPixel(pos);
					pos = viewer.viewport.viewportToImageCoordinates(pos);

					this._line.set({x2: pos.x, y2: pos.y});
					this.fabricCanvas.renderAll();
				}
			},
		});

```

And changing `viewer.drawer.element` to the id of the content div solved the problem...
Very strange issue i had, any ideas?

**Comment by iangilman** [comment]
Interesting… I don't know exactly why that would cause that issue, but I'm glad you found a solution!
