### ISSUE TITLE
panTo with FabricJs Values

### ISSUE THREAD

**Issue by ozgunlu** [openseadragon/openseadragon#1267]
I was using Annotorious plugin and panTo point was work well.

Here is, how annotorious save points : 
x - '0.42422035102551103'
y - '0.3253031087435106'
width - '0.4537798539161866'
height - '0.36942334261125437

And now i am using FabricJS, and fabricjs get real coordinates from picture : 
x - 11935.451922877512 
y - 15028.463425087202 
width - 197.5370068138218  
height - 197.5370068138218 

PanTo method pan to outside of image. 
viewer.viewport.panTo(new OpenSeadragon.Point(center_x, center_y)); 

So how can i fix this problem ? I dont know to convert what ?

**Comment by iangilman** [comment]
@ozgunlu I assume you got this sorted out, since you closed the issue? Btw, I understand the fabricJS plugin has recently been updated to use the viewport coordinate system, which might be helpful.
