### ISSUE TITLE
Open DZI

### ISSUE THREAD

**Issue by zloysmiertniy** [openseadragon/openseadragon#1269]
Hello.

I am trying to open a .dzi file and no error is being displayed and I still see no image. I tried both implementing getTileUrl and simply giving the tileSources parameter.

First I create my viewer like this:

```
var fixed_viewer = OpenSeadragon({
  id: "fixed_viewer",
  prefixUrl: "openseadragon/images/",
  ...
});
```

Then I want to open the dzi which is stored in the same server where the html is.

I use either: 

```
fixed_viewer.open({
  height:95680,
  width:80656,
  tileSize: 2048,
  minLevel:0,
  maxLevel:17,
  getTileUrl: function( level, x, y ){
    return "http://www.cb.uu.se/~tissuemaps/images/portugal/A-2554/vips_files" + "/" + level + "/" + x + "_" + y + ".png";
  }
});
```

or simply:

`fixed_viewer.open("http://www.cb.uu.se/~tissuemaps/images/portugal/A-2554/vips.dzi");`

It shows no error on console but I can't still see the image. I don't fully understand if there is a problem with crossorigin, or what should I do, reformat the url, and how to tell it to find the images in a directory outside the current script. 

The directory structure of my server is the following:

public_html/images/portugal/A-2554/vips.dzi
public_html/images/portugal/A-2554/vips_files
public_html/viewer/viewer.html
public_html/js/viewer.js (script calling the dzi)

and my simple html:

```
<html>
   <head>
      <title>TM control points</title>
      <meta content="text/html; charset=utf-8" />
      <!--OpenSeadragon-->              
      <script src="js/openseadragon-bin-2.3.0/openseadragon.min.js"></script>
      <link rel="stylesheet" href="css/tmcpmain.css">
   </head>
   <body>
      <div id="container">
         <div id="fixed_viewer">
         </div>
         <div id="moving_viewer">
         </div>
      </div>
   </body>

      <script src="js/viewer.js"></script>
</html>
```

I realize it is a very simple question but I havent been able to even visualize the image. I would appreciate any help.

Thank you

**Comment by zloysmiertniy** [comment]
I just discovered that the viewer is not inheriting the height of the container. Now I only see the thumbnail, but still cant manage to load the levels. My guess is it is pointing to the wrong place but I don't understand how or where it is looking for the tile sources.

**Comment by iangilman** [comment]
@zloysmiertniy Looks good to me. When you say you can see the thumbnail but can't load the levels, what does that mean? You try zooming in and you don't get anything else? Maybe try turning `debugMode` on? 

Can you share the project somewhere so I can take a look directly?

**Comment by zloysmiertniy** [comment]
A rapid protoype is here http://www.cb.uu.se/~tissuemaps/tmcpoints/viewer.html

It is alright now. I meant that I saw the thumbnail but then checked that the size of the canvas was 0 because it seems that it doesn't inherit the size of the container if it is specified as : min-width or min-height in the css.

**Comment by iangilman** [comment]
Okay, good to hear you got it sorted out :)
