### ISSUE TITLE
Question mouse tracker events

### ISSUE THREAD

**Issue by apricea4** [openseadragon/openseadragon#1274]
Thank you so much for a great tool that is easy to use, I have enjoyed working with it.  I just have a question about mousetracker handlers.  I am diving into JS without a whole lot of background.  How might I go about wiring up a handler to listen for left click down, hold and release on a touch screen?   Right now I am using a mousetracker and event.position is coming up undefined.  Do I have to go through a viewer handler or can I go straight to the mouse tracker?  Here is my code.  

![osdhandlers](https://user-images.githubusercontent.com/22583746/28843875-8b803dfe-76b7-11e7-9b17-8e895a20705d.PNG)

Edit:  I tried doing the same thing with canvas-click, drag and drag-end but touch is not firing, only pen and mouse.  Has anyone had any success capturing touch events through canvas events?  Are there tools in OSD that can help me determine if the click is outside the image bounds so I can use JS touch without it registering touch to the ref strip or nav box?
Thanks

**Comment by iangilman** [comment]
Strange... so pressHandler is getting called, but the event.position is undefined? That should be working fine for touch (and mouse). What device are you on? Can you share a link to the issue in action?

**Comment by apricea4** [comment]
I am using a Surface Edge Pro 3.  Actually only the moveHandler is getting called when I move the mouse or click the mouse but clicking and dragging my finger does nothing.   The event position is undefined when I look at developer tools and the function that is called via moveHandler gives me an error "cannot read property attr of undefined" but when I alert(position.x) there is a value there.  I am attempting to use SVG-overlay plugin to draw lines.  I'll try and put something together to show the issue in action but you won't see my finger moving around, you might see a little darkened area that the Surface shows but it is hard to see.

**Comment by iangilman** [comment]
Interesting. Have you tried on other touch devices? It would be great to narrow it down.

**Comment by apricea4** [comment]
I haven't tried any other devices but after not getting the mouse trackers to work, I ended up using the canvas events solely and not attaching a mouse tracker to them and it worked great.  Thank you @iangilman.

**Comment by iangilman** [comment]
Great to hear!
