### ISSUE TITLE
How to proper show translation/transcript along with the original digitisation?

### ISSUE THREAD

**Issue by dureyingenieria** [openseadragon/openseadragon#1275]
I am looking for some library (like this one) to show digitised ancient manuscripts, but I would love to show the translation and/or the transcript of the text next to the original image at the same time. What alternatives do you guys think I have? I am talking about thousand of documents for several cultural institutions. I really appreciate any idea.

**Comment by iangilman** [comment]
Do you want the translation text to appear in the same viewer, panning and zooming with the scan? Or do you want it in a scrolling panel next to the viewer? If it's the former, you could use OpenSeadragon along with one of the overlay plugins to position the text where you want it. If it's the latter, you'd just do the text in regular HTML / JavaScript, and you can use OpenSeadragon events to synchronize with navigation. You'd have to build some of the functionality either way, as I'm not aware of an off the shelf solution for exactly what you're looking for. 

Have you looked into http://projectmirador.org/? It uses OpenSeadragon, and I believe it has some sort of annotation functionality, though I don't know if it's exactly what you need.
