### ISSUE TITLE
second flickering image below some zoomed simple images

### ISSUE THREAD

**Issue by haheute** [openseadragon/openseadragon#1276]
Below some of the zoomed images on my website, I see a flickering duplicate of the photo when zooming in or out (with mousewheel).
I have tried with firefox, chromium, opera and midori (all on linux), and disabled the compression of the js code, which did not help. (minified with [JSMin](https://github.com/douglascrockford/JSMin) in a bash script)

version:
```
yarn list v0.28.4
└─ openseadragon@2.3.0
```

Maybe somebody has an idea what could cause such behaviour..
Here is the javascript, used to start OpenSeadragon:
Thanks for any help.

```
                viewer = OpenSeadragon({
                    id: 'osd',
                    prefixUrl: '/img/layout/openseadragon/',
                    tileSources: {
                        type: 'image',
                        url:  '/img/graf/f/flvr{{ $photo->id }}.jpg'
                    },
                    toolbar:'toolbardiv',
                    showZoomControl:false
                });
```

**Comment by iangilman** [comment]
Strange! Can you share a link to it in action? 

@avandecreme Looks like this has to do with the ImageTileSource; any thoughts?

**Comment by haheute** [comment]
Thank you. I see the second photo when zooming on this page: https://flavuur.de/photos/10005

**Comment by iangilman** [comment]
Sure enough! Very strange. I've made a CodePen for it: 

https://codepen.io/iangilman/pen/BdQVEN

You don't even need to zoom; it's already got a duplicate when it first loads. I've provided the URL to a different image that loads fine. I wonder if it has to do with the aspect ratio. 

@avandecreme Would you mind taking a look at this?

**Comment by haheute** [comment]
I found one more, perhaps it helps: https://flavuur.de/photos/9870

**Comment by avandecreme** [comment]
Argh, it is `TileSource.getTileAtPoint` bitting us again.
Because of a floating point calculation error this method returns that the tile 0,1 must be drawn instead of 0,0.
I created #1280 for this.

**Comment by iangilman** [comment]
@avandecreme thank you for the fix! 

@haheute The fix is merged into master... can you give it a try?

**Comment by haheute** [comment]
I can't find the openseadragon.min.js. It does not seem to be in yarn, yet.
How can I install it without yarn? Thank you very much

**Comment by iangilman** [comment]
Wonderful, thank you for testing it, and I'm glad it fixes the issue. :)
