### ISSUE TITLE
newbee question: How to do an offline application in c#/.NET?

### ISSUE THREAD

**Issue by basqddfred** [openseadragon/openseadragon#1277]
Hi there, 
I hope I do not bother you too much with a 100% new bee question. I'd like to use "deep zoom" within my offline standalone Windows .NET application (not silverlight, but .NET forms only) programmed in C#. I already used the DeepZoomTools.dll to generate a subdirectory which contains all these nice litte images which may certainly could be used for deep zooming. So far my project looked promising. But now I do not know how to continue. What I dream about is to program an image viewer (not silverlight based and not dependend of an internet browser) within my own little application. What I really need is a library which offers some functions for example returning the bunch of images needed for display my "deep zoom image" at current zoom or drag position.

Do you know if such a library compatible with .NET / C# is available somewhere?
(If only commercial libraries are available, I'd appreciate a hint, also)

Kindest regards and happy programming

**Comment by iangilman** [comment]
Can you use JavaScript in your application, or include a web component? If so, OpenSeadragon should work for you. 

I'm not aware of C# native zooming libraries, though they may certainly exist. Perhaps other people have thoughts they can add.

**Comment by iangilman** [comment]
Well, it's definitely possible. I don't know that much about the C# world, so it may already exist. If it doesn't, though, you should be able to write it yourself based on the logic from OpenSeadragon. 

Do you already have an image tiling system in OpenGL, and you just need to load the deep zoom format? Or do you also need to build the tiling and zooming code?

**Comment by basqddfred** [comment]
Hi IanGilman,
thanks a lot for your encouraging words. What I'd really love to implement is to "feed" my OpenGL engine with the bunch of images being output from the OpenSeadragon library or other library which does that for a DeepZoomImageformat. I'd do the tiling by my own, afterwards. 

Something like that:
Bitmaps [ ] BunchOfBitmaps= HiNiceDeepZoomImageLibraryGetMeTheBunchOfImagesYouThinkAreNeeded(IamHereAtX,IamHereAtY,ThatIsMyZoom,ThereIsWhereIwantToGo,WithThisZoom);

If something commercial is on market (library to solve this), any hint is appreciated.
Kind regards

**Comment by boskar** [comment]
http://deepzoom.codeplex.com/ ?

**Comment by avandecreme** [comment]
I wrote a similar library in Java https://github.com/usnistgov/pyramidio (see the `Read a DZI pyramid` section).
Considering how close Java and C# syntax are, maybe you can translate it in C# for your needs?

**Comment by basqddfred** [comment]
Hi AvandeCreme,
WOOOOOOOOOOOOOOW, thanks a lot for your valuable hint. I'll give that a try. It really sounds promising. Super :-)
