### ISSUE TITLE
Adding a control to the native navControl element, iOS isn't happy.

### ISSUE THREAD

**Issue by superbland** [openseadragon/openseadragon#1281]
I've got a couple of things that I want to add to the `viewer.navControl` element; a basic download link and something else which will toggle a background colour. It is quite messy, but I wanted to benefit from the generic auto-hiding, the standard hover states on the default buttons, without having to write that in myself as I just wanted these to sit alongside and compliment the standard buttons.

So I appended them as children:

```
  downloadImg.src = '/js/vendor/openseadragon/images/download_rest.svg';
  downloadLink.appendChild(downloadImg);
  downloadLink.href = iiifBaseURL + lunaID + '/full/full/0/default.jpg';
  downloadLink.setAttribute('download', document.querySelector('h1').innerText + '.jpg');

  viewer.navControl.parentElement.parentElement.classList.add('nav-control');
  viewer.navControl.appendChild(downloadLink);

  backgroundToggle.setAttribute('id', 'toggle-background');
  viewer.navControl.appendChild(backgroundToggle);
```

This works fine on desktop browsers and an Android tablet I've been testing on (Samsung Galaxy Tab A, Android 6), however on iOS (10.3.3), the controls I have added are not tappable and I have no idea why.

Adding these elements somewhere else seems to work as expected, so I assume there might be something else going on here that I'm not aware of?

**Comment by iangilman** [comment]
I'm guessing it's running against the complicated gesture tracking code we have. It might work to use a MouseTracker similar to this pen:

https://codepen.io/iangilman/pen/mEkKaY

@msalsbery Any thoughts?

**Comment by superbland** [comment]
@iangilman There is an awful lot going on in this part of the code so I wasn't able to figure out exactly where this might be coming from, but that sounds like a good guess to me.

Thanks for your suggestion, this is useful to know about. For my case there may be some more refactoring involved if I implemented it this way (e.g. I will lose the download attachment behaviour).

Another option I'm considering is just creating my own element outside of the viewer, putting everything in that and positioning it over the top, that would at presumably sidestep this issue.

**Comment by iangilman** [comment]
Hmm... I'm not sure how to make a download link work in that context, but I think it might be possible. 

Anyway, yes, creating your own toolbar might be the way to go at this point. Sorry that stuff isn't more extensible!
