### ISSUE TITLE
Image colors not updated immediately after filter application

### ISSUE THREAD

**Issue by imoutsatsos** [openseadragon/openseadragon#1290]
I have create a demo application using the OSD viewer for reviewing multi-channel digital microscopy images. 
Demo here: https://imoutsatsos.github.io/osdUseCaseHCS/

The  viewer is using a variety of OSD features (multi-image, overlays) as well as two OSD plugins (filtering, annotations). More detailed description here: https://github.com/imoutsatsos/osdUseCaseHCS

The primary use for this demo is for collaborating with others to resolve some issues, especially with the annotations plugin. 

Nonetheless, I'm experiencing an issue with the static image sources, that I did not notice while the images were served from a IIIF image server (Cantaloupe: https://github.com/medusa-project/cantaloupe)

When I  apply various filters via the provided controls, such as brightness, contrast or channel color, the images seem to revert to the original gray scale, and I need to 'nudge' the viewer (pan or zoom) for color to re-appear. When the images were served from the image server, such updates were displayed in color immediately. I should note that colorization is the one filter that uses the CamanJS library.

I would appreciate it if you could provide some feedback for troubleshooting.

Best regards
Ioannis

**Comment by iangilman** [comment]
Interesting. The fact that it clears up when you pan makes me think you just need to add a `viewer.forceRedraw()` after the color change. On the other hand, the fact that it only happens with static sources makes me wonder if there's some sort of caching issue in the browser. 

Have you tried filing an issue on the repository for the filtering plugin? Looks like @avandecreme was involved in it... he might have some thoughts.

**Comment by avandecreme** [comment]
I noticed some issues with CamanJS cache as well.
Have you tried re-implementing those filters without using CamanJS?
