### ISSUE TITLE
Are tiles cached?

### ISSUE THREAD

**Issue by apricea4** [openseadragon/openseadragon#1292]
When viewing an image with OSD and zooming in then panning around, are the tiles cached so if you were to go back to a recent zoom level and position it would already have it?  Or is it a fresh get every time?
Thanks guys.

**Comment by WilliamCarlos** [comment]
Tiles are cached: https://openseadragon.github.io/docs/OpenSeadragon.TileCache.html

**Comment by apricea4** [comment]
Thank you @WilliamCarlos
