### ISSUE TITLE
How to slow down zoom in/out speed?

### ISSUE THREAD

**Issue by umairm638** [openseadragon/openseadragon#1294]
I'm using openseadragon version 2.2.1 in which when we zoom in or out it does too much zooming. So I need to make it to do less zoom on single click. Below is my code:

    var osd_config = {
    id: "viewer",
    prefixUrl: prefixUrl,
    preserveViewport: true,
    showNavigator: false,
    visibilityRatio: 1,
    minZoomImageRatio: 0.4,
    defaultZoomLevel: 0.9,
    zoomInButton: "zoom-in",
    zoomOutButton: "zoom-out",
    homeButton: "home",
    fullPageButton: "full-page",
    nextButton: "next",
    previousButton: "previous",
    showRotationControl: true,
    gestureSettingsTouch: {
        pinchRotate: true
    },
    tileSources: []
    };
```
feedMe = getUrlVars()['feedme'];
if (feedMe) {
    osd_config['tileSources'].push(image + INFO);
} else {
    osd_config['tileSources'].push(image + INFO);
}
var viewer = OpenSeadragon(osd_config);
viewer.addHandler('open', function () {
    var targetZoom = 0.9;
    var imageBounds = viewer.world.getItemAt(0).getBounds();
    var viewportBounds = viewer.viewport.getBounds();
    var imageAspect = imageBounds.width / imageBounds.height;
    var viewportAspect = viewportBounds.width / viewportBounds.height;
    var aspectFactor = imageAspect / viewportAspect;
    var zoomFactor = (aspectFactor >= 1 ? 1 : aspectFactor) * targetZoom;
    console.log(zoomFactor + ' ' + imageBounds.width);
    viewer.viewport.defaultZoomLevel = zoomFactor / imageBounds.width;
    viewer.viewport.goHome(true);
}); 
```

**Comment by iangilman** [comment]
You want the `zoomPerClick` option. The default is 2; maybe try 1.5?

**Comment by umairm638** [comment]
@iangilman thanks it worked.
