### ISSUE TITLE
Navigator bounds are outside the navigator image

### ISSUE THREAD

**Issue by AsmaAq** [openseadragon/openseadragon#1295]
I used navigator in a div next to the main viewer div so I cant set navigator height and width since it doesn't take effect in this case. 

But Navigator green border is always bigger than its parent container which fits with the image, and If i added code to manually reset height,width,top,left seems openSeaDragon itself reset everything to its calculations, 

like shown below:
![image](https://user-images.githubusercontent.com/14885860/29749273-5d47f386-8b30-11e7-8469-6460deb93154.png)

Can you please check if there is anything we can do to set it correctly? 

Thanks

**Comment by iangilman** [comment]
Interesting. Can you share a repro, perhaps in CodePen? 

Off the top of my head, have you tried adding `position: relative` to the div that contains the navigator?

**Comment by AsmaAq** [comment]
Yes its position is relative, 

I think its hard to share code now, but i need to know how openSeaDragon determine the navigator tileImage width and height? And what is the relation between tileSource width,height and this div (id + "_displayregion") If you please?

Thanks in advance

**Comment by iangilman** [comment]
The navigator sizes itself based on the viewer, and depending on what navigator settings you've specified. Here's how it sizes itself on startup: 

https://github.com/openseadragon/openseadragon/blob/master/src/navigator.js#L178-L193

...and here's how it resizes itself when you resize the window:

https://github.com/openseadragon/openseadragon/blob/master/src/navigator.js#L289-L309

Based on what you're seeing, it sounds like it's somehow getting an incorrect size for the viewer. 

As for how it sizes the tiled image, once the navigator has figured out how big it should be, it zooms the tiled image to fit itself. In other words, the tiled image and its tile source have no impact on the size of the navigator; they just scale to fit the navigator.

**Comment by AsmaAq** [comment]
Ok so width is calculated this way:
this.element.style.width  = Math.round( viewerSize.x * options.sizeRatio ) + 'px';

For the configuration; here the openSeaDragon Object:


OpenSeadragon({
            id: "thumbnailBlock_body_1",
            showNavigator: true,
            navigatorId: "thumbnail_left_container_1",
            debugMode: false,
            constrainDuringPan: true,
            showZoomControl: false,
            showHomeControl: false,
            showFullPageControl: false,
            showRotationControl: false,
            showNavigationControl: false,
            minZoomImageRatio: 0.5,
            navigatorPosition: "ABSOLUTE",
            tileSources: {
               ......
            }

And here is the HTML for navigator Container: 

![image](https://user-images.githubusercontent.com/14885860/29861174-10db091e-8d71-11e7-9b6d-68a3643ced4a.png)

Then openSeaDragon Element which is "thumbnail_left_container_1-displayregion" width is calculated to around 247px ! and that's what i am not understanding . how it become this big while the container is only 100px ! 

![image](https://user-images.githubusercontent.com/14885860/29861300-7e302026-8d71-11e7-8550-6e06e8b436a4.png)

For navigatorSizeRatio I didn't send it in configuration since its default is 0.2, I also tried changing it to another values but it looks almost the same here. 


Thanks for your help !

**Comment by iangilman** [comment]
Hmm... I think if you're specifying a `navigatorId` you're not supposed to specify a `navigatorPosition`; those two things might be fighting with each other. Try removing the `navigatorPosition` and see what happens.

**Comment by AsmaAq** [comment]
I think the issue is in this case calculations doesn't fit the container or the expected width I need, since logically according to this : this.element.style.width = Math.round( viewerSize.x * options.sizeRatio ) + 'px';

viewerSize.x = 1257 and sizeRatio is the defaullt (0.2) which is almost 247 ..  ? And i need it to be almost 100px. 

So What should i do ? Maybe we can play with SizeRatio? notice that in my application image is not always same so the navigator should be always compatible with it !

Thanks,
Asma

**Comment by AsmaAq** [comment]
Regarding "navigatorPosition"; I added it to test if it can change anything, but container looks the same in both cases.

**Comment by iangilman** [comment]
You should never be hitting the sizeRatio line; it doesn't happen if `_resizeWithViewer` is false, which is the case when `anchor` is `ControlAnchor.NONE`, which is the case when you provide a `navigatorId`. 

Also note that the `displayRegion` (the element that has the ID `thumbnail_left_container_1-displayregion`) is the little red box that indicates where you're zoomed to. I suppose if you were to zoom very far out it would make sense that it would be sized larger than the navigator.

Sorry I don't have much more to go on here... I'm having a hard time visualizing what might be contributing to the problem.

**Comment by AsmaAq** [comment]
Actually the whole image is displayed with no zooming! that's why I need it to fit the navigator image. 

I will try more for work around ..

Thanks for the help appreciated 👍

**Comment by iangilman** [comment]
Okay, well, it's not normal behavior. If you get stuck, try making a simplified repro in something like CodePen so you can share it (and maybe also isolate the issue). Good luck!
