### ISSUE TITLE
add overly on the fly in multi-image mode

### ISSUE THREAD

**Issue by michaelw3** [openseadragon/openseadragon#1296]
Hi everyone,
In the thumb-bar plugin that I'm trying to build, i want to draw an overly outline on the image selected by a mouse click.
right now i get the index of the image that has been clicked and also its position and then scroll it to the middle of the bar, but I'm not sure how to apply an overly at the click moment and then scroll it with the item, and also remove the overly from the previous image. 
actually I'm not sure at all how to add an remove overly to an element on the fly.

any help is appreciated!
Michael

**Comment by michaelw3** [comment]
**UPDATE**

i managed to attach and unattach the overly but it's only on the sides no border on the top and bottom 
using `outline` in css when i changed it to `border` i get also the top but no bottom.

**Comment by iangilman** [comment]
Interesting... I assume you're using Viewer.addOverlay? I'm not sure why the border wouldn't be working. Do you have a repro to share?

**Comment by michaelw3** [comment]
thanks @iangilman sadly i only have a repro locally, i tried to upload it to github pages but it's so inconvenient, they don't let me upload more than 10 files and using DZI makes it even worth with all these tiles and subfolder.
hopefully I'll buy a small server soon I want to use the IIIFServer instead of DZI because it's space friendly.
this is how it looks so far- 
![2017-08-28 1](https://user-images.githubusercontent.com/8994886/29784908-646239c0-8c2e-11e7-9bfe-a9d877ab22f7.png)

**Comment by iangilman** [comment]
Strange that you're having trouble with GitHub pages... that's what we're using for https://github.com/openseadragon/example-images/tree/gh-pages and that repository has 11,000+ files, totaling approximately 1.23 GB. 

Anyway, it's looking good so far. It looks like that screenshot doesn't include the border issue?

**Comment by michaelw3** [comment]
@iangilman thanks for the info, so i guess i have to dig in more into the GitHub pages.. is there an FTP option of uploading files? 

in the Screenshot i don't get the bottom border..

**Comment by iangilman** [comment]
I'm not aware of an FTP option for uploading files to GitHub; typically you'd just use Git. Are you having trouble pushing files to your repository? 

How are you drawing that strip at the bottom? Is that the built in reference strip, or something custom you're making?

**Comment by michaelw3** [comment]
@iangilman  thanks, I think i had a problem pushing it, i'll try it again.

It's the custom one i'm trying to build a plugin for:
https://github.com/openseadragon/openseadragon/issues/1045

**Comment by iangilman** [comment]
Great! 

Well, looks like the rectangle you've given the overlay is too tall. Can you just shorten it up some?
