### ISSUE TITLE
Simple images repeated

### ISSUE THREAD

**Issue by alexandermendes** [openseadragon/openseadragon#1297]
Possibly related to #1113, simple images can be repeated if the viewer container happens to be larger than the image.

See https://jsfiddle.net/2bkw2rLb/

**Comment by iangilman** [comment]
@alexandermendes Yes, looks like the same issue. Can you try building the master branch here and see if it fixes it?

**Comment by microbrent** [comment]
I had the same issue. It appears to be fixed on the master: [cd4c4d3](https://github.com/openseadragon/openseadragon/commit/cd4c4d38ed6938339beb623e34e80aea30a2373c)

**Comment by alexandermendes** [comment]
Ok cool, I'll try to double check today
