### ISSUE TITLE
showNavigationControl disables custom buttons

### ISSUE THREAD

**Issue by arnoson** [openseadragon/openseadragon#1310]
when adding custom buttons via the options
```
const viewer  = OpenSeadragon({
	// ...
	zoomInButton: "zoom-in",
	zoomOutButton: "zoom-out",
	showNavigationControl: false,
	// ...
})
```
they wont work. When I remove the 'showNavigationControl: false' they do work. But I want to hide the NavigationControl and only use my custom buttons

**Comment by iangilman** [comment]
Hmm... if you do a view source on http://openseadragon.github.io/examples/ui-binding-custom-buttons/ it looks like one thing that's not mentioned on the page is the use of `toolbarDiv`... if you use that (and don't use `showNavigationControl`) does that fix the issue?

**Comment by arnoson** [comment]
when specifying the toolbar div openseadragon tries to add the controls I havent maually set. I haven't included the control button images on my page, but now openseadragon tries to load these images and I get errors.
My situation: I only want my custom zoom-in and a zoom-out buttons and nothing else.
Now I use hidden divs and specify all controls in the options and it works! An option to just disable the unneeded buttons would be cool! Anyway thanks so much for this awesome viewer

**Comment by iangilman** [comment]
Excellent, glad to hear it :)
