### ISSUE TITLE
GestureSettings are ignored

### ISSUE THREAD

**Issue by swanijam** [openseadragon/openseadragon#1312]
I'm trying to disable pinch-zooming on our OSD viewer and running into some trouble. 

Here's how I'm setting pinchToZoom to false:
```

viewer = new OpenSeadragon.Viewer({
            ....
            immediateRender: false,
            animationTime: 1.5,
            tileSources: dzc_file,
            gestureSettingsMouse:   { scrollToZoom: true,  clickToZoom: true,  dblClickToZoom: false, pinchToZoom: false,  flickEnabled: true, flickMinSpeed: 120, flickMomentum: 0.25, pinchRotate: false, dragToPan: true },
            gestureSettingsTouch:   { scrollToZoom: false, clickToZoom: true, dblClickToZoom: false,  pinchToZoom: false,  flickEnabled: true,  flickMinSpeed: 120, flickMomentum: 0.25, pinchRotate: false, dragToPan: true },
            gestureSettingsPen:     { scrollToZoom: false, clickToZoom: true,  dblClickToZoom: false, pinchToZoom: false,  flickEnabled: true, flickMinSpeed: 120, flickMomentum: 0.25, pinchRotate: false, dragToPan: true },
            gestureSettingsUnknown: { scrollToZoom: false, clickToZoom: true, dblClickToZoom: false, pinchToZoom: false,   flickEnabled: true,  flickMinSpeed: 120, flickMomentum: 0.25, pinchRotate: false, dragToPan: true }
        });
```

But this isn't having any effect. Im still able to pinch zoom in any browser or device. Am I misunderstanding how I'm meant implement these options?

**Comment by iangilman** [comment]
Hmm... that definitely seems like it should work! Can you share a link to this in action, maybe on CodePen? 

Btw, if you want to target just a single setting, you could do this after you create the viewer: 

```
viewer.gestureSettingsTouch.pinchToZoom = false;
```

**Comment by jj2883** [comment]
I am running into the same issue. Could you please help me?
@iangilman 

I have also tried the single setting method, but it does not work.

I am currently working with django and openseadragon 2.4.2

**Comment by iangilman** [comment]
I've just verified that it's working for me on the latest OSD (on iOS Safari) with both of the techniques listed above:

```
gestureSettingsTouch:   { scrollToZoom: false, clickToZoom: true, dblClickToZoom: false,  pinchToZoom: false,  flickEnabled: true,  flickMinSpeed: 120, flickMomentum: 0.25, pinchRotate: false, dragToPan: true },
```

...or:

```
viewer.gestureSettingsTouch.pinchToZoom = false;
```

There must be some other issue at play. Can you share a repro (in CodePen or something like that) to show how you are getting the problem?

**Comment by jj2883** [comment]
@iangilman 

The issue was fixed when I used a different example .dzi file.

I think it has to do with levels of the .dzi file, but I am not sure.

**Comment by iangilman** [comment]
Strange. Well, glad you got it sorted out.

**Comment by msalsbery** [comment]
Closing this, feel free to re-open if issue persists!
