### ISSUE TITLE
Collection mode wrap support

### ISSUE THREAD

**Issue by AMercer87** [openseadragon/openseadragon#1314]
I have been trying to get wrapHorizontal and wrapVertical to work in collection mode, and neither will work, together or on their own. They basically fill up the viewer and the available memory on my machine, and grind it to a halt, so I can't really send a print screen. This is the best screenshot I can offer when only on wrapVertical:
![wraphorizontal](https://user-images.githubusercontent.com/32326644/30906898-1fb1c552-a371-11e7-89fd-952d1d07924d.jpg)

**Comment by iangilman** [comment]
Yeah, the wrapping modes aren't really set up for multi-image. What are you hoping would happen? Having the entire grid repeat?

**Comment by AMercer87** [comment]
Yeah. Not sure how to achieve that, and I was hoping to use that functionality to create the illusion of infinite tiles.

**Comment by iangilman** [comment]
Cool. I don't think we would want to extend the wrap feature to include that sort of functionality; wrapping a single image has a relatively common use case (e.g. a map of the globe), but once you get into multiple images, how you wrap to cover all possibilities is a lot less obvious.

My recommendation would be to go with true multi-image (not collection mode, which manages the images for you), and then lay the images out in a big grid yourself. OSD is pretty efficient about sharing resources if you have multiple copies of the same tilesource, so it should go pretty smoothly. If you want it to feel infinite, turn off the panning constraints (you probably still want zoom constraints so people don't zoom crazy far out) and listen to pan events; once the user pans outside of the area you've already tiled, add more images to the exposed area.

**Comment by AMercer87** [comment]
How would I go about drawing the cached version multiple times? Currently, it uses a list of JSON files to re-draw the images.

`function addImages(startX, startY){
	if (!isDrawn(startX,startY)){
		drawn.push([startX,startY]);
		fullwidth = tilesize+tilemargin;
		linelength = Math.floor(((fullwidth*images.length/collectionrows)/fullwidth)+1)*fullwidth;
		startX = startX*linelength;
		startY = startY*fullwidth*collectionrows;
		for (var i = 0; i < images.length; i++){
			var line = Math.floor((fullwidth*i)/linelength);
			var x = fullwidth*i-linelength*line;
			x = Math.floor(x/fullwidth)*fullwidth;
			var y = fullwidth*line;
			x=x+startX;
			y=y+startY;
			viewer.addTiledImage({
				tileSource: images[i],
				fitBounds: new OpenSeadragon.Rect(x,y,tilesize,tilesize)
			});
		}
	}
}`

Where:
'drawn' is an array of areas which have already been drawn to stop drawing multiple sets on top of each other,
'tilesize' is the width and height of the square tiles,
'tilemargin' is the margin between tiles on each axis,
'collectionrows' is how many rows in the view of the collection,
and 'images' is an array of the locations of the JSON files.

**Comment by iangilman** [comment]
If you use ``` instead of ` for multi-line code, it does the right thing. I've gone ahead and fixed it for you. 

Anyway, your code looks good. You need to have all of those tiled images, but wherever there are duplicates, they should share the same cached tiles, so you're not loading new image files from the server for them.

**Comment by AMercer87** [comment]
It's probably an issue on my machine's graphics drawing ability, rather than the code, then. Thankfully, this is for a project which won't be live on the internet, so it's just run on specific hardware. I might try loading them as an array, as currently the top line of the collection loads first and when panning upwards, it's noticeable.

**Comment by iangilman** [comment]
What are the symptoms you're seeing? Does it depend on how much you're zoomed?

**Comment by AMercer87** [comment]
Extreme lag when it adds in a new set. The lag isn't so noticeable on the hardware it'll be running on, but it's still there. Is there a way to slow down the adding process to mitigate lag? This wouldn't be a problem if I added a large area of tiles around the start point, then added them slowly once I'm at a bigger distance away. I've also started using a 'map' of a single set of images, which I use to start adding them from the bottom, left, top or right. Code below, for reference.
```
function addMoreImages(startX, startY, direction){
	console.log(initComplete);
	if (!isDrawn(startX,startY) && initComplete){
		console.log(map);
		drawn.push([startX,startY]);
		fullwidth = tilesize+tilemargin;
		linelength = Math.floor(((fullwidth*images.length/collectionrows)/fullwidth)+1)*fullwidth;
		startX = startX*linelength;
		startY = startY*fullwidth*collectionrows;
		var toBeAdded = [];
		for (var i = 0; i < images.length; i++){
			var line = Math.floor((fullwidth*i)/linelength);
			var x = fullwidth*i-linelength*line;
			x = Math.floor(x/fullwidth)*fullwidth;
			var y = fullwidth*line;
			x=x+startX;
			y=y+startY;
			toBeAdded[i] = [images[i],x,y];
		}
		
		switch (direction){
			case 0:
				for (var y = collectionrows-1; y > -1; y--){
					for (var x = 0; x < collectioncollumns; x++){
						if (map[x][y]>0 || (x==0&&y==0)){
							var index = map[x][y];
							console.log(map[x][y]);
							viewer.addTiledImage({
								tileSource: toBeAdded[index][0],
								fitBounds: new OpenSeadragon.Rect(toBeAdded[index][1],toBeAdded[index][2],tilesize,tilesize)
							});
						}
					}
				}
				break;
			case 1:
				for (var x = 0; x < collectioncollumns; x++){
					for (var y = 0; y < collectionrows; y++){
						if (map[x][y]>0 || (x==0&&y==0)){
							var index = map[x][y];
							console.log(map[x][y]);
							viewer.addTiledImage({
								tileSource: toBeAdded[index][0],
								fitBounds: new OpenSeadragon.Rect(toBeAdded[index][1],toBeAdded[index][2],tilesize,tilesize)
							});
						}
					}
				}
				break;
			case 2:
				for (var y = 0; y < collectionrows; y++){
					for (var x = 0; x < collectioncollumns; x++){
						if (map[x][y]>0 || (x==0&&y==0)){
							var index = map[x][y];
							console.log(map[x][y]);
							viewer.addTiledImage({
								tileSource: toBeAdded[index][0],
								fitBounds: new OpenSeadragon.Rect(toBeAdded[index][1],toBeAdded[index][2],tilesize,tilesize)
							});
						}
					}
				}
				break;
			case 3:
				for (var x = collectioncollumns-1; x > -1; x--){
					for (var y = 0; y < collectionrows; y++){
						if (map[x][y]>0 || (x==0&&y==0)){
							var index = map[x][y];
							console.log(map[x][y]);
							viewer.addTiledImage({
								tileSource: toBeAdded[index][0],
								fitBounds: new OpenSeadragon.Rect(toBeAdded[index][1],toBeAdded[index][2],tilesize,tilesize)
							});
						}
					}
				}
				break;
			default: alert("Incorrect direction.");
		}
	}
}
```

**Comment by iangilman** [comment]
Yeah, one approach, if you don't mind how it looks, would be to add one new image every frame or so, so it's not all at once.

A bigger thing though: what are your tile sources? Are they URLs for DZI files or IIPImage links? If so, while we do cache all of the tiles, we don't cache those initial URLs (maybe we should). The way to get around that is to load the URLs once each and then use the parsed data as your tile source. That way you're not generating extra server calls. Here's an example of that sort of thing for DZI: 

https://codepen.io/iangilman/pen/gpejpJ

**Comment by AMercer87** [comment]
I am using a IIIF manifest. Is there any way to call TileSourceFromData (or similar) for a JSON object? 'images[i]' refers to the correct image object within the OpenSeadragon instance, so I thought this would be the most efficient way to re-use parsed data. I'll try having a fiddle around with it today, and if I get anywhere with it, I'll post about it here.

**Comment by AMercer87** [comment]
Turns out most of the lag is due to it drawing vertically. I've managed to get the lag down to a manageable amount by simply only infinitely drawing horizontally, and it's actually quite fast.

**Comment by iangilman** [comment]
I believe you can use the inline configuration style for IIIF as shown here:

http://openseadragon.github.io/examples/tilesource-iiif/

At any rate, glad to hear you found something that's working!
