### ISSUE TITLE
Error while loading tif : Ignoring tile a.Tile loaded before reset

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1316]
HI  - i am experience some issues with tiled image (tif) . sometimes while zooming I am getting the following error: 
Ignoring tile a.Tile loaded before reset: http://127.0.0.1/cgi-bin/ImageServer.cgi/C:/images/image.tif_files/11/3_1.jpg

When open the url its working and I see the image;
How can I fix it ? is is cgi-bin application error?  

Thanks

**Comment by iangilman** [comment]
I'm not sure. Are you opening and closing images? What are the visual symptoms of this error? It may just be normal operation.
