### ISSUE TITLE
click with both right and left click on the mouse cause the image to freeze and create a "free mode"

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1317]
HI - when I click both right and left buttons on the mouse in windows (regular mouse not a magic one like mac) the viewer is being in "free mode"  you can move the viewer without clicking on the mouse.
and to cancel it I need to click on the wheel but then the mouse is stuck 

did you experience something like that ? 
I will try to provide an example

**Comment by iangilman** [comment]
Is this with the latest release? There were some recent bug fixes for this sort of thing.

**Comment by johnico** [comment]
hi reproduced in 2.3.0

**Comment by iangilman** [comment]
Well, you can take a look at #1223 and #1244; I think those are the ones that fixed this. Even so, I think you're better off just updating to 2.3.1.
