### ISSUE TITLE
TiledImage with opacity 0 has always _needsDraw = true

### ISSUE THREAD

**Issue by jetic83** [openseadragon/openseadragon#1318]
If you set a tiledImage to opacity 0, it needs to be drawn once, of course. Still, it's `_updateViewport()` function will never be called (which would be the only chance to set `_needsDraw = false`).

Therefore, '_needsDraw' stays 'true' all the time, which triggers the whole world to be redrawn (`viewer.world.needsDraw()` in `updateOnce(viewer)` in `updateMulti(viewer)` in `scheduleUpdate(viewer, updateFunc)`), again and again, since this transparent tiledImage never reports to be done with drawing.

This leads to unwanted side effects when I use the fabricjs plugin for OSD.

I will post a pull request which sets `_needsDraw = false` for transparent images in the `TiledImage.draw()` function, which solves the whole problem.

**Comment by iangilman** [comment]
Good catch! Thank you for fixing this :)

**Comment by iangilman** [comment]
Fixed by #1319
