### ISSUE TITLE
Question: Detecting FullScreen

### ISSUE THREAD

**Issue by musnuxer** [openseadragon/openseadragon#1320]
Hi, I am new to this, and I am trying to rise my first project...
The challange I have might be easy for you ;-)
I am looking for a way to detect if the viewer is in fullscreen mode or not - based on this I would like to display html contet or not.
This is what I have, the if is not working, that why it is commented out:

```
var viewer = OpenSeadragon({... });
var filenames = [...]; //Array with all my file names of the tile sources
viewer.addHandler("page", function (data) {
	//if (viewer.isFullScreen() == false) {
		document.getElementById("nameprint").innerHTML = filenames[data.page];
	//};
});
```

**Comment by iangilman** [comment]
There's no `viewer.isFullScreen`... where did you get the impression there was one? That said, there probably should be! 

There is, however, a global `OpenSeadragon.isFullScreen()` you can use.

**Comment by iangilman** [comment]
For anyone who wants to implement `viewer.isFullScreen()`, note that the difference would be to show whether that specific viewer (of possibly multiple viewers on the page) was full screen, whereas `OpenSeadragon.isFullScreen()` just tells whether any viewer is full screen.

**Comment by JachiOnuoha** [comment]
Hello
I'm new to contributing to this repo and I thought I'd try to resolve this issue.
From my understanding, it seems like a straightforward fix. I have a draft PR that contains potential fixes to this issue.

**Comment by hrghauri** [comment]
It appears to be solved. Is this one still open?

**Comment by iangilman** [comment]
@hrghauri Good point! Looks like I forgot to close it when the PR was merged. Thank you for pointing it out. :)
