### ISSUE TITLE
How to stop event?

### ISSUE THREAD

**Issue by Ronalses** [openseadragon/openseadragon#1321]
Hi, i have a problem.
how to stop event ?
	this.viewer.addHandler('canvas-press', (e) => {
            e.preventDefault()
       });

**Comment by iangilman** [comment]
What are you trying to prevent?

**Comment by Ronalses** [comment]
was trying to prevent the spread of the event, when it opened a modal.
but I could solve it another way.
Thank you!

**Comment by iangilman** [comment]
The event we pass isn't the original browser event, but it contains the original... you just need to do:

e.originalEvent.preventDefault();

...and probably also:

e.originalEvent.stopPropagation();

**Comment by Ronalses** [comment]
Thank you very much for the help.
:3

**Comment by barmok** [comment]
He everyone, in my case I try to rewrite the home event to get me to the top of an image instead of the middle. But there is no originalEvent on the home event.
Any idea how to handle that kind of case?

viewer.addHandler('home', function(e) {
		var viewBounds = viewer.viewport.getBounds();
        var viewAspect = viewBounds.height / viewBounds.width;
        var imageBounds = viewer.world.getItemAt(0).getBounds();
        var newViewWidth = imageBounds.width;
        var newBounds = new OpenSeadragon.Rect((imageBounds.width - newViewWidth) * 0.5, 0, newViewWidth, newViewWidth * viewAspect);
		viewer.viewport.fitBounds(newBounds,true);
		e.originalEvent.preventDefault();
	});

Thank you.

**Comment by iangilman** [comment]
Sounds like you basically want to redefine the home behavior? We don't have functionality for that, but there are a few ways that you could hack it in. If you want to override the home button, you could do something like this:

```
viewer.homeButton.removeAllHandlers('release');
viewer.homeButton.addHandler('release', function() {
    // do your home behavior 
});
```

Or you could replace the `goHome` function itself:

```
viewer.viewPort.goHome = function() {
    // do your home behavior
};
```

Of course it might be nice to actually add in some sort of standard method for overriding the home behavior... I'm happy to give suggestions if you'd like to make a patch for that!

**Comment by Shaked** [comment]
I am trying to do something similar by cancelling the default behavior for the `Shift` key. Default behavior opens a new window while I want it to open a new tab: 

```
 viewer.addHandler('canvas-click', function (event) {
      if (event.shift) {
	  	// cancel browser Shift behviour - do not open a new window
        event.originalEvent.preventDefault();
	  	event.originalEvent.stopPropagation(); 
      	var url = '/test' ;
      	var w = window.open(url, '_blank');
      	w.focus(); 
    	return false;
    }
  });
```

Unfortunately it opens a new window even though I added `preventDefault` (and later also `stopPropagation`) 

Ideas? 

Thank you! 
Shaked

**Comment by iangilman** [comment]
@Shaked why is shift-clicking the canvas opening a new tab/window at all? Do you have an `a` tag on it or something, perhaps in an overlay? Or is the window opening happening only because of this new code?

**Comment by msalsbery** [comment]
@Shaked Assuming your browser is set to open new pages in tabs instead of windows, it's probably the browser treating it as a popup. Depending on the browser, it's usually possible to open in a new tab if the window.open() call is a direct result of user interaction (e.g. in a click event handler) but the OSD Viewer's canvas-click event may not be treated that way as it's a manufactured event, not a true DOM element event.

You could try this trick (taken from StackOverflow https://stackoverflow.com/questions/4907843/open-a-url-in-a-new-tab-and-not-a-new-window-using-javascript)
```
Object.assign(document.createElement('a'), { target: '_blank', href: '/test'}).click();
```
but I'm skeptical...if it worked then popup blockers would be kind of useless ;) but maybe since the target link is in the same domain the browser(s) will allow it?

Another possible solution is to catch the appropriate events and stop their propagation to the viewer. While possible, it's not simple and gets more complicated supporting multiple pointer event models if you want it to work with mouse and touch for example

**Comment by Shaked** [comment]
> @Shaked why is shift-clicking the canvas opening a new tab/window at all? Do you have an `a` tag on it or something, perhaps in an overlay? Or is the window opening happening only because of this new code?

Yes, I'm using multiple images with an overlay for each an every image. I want click to behave as expected in OSD but click+shift to react. What I did at the end was using `CTRL` instead: 

```
viewer.canvas.addEventListener('contextmenu', function(event) {
        if (HotKeys.isCtrl()) {
            event.preventDefault();
            }
        });
  viewer.addHandler('canvas-click', function (event) {
      if (HotKeys.isCtrl()) {
        var tileIndex = OpenSeadragon.CanvasOverlayHd.getTileIndexFromPixel(viewer, event.position);
	var id = event.eventSource.tileSources[tileIndex].id;
      	var url = '/?id=' + id;
      	var w = window.open(url, '_blank');
      	w.focus(); 
    	return false;
    }
  });
```

Unfortunately I wasn't able to do the same for the `Shift` key - but haven't tried @msalsbery's idea

**Comment by iangilman** [comment]
If you're dealing with overlays, this example might be of use: https://codepen.io/iangilman/pen/mEkKaY

**Comment by Shaked** [comment]
> If you're dealing with overlays, this example might be of use: https://codepen.io/iangilman/pen/mEkKaY

Yes I so this example. Still, it won't help preventing `Shift`'s default behavior - opening a new window instead of a new tab. Having said that, it seems like @msalsbery's idea works:
https://codepen.io/ShakedKlein/pen/vvaOrM

Thank you!

**Comment by iangilman** [comment]
Excellent... glad you found something that works!
