### ISSUE TITLE
Do the tileSources support h264 format?

### ISSUE THREAD

**Issue by lihan2016nju** [openseadragon/openseadragon#1322]
Hi, @iangilman , I am making  a  webpage to display a deep zoom image.  Now, I have a question about the format that the `tileSources `support ? Except the `jpg/png ` format as below, could the openseadragon support ` .h264 ` input ? which means can I input the compressed  file after H246 encoding.  If not , can I write a decoding script to solve this ?
Thanks a lot !
` tileSources.push({
    Image: {
      xmlns:  "http://schemas.microsoft.com/deepzoom/2009",
      Url: src[i],
      Overlap: "1",
      TileSize: "256",
      Format : "png",
      Size:{
         Height: "3731",
         Width:  "13131"
      }  
    }  
  });`

**Comment by iangilman** [comment]
Do you mean video? We don't currently support video; that would be an interesting project, but probably outside the scope of what OpenSeadragon can do.

**Comment by lihan2016nju** [comment]
Not the video. I mean the tiled images of `.h264`format, which are compressed by H264.  Because my tiled images are very large, the total file  is over 1  gigabyte, so I want to compress them first, But I am not sure whether `openseadragon` can support them or not.

**Comment by iangilman** [comment]
Interesting! Well, OpenSeadragon is just a client side library, so it can only handle the formats the browser can handle. Can H264 images be used normally in the browser? 

You might also look into http://iipimage.sourceforge.net/ for the server side and see if they support anything like that.

**Comment by lihan2016nju** [comment]
Ok, I see. Thanks for your help!
