### ISSUE TITLE
When is TiledImage.setOpacity() executed and how can I use it programmatically?

### ISSUE THREAD

**Issue by jetic83** [openseadragon/openseadragon#1325]
Consider I have two overlayed tiledImages in my OSD world. I want to do screenshots of them separately using the viewer.drawer.canvas.

First, I set the first image's opacity 0
`viewer.world.getItemAt(0).setOpacity(0);`

then I use the `viewer.drawer.canvas` to paint it on my screenshot (the second image should now be visible).

Then, I set the first images visible (`setOpacity(1)`) and the second transparent, to save the `viewer.drawer.canvas` again, this time expecting the first image on the canvas.

But I get two times the same image, since the opacity change seems to be effective _after_ my whole function has already finished. 

So how could I "force" the opacity change to appear before my function continues? `draw` and `forceRedraw` do not work either.

**Comment by iangilman** [comment]
Yes, all such changes are asynchronous and don't show up on the canvas until the next frame is drawn. You'll need to set the opacity, then wait for an `update-viewport` event on the viewer, then take your picture, then set the opacity, etc.
