### ISSUE TITLE
How to access instance of TiledImage?

### ISSUE THREAD

**Issue by robhicks** [openseadragon/openseadragon#1326]
I want to use the setClip and getClip methods of TiledImage. 

The docs say "You shouldn't have to create a TiledImage directly; use OpenSeadragon.Viewer#open or OpenSeadragon.Viewer#addTiledImage instead."

But in looking at the docs for open nothing is mentioned about how to access the instance of TiledImage apparently created by that method. 

The addTiledImage method has a cryptic comment about the success property, which apparently is "a function that gets called when the image is successfully added. It's passed the event object which contains a single property: "item", the resulting TiledImage."

So, how do I get access to instances of TiledImage or use setClip and getClip?

**Comment by iangilman** [comment]
Sounds like we could improve the docs! 

All of the TiledImages are accessible via the World, so if you have a single image (and your Viewer is named `viewer`), it'll be:

```
viewer.world.getItemAt(0);
```

Note that it won't be available until after the `open` event (or the `success` callback, if you're using `addTiledImage`).

Any thoughts about how to improve the docs for this? What are you finding confusing about the comment for the success property? I'm afraid I'm too close to the project...

**Comment by robhicks** [comment]
@iangilman Thanks for your response.

I guess for me it would be helpful to  understand that getting access to an instance of TiledImage using either open or addTitledImage is asynchronous in nature. 

Since I would prefer not to add an event listener, I'll probably use addTitledImage. 

Do you want a PR for suggested changes for the API docs?

**Comment by iangilman** [comment]
Yes, the asynchronous nature is very important... definitely worth making clearer! If you'd be up for making a pull request with suggested changes, that would be great!

**Comment by iangilman** [comment]
#1332 addresses this.
