### ISSUE TITLE
How delete request tiles.

### ISSUE THREAD

**Issue by Ronalses** [openseadragon/openseadragon#1327]
is there any way to cancel all calls that are pending?
I have an application in angular and when I change of route, the calls still are pending.
I would like to stop calls that are still pending. when the application changes its route.
sorry for my English.

Thank you very much in advance.

**Comment by thatcher** [comment]
I believe you are looking for `viewer.imageLoader.clear()`

For example:

```
var viewer = OpenSeadragon({
   // ....options
});
// Im make up this event handler to pretend your app has a callback when the route changes
yourApp.onRouteChange(function(){
    // THIS IS THE RELEVANT API CALL
    viewer.imageLoader.clear();
});
```

**Comment by Ronalses** [comment]
Hello thank you very much.
I'll try to see how this works.

Thank you very much for your help.
