### ISSUE TITLE
On clicking on the overlay I need id(Css id) of it

### ISSUE THREAD

**Issue by aditya1092mukkavilli** [openseadragon/openseadragon#1328]
I had a scenario, when we click on the overlay, it should give me the id(css id which was given at the time of creation) of that particular overlay.. 
I tried by appending onclick event for the overlay but, onclick event is not attaching to the dom.. 

Please help me on this.. 

Thanks in advance

**Comment by thatcher** [comment]
Hi aditya, can you provide a small code sample to share how you are configuring your overlay so I can  answer in a way thats most relevant to your setup?  In the mean time I'll work on providing a short example of attaching custom event handlers to overlays.

Thatcher

**Comment by thatcher** [comment]
The documentation here should provide insight on how to add additional events to overlays.  

https://openseadragon.github.io/examples/ui-overlays/

Have you given this a read?  

If you are using the overlays created through the OpenSeadragon constructor you can specify the id and/or class names to attach to it.  The id and/or classes can be used to add event handlers using the regular DOM api or via jQuery etc.
```
var viewer = OpenSeadragon({
OpenSeadragon({
                id:            "example-tilesource-overlay",
                prefixUrl:     "/openseadragon/images/",
                sequenceMode: true,
                tileSources: [{
                    ...
                    overlays: [{
                        id: 'example-overlay',
                        x: 0.33, 
                        y: 0.75, 
                        width: 0.2, 
                        height: 0.25,
                        className: 'highlight'
                    }],
                    ...
                }]
});

// BIND YOUR OWN HANDLERS HERE
jQuery('#example-overlay').click(function(){
    // do something with the event.
});
```

On the other hand if you are constructing the layers with `viewer.addOverlay` you again have direct access to the element to add your own event handlers:
```
var viewer = OpenSeadragon({
            id: "contentDiv",
            prefixUrl: "../../build/openseadragon/images/",
            tileSources: "../data/testpattern.dzi",
            minZoomImageRatio: 0,
            maxZoomPixelRatio: 10
        });

        viewer.addHandler("open", function(event) {
            var elt = document.createElement("div");
            elt.className = "runtime-overlay";
            elt.style.background = "green";
            elt.style.outline = "3px solid red";
            elt.style.opacity = "0.7";
            elt.textContent = "Scaled overlay";
            viewer.addOverlay({
                element: elt,
                location: new OpenSeadragon.Rect(0.21, 0.21, 0.099, 0.099),
                rotationMode: OpenSeadragon.OverlayRotationMode.BOUNDING_BOX
            });

           // ADD YOUR OWN EVENT HANDLERS HERE
           jQuery(elt).click(function(){
                 //do something with the event
           });
})
```

Let me know if that helps!

Thatcher

**Comment by aditya1092mukkavilli** [comment]
second way is what I am exactly looking for...

Thank you for your quick response...

**Comment by iangilman** [comment]
@thatcher Great answers! One thing to be aware of is that the OSD event handling sometimes has to stop the propagation of certain events, so if standard DOM event handlers (like jQuery) don't work, it's advised to use a MouseTracker. Here's an example: https://codepen.io/iangilman/pen/mEkKaY
