### ISSUE TITLE
High quality images being pixelated

### ISSUE THREAD

**Issue by bettyhill** [openseadragon/openseadragon#1329]
I'm using OSD as an image viewer but the small version of the image is appearing very pixelated. The images are very high quality and the issue is happening when there is a lot of detail for images such as drawings. Is there anything that can be done about this? Attaching a screenshot of the viewer and the same image in photoshop.

![photoshop image](https://user-images.githubusercontent.com/33061090/31945086-0f592bfe-b8c6-11e7-94fc-5fc88d8a8afa.png)
![pixelated image](https://user-images.githubusercontent.com/33061090/31945087-0f76ef90-b8c6-11e7-9a0a-6ddd79ead07a.png)

**Comment by thatcher** [comment]
Hi betty, can you share the a page where we can preview the issue or provide some code to give us insight into how your tile source and or openseadragon is configured?  

Thanks,
Thatcher

**Comment by iangilman** [comment]
Also, you might try playing with the `minPixelRatio` option; it controls the threshhold between levels. The default is 0.5; try 1 or so.
