### ISSUE TITLE
Only image edge tiles displayed

### ISSUE THREAD

**Issue by imoutsatsos** [openseadragon/openseadragon#1335]
I have been running into this issue frequently, but not reproducibly! The OSD viewer only displays the image edge tiles, but not the internal tiles as shown below. Frequently, the same images are displayed fine when I browse from another computer. I tend to think that it's a setting in my Chrome browser, but I can't quite figure out what affects it. Clearing out the local browser cache and reloading does not seem to have any effect. Any ideas for diagnosing the cause are greatly appreciated!

In the example below I'm loading 6 images and I'm creating a custom layout

![image](https://user-images.githubusercontent.com/3408226/32191902-f878ff1e-bd88-11e7-83db-53455cf3eae9.png)

**Comment by imoutsatsos** [comment]
I'm finding that if I don't use a fully qualified domain name for the server that hosts the page, the problem is resolved. I don't understand why though!
![image](https://user-images.githubusercontent.com/3408226/32243144-f9470a90-be4a-11e7-9b04-18c1dbc19f69.png)

**Comment by iangilman** [comment]
That is very strange! Do you have a URL I could try?

If you open up the developer console are there any errors?

**Comment by imoutsatsos** [comment]
Unfortunately not. This is happening on our internal network and IS NOT reproducible for everyone. Given that this issue does not happen with all of the users, I have started suspecting network latency and timeout issues. There are no errors reported in the developer tools console, but i'm wondering whether the OSD API has any way of adjusting the timeout for displaying the images. What is the behavior if this timeout is exceeded? Should OSD be able to load slow images from the browser cache next time?

**Comment by iangilman** [comment]
You can adjust the image timeout with the `timeout` option when you create your viewer. The default is 30 seconds (you specify milliseconds). You should get a message in the console if it's timing out, though. You're not seeing anything in the network tab of the dev inspector either?

OSD just uses the browser's image fetching (unless you specify you want to do it via AJAX), so the standard browser cache does get used as appropriate.
