### ISSUE TITLE
Multiple users viewing single image

### ISSUE THREAD

**Issue by delta2golf** [openseadragon/openseadragon#1336]
I need to create a solution where one user user navigates an image and the position of the image is updated to other users in other computers. I need to capture all navigation events (zooming, moving, etc...) and send coordinates to other users. Which properties and methods could I use to reproduce the navigation to other users? It is not clear how I can set new zoom or positions to other users. Any suggestions.

**Comment by iangilman** [comment]
All you should need is the zoom and pan. You can get them with `viewer.viewport.getZoom()` and `viewer.viewport.getCenter()` respectively, and you can set them with `viewer.viewport.zoomTo(zoom)` and `viewer.viewport.panTo(point)`. To know when the user zooms and pans you can watch the viewer for `zoom` and `pan` events using `viewer.addHandler`.

Of course you'll need to coordinate this data between the computers, presumably using web sockets. You'll also want to filter your zoom and pan events so you know which ones are initiated by the user and which ones come from other users.

There's some discussion about such things here in the Issues... https://github.com/openseadragon/openseadragon/issues/1160 is a good entry point.

**Comment by boskar** [comment]
I've succesfully implemented it some time ago, demo here:
http://lekarski.katowice.pl/master.php

http://lekarski.katowice.pl/node.php

**Comment by arrigo55** [comment]
I read this issue only today (more than a year in late). I found very interesting the two links posted by boskar. It is exactly what I was looking for my interactive teaching with medical students and trainees in Pathology. Is it possible to have more information and/or download them?
