### ISSUE TITLE
page fully loaded event

### ISSUE THREAD

**Issue by michaelw3** [openseadragon/openseadragon#1339]
for my Thumbbar plugin I'm trying to pan the Thumbar to the right image when a user changes the page in Mainviewer, yet i have a lagging in the panning of the Thumbbar. i think it is because the 'page' event i'm listening to in the Thumbbar and firing the pan function upon this event, but the 'Mainviewer' hasn't finished to load all tiles and therefor stops the panning of the Thumbbar and after the page is fully loaded the panning continues.

so my question is-
is there a way to create a `page-loaded` event which is fired only once when `page` event was fired and fully loaded and not each time a zoom has been made?
this i guess will be the solution for my problem i guess.

or does anyone else have a better solution?

thanks for any help.
Michael

**Comment by iangilman** [comment]
Just so I understand: the network traffic of loading the new tiles is causing hiccups in the animation? That shouldn't be happening. Do you have an example you could share?

Anyway, if that's what's happening, one reasonable thing to try is what you suggest. It might look something like this:

```
viewer.addHandler('page', function() {
  viewer.addOnceHandler('open', function() {
    whenFullyLoaded(viewer.world.getItemAt(0), panThumbBar());
  });
});

function whenFullyLoaded(tiledImage, callback) {
  if (tiledImage.getFullyLoaded()) {
    setTimeout(callback, 1); // So both paths are asynchronous
  } else {
    tiledImage.addOnceHandler('fully-loaded-change', function() {
      callback(); // Calling it this way keeps the arguments consistent (if we passed callback into addOnceHandler it would get an event on this path but not on the setTimeout path above)
    });
  }
}
```

(That `whenFullyLoaded` is example code from https://github.com/openseadragon/openseadragon/issues/1257.)

**Comment by michaelw3** [comment]
Hi @iangilman and thanks for your detailed answer!

The funny thing is that i use it in an NW.js environment-local, and yes i ment the animation that is getting stuck, i have a similar app for web where i didn't encounter this problem.
don't know how to explain that, i thought local should be faster.
i"ll try to implement your code and will update on how it works.

 my code-
in the thumbbar i'm listening to a  `page` event 
```
  this.mainViewer.addHandler('page',function(e){
        self.scrollToThumb(e.page);
      });
```
then i trigger the panning function
  ```
  scrollToThumb : function(index){
        var position =  this.thumbbarViewer.world.getItemAt(index).getBounds().getCenter();
        var temppoint = this.thumbbarViewer.world.getItemAt(index).getBounds();
      addOverlyFly(temppoint);
      self.thumbbarViewer.viewport.panTo(position, false);
      }
```

**Comment by michaelw3** [comment]
@iangilman the implementation of your code solve the issue! 
thanks a lot!

**Comment by iangilman** [comment]
Great, good to hear!
