### ISSUE TITLE
What is the maximum number of tile images that can be cached?

### ISSUE THREAD

**Issue by abhisb** [openseadragon/openseadragon#1341]
I would like to know the count of maximum images which can be cached using **TileCache**. I can see by default **maxImageCacheCount** is now set to **200**. 
Would there be any negative impact on browser performance if we set cache count to a higher value(**500** or **1000**)?
I tried the below code, but I couldn't see any impact in the browser performance/lag.
`var cache = new OpenSeadragon.TileCache({maxImageCacheCount: 1000});`
Please advice me on this.

**Comment by iangilman** [comment]
Unfortunately it's hard to say. It has to do with how much memory is available to the browser, and how big each tile is. As far as I know it's difficult to learn from the browser how much memory it has for you. Anyway, on a beefy desktop you could have room for many thousands of tiles, whereas on a small mobile device, maybe not so many.

If you learn more about how to find out from the browser how much memory it has, I'd love to hear about it!

**Comment by abhisb** [comment]
Thanks for the info @iangilman If I come to know more about this, I'll let you know.
