### ISSUE TITLE
Couldn't draw a line between two points using OSD and paperjsOverlay

### ISSUE THREAD

**Issue by georgebabu92** [openseadragon/openseadragon#1342]
Hi, 
I am trying to draw lines between points in a image dynamically, using paperjsOverlay and OSD. When I try to draw lines using image coordinates(which, I get from db) the line is drawn, but not where I want in the viewport. So, I tried to convert the actual image coordinates to viewport coordinates, using "imageToViewportCoordinates", and draw. But the line is not drawn.

My code looks like this:
```
function getPoint(route_nodes) {
    var viewer = this.viewer;
    var keys=[];
    for (var i=0; i <route_nodes[0].length; i++) {
        var point = new OpenSeadragon.Point(route_nodes[0][i].x, route_nodes[0][i].y);
        var pixel = viewer.viewport.imageToViewportCoordinates(point);
        keys.push([pixel]);
    }
    var overlay = viewer.paperjsOverlay();
    drawLine(keys);
};

function drawLine(keys) {
    var canvas = document.getElementById('osd-overlaycanvas');
    paper.setup(canvas);
    var path = new paper.Path();
    path.strokeColor = 'black';
    for(var i=0; i<keys.length; i++) {
        if(keys[i+1]) {
            var pointOne = new paper.Point(keys[i][0],keys[i][1]);
            var pointTwo = new paper.Point(keys[i+1][0], keys[i+1][1]);
            path.moveTo(pointOne);
            path.lineTo(pointOne.add(pointTwo));
            path.closed = true;
            paper.view.draw();
        }
    }
```

**Comment by iangilman** [comment]
Looking at the code for https://github.com/eriksjolund/OpenSeadragonPaperjsOverlay it seems maybe it's using image coordinates (though I think it would be better if it was using viewport coordinates). Interesting that's it's not in the right spot. You might try filing an issue on the plugin's repository so @eriksjolund can take a look.
