### ISSUE TITLE
svg-overlay get the specific node onclick

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1347]
Hi, when I click on rect in svg overlay is returned the whole SVG element and not specific <rect>.
in that case i Can not know which rect I clicked on.

```
     if(viewerId === 1){
                overlay.onClick(d3Rect.node(), function() {
                    console.log(d3Rect.node());
                     console.log(arguments)
                });
            }
```

**Comment by iangilman** [comment]
This is probably better filed over in https://github.com/openseadragon/svg-overlay/issues. 

Anyway, this has worked for me: 

`d3Rect.on('click', handler)`

In other words, put the handler on the d3Rect itself, rather than on the overlay.
