### ISSUE TITLE
Adding new svg overlay to array while click on point

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1348]
Hi ,  while I click on the screen I want to add new <rect> element to the svg-overlay 

How can I do that ? , I am using canvas click listener
I want to create a node with default size of x and y surround  the click position

for example: x =100 and y = 100 

```
<rect x="0.17698797343385386" width="0.18309100700053849" y="0.03859271225991743" height="0.050260276431520375" id="1" 
style="fill-opacity: 0; stroke-linejoin: inherit; stroke: red; stroke-width: 0.002px;"></rect>

```

**Comment by iangilman** [comment]
This is better asked in https://github.com/openseadragon/svg-overlay/issues.

Also, btw, multi-line code examples should use ```. I've fixed this one to show you.
