### ISSUE TITLE
is it possible to draw a rectangle on the seadragon canvas?

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1349]
Hi . I m looking for a way to draw with drag and drop 

1- right click on the canvas will create a drawer pointer and then I can create rectangle until I will click again to save that.

example:
http://jsfiddle.net/d9BPz/546/

**Comment by iangilman** [comment]
https://github.com/picturae/openseadragonselection is a plugin for doing this. If it doesn't do exactly what you want, you can look at the code to get ideas for how to do it yourself.
