### ISSUE TITLE
Get image dimensions

### ISSUE THREAD

**Issue by zloysmiertniy** [openseadragon/openseadragon#1350]
This may be very silly, but how can I get the image dimensions after having loaded an image? I need them to do some calculations on the svg overlays.

**Comment by iangilman** [comment]
Assuming you just have a single image, it would be: 

```
viewer.world.getItemAt(0).getContentSize();
```

That gets you the actual pixel dimensions of the image, not its location in the viewport.

**Comment by Whao510** [comment]
How to have more than one?

**Comment by iangilman** [comment]
`getItemAt` takes an index, so if you have more than one image you can pass in the correct index for the image you're interested in.

Or are you asking how to add more than one image to the scene in the first place? If so, take a look at the "multi-image" section on https://openseadragon.github.io/.
