### ISSUE TITLE
Preset a certain part of the picture before start

### ISSUE THREAD

**Issue by ftomasch** [openseadragon/openseadragon#1351]
Hi Ian,

Openseadragon fascinates me. I presents  fantastic possibilities. But now I am achieving a difficulty and maybe you can help me. I want to process panoramic images in a way that the user can find the picture in a certain way.

The panorama shows, when processed, one part of the whole picture.

To enlarge the picture as much as you want it to  is no problem with the option "defaultZoom". But my problem is, however,  the enlarged picture is central. Is it possible to choose another part of the picture?

One example: When I click on the link to activate the panorama picture, it is  400 % enlarged (defaultZoom: 4). But I only want to show one special part of the picture, f.e. the one that shows the corner down left.

Is it possible - like with defaultZoom - to  preset a certain part of the picture before I start it?

Did I possibly overlook something within the documentary?

Kind regards

Franz

**Comment by iangilman** [comment]
I recommend `fitBounds` for going to specific locations. If you want to go to a specific location at startup, you can do it like so:

```
viewer.addHandler('open', function() {
  viewer.viewport.fitBounds(bounds, true);
});
```

Remember that the bounds that you give (which should be an OpenSeadragon.Rect) need to be in viewport coordinates. You can learn more about that here:

http://openseadragon.github.io/examples/viewport-coordinates/

**Comment by ftomasch** [comment]
Hi Ian,
Thank you for your quick response. That seems to be the slolution!
Unfortunately I did not manage to find the definition for the variations. You refer to the part "viewport-coordinates" within the tutorial. There it is described that the variations for the start value are x and y. But unfortunantely I cannot manage how to add "bounds".

Among others I tried the following three possibilities:
version 1:
    var bounds = OpenSeadragon.bounds.x(0.1);
    var bounds=OpenSeadragon.bounds.y(0.1);
version 2
    var bounds=x(0.1);
    var bounds=y(0.1);
version 3
    var bounds=(0.1, 0.1);

and then I added your sentencs:
viewer.addHandler('open', function() {
viewer.viewport.fitBounds(bounds, true);
});

- Unfortunately without success. I have the feeling I have got this completely wrong.
Can you help me again?
Best regards
Franz

**Comment by ftomasch** [comment]
Whats this?
I don´t want close this .....

**Comment by iangilman** [comment]
Apologies for the confusion. I meant the `bounds` variable should be a `OpenSeadragon.Rect`, for instance like so: 

```
var bounds = new OpenSeadragon.Rect(0, 0, 0.1, 0.1);
```

Those coordinates will give you the upper left tenth of the image, assuming the image is 1 viewport coordinate wide (which is the default).

**Comment by ftomasch** [comment]
Hi Ian!

Thanks for the fast answer.

But it doesn`t work.

Did you mean to generate a retangle?
![no1](https://user-images.githubusercontent.com/34056100/33732965-7db4da00-db88-11e7-8c70-90ddc0cc40a0.jpg)
![no1](https://user-images.githubusercontent.com/34056100/33732987-8d39fd52-db88-11e7-97ca-420b3cc897e2.jpg)
![no2](https://user-images.githubusercontent.com/34056100/33733000-92e1e0bc-db88-11e7-976a-bf5beb356692.jpg)
I thought:
For the point to start the panorama I need only a Ccoordininate or landmark, like (0.0, 0.5) for  startpoint.

As an exampel I send two screenshots: 
No1 ist the usual startposition. 
Photo No2. shows the situation which I like.

Best regards
Franz

**Comment by ftomasch** [comment]
could you help further

**Comment by iangilman** [comment]
Just a point isn't really enough, because it doesn't set the zoom for you. You could pan to a point and also set the zoom separately, but the advantage to fitBounds is that it all happens together in one call.

As for how to figure out what the rectangles should be, the easiest thing is to open up your page in a web browser and navigate to the point of interest, then go into the browser's console and type (assuming your viewer is called `viewer` and is accessible globally): 

```
viewer.viewport.getBounds();
```

Grab the numbers from the result, and then you can use those for your fitBounds.

**Comment by ftomasch** [comment]
Hi Ian!
Thank you very much, 
now it is working!
Yeah!!!!

Here is the pre release for my Projekt:
http://www.tomaschowski.com/Panorama/Megazoom/TEST%20-%20Paris2.html
It is a very early version without anything special.
I want to create elements of storytelling in panorama. It will be a mixture between a linear story and an intuitive discover.
If you are Interested, I can give you  the link for my project if it finish. Maybe for your showcase, just in case you are interested.

Best regards,
Franz

**Comment by iangilman** [comment]
Excellent, and yes, please do let me know when it's ready to share! :)

**Comment by ftomasch** [comment]
Hi Ian,
After a long break I finally can manage to develop the panoramas. Id like to add another panorama to the first. For both of them I have determined an image section for the start. Your script functions very well!
However, I have another problem:
The start position of the second  panorama functions. At the first panorama the determined start positions are ignored.

I have added the following:
screenshot 1: only one panorama
![nur eins](https://user-images.githubusercontent.com/34056100/44959777-a2b7ae00-aef4-11e8-9cc1-beed86333350.jpg)
![beide](https://user-images.githubusercontent.com/34056100/44959780-acd9ac80-aef4-11e8-876b-e89d07c1ad6a.jpg)

screenshot 2: both panoramas

and here is the code:
 <div id="ParisHotel" class="Panorama">  </div>

    <div id="Agde" class="Panorama"> </div>
   
</article>    
</Main>  
       

<footer>
    <p>
        <a href="#Start">Franz Tomaschowski | Dorfen/Germany |</a>
        <a href="Info/Kontakt.html">Impressum</a>
    </p>
</footer>

    
// Panorama Paris    --> 
    
<script type="text/javascript">
 // Variablen zum positionieren der Navigationselemente       
        var _viewer;
        var CtrlPos= OpenSeadragon.ControlAnchor.BOTTOM_RIGHT;
        var CtrlPos2= OpenSeadragon.ControlAnchor.BOTTOM_RIGHT;

var viewer = OpenSeadragon
        ({
        id: "ParisHotel",
        tileSources: "Panorama/ParisHotel/ParisHotel.xml",
 
        // Begrenzungsrahmen         
            visibilityRatio: 1,
            constrainDuringPan: true,
 
        // Button und andere Anzeigen //
           controlsFadeDelay:500,  
           
        //Pfad zu den Buttonbildern
            prefixUrl: "Panorama/openseadragon/images/",
           
        //Navigationsbutton
          showNavigationControl: true, // die vier Standardbutton
                navigationControlAnchor: CtrlPos,
                showZoomControl: true,
                showHomeControl: false,
                showFullPageControl: false,
                homeFillsViewer: false,
           
                showSequenceControl: false,
                sequenceControlAnchor: CtrlPos2,
                sequenceMode: false,   
       
        //kleines Bildfenster zum Navigieren
                showNavigator:false, //verkleinerte Ansicht mit Zoomausschnitt (bildnavigator)
                navigatorPosition: "BOTTOM_RIGHT", // verschiebt das Fenster                  
                navigatorHeight:   "75px",// Größe des Navigatorfensters
                navigatorWidth:    "120px",       
         });
   
    // festlegen der  Startansicht          
        var boundsParis = new OpenSeadragon.Rect(
            0.019333581180118742,
            1.9517561207172962,
            0.8167599134234494,
            0.563043004147229,);
   
  viewer.addHandler('open', function()
        {viewer.viewport.fitBounds(boundsParis, true);
        }); 
       
</script>
   
    
// Panorama Agde    --> 
    
<script type="text/javascript">
 // Variablen zum positionieren der Navigationselemente       
        var _viewer;
        var CtrlPos= OpenSeadragon.ControlAnchor.BOTTOM_RIGHT;
        var CtrlPos2= OpenSeadragon.ControlAnchor.BOTTOM_RIGHT;

var viewer = OpenSeadragon
        ({
        id: "Agde",
        tileSources: "Panorama/Agde/Agde.xml",
          
 
        // Begrenzungsrahmen         
            visibilityRatio: 1,
            constrainDuringPan: true,
 
        // Button und andere Anzeigen //
           controlsFadeDelay:500,  
           
        //Pfad zu den Buttonbildern
            prefixUrl: "Panorama/openseadragon/images/",
           
        //Navigationsbutton
          showNavigationControl: true, // die vier Standardbutton
                navigationControlAnchor: CtrlPos,
                showZoomControl: true,
                showHomeControl: false,
                showFullPageControl: false,
                homeFillsViewer: false,
           
                showSequenceControl: false,
                sequenceControlAnchor: CtrlPos2,
                sequenceMode: false,   
       
        //kleines Bildfenster zum Navigieren
                showNavigator:false, //verkleinerte Ansicht mit Zoomausschnitt (bildnavigator)
                navigatorPosition: "BOTTOM_RIGHT", // verschiebt das Fenster                  
                navigatorHeight:   "75px",// Größe des Navigatorfensters
                navigatorWidth:    "120px",
           
               
         });
        // festlegen der  Startansicht          
        var boundsAgde = new OpenSeadragon.Rect(
            0.1845514603352556,
            0.057905793669573054,
            0.23080523768893155,
            0.08691259731723829);
        viewer.addHandler('open', function()
        {viewer.viewport.fitBounds(boundsAgde, true);
        });
</script>   
</body>
</html>

The adress of the Site is: www.tomaschowski.com

Please, could you hlp me, once more

Best regards
ftomasch

**Comment by iangilman** [comment]
Great to see it coming along!

BTW, you can make your code easier to read here on GitHub by wrapping it in ```.  I've taken the liberty of doing that for your comment above. 

I think your big issue is that both of your viewers are named `viewer`, so when the `open` event fires you're telling only the second viewer where to go. Just give the second viewer a different variable name and update the code as appropriate and that should sort it out.

**Comment by iangilman** [comment]
Every time the word `viewer` appears in the "Panorama Agde" section, change it to `viewer2` (with no space). That should fix it.
