### ISSUE TITLE
bounds.height must be greater than 0

### ISSUE THREAD

**Issue by julmot** [openseadragon/openseadragon#1354]
OpenSeadragon fails in IE11 in my simple image example:

![ie11-error](https://user-images.githubusercontent.com/8310677/33493418-411782fe-d6c0-11e7-8ca5-ec6cbd7edd62.png)

```javascript
this.viewer = OpenSeadragon({
  element: this.container,
  tileSources: {
    type: 'image',
    url: this.source
  },
  showZoomControl: false,
  showHomeControl: false,
  showFullPageControl: false,
  minZoomImageRatio: 0.9,
  maxZoomPixelRatio: 1.7
});
```

I've tried playing around with the options and googling, but wasn't successful. Since this error isn't visible on the corresponding example of OpenSeadragon itself, I'm not sure about the reason. Is there anyone out there that can help figuring out the reason of this issue?

**Comment by iangilman** [comment]
Interesting... Can you share a CodePen or something so I can take a look?

**Comment by julmot** [comment]
My mistake. I was reading `currentSrc` from an `<img>` inside a `<picture>` element, and this didn't work in IE11, even when using the picturefill polyfill (scottjehl/picturefill/issues/659). Therefore I was passing `undefined` to OpenSeadragon and thus, the error appeared. However, having a check of the img source would be a nice to have. But I can understand if you don't like it since this means that others could want other validations too.

**Comment by iangilman** [comment]
I'm happy for more validations if you want to add them! We've been starting to add more asserts, for instance.
