### ISSUE TITLE
How to show a different TiledImage in navigator?

### ISSUE THREAD

**Issue by jetic83** [openseadragon/openseadragon#1355]
Hi,

i wonder if it is possible to show a different TiledImage in the navigator than in the main viewer.

There was a similar issue already #903 saying that it is not possible as it is. I tried the hack provided in there, but the navigator window stays blank then. So, when I run 

    var originalImage = viewer.world.getItemAt(0);
    var oldNavigatorImage = viewer.navigator.world.getItemAt(0);
    viewer.navigator.world.removeItem(oldNavigatorImage);
    viewer.navigator.world.removeItem(viewer.navigator.world.getItemAt(0));
    viewer.navigator.addTiledImage({
        tileSource: NEWTILESOURCE.dzi,
        originalTiledImage: originalImage
    });

the navigator turns blank and the console writes: 
`Tile 8/0_0 failed to load: /newtilesource/8/0_0.jpeg - error: Image load aborted`.
I recognize that the .dzi is never parsed, too (my .dzi route is never visited on the server when I switch the dzi tilesource in the navigator). So, I think the navigator is just not updated 'properly'.

I wonder what I should try more to get this happen. Of course the navigator should be bound to the main image. I am asking since I try to build a plugin where we can switch the image in a side viewer and where the images are still synchronized to the main viewer for navigation. I try to use the navigator and magnifier plugin as a starting point, but they cannot change the image apparantly.

**Comment by jetic83** [comment]
Well, it works in my fiddle. 

https://jsfiddle.net/49uq1yqh/3/

So let me follow up why it doesnt work in my life version.

**Comment by iangilman** [comment]
Cool... Let us know what you find!

**Comment by jetic83** [comment]
It works also in my live demo now. The issue was that my tileserver returned null when the queried tile comes from a different image than the image in the current session. So, all on my side.

**Comment by iangilman** [comment]
Cool; good to know.
