### ISSUE TITLE
How to constrain zoomLevel to a constant pixel value?

### ISSUE THREAD

**Issue by kayw-cogapp** [openseadragon/openseadragon#1356]
Hi there, 

I'm fairly new to OSD so please bear with me!

I have a viewer that is always the same size regardless of the browser window as well as the 'view full screen' mode that is responsive. The images displayed in the viewer are licensed to be shown at no more than 2000px on their longest edge even when zoomed in.

What would be the best way to constrain the images to a maximum of 2000px in either the smaller, non-responsive viewer and in full screen mode?

Through trying out different things the thing I think I know about maxZoomLevel is that 1 is the width of the parent container. To set this to a restricted value you are dividing 2000 by the width of the container to get the ratio of the width needed to restrict to that size. The problem has been dealing with height as well. I also noticed separately that after I set the maxZoomLevel dynamically there seems to be something stopping it from going below a certain size (and it doesn’t seem to be minZoomLevel), and I don’t really know what that is.

Thanks,
Kay

**Comment by iangilman** [comment]
Welcome to OSD! I'm not sure I understand what you're trying to do... Do you need to constrain the viewer element so it's not bigger than 2000px? Or do you need to make sure the user sees no more than 2000px of the image? How big is the image normally? Or do you need to make sure you never zoom in further than where the image would be 2000px on the screen (if it fit in the window)?

**Comment by kayw-cogapp** [comment]
Hi Ian, 

The zoomable images start from around the 4500px mark on the shortest edges but they can vary, the largest image I have is 18055px on it's longest edge.
 
My objective is to limit the zooms in a way that means that the image is no bigger than 2000px as a whole whether that is in full screen (2000px in full view) or zoomed in to view parts of the image at a time using the smaller viewer. For the latter, if you imagine at the most zoomed in level that we would allow, if the user were to then screen capture all the parts of the image and stitch them back together again, the resulting image would still only be 2000px on it's longest edge.

I was hoping that calculating the maxZoomLevel value from the longest side would achieve that, which it did for widths, but the problem seemed to be checking against heights as well.

I hope that helps clear up what I'm trying to achieve a bit?

Thanks again,
Kay

**Comment by iangilman** [comment]
Setting maxZoomLevel is ultimately what you'll need to do. You'll just need to figure out your target width based on the aspect ratio. In other words, if the image is wider than it is tall, your target width is 2000. If it's taller than it is wide, the target width needs to be based on the aspect ratio. For instance, if it's twice as tall as it is wide, the target width is 1000.

You'll also need to update the maxZoomLevel when the user goes into full screen, since the zoom level is a factor of the viewer size. Unfortunately we don't have an explicit API for this, but it looks like `viewer.viewport.maxZoomLevel = foo` should work fine.

**Comment by kayw-cogapp** [comment]
OK I see. That's really helpful thank you for your help Ian.

**Comment by kayw-cogapp** [comment]
Hi Ian,

The good news is I've gotten the maxZoomLevel set and working how I wanted based on the aspect ratio of the images. However, I'm seeing some weird tile stretching and was wondering if you have seen anything like this before? 

At zoom level 1/ zoomed all the way out the image is perfectly fine but as I begin to zoom in the tiles within the image jerk around a bit where tiles are stretching in different places, where before (when using the default image dimensions from the database) it was very smooth as you'd expect.

Here is the code that I'm using and an example screenshot of the stretches that I'm seeing:

```
  var img_contraints = calculateAspectRatioFit(zoomify_w,zoomify_h,2000,2000);
  
  // initiate viewer on to page with settings
  window.viewer = OpenSeadragon({
    id: id,
    prefixUrl: '../js/openseadragon/images/',
    forceRedraw: true, // Tried this to see if it would solve the stretching problem
    tileSources: [{
      type: "zoomifytileservice", // replacing an old zoomify viewer
      width: img_contraints.width,
      height: img_contraints.height,
      tilesUrl: tilesUrl
    }]

...

  window.viewer.addHandler('open', () => {
    document.body.classList.add('viewer-ready');
    viewer.viewport.maxZoomLevel = setMaxZoom(img_contraints.width,window.viewer);
  }); 
  
  function calculateAspectRatioFit(srcWidth, srcHeight, maxWidth, maxHeight) {
    var ratio = Math.min(maxWidth / srcWidth, maxHeight / srcHeight);
    return { width: Math.floor(srcWidth*ratio), height: Math.floor(srcHeight*ratio) };
  }

  function setMaxZoom (maxWidth,viewer){
    var maxZoom = Math.floor(maxWidth/viewer.viewport._containerInnerSize.x);
    return maxZoom;
  }
```

![image](https://user-images.githubusercontent.com/12559337/33991315-17e46d92-e0c6-11e7-8f27-84883a629a6e.png)
See along the bottom edge?

Thanks again,
Kay

**Comment by iangilman** [comment]
You shouldn't be using `img_contraints` in your tileSource... that's probably confusing things. Just use the natural width and height of the image there, and use the constrained version elsewhere.

**Comment by kayw-cogapp** [comment]
Thanks for all of your help Ian. Got it working exactly as I need now! 3rd times a charm!

**Comment by Pin0** [comment]
Can you share your final solution @kayc-cogapp
