### ISSUE TITLE
Dynamically change url at runtime

### ISSUE THREAD

**Issue by 1Map** [openseadragon/openseadragon#1357]
Hi,

I have a viewer that uses url (not tileSources) to load a single image from a remote url.  Now, this url is dynamic during runtime.  My Question:  How do I load the new image (in other words change the url during runtime) without destroying the openseadragon instance?

**Comment by 1Map** [comment]
Ignore this, you are taking too long

**Comment by thatcher** [comment]
Hi 1Map, sorry if we didn’t respond within a few hours.  It’s a small team, mostly Ian, and of course freely available and open source.  

All images must be consumed through a TileSource. If the image changes dynamically then you must be able to request the new image via a triggered event.

I’d be happy to go over your use case in detail but you have to be willing to wait more than a few hours for a response.

Sincerely, 
Thatcher
