### ISSUE TITLE
Can we change MaxZoomPixelRatio after tiles are already loaded without re-render?

### ISSUE THREAD

**Issue by AsmaAq** [openseadragon/openseadragon#1359]
I have a case in which the user can choose if he wants deeper zoom pixel ratio more than the default supported value (1.1). 

Can I load openSeaDragon with its default value and change it later on after all set and all tiles are loaded? like if he clicked on a checkbox to set MaxZoomPixelRation to 4. 

I did this but no effect was shown at that point. Do I need to destroy and rebuild it again? I guess there is a more simple way to do this without annoying the user about what's happening in the background?

Thanks!

**Comment by iangilman** [comment]
You have to change it in the viewport: 

```
viewer.viewport.maxZoomPixelRatio = 4;
```

Perhaps we should provide an explicit setter for this on the viewer...

**Comment by AsmaAq** [comment]
And this should take effect even so tiles and viewport all loaded?no need to re render after this set?

**Comment by iangilman** [comment]
Yes, it should take effect right away, although if the user is zoomed in further than the new value allows, it won't automatically kick them back. If you want that, you'll have to also do: 

```
viewer.viewport.applyConstraints();
```

**Comment by AsmaAq** [comment]
Thanks @iangilman 

But its not taking effect unless I set the maxZoomPixelRatio value when viewer first created. 
so its first like this:
![image](https://user-images.githubusercontent.com/14885860/34145779-223d52e4-e4a0-11e7-8a7b-63dda935fa6f.png)

Then if I say 
viewer.viewport.maxZoomPixelRatio = 4;

Then I zoom the image, its max zoom is the same as before ( as when value is 1.1)

But If viewer created with 4 from the beginning; zoom max is bigger as expected. 

Should I call anything else to apply the change? 
I've also called applyConstraints but no effect.

Thanks,
Asma

**Comment by iangilman** [comment]
Well, in this code it looks like it would be `parent.previewImageController.viewport.maxZoomPixelRatio = 4`... Is that what you're doing?

**Comment by AsmaAq** [comment]
Oh sorry i was using setting it for the viewer like this:

parent.previewImageController.viewport.viewer.maxZoomPixelRatio 

Yes you are right, now its working perfect. 

Thanks,
Asma

**Comment by iangilman** [comment]
Good to hear :)
