### ISSUE TITLE
Make keyboard speed configurable

### ISSUE THREAD

**Issue by j-hudecek** [openseadragon/openseadragon#1361]
Currently pressing an arrow moves the view by 40 screen pixels. Users with high resolution screens complain that that's too slow. It would be nice if we could change that easily.

**Comment by iangilman** [comment]
Good idea! Those numbers are hard-coded here: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2479

Would you be up for making a patch?

**Comment by iangilman** [comment]
Great! Let me know if you have any questions.
