### ISSUE TITLE
2.3.1 pan broken and zooming stutter

### ISSUE THREAD

**Issue by robhicks** [openseadragon/openseadragon#1367]
I just installed 2.3.1.  

Panning no longer works and zooming in and out causes image jitter which is so bad it is unusable. 

I looked at breaking changes and none seems to apply. 

I have tried to create a JS-Bin, Plunkr, etc. to show the problem but so far no luck. 

If I drop back to 2.2.1 everything works fine.

**Comment by iangilman** [comment]
Wow, that's terrible! Please see if you can come up with a repro that you can share! I'm certainly not seeing those things anywhere else (e.g. http://openseadragon.github.io/).

**Comment by robhicks** [comment]
I guess this can be closed. I cannot reproduce it in the app I'm working on. It is odd that 2.2.1 works though.

**Comment by iangilman** [comment]
So it's something that happened once and you can't get it to happen again? Well, let me know if it happens again!

**Comment by robhicks** [comment]
No it happens all the time in the app I'm working on. I haven't been able to reproduce it outside of the app. If I figure out how, I'll create another issue.

**Comment by iangilman** [comment]
I see. Well, hopefully you can! :)
