### ISSUE TITLE
CSS-filters and SVG-filters lags a lot in Firefox

### ISSUE THREAD

**Issue by victorwallin** [openseadragon/openseadragon#1368]
https://codepen.io/anon/pen/opLrOw 
When even just one filter like sharpen is applied in Firefox, the viewer becomes very slow right away. In chrome it works flawlessly with many filters.

Is this a bug, and if so is there a possible fix?

**Comment by victorwallin** [comment]
I have tried OpenSeadragonFiltering, but when using it with a Sharpen matrix-filter, it enhances and shows the "boxes" of each part of the image, that is why I am not using that at this moment. Is there maybe a fix for that?

**Comment by iangilman** [comment]
Hmm, that's too bad. Looks like there's some discussion about that here:

https://github.com/usnistgov/OpenSeadragonFiltering/issues/4

Maybe you can bump that thread and see if anyone has any thoughts there. 

I imagine the WebGL filtering is probably your best bet, and I'm not seeing any seams in its demo:

http://via.hoff.in/demo/dzi/index.html

Perhaps you can ask @thejohnhoffer how to run a sharpen filter with it.

**Comment by victorwallin** [comment]
@thejohnhoffer Is there a way to use your OpenSeadragonGL to create svg-filters like feConvolveMatrix and feColorMatrix? I am currently using CSS-filters and SVG-filters to modify images with OpenSeadragon, but they are way too slow on Firefox, whereas your demo with WebGL seems to run really smoothly on Firefox too. Thanks for any help!

**Comment by iangilman** [comment]
@victorwallin Are you familiar with GLSL at all? You'll either need to write some yourself or find some already written for the filters you want. Here's a good starting point: http://thebookofshaders.com/

@thejohnhoffer Any pointers for where to get shaders like @victorwallin is looking for?  Seems like it would be a great resource for OpenSeadragonGL.
