### ISSUE TITLE
CPU overload while zoom in JPG/TIF image

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1375]
HI, I am looking at my chrome task manager(chrome->Tools->task manager) 

And I see that the CPU is around 40-60% while zooming on the image (20MB image) jpg or tif/dzi. 
is that ok?  
then it goes back to 10-20%

**Comment by iangilman** [comment]
It certainly seems possible... We're redrawing the screen at 60 frames per second while you're zooming, so the processor certainly is working. 

Just out of curiosity, what sort of tile source is this?

**Comment by johnico** [comment]
one of them is regular JPEG image using regular URL 
the second is with CGI-bin that sperate the tif to smalls jpegs . 
maybe the connection with cgi-bin in my apache is expensive?

**Comment by iangilman** [comment]
Is the Apache running locally? That would certainly contribute to the CPU load.

Anyway, I'm not surprised that animation takes CPU. Of course if you can come up with ideas for how to slim it down, that would be great too.

**Comment by johnico** [comment]
Yes Apache locally . Wamp - windows

**Comment by iangilman** [comment]
Can you get a CPU readout that tells you which process is taking all of the time? How much is your browser and how much is your Apache?
