### ISSUE TITLE
Gray screen in fullscreen mode

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1376]
Hi 
When I open the full-screen mode on the right image (I  present 2 image side by side, 50% width for each of them) the left image become gray until resizing the window.

version: 2.2.1

code:

```
    function maintainZoom() {
        var size1 = new OpenSeadragon.Point(viewer1.container.clientWidth || 1, viewer1.container.clientHeight || 1);
        var size2 = new OpenSeadragon.Point(viewer2.container.clientWidth || 1, viewer2.container.clientHeight || 1);

        viewer1Leading = true;
        viewer2Leading = true;

        viewer1.viewport.resize(size1, true);
        viewer2.viewport.resize(size2, true);

        viewer2.viewport.zoomTo(masterZoom, null, true);
        viewer2.viewport.panTo(masterCenter, true);

        viewer1.viewport.zoomTo(masterZoom, null, true);
        viewer1.viewport.panTo(masterCenter, true);

        viewer1Leading = false;
        viewer2Leading = false;

        viewer1.forceRedraw();
        viewer2.forceRedraw();

    }

    viewer1.addHandler('full-screen',function(a){
        if(a.fullScreen == true){
            viewer1.autoResize = true;
        }
        else
        {
            setTimeout(function () {
                $(window).on('resize', maintainZoom);

                viewer1.autoResize = false;
            }, 400);
        }
    });
    viewer2.addHandler('full-screen',function(a){
        if(a.fullScreen == true){
            viewer2.autoResize = true;
        }
        else
        {
            setTimeout(function () {
                $(window).on('resize', maintainZoom);

                viewer2.autoResize = false;
            }, 400);
        }
    })
```
  
Thanks a lot

**Comment by iangilman** [comment]
Can you make a Codepen of this so I can play with this?

**Comment by johnico** [comment]
@iangilman thanks, I hope you will see the issue in codepen, in my browser it can reproduce

https://codepen.io/anon/pen/XVqKWV 

you need to click on "show" 

and when the images are side by side when you click on full screen . and close it with ESC or with the x you will see grayscreen in the second image 

it something related to the autoresize

thanks

**Comment by iangilman** [comment]
Thank you for making the Codepen. Unfortunately I can't reproduce your issue with it. I've tried Mac Chrome and Firefox, with or without the full-screen event handler. I load the page, hit the show button, and hit the full-screen button for the right viewer, and then hit escape. Both viewers look fine. Any more tips on reproducing it?
