### ISSUE TITLE
OSD canvas appear to be scaled by factor 0.5 when using draw functions

### ISSUE THREAD

**Issue by francescocretti** [openseadragon/openseadragon#1377]
Hi,
I need to draw on my OSD viewer canvas for debug purposes, so I thought that the simplest thing to do would have been to retrieve the canvas object from OSD viewer and use native draw functions (I started from this discussion: #864).

So I did, but the behaviour is quite strange.
For example, if I want to draw a rectangle overlapping to the view bounds, I first get the dimensions of canvas and the (0,0) point this way:

```
var ctx = viewer.drawer.context;
var width = ctx.canvas.clientWidth;
var height = ctx.canvas.clientHeight;
// Point at 0 0 (origin)
var px = viewer.viewport.pixelFromPoint(new OpenSeadragon.Point(0,0), true);
```
and I use them to draw:
```
// Draw canvas bounding box
ctx.beginPath();
ctx.rect(Math.round(px.x), Math.round(px.y),width,height);
ctx.stroke();
```

But the resulting rectangle is 1/4 of the size of the bounding box, as if width and height dimensions were scaled by factor 0.5 when passed to the draw function.

You can see a working demo here: https://codepen.io/francescocretti/pen/QamOex

I added a mouse pointer coordinate logger and a canvas dimensions logger to the page, so you can see the incoherence between actual web coordinates and the objects drew on the canvas. 

I tried also to retrieve the viewport bounds in viewport coordinates and than convert it to web coordinates like this:

```
var ctx = viewer.drawer.context;
// get bounds data
var bounds = viewer.viewport.getBounds();
var canvasBounds = viewer.viewport.viewportToViewerElementRectangle(bounds);
// draw bound rectangle
ctx.beginPath();
ctx.rect(canvasBounds.x, canvasBounds.y, canvasBounds.width, canvasBounds.height);
ctx.stroke();
```
And the result is the same.

I really don't understand what I'm doing wrong.
Any ideas?
My workaround is just to multiply by 2 the dimensions that I need for drawing (such as x or y coordinates for points, circle ratios, rectangle width/height...), and this does the trick. It's not a clean solution but it works . :/
I'm still curious to understand why this happens, though. :)

Thank you in advance,

Francesco

**Comment by iangilman** [comment]
Looks like you're on an HDPI screen (e.g. a Macbook Pro with a retina screen). By getting `ctx.canvas.clientWidth` you're getting the CSS dimensions of the canvas, which are half the actual pixel dimensions (since the HDPI screen has two real pixels per CSS pixel along each dimension). To gethe the actual pixel width, you can use `ctx.canvas.width`. You can also check `OpenSeadragon.pixelDensityRatio` to tell you how dense the screen is.

**Comment by iangilman** [comment]
Btw, you might take a look at https://github.com/altert/OpenSeadragonCanvasOverlay, at least for ideas. Be aware that it uses the image coordinate system for the first image in the viewer, though... This is fine if you just have a single image, but could get weird if you have multiple images at the same time.

**Comment by francescocretti** [comment]
Thank you so much @iangilman !
Everything makes perfectly sense now :)
