### ISSUE TITLE
Opneseadragon Custon Tile source is not working for IE 11 and Edge

### ISSUE THREAD

**Issue by prathibhap8** [openseadragon/openseadragon#1379]
As far as our findings, our cookie is not getting passed in the request header for IE 11 and IE edge.

Is there anyway to pass cookie in openseadragon url ? Anyhelp is really appreciated.

**Comment by iangilman** [comment]
Unfortunately I don't know much about passing cookies. Doesn't it just happen automatically with every call? Is it working on other browsers? Are you seeing any error messages in the console? Is it the same server the page is running on? Can you make a request from elsewhere on the page (not using OSD) that does the right thing? If so, any idea what the difference is?

**Comment by prathibhap8** [comment]
Yeah, cookie is suppose to pass in every calls. It is working fine in all other browsers except IE and edge.
In network tab we could see 404 error, it is due to missing of cookie. And in console, we could find warning as - "DOM7009: Unable to decode image at URL" (it seems these all are due to 404 error. When we try to fetch the image in a separate tab, it is working perfect.

**Comment by iangilman** [comment]
I don't know that OSD is doing anything special with cookies. Does it work if you just try to load one of the image tiles directly on the page? Can you share a link to a repro?
