### ISSUE TITLE
Using Openseadragon as Georeferencing Tool

### ISSUE THREAD

**Issue by 1Map** [openseadragon/openseadragon#1382]
Hi,

I have a question.  I want to use Openseadragon as a Georeferencing tool.  Currently I load my image into Openseadragon.  What I want to achieve is when the user click on the image it should add a point at the clicked position.  The user can click on different positions and add more than 1 point.  When the user click on a existing point it should remove that point.  When the user click and hold on a point it should drag the existing point to the new location.  How can this be done with a single overlay and multiple points in Openseadragon?

**Comment by iangilman** [comment]
Yes, this can be done, though no one has implemented this exact functionality as far as I know. You might look at the plugins: 

http://openseadragon.github.io/#plugins

For instance this one:

https://github.com/picturae/openseadragonselection

If you use the built-in overlays, you'll want one overlay per point. If those overlays don't work the way they want, there are a number of overlay plugins. 

Keep in mind that OSD doesn't have any Geo support, such as converting latitude and longitude. Have you looked at the more Geo specific zooming libraries such as http://leafletjs.com/ or http://openlayers.org/ ? I believe they also support overlays.

**Comment by msalsbery** [comment]
@1Map 

[here's something new](https://github.com/recogito/openseadragon-wmts)
