### ISSUE TITLE
Draw dots upon image on mouse double click

### ISSUE THREAD

**Issue by gt0p** [openseadragon/openseadragon#1383]
First, I create a viewer for a **simple** image

```
{
...
tileSources: {
        type: 'image',
        url: this.getCurrentVersionOfMockup(this.contentStateService.selectedAltMockupOfScreen).imgPath,
        buildPyramid: false
      }
...
}
```

After that, I define a handler for double-click event. 
```
this.osd.addHandler('canvas-double-click', function (event) {
      // The canvas-click event gives us a position in web coordinates.
      var webPoint = event.position;

      // Convert that to viewport coordinates, the lingua franca of OpenSeadragon coordinates.
      var viewportPoint = that.osd.viewport.pointFromPixel(webPoint);

      // Convert from viewport coordinates to image coordinates.
      var imagePoint = that.osd.viewport.viewportToImageCoordinates(viewportPoint);

      function drawDot(imgPoint) {
        var pointSize = 3; // Change according to the size of the point.
        var ctx = document.getElementsByTagName("canvas")[0].getContext("2d");

        let point = that.osd.viewport.imageToViewerElementCoordinates(imgPoint);

        ctx.beginPath();
        ctx.fillStyle = "#FF0000";
        ctx.fillRect(webPoint.x, webPoint.y, 10, 10);

        ctx.fillRect(points.x, point.y, 10, 10);
        ctx.stroke();
      }
      let point = new OpenSeadragon.Point(imagePoint.x, imagePoint.y);
      drawDot(point);
    });
```

Both fillRect() calls draw a dot(same dot as expected) which is not located on the mouse double-click location.
Any idea ?

**Comment by iangilman** [comment]
I'm guessing you're on an HDPI screen (e.g. retina MacBook Pro). The canvas coordinates are different from the web coordinates because of the pixel density. You should be able to multiply your points by `OpenSeadragon.pixelDensityRatio` to get the right value.

**Comment by gt0p** [comment]
Amazing.
Actually, I don't have a retina screen. Your suggestion works in two different monitors. I had not found `OpenSeadragon.pixelDensityRatio` earlier.

Thank you for your time.

**Comment by iangilman** [comment]
Interesting. Well, it also takes into account the density of your browser's backing store, so maybe that's why. Anyway, glad to hear that sorted it out :)
