### ISSUE TITLE
Cannot get 

### ISSUE THREAD

**Issue by RockGuitarist1** [openseadragon/openseadragon#1384]
I am converting canvas images into PNGs using this.

`let img = new Image();
      img.src = canvas.toDataURL('image/png');`

If I was to append img to the body, it will show up just fine, but whenever I try using the source with OpenSeaDragon, I get nothing. It's just a blank screen.

`let viewer = OpenSeaDragon({
        id: 'imageViewer',
        prefixUrl: `${dirname}/node_modules/openseadragon/build/openseadragon/images/`,
        tileSources: {
          type: 'image',
          url: img.src // data:image/png;base64,.... example
        }
      });`

**Comment by iangilman** [comment]
I assume you got this sorted out?
