### ISSUE TITLE
Cannot Load Images via Img.src

### ISSUE THREAD

**Issue by RockGuitarist1** [openseadragon/openseadragon#1385]
I am converting canvas images into PNGs using this.

```
let img = new Image();
img.src = canvas.toDataURL('image/png');
```

If I was to append img to the body, it will show up just fine, but whenever I try using the source with OpenSeaDragon, I get nothing. It's just a blank screen.

```
let viewer = OpenSeaDragon({
    id: 'imageViewer',
    prefixUrl: `${dirname}/node_modules/openseadragon/build/openseadragon/images/`,
    tileSources: {
        type: 'image',
        url: img.src // data:image/png;base64,.... example
    }
});
```

Note that if I remove tileSources, the viewer shows up as intended, but with no image of course.

I have also just tested using legacy-image-pyramid that I found while looking at a post here from 2015 with no luck.

```
        tileSources: {
          type: 'legacy-image-pyramid',
          levels: [{
            url: base64,
            mimetype: 'image/png'
          }]
        }
````

**Comment by iangilman** [comment]
Are you seeing any errors in the console? Are the images coming from the same domain as your page? Otherwise you may be dealing with a tainted canvas security issue.

**Comment by RockGuitarist1** [comment]
Nope no errors. I tested my base64 code in a base64 to image converter and it pops up just fine, but when I use the same base64 code here, nothing shows up.

**Comment by RockGuitarist1** [comment]
Ok so I think I know what the problem is. I am initializing the viewer when the page finishes loading and then setting tileSources to null, because I will not have base64s until about 5 seconds after the page is already loaded since the images are fairly big. Once I am get those base64 urls back, I am setting:

`viewer.tileSources...`

And that doesn't work. If I go only and take a random base64 url and hardcode it into the url property in tileSources when the viewer is initialized, it works fine.

How do I go about applying images to the viewer well after the viewer has already been initialized?

**Comment by RockGuitarist1** [comment]
I figured it out!

I just bit the bullet and threw the viewer initialization inside of the constructor (i'm using Angular 5) and threw my dynamic array in it and it worked. Before I had the viewer initialization inside of ngAfterViewInit and then throwing the array in later, because I feared running into an error related to initializing the viewer before the page exists (hence the constructor). Looks like it all works flawlessly now!

**Comment by iangilman** [comment]
Glad to hear you got it sorted out! You can also call `viewer.open()` with a set of tile sources whenever you want, or you can add tile sources individually using `viewer.addTiledImage()`. Anyway, sounds like what you've got is working just fine :)

**Comment by RockGuitarist1** [comment]
Might not be a bad idea. I have a black box showing until the images are loaded, so using that open function would be good. Next step is figuring out how to add new buttons to the existing toolbar so that I can add print functionality.

**Comment by iangilman** [comment]
Cool... There is a mechanism for that. Let me know if you need help with it.
