### ISSUE TITLE
Is it possible to add bookmark URL?

### ISSUE THREAD

**Issue by tosco** [openseadragon/openseadragon#1390]
Hi,
the only feature I am missing coming from Zoomify is the bookmark URL: http://www.zoomify.pl/demo/zoomify-bookmarks.htm?x=1040&y=1560&z=31
Very useful in two cases: to link a spacific portion of a large image and to easily switch between two images in a collection, keeping the same view.
Can it be added?

**Comment by tosco** [comment]
Yes, a plugin is a good option.
Not a developer, just a user, no idea where to start.
If someone is willing to start I can test it and report.

**Comment by iangilman** [comment]
Fair enough... I'm spreading the word:

https://twitter.com/openseadragon/status/960925378154921984

Hopefully someone will be interested.

**Comment by tosco** [comment]
Great, thanks!

**Comment by iangilman** [comment]
Whoever wants to write this plugin can get some good ideas from the code here:

https://github.com/davidmcclure/osd-dzi-viewer

...or perhaps @davidmcclure would be interested in making such a plugin?

**Comment by iangilman** [comment]
At @jason-green-io's insistence I've gone ahead and made this plugin:

https://github.com/openseadragon/bookmark-url

@tosco please take a look and see if it works for your needs as well!

**Comment by tosco** [comment]
Great!
Tested and works perfectly: it is exactly what I was looking for.
Thanks

**Comment by iangilman** [comment]
@tosco Excellent... thanks for giving it a try!
