### ISSUE TITLE
canvas panning on canvas-drag

### ISSUE THREAD

**Issue by j-hudecek** [openseadragon/openseadragon#1392]
Hi,

I would like to handle canvas-drag event and not have the image pan. I've tried doing this in my canvas-drag handler:

        e.originalEvent.stopPropagation();
        e.preventDefaultAction = true;
        return false;

but it doesn't seem to do anything. Looking a bit at the code it seems that the onCanvasDrag method should return the value from the handler but it never returns anything, updatePointersMove expects it to return a bool propagate and it would cancel the event if it's false, but it's always undefined. 
Am I doing something unexpected/unsupported? Should I just use a MouseTracker?

**Comment by iangilman** [comment]
This works for me:

```
this.viewer.addHandler('canvas-drag', function(event) {
  event.preventDefaultAction = true;
});
```

Are you on the latest version of OSD?

**Comment by j-hudecek** [comment]
Oh yeah you're right. Sorry to bother!
