### ISSUE TITLE
Merging Two Images

### ISSUE THREAD

**Issue by RSantosh09** [openseadragon/openseadragon#1393]
Hi,
I have a requirement where i have a Base image and template Image. Base image just contains the Form Data where as the Template image contains the Form template. (both images have same size)
Now i need to Combine/Merge Template image on top of Base image so that user can see the complete form (i.e. With template and data in the same image). 
I tried various options but actually it is overlapping the base image. only top/overlayed image is visible.
Any help or suggestions are deeply appreciated.
Thanks

**Comment by iangilman** [comment]
In what way do they need to be merged? Is it just an overlay? If so, the top image can have transparency (if it uses PNG tiles).

**Comment by RSantosh09** [comment]
Yes. Overlay is also fine. Only concern is the base/background image should be visible after overlaying the top image.
And yes, my Top image is a PNG image. Could you please provide a link or example to implement the same.

**Comment by iangilman** [comment]
Cool. You just need to make sure your top image has transparent areas in it. And no, you wouldn't use the overlay feature of OSD, you'd just have it be a second image in the viewer. 

```
var viewer = OpenSeadragon({
  tileSources: [
    baseTileSource, // this one is opaque
    topTileSource // this one needs to have transparent bits
  ]
});
```

What kind of image format are you using? DZI? Just straight images? Something else?

**Comment by RSantosh09** [comment]
yes. works like a charm. Using C# code i made my top image as Transparent, and passed this image as TOP image in tile source as you said. its done. now both Base & top images are visible.
Thanks a lot. Cheers!!!

**Comment by iangilman** [comment]
Great to hear it!

**Comment by tufail** [comment]
Hi @iangilman ,
I like check the difference between these two dzi images. Is it possible to add class to dzi images so that I can apply css filter to it Or else any method already exist in the plugin. Please help me.
Thanks

**Comment by iangilman** [comment]
@tufail If you have two images in the viewer, you can apply a composite operation to the top one to have it draw differently. For instance:

```
var topImage = viewer.world.getItemAt(1);
topImage.setCompositeOperation('difference');
```

Another option would be to have two viewers stacked on top of each other, each with their own image. You could then add a CSS filter to the top viewer. This would of course require synchronizing the viewers, so it would be more work than the first approach.
