### ISSUE TITLE
How to fetch image co-ordinates to save in database?

### ISSUE THREAD

**Issue by KrupaRajashekar** [openseadragon/openseadragon#1395]
Hi,

I am using Openseadragon with FabricJs overlay. Now in order to need to save the free-hand annotations as well as other annotations in a database, I need the image co-ordinates of the annotations. How can i retrieve the co-ordinates? Any help on this appreciated! Thanks.

**Comment by iangilman** [comment]
Looks like that's discussed here:

https://github.com/altert/OpenseadragonFabricjsOverlay/issues/16

...assuming you know how to get coordinates from the Fabric objects. For instance, when you set up your fabric overlay, you can use your image's natural width as the scale option, and then all of the Fabric objects will use those coordinates. Then you can just grab the `left` and `top` or whatever you need from your Fabric objects: 

http://fabricjs.com/docs/fabric.Object.html

**Comment by KrupaRajashekar** [comment]
Hi Ian,

Thanks for answering that. Based on your input, I made the scale of Fabricjs to be same as width of my image. This helped in avoiding convertion between co-ordinates, but I am having trouble with positioning of fabric objects. When I render the objects on my image, it is not showing at the right position. It is shifting about 10px to the right.

The co-ordinates are showing correctly when i hover-over the mouse on the image. But the object is not placed at the right position. Can you please help with this? Thanks in advance.

**Comment by iangilman** [comment]
[I edited your comment to wrap the code in ``` so it'll display better]

It's hard for me to tell from that code what might not be working. Can you make a CodePen or some such with a simple repro, and I can fiddle with that?

**Comment by KrupaRajashekar** [comment]
Hi Ian,

I figured out the problem - I was setting the 'left' and 'top' of the
polyline object from the first 2 co-ordinate points from the array.
Instead, 'left' and 'top' should be the minimum value of all co-ordinates.
I calculated min of x and y and made it as 'left' and 'top'. That worked.

Thanks for responding :)

Regards,
Krupa

**Comment by iangilman** [comment]
Great! Glad to hear it :)

**Comment by KrupaRajashekar** [comment]
Hi Ian,

Sorry to bother you again, but this is an extension of my initial question. I am having trouble with my free-hand elements, drawn using fabricJs overlay. 
The free-hand polylines are being drawn fine, but I need to send the details of these elements to a database (co-ordinates etc). Now, i have kept the scale same as my image width, so there is no need for co-ordinate conversion. But how do I get coordinates & other details from the Fabric polyline object?

Below is my code for free-hand polyline drawings:

self.viewer.setMouseNavEnabled(false);
self.viewer.outerTracker.setTracking(false);
overlay.fabricCanvas().isDrawingMode=true;
overlay.fabricCanvas().freeDrawingBrush.color = 'red';
overlay.fabricCanvas().freeDrawingBrush.width = 5;

Please help! Thanks.

**Comment by iangilman** [comment]
I don't really know anything about Fabric; you will have to look at their docs. I imagine for polyline you want the points member: 

http://fabricjs.com/docs/fabric.Polyline.html#points
