### ISSUE TITLE
Question: Is there a recommended iiif server to render images with alpha channel for use with multi-layer (i.e. multiple tile sources, stacked)?

### ISSUE THREAD

**Issue by chaimpeck** [openseadragon/openseadragon#1397]
I would like to use openseadragon to display multiple layers of images with transparency.

I know that this is possible with pre-rendered png's and a custom tile-source. There is a nice example of that here:
https://openseadragon.github.io/examples/tilesource-custom/

But, I would like to use an image server. I already tried iipsrv, which does not render transparency. I also tried go-iiif, which will render transparent png's extremely slowly. It might be usable if I can find a way around that issue, but not at the moment.

I am looking at some other options at the moment, but I would like to get some input as to whether there is an ideal/recommended way to accomplish this.

**Comment by iangilman** [comment]
@azaroth42 Any suggestions?

**Comment by azaroth42** [comment]
I would ask on iiif-discuss: https://groups.google.com/forum/#!forum/iiif-discuss 

As far as I know Loris will maintain the alpha channel of PNGs, but I have no idea about performance relative to other servers. It's very fast for JPEG2000s, but they're optimized for tile based delivery.

**Comment by chaimpeck** [comment]
Thank you for the response.

After trying some things, I came to the conclusion that pre-rendered is the way to go with png's. I was impressed with how simple it is to create a .dzi out of my images with `vips dzsave`, and I can then upload to s3 and point openseadragon at it.

With that solution, I am all set.

Thanks!

**Comment by iangilman** [comment]
@chaimpeck Glad you found something that worked!

@azaroth42 thank you as always for the words of wisdom :)
