### ISSUE TITLE
How to manipulate images from cloud? 

### ISSUE THREAD

**Issue by samzalahi** [openseadragon/openseadragon#1398]
hi, i am literally newbee to  #openseadragon, i have 1000s of high resolution of images (book's pages as jpg image format) in my cloud, i have a web app same as Image Reference Strip feature without openseadragon or zoom function, im fetching minimum 150 book pages per book in one click from my cloud along with book info from mysql (i dunno this is the best way and tell me if there is best way in openseadragon).  So i was planing to make that zoomable image to my app then only i found openseadragon, now im thinking, do i need to make Image Reference Strip instead of my previous feature or i can add some codes to make it zoomable by openseadragon? if its so, for me its really hard to find how to archive this in openseadragon, anyone please explain me how can i archive this

**Comment by iangilman** [comment]
How big are your images? If they are under 3000px wide, you can probably load them with the "Simple Image TileSource" and not have to convert them: 

http://openseadragon.github.io/examples/tilesource-image/

You should be able to just put the OSD viewer in place of your existing images, and use the reference strip you already have.

I'd recommend starting off by getting an OSD viewer working in a temporary page, just so you get the hang of it. Then you can work on integrating it into your viewer page. Let me know if you have additional questions.

**Comment by samzalahi** [comment]
Thank you very much for your reply mate, i have done it but when i click my other images from thumbnail old big image still there and it is adding other image bellow it, what should i do for this, do i need to hide the previous image when it click new image? how i can do that, explain me please

**Comment by iangilman** [comment]
Are you adding the new images with  `viewer.addTiledImage`? If so, you can remove them with `viewer.world.removeItem`.

If just want to replace one image with the next, you can also just to `viewer.open`, which closes the current image and opens the new one.

**Comment by samzalahi** [comment]
No im not using `viewer.addTiledImage` , im just getting image url and sending into tilesource, so when i click new image old image still there

**Comment by iangilman** [comment]
I see! You were creating a whole new viewer each time. You only need to create one viewer, and then you can have it open one image after the next, like so:

```
var viewer = OpenSeadragon({
     id:"seaDragon",
     prefixUrl: "js/images/"
 });
 
$(".book").click(function() {
        var currIndex = $(this).index();
        var src = $(this).find('img').attr('src');
        var tileSource = {
             type: "image",
             url: src,
             buildPyramid:false
        };
        
        viewer.open(tileSource);
});
        
```

**Comment by samzalahi** [comment]
Thank you very much mate, it was very helpful, i know it is very basic but im also new to this. i have some question,  
1. as u said if images are under 3000px wide why Simple Image TileSource is enough and no need to convert into DZI? also what will happen if i convert my under 3000px images?
2. the way i did this getting 100s of images by one click from file server and put it as thumbnails then getting particular image src and placing in one place is efficient or is there is any other best and speedy way?
please explain me. i really do not know that much about image processing, again thank you very much

**Comment by iangilman** [comment]
I was just saying that with internet speeds these days, a 3000px image can download pretty quickly, so it's okay if you don't turn it into a DZI. Even so, it's fine, and perhaps even smoother, if you do turn it into a DZI.

As for loading hundreds of images for your thumbnails, that'll probably cause some slowness, just because of how many transfers that is. One way to speed that up would be to put small versions of all of those images into a single image for the transfer and then break it apart for display in the browser. That's not something OSD can help you with though. Here's some information on doing this with CSS: https://www.w3schools.com/css/css_image_sprites.asp
