### ISSUE TITLE
Question: Add multiple images to viewer using the Openslide Python API.

### ISSUE THREAD

**Issue by aris-ang** [openseadragon/openseadragon#1399]
Hello.

I'm new to OpenSeadragon and JavaScript in general, and i'm trying to view whole slide images using the Openslide Python API, which views WSIs on web browsers, utilizing OpenSeadragon. Basically, i'm using Flask to create URLs for the images i want to load and then create an OSD instance on a html page and load the images on it.

I have no problem loading a single image on a viewer. The problem is that, i call the viewer.addTiledImage() function with a tile source that is in .dzi format and the image is not added to the existing viewer. This is the html file with OpenSeadragon:

```
<!doctype html>
<meta charset="utf-8">
<title>{{ slide_filename }}</title>

<style type="text/css">
html {
    overflow: hidden;
}
body {
    margin: 0;
    padding: 0;
}
div#view {
    position: absolute;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: black;
    color: white;
}
</style>

<div id="view"></div>

<script type="text/javascript" src="{{ url_for('static', filename='jquery.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='openseadragon.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='openseadragon-scalebar.js') }}"></script>
<script type="text/javascript">
$(document).ready(function() {
    var viewer = new OpenSeadragon({
        id: "view",
        tileSources: "{{ slide_url }}",
        prefixUrl: "{{ url_for('static', filename='images/') }}",
        showNavigator: true,
        showRotationControl: true,
        animationTime: 0.5,
        blendTime: 0.1,
        constrainDuringPan: true,
        maxZoomPixelRatio: 2,
        minZoomLevel: 1,
        visibilityRatio: 1,
        zoomPerScroll: 2,
        timeout: 120000,
    });
    viewer.addHandler("open", function() {
        // To improve load times, ignore the lowest-resolution Deep Zoom
        // levels.  This is a hack: we can't configure the minLevel via
        // OpenSeadragon configuration options when the viewer is created
        // from DZI XML.
        viewer.source.minLevel = 8;
    });
    var mpp = parseFloat("{{ slide_mpp }}");
    viewer.scalebar({
        pixelsPerMeter: mpp ? (1e6 / mpp) : 0,
        xOffset: 10,
        yOffset: 10,
        barThickness: 3,
        color: '#555555',
        fontColor: '#333333',
        backgroundColor: 'rgba(255, 255, 255, 0.5)',
    });
	viewer.addTiledImage({
	tileSource: 'http://127.0.0.1:5000/templates/Test_004.tif_overlay.dzi',
	x: 0,
	y: 0,
	height: 1000,
	degrees: 90,
    });

});
</script>

```
The slide_url value is: http://127.0.0.1:5000/templates/Test_001.tif.dzi. Accessing this URL on the browser returns:
```
<Image Format="jpeg" Overlap="1" TileSize="254"><Size Height="89600" Width="86016"/></Image>
```
and accessing the URL of the tileSource in viewer.addTiledImage() views this:
```
<Image Format="jpeg" Overlap="1" TileSize="254"><Size Height="103936" Width="98304"/></Image>
```
Both images are .tif files, and as far as i can tell i get the .dzi files for both of them, in order to view them with OSD. Any help would be greatly appreciated.

Thanks in Advance.

**Comment by iangilman** [comment]
If you just want to load them both at the beginning, you can pass them both into the `tileSources` option when you create the viewer, like so:

```
var viewer = new OpenSeadragon({
  tileSources: [
    "{{ slide_url }}",
    {
    	tileSource: 'http://127.0.0.1:5000/templates/Test_004.tif_overlay.dzi',
    	x: 0,
    	y: 0,
    	height: 1000,
    	degrees: 90,
    }
  ],
  // Remaining options go here
});
```

You can of course also use `addTiledImage` to add additional images after the first one has loaded if you prefer. However, the initial open is actually async, so I believe you can't add new images until after the `open` event fires. Probably what's currently happening is that the open is fighting with the addTiledImage.

**Comment by aris-ang** [comment]
Thank you very much for the quick reply. Your answer worked well, but i seem to have misunderstood things, and my question was not set in the right way.

What i'm trying to do is overlay one image above the other. Just like in the example at the Multi-Image documentation page of OSD (http://iangilman.com/openseadragon/chrisjordan/) but without the zooming. Any tips about how i could do that?

Thanks again.

**Comment by iangilman** [comment]
I see. Well, the example I gave above should already have it overlayed, but since you're not giving explicit layouts to the first image (which will be the bottom of the stack), it's probably not where you want it. Something like this might be more like what you're trying to do:

```
var viewer = new OpenSeadragon({
  tileSources: [
    {
      tileSource: "{{ slide_url }}",
      x: 0,
      y: 0,
      height: 1000
    },
    {
    	tileSource: 'http://127.0.0.1:5000/templates/Test_004.tif_overlay.dzi',
    	x: 300,
    	y: 300,
    	height: 300,
    	degrees: 90,
    }
  ],
  // Remaining options go here
});
```

**Comment by aris-ang** [comment]
Hello again. I added your code and i got the following error:
Unable to open[Object object]: Unable to load TileSource.

This must be the reason it didn't load the overlay with your previous example code. The same error should have come up for the overlay. The Openslide Python implementation loads the tiles of the image on the fly instead of creating static tiles. Is that involved with the whole problem?

I am adding the code with which the application loads the tiles
```
@app.route('/<path:path>_files/<int:level>/<int:col>_<int:row>.<format>')
@app.route('/<path:path>_overlay_files/<int:level>/<int:col>_<int:row>.<format>')
def tile(path, level, col, row, format):
    slide = _get_slide(path)
    format = format.lower()
    if format != 'jpeg' and format != 'png':
        # Not supported by Deep Zoom
        abort(404)
    try:
        tile = slide.get_tile(level, (col, row))
    except ValueError:
        # Invalid level or coordinates
        abort(404)
    buf = PILBytesIO()
    tile.save(buf, format, quality=app.config['DEEPZOOM_TILE_QUALITY'])
    resp = make_response(buf.getvalue())
    resp.mimetype = 'image/%s' % format
    return resp
```
Nevertheless, the viewer works perfectly for both images when not trying to set one on top of the other, which i suppose means that the tiles can be found.

**Comment by aris-ang** [comment]
Yes, slide_url gets a proper, working url. I am using the latest version of openseadragon.
This is the link to the project: https://github.com/aris-ang/wsi_image_overlay

The images need to be added to the template folder. I used .tif images.
I should also mention that the project requires an installation of openslide and openslide python.

Thank you for your time.

**Comment by aris-ang** [comment]
Ok, i tried it again making some changes here and there and it finally works. It seems i assigned the wrong url to the overlay, plus i had some trouble with my text editor regarding the indentation...
![test_001 tif - mozilla firefox_004](https://user-images.githubusercontent.com/35759590/36477836-5580afbe-170b-11e8-9c63-09eae9edaa59.png)

Thank you very much for your help!

**Comment by iangilman** [comment]
Beautiful! :)

**Comment by rwtam121** [comment]
Hi Aris and Ian,
I'd like to follow up with you both on this project since I am doing something similar, creating overlays on high resolution images. I am also using OpenSlide's DeepZoom code (https://github.com/openslide/openslide-python/blob/master/examples/deepzoom/deepzoom_multiserver.py) and also looking to place an overlay on top of the image. 

I modified the javascript template file called "slide-fullpage" with displays the zoomable slide image according to Ian's advice. This is the part I modified (highlighted in bold):

`$(document).ready(function() {
    var viewer = new OpenSeadragon({
        id: "view",
	**tileSources: [
	  {
        	tileSource: "{{ slide_url }}",
		x:60,
		y:60,
		height:8000
	  },
	  {
    		tileSource: 'http://127.0.0.1:5000/JP2K-33003-1.svs',
		x:500,
		y:500,
		height:4000,
		degrees:90,
	  },
	],**
        prefixUrl: "{{ url_for('static', filename='images/') }}",
        showNavigator: true,
        showRotationControl: true,
        animationTime: 0.5,
        blendTime: 0.1,
        constrainDuringPan: true,
        maxZoomPixelRatio: 2,
        minZoomLevel: 1,
        visibilityRatio: 1,
        zoomPerScroll: 2,
        timeout: 120000,
    });`

The slide_url is referenced from the python script which pulls the url for the high resolution image, and 
JP2K-33003-1.svs is recognized as one of the available slides when I deploy my python code (I plan on using it as the overlay). However, when I re-ran the script it says "Unable to open object[object]; unable to load TileSource". The original code was tileSources: "{{ slide_url }}" which worked well to display the slide image. I'm wondering if I have any indentation errors or anything similar in my code. 

Ryan

**Comment by aris-ang** [comment]
Hello Ryan.

I'm going to try to explain the functionality of the code so that i can help you the best i can. What happens is that openslide actually creates tiles of the initial image and a .dzi file that utilizes those tiles to view them on openseadragon. Openseadragon works only with .dzi files, not .tiff, .svs or other file types. The tile creation happens in tile and get_tile functions. The dzi and slide functions are responsible for creating the dzi files and rendering the html template respectively. If you take a look, the app route of the dzi function is <path>.dzi, which means that the dzi file you need to access for viewing the image is most probably at this url: http://127.0.0.1:5000/JP2K-33003-1.svs.dzi. I believe this should work if you haven't modified the app routes of the functions, or other code too much.

Hope this helps.

**Comment by rwtam121** [comment]
Hi Aris, thank you so much for the insight and quick response. I was able to access the http://127.0.0.1:5000/JP2K-33003-1.svs.dzi from the browser : 

<Image xmlns="http://schemas.microsoft.com/deepzoom/2008" Format="jpeg" Overlap="1" TileSize="254">
<Size Height="17497" Width="15374"/>
</Image>

I made the modification here and didn't modify anything in deepzoom_multiserver.py : 
![slide-fullpageimg](https://user-images.githubusercontent.com/29108723/36914093-ec23eb10-1e00-11e8-84a2-100d546aab9a.png)

But I still got the "Unable to open object[object]; unable to load TileSource" when trying to open the image. One thing I noticed was when I put 	tileSource: "{{ slide_url }}" I can't see the image anymore (it doesn't say unable to load TileSource; it just shows a black screen). If I just do "{{ slide_url }}" without putting tileSource in front, the image shows up. 

Also, putting brackets in front of my code 
	    {
        	"{{ slide_url }}",
	    },
causes a black screen as well. 

I noticed that when I commented out the brackets, the image from the slide_url shows up but the overlay svs.dzi does not:

![slide-fullpageimgtwo](https://user-images.githubusercontent.com/29108723/36914635-c9e14f3c-1e02-11e8-96ee-3accf2be4713.png)

Just wondering if I have any indentation errors or some other underlying issue with this.

Thank you,
Ryan

**Comment by aris-ang** [comment]
Hi again,

One problem that i see right now is that you have an unnecessary comma in your code, right after the closing bracket of the second tile source, which most probably throws a syntax error. Generally, if nothing but black screen shows up, it's most probably a syntax error. You can always right click on the html page and inspect the elements on it. If you click on the console tab after doing that, you will be able to see any errors that you get from your code.

**Comment by iangilman** [comment]
I'm unfamiliar with OpenSlide... can you tell me what `{{slide_url}}` expands to? You can just do a view source on that page and copy out that section. That might shed some light. 

And yes, checking the browser console is also a good idea!

**Comment by loathing-diffuse** [comment]
> Ok, i tried it again making some changes here and there and it finally works. It seems i assigned the wrong url to the overlay, plus i had some trouble with my text editor regarding the indentation... ![test_001 tif - mozilla firefox_004](https://user-images.githubusercontent.com/35759590/36477836-5580afbe-170b-11e8-9c63-09eae9edaa59.png)
> 
> Thank you very much for your help!





https://stylesheets.space/questions/create-a-dynamic-web-design-by-seamlessly-layering-one-image-on-top-of-two

**Comment by iangilman** [comment]
@loathing-diffuse That's for regular images in CSS; it doesn't work the same in this library.
