### ISSUE TITLE
Question: Display image regions using iiif Image API

### ISSUE THREAD

**Issue by imoutsatsos** [openseadragon/openseadragon#1400]
I have used OSD successfully to display full size images served from a iiif image server by configuring an imgUrl array where the image URLs are post-fixed with info.json. In this case OSD works with the image server to retrieve zoomable images.

Now I have a new requirement to retrieve several regions from the full image that represent ROIs. I can use the image API to retrieve these directly in the web browser and even can retrieve them in OSD using an array of 
`{type:'image', url:'http://cantaloupe.net:8182/iiif/2/%2FE10_4%2Ftest100_CorrRNA_Image.jpg/484,23,100,100/pct:40/0/default.jpg'},
{type:'image', url:'http://cantaloupe.net:8182/iiif/2/2Ftest100_CorrRNA_Image.jpg/961,78,100,100/pct:40/0/default.jpg'}
`
where a 100X100 px image region is defined by a parameter like: 484,23,100,100 (x,y,width,height)
![image](https://user-images.githubusercontent.com/3408226/36274500-eb7f1b32-1255-11e8-9ecf-cdf97e5317ed.png)

These images however, are no longer zoomable in OSD.

Can OSD and a iiif image servers work in tandem to load these regions so they can be zoomable?
In general I'm confused on how the iiif [image request parameters](http://iiif.io/api/image/2.0/#image-request-parameters) can be used from the OSD viewer.

**Comment by iangilman** [comment]
It's probably not zoomable just because it's too low res for OSD to consider it worth zooming. You can tell it to allow further zooming by changing the `maxZoomPixelRatio` option when you create the viewer. It's normally 1.1 (meaning that you can zoom in 10% beyond full resolution)... try changing it to 10 or something.

I don't know enough about IIIF to know whether you can get a higher resolution patch of that POI.

Tagging @azaroth42 in case he has any further thoughts.

**Comment by azaroth42** [comment]
It's also not zoomable as there's no way to specify x,y offset and h,w into the full image to construct tiles from.  It would require a level 2 implementation of IIIF Image API that can generate arbitrary regions, as these would not be the regular tiles (which is fine for Loris, Cantaloupe, IIP etc ... not so great for less functional implementations).

It would require adding the additional region information as an input param to the IIIF TileSource, then using those values to construct the requests.  It's possible to implement, I think, but we haven't :)

**Comment by imoutsatsos** [comment]
Yes, I agree with you @iangilman. Indeed the tile is only 100x100 pixels by the API request and so it is already 'zoomed-in' . But I can't zoom out either in the sequence OSD viewer at least using the standard controls. 

I'm also gradually realizing that there are several open TO DOs in the OSD- IIIF TileSource including my previous challenge requesting tiles in a different format #1293 (jpeg is currently the only one, although iiif supports others). @azaroth42 I wish I was more proficient in javascript to help with the implementation :-(

**Comment by iangilman** [comment]
Yes, hopefully someone will volunteer to take these issues on!

@imoutsatsos Meanwhile, would it make sense to stick with the original full resolution image and use the viewer to zoom in on the area of interest?
