### ISSUE TITLE
Change keyboard navigation behaviour

### ISSUE THREAD

**Issue by francescocretti** [openseadragon/openseadragon#1405]
I use an OSD viewer in my web-app and I have the need of preventing some navigation keyboard commands (such as vertical panning with up/down arrows) under certain conditions.
I could not find anything useful in the documentation except for a method to disable all the keyboard handler (`viewport.viewer.innerTracker.keyHandler = null`).
I tried to use the event.preventDefault() function this way:

```
  window.addEventListener('keydown', function (e) {
    if ( my condition ) {
      if (e.key === "ArrowUp" || e.key === "ArrowDown") {
        e = e || window.event;
        e.preventDefault();
      }
    }
  });
```

But is not working. 

This issue #1219 refers to redirecting key events to OSD when the container is not focused, so it does not help me.
Is there any workaround to obtain this?

Thank you so much,
Francesco

**Comment by iangilman** [comment]
Unfortunately the keyboard code isn't terribly customizable at the moment. For your scenario, I think what we'd want is a keyboard event that the viewer could raise that would include a `preventDefaultAction` like the `canvas-click` and other events do. That would happen in both `onCanvasKeyDown` and `onCanvasKeyPress` starting around here:

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2479

You can look at `onCanvasClick` to see how it's done:

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2566

If you're not up for making this patch and just want to hack it, you'll need to make your own copies of `onCanvasKeyDown` and `onCanvasKeyPress` and assign them to `viewer.innerTracker.keyDownHandler` and `viewer.innerTracker.keyHandler` respectively.

**Comment by francescocretti** [comment]
Ehy @iangilman thanks as always for the quick response. I can try!
Do you have any "best practice guide" or similar for writing a patch for OSD? I
Sorry but I've never done it before.

Francesco

**Comment by francescocretti** [comment]
Hey @iangilman I've done it!
I edited the two handlers directly in the OSD source code this way:

```
function onCanvasKeyDown( event ) {

  var canvasKeyDownEventArgs = {
      originalEvent: event.originalEvent,
      preventDefaultAction: event.preventDefaultAction,
      preventVerticalPan: event.preventVerticalPan,
      preventHorizontalPan: event.preventHorizontalPan
  };

  this.raiseEvent( 'canvas-key-down', canvasKeyDownEventArgs);

  if ( !canvasKeyDownEventArgs.preventDefaultAction && !event.ctrl && !event.alt && !event.meta ) {
    switch( event.keyCode ){
      case 38://up arrow
        if (!canvasKeyDownEventArgs.preventVerticalPan) {
          if ( event.shift ) {
            this.viewport.zoomBy(1.1);
          } else {
            this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(0, -40)));
          }
          this.viewport.applyConstraints();
        }
      return false;
      case 40://down arrow
        if (!canvasKeyDownEventArgs.preventVerticalPan) {
          if ( event.shift ) {
            this.viewport.zoomBy(0.9);
          } else {
            this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(0, 40)));
          }
          this.viewport.applyConstraints();
        }
        return false;
      case 37://left arrow
        if (!canvasKeyDownEventArgs.preventHorizontalPan) {
          this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(-40, 0)));
          this.viewport.applyConstraints();
        }
        return false;
      case 39://right arrow
        if (!canvasKeyDownEventArgs.preventHorizontalPan) {
          this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(40, 0)));
          this.viewport.applyConstraints();
          return false;
        }
      default:
        //console.log( 'navigator keycode %s', event.keyCode );
        return true;
      }
    } else {
      return true;
    }
}

function onCanvasKeyPress( event ) {
  var canvasKeyPressEventArgs = {
      originalEvent: event.originalEvent,
      preventDefaultAction: event.preventDefaultAction,
      preventVerticalPan: event.preventVerticalPan,
      preventHorizontalPan: event.preventHorizontalPan
  };

  this.raiseEvent( 'canvas-key-down', canvasKeyPressEventArgs);

    if ( !canvasKeyPressEventArgs.preventDefaultAction && !event.ctrl && !event.alt && !event.meta ) {
        switch( event.keyCode ){
            case 43://=|+
            case 61://=|+
                this.viewport.zoomBy(1.1);
                this.viewport.applyConstraints();
                return false;
            case 45://-|_
                this.viewport.zoomBy(0.9);
                this.viewport.applyConstraints();
                return false;
            case 48://0|)
                this.viewport.goHome();
                this.viewport.applyConstraints();
                return false;
            case 119://w
            case 87://W
            if (!canvasKeyPressEventArgs.preventVerticalPan) {
                if ( event.shift ) {
                    this.viewport.zoomBy(1.1);
                } else {
                    this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(0, -40)));
                }
                this.viewport.applyConstraints();
              }
                return false;
            case 115://s
            case 83://S
            if (!canvasKeyPressEventArgs.preventVerticalPan) {
                if ( event.shift ) {
                    this.viewport.zoomBy(0.9);
                } else {
                    this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(0, 40)));
                }
                this.viewport.applyConstraints();
              }
                return false;
            case 97://a
            if (!canvasKeyPressEventArgs.preventHorizontalPan) {
                this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(-40, 0)));
                this.viewport.applyConstraints();
              }
                return false;
            case 100://d
            if (!canvasKeyPressEventArgs.preventHorizontalPan) {
                this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(40, 0)));
                this.viewport.applyConstraints();
              }
                return false;
            default:
                //console.log( 'navigator keycode %s', event.keyCode );
                return true;
        }
    } else {
        return true;
    }
}
````

So in the app is possible to handle keyboard events like this, e.g.:

```
viewer.addHandler('canvas-key-down', function (e) {
   e.preventDefault = true; // disable default keyboard controls
   e.preventVerticalPan = true; // disable vertical panning with arrows and W or S keys
   e.preventHorizontalPan = true; // disable horizontal panning with arrows and A or D keys
});
```

**Comment by iangilman** [comment]
Looks fantastic! I'd love it if you could make that into a pull request. Here's our guide:

https://github.com/openseadragon/openseadragon/wiki/Making-a-Pull-Request

**Comment by francescocretti** [comment]
Done ;)

I also did another edit, this time in the navigator code: when you set panHorizontal/panVertical to false, the panning was actually prevented only for the drag action, and not for the click action (the user was able to pan in the prevented direction just clicking one time on the minimap). 

Now when panHorizontal/panVertical is set to false, the click action triggers a vertical/horizontal only panning.

If you're interested, I can make a pull request also for this.

Francesco

**Comment by iangilman** [comment]
Good catch (panning with the minimap)! Yes, please make a new pull request for that :) Thank you!

**Comment by luna-red** [comment]
Hey guys.  Are there any specials options I have to turn on to get this new handler to fire?  Currently, I have the latest OSD version installed and have many working handlers.  I just wired this one up with the new convention name of 'canvas-key' per the source code, and it never fires.

**Comment by iangilman** [comment]
@luna-red Can you share a repro or some code? Also, have you clicked into the viewer before testing the keys? I believe the viewer needs to have focus in order for the keys to work.

**Comment by luna-red** [comment]
Yes, I clicked into the viewer:
    this.viewer.addHandler(eventTypes.canvaskey, function (e) {
      console.log('we have keyPress Event in OSD')
      // e.preventDefault = true; // disable default keyboard controls
      // e.preventVerticalPan = true; // disable vertical panning with arrows and W or S keys
      // e.preventHorizontalPan = true; // disable horizontal panning with arrows and A or D keys
    }, _this)
    
for eventTypes, I've tried, 'canvas-key' as well as 'canvas-key-down'.  In conjunction with this code, I have many handlers working, including the following:
(I've removed code from some of the functions for readability)

    this.viewer.addHandler('page', (data) => { }, this)
    this.viewer.addHandler('open', () => { }, this)
    this.viewer.addHandler('tile-load-failed', () => { }, this)
    this.viewer.addHandler(eventTypes.press, this[eventTypes.press], _this)
    this.viewer.addHandler(eventTypes.drag, this[eventTypes.drag], _this)
    this.viewer.addHandler(eventTypes.release, this[eventTypes.release], _this)
    this.viewer.addHandler(eventTypes.click, this[eventTypes.click], _this)


I upgraded from version 2.4.2 to 3.1.0 so that I could use this keypress code. In the meanwhile, what I've done is just turned off all the kepress handling like so => this.viewer.innerTracker.keyDownHandler = null

Then, I set up a Mousetracker instance which now handles all the keypress events.  I added back the arrow key functionality wrapped in if/else blocks so that I can control when they fire and used variations of the following code:

            const point = new OpenSeadragon.Point(0,-40)
            const pixelDelta = _this.viewer.viewport.deltaPointsFromPixels(point)
            _this.viewer.viewport.panBy(pixelDelta)
            _this.viewer.viewport.applyConstraints()

I've also found ways to do zoom in and out, so basically I am no longer blocked, but I was thinking having a built in handler for concise control of keypress events would have been nice.

**Comment by iangilman** [comment]
@luna-red Good to hear you've found a solution! I still don't know why `canvas-key` isn't working for you. I just tested it now by adding:

```
        viewer.addHandler('canvas-key', function(event) {
            console.log(event);
        });
```

... To this file: 

https://github.com/openseadragon/openseadragon/blob/master/test/demo/basic.html

... And it worked just fine. There must be something in your code that's causing the issue. 

I assume you were having the issue before you did ` this.viewer.innerTracker.keyDownHandler = null`, right? Because that certainly would cause it. 

BTW, while taking a look at this, I did notice an issue which I've filed as https://github.com/openseadragon/openseadragon/issues/2192. That's not the cause of your issue, though, since it's creating too many events, rather than not enough.

**Comment by raresgaia** [comment]
> Hey @iangilman I've done it! I edited the two handlers directly in the OSD source code this way:
> 
> ```js
> function onCanvasKeyDown( event ) {
> 
>   var canvasKeyDownEventArgs = {
>       originalEvent: event.originalEvent,
>       preventDefaultAction: event.preventDefaultAction,
>       preventVerticalPan: event.preventVerticalPan,
>       preventHorizontalPan: event.preventHorizontalPan
>   };
> 
>   this.raiseEvent( 'canvas-key-down', canvasKeyDownEventArgs);
> 
>   if ( !canvasKeyDownEventArgs.preventDefaultAction && !event.ctrl && !event.alt && !event.meta ) {
>     switch( event.keyCode ){
>       case 38://up arrow
>         if (!canvasKeyDownEventArgs.preventVerticalPan) {
>           if ( event.shift ) {
>             this.viewport.zoomBy(1.1);
>           } else {
>             this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(0, -40)));
>           }
>           this.viewport.applyConstraints();
>         }
>       return false;
>       case 40://down arrow
>         if (!canvasKeyDownEventArgs.preventVerticalPan) {
>           if ( event.shift ) {
>             this.viewport.zoomBy(0.9);
>           } else {
>             this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(0, 40)));
>           }
>           this.viewport.applyConstraints();
>         }
>         return false;
>       case 37://left arrow
>         if (!canvasKeyDownEventArgs.preventHorizontalPan) {
>           this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(-40, 0)));
>           this.viewport.applyConstraints();
>         }
>         return false;
>       case 39://right arrow
>         if (!canvasKeyDownEventArgs.preventHorizontalPan) {
>           this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(40, 0)));
>           this.viewport.applyConstraints();
>           return false;
>         }
>       default:
>         //console.log( 'navigator keycode %s', event.keyCode );
>         return true;
>       }
>     } else {
>       return true;
>     }
> }
> 
> function onCanvasKeyPress( event ) {
>   var canvasKeyPressEventArgs = {
>       originalEvent: event.originalEvent,
>       preventDefaultAction: event.preventDefaultAction,
>       preventVerticalPan: event.preventVerticalPan,
>       preventHorizontalPan: event.preventHorizontalPan
>   };
> 
>   this.raiseEvent( 'canvas-key-down', canvasKeyPressEventArgs);
> 
>     if ( !canvasKeyPressEventArgs.preventDefaultAction && !event.ctrl && !event.alt && !event.meta ) {
>         switch( event.keyCode ){
>             case 43://=|+
>             case 61://=|+
>                 this.viewport.zoomBy(1.1);
>                 this.viewport.applyConstraints();
>                 return false;
>             case 45://-|_
>                 this.viewport.zoomBy(0.9);
>                 this.viewport.applyConstraints();
>                 return false;
>             case 48://0|)
>                 this.viewport.goHome();
>                 this.viewport.applyConstraints();
>                 return false;
>             case 119://w
>             case 87://W
>             if (!canvasKeyPressEventArgs.preventVerticalPan) {
>                 if ( event.shift ) {
>                     this.viewport.zoomBy(1.1);
>                 } else {
>                     this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(0, -40)));
>                 }
>                 this.viewport.applyConstraints();
>               }
>                 return false;
>             case 115://s
>             case 83://S
>             if (!canvasKeyPressEventArgs.preventVerticalPan) {
>                 if ( event.shift ) {
>                     this.viewport.zoomBy(0.9);
>                 } else {
>                     this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(0, 40)));
>                 }
>                 this.viewport.applyConstraints();
>               }
>                 return false;
>             case 97://a
>             if (!canvasKeyPressEventArgs.preventHorizontalPan) {
>                 this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(-40, 0)));
>                 this.viewport.applyConstraints();
>               }
>                 return false;
>             case 100://d
>             if (!canvasKeyPressEventArgs.preventHorizontalPan) {
>                 this.viewport.panBy(this.viewport.deltaPointsFromPixels(new $.Point(40, 0)));
>                 this.viewport.applyConstraints();
>               }
>                 return false;
>             default:
>                 //console.log( 'navigator keycode %s', event.keyCode );
>                 return true;
>         }
>     } else {
>         return true;
>     }
> }
> ```
> 
> So in the app is possible to handle keyboard events like this, e.g.:
> 
> ```js
> viewer.addHandler('canvas-key-down', function (e) {
>    e.preventDefault = true; // disable default keyboard controls
>    e.preventVerticalPan = true; // disable vertical panning with arrows and W or S keys
>    e.preventHorizontalPan = true; // disable horizontal panning with arrows and A or D keys
> });
> ```

@francescocretti @iangilman  is there a reason for adding check for `!event.ctrl`?

I have a request from my PO to handle ctrl + arrows to pan the image when zoom level is applied. But after checking this code, I saw this condition. Please let me know.

**Comment by iangilman** [comment]
@raresgaia For the default handlers, we don't want to trigger if any of the modifier keys are held down, especially the control key and the meta key, since those keys are often browser commands. For instance, while the "w" key pans you up, control + W (on PC) and meta + W (on Mac) close the tab. 

If you want to support control + arrow, you should watch for key events from OSD and detect the control + arrow combo and then do the panning yourself.
