### ISSUE TITLE
updating the coordinates when the polygon is moved?

### ISSUE THREAD

**Issue by volkanciloglu** [openseadragon/openseadragon#1406]
I move the polygon to the canvas then move it. Then I need to send the coordinates of the polygon with a button. But the coordinates of the polygon that I replaced are not changing

**Comment by iangilman** [comment]
Can you give some more context? OpenSeadragon doesn't have polygons... Are you using a plugin? Which one? What's the scenario?

**Comment by volkanciloglu** [comment]
Sorry 
I wrote the question incorrectly
