### ISSUE TITLE
Issue getting mouseup and mousedown to work on canvas

### ISSUE THREAD

**Issue by RockGuitarist1** [openseadragon/openseadragon#1407]
So on my Openseadragon viewer I need to develop a drawable rectangle and based on the selection, zoom into that general area. This is the behavior I am expecting: [jsfiddle](http://jsfiddle.net/2yL7k8L8/)

I get the jsfiddle working just fine, but when trying to draw that over a new canvas that overlays the image canvas that Openseadragon uses for the image, my mouseup and mousedown events are blocked. My guess is that it is a css issue. However, pointerdown and mousemove works, but pointerup doesn't, so I am at a loss right now and am out of ideas. Here is the code that I am using. Would someone be able to give me a hand to get my code to be able to draw a rectangle like that in the jsfiddle? 

The reason I think it is css related, is because whenever I use Chrome's element picker, the mouseup event gets triggered, but otherwise it will not fire.

NOTE: this code is being toggled via button.

```
    let imageViewerCanvas = this.userData.viewer.drawer.canvas;
    let parentNode = imageViewerCanvas.parentNode;
    let rect: any = {};
    let ctx = null;

    this.dragToZoomActive = !this.dragToZoomActive;

    if (this.dragToZoomActive) {
      let drag = false;
      let canvas = null;

      imageViewerCanvas.setAttribute('style', 'background: none transparent; border: none; margin: 0px; padding: 0px; ' +
        'width: 100%; height: 100%;');

      let newNode = document.createElement('canvas');
      newNode.id = 'rectangle';
      newNode.setAttribute('style', 'background: none transparent; border: none; margin: 0px; width: 100%; height: 100%; ' +
        'padding: 0px; position: absolute;');
      newNode.onmouseup = (() => {
        drag = false;
        ctx.clearRect(0, 0, canvas.width, canvas.height);
      });
      newNode.onmousedown = ((e) => {
        rect.startX = e.pageX - this.offsetLeft;
        rect.startY = e.pageY - this.offsetTop;
        drag = true;
      });
      newNode.onmousemove = ((e) => {
        if (drag) {
          rect.w = (e.pageX - this.offsetLeft) - rect.startX;
          rect.h = (e.pageY - this.offsetTop) - rect.startY;
          ctx.clearRect(0, 0, canvas.width, canvas.height);
          draw();
        }
      });

      parentNode.insertBefore(newNode, imageViewerCanvas);

      canvas = document.getElementById('rectangle');
      ctx = canvas.getContext('2d');

      this.userData.viewer.panHorizontal = false;
      this.userData.viewer.panVertical = false;
      this.userData.viewer.zoomPerClick = 1;
    } else {
      this.userData.viewer.panHorizontal = true;
      this.userData.viewer.panVertical = true;
      this.userData.viewer.zoomPerClick = 2;

      let oldCanvas = document.getElementById('rectangle');
      parentNode.removeChild(oldCanvas);
    }

    function draw() {
      ctx.strokeStyle = 'red';
      ctx.strokeRect(rect.startX, rect.startY, rect.w, rect.h);
    }
```

**Comment by iangilman** [comment]
Yes, due to the complexities of supporting all of the various pointer types OSD supports, it eats some of the events that come through. Your best bet is to either use the viewer's mouse events or create a `MouseTracker` and use its events.

You might also take a look at the https://github.com/picturae/openseadragonselection plugin... It does something similar to what you're trying to accomplish, so you might be able to use it, or at least learn from its code.

**Comment by RockGuitarist1** [comment]
Ya I stared at that Selection plugin for a good week and decided that is not what we want. Way too complex for just a rectangle. I'll look into the viewer events, though I didn't see anything pertaining to mousedown and/or mouseup.

**Comment by RockGuitarist1** [comment]
I got this to work. I ended up using these:

* canvas-press = mousedown
* canvas-drag = mousemove
* canvas-drag-end = mouseup

**Comment by iangilman** [comment]
@RockGuitarist1 Excellent :)
