### ISSUE TITLE
Issue using zoomTo to rectangle midpoint

### ISSUE THREAD

**Issue by RockGuitarist1** [openseadragon/openseadragon#1410]
I am drawing a rectangle onto the viewer via a duplicated, transparent canvas, so that both the drawable surface and viewer are the exact same size and, in theory, share the same coordinates. I am getting the midpoint of a drawn rectangle and want to zoom into it, but when I do so, it zooms me miles away from the image instead of the center of the rectangle. Any ideas on what could be going on? This is the code I am using:

```
let x = (rect.startX + e.position.x) / 2; // x=315
let y = (rect.startY + e.position.y) / 2; // y=152.5
let point = new OpenSeadragon.Point(x, y);
this.viewer.viewport.zoomTo(1, point, true);
```

**Comment by RockGuitarist1** [comment]
I figured it out! I did some digging and stumbled upon this [page](https://openseadragon.github.io/examples/viewport-coordinates/).

I had to convert my web coordinates to viewport coordinates and it worked fine!

**Comment by iangilman** [comment]
Glad you got it sorted out!
