### ISSUE TITLE
Large gaps between tile requests noticed in case of fast tile loads

### ISSUE THREAD

**Issue by sandyrao** [openseadragon/openseadragon#1411]
I am facing a performance problem related to time taken for completion of tile loads in viewport. 

I tried to replicate it with the OSD website to demonstrate. If you check the attached profile and network timings, the tile images do not load as concurrent requests. Instead there are large gaps before the next request is initiated.

_To replicate:
Take the website in a high bandwidth network. (or from local machine) (The load times for the tiles were very small.)
Use the zoom control to zoom into the image.
Expected: tiles should load in parallel or in bunches of 6.
Actual: Large gaps are seen in between tile requests._

Also, I have attached the Chrome browser profile (zip file) demonstrating this. Can you kindly analyze the profile and help me understand what is happening here and what could be done to reduce the large load time gaps (Which is in seconds).

![capture](https://user-images.githubusercontent.com/2179715/36905827-5d9396ac-1e5a-11e8-9a28-a8d7cf5388af.PNG)

![capture2](https://user-images.githubusercontent.com/2179715/36906212-5d1d0996-1e5b-11e8-8ee6-8f9ee8625455.PNG)

[openseadragon-webpage-profile.zip](https://github.com/openseadragon/openseadragon/files/1775725/openseadragon-webpage-profile.zip)

Thanks in advance.

**Comment by iangilman** [comment]
Very strange! It certainly shouldn't be doing that. 

Can you help me repro? Looks like you go to http://openseadragon.github.io/ in Chrome (Mac? Windows? Linux?) and then zoom in right away as deep as you can go? Does it happen the same on other browsers? 

I've tried it on my Mac Chrome, and it seems to be working fine:

![image](https://user-images.githubusercontent.com/338989/36914131-1afce270-1e01-11e8-9938-04cfd7b37f06.png)

I took a look at your `.har` file in Charles, but I don't know what to do with the browser profile file.

**Comment by sandyrao** [comment]
Thanks Ian,
I was on a Windows 7 machine where I got this behavior. I opened the page and used the zoom control on top to zoom in as deep as possible. 

I will check and get back with the behavior on other browsers.

The browser profile file can be loaded to Chromes Performance tab in Dev tool. 
![untitled](https://user-images.githubusercontent.com/2179715/36930695-bca78546-1ecc-11e8-88ec-48a7fec7b275.png)

**Comment by sandyrao** [comment]
Hi Ian,

I checked the deep zoom scenario as well as the webpage load on Firefox (newly downloaded).

Deepzoom: (using zoom control button)
![firefox_deepzoom_scenario](https://user-images.githubusercontent.com/2179715/36961875-3d5dc31a-2073-11e8-811c-e23f3343fd1c.PNG)

Loading of osd website on firefox: (No mouse scroll)
![firefox_osd-website](https://user-images.githubusercontent.com/2179715/36961876-3d8f9868-2073-11e8-9a14-75ffa4f9510d.PNG)

Alse, these scenarios I am testing over Remote desktop, though I don't see an issue due to that.

**Comment by iangilman** [comment]
Your Firefox timelines look pretty reasonable... I suspect the browser is limiting you to a certain number of streams, so that's why they come in chunks. 

Thanks for the info on how to load the performance file in Chrome... I've taken a look, but don't have any additional insights.

If you wanted to look into this further, I'd recommend digging into the code and adding some console logging to start figuring out what the sequence is. Btw, in OSD, use `$.console.log` because otherwise the linter will complain. `loadTile` in tiledimage.js is probably a good place to start:

https://github.com/openseadragon/openseadragon/blob/master/src/tiledimage.js#L1449

**Comment by sandyrao** [comment]
From the firefox results, during deep zoom, though the load times are ~95 ms for each tile the overall time taken seems too high at 1.37 minutes.

From the simple page load scenario on firefox, it took close to 50 seconds for the tiles to load and there are gaps of 5 to 10 seconds where nothing happens.

The system was running on i7 with 8 cores, 16 GB RAM and on a high speed network.

I feel that OSD can run faster. From my investigation I see that RequestAnimationFrame was actually slowing down the image loads. When I inspect the image loads closer on the profile, I saw the Image requests tied to the loadTile which in turn is called at the AnimationFrame callback scheduled at updateOnce.

In my case, these frames last long (5 to 10 seconds) without actually having any thing to do (no javascript execution, no browser paints) and hence delaying the next image request which fires only on the end of the  Animation frame.

I made the $.requestAnimationFrame wrapper function fall back to the settimeout implementation by modifying the code and saw much better load times.

**Comment by iangilman** [comment]
Wow, that would do it! Any idea why requestAnimationFrame would be so slow on that browser? Is it something about our wrapper, or does raw requestAnimationFrame have that same problem? Do you have that problem with other pages that use requestAnimationFrame? I get a steady 60fps in Mac Chrome, FWIW.

**Comment by sandyrao** [comment]
Hi Ian,

I see that this is because of the Remote desktop connection I was talking about earlier. It looks like the frame rate drops during remote desktop to accommodate the network slowness.(I am connecting RDP over the web, from a relatively slower connection here, though the physical machine is situated on a high speed network.)

The frame rates dropped for these two urls as well, which brought me to the above conclusion.
https://www.testufo.com/animation-time-graph#scale=10&ppf=2&measure=animation&busywait=0
https://www.vsynctester.com/

So, the problem is not in the code. I am planning to revert the changes I made here. :)
Thanks a lot for your help and guidance on this issue.

**Comment by iangilman** [comment]
Good to know! Thank you for updating with what you found.

**Comment by unfitearth** [comment]
Hi Sandeep, I was wondering how did you exactly fix this error. I have same problem where i get large gaps in HARs in both manual run and through selenium when running on RDP, my server is decent config of i7, 32 gb of RAM and running at about 50 mbps. Please do help me out.

**Comment by sandyrao** [comment]
> Hi Sandeep, I was wondering how did you exactly fix this error. I have same problem where i get large gaps in HARs in both manual run and through selenium when running on RDP, my server is decent config of i7, 32 gb of RAM and running at about 50 mbps. Please do help me out.

@unfitearth 
The way I resolved it, was that I convinced the stakeholders that we should not use  Remote Desktop for Testing and Verfication since that isnt how the end user would use the system. As mentioned, my understanding is that Remote Desktop gives you very poor browser Frame Rates due to the fact that the screen is always trying to sync with a remote monitor over the network which is very slow.

However, If you feel, you want it to work well over Remote Desktop nonetheless, then you will need to fall back to use settimeout. Not a good idea for non-remote desktop scenario.

**Comment by unfitearth** [comment]
Thanks for replying Sandeep. Our company runs selenium scripts for synthetic monitoring on RDP and our clients have raise a concern over the gaps HARs the scripts are capturing. We do not have access to the way the website behaves and only rely on the HARs the script captures. Most we can do is somehow optimize our server. Was wondering if optimizing the server or getting better hardware could help.

**Comment by sandyrao** [comment]
I don't think Selenium would access a webpage over RDP since webdriver would be directly communicating with a local browser. From your reply, it looks like the scripts are running on a VM and it is accessing the application on a local browser.

Check the spec of the VM that is running the browser, and compare it against the spec on a machine where it is running fast. 
1. I think allocating more RAM or CPUs can improve your results unless it is due to network latency. 

2. Compare the bandwidth available as well. See if it is due to poor connection.

3. To check whether the slowness is due to slow server response read the below guide:
[https://developers.google.com/web/tools/chrome-devtools/network/issues](https://developers.google.com/web/tools/chrome-devtools/network/issues
)
