### ISSUE TITLE
Touch events blocked on IOS browsers?

### ISSUE THREAD

**Issue by fariskas** [openseadragon/openseadragon#1413]
I have the OSD test duomo example running with some modifications.

But i have an issue while on IOS 10 and 11, both Chrome and Safari, iPhone 7 and IPad. 

Touch events such as touchstart and touchend and 'click' do not fire when im interacting with OSD.
Sometimes the touchend does fire but only when i use 2 fingers and release it perfectly at the same time. Also when i overlay a html div overlapping the OSD canvas, the touchevents fire.

On chrome mac and chrome android, it works just fine. 

I also tried and currently using a touch library [zingtouch] and the same issue persists.

I googled and it seems like it might be related to the following issue? But for me, it doesnt work right from the start
https://github.com/openseadragon/openseadragon/issues/877

Here's the test sites im working on. 

[plain js touchend] Lookout for alert for "touch detected" firing 
http://fariskassim.com/stage/rebel9/bosch/v5/control/test_clean/

[with zingtouch library] Check console for "pan" / "swipe / "tap" firing 
http://fariskassim.com/stage/rebel9/bosch/v5/control/test_zing

**Comment by iangilman** [comment]
Due to the complexities of supporting all of the various pointer types OSD supports, it eats some of the events that come through. Your best bet is to either use the viewer's pointer events or create a MouseTracker and use its events.

**Comment by msalsbery** [comment]
@fariskas This is an old issue, but I'd still like to make sure things are ok as of OpenSeadragon v2.4.2.

I believe all iOS browsers are using the PointerEvent model at this point...

**Comment by msalsbery** [comment]
Fixed for v2.5.0 (#1872)

Feel free to reopen if issue persists!
