### ISSUE TITLE
Custom Image Encoding with Custom Tile Server

### ISSUE THREAD

**Issue by DJDaveMark** [openseadragon/openseadragon#1417]
We're currently using OSD with a custom tile server. It works great when we're returning "grayscale" PNGs encoded in RGBA (e.g. the same value for R & G & B) but we actually need to send back the raw values which can be anywhere up to a uint16.

We've tried encoding the raw value into the RGBA values by bit shifting then trying to decode the values via the OSDFilter plugin but the image is corrupted because of canvas interpolation.

It looks like the only way to get the raw values is to access the response of the ajax request directly (via the "tile-loaded" `event.tileRequest.response`), manually decode it via png.js, keep it in a custom cache, then using the OSDFilter plugin (modified to tell us which tile is being rendered) take the raw values out the cache and write what we need to the canvas.

Are we missing something simpler?

**Comment by iangilman** [comment]
Yes, that seems like what you would need to do at this point. I'd love to hear your thoughts on how we could make this sort of scenario smoother, though!

**Comment by DJDaveMark** [comment]
Thanks for the response @iangilman (and also thanks to @avandecreme for the filtering plugin)
The whole thing's working great now. Below is a few code snippets for anyone interested.
I had to:
* modify the [YAPD](https://github.com/kyriosli/YAPD/) library so it ran synchronized instead of using a Webworker.
* modify the [OpenSeadragonFiltering](https://github.com/usnistgov/OpenSeadragonFiltering/) so that the tile being filtered was passed to the processor function

```
var pngCache = {};
var viewer = new OpenSeadragon.Viewer({
    loadTilesWithAjax: true
});

viewer.addHandler("tile-loaded", tileLoaded);
viewer.addHandler("tile-unloaded", tileUnloaded);
initFilters();

function initFilters(event) {
    viewer.setFilterOptions({ // OSDFiltering (with custom mod)
        loadMode: 'sync',
        filters: {
            processors: filter
        }
    });
};

function tileLoaded(event) {
    var buffer = event.tileRequest.response;
    var tile = event.tile;
    var png = PNG.decode(buffer); // YAPD (with custom synch mod)
    pngCache[tile.url] = png;
};

prototype.tileUnloaded = function (event) {
    pngCache[event.tile.url] = null;
};

filter = function (context, callback, tile /*extra custom arg*/) {
    if(tile==null) {
        callback();
        return;
    }
    var png = pngCache[tile.url];
    if (png == null) {
        callback();
        return;
    }

    var origPixels = png.data;

    var imgData = context.getImageData(0, 0, context.canvas.width, context.canvas.height);
    var pixels = imgData.data;

    // manipulate pixels based on original (bit shifted) pixel values

    context.putImageData(imgData, 0, 0);
    callback();
}

function filterConfigChangedByUser() {
    initFilters();
}
```

**Comment by iangilman** [comment]
Wonderful! Thank you for sharing the code.

Any thoughts about how OSD could make this sort of thing smoother (either as part of the core system or a plugin), or are you happy with how it came together?

**Comment by DJDaveMark** [comment]
I think it would be the OSDFiltering plugin's job to expose some override-able hooks and pass a filterContext to the processor callbacks (basically what I did).
I'm unable to propose anything concrete since I just hacked away till I saw the light, and I've now moved on to the next task. Too much work to be done elsewhere I'm afraid (which depends on this).
But we're more than happy with the result!

**Comment by iangilman** [comment]
That sounds amazing! I'm glad it's working well :) You don't happen to have any examples running publicly we could share?

Thank you for the feedback on what it took to make it work. @avandecreme, some feedback on filtering plugin above :)
