### ISSUE TITLE
Add click events to overlays added in runtime

### ISSUE THREAD

**Issue by fariskas** [openseadragon/openseadragon#1419]
I have a bunch of overlays added in runtime. Eg:

```
    for (var i = 0; i < data.length; i++) {
      var elt = document.createElement("div");
      elt.id = "overlay"+i;
      elt.className = "highlight";
      viewer.addOverlay({
          element: elt,
          location: new OpenSeadragon.Rect(data[i].pos_x, data[i].pos_y, 0.2, 0.2)
      });
    }

```

I am trying to add a click event whenever the user taps (on IOS mobile) on the overlays.
Initially I did a normal jquery click function, which works in desktop, but doesnt work in IOS mobile because OSD eats some of the events that come through.
So instead i'm trying to use OSD's overlay functions.

I followed the example here where a addOnceHandler / MouseTracker is added for 1 overlay. 
https://openseadragon.github.io/examples/ui-overlays/

This method works for overlays added in the OSD initialisation options. But how do i the same if i with MULTIPLE overlays added in runtime, as demonstrated in the code above?

Also, for the overlays, is it possible to use the 'class' selector, instead of the 'id'? I would like to apply some common click events for overlays that share the same classes.

**Comment by iangilman** [comment]
You can pass the element directly into the MouseTracker instead of using an id or class. For example:

```
for (var i = 0; i < data.length; i++) {
     var elt = document.createElement("div");
     elt.id = "overlay"+i;
     elt.className = "highlight";
     viewer.addOverlay({
         element: elt,
         location: new OpenSeadragon.Rect(data[i].pos_x, data[i].pos_y, 0.2, 0.2)
     });
     
     var tracker = new OpenSeadragon.MouseTracker({
        element: elt,
        clickHandler: function(event) {
            // ...
        }
     });
}
```

...though you might not want to be creating a function inside a for loop like that. Possibly better to use `forEach`:

```
data.forEach(function(datum, i) {
    // create the overlay and mouse tracker
});
```

**Comment by fariskas** [comment]
Thank you for the helpful suggestions. I'll try them out!

**Comment by nikreations** [comment]
I am trying to add multiple overlays grabbing information from an xml file. I have successfully added the overlays using the above method, but I am unable to add onclick function to each of the overlays. I get an htmlcollection from the xml, so I think I cannot use ForEach. I added the mousetracker inside the for loop. The onclick event is added but only the last id is shown when clicked on any of the overlays. Here is my code. Any pointers appreciated.			
			
			function getHSlist(xml) {
				var i;
				var xmlDoc = xml.responseXML;
				var x = xmlDoc.getElementsByTagName("hotspot");
				
				for (i = 0; i <x.length; i++) { 

					var overlayid = x[i].getElementsByTagName("id")[0].childNodes[0].nodeValue;
					var overlayx = Number(x[i].getElementsByTagName("x")[0].childNodes[0].nodeValue);
					var overlayy = Number(x[i].getElementsByTagName("y")[0].childNodes[0].nodeValue);
					var overlaytitle = x[i].getElementsByTagName("title")[0].childNodes[0].nodeValue;
					var overlaysrc = x[i].getElementsByTagName("src")[0].childNodes[0].nodeValue;
					
					var elt = document.createElement("img");
					elt.id = overlayid;
					elt.className = "hotspot";
					elt.src = 'images/info-icon.png';
					elt.title = overlaytitle;
					elt.alt = overlaytitle;
					
					viewer.addOverlay({
						element: elt,
						location: new OpenSeadragon.Point(overlayx, overlayy),
						placement:	OpenSeadragon.Placement.CENTER,
						checkResize: false
					});
				
					var tracker = new OpenSeadragon.MouseTracker({
						
						element: overlayid,
						clickHandler: function(event) {
							alert (overlayid);
						}
					 });
				}
			}
