### ISSUE TITLE
Amazon S3 or Azure Hosting Workflow

### ISSUE THREAD

**Issue by maxrottersman** [openseadragon/openseadragon#1420]
Been a while, any one have a new, or cleaner workflow for uploading images to AWS or Azure, server-size processing them into tiles and then funneling into OpenSeaDragon? When I left off last year my workflow was a pain.  My wishlist is 1) upload image via FTP, 2) have server create tiled DZI 3) have server create thumbnail (would be bonus) 4) have server be able to serve web pages.  I understand others have done this, as I have, with limitations.

**Comment by boskar** [comment]
The real question is - what's Your input format?

**Comment by maxrottersman** [comment]
Either a high-res JPG or a compressed DZI file.  It's the uploading of all the tiles that is too time consuming.

**Comment by iangilman** [comment]
I don't have any specific suggestions, except to say that many of the options at: 

http://openseadragon.github.io/examples/creating-zooming-images/

...can work on the server side. You still have to hook them up, of course.

As far as I'm aware, no one has open sourced their server-side solution for the whole workflow (uploading, converting, organizing, accessing). 

Regarding S3, another option could be doing the conversion locally and having a script that does the upload... That way you can just set it up and let it run unattended. Depends upon how many you're trying to do per week I suppose.

**Comment by jcupitt** [comment]
One improvement I've seen is to put the DZI into an uncompressed zip, and then use a little extra JS in the viewer to read tiles directly out of the zip without having to unzip it on the server.

These large zips are quicker to upload (perhaps everyone zips before upload anyway?), more convenient to manage and take up less space, but the big win is on Windows servers. Windows goes much, much faster if you avoid the huge directory trees which DZI uses -- more than 4x faster.

vips dzsave can directly write an uncompressed zip containing the whole DZI, so you don't even need to zip the thing up.

**Comment by maxrottersman** [comment]
Hi John, that would be interesting?  Is there any open-source out there?  

I should have clarified in my original post that the technical work necessary for me to build these cameras, and do stitching are almost more than I can handle by themselves.  It's why I don't want to fight a war on so many fronts ;)  I want to create a zipped DZI, upload, and be done!  Sorry to be such a baby ;)

**Comment by jcupitt** [comment]
You can make a zip directly from vips -- just use a .zip suffix:

```
$ vips dzsave huge_image.tif mypyr.zip
```

Now `mypyr.zip` will be an uncompressed zip you can upload to a server and unzip where you please. 

In openseadragon, you add a custom tile fetch hander (is that the right terminology?) and use an http range request to pull the tile you need directly from the zip. The end of the zip file has an index, so on first request you fetch that and build a mapping from tile name to index and size.

I don't actually know of an open source js implementation of that last bit, but it's not very complicated. I know three or four commercial versions.

**Comment by maxrottersman** [comment]
Yes, I have the vips thing already down.  But the rest, figuring out the js from scratch, is not worth my time at the moment.  Do you know a specific commercial version that you'd recommend?  Thanks anyway!

**Comment by jcupitt** [comment]
The commercial ones are part of image delivery platforms, there isn't really a separate thing you could buy that implements that function (if that's what you mean).

**Comment by maxrottersman** [comment]
Yes, thanks!

**Comment by jcupitt** [comment]
EasyZoom and SZI do this: https://easyzoom.com/popular

I've been looking but I can't find the issue where this was discussed before, sorry. A few people chimed in on that and talked about how they'd done it, and the range trick was the most common one.

**Comment by maxrottersman** [comment]
Yes, I'd use easyzoom but it doesn't have features that OSD has, like re-center image.  Here's one of my test images on it: https://www.easyzoom.com/image/108502

**Comment by iangilman** [comment]
https://github.com/openseadragon/openseadragon/issues/944 has some discussion around creating a single file tile set, as well as a link to a prototype version. I don't know the state of that project at this point.

**Comment by jcupitt** [comment]
Oh, interesting, I'll add a note.
