### ISSUE TITLE
What might be the cause of `attempting to draw tile 11/4_6 when it's not cached`?

### ISSUE THREAD

**Issue by jeffpeck-readcoor** [openseadragon/openseadragon#1421]
I am getting thousands of these warnings when I load a page. What are some common causes that I can look for?

Thanks!

**Comment by iangilman** [comment]
I'm not sure exactly. I think the caching mechanism is pretty solid... Are you doing anything that might reset the cache or unload tiles? 

The line that's giving the error is probably here:

https://github.com/openseadragon/openseadragon/blob/master/src/tile.js#L308

It's looking for either `context2D` or `cacheImageRecord`. The former is generally for special processing, but it's also used by the simple image tile source. The latter is the more common caching mechanism (I believe).

What sort of tile source are you using? Can you share a link or a repro?

**Comment by jeffpeck-readcoor** [comment]
Thanks. I am going to debug and see what I can find. If I can make small sample that reproduces the issue I will post it here.

I will note that I am using multiple layers with and that I am using the filtering plugin.

For each layer, I am calling `.addTiledImage()` with an index. And I am setting the `replace` property to `viewer.world.getItemAt(index) ? true : false` (since it is possible to change the images after the page is loaded).

I am not 100% sure that is the best way to do it, but I don't think that would have an affect here, since `replace` should be `false`, at least for the first page load. I can confirm that...

**Comment by jeffpeck-readcoor** [comment]
Ok, it is only happening when I call `viewer.setFilterOptions()`

So, perhaps it is a bug with the plugin:
https://github.com/usnistgov/OpenSeadragonFiltering

I will investigate more at some point, but I will check there.

Thanks.

**Comment by iangilman** [comment]
Good to know... @avandecreme FYI ^

**Comment by jeffpeck-readcoor** [comment]
debugging.... I noticed that `drawCanvas` is called repeatedly even when there is no user action taking place. I'm not sure if it is related, but is that the expected behavior?

**Comment by jeffpeck-readcoor** [comment]
oh... and this is interesting: It does not happen when I add 3 layers. But it does when I add a fourth...

checking this `maxImageCacheCount` property...

**Comment by jeffpeck-readcoor** [comment]
Aha! yes, setting `maxImageCacheCount` to something significantly higher than the default `200` did the trick.

So... in summary, when using the openseadragon filtering plugin, if you try to load multiple tilesources and are getting thousands of the following warning message shortly after it looks like everything finished loading:
```
attempting to draw tile ... when it's not cached`
```

then, try to increase the `maxImageCacheCount` option:
```
const viewer = OpenSeadragon({
      ...
      maxImageCacheCount: 800,
      ...
    });
```

I hope this is helpful for anybody who finds this.

**Comment by iangilman** [comment]
I see! That definitely makes sense. Thank you for figuring it out and sharing the result.
