### ISSUE TITLE
Zoom behavior in center instead of mouse pointer

### ISSUE THREAD

**Issue by jetic83** [openseadragon/openseadragon#1422]
From some of our users I got the feedback that they prefer the zoom behavior to zoom into the middle of the image regardless where the mouse currently is. They focus with their eyes in the middle of the image and and the want to zoom in or out without prior movin the mouse into the middle of the image.
Currently, OSD does not support that, but I worked on a fix PR, which makes it optional to change the zoom behavior.

**Comment by jetic83** [comment]
The zoom behaviour can not be changed with the gestureSettings: E.g.

    gestureSettingsMouse: {
         zoomToRefPoint: false, // zooms into middle (default is true: zooms into pointer position)
    },

**Comment by iangilman** [comment]
Fixed by #1423.
