### ISSUE TITLE
how to hide toolbar？

### ISSUE THREAD

**Issue by CodeBennn** [openseadragon/openseadragon#1424]
I want to hide toolbar,but I can not do that by setting : OpenSeadragon({...,toolbar:false,...})  what should I do?

**Comment by CodeBennn** [comment]
a easy way to hide it:(typescript)
const toolbar : any= document.getElementsByClassName("openseadragon-container")[0].childNodes[1];
toolbar.style.display = "none";

**Comment by iangilman** [comment]
Out of curiosity, in what documentation did you find `toolbar: false`? Anyway, it's `showNavigationControl: false`.

**Comment by CodeBennn** [comment]
thank you!

**Comment by robertlight** [comment]
I believe:  
`viewer.setControlsEnabled(false)`
should let you do it programatically.
