### ISSUE TITLE
Be able to add new buttons to the viewer's ButtonGroup

### ISSUE THREAD

**Issue by petk** [openseadragon/openseadragon#1430]
Hello, great work with the OpenSeaDragon.

I have a question/possible issue. When adding a custom button like this: https://codepen.io/peterkokot/pen/WzdwbV

the custom button doesn't fade out to rest mode anymore once it has been covered.

Rest state of all buttons at the beginning (OK so far):
![rest](https://user-images.githubusercontent.com/1614009/37995198-dca67640-3213-11e8-9da3-ae02d611654a.png)

Hovering the zoom out button doesn't change the custom button state:
![zoomouthover](https://user-images.githubusercontent.com/1614009/37995210-e8fd0da0-3213-11e8-9280-3c9033715bec.png)

And once the custom button is hovered:
![customhover](https://user-images.githubusercontent.com/1614009/37995426-af75d70a-3214-11e8-8edd-2a717aeeb031.png)

After some delay the left buttons group fades to the rest state, but not the custom right button (which is left in the grouphover state):
![bug](https://user-images.githubusercontent.com/1614009/37995303-42506a00-3214-11e8-92f1-4195f9ac276c.png)

Is there anything I'm missing here? Thank you.

**Comment by iangilman** [comment]
In order to match the behavior of the other buttons, the new button needs to be part of their ButtonGroup. Instead of adding it like this:

```
viewer.addControl(customButton.element, { anchor: OpenSeadragon.ControlAnchor.TOP_LEFT });
```

...you can add it like this:

```
viewer.buttons.buttons.push(customButton);
viewer.buttons.element.appendChild(customButton.element);
```

The `viewer.buttons` is the viewer's ButtonGroup.

Of course it would be good if we had a cleaner API for adding buttons to button groups... I suppose it could be as simple as a function like this added to the ButtonGroup prototype:

```
addButton: function(button) {
  this.buttons.push(button);
  this.element.appendChild(button.element);
}
```

If you're up for it, you could make a pull request to that effect.

Anyway, I hope this helps!

**Comment by petk** [comment]
Wow, nice. This works great.

**Comment by MohitBansal321** [comment]
> In order to match the behavior of the other buttons, the new button needs to be part of their ButtonGroup. Instead of adding it like this:
> 
> ```
> viewer.addControl(customButton.element, { anchor: OpenSeadragon.ControlAnchor.TOP_LEFT });
> ```
> 
> ...you can add it like this:
> 
> ```
> viewer.buttons.buttons.push(customButton);
> viewer.buttons.element.appendChild(customButton.element);
> ```
> 
> The `viewer.buttons` is the viewer's ButtonGroup.
> 
> Of course it would be good if we had a cleaner API for adding buttons to button groups... I suppose it could be as simple as a function like this added to the ButtonGroup prototype:
> 
> ```
> addButton: function(button) {
>   this.buttons.push(button);
>   this.element.appendChild(button.element);
> }
> ```
> 
> If you're up for it, you could make a pull request to that effect.
> 
> Anyway, I hope this helps!

viewers.buttons are deprecated instead of it use viewers.buttonGroup @iangilman

**Comment by MohitBansal321** [comment]
### Let me Know any changes need 
**viewer.js**  (after line 980) 
```
 /**
     * Add custom button  for this viewer.
     *
     * @functions
     * @param {Element} CustomButton A reference to an element.
     */
    addButton: function( Custombutton ){
        this.buttonGroup.buttons.push(Custombutton);
        this.buttonGroup.element.appendChild(Custombutton.element);
    },
```

**script ( testing )**
```
<script type="text/javascript">
    var viewer = OpenSeadragon({
        id: "openseadragon1",
        prefixUrl: "../openseadragon/build/openseadragon/images/",
        tileSources: {
          type: 'image',
          url:  '../tile_source/check.jpg',
          buildPyramid: false
      }
    });
    let customButton = new OpenSeadragon.Button({
    tooltip: 'Custom Button',
    srcRest: 'https://raw.githubusercontent.com/openseadragon/openseadragon/master/images/button_rest.png',
    srcGroup: 'https://raw.githubusercontent.com/openseadragon/openseadragon/master/images/button_grouphover.png',
    srcHover: 'https://raw.githubusercontent.com/openseadragon/openseadragon/master/images/button_hover.png',
    srcDown: 'https://raw.githubusercontent.com/openseadragon/openseadragon/master/images/button_pressed.png'
});
viewer.addButton(customButton);
```
![Screenshot 2023-02-20 120915](https://user-images.githubusercontent.com/78220157/220031724-93bb55f3-3f76-47ff-ae38-8d1e8b1e5143.png)

**Comment by iangilman** [comment]
@MohitBansal321 Are you proposing this as a new pull request? You might as well do it in pull request form :) 

My proposal above was to add this new function to the ButtonGroup class, rather than the Viewer class. I still think that's the way to go, though I suppose we could also add a convenience function in the Viewer that just calls `this.buttonGroup.addButton`.

**Comment by MohitBansal321** [comment]
> @MohitBansal321 Are you proposing this as a new pull request? You might as well do it in pull request form :) 
> 
> My proposal above was to add this new function to the ButtonGroup class, rather than the Viewer class. I still think that's the way to go, though I suppose we could also add a convenience function in the Viewer that just calls `this.buttonGroup.addButton`.

It is convenient for people and it's working fine so I can create a pull request for it
