### ISSUE TITLE
Unable to load an Image

### ISSUE THREAD

**Issue by Louis345** [openseadragon/openseadragon#1434]
I am trying to use the library, but I am having trouble just loading a basic image nothing fancy. I just want to simply pass in an image and have it render. I created a codepen for an example. https://codepen.io/louis345/pen/OvQJVP. If anyone can refactor my example, that would be great.

This could be the source of my problem:
  var viewer = OpenSeadragon({
        id: "seadragon-viewer",
        prefixUrl: "https://i.imgur.com/j4Ycd7h.jpg",
        tileSources: "https://i.imgur.com/j4Ycd7h.jpg"
    });

Any Help will be appreciated.

**Comment by petk** [comment]
See this fixes: https://codepen.io/peterkokot/pen/mxXVrR

**Comment by Louis345** [comment]
Thank you
