### ISSUE TITLE
How to calculate distance between two point along with zoom factor / level on canvas image 

### ISSUE THREAD

**Issue by vinaymuthanna0727** [openseadragon/openseadragon#1435]
Hello , I am using OpenSeaDragon to view Deep Zoom images, and we also want to draw line (on click with two different points(x1,y1) ,(x2,y2)) and need to calculate  distance between two points or line on the canvas image .
Distance value will varies along with zoom level and could not get the accurate distance (because of the zoom factor / level on canvas image). How to calculate the distance along with zoom factor/level in the OpenSeaDragon canvas image

**Comment by iangilman** [comment]
You need to convert the mouse click coordinates (which are in the web coordinate system) into viewport coordinates (which stay the same regardless of zoom/pan). For more info on the different coordinate systems, see:

http://openseadragon.github.io/examples/viewport-coordinates/

Anyway, here's the basic operation:

```
viewer.addHandler('canvas-click', function(event) {
  var viewportPoint = viewer.viewport.pointFromPixel(event.position);
});
```

**Comment by vinaymuthanna0727** [comment]
Resolved thank you so much
