### ISSUE TITLE
How to Set zoomPerScroll for openseadragon canvas image ?

### ISSUE THREAD

**Issue by vinaymuthanna0727** [openseadragon/openseadragon#1436]
Hello ,I need to set the zoomPerScroll for canvas deepzoom image .  

viewer = new OpenSeadragon.Viewer({
      id: "seadragon",
      zoomPerClick: 1.5,
      zoomPerScroll: 1.1  
    });

is not working

**Comment by iangilman** [comment]
What effect are you trying to achieve? 1.1 isn't very different from the default of 1.2... Try something like 2 if you want it a lot faster or 1.01 if you want it a lot slower.
