### ISSUE TITLE
Defer image load - I have a method that works - but I lack further JS knowledge

### ISSUE THREAD

**Issue by Etienne79** [openseadragon/openseadragon#1438]
Hi,
There is a simple Javascript trick to defer image load, see below.
I wonder how to apply this to Openseadragon?

The trick: initially, you load a _"base 64"_ image instead of the real jpg image, and a 5-line long Javascript code swaps it after "on load" event is fired. It takes two minutes to set up for a normal HTML image, and speed rank gain is incredible, I tested on image heavy sites!

**This is how you modify the image src in HTML:**
`<img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="www.example.com/real-photo.jpg">`

**And all you need is this Javascript code:**

`	//image defer for mobile
		function init() {
		var imgDefer = document.getElementsByTagName('img');
		for (var i=0; i<imgDefer.length; i++) {
		if(imgDefer[i].getAttribute('data-src')) {
		imgDefer[i].setAttribute('src',imgDefer[i].getAttribute('data-src'));
		} } }
		window.onload = init;
`

The method is explained **on the bottom** of this article: https://varvy.com/pagespeed/defer-images.html

**QUESTION:**
How to implement this for Openseadragon? This method would help all of us using Openseadragon on pages that are already image heavy! As a photographer, I am not so advanced with Javascript modification, is there anyone who knows how to add this "base64" and "data-src" into the file? Would you be willing to help out the community to make Openseadragon even faster?

Thank you!

**Comment by iangilman** [comment]
The technique described in that article is more or less what OpenSeadragon already does; the initial page load includes no images, and then once the rest of the page is loaded, OSD loads just the image tiles you need. We can't add deferred image load, since it's already there. Thank you for the suggestion, though!
