### ISSUE TITLE
lock touch rotation to 90 degrees?

### ISSUE THREAD

**Issue by jrochkind** [openseadragon/openseadragon#1440]
In our viewer, we really only want 90 degree rotations (which is all you get without touch from the toolbar buttons). 

On mobile touch screen, users like that they can use gestures to rotate -- but often wind up at an annoying not-quite-90-degree angle, and have trouble manually getting it back to a 90 degree. I know I can turn off touch rotation; I also know I could provide my own toolbar buttons to restore the nearest 90 degree. 

But any advice for a way to have touch rotation, but lock to 90 degrees?  Hmm, I guess I could just hook into an event for a rotate happened, and then rotate it myself to the nearest 90 degrees. Hmm. Any thoughts welcome.

**Comment by iangilman** [comment]
Yes, I think that's probably best... from a UX standpoint, you want the user to be able to freely rotate while their fingers are still on the screen (to provide direct physical feedback), but you want it to snap to 90 degrees once they let up.

I think you might be able to accomplish this by watching the viewer for `canvas-release` events (to know when the user let up their finger) and check the rotation to see if it needs adjustment. By the way, I don't think we every got around to adding rotation animation, so you'll have to animate it yourself if you want it to snap smoothly.

**Comment by jrochkind** [comment]
Interesting, thanks. In my initial experiments, I wasn't succesful, so for now I'm just disabling pinch scrolling, which is probably acceptable for my app. 

I was trying to watch for `rotate` events, one catch is that `setRotation` generates em too -- and I'm not sure if pinch rotation actually does!  canvas-release might have worked better. I might try a bit more with that. 

The problem is that when people are pinch-zooming (which works AWESOMELY), they universally end up accidentally also rotating by a few annoying degrees that are hard to fix to straight 90 degrees by touch alone. 

Another colleague mentioned noticing that on google maps, you have to rotate more than X degrees before the gesture is interpreted as a rotation (at which point you can rotate back under the limit if you want), which is a nice UX, but definitely beyond me to try to get into OSD. :)

**Comment by jrochkind** [comment]
Aha! I was wondering about that. This was very hard for me to test in development, cause I can't find a way to emulate actual two finger pinch gestures on the desktop in a browser! 

I've abandoned this for now, and just turned off touch/pinch rotate in my app, we decided that was okay.

**Comment by iangilman** [comment]
Fair enough... Let me know if you get back into it.
