### ISSUE TITLE
Testing in React.

### ISSUE THREAD

**Issue by Louis345** [openseadragon/openseadragon#1443]
I have made a lot of progress getting this library to work with React do to all the help I have received from the community. I plan on posting a working version of this implemented with my React App with a test to help future newcomers.

My Error is  ```  1)  Uncaught error outside test suite:
     Uncaught ReferenceError: Image is not defined
      at getImageInfo (node_modules/openseadragon/src/imagetilesource.js:106:43)
      at $.TileSource (node_modules/openseadragon/src/tilesource.js:187:14)
      at new $.ImageTileSource (node_modules/openseadragon/src/imagetilesource.js:72:22)
      at Timeout._onTimeout (node_modules/openseadragon/src/viewer.js:2304:32)```

My simple test is

 ```const wrapper = mount(
  <Viewer showNavigator imageUrl={'https://i.imgur.com/b4z9aNS.jpg'} />
);

describe.only('The Viewer should have a ', () => {
  it('should a have a class', () => {
    expect(wrapper.find(`.${styles.container}`).length).to.equal(1);
  });
});
```

Any ideas on why Image is undefined?

**Comment by iangilman** [comment]
Looks like this is the line that's failing:

https://github.com/openseadragon/openseadragon/blob/master/src/imagetilesource.js#L106

That's just the standard `Image` class that's built in to the browser:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image

Are you running your test suite in a browser or a headless browser, or is it just running in Node? If the latter, I guess you need to mock Image or something.

I'm glad to hear the React project is going well! I look forward to seeing the result :)

**Comment by iangilman** [comment]
I guess you'll have to mock as much of the `Image` class as you need (in this case its `addEventListener` method). This is part of the challenge of testing client-side code with server-side tests. Maybe your test suite has some facility for dealing with this sort of thing? It certainly seems like it'll come up in other contexts besides OSD.

**Comment by mejackreed** [comment]
@Louis345 Have you tried using JSDOM here in your setup?

Something like:

```javascript
const jsdom = new JSDOM('<!doctype html><html><body><div id="main"></div></body></html>');
const { window } = jsdom;

global.window = window;
global.document = window.document;
global.Image = window.Image;
```
