### ISSUE TITLE
Filter methods

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#1445]
I'd like to add image 'filters' to a set of old documents.
The demo here is broken: https://github.com/usnistgov/OpenSeadragonFiltering
And a bit more complicated than I need.

I found this solution works, but not in iOS at all.
(feColorMatrix svg filters)

See the page here I'm working with. Any ideas on how to filter with iOS support?
http://deepzoomchattanooga.com/docfilter

**Comment by iangilman** [comment]
Have you tried the built in CSS filters?

https://developer.mozilla.org/en-US/docs/Web/CSS/filter

In other words, try using `filter: invert(100%)`. Unfortunately I don't see a sharpen in that list, though.

If you need sharpen on iOS you might need to use something like OpenSeadragonFiltering. You say the demo is broken... how so? It's working for me on Mac Firefox. This is the demo you're referring to, right?

https://pages.nist.gov/OpenSeadragonFiltering/

Though I don't see sharpen in its list either. @avandecreme Any suggestions?

Btw, another filtering plugin is this one:

https://github.com/thejohnhoffer/viaWebGL

...though that might be even more complicated.

**Comment by SamHall** [comment]
http://deepzoomchattanooga.com/docfilter2

That works! Thank you.

As for the demo issue. I found that an adblocker extension was blocking the .dzi.
I'm not sure why it did for that page, but not on others.

**Comment by iangilman** [comment]
Glad that worked! That's strange about the adblocker...
