### ISSUE TITLE
Too many tiles in simple image

### ISSUE THREAD

**Issue by prayerslayer** [openseadragon/openseadragon#1447]
When using OpenSeaDragon with a single image that has a specific resolution, it appears twice in the drawer.

Demo: https://jsfiddle.net/r6rmtmuj/2/

![image](https://user-images.githubusercontent.com/878512/38739594-a10d539a-3f35-11e8-9564-5fb3247013fb.png)

The reason for this behavior, as far as I can tell, is a rounding error in [`getTileAtPoint`](https://github.com/openseadragon/openseadragon/blob/master/src/tilesource.js#L364). The image has a resolution of 1280x1752 (aspect ratio `0.7305936073`). The calculation on the mentioned line is thus:

```
point.y >= 1 / this.aspectRatio - EPSILON
1.36875 > 1 / 0.730593607305936 - 1e-16
1.36875 > 1.3687500000000001
false
```

The easiest fix would be to increase `EPSILON`, but I don't know the implications.

**Comment by iangilman** [comment]
@avandecreme This one is back! What do you think about the proposed solution?

**Comment by avandecreme** [comment]
I agree, my fix never got merged :p

https://github.com/openseadragon/openseadragon/pull/1370

**Comment by iangilman** [comment]
@avandecreme whoops! Sorry about that!

**Comment by iangilman** [comment]
Fixed by #1370 .

**Comment by avandecreme** [comment]
No problem, forgot about the PR myself :)

**Comment by prayerslayer** [comment]
Many thanks for the quick response 🙏
