### ISSUE TITLE
Show loader and Loading the first tiles  (slow network 

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1449]
I have issue with slow network . Like 3-5 seconds to get tiles 
How can I show a loader on the image and remove it when first tile is ready.

Also I would like to print something on the canvas . But I would like to do that only when all tiles has finished 

Thanks a lot

**Comment by iangilman** [comment]
You'll want to use the `fully-loaded-change` event. See https://github.com/openseadragon/openseadragon/issues/1257 for examples. 

As for printing something on the canvas, there are lots of options. If you want it to move with the canvas, you can make an overlay. If you just want it to hover over the viewer, you can just make a regular HTML element. http://openseadragon.github.io/#plugins also has more advanced overlay options.
