### ISSUE TITLE
on Zoom Rubber line / Elastic line will get redrawn in different location : Using ImagePoint on Zoom redraw and webpoint on draw 

### ISSUE THREAD

**Issue by vinaymuthanna0727** [openseadragon/openseadragon#1452]
Hi All,

When i try to draw the Rubber line using overlay canvas the elastic line is drawn in different position .

On zoom line is redrawn in the different location

I am using 1)  webpoint to draw the line and  imagepoint on zoom to redraw the saved previous line 

textAnnotationData.push : used to save and redraw the previous elastic line on zoom in and zoom out

step 1: Getting the Start point X,Y in canvas press

 viewer.addHandler('canvas-press', function (event) {

        var webPoint1 = event.position;

        var viewportPoint1 = viewer.viewport.pointFromPixel(webPoint1);

        var imagePoint1 = viewer.viewport.viewportToImageCoordinates(viewportPoint1);

        startX = event.position.x;

        startY = event.position.y;
        isDown = true;

        textAnnotationData.push({ id: ++id, type: "line", data: "", startPoint: { webPoint: webPoint1, imagePoint: imagePoint1 }, endPoint: {} });
    });

Step 2 : Creating the elastic line using drag  

    viewer.addHandler('canvas-drag', function (event) {
       
        if (!isDown) {
            return;
        }
      context2d.clearRect(0, 0, canvas.width, canvas.height);

        drawLine(event.position.x, event.position.y, context2d);
    });

step 3: Getting the end point and save in the textAnnotation object and redraw it  
```
    viewer.addHandler('canvas-release', function (event) {

       var webPoint2 = event.position;

        var viewportPoint2 = viewer.viewport.pointFromPixel(webPoint2);

        var imagePoint2 = viewer.viewport.viewportToImageCoordinates(viewportPoint2);

        if (!isDown) {
            return;
        }
        isDown = false;

       /// overlay.onRedraw(false);

        var lastData = textAnnotationData[id - 1];

        if (lastData.type == "line" && jQuery.isEmptyObject(lastData.endPoint)) {

            textAnnotationData[id - 1].data = "1";

            textAnnotationData[id - 1].endPoint = { webPoint: webPoint2, imagePoint: imagePoint2 };
        }         
        drawLine(event.position.x, event.position.y, context2d);
       
    });
```

  function drawLine(toX, toY, contextOver) {

        overlay.onRedraw(false);

        contextOver.beginPath();

        contextOver.moveTo(startX, startY);

        contextOver.lineTo(toX, toY);

        contextOver.stroke();
  
        //if (viewer.viewport.getZoom() > deafultZoom) {
        //    overlay.onRedraw(false);
        //}
        //else {
        //    overlay.onRedraw(true);
        //}
       
    }

**Comment by iangilman** [comment]
I assume you're using this plugin?

https://github.com/altert/OpenSeadragonCanvasOverlay

I believe it uses the image coordinate system, so you need to convert. Instead of:

```
startX = event.position.x;
```

...it should be:

```
startX = imagePoint1;
```

...and so on.

**Comment by vinaymuthanna0727** [comment]
Hello iangilman,
thanks for the reply 

I have tried with imagePoint1 but it is not working 
i have created code pin 

https://jsfiddle.net/vinay0727/ueyqmmhg/5/

Steps to Reproduce the issue 

1) Click on canvas image and drag on it to draw a line 

2) Zoom the canvas image 

3) Again drag on canvas image 
 issue 1: on Drag older line will get clear because we are using **overlay.clear();**  (Do not resale the mouse click ) 

Question : How to clear only the present / Current drawing line in the canvas ,so we can get Rubber-ed / Elastic line ?

   `  viewer.addHandler('canvas-drag', function (event) {
      
        if (!isDown) {
            return;
        }
        overlay.clear();      
      drawLine(event.position.x, event.position.y,overlaycontext);
    });`

  issue 2: Previous drawn line is not redrawn on the canvas .Once we zoom in on canvas it will get redrawn (with out zoom in, line should get redrawn on canvas after mouse release event )

  issue 3: Some times older / Previous line position get changes on redrawn i am using image point to redrawn 


Please Check the code pin and any suggestion will be helpful
Thanks

**Comment by iangilman** [comment]
I see you're calling `overlay.onRedraw()` in the `canvas-release` handler. That's the right idea, but it doesn't set up the transforms properly. Instead you need to call `overlay._updateCanvas()`. Technically this is not part of the API; I've filed https://github.com/altert/OpenSeadragonCanvasOverlay/issues/8 to propose that it be made public. Meanwhile you can still use it (just knowing that it might change in the future).

You should also call it from the `canvas-drag` handler, so the other lines stay visible while you drag.

**Comment by vinaymuthanna0727** [comment]
Thanks a ton ....work perfectly.

But facing new issue with  constrainDuringPan 
  
I need to enable  constrainDuringPan based on some condition . Even if constrainDuringPan is true based on condition .it was not reflecting with viewer 

  if(lineAnnotationenable == true){
           viewer.visibilityRatio = 500;
           viewer.constrainDuringPan = true;
         }
        else{    
         viewer.visibilityRatio = 0;
         viewer.constrainDuringPan = false;       
    }

Here is the code for the same 
https://jsfiddle.net/vinay0727/et7o404n/2/

Please Check the code pin and any suggestion will be great helpful
Thanks

**Comment by vinaymuthanna0727** [comment]
Got resolved with  
viewer.constrainDuringPan = true;
viewer.viewport.visibilityRatio = 50;

Thank you

**Comment by iangilman** [comment]
Good to hear :-)
