### ISSUE TITLE
handling doubleclick

### ISSUE THREAD

**Issue by VladoPortos** [openseadragon/openseadragon#1454]
Hello, 
I'm lost in javascript quite a lot. But I'm trying to achieve what I suppose is simple thing. 
I want to make handler that when past certain zoom level starts tracking mouse coordinates. I have that as follow:

```
viewer.addHandler('open', function() {
        var coordEl = document.getElementById('coordinates');
        var tracker = new OpenSeadragon.MouseTracker({
          element: viewer.container,
          moveHandler: function (event) {
            var webPoint = event.position;
            var viewportPoint = viewer.viewport.pointFromPixel(webPoint);
            var imagePoint = viewer.viewport.viewportToImageCoordinates(viewportPoint);
            var zoom_level = viewer.viewport.getZoom().toFixed(0);
            if (zoom_level > 10) {
              coordEl.innerHTML =  imagePoint.toString() + zoom_level.toString();
            }
          
          }
        });

        tracker.setTracking(true);
```
This works, but how to handle double clicks ? In the end what I really want is only on max level zoom to be able double click at javascript would call php with the mouse point coordinated ( ajax, so it would search in DB string base on that coordinates and show it on the page, or open directly url with the string ) unfortunately I'm stuck, I have very little knowledge of Java

**Comment by iangilman** [comment]
You can add a `dblClickHandler` to your MouseTracker, and in it check the zoom level with `viewer.viewport.getZoom()`, only sending the AJAX message if the zoom level is high enough.

**Comment by VladoPortos** [comment]
Already figured it out, using the openseadragon-viewerinputhook.js plug in.
