### ISSUE TITLE
Image is blurred after setting canvas imageSmoothingEnabled to false on deep zoom levels

### ISSUE THREAD

**Issue by AsmaAq** [openseadragon/openseadragon#1455]
We are using high zooming levels (up to 6000). and we disabled the imageSmoothingEnabled to "false" to get better image resolution at that point.

but we faced some blurry/fuzziness when its set to false. 

Is there anything we can do in openseadragon helps in reducing the blurry thing?

Thanks,
Asma

**Comment by iangilman** [comment]
So you're zooming in past the amount of available pixels you have? And you want those pixels to be sharp and blocky? And setting  imageSmoothingEnabled to false doesn't change that? Which canvas are you doing this on? Depending on how you're using OSD, the drawer also has a "sketch" canvas that may need to be set as well.

Also, are you getting the same result on all browsers? And have you tried using https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering instead of imageSmoothingEnabled?

**Comment by AsmaAq** [comment]
Here is another image maybe this one is better to see the difference : 

imageSmoothingEnabled = true
![imagesmoothingtrue](https://user-images.githubusercontent.com/14885860/39404518-45525dce-4b9d-11e8-84a8-8596030fc08b.png)

imageSmoothingEnabled = false
![falseimagesmoothing](https://user-images.githubusercontent.com/14885860/39404522-59e5215e-4b9d-11e8-8d39-4536f0f817a4.png)

So what we need here is to make the image look better when imageSmoothingEnabled is set to false (no blurry/fuzziness). 

Is it doable? 

For image-rendering yeah its not supported on chrome and FF as well. 

Thanks !

**Comment by AsmaAq** [comment]
Yeah maybe this should be done on server. me also couldn't find anything more to be done on client. 

Thanks alot for the help :)

**Comment by AsmaAq** [comment]
Here is a clear case: 

While you are moving between tiles; its like some are loaded correctly and others have some blurry like seen below:

![image](https://user-images.githubusercontent.com/14885860/39742491-58e1e52a-52a6-11e8-8b98-48cc309909e9.png)

Is there anything we can do with openseadragon in "animation" event? to reset this? .

(same tile will look good if you moved the image)
note that this is zooming on latest tiles we got from server .. so its all zooming by openseadragon 

Thanks alot

**Comment by iangilman** [comment]
Interesting... It seems that the tile isn't quite lined up with the screen at that moment. Can you make a codepen or something that I can play with?

**Comment by robertlight** [comment]
Can you tell me where in openseadragon where I would set imageSmoothingEnabled=false to get those nice pixelated zoomed images?   I hate how OSD blurs the image once it gets beyond 1:1 pixel-to-pixel scaling.

**Comment by iangilman** [comment]
The code above from @AsmaAq should work:

```
canvas = viewer.canvas.childNodes[0];
ctx = canvas.getContext('2d');
ctx.mozImageSmoothingEnabled = false;
ctx.webkitImageSmoothingEnabled = false;
ctx.msImageSmoothingEnabled = false;
ctx.imageSmoothingEnabled = false;
```

It might be as simple as: 

```
viewer.drawer.context.imageSmoothingEnabled = false;
```

**Comment by AsmaAq** [comment]
@iangilman I’ve set  smoothTileEdgesMinZoom to 1000 (which is my max zoom) so its like been set to off and seems it works much better now ! We didn’t see the blurry thing after that

If we faced it again I’ll share the code here

Thanks a lot

**Comment by AsmaAq** [comment]
@robert yeah as Ian mentioned that’s how we set it ,and the extra lines are added to support browsers other than chrome since they need a prefix (Firefox works with mozImageSmoothingEnabled) and so on

**Comment by iangilman** [comment]
@AsmaAq Oh yes, I forgot about `smoothTileEdgesMinZoom`... Good catch!

As for the browser prefixes, it looks like you don't need them anymore if you're just targeting modern browsers:

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled#Browser_compatibility

It's a good precaution for older browsers though.

**Comment by jetic83** [comment]
There is a pull request #1507 related to this, but it seems it is not even necessary to put this imageSmoothingEnabled into the code of OSD, since we can change the context externally?

**Comment by iangilman** [comment]
#1507 has now landed, so there's now an API for turning imageSmoothing off (not yet released, just on master).
