### ISSUE TITLE
Rendering a image in openseadragon at its original pixel resolution

### ISSUE THREAD

**Issue by DerrickLemley** [openseadragon/openseadragon#1457]
Hi,
We are trying to open a simple Jpeg image at its original resolution without having the image stretched to the viewport. We have tried all the default zoom settings and they do not seem to do what we are asking. We also tried setting viewer.viewport.zoomTo() but it only works if we set a timeout. If we do not set a timeout the zoomTo doesn't seem to do anything.

Are there any events that OpenSeadragon emits that will fire after an image is already loaded so that the zoom can then be set after the image is loaded?

Also are there any settings that can be specified to load the image at its Original Resolution?

Thanks!

**Comment by iangilman** [comment]
Yes, opening the image is asynchronous, so you need to wait for the `open` event. You can use `imageToViewportZoom` to find out the appropriate zoom for the original resolution. Like so:

```
viewer.addHandler('open', function() {
  var zoom = viewer.viewport.imageToViewportZoom(1);
  viewer.viewport.zoomTo(zoom, null, true);
});
```

**Comment by DerrickLemley** [comment]
Excellent! That worked perfectly!

Thanks so much Ian, I really appreciate it! 👍
