### ISSUE TITLE
viewer.addSimpleImage base64 instead of URL

### ISSUE THREAD

**Issue by MarkusAnthony** [openseadragon/openseadragon#1458]
I would like to add an image from a base64 string that is stored in an object instead of a URL.  Is this possible?
                viewer.addSimpleImage({
                    'url': ...,
                    'x': 0,
                    'y': 0
                });
-Markus

**Comment by iangilman** [comment]
So your image is base64 encoded, but it's not a URL? You'll need to turn it into a URL before adding it to OpenSeadragon. That may be as simple as adding `data:image/png;base64,` to the beginning (depending on what format it's in).

**Comment by MarkusAnthony** [comment]
Ok, issue was I had to add "width: 100".

-Markus

**Comment by iangilman** [comment]
Glad you got it working!
