### ISSUE TITLE
how to draw a grid on openseadragon viewer

### ISSUE THREAD

**Issue by KrupaRajashekar** [openseadragon/openseadragon#1460]
Hi,

I am trying to draw a grid on openseadragon viewer, but I am not sure how to do this. Can someone please help?

Thanks !

**Comment by iangilman** [comment]
I assume you want the grid to zoom and pan as you go? There are lots of options... You could have a grid image with transparency that you load into the viewer on top of your other image. Or you could use one of the overlay plugins such as https://github.com/altert/OpenSeadragonCanvasOverlay (for drawing with canvas) or https://github.com/openseadragon/svg-overlay (for svg), and draw the grid yourself.

**Comment by RaunakGangi** [comment]
hey ian i have to tried to use the canvas overlay option but it doesnt seem to work at all
it seems that it has been depriciated. can u help me in using the svg overlay plugin
thanks

**Comment by iangilman** [comment]
Yes, I believe this canvas overlay is a better choice these days: 

https://github.com/joshua-gould/OpenSeadragonCanvasOverlayHd

You could also try the SVG overlay but I think for drawing a grid, the canvas is going to have better performance (though that's just a guess).
