### ISSUE TITLE
Preloading tiles

### ISSUE THREAD

**Issue by fariskas** [openseadragon/openseadragon#1461]
I have a **question** regarding how i can preload all tiles before zooming to the different levels on the viewer.

i saw a 'preload' option in the documentation here:
http://openseadragon.github.io/docs/OpenSeadragon.html

and here's how i tried using it. 

> viewer = OpenSeadragon({
  id: 'osd',
  visibilityRatio: 0.6,
  constrainDuringPan: false,
  defaultZoomLevel: 1.062,
  minZoomLevel: 1.062,
  maxZoomLevel: 7,
  tileSources: tileSourceFromData(dziData, dziFilesUrl),
  **preload:true**
});

Not sure if this is the correct way of using it because i dont think i see any performance improvements . Is this wrong?

**Comment by iangilman** [comment]
The `preload` setting is only for controlling whether hidden images continue to load their tiles (so you can load them while they're hidden). 

Do you want your image to be hidden entirely before all the tiles have loaded? Or do you just want to wait before zooming?

Either way, what you need is to keep an eye on the "fully loaded" property of the images. There are some suggestions on how to do that here: https://github.com/openseadragon/openseadragon/issues/1257

**Comment by iangilman** [comment]
Yeah, with an image that big you definitely want it tiled, and loading the entire thing before you let people navigate probably isn't a good idea.
