### ISSUE TITLE
How can I fix difference in zoom of displayed Image at zoom=20 and actual image scanned at 20X.

### ISSUE THREAD

**Issue by sandyrao** [openseadragon/openseadragon#1462]
Hi Ian,
I have a pathology image scanned at 20X magnification and deep zoom tiles were created from it. The Viewer has multiple such images arranged 5 in a row and any number of columns. The max zoom level set to OSD is 40. While trying to view the image at zoom 20, there is a difference between the zooms of the actual image tile and the OSD viewer at max zoom level . 
Also, I see that, as  we change the screen size, the actual zoom displayed, for the same zoom value on OSD, is changing. Do you have any setting for controlling this behavior, so that, accurate  zoom can be retained irrespective of the browser dimensions?

**Comment by iangilman** [comment]
The zoom value you get from `viewer.viewport.getZoom()` is the viewport zoom. which is a ratio of the viewer width. If the image is shown the exact width of the viewer, it's 1. If the image is shown twice the width of the viewer, it's 2.

It sounds like you want the image zoom, where 1 means you're zoomed in to the native resolution of the image, 0.5 means you're zoomed out to half size, etc. This value is unrelated to the size of the viewer. The viewport has a couple of methods for converting between image and viewport zoom: 

http://openseadragon.github.io/docs/OpenSeadragon.Viewport.html#imageToViewportZoom

http://openseadragon.github.io/docs/OpenSeadragon.Viewport.html#viewportToImageZoom
