### ISSUE TITLE
Redraw Navigator Example

### ISSUE THREAD

**Issue by stone12379** [openseadragon/openseadragon#1464]
I want update navigator's position while in fullscreen mode, but cannot find an example on how. Could anyone be kindly enough to help?

**Comment by iangilman** [comment]
Looks like we may not have an API for that. In what way do you want the position changed?

You can take a look at the navigator code:

https://github.com/openseadragon/openseadragon/blob/master/src/navigator.js

...keeping in mind that the navigator is a subclass of the Viewer (in other words, it's a small viewer that's nested inside the big viewer).

You might be able to move it by changing the style of `viewer.navigator.element`.

**Comment by stone12379** [comment]
Thnaks a lot!
