### ISSUE TITLE
Align a scroll to right from the beginning and autoplay

### ISSUE THREAD

**Issue by stone12379** [openseadragon/openseadragon#1467]
I am trying to display a long scroll using fitVertically. Although it works fine, I would like it to start from the right end from the beginning. Also, is there a way to automatically move the scroll from right to left? It could be useful to display art in scroll form.
Regards!

**Comment by stone12379** [comment]
One more question related. How to restore OSD to the status that it is first opened after this align operation?

**Comment by iangilman** [comment]
The best way to move the viewer around is using `fitBounds`. For instance:

```
var bounds = new OpenSeadragon.Rect(0.25, 0.25, 0.5, 0.5);
viewer.viewport.fitBounds(bounds, true);
```

You just need to do the math to create a rectangle that suits your needs.

As for going back to the starting state, that's `viewer.viewport.goHome()`.

**Comment by stone12379** [comment]
appreciated
