### ISSUE TITLE
Container / canvas not fitting in DIV

### ISSUE THREAD

**Issue by darkmich** [openseadragon/openseadragon#1469]
I'm working on this:
http://slides.cldavis.org/IAAAM/#

When a case is selected, the OSD container doesn't fit in the outside DIV. As near as I can tell, in landscape, this is because of the border and the margin. Things get really off when the window is in portrait mode - the container goes way off the page. 

What am I doing wrong? Is there a way to pass the size to OSD?

**Comment by iangilman** [comment]
Looks like there is some CSS weirdness in the containing structure. I can repro the issue on Mac Chrome but not Firefox. Adding `height: 100%` to both `#images` and `#view` extend those areas so they match the OSD viewer. I'm not sure exactly why.

**Comment by iangilman** [comment]
As for the portrait state, your `#content` is `height: 100%` but your `header` also has height, so the content gets pushed down because the total percentage is more than 100.
