### ISSUE TITLE
How to use getTileAtPoint function to get tile at certain point?

### ISSUE THREAD

**Issue by AsmaAq** [openseadragon/openseadragon#1471]
I need to get the tile by like 4*4 pixels (for example) at certain clicked point. 

Is getTileAtPoint function useful for this? I couldn't find a clear example for it or how should I call it.

![image](https://user-images.githubusercontent.com/14885860/40345330-7439c7f6-5da1-11e8-80c4-109d8176f544.png)

Can you please advice? 

Thanks,
Asma

**Comment by iangilman** [comment]
You want to know the actual tile at that location, based on where you're zoomed? If you zoomed in more it'll be a lower level tile, and if you're zoomed out it'll be a higher level tile. Also if you're waiting for the lower level tiles to load, maybe it'll be a higher level tile at the moment. Anyway, that's what you're looking for? I don't think we have any specific API for getting that info, but you can walk through the TiledImage's `lastDrawn` property which is an array of tiles. I can give you some pointers on that if you'd like.

I'm curious, what's the purpose of this?

**Comment by AsmaAq** [comment]
I need to know the actual tile in size of (3*3) pixels at certain point in the image. like when user clicks on a point we give him more deep zoomed tile for that point. 

so lets say user clicked on point (100,200) in terms of x,y , I need to know the tile around that point by (3*3) pixels.

Actually we need it to display zoomed detailed popup like in the screenshot which is useful for certain points in the image to get to know more about the colors like in other images editors. 

so lastDrawn will be useful for this? getTileAtPoint doesn't help ?

**Comment by AsmaAq** [comment]
![image](https://user-images.githubusercontent.com/14885860/40410944-adeb5d3a-5e77-11e8-8632-a4899478d909.png)

so first user clicks on a point like the above image. after that I need to display the tile around that point by 3*3 pixels for example like the rectangle in screenshot.

**Comment by iangilman** [comment]
Looks like you could use getTileAtPoint as well if you wanted to. The difference is `lastDrawn` contains the actual tiles which are currently drawn on the screen, whereas `getTileAtPoint` gives you the tile numbers (not the tile itself) for a particular location at a particular level regardless of whether it's drawn or not.

Here's some code that shows both techniques:

        var mouseTracker = new OpenSeadragon.MouseTracker({
            element: viewer.element,
            moveHandler: function(event) {
                var viewportPos = viewer.viewport.pointFromPixel(event.position);
                var tiledImage = viewer.world.getItemAt(0);
                if (tiledImage) {

                    // lastDrawn technique
                    tiledImage.lastDrawn.forEach(function(tile) {
                        if (tile.bounds.containsPoint(viewportPos)) {
                            console.log('lastDrawn', tile);
                        }
                    });

                    // getTileAtPoint technique
                    var viewportPosRect = new OpenSeadragon.Rect(viewportPos.x, viewportPos.y, 0, 0);
                    var tileSourcePosRect = tiledImage._viewportToTiledImageRectangle(viewportPosRect);
                    var tileSourcePos = tileSourcePosRect.getTopLeft();
                    var source = tiledImage.source;
                    if (tileSourcePos.x >= 0 && tileSourcePos.x <= 1 && tileSourcePos.y >= 0 &&
                        tileSourcePos.y <= 1 / source.aspectRatio) {

                        var level, tilePoint;
                        for (level = source.minLevel; level <= source.maxLevel; level++) {
                            tilePoint = source.getTileAtPoint(level, tileSourcePos);
                            console.log('getTileAtPoint', level, tilePoint.x, tilePoint.y);
                        }
                    }
                }
            }
        });

Note that you have to do some funny things with non-official functions for the `getTileAtPoint` technique. Anyway, play with them and see what works for you.

**Comment by AsmaAq** [comment]
Thanks alot for the help. I just got the chance to try it.

lastDrawn is exactly what I want :) 👍 

but I'm trying to draw the tile on a separate div/canvas ..so instead of 
console.log('lastDrawn', tile); 

I put this:

var htmlElement = Dom.get("tileImage");
 tile.drawHTML(htmlElement);

But I'm getting this error in the console : 
![image](https://user-images.githubusercontent.com/14885860/41091672-c87b8236-6a4f-11e8-8279-dd3cf98092b9.png)

Seems imgElement can't be set 
![image](https://user-images.githubusercontent.com/14885860/41091740-f2e621ac-6a4f-11e8-9485-9a95e3ca8555.png)

Is it the right way to draw the tile ?

**Comment by iangilman** [comment]
`drawHTML` isn't really being used anymore (except in rare circumstances). You'll want `drawCanvas` or maybe you'll want to look at how it does things and just use some of its code. Here it is: 

https://github.com/openseadragon/openseadragon/blob/master/src/tile.js#L312

**Comment by AsmaAq** [comment]
Great ! Thank you 

I'm using drawCanvas and its working :)

**Comment by AsmaAq** [comment]
Is there any relation between Scale value in drawCanvas function and current zoom on image? 

Because using same scale for different zoom levels is not working for me but I couldn't figure out how they are related.

**Comment by iangilman** [comment]
No, the scale is just for the edge smoothing that's done when you zoom in past 1:1 on a tile. I don't know that there's any way to find out the current zoom from a tile, but of course the viewport knows.

**Comment by AsmaAq** [comment]
Okay I see..

Can I zoom the viewport to a certain point ? so the point will be the center of the zoomed image? I've tried zoomTo and zoomBy with the point as refPoint but didn't work. 

I used it as in the documents : zoomTo(zoom, refPoint, immediately)

**Comment by AsmaAq** [comment]
Yeah its more reliable :) 👍 

Thanks alot for the help !

**Comment by AsmaAq** [comment]
Hi Ian, 

I've used panTo then applyConstraints to set the zoomed in to point, and its working perfect.

But there is a case when image is zoomed in to large zoom value like 500 and above (to 1000); image returned will be shifted approximately to 10 pixels in y and x, 

Do you have any idea why ? and how I can solve it?

here is a sample of my code
Note: (cursorX and cursorY are where the cursor is currently over the image from mousemove event)
//here i get the point from the original canvas
viewportPos = viewe1.viewport.pointFromPixel(new OpenSeadragon.Point(cursorX,cursorY));
//below i set the second canvas to the point i got
viewer2.viewport.panTo(viewportPos, true);
 viewer2.viewport.applyConstraints();

Thanks in advance, 
Asma

**Comment by iangilman** [comment]
Wow, that's a lot of zoom! I wonder if it's floating point rounding errors. One thing to try would be to set your coordinate system up with bigger numbers to start. For instance: 

```
viewer.open({
  tileSource: myTileSource, 
  width: 10000
});
```

If you don't specify width it defaults to 1.

**Comment by AsmaAq** [comment]
Unfortunately it didn't help, also I do use width with big number when i load the tiles. 

Do you think there is something else that can help? to get the point more accurate in case of large zoom?

Thanks

**Comment by iangilman** [comment]
Nothing comes to mind. Could you make a CodePen or something to share a repro that I could poke at?

I know it's a hack, but if it's consistently off by 10 pixels you could fudge it by that much.

**Comment by AsmaAq** [comment]
Hi Ian, 

Sorry for the late response but i was trying all possible scenarios to fix it. 

Here below the codepen for the idea i am working on:

https://codepen.io/AsmaAq/pen/KrYbWe

What I've noticed is its working good on the openseadragon library images like the one i used in the code. 
then I realized that it differs from image to another , so sometimes it works perfect and on the other images there is a shift in the center coordinates.

Any thoughts? 

Thanks

**Comment by AsmaAq** [comment]
I noticed that in 2.4.0 version its not working on portrait images like the one below:
![image](https://user-images.githubusercontent.com/14885860/50594008-752f4100-0ea3-11e9-9a93-2cf777ed2464.png)

But its working as expected on kind of wide images like the one below:
![image](https://user-images.githubusercontent.com/14885860/50594088-bd4e6380-0ea3-11e9-9bb7-a4fe64b0ac53.png)

What is the difference in this case?

**Comment by iangilman** [comment]
Happy new year! 

Thank you for putting that CodePen together. It wasn't loading the image at all, so I replaced your image definition with a couple I have lying around: 

```
var highsmith = {
    Image: {
        xmlns: "http://schemas.microsoft.com/deepzoom/2008",
        Url: "http://openseadragon.github.io/example-images/highsmith/highsmith_files/",
        Format: "jpg",
        Overlap: "2",
        TileSize: "256",
        Size: {
            Width:  "7026",
            Height: "9221"
        }
    }
};

var duomo = {
    Image: {
        xmlns: "http://schemas.microsoft.com/deepzoom/2008",
        Url: "http://openseadragon.github.io/example-images/duomo/duomo_files/",
        Format: "jpg",
        Overlap: "2",
        TileSize: "256",
        Size: {
            Width:  "13920",
            Height: "10200"
        }
    }
};
```

It seems to be working fine with both of them (assuming I understand the purpose); the little viewer in the upper left seems to be showing exactly what's under the cursor in the viewer on the right. When you swap these images in, do they work for you as well? If not, what should I be looking for?

At any rate, your code looks reasonable. 

Regarding the different aspect ratios, one thing to be aware of is that by default the viewport coordinates are based on the width of the image, with 0 being the left side and 1 being the right. That means that portrait images have a height that's greater than 1 and landscapes have a height that's less than 1. Depending on what you're trying to do you might have to account for that, though I'm not seeing anything in your code that makes me think you would need to.

**Comment by iangilman** [comment]
Well, one thing I noticed is that you can get out of sync if you leave the mouse in the same place and just use the scroll wheel to zoom. This is because your syncing code happens in the move handler and is therefore not triggered when the mouse is still, even if there's zooming. Could that account for what you're seeing?

**Comment by AsmaAq** [comment]
mmm I don't think so, can this be affected by the tile itself? maybe some are accurate more than others? 

Or that doesn't make sense lol. 

What do u think?

**Comment by iangilman** [comment]
Well, the only differences I can think of between different images are the aspect ratio and the total quantity of pixels. I suppose it might be good to narrow down whether either of those is the main culprit.

**Comment by AsmaAq** [comment]
I've used the image in openseadragon library ("http://openseadragon.github.io/example-images/duomo/duomo_files/")  in my code and it worked ! 

so its something with the images, can you explain more to me what is the aspect ratio ? and how it affects the calculations ?

what can we do in this case?

Thanks alot !

**Comment by iangilman** [comment]
The aspect ratio is just the relationship between the width and the height... perhaps there are differences in the calculation for tall images versus wide images.  

The other factor would be just how big the image is... if there are floating point rounding errors in the calculation, this would get worse with bigger images because you could zoom further into them.

Have you been able to narrow down which of your images is affected? Can you share one of them? If you can't share it publicly, you can share it with me directly on https://gitter.im/iangilman.

**Comment by abhidg** [comment]
@iangilman Is there any way to get the actual OpenSeadragon.Tile object corresponding to a value returned from getTileAtPoint? I could create a new Tile by directly referencing the tiff in the DeepZoom image corresponding to the level, just wondering if there's a better way.

**Comment by iangilman** [comment]
@abhidg every Tile knows its level, x, and y, so you can look through all the tiles and use the information from `getTileAtPoint` to compare and find the right one. One way to look through the tiles would be the `lastDrawn` array in a TiledImage. That would only show you the tiles that are currently visible in the viewport at the moment.
