### ISSUE TITLE
draw a line use openseadragon-fabric，but it's drag background image together

### ISSUE THREAD

**Issue by oyy123** [openseadragon/openseadragon#1472]

**Comment by iangilman** [comment]
It's hard for me to tell exactly what's going on without playing with it... could you make a CodePen with it?

At any rate, I think it might work well to use the `canvas-drag` event and tell it to prevent the default action. Something like so: 

```
viewer.addHandler('canvas-drag', function(event) {
  event.preventDefaultAction = true;
  
  // move line 
});
```

**Comment by oyy123** [comment]
sorry to forget to reply immediately,it's useful ,thanks for your help~~

**Comment by iangilman** [comment]
Great... thanks for letting me know!

**Comment by msalsbery** [comment]
@oyy123 

When version 3.0.0 is released, there's a bunch of new stuff to make these things easier!

Closing this for now...feel free to re-open if there's any more questions or issues!
