### ISSUE TITLE
Overlay over overlay selection 

### ISSUE THREAD

**Issue by AlexDarbyFujitsuGmail** [openseadragon/openseadragon#1476]
How to re-produce issue :

1.  Create a small overlay (using addOverlay())
2.  Add a MouseTracker() to the small overlay element.
3.  Create a large overlay over the first small overlay.
4.  Add a MouseTracker() to the large overlay element.
5.  Unable to select / delete (top right x) the first small overlay.

Is there a way to configure openSeaDragon to check for all overlays regardless of the creation / depth ordering?

**Comment by iangilman** [comment]
Can you make a Code Pen (or similar) to illustrate this issue?

**Comment by msalsbery** [comment]
@AlexDarbyFujitsuGmail 

Now that #1872 has landed, it should be much easier to get control of the pointer events

[Here's a CodePen](https://codepen.io/msalsbery/pen/dyOeXqO) that shows what can be done...
