### ISSUE TITLE
Accessing a TileSource instance and a question about docs

### ISSUE THREAD

**Issue by alanaberdeen** [openseadragon/openseadragon#1477]
Hi, 

First off, thanks a lot for all the work on openseadragon - really great stuff! 

I have a few questions that are very similar to #1326, I could easily be missing something but I've had a good search through the docs and nothing jumped out. 

1. If I have created my Viewer via `var viewer = OpenSeadragon(options)` how do I then access the associated [TileSource](http://openseadragon.github.io/docs/OpenSeadragon.TileSource.html) instance? In my case I'd particularly like to use the `tileSource.getTileAtPoint()` method.
2. I understand you can access the World instance owned by a Viewer via `viewer.world`, it took me a while to discover this was possible. Is there a reason it's left out from the list of members on the [documentation for the viewer](http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html)?

**Comment by iangilman** [comment]
Assuming you just have a single image, you can access its tileSource like so:

```
var tileSource = viewer.world.getItemAt(0).source;
```

Thank you for pointing out the missing documentation! No reason at all; just an oversight. Adding it should be easy; just a jsdoc comment here:

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L155

... like the one for `drawer` above and `viewport` below.

For that matter, it appears that `source` isn't documented in TiledImage. Adding that to the documentation would also be good, and it would be similar to the viewer addition, but over in tiledimage.js.

**Comment by alanaberdeen** [comment]
Ah great, that's exactly what I'm after. I'll have a look at adding those edits to the docs tomorrow, will submit a PR with the required changes. 

Thanks!

**Comment by iangilman** [comment]
Great, thank you!
