### ISSUE TITLE
Custom tile source repeatedly loads source files

### ISSUE THREAD

**Issue by xiayuan920** [openseadragon/openseadragon#1485]
When I used the custom tile source that official demo provided in GitHub, I found that each time a tile is acquired, a source file is requested and the source file is stored in the browser memory. If the source file is too large, it may easily cause insufficient memory to run. Is there any solution?
![1](https://user-images.githubusercontent.com/10568938/41697573-f87cd03c-754b-11e8-8ff1-fa7df60df228.png)

**Comment by iangilman** [comment]
Which custom tile source demo are you talking about? This one?

http://openseadragon.github.io/examples/tilesource-custom/

I don't get any of those things when I try it...

**Comment by xiayuan920** [comment]
I see this example
https://github.com/openseadragon/openseadragon/blob/master/test/demo/customheaders.html
But I already solved it

**Comment by iangilman** [comment]
Great! Out of curiosity, what was the issue?
