### ISSUE TITLE
Trying to display 2 images together - is collectionMode with collectionTileMargin=0 a way to go?

### ISSUE THREAD

**Issue by filak** [openseadragon/openseadragon#1487]
I have integrated OSD into Angular project https://github.com/filak/wck/blob/f83df8b11326786eed99ffe963d362550a5e7f1e/src/app/book/iiif-viewer/iiif-viewer.component.ts (I have no live site to show yet.)

Most things work fine, though I am struggling with the two page layout. I have set up the collectionTileMargin to 0 but I cannot see any effect - there is still a huge gap between the images.

The fiddles here https://github.com/openseadragon/openseadragon/issues/1011 do not work anymore unfortunately.

**Comment by iangilman** [comment]
Collection mode will only work to put your images directly next to each other if they both happen to be square or wider than they are tall (and ideally if they both have the same aspect ratio). It positions the images centered in a grid, so if the images are taller than they are wide, there will be space between them (though I don't know if a negative `collectionTileMargin` could be used). 

At any rate, my recommendation would be to ignore collection mode and just lay them out yourself, for example:

```
this.view.open([
  {
    tileSource: images[0],
    x: 0,
    width: 1
  },
  {
    tileSource: images[1],
    x: 1,
    width: 1
  }
]);
```

**Comment by filak** [comment]
Thank you! It works great.
