### ISSUE TITLE
openseadragon cannot open big legacy image pyramids image?

### ISSUE THREAD

**Issue by sommour** [openseadragon/openseadragon#1489]
I try to use this mode：
http://openseadragon.github.io/examples/tilesource-legacy/
my code is:
`<script type="text/javascript">
            var viewer = OpenSeadragon({      
                id: "contentDiv",      
                prefixUrl: "images/",        
                tileSources: {           
                    type: 'legacy-image-pyramid',            
                    levels:[{               
                    url: 'image2/4.jpg',               
                    height: 1280,               
                    width:  1280           
                    },{               
                    url: 'image2/3.jpg',               
                    height: 2560,                
                    width:  2560            
                    },{               
                    url: 'image2/2.jpg',               
                    height: 5120,                
                    width:  5120           
                    },{               
                    url: 'image2/1.jpg',               
                    height: 10240,               
                    width:  10240           
                    },{              
                    url: 'image2/0.jpg',               
                    height: 20480,                
                    width:  20480           
                    }]       
                },       
                showNavigator:true   
            });
        </script>`
when it run in the browser(IE or Chrome),  zoom into the big image(0.jpg (20480 X 20480)),  the browser will become blank.  when it turn to smaller image(1.jpg (10240 X 10240)), the browser will show normal.

why? because the browser memory Limit ?

thank you!

**Comment by iangilman** [comment]
Yes, it's quite possible your browser doesn't want to load that giant image. It's definitely big enough that it would be worth tiling it if you can. 

I'm curious... can you share a link to the image so I can take a look?

**Comment by sommour** [comment]
@iangilman OK, I put it : http://www.scinly.com/test/ , but it seems work normal. But  I tested it in my local compute, not online. can you download it (link: https://pan.baidu.com/s/1zujASxqOo93lqOXhvrXQ1w    password: xu7a ) and try it in your compute ? thank you. if you cannot download it, I can send it using email.
PS: by the way,  using the legacy image pyramids model, if i zoom in to the maximum layer, it must load the whole biggest image(like 0.jpg (20480 X 20480)) or just load the regional biggest image that shown in the interface ? I test it, I think it load the whole image, am I right? if so, this model(legacy image pyramids) is not useful(Compared to other models)

**Comment by iangilman** [comment]
So it does work for you on a server? Then maybe just don't worry about the fact that it doesn't work locally? 

But yes, the legacy tile source loads the entire tile for the appropriate level; it can't load just a region of that tile. Looks like your largest tile is dozens of megabytes in size, so that's definitely way too big for a reasonable user experience. I'm still downloading your largest tile, but the second largest (1.jpg) is 12mb and it took almost 2 minutes to load for me.

You should look into tiling it with one of the tools listed here: 

http://openseadragon.github.io/examples/creating-zooming-images/

**Comment by sommour** [comment]
@iangilman Thank you for answer. I am trying to using  zooming image format.

I think legacy image pyramids may be used by Tiff format, like openslide and legacy image pyramids is more simple and convenience. So I hope that I can know the reason of this question. Thanks again.

**Comment by iangilman** [comment]
The tiled formats (like DZI, for instance) have the advantage of breaking the large levels into small, bite-size pieces. That way you never need to load a single 40 MB image. Transferring 40 MB can take several minutes on some connections, so it's definitely worth the trouble!
