### ISSUE TITLE
Web to Image coordinate conversion giving negative values

### ISSUE THREAD

**Issue by KrupaRajashekar** [openseadragon/openseadragon#1490]
Hi,

I am drawing annotations on an image, by opening the image in openseadragon viewer in chrome. I am saving the co-ordinates in backend after converting these web co-ordinates to image coordinates, as follows:
pointer = overlay.fabricCanvas().getPointer(o.e);
osdPoints = new OpenSeadragon.Point(pointer.x, pointer.y);
imgPoints = viewer.viewport.viewerElementToImageCoordinates(osdPoints );

Is this the right way of converting coordinates? When I click on the left side of the image, x coordinates are negative after conversion. Can someone please tell me where I am going wrong?

**Comment by iangilman** [comment]
I assume you're using https://github.com/altert/OpenseadragonFabricjsOverlay ?

That plugin should already be using viewport coordinates, not web coordinates. If you want to convert those to image coordinates, use `viewportToImageCoordinates`.

**Comment by KrupaRajashekar** [comment]
Hi Ian,

I figured out the problem. I was giving a high value for scale of fabric, so i guess it was multiplying by that scale to calculate image co-ordinates?
Setting the scale to 1 (like below) fixed the issue.

this._overlay = this._viewer.fabricjsOverlay({ scale: 1 });

But now, I am not able to draw fabric objects on the overlay. When is scale has a higher value, i was able to draw rectangles & polylines properly. 
Any idea what is happening and how I can fix this?

Thanks,
Krupa

**Comment by iangilman** [comment]
Oh, I didn't know about the scale feature! How about if you do `scale: 100` and then divide the coordinates you get by 100? Seems like that should sort things out.

**Comment by KrupaRajashekar** [comment]
Hi Ian,

I was able to make this work. I left my tileSources alone (did not set width or anything there) and changed the scale to be same as image width. Now there is no need for me to do coordinate conversion and co-ordinates are almost correct. But there seems to be a slight shift from actual coordinates (maybe about 5px).

**Comment by iangilman** [comment]
Sounds like you're getting close! I'm not sure what would account for the slight shift, except maybe some floating point rounding somewhere. It might be interesting to experiment with setting the width of the tile source instead or some other way to scale differently.
