### ISSUE TITLE
Infinite Zoom

### ISSUE THREAD

**Issue by Salitehkat** [openseadragon/openseadragon#1493]
Hi to everyone, 
Im new in this forum, in javascript and to openseadragon. Excuse if my question has an obvious answer. Ive been doing searching and didn’t find an explanation. 
I would like to have an infinite zooming (zoom in). Or at least 100 levels. I wouldn’t mind that the image pixelates or is not clear. I just the need action of extreme zooming. Ive tried changing the maxzoomlevels values but zooming always stops, which I can guess that has to do with the size of the image im using. My questions are:
1-In what depends the zoom levels? Does It stops zooming when it reaches the maximum of the width (or size) of the image? 
2-Is there a possibility to zoom inifinite (like leaflets zoom) no matter what width (or size) is the image?

Thanks so much for any explanation. I am really lost.

**Comment by Salitehkat** [comment]
Finally I got some light.

maxZoomPixelRatio: Infinity

thanks for any further explanation.

**Comment by iangilman** [comment]
Yes, I think that's the correct solution. Do you have further questions about it?

**Comment by Salitehkat** [comment]
In the doc says "This can be set to Infinity to allow 'infinite' zooming into the image "though it is less effective visually if the HTML5 Canvas is not availble on the viewing device." .Please, what does it mean?
Thanks lots.

**Comment by iangilman** [comment]
In the early days, OpenSeadragon used image elements instead of canvas to do its drawing, but nowadays it's pretty much always using canvas (because browsers are more advanced now). So perhaps that message is a little out of date... anyway, you should expect it'll always be using the more effective technique.
