### ISSUE TITLE
SVG OSD from file Resize 

### ISSUE THREAD

**Issue by Salitehkat** [openseadragon/openseadragon#1495]
Good moring, 
Ive found this code [pen](https://codepen.io/iangilman/pen/wKVQjK) which attaches an external svg overlay on top of a tile image.  Its exactly what I need so many thanks to the author.  (due to restrictions of browsers you cannot try it directly, but here is the code:

` <script type="text/javascript">

   var svgUrl = "images/test.svg";

		var tileSource = {
			Image: {
				xmlns: "http://schemas.microsoft.com/deepzoom/2008",
				Url: "//openseadragon.github.io/example-images/highsmith/highsmith_files/",
				Format: "jpg",
				Overlap: "2",
				TileSize: "256",
				Size: {
					Height: "9221",
					Width:  "7026"
				}
			}
		};
		
		var viewer = OpenSeadragon({
			id: "contentDiv",
			prefixUrl: "//openseadragon.github.io/openseadragon/images/",
			tileSources: [{
				tileSource: tileSource,
				width: 500
			}]
		});
		
		var overlay = viewer.svgOverlay();
		
		var snap = Snap(overlay.node());
		
		Snap.load(svgUrl, function (f) {
			var g = f.select("g");
			snap.append(g);
		});
			
     
    
    </script>

It works perfectly but the svgOverlay does not resize with the viewport (or brower size) as the back tiled image does.  How can that be achieved? 
Many thanks. for any help-
`

**Comment by Salitehkat** [comment]
Now its working and resizing. Did not change anything. Guess somehitng was wrong in my browser.

**Comment by iangilman** [comment]
Interesting. Glad to hear it sorted itself out; let us know if it pops up again!
