### ISSUE TITLE
Can you set the number of pre-loaded tilesource when using the multi-image API

### ISSUE THREAD

**Issue by linker2424** [openseadragon/openseadragon#1496]
From reading this chain https://github.com/openseadragon/openseadragon/issues/1238
It seems like you can use OSD as a frame (“movie”) player. Though, I’m still confused if you can set how many frames (tilesources) get pre-loaded? 
Is there some setting I’m missing that allows you to set how many tilesources to preload at one time? 
If you can’t set this and you have to pre-load all the frames, I’m assuming that OSD isn’t meant to play 100+ frame collections (i.e., it would take too long to preload). 
Thanks so much for the help!

**Comment by iangilman** [comment]
The preload can be set on a per image basis using the image's preload flag. You can go through all of the `TiledImages` in the `World` and call their `setPreload` as needed. Keep in mind that preload simply means that the image will load even if the opacity is 0. 

If you're loading 100+ images, and you're providing the tile sources as URLs, keep in mind they will all load those data URLs immediately (just not the image tiles). More efficient would be to use the "inline configuration" described in http://openseadragon.github.io/examples/tilesource-dzi/ ... you can load all of the data you need in one call (however you want) and then give them straight to OpenSeadragon.

Another approach is to add your images to the viewer only as you're ready to preload them. This way it's not as important whether you use the inline configuration, and you don't have to fiddle with managing all the preload flags.

**Comment by linker2424** [comment]
Sorry for the delay in my response and thanks for the great information. 
I have a couple of follow-up questions:
When you suggested to try the, "inline configuration" dzi approach listed above, if I pass a 100 images in the diz file to the viewer, will that load all 100 images? If so, will that load all levels of each image?
In your last suggestion i.e.,
“Another approach is to add your images to the viewer only as you're ready to preload them. This way it's not as important whether you use the inline configuration, and you don't have to fiddle with managing all the preload flags.”
This means passing an individual tilesoruces to the viewer once I’m ready to preload the next image correct? 
Thanks so much for your help.
By the way, you’ve always been such a help to me, is there any way to support you?

**Comment by iangilman** [comment]
> When you suggested to try the, "inline configuration" dzi approach listed above, if I pass a 100 images in the diz file to the viewer, will that load all 100 images? If so, will that load all levels of each image?

If you use inline configuration and pass 100 images to the viewer it won't immediately load anything from the server. It will then start to load whatever tiles it needs to show whichever images are visible in the viewport. This means if you load all 100 images with opacity 0 and preload false, it won't load any tiles at all. If you then change the opacity or preload value for a single image, it'll start loading the tiles for that image. Does that make sense?

> This means passing an individual tilesoruces to the viewer once I’m ready to preload the next image correct?

Correct. You would use `viewer.addTiledImage` to add the next image. 

> By the way, you’ve always been such a help to me, is there any way to support you?

Thank you! I appreciate it. You can support me on my Patreon: 

https://www.patreon.com/iangilman

... Or let me know if there's something else that would work better for you (I'm still trying to figure out what's best). Either way, I'm glad to be helping :)
