### ISSUE TITLE
Overlayed images aren't  flipped when there's no rotation

### ISSUE THREAD

**Issue by nelsonn3c** [openseadragon/openseadragon#1498]
Issue detected by @jetic83 

> Have you tested it with overlayed images (multiple, semitransparent images in viewer.world)?
> It seems like that they are not flipped, when rotation = 0, but they are also flipped, when rotation != 0.

**Comment by nelsonn3c** [comment]
Hi @iangilman ,

I made some changes and it seems to be better now but incomplete.

When collectionMode and sequenceMode are set, everything is working nice but when sequenceMode is unset, it doesn't go well for slides drag and rotation.

Do have any clue about the solution for this?

**Comment by nelsonn3c** [comment]
Should I open a new issue relative to the individual tiled images flip need?

**Comment by nelsonn3c** [comment]
It was solved on branch #1549

**Comment by iangilman** [comment]
@nelsonn3c Yes, it would be good to document that. I don't know how many people would be interested in that feature, but with an issue filed, those people can speak up!
