### ISSUE TITLE
How could I disable the animation only when pointing to certain location?

### ISSUE THREAD

**Issue by zmxu** [openseadragon/openseadragon#1499]
Is there anyway to disable the animation only when panning to certain location? We want to decrease the loading operation times, and find that when panning to certain location on the most detailed level, it will raise lots of Ajax request if the image has very high resolution and small tile size. Is it possible to make it go to the desired position directly? 

Another question is how to decrease the memory usage of the browser?

Thanks.

**Comment by iangilman** [comment]
Is this panning by user drag, or is it something you're doing programmatically? If it's the latter, you can use the `immediately` flag to make it pop straight there. 

I'm not sure the best way to decrease memory usage. One option, perhaps, would be to limit the size of the tile cache. This might increase network load, as uncached tiles might need to be reloaded later. Anyway, you can control it with the `maxImageCacheCount` option (default is 200). 

You might also try using `useCanvas: false` ... the old HTML renderer is probably lighter on memory (though its quality isn't as good).

Are there specific scenarios where you're running into memory issues?

**Comment by zmxu** [comment]
Thanks for the prompt reply. In our case, we want to open multiple dzi files (less than 10) at the same time. In addition, we need the actions in these viewers connected with each other. It means that the user drag in one viewer should trigger the same actions in other viewers. It will consume lots of memory if the tiles are all cached. We have tried to the maxImageCacheCount option. But it seems no obvious different when setting to a smaller number.

Another need is to load a single file packaging all the tiles. As javascript prohibits loading binary files from local path, we need to bypass this restriction as follows: When frontend asks for a tile, it sends a request to the backend and then wait via polling mechanism.  After backend gets the request, it will prepare the tile by extracting the corresponding tile from the single package file and saving it in a temporary location. There will be lots of requests when user points to a certain position or drags quickly in the navigation region. The backend cannot process them in time because these are slow hard-disk operations. That is why we want to disable the animation or try other ways to decrease the number of requests.

Any suggestion to our scenarios? We have tried the immediately flag. It works, but there are still many tile requests when user drags in the navigation map. Our thought is to estimate the dragging speed, 爱and only to response the slow motion requests. We haven't figured out where to add this condition yet. BTW, we just tried the animationtime flag, it can somehow slow the request speed but cannot decrease the request number.

**Comment by zmxu** [comment]
One more question: where and how could I know if the tile is successfully loaded? I want to add an handler after tile finishing loading. Thanks.

**Comment by iangilman** [comment]
I see. Yeah, unfortunately I don't think multiple viewers really do anything to share resources between each other. You want them in different viewers, not all in the same viewer, right?  You can have multiple images in the same viewer but they would all have to zoom and pan together. 

Another thing to try is `imageLoaderLimit: 1`, which will make sure only a single tile per viewer is being loaded at any one time. Unfortunately I don't think it's set up to throttle across all open viewers. At any rate, this may have the effect of not loading as many tiles while the user is in motion. 

As for loading the tiles your own way, I believe you can transfer a binary file and interpret it on the client if you want (just in normal JavaScript) as long as you're on the same domain (or perhaps if you have CORS set up properly). OpenSeadragon isn't really set up for accepting tiles in that way, but I imagine modifications could be made, and it's certainly a scenario we'd like to be able to support. You might take a look at https://github.com/openseadragon/openseadragon/issues/944. 

As for knowing when a tile is loaded, do you mean for a single tile or do you mean all of the tiles needed for the current view of the image? For the former, see the [tile-loaded](http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#.event:tile-loaded) event. For the latter, see [getFullyLoaded](http://openseadragon.github.io/docs/OpenSeadragon.TiledImage.html#getFullyLoaded) and its friends. 

It seems you're pushing on the boundaries of what OpenSeadragon is set up to do, so it may involve making some modifications. If you're up for that, I can help point you in the right direction.

**Comment by zmxu** [comment]
Thanks for the suggestions. They are really helpful. Our scenario is really rare where we want to open some tiled Images in different viewers, only one in each viewer. We may have the need to open multiple DZIs once, therefore the binary file requests are not in the same domain. That is why we bypass that by asking backend to prepare the tiles when frontend asks. I will definitely look at CORS and see if it suits to our case.

"_tile-loaded_" event is exactly what we need. We also need to reload tiles when "_tile-load-failed_" event raised. Unfortunately, there is no such method, and we have to modify OSD by re-calling _loadTile()_ when tile loading is failed in _onTileLoad()_ until the tile is successfully loaded. Any better way to achieve that? BTW, I originally thought I didn't need to re-call _loadTile()_, I just needed to set _tile.exists = true_. But the results were not the same. Which part was I wrong?

We just encounter a new problem. The navigator turns to black when we delete the loaded tiles. (I know it is kind of strange but we have to.) The strange thing is that it happens when the tile size is of 1024x1024, but OK when 256x256. Do you know why? Which image does the navigator need exactly? Is it the tile image of a specific level?

Yeah, we would like to make some contribution to OSD. Let me know what and how we could do. Thanks.

**Comment by iangilman** [comment]
Hmm... interesting. `tile.exists = true` should be enough to get it to retry. What were the results when you tried that? On a related note, you might be interested in https://github.com/openseadragon/openseadragon/pull/1386 , which adds an automatic retry mechanism. The original author has moved on, but you might get some ideas, or you might be interested in finishing up the patch.

The navigator is just another viewer, so it uses whatever tile is appropriate for its size. Since the navigator is usually fairly small, it would be one of the smaller tiles. If you delete the tile it needs and it doesn't get reloaded, it makes sense that it would be black. I do believe the navigator fires `tile-load-failed` events, though you'll have to catch them with `addHandler` on the navigator rather than your viewer. 

As for contributing to OpenSeadragon, you have a number of issues you are interested in, it appears! Pick one out and I can help point you in the right direction for that one. It helps to focus on one at a time.

**Comment by zmxu** [comment]
`tile.exists = true` works now... If I remember correctly, the difference should be the number of `tile-loaded` event triggered. The code with `tile.exists = true` fires fewer events than by re-calling `loadTile()`. Anyway, it solves our problem.

How could I capture the `tile-load-failed` event fired by the navigator? Its seems no events supported by navigator class.

**Comment by iangilman** [comment]
The navigator descends from the viewer class, so it should fire (at least most of) the same event types the viewer fires. To watch for `tile-load-failed`, do:

```
viewer.navigator.addHandler('tile-load-failed', func);
```

As for the loader, that's interesting. Are both of those AJAX requests from the same viewer, and are they both for tiles, and they both fire at the same time? Once they complete, does it fire a second pair of requests? It's certainly possible that the limit is off by 1 or something. Or it's possible the second request you're seeing is for the DZI file itself or something. Can you share a snapshot of your network tab?
