### ISSUE TITLE
How can I get exact clicked point when Image is rotated?

### ISSUE THREAD

**Issue by AsmaAq** [openseadragon/openseadragon#1502]
I used viewportToImageCoordinates and pointFromPixel to get clicked cursor point relative to the image canvas. 

But when image is rotated (90,180,270) these values will be not reflected with the rotate so results will be wrong in this case. 
Also I think this applies to getting topLeft and bottomRight functions. 

How can I solve this and get point in terms of rotation value?

Here is the code I used so far: 
//for the point:
        newPoint = new OpenSeadragon.Point(clickPoint.x, clickPoint.y);
        canvasPoint = parent.previewImageController.viewport.viewportToImageCoordinates(newPoint);
        imagePoint =  parent.previewImageController.viewport.pointFromPixel(canvasPoint);
//for topLeft,bottomRight

imgBounds = new OpenSeadragon.Rect(0, 0, viewer.source.width, viewer.source.height);

topLeft = viewer.viewport.imageToViewerElementCoordinates(imgBounds.getTopLeft());
bottomRight = viewer.viewport.imageToViewerElementCoordinates(imgBounds.getBottomRight());

**Comment by AsmaAq** [comment]
Thanks @iangilman for the help.

two sequences gave me same results.I think these functions are taking the rotate into consideration But calculating the viewed area width and height is not correct depending on the topLeft and bottomRight.

So when getTopLeft , getBottomRight are called. do they change according to the rotate state? or they are relevant to the main image?

Thanks,
Asma

**Comment by iangilman** [comment]
Hmm... I'm getting a little lost. Maybe we should be working on a CodePen so we can play with the same code directly?

Anyway, let me go through your code and how I see it.

### For the point

Here's the first line. I'm assuming clickPoint is in web coordinates, so newPoint is also in web coordinates.

`newPoint = new OpenSeadragon.Point(clickPoint.x, clickPoint.y);`

Here we're converting newPoint (which is in web coordinates) using `viewportToImageCoordinates` which is supposed to take in viewport coordinates. Either I'm wrong and `newPoint` is actually in viewport coordinates, or you shouldn't be doing this.

`canvasPoint = parent.previewImageController.viewport.viewportToImageCoordinates(newPoint);`

Theoretically canvasPoint is in viewport coordinates (if newPoint was really in viewport coordinates), and here you're passing it into a function that's supposed to take web coordinates and convert them to viewport coordinates, which is backwards.

`imagePoint = parent.previewImageController.viewport.pointFromPixel(canvasPoint);`

You're telling me this sequence produces more accurate results, but it seems like you're passing all the wrong things in the wrong direction, so I don't know how it's working!

### For topLeft,bottomRight

Here you're creating an unrotated rectangle in image coordinates. So far so good. Note that there's no rotation in this rectangle, which is as it should be (the rotation gets applied further up the chain).

`imgBounds = new OpenSeadragon.Rect(0, 0, viewer.source.width, viewer.source.height);`

Here you're using the correct conversion to go from image coordinates to web coordinates. Looking at the code for these functions it does look like it should be taking the viewport and image rotations into account.

```
topLeft = viewer.viewport.imageToViewerElementCoordinates(imgBounds.getTopLeft());
bottomRight = viewer.viewport.imageToViewerElementCoordinates(imgBounds.getBottomRight());
```

If this isn't getting you the right results, there may indeed be a bug. One way to track it down is to break it into smaller chunks... Internally ` imageToViewerElementCoordinates` converts first from image coordinates to viewport coordinates and then from viewport to viewer element (i.e. web, with the viewer element as the origin) coordinates. Try doing those conversions yourself and printing the results to see where the breakdown is. For instance:

```
var topLeft = imgBounds.getTopLeft();
console.log('image', topLeft.toString());
topLeft = viewer.viewport.imageToViewportCoordinates(topLeft);
console.log('viewport', topLeft.toString());
topLeft = viewer.viewport.viewportToViewerElementCoordinates(topLeft);
console.log('web', topLeft.toString());
```

Anyway, perhaps a CodePen would help us get on the same page?

**Comment by AsmaAq** [comment]
Ops I'm sorry .. I was getting point like the sequence you've mentioned. That's why its working lol :) 

And I used the wrong sequence for converting the topLeft,bottomRight. 

so after I get the topLeft, bottomRight ; I call a function which convert the imagePoint to canvasPoint , so I shouldn't do this.. 

I think to calculate width, height regardless of the rotate state..I've to directly use imgBounds.getTopLeft();, imgBounds.getBottomRight(); 
without any conversion ..? 

I'll try this way. if It didn't work I'll put my code on CodePen so we can investigate easier. 

Thanks alot 👍

**Comment by iangilman** [comment]
Sounds good :)
