### ISSUE TITLE
Couple of Questions About The Tile Cache

### ISSUE THREAD

**Issue by linker2424** [openseadragon/openseadragon#1503]
I’m changing my image by changing a parameter in the image’s URL (which changes how the image looks). I can’t figure out how to invoke this on the fly. I need re-request all the tiles that have already been loaded. I’ve tried the following:
viewer.world.resetItems();
               viewer.forceRedraw();
                
Any sequence of the above calls still leaves the current image unchanged (i.e., it didn’t redraw the already cached tiles). Once I start zooming or panning, I get the updated tiles, but I want to be able to change the image once I update the parameter. 
Is there a way to force delete all the tiles that are cached? Am I missing how to force redraw the image?
Lastly, in the tileCache class how does maxImageCacheCount work? What is it default set to? Are there performance improvement by setting this higher?

Thanks!

**Comment by iangilman** [comment]
Strange... just `viewer.world.resetItems();` should be enough. Can you share a CodePen or something of the issue?

The default `maxImageCacheCount` is 200. If more images than that are loaded, we start releasing tiles that haven't been used in a while. Making the value bigger will only have an effect if your image has more than 200 tiles, and even then it probably won't be terribly noticeable.
