### ISSUE TITLE
Viewport With Custom Navigator Location

### ISSUE THREAD

**Issue by Fabroh** [openseadragon/openseadragon#1504]
Hello,

I think I found a bug with the custom navigator location : 

 - Move the viewport to get the highlighted area in the navigator
 - Click on Toggle full page button
 - Move the viewport
 - Exit fullscreen (by keyboard or button) => the highlighted area is small and glued in top left corner
 - Move the viewport => the highlighted area is correcly redraw.

Here is a video reproducing on openseadragon github site : https://drive.google.com/file/d/1W15NMAyGNcXW259FEC-2dAuns4cbMXcx/view?usp=sharing
Regards.

**Comment by iangilman** [comment]
Good catch! Thank you for reporting this. 

I believe issue is that while we're in full screen, the other elements on the page are temporarily removed, so sizing information is incorrect. 

One possible fix would be for the navigator to listen to its parent viewer's `full-screen` event and call its own `update` function at that time. Something like this:

```
this.viewer.addHandler('full-screen', function(event) {
  if (!event.fullScreen) {
    _this.update();
  }
});
```

Would you be up for making a patch for this?

**Comment by Fabroh** [comment]
You're welcome, yes I can make a patch but I can't do it until two weeks if it's ok to you.

**Comment by iangilman** [comment]
Sure, no problem... thank you!

**Comment by Fabroh** [comment]
Hello,
I'm back on the issue. I read again you answer and I think I misunderstood it. Would like me to try to correct the source code or just try your patch in my code ?

If it's the second choice I tried and it's not working, and if it's the first would you like me to take a look ?

Regards.

**Comment by iangilman** [comment]
I meant would you be up for correcting the code, but yes, trying it on your own code is a good first step. I wrote the example code as if it was a part of the Navigator object, though, so that might be part of the problem. Here it is written standalone (assuming your viewer is called `viewer`):

```
viewer.addHandler('full-screen', function(event) {
  if (!event.fullScreen) {
    viewer.navigator.update();
  }
});
```

If that still doesn't work, it might be a timing issue. Give this a try:

```
viewer.addHandler('full-screen', function(event) {
  if (!event.fullScreen) {
    setTimeout(function() {
      viewer.navigator.update();
    }, 1);
  }
});
```

Anyway, once we get something that works standalone, it would be great if you would make a pull request that fixes the OSD code as well!

**Comment by Fabroh** [comment]
Thank your for the clarification, I thought about timing but still not working.

I'll make a pull request as soon as I get something that works.

Regards.

**Comment by iangilman** [comment]
Hmm... well, let me know if I can be of further help in your hunt. Feel free to share a CodePen or something if you'd like.

Anyway, good luck and I look forward to seeing what you find!

**Comment by iangilman** [comment]
This is fixed by #1515.

**Comment by Fabroh** [comment]
Just for information, do you know when v2.4.1 will be released ?

**Comment by iangilman** [comment]
We're on a pretty slow release cycle, so probably not for a few months, unless we've got reason to do otherwise. Can you use a build from the master branch in the meantime?

**Comment by Fabroh** [comment]
Ok thanks for the answer, I'll do that.
