### ISSUE TITLE
.DZI creator using grid images.

### ISSUE THREAD

**Issue by shivamchaubey** [openseadragon/openseadragon#1506]
Hello!

Is it possible to create a full resolution image using openSeadragon? I have a 300X300 image, I want to display the mosaiced image. The images can be assembled without any processing (without crop, blending etc.), joining vertically and horizontally. I am using Pyvips to create .dzi image but it's taking huge RAM around 20GB for this set, I want it to bring down <4GB RAM uses. I just need to see the full resolution image. Is there any API to do this, How can this be done?

**Comment by iangilman** [comment]
So you're creating a mosaic out of 300px square images? And you want to go directly from those images to a DZI, without going through the step of stitching it together into a giant image first? Theoretically it should be possible, but you'll need to right a custom script for it; I'm not aware of an existing script that will do that.

Take a look at the DZI docs:

https://github.com/openseadragon/openseadragon/wiki/The-DZI-File-Format

... To get an idea of what you're building. You'll want your tile size to be 300 and your overlap to be 0. Then layout all of your 300px images using the DZI filename structure. That's your high resolution layer. Then you need to make the lower resolution layers, by taking quartets of tiles and turning them into single 300px tiles; that's your next layer. From there just keep repeating until you get to the smallest level. 

Of course maybe you don't care about the lower levels and just want to visualize the highest resolution? If that's the case, making a custom tile source is probably best:

http://openseadragon.github.io/examples/tilesource-custom/

You can have it only care about the one layer. 

Anyway, let me know if I understood your question properly, and if you have any questions about my answer :)

**Comment by iangilman** [comment]
I see from https://stackoverflow.com/questions/51588329/tiling-of-large-numer-of-images-using-database that your images are actually 640px by 480px (and that you have 300x300 of them). Note that the DZI format requires square tiles, so you wouldn't be able to have one tile per image. You could still build a DZI this way, but you would have to do more math to figure out which images go in which tiles. 

I believe it's possible to make a custom tile source with non-square tiles (use `tileWidth` and `tileHeight` instead of `tileSize`).

**Comment by shivamchaubey** [comment]
Thanks @iangilman 

I have understood the concept of .dzi. I can create it manually at each level and resolution. The whole mosaiced image can be cropped in 256X256 and the remaining area can be padded, but we need to have prior information of mosaiced image size and coordinates of images and thus it can be mapped in different resoltuions and levels. 
Still I am searching for some open source code which can do my job.

**Comment by iangilman** [comment]
Okay, good luck! I don't know of such code, but it must be out there!
