### ISSUE TITLE
ViewportPoint to world item index/coordinates

### ISSUE THREAD

**Issue by alvaromartmart** [openseadragon/openseadragon#1508]
I am using collection mode to display several TileSources, capturing the 'canvas-click' event and using Viewport.pointFromPixel to obtain the clicked viewportPoint.

```
viewer.addHandler('canvas-click', function(event) {
  var viewportPoint = viewer.viewport.pointFromPixel(data.position, true);
  var selectedImage = viewer.world.getItemAt(0); // < This is what I would like to detect
  var pixelCoordinate = selectedImage.viewportToImageCoordinates(viewportPoint,true);
})
```

I would like to obtain the ID of the item under that viewportPoint, so I can use viewportToImageCoordinates to obtain the pixel position in that specific image. Is there any way I can do it?

**Comment by iangilman** [comment]
Here's an example of figuring out which image a viewport point is over: 

https://codepen.io/iangilman/pen/PqxvgN

Basically you just have to go through all of the images and compare their coordinates.

**Comment by alvaromartmart** [comment]
Thanks a lot @iangilman, that worked perfectly!
