### ISSUE TITLE
Convert pixel to web for annotation

### ISSUE THREAD

**Issue by HafezEM** [openseadragon/openseadragon#1509]
Hi,

I have one .svs file and some annotations on it. I created a deepzoom of .svs and I need to visualize the image with annotations on Openseadragon. So coordinates of the annotations are in pixels (actual image). I am trying to do the same as https://openseadragon.github.io/examples/viewport-coordinates/, but reverse. First, I read the pixel coordinates. Convert them to viewport by: imageToViewportCoordinates() and then convert viewports to web by:  me.viewer.viewport.pixelFromPoint(). But they don't lie on the deepzoom image on openseadragon. Do you have any idea how I can fix it?

Thank you so much.
 
Hafez

**Comment by iangilman** [comment]
Sounds like you’re doing basically the right thing… once you get the point converted to web coordinates, what do you do with it then? Are you using it to draw the annotation to the screen? How are you drawing it? 

If you have an example I can look at (such as a CodePen), it would be easier for me to see where it’s going wrong.
