### ISSUE TITLE
multi-image example

### ISSUE THREAD

**Issue by joesong168** [openseadragon/openseadragon#1510]
Dear Iangilman,
      I am looking for a good multi-image example in OSD and find the example OSD+Flickr rather interesting. Is the possible to show the source code of this example?

Regards,
Joe

**Comment by stone12379** [comment]
Excellent! Thanks a lot! I will definitely look into them.

**Comment by ratigumashvili** [comment]
Sorry for the silly question but anyway: As far as I understand you are adding tiles from ‘js/harvard-tilesources.js’ and as I can see it is some kind of a manifest file. So **I’m completely stacked at this level**. How can I create my own manifest file or how can I import **my own book/multiple pages**?

**Comment by iangilman** [comment]
That manifest is just a little ad-hoc array I created for that demo. It's got some info that's useful (like a label for each file), but the format isn't important.

If you're trying to create your own multi-image project, you can just use an array of tile sources, like so: 

```
var viewer = OpenSeadragon({
  tileSources: ['/files/a.dzi', '/files/b.dzi']
});
```

Of course if you're using the code from the demo above, then you will want to mimic the manifest format it uses.
