### ISSUE TITLE
Empty tile dillemma 

### ISSUE THREAD

**Issue by boskar** [openseadragon/openseadragon#1514]
Hello, 

to cut long story short - in my scenario up to 30-80% of the DZI image is empty.
As I gave up on generating tiles on the fly I need to keep empty tiles, and transfer them to the user, which is a waste of resources. 

Have anybody tried to manage with this issue? 
Although empty tiles are small, it is still something. 

The best solution that comes to my mind is to display predefined "error tile" on http 404, and remove empty tiles from the server (with OSD plugin?) 

Other ideas are server side - like symbolic links, HTTP redirections, but those solutions does not decrease the number of http transactions. 

What do You think?

**Comment by iangilman** [comment]
The DZI file format includes a concept called "sparse images" which is briefly described here:

https://docs.microsoft.com/en-us/previous-versions/windows/silverlight/dotnet-windows-silverlight/cc645077(v=vs.95)#sparse-images

The sparse image has a `DisplayRects` section that shows which areas should be loaded. You can see an example of one of these DZI files at the top of https://github.com/openseadragon/openseadragon/issues/1081. 

I know Deep Zoom Composer can generate these files; I am not sure what other tools do. It's just XML, so you can experiment with building it yourself. Unfortunately there's not a lot of documentation about sparse images that I'm aware of. 

Anyway, that's probably exactly what you're looking for. Another option (as you've suggested) is to delete those tiles from your server and OSD will get 404s. It already knows to ignore tiles that come back empty like that.
