### ISSUE TITLE
Attempting to Use Inline-Configuration With Multiple Tile Sources

### ISSUE THREAD

**Issue by Seanrc** [openseadragon/openseadragon#1516]
Is it possible to array inline-configuration data for multiple tile sources?

I've had to move my viewer to a new domain while maintaining storage of images and xml files on another domain. To avoid enabling CORS I'd like to use inline-configuration for the images I need to display (not as a collection). I've tried finding examples and setting up the array myself under tileSources but have not been successful.

**Comment by iangilman** [comment]
Absolutely... just use an array where you normally would use a single object. Here's an example: 

https://codepen.io/iangilman/pen/PqxvgN

**Comment by Seanrc** [comment]
Thanks Ian - I'm not sure this is what I'm looking for. Though to be honest my knowledge of javascript is lacking.

Sorry for not being more specific. I currently have the images set up so that the user can click through them one by one or click a link in a menu to the left of the viewer to go directly to one of their choice. So I have every xml file listed out under tileSource but now want to load all of that xml using the inline-configuration. All of the images are PNGs and of the same size. Does your example work towards this end? Example below:

` var viewer = OpenSeadragon({
        id: 'contentDiv',
        sequenceMode: true,
        showReferenceStrip:  false,
        collectionMode:  false,   
        prefixUrl:          'https://www.aacp.org/sites/default/files/posters/openseadragon/images/',
        showNavigator: false,
        maxZoomPixelRatio: 1.0,
        controlsFadeDelay: 3500,
        homeFillsViewer: false,
        minLevel: 9,
        maxLevel: 12,     
        tileSource: [
        	"example.net/.../k-johnson.xml",
            "example.net/.../j-malinowski.xml",
            "example.net/.../g-anagnostou.xml",
             ...`

**Comment by iangilman** [comment]
[I've taken the liberty of formatting your code using ``` so it prints on multiple lines.]

That should be fine. What kind of XML is it? DZI? If so, you might find this example useful for converting from XML to inline-configuration:

https://codepen.io/iangilman/pen/gpejpJ

**Comment by Seanrc** [comment]
The XML is DZI, out of Deep Zoom Composer. I was able to get one tile source to load using your example. However, the tiles fail to load when I add my own viewer code plus javascript for menu interaction and all of the tile sources.

https://jsfiddle.net/seanrcl/ezut8ya0/

**Comment by iangilman** [comment]
Cool, you're getting there. Just a couple of issues. Rather than having a single bit of XML, you need one for each of your files. Basically you need to copy the entire content of your DZI XML file and pair it with the URL to the `_files` folder. For example:

```
var imageData = [
  {
    filesUrl: 'https://www.aacp.org/sites/default/files/posters/2018/H-Eukel_files/',
    xml: '<?xml version="1.0" encoding="utf-8"?><Image TileSize="256" Overlap="1" Format="png" xmlns="http://schemas.microsoft.com/deepzoom/2009"><Size Width="2559" Height="1801"/></Image>'
  },
  {
    filesUrl: 'https://www.aacp.org/sites/default/files/posters/2018/b-chewning_files/',
    xml: '<?xml version="1.0" encoding="utf-8"?><Image TileSize="256" Overlap="1" Format="png" xmlns="http://schemas.microsoft.com/deepzoom/2009"><Size Width="2559" Height="1801"/></Image>'
  }
];
```

... But with the actual XML content for each file (instead of my example XML).

The other thing is instead of passing just a single tileSource into the viewer, you need to convert all of the images and make an array of tileSources, like so:

```
var tileSources = imageData.map(function(image) {
  return tileSourceFromData(image.xml, image.filesUrl);
});

var viewer = OpenSeadragon({
  tileSource: tileSources,
  // Other options go here
});
```

**Comment by Seanrc** [comment]
Getting closer. I now see the xml for each tilesource logged in the console. Luckily, the xml is the same for each as they're all the same size and format.  

However, I'm seeing TypeErrors for the object under each {Image: {…}}. Do I not have the functions setup/ordered properly? The tiles are still not loading.

https://jsfiddle.net/seanrcl/ezut8ya0/

**Comment by iangilman** [comment]
Woops! Sorry, I didn't notice that it shouldn't be `tileSource` when creating the viewer, but `tileSources`, like so:

```

**Comment by Seanrc** [comment]
I should have caught that as well. 

Thanks for all the help! I had to clean up some clerical errors but all the images are loading correctly. Now I can begin working towards making the sidebar menu collapsible and taking another stab at making it searchable.

**Comment by iangilman** [comment]
Excellent :)
