### ISSUE TITLE
constrainDuringPan and visibilityRatio do not work on 'canvas-release' event

### ISSUE THREAD

**Issue by vinaymuthanna0727** [openseadragon/openseadragon#1519]
Hi iangilman,

I have canvas images and I need to draw line on canvas image with mouse button press.
I have zoom in and moved to the corner part of the canvas image and set the properties with 
 viewer.constrainDuringPan = true;
 viewer.viewport.visibilityRatio = 500;
After drawing the line on canvas image .On mouse 'canvas-release' event the canvas image comes to original position Even  
 viewer.constrainDuringPan = true;
 viewer.viewport.visibilityRatio = 500; is set .
I Need canvas image to remain in the same position and zoom level after drawing the line 
Can you please give any other solution to resolve this ??

Thanks
Vinay

**Comment by iangilman** [comment]
`visibilityRatio` should be a number between 1 and 0, so that's your first problem. 

I'm not sure what you're trying to accomplish... you just don't want the canvas to move at all while the user is drawing lines on it?

**Comment by vinaymuthanna0727** [comment]
Hi iangilman,
Thanks for the response.
Above properties for  visibilityRatio should be a number between 1 and 0,
will get failed when you zoom in image and drag it (image moves to the horizontal and vertical)
Here is the code pin for the same 

https://jsfiddle.net/ptqmLf2u/

Step 1:Able to draw the line without zoom in
Step 2:Zoom the image and draw the line .Images shift the potions according to the movement

**Comment by iangilman** [comment]
Sounds like maybe you just want to stop panning? One way to do that would be: 

```
viewer.panHorizontal = false;
viewer.panVertical = false;
```

**Comment by vinaymuthanna0727** [comment]
Hi,
Its working with these setting and one problem i am facing is, its work perfectly when is image is fit to the viewer of the deep zoom [Image name :viewer1].when i zoom and move the image to the half of the viewer[image name:viewer2] and draw the line,then image will be fit(move) back the deep zoom complete viewer size(but before i draw the line i have moved the image to half of the viewer) how to overcome there problem?? 

These is the code i am using now 
I am calling deepZoomImageMovement function on
 viewer.addHandler('canvas-press', function (event) { 
///lineAnnotationEnabled  value is set on button click 
if (lineAnnotationEnabled == "true" ) {
            deepZoomImageMovement(true);         
        } else {
            deepZoomImageMovement(false);
        }
}
function deepZoomImageMovement(result) {       
            if (result) {
                viewer.constrainDuringPan = true;
                viewer.viewport.visibilityRatio = 1;
                viewer.panHorizontal = false;
                viewer.panVertical = false;              
            } else {
                viewer.constrainDuringPan = false;
                viewer.viewport.visibilityRatio = 0;
                viewer.panHorizontal = true;
                viewer.panVertical = true;
            }
        }
    }

Thanks in advance 
![viewer1](https://user-images.githubusercontent.com/10174962/44466673-7c655900-a63e-11e8-820b-708c2e05d975.PNG)
![viewer2](https://user-images.githubusercontent.com/10174962/44466683-85562a80-a63e-11e8-8c39-a2708d917603.PNG)

**Comment by iangilman** [comment]
Try removing the lines that change `viewer.constrainDuringPan` and `viewer.viewport.visibilityRatio`.

**Comment by vinaymuthanna0727** [comment]
Its work perfectly.
Thank you so much
