### ISSUE TITLE
Need an example of a swipe-able gallery with zoom capability

### ISSUE THREAD

**Issue by stone12379** [openseadragon/openseadragon#1523]
Is this feature possible by OSD? Cause swipe-able gallery looks useful especially on mobile end. Thanks.

**Comment by stone12379** [comment]
Thank you, Iangilman. I will figure out my way to solve this problem including writing a plug-in if necessary.

**Comment by iangilman** [comment]
Sounds good... let me know how it goes!

**Comment by SamHall** [comment]
Not sure if this is what you have in mind, but it worked for my needs.
It utilizes a plug-in to center dzi's and restricts movement to horizontal.
http://deepzoomchattanooga.com/1904springfestival.php

**Comment by stone12379** [comment]
Looks interesting, although I couldn't replay it on my cellphone. Any luck to share the source code?

**Comment by SamHall** [comment]
What phone OS? Should look like this: https://vimeo.com/287369907/51b00ce54a

Relevant code with the auto-center feature below (number of DZIs greatly reduced for simplicity)

`<script type="text/javascript">
var viewer = new OpenSeadragon.Viewer({
id: "openseadragon-canvas",
prefixUrl: "/openseadragon/images_TEST/",
navigationControlAnchor: OpenSeadragon.ControlAnchor.TOP_RIGHT,
sequenceControlAnchor: OpenSeadragon.ControlAnchor.TOP_RIGHT,
showNavigator:  false,
showZoomControl: false,
showHomeControl: true,
collectionMode: true,
collectionRows: 1,
autoHideControls: false,
tileSources: [
"https://s3.amazonaws.com/dzchattzoom/legaldocs/Cover_inside.dzi",
"https://s3.amazonaws.com/dzchattzoom/legaldocs/p1.dzi",
"https://s3.amazonaws.com/dzchattzoom/legaldocs/p2.dzi",
"https://s3.amazonaws.com/dzchattzoom/legaldocs/p3.dzi",
"https://s3.amazonaws.com/dzchattzoom/legaldocs/p4.dzi",
"https://s3.amazonaws.com/dzchattzoom/legaldocs/p061.dzi",
"https://s3.amazonaws.com/dzchattzoom/legaldocs/Back_inside.dzi"
]
});
viewer.addHandler('open', function() {
setTimeout(function() {
viewer.viewport.fitBounds(viewer.world.getItemAt(0).getBounds());
}
, 700);
} );
viewer.addHandler('canvas-drag-end', function() {
var viewportBounds = viewer.viewport.getBounds();
var intersectionCount = 0;
var imageBounds, intersection, area, best;
var count = viewer.world.getItemCount();
for (var i = 0; i < count; i++) {
imageBounds = viewer.world.getItemAt(i).getBounds();
intersection = viewportBounds.intersection(imageBounds);
if (intersection && intersection.width > 0 && intersection.height > 0) {
area = intersection.width * intersection.height;
intersectionCount++;
if (!best || area > best.area) {
best = {
area: intersection.width * intersection.height,
imageBounds: imageBounds.clone()
}
}
}
}
if (intersectionCount > 1) {
viewer.viewport.fitBounds(best.imageBounds);
}
});
</script>`

**Comment by iangilman** [comment]
@SamHall That slider looks great! 

BTW,  you can use ``` to format your text so it's not all one long run on. I've gone ahead and done it for your comment above.

**Comment by SamHall** [comment]
Whoops - thank you.
I used the <>insert code GUI option which didn't look correct, but it was late and I was sleepy.
