### ISSUE TITLE
Check if elements are visible in viewport.

### ISSUE THREAD

**Issue by Salitehkat** [openseadragon/openseadragon#1525]
HI, 
Maybe this is super complex or maybe not, but as I am super newbie  everything is complex. I am asking expecting any answer in return ;). 
I have some rotating animations on svg elements using svg overlay. 
I would like to know if its possible to rotate the elements only if they are visible in the viewport. ( and stop the animations if not). 
I imagine it has to do with getBounds() to check the coordinates but from then on I am lost. 
If its "finding the 5 leg of the cat", please forgive my question. 
Thanks so much

**Comment by Salitehkat** [comment]
I did this  [test page](https://linkrural.org/pp/test.html) to help the question. Thanks so much.

**Comment by Salitehkat** [comment]
I managed by using this function for each element:

```
function inViewport(el) {

			var r, html;
			if ( !el || 1 !== el.nodeType ) { return false; }
			html = document.documentElement;
			r = el.getBoundingClientRect();
		
			return ( !!r 
			  && r.bottom >= 0 
			  && r.right >= 0 
			  && r.top <= html.clientHeight 
			  && r.left <= html.clientWidth 
			);
		
		}

;) 
```
Thank u!!

**Comment by iangilman** [comment]
That seems like a fine approach. The other option would be to do it with viewport coordinates and `viewer.viewport.getBounds()` instead of `el.getBoundingClientRect()`, but since you've already got it working, no reason to change :)
