### ISSUE TITLE
Fire Event when click on Next/Previous-Button?

### ISSUE THREAD

**Issue by fabianschan** [openseadragon/openseadragon#1527]
I have build a synoptical View with IIIF and OpenSeadragon (see related picture). Now if i want to add an EventListener I dont get how to adress die buttons, while they don't have any HTML-IDs oder -Classes. I want to change the HTML-File in the iframe on the right to the right page when changing the faksimile to the left.

Can someone help me with that issue?

<img width="1440" alt="screen shot 2018-08-26 at 09 09 24" src="https://user-images.githubusercontent.com/21081453/44625703-f4b66d80-a90f-11e8-8506-2f8e76168b2d.png">

**Comment by iangilman** [comment]
You should be able to catch the `page` event to know this. 

```
viewer.addHandler('page', function(event) {
  console.log('Now on page', event.page);
});
```

See http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#.event:page for more info.

**Comment by fabianschan** [comment]
@iangilman Thank you very much! That worked perfectly.
I'm very new to JavaScript. How can I call the GoToPage() Method? If I want to make an Input-Field, where the visitor can give in the page-number as a value?

**Comment by NiteshSaxena** [comment]
@fabianschan You can add a input box in the viewer via viewer.addControl method. 

You could use something like this:
`viewer.addControl(yourHtmlElement, { anchor: OpenSeadragon.ControlAnchor.TOP_RIGHT });`

In your html element, you can add an onchange event.
`<input type="text" id="page" onchange="GoToPage" />`

On GoToPage() method, write your logic to refresh the viewer.
I hope this helps.

**Comment by iangilman** [comment]
It's not actually `GoToPage` literally... it's `viewer.goToPage(index)`. So yeah, using @NiteshSaxena's example, you could define your own `GoToPage` like so: 

```
function GoToPage(event) {
  var index = parseInt(event.currentTarget.value, 10);
  viewer.goToPage(index);
}
```
