### ISSUE TITLE
Preset a certain part of severel picture before start

### ISSUE THREAD

**Issue by ftomasch** [openseadragon/openseadragon#1530]
Hi Ian,
After a long break I finally can manage to develop the panoramas. Id like to add another panorama to the first. For both of them I have determined an image section for the start. Your script functions very well!
However, I have another problem:
The start position of the second panorama functions. At the first panorama the determined start positions are ignored.

I have added the following:
screenshot 1: only first panorama
![nur eins](https://user-images.githubusercontent.com/34056100/44998178-c7bf2600-afb3-11e8-973f-908851e71921.jpg)

screenshot 2: both panoramas
![beide](https://user-images.githubusercontent.com/34056100/44998173-be35be00-afb3-11e8-95cc-1d4a1ae7205e.jpg)

and here is the code:
...

// Panorama Paris -->

<script type="text/javascript"> 
// Variablen zum positionieren der Navigationselemente 
var _viewer; 
var CtrlPos= OpenSeadragon.ControlAnchor.BOTTOM_RIGHT;
var CtrlPos2= OpenSeadragon.ControlAnchor.BOTTOM_RIGHT; 
var viewer = OpenSeadragon 
({ 
id: "ParisHotel", 
tileSources: "Panorama/ParisHotel/ParisHotel.xml", 

// Begrenzungsrahmen 
visibilityRatio: 1, 
constrainDuringPan: true, 

// Button und andere Anzeigen // 
controlsFadeDelay:500, 

//Pfad zu den Buttonbildern 
prefixUrl: "Panorama/openseadragon/images/", 
//Navigationsbutton 
showNavigationControl: true, 

// die vier Standardbutton navigationControlAnchor: CtrlPos, showZoomControl: true, showHomeControl: false, showFullPageControl: false, homeFillsViewer: false, showSequenceControl: false, sequenceControlAnchor: CtrlPos2, sequenceMode: false, 

//kleines Bildfenster zum Navigieren 
showNavigator:false, 

//verkleinerte Ansicht mit Zoomausschnitt (bildnavigator) 
navigatorPosition: "BOTTOM_RIGHT", 

// verschiebt das Fenster 
navigatorHeight: "75px",

// Größe des Navigatorfensters 
navigatorWidth: "120px", 
}); 

// festlegen der Startansicht 
var boundsParis = new OpenSeadragon.Rect
( 0.019333581180118742, 1.9517561207172962, 0.8167599134234494, 0.563043004147229,); viewer.addHandler('open', function() {viewer.viewport.fitBounds(boundsParis, true); }); 
</script>

// Panorama Agde -->
<script type="text/javascript"> 
// Variablen zum positionieren der Navigationselemente 
var _viewer; var CtrlPos= OpenSeadragon.ControlAnchor.BOTTOM_RIGHT; 
var CtrlPos2= OpenSeadragon.ControlAnchor.BOTTOM_RIGHT; 
var viewer = OpenSeadragon ({ 
id: "Agde", 
tileSources: "Panorama/Agde/Agde.xml", 

// Begrenzungsrahmen visibilityRatio: 1, 
constrainDuringPan: true, 

// Button und andere Anzeigen 
controlsFadeDelay:500, 

//Pfad zu den Buttonbildern 
prefixUrl: "Panorama/openseadragon/images/", 

//Navigationsbutton showNavigationControl: true, 

// die vier Standardbutton 
navigationControlAnchor: CtrlPos, 
showZoomControl: true, 
showHomeControl: false, 
showFullPageControl: false, 
homeFillsViewer: false, 
showSequenceControl: false, 
sequenceControlAnchor: CtrlPos2, 
sequenceMode: false, 

//kleines Bildfenster zum Navigieren 
showNavigator:false, 

//verkleinerte Ansicht mit Zoomausschnitt (bildnavigator) 
navigatorPosition: "BOTTOM_RIGHT", 

// verschiebt das Fenster 
navigatorHeight: "75px",

// Größe des Navigatorfensters 
navigatorWidth: "120px", 
}); 

// festlegen der Startansicht 
var boundsAgde = new OpenSeadragon.Rect
( 0.1845514603352556, 0.057905793669573054, 0.23080523768893155, 0.08691259731723829); viewer.addHandler('open', function() {viewer.viewport.fitBounds(boundsAgde, true);
}); 
</script>
The adress of the Site is: www.tomaschowski.com

Please, could you hlp me, once more

Best regards
ftomasch

**Comment by iangilman** [comment]
I've gone ahead and commented on this over in #1351, so I'll close this one.
