### ISSUE TITLE
the position of navigator

### ISSUE THREAD

**Issue by xiayuan920** [openseadragon/openseadragon#1536]
Hi.When the height and width of viewerport is fixed value , How to set the css style of navigator to fixed？In the other word,I want the navigator to move as the browser window zooms.

**Comment by iangilman** [comment]
I'm not sure I understand what you're trying to accomplish. How do you want the navigator to move? 

At any rate, there are a number of positioning options for the navigator documented here:

http://openseadragon.github.io/docs/OpenSeadragon.html#.Options
