### ISSUE TITLE
White background under image before loading it.

### ISSUE THREAD

**Issue by arreumb** [openseadragon/openseadragon#1538]
When loading images on a colored background, in the small time before the image is loaded a white shape of the same format of the image is shown over the colored background. This causes a sort of flashing (not very nice to see).  To avoid this problem I'm using Openseadragon 2.2.1 where this white background is not shown. Is there any way or workaround to avoid this problem in the last versions ?
Thanks.

**Comment by iangilman** [comment]
Hmm, I don't think that's supposed to be happening. Do you have an example you can share?

Anyway, you might try playing with the `placeholderFillStyle` option (e.g. `placeholderFillStyle: '#ff88aa'`) to see if that helps.

**Comment by arreumb** [comment]
It seems like the default for placeholderFillStyle is the white color while I need  'transparent' as  default.
The background under the images (of different sizes) has a gradient so I cannot simply set that property to some color or gradient. I will try to set that placeholderFillStyle to 'transparent' to see if it works. Unfortunately the code is part of a large application so is difficult for me to share it.
Thanks for your help.

**Comment by iangilman** [comment]
The default for placeholderFillStyle is supposed to be transparent. I've just now tried it on my computer and it seems to be working. I've also tried with `'transparent'` and that's working as well.

If you could make a CodePen that isolates and illustrates the issue that could help me track it down, and it could also help you figure out what aspect of your project might be causing it.

**Comment by arreumb** [comment]
I'm sorry, it was my fault: placeholderFillStyle was initialized in my code to white. Thanks again for your help.

**Comment by iangilman** [comment]
Good to know! All is well that ends well :)
