### ISSUE TITLE
WebGL to render constantly and react to change

### ISSUE THREAD

**Issue by zloysmiertniy** [openseadragon/openseadragon#1544]
I am trying to load an image using OSD and then applying a shader to get each channel of the RGB image separately. But so far it only changes the channel when the tile is drawn the first time and once it has been loaded it never changes channel again. So I think that the shader is not being applied to every draw but only once when tile is loaded.

I am trying to understand the code of ViaWebGL and I am wondering if I am missing something. I try to set "gl-drawing" like it says in the ViaWebGL doc but my guess is that the tile is loaded, shaded and then sent to OSD. I thought it was about like a postprocessing shader that acted on the whole rendered view. 

So my hope is to be able to change the channel using `gl.getUniformLocation(program, channel);` and then as soon as I zoom in/out or pan, this change has to be apparent. 

Maybe something like when the OSD view is updated I could make a call to ViaWebGL toCanvas? or something like that?

**Comment by iangilman** [comment]
It might be worth filing this over on https://github.com/thejohnhoffer/viaWebGL for @thejohnhoffer. Also, you might be interested in https://github.com/openseadragon/openseadragon/issues/1482 that he's also involved in.

**Comment by zloysmiertniy** [comment]
Thanks. I did post it in the issues some time ago. I will read that thread seems very interesting. Just by trying many things I realized that in the simplest form the tiles are loaded and when loaded they are shaded and then sent to OSD. So I am looking for a way to keep the original and shade them all the time or maybe better whenever the view is updated.

I am also interested in knowing how to properly pass a uniform to the shaders, I "hacked" my way into getting the id of the shader program so I could do it manually but I was wondering if I am missing a way to do it more elegantly.

I might be missing something but I can't make OSD to wait and not open the image, so that ViaWebGL can merge its init function with OSD init function. I create a new OSD like this
`osdviewer = OpenSeadragon(my_options);` and "my_options" looks like this:
```
my_options: {
       id: "raw_viewer",
       prefixUrl: "js/openseadragon/images/",
       navigatorSizeRatio: 1,
       wrapHorizontal: false,
       showNavigator: true,
       navigatorPosition: "BOTTOM_LEFT",
       navigatorSizeRatio: 0.25,
       animationTime: 0.0,
       blendTime: 0,
       minZoomImageRatio: 1,
       maxZoomPixelRatio: 1,
       zoomPerClick: 1.0,
       constrainDuringPan: true,
       visibilityRatio: 1
     }
```

**Comment by iangilman** [comment]
Yeah, being able to keep hold of the original sounds useful. 

I don't know enough about viaWebGL to know if there's a better way to pass uniforms in. Hopefully we'll hear from @thejohnhoffer at some point.

I don't understand what you mean by needing OSD to wait and not open the image. You can create the viewer first and then call `open` on it when you're ready. Is that all you mean, or is it something more complicated?

**Comment by zloysmiertniy** [comment]
I need to check, because the idea is that viaWebGL merges its open function with that of OSD. But right now What I do is simply 
`my_viewer = OpenSeadragon(my_options); `
and without calling open it is still opening

I found out that I was passing the uniform right, the problem was that the tile was only rendered once and even if I change the uniform it won't have any effect because the tiles are not being drawn constantly but only once, when they are loaded.

I can wait :) all of this will be documented and used by the people who work with the project in the future.

**Comment by iangilman** [comment]
Cool. This seems like an important direction to be pushing forward...

**Comment by iangilman** [comment]
BTW, @KevinSjoberg might be interested in this conversation as well, so tagging him here.
