### ISSUE TITLE
How to get the four coordinates for the navigator window?

### ISSUE THREAD

**Issue by zzzghm** [openseadragon/openseadragon#1545]
Hi, I would like to record the field of view for viewing each image through openseadragon, I find that the viewport navigator in the demo does record the field of view. I wonder how can I get and record the four coordinates of the navigator(the red rectangle)? Could you please tell me? Really appreciate for your response!

**Comment by zzzghm** [comment]
Can I get them directly in the html like the webPoint, viewportPoint, and imagePoint?
 viewer.addHandler('open', function () {

            var tracker = new OpenSeadragon.MouseTracker({
                element: viewer.container,
                moveHandler: function (event) {
                    updateZoom();
                    var webPoint = event.position;
                    var viewportPoint = viewer.viewport.pointFromPixel(webPoint);
                    var imagePoint = viewer.viewport.viewportToImageCoordinates(viewportPoint);
                    var zoom = viewer.viewport.getZoom(true);
                    var imageZoom = viewer.viewport.viewportToImageZoom(zoom);
                    
                    positionEl.innerHTML = 'Web:<br>' + webPoint.toString() +
                        '<br>Viewport:<br>' + viewportPoint.toString() +
                        '<br>Image:<br>' + imagePoint.toString();

                    
                }
            });

**Comment by iangilman** [comment]
The red rectangle is the same as the viewport bounds. Sounds like you want that in image coordinates? That would be: 

```
var viewportBounds = viewer.viewport.getBounds();
var tiledImage = viewer.world.getItemAt(0); // Assuming you want the first (or only) image
var imageBounds = tiledImage.viewportToImageRectangle(viewportBounds);
```

**Comment by zzzghm** [comment]
Thank you!! It worked!! But the viewport bounds don't update when scrolling the mouse, only worked on moving the mouse. How can I fix it? The basic idea for the whole project is to record the mouse coordinate, zoom information, bound information and the time for each action in a textarea then save the log file for viewing path analysis. Following is my code based on your viewport coordinate:

<script type="text/javascript">
        var positionEl = document.querySelectorAll('.info .position')[0];
        var zoomEl = document.querySelectorAll('.info .zoom')[0];

        var viewer = new OpenSeadragon.Viewer({
            id: "openseadragon1",
            prefixUrl: "openseadragon/images/",
            tileSources: "RB4/Exported Data/rb4/GeneratedImages/dzc_output_images/rb1.xml",
            showNavigator: true,
            crossOriginPolicy: "Anonymous"
        });
        
        var updateZoom = function () {
            var zoom = viewer.viewport.getZoom(true);
            var imageZoom = viewer.viewport.viewportToImageZoom(zoom);
            var viewportBounds = viewer.viewport.getBounds();
            var tiledImage = viewer.world.getItemAt(0); // Assuming you want the first (or only) image
            var imageBounds = tiledImage.viewportToImageRectangle(viewportBounds);

            zoomEl.innerHTML = 'Zoom:<br>' + (Math.round(zoom * 100) / 100) +
                '<br>Image Zoom:<br>' + (Math.round(imageZoom * 100) / 100);
        }

        viewer.addHandler('open', function () {

            var tracker = new OpenSeadragon.MouseTracker({
                element: viewer.container,
                moveHandler: function (event) {
                   // 
                    var webPoint = event.position;
                    var viewportPoint = viewer.viewport.pointFromPixel(webPoint);
                    var imagePoint = viewer.viewport.viewportToImageCoordinates(viewportPoint);
                    var zoom = viewer.viewport.getZoom(true);
                    var imageZoom = viewer.viewport.viewportToImageZoom(zoom);

                    var viewportBounds = viewer.viewport.getBounds();
                    var tiledImage = viewer.world.getItemAt(0); // Assuming you want the first (or only) image
                    var imageBounds = tiledImage.viewportToImageRectangle(viewportBounds);
                    

                    var now = new Date();
                    


                    positionEl.innerHTML = 'Web:<br>' + webPoint.toString() +
                        '<br>Viewport:<br>' + viewportPoint.toString() +
                        '<br>Image:<br>' + imagePoint.toString()+'<br>test<br>'+imageBounds.toString();
                    updateZoom();
                    var text = "Viewport " + viewportPoint.toString() + "Zoom " + (Math.round(zoom * 100) / 100) +
                        "  time " + now.getHours() + ":" + now.getMinutes() + ":" + now.getSeconds() + ":" + now.getMilliseconds() + "\n\r";
                    $("#log").val(text + $("#log").val());
                    
                }
            });

            tracker.setTracking(true);

            viewer.addHandler('animation', updateZoom);
        });

**Comment by iangilman** [comment]
Looks good... you just need to call your update function from more places than just the move handler; otherwise you'll it'll only happen on mouse move. Define it as a function and use it for the moveHandler, but also use it for scrollHandler (if you want to capture the scroll wheel). You might want to test on a touch device to make sure you're getting all the events you want there as well. 

Another option is to base it on viewer events like `zoom` and `pan`; that might be more general.

**Comment by zzzghm** [comment]
Thanks! I added another 'scrollhandler', and it worked for now. Thank you for your generous help!!!

**Comment by iangilman** [comment]
Great... glad it worked!
