### ISSUE TITLE
button controls do not work in Firefox

### ISSUE THREAD

**Issue by christopher-johnson** [openseadragon/openseadragon#1546]
I have implemented openseadragon in React and have run into a snag with Firefox.  

The example here:
https://iiif.cloud/view/01c05eb4-eb83-5c00-9df8-3eb04dbf94dd
can be used to demonstrate the problem.  

The button controls (Zoom, Rotate, Home, FullScreen, Back and Next) work in Chrome, but not in Firefox.   The inconsistency in behavior between browsers is perplexing and leads me to believe that it is not something in my code as the cause.  

I have noticed however that the controls do work in Firefox in the seadragon examples...

Any ideas?

**Comment by christopher-johnson** [comment]
This is not an openseadragon issue directly.  The problem is that Firefox does not recognize a button with a  child anchor that has an id, and the button must have the id.  So, for example:
```html
<button>
  <a id='zoom-in'/>
</button>
```
does not work, but 
```html
<button id='zoom-in'/>
```
does

**Comment by iangilman** [comment]
Thanks for updating with the fix! :)
