### ISSUE TITLE
Button images loaded while I use custom buttons 

### ISSUE THREAD

**Issue by arnaudbey** [openseadragon/openseadragon#1547]
Hey there

I'm wondering why I get my browser trying to load `rotateleft_rest.png` ` rotateleft_grouphover.png` `rotateleft_hover.png` and `rotateleft_pressed.png` while i'm using custom buttons.

*  I have `'rotateLeftButton: 'osd-left'` in my OSD initialization and this in my HTML file :  ```<button id="osd-left" type="button" class="btn btn-light"><i class="fa fa-undo"></i></button>```

* I do not have the problem for other action buttons
* My custom btn is fully functional
* Here is my full config : 

```
Openseadragon({
    id: idLeft,
    showNavigator: true,
    navigatorOpacity: 0.5,
    navigatorSizeRatio: 0.1,
    navigatorPosition: 'TOP_LEFT',
    showRotationControl: true,
    showSequenceControl: false,
    prefixUrl: osdDir,
    zoomInButton: 'left-osd-zoom-in',
    zoomOutButton: 'left-osd-zoom-out',
    homeButton: 'left-osd-home',
    fullPageButton: 'left-osd-full-page',
    rotateLeftButton: 'left-osd-left',
    rotateRightButton: 'left-osd-right',
    tileSources: {
      type: 'image',
      url: url
    }
  })
```

Did I miss something ?

Thanks a lot !
Arnaud

**Comment by iangilman** [comment]
Hmm... well, you mention `<button id="osd-left"` but in your config it's `rotateLeftButton: 'left-osd-left'` ... those should be the same or it won't work.  

Other than that, seems like you're doing the right thing. If that's not the issue, could you share a CodePen or something?
