### ISSUE TITLE
OSD display images with wrong ratio

### ISSUE THREAD

**Issue by koldasm** [openseadragon/openseadragon#1551]
When I open an image with Openseadragon, the image sides are deformed. F.E. when open a square image (https://s3-eu-central-1.amazonaws.com/origoo-resized-images/product/large/15355547299691788.jpg, 1200x1200px), the opened image is deformed and I got a rectangle image. 
Trouble is not only with square images, every image I try is visually deformed. 
Using TypeScript and Openseadragon v. 2.4.0

```
this.viewer = OpenSeadragon({
          id: 'openseadragon1',
          showNavigationControl: false,
          animationTime: 0.5,
          visibilityRatio: 1.0,
          minZoomImageRatio: 0.1,
          defaultZoomLevel: 0.5,
          maxZoomLevel: 1,
          minZoomLevel: 0.5,
          zoomPerClick: 0.2,
          constrainDuringPan: true,
          tileSources: {
            type: 'image',
            url: this.selectedPicture.largeUrl
          }
        });
```

Any help? Thanks.

**Comment by iangilman** [comment]
Hmm... It's working fine for me with that image and that code (I'm using the latest master, but it's very similar to 2.4.0). Can you tell me more about the circumstances where you're seeing this? Does it happen on every browser you try? Can you make a CodePen or similar that shows the problem?

**Comment by koldasm** [comment]
It does not depend on browser (or display either). I have a printscreen, the main image uses the OSD, the red border is a square. In the bottom of the page is a thumbnail of this image loaded with `<img>` tag and it is a square.

https://origoo.cz/en/art/marek-matustik-bez-nazvu-z-cyklu-unspoken-games-7 
(You have to click on the image to get to the zooming screen.)

![screen](https://user-images.githubusercontent.com/44366310/47312251-1eec8900-d63c-11e8-85ae-49471b416946.PNG)


> Hmm... It's working fine for me with that image and that code (I'm using the latest master, but it's very similar to 2.4.0). Can you tell me more about the circumstances where you're seeing this? Does it happen on every browser you try? Can you make a CodePen or similar that shows the problem?
