### ISSUE TITLE
Fadein/out animation when replace image

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1552]
Hi when I replace an image I want to show some animation like fade in/fade out  without flickering(while change the image( ... using 
.close()
.open() 

is it possible?

thanks

**Comment by iangilman** [comment]
This functionality is not built into OpenSeadragon, but here's an example of how to build it: 

https://codepen.io/iangilman/pen/YXRLea

**Comment by johnico** [comment]
Thanks . Do you have example without fade? , just replace the image (this will be same image but the second will be with high resolution )

**Comment by iangilman** [comment]
You can use the same idea, but just change the opacity directly rather than animating. Or even remove the old one after the new one arrives. You might want to set the new one to preload and wait until it's loaded so there's no flicker.

But why are you replacing a low resolution image with a high resolution one? That's what OpenSeadragon does anyway... just make a DZI of your high resolution one and you don't need a low resolution version.

**Comment by johnico** [comment]
i am trying to replace from jpg to Tif image (IIP) with CGI bin application , 
I am trying the following:

the tiff is not working and somtimes I get 
Assertion failed: [Viewer.addTiledImage] options.tileSource is required 
```
var tileSource = 	{
				x: 0,
				y: 0,
				opacity: 1,
				tileSource: {"type":"image", "ur"l:url}
}; 													
		var selectedIndex = 0;		
		selectedIndex = 0;  
		viewer1.addTiledImage(tileSource);
											
		viewer1.world.addHandler('add-item', handler);


/// this was for jpg 

// this code for TIF 

           var tileSource = 	{
				x: 0,
				y: 0,
				opacity: 1,
				tileSource:  { tileSource:url + "/cgi-bin/app.cgi/XXXX.dzi" }; // this working with viewer.open()
                }; 	
	       var selectedIndex = 1;		
		viewer1.addTiledImage(tileSource);					
		viewer1.world.addHandler('add-item', handler2);


			function handler(){
						fade(viewer1.world.getItemAt(0), (1));	
		      }
		  function handler2(){
						fade(viewer1.world.getItemAt(1), (0));	
		  }
```

**Comment by johnico** [comment]
I manged to do smth like :

open the jpg image using open  and then run this :

```
		var oldImage = viewer1.world.getItemAt(0);
		var oldBounds = oldImage.getBounds();
		var oldSource = oldImage.source;

		viewer1.addTiledImage({
				tileSource:"get cgi ur"l,
				x: oldBounds.x,
				y: oldBounds.y,
				width: oldBounds.width, // It'll do height automatically based on aspect ratio
					success: function() {
				debugger;
				 oldImage.setOpacity(0);
				 var newImage = viewer1.world.getItemAt(0);
		              newImage.setOpacity(1);										
				}
			});

```


this is working and keep the zoom also , but still there is a little flicker .. can i improve this?

**Comment by iangilman** [comment]
Good progress! To avoid the flicker you'll have to use the preload flag and pay attention to the "fully loaded" event, like so:

```
// See https://github.com/openseadragon/openseadragon/issues/1257
function whenFullyLoaded(tiledImage, callback) {
  if (tiledImage.getFullyLoaded()) {
    setTimeout(callback, 1); // So both paths are asynchronous
  } else {
    tiledImage.addOnceHandler('fully-loaded-change', function() {
      callback(); // Calling it this way keeps the arguments consistent (if we passed callback into addOnceHandler it would get an event on this path but not on the setTimeout path above)
    });
  }
}

var oldImage = viewer1.world.getItemAt(0);
var oldBounds = oldImage.getBounds();
var oldSource = oldImage.source;

viewer1.addTiledImage({
  tileSource: "get cgi url",
  x: oldBounds.x,
  y: oldBounds.y,
  width: oldBounds.width, // It'll do height automatically based on aspect ratio
  opacity: 0,
  preload: 1,
  success: function(event) {
    var newImage = event.item;
    whenFullyLoaded(newImage, function() {
      newImage.setOpacity(1);
      viewer1.world.removeItem(oldImage); // You could set its opacity to 0, but we probably don't need it anymore.
    });					
  }
});
```

**Comment by johnico** [comment]
cool thanks
2 questions 
1 - it is much better but still there is little flick when the tiles loaded when moving from jpg  like we see the building tiles time on the screen 

2- how can I use the same functionaliy but to prevent the screen to keep zoom ( even if the previous image was with zoom), so that the user will return the home and wont feel the "return to home behavior)

thanks a lot

**Comment by iangilman** [comment]
You have two synchronized viewers, and you want the second viewer to load an image that looks like it's zoomed to home, except it's just wherever that viewer happens to be loaded to, is that correct?

BTW, can you share a link to an example of what you're doing?

As for the flicker, there shouldn't be one... I'm not sure what's going on without being able to look at what your code is doing.

**Comment by johnico** [comment]
about 
"You have two synchronized viewers, and you want the second viewer to load an image that looks like it's zoomed to home, except it's just wherever that viewer happens to be loaded to, is that correct?" 

i have one viewer on the screen , now I got update that the second image is ready and I want to update the viewer 2 , the issue is there are always sync between those images. so I need them go back to home zoom without any animation/ flickering , the image in viewer one is not updated in that case, only viewer 2

the second image will be shown after click on button (but its ready , just show the div) 


I will try to share an example

**Comment by iangilman** [comment]
Yeah, an example would help me understand!
