### ISSUE TITLE
OpenSeadragonHTMLelements plugin

### ISSUE THREAD

**Issue by antonioxdias** [openseadragon/openseadragon#1554]
Following the issues raised by user Salitehkat, #1497 and #1501 , a general solution to have HTML elements "tied" with an osd viewer seemed the way to go, so this plugin was created.

[GitHub repository](https://github.com/antonioxdias/OpenSeadragonHTMLelements)

Feel free to give suggestions and/or feature requests.

**Comment by iangilman** [comment]
Beautiful! Looks great to me. Can you make a pull request on our site repository to add it to the list of plugins?

https://github.com/openseadragon/site-build/blob/master/www/index.html#L155

**Comment by antonioxdias** [comment]
Just did ^^

How should eventual user required changes and updates be handled? Can the plugin repository be changed at will, if ever necessary?
