### ISSUE TITLE
Tiles with origin="BOTTOM_LEFT" (14 masterpieces of the Prado Museum, Madrid)

### ISSUE THREAD

**Issue by metrogoldimeyer** [openseadragon/openseadragon#1555]
Hi
How to configure for empty_pels_y?
Best Regards

```
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Custom Tile Source | OpenSeadragon 2.4.0</title>
	<link rel="stylesheet" type="text/css" media="screen" href="https://openseadragon.github.io/css/style.css">
	<style type="text/css">body, .openseadragon { background-color: #ffffff; }</style>
	<script src="https://openseadragon.github.io/openseadragon/openseadragon.min.js"></script>
</head>

<body>
	<!-- center page -->
    <div id="container">

	<!-- viewer OpenSeadragon -->
    <div id="OpenSeadragonViewer" class="openseadragon"></div>

<script>
/**
   <TileInfo tile_width="256" tile_height="256" full_pyramid_depth="10" origin="BOTTOM_LEFT">
   <pyramid_level num_tiles_x="3" num_tiles_y="4" empty_pels_x="98" empty_pels_y="253" />
 
    tiles Prado z=2          Art Project z=2
   +-----+-----+-----+      +-----+-----+-----+
   | 0,3 | 1,3 | 2,3 |      | 0,0 | 1,0 | 2,0 |
   +-----+-----+-----+      +-----+-----+-----+
   | 0,2 | 1,2 | 2,2 |      | 0,1 | 1,1 | 2,1 |
   +-----+-----+-----+      +-----+-----+-----+
   | 0,1 | 1,1 | 2,1 |      | 0,2 | 1,2 | 2,2 |
   +-----+-----+-----+      +-----+-----+-----+
   | 0,0 | 1,0 | 2,0 |      | 0,3 | 1,3 | 2,3 |
   +-----+-----+-----+      +-----+-----+-----+
*/
var cuadrosArray = [
// Dir    preTile  name maxWidth maxHeight sizeClip maxZoom
['P00015', 'img', 'Fra Angelico - La Anunciación, 1426', 86539, 85398, 256, 9],
['P00299', 'img', 'Rafael - El Cardenal, 1510', 33392, 43012, 256, 8],
['P00363', 'img', 'Tiepolo - Inmaculada Concepción, 1767-1769', 51952, 95470, 256, 9],
['P00410', 'img', 'Tiziano - El emperador Carlos V, a caballo, en Mühlberg, 1548', 58990, 69995, 256, 9],
['P00749', 'img', 'Goya - El 3 de mayo de 1808 en Madrid: Los fusilamientos en la montaña del Príncipe Pío, 1814', 58689, 45252, 256, 8],
['P00809', 'img_recortada', 'El Greco - El caballero de la mano en el pecho, 1580', 12673, 16238, 256, 6],
['P01117', 'img', 'José de Ribera - El sueño de Jacob, 1639', 52560, 39755, 256, 8],
['P01174', 'meninas', 'Velázquez - La familia de Felipe IV, o Las Meninas, 1656', 42923, 49403, 256, 8],
['P01670', 'img', 'Rubens - Las Tres Gracias, 1635', 54654, 66596, 256, 9],
['P02132', 'img', 'Rembrandt - Artemisa, 1634', 36898, 34320, 256, 8],
['P02179', 'img', 'Durero, Alberto - Autorretrato, 1498', 19047, 24047, 256, 7],
['P02823', 'img', 'El Bosco - El jardín de las Delicias, 1500-1505', 156547, 89116, 256, 10],
['P02825', 'img', 'Roger van der Weyden - El Descendimiento, 1435', 90608, 70303, 256, 9],
['P07878', 'img', 'Juan de Flandes - La Crucifixión, 1509-1518', 69273, 50061, 256, 9],
];
var [cDir, cPreTile, cName, cMaxWidth, cMaxHeight, cSizeClip, cMaxZoom] = [0,1,2,3,4,5,6];

Array.prototype.random = function(){
	var rand = Math.floor(this.length * Math.random());
	//return this[rand];
	return this[0]; // P00015
}
var cuadro = cuadrosArray.random();

	OpenSeadragon({
        id: "OpenSeadragonViewer",
        prefixUrl: "https://openseadragon.github.io/openseadragon/images/",
        showNavigator: !0,
 		navigatorAutoResize: !0,
        navigatorAutoFade: !1,
		debugMode: !0,
		debugGridColor: '#66A61E',
        tileSources:   {
            width: cuadro[cMaxWidth],
            height: cuadro[cMaxHeight],
			tileSize: cuadro[cSizeClip],
            minLevel: 0,
            maxLevel: cuadro[cMaxZoom],
            getTileUrl: function( z, x, y ){
				y = this.getNumTiles(z).y - y - 1; // invert y
				// http://mw2.google.com/mw-earth-vectordb/gallery_layers/prado/P01174/img/meninas_0_0_0.jpg
				// http://mw2.google.com/mw-earth-vectordb/gallery_layers/prado/P00299/img/img_0_0_0.jpg
				var url = "https://mw2.google.com/mw-earth-vectordb/gallery_layers/prado/"+
				cuadro[cDir]+"/img/"+cuadro[cPreTile]+"_"+z+"_"+x+"_"+y+".jpg";
				return url;
            }
        }
    });
</script>
</div>
</body>
</html>
```

![prado-openseadragon](https://user-images.githubusercontent.com/44524325/47603796-24a5ee00-d9f1-11e8-96ab-774a33ffe4c6.jpg)

**Comment by iangilman** [comment]
Hello! What problem are you trying to solve? 

BTW, I added ``` to your post so the code is readable.

**Comment by metrogoldimeyer** [comment]
Hello,
Ian, thank you very much for the support.

I attach a partial patch and it does not completely solve the visualization of tiles with origin = "BOTTOM_LEFT".
![prado-openseadragon-1b](https://user-images.githubusercontent.com/44524325/47679282-38ee1480-dbc4-11e8-9e1b-edc480757f6e.jpg)
'
 	getTileBounds: function( level, x, y, isSource ) {
        var dimensionsScaled = this.dimensions.times( this.getLevelScale( level ) ),
            tileWidth = this.getTileWidth(level),
            tileHeight = this.getTileHeight(level),
            px = ( x === 0 ) ? 0 : tileWidth * x - this.tileOverlap,
            py = ( y === 0 ) ? 0 : tileHeight * y - this.tileOverlap,
            sx = tileWidth + ( x === 0 ? 1 : 2 ) * this.tileOverlap,
            sy = tileHeight + ( y === 0 ? 1 : 2 ) * this.tileOverlap,
            scale = 1.0 / dimensionsScaled.x;

		// ini - Prado partial patch (openseadragon-2.4.0.js)
		var numTiles = this.getNumTiles( level );
		var empty_pels_y = ( numTiles.y * tileHeight ) - dimensionsScaled.y;
		py = py - empty_pels_y;
		// end  - Prado partial patch (openseadragon-2.4.0.js)

		sx = Math.min( sx, dimensionsScaled.x - px );
        sy = Math.min( sy, dimensionsScaled.y - py );

        if (isSource) {
            return new $.Rect(0, 0, sx, sy);
        }
        return new $.Rect( px * scale, py * scale, sx * scale, sy * scale );
    },
'
Best Regads
![prado-openseadragon-1d](https://user-images.githubusercontent.com/44524325/47680031-09d8a280-dbc6-11e8-9e47-4c19a6b85889.jpg)

**Comment by iangilman** [comment]
It looks like you've closed this issue... does that mean you got it sorted out? 

If not, I still need to know what it is you're trying to accomplish. I'm not familiar with `tilesOrigin`, so I don't know what it's supposed to do. Are you having trouble loading the area outlined in red in your example above?

**Comment by metrogoldimeyer** [comment]
Hello,
I try to get a correct visualization with tiles origin = "BOTTOM_LEFT" in the same way that OpenSeadragon does with origin = "TOP_LEFT" (see photo).

![tillesinfo-1b](https://user-images.githubusercontent.com/44524325/47910418-147b8c00-de93-11e8-80a9-a6a03bee9f0d.jpg)

**Comment by metrogoldimeyer** [comment]
Information of tiles with origin = "BOTTOM_LEFT"
From TileCache to WMTS
https://www.camptocamp.com/actualite/from-tilecache-to-wmts/
WMTS (Web Map Tile Service) Overview
https://www.supermap.com/EN/online/iServer%20Java%206R/API/WMTS/wmts_introduce.htm

**Comment by iangilman** [comment]
I see! Having a tile system that comes from the bottom left is new to me, so it took me awhile to understand. I'm also not familiar with TileCache or WMTS; Thank you for the links. 

So yes, OpenSeadragon only thinks in terms of top left oriented tiles. I suppose to truly fix this and natively support the bottom left tiles from TileCache, someone would have to do a lot of piping within OpenSeadragon to account for the possibility that there could be partial tiles at the top rather than at the bottom. 

Meanwhile, the work around is to use the cropping facility built into OSD. Looks like you've already got the image showing up correctly, just with some extra black at the top.  Something like so:

```
// Use the real values of course.
var imageWidth = 40000; 
var imageHeight = 40000; 
var topBlackHeight = 1000;

var tiledImage = viewer.world.getItemAt(0); // Assuming it's the first image in the viewer. 
tiledImage.setClip(new OpenSeadragon.Rect(0, topBlackHeight, imageWidth, imageHeight));
```

**Comment by metrogoldimeyer** [comment]
Thank you very much Ian.
Attachment code working correctly.
'
-------------[ changes in openseadragon-2.4.0.js ]-------------
    getTileBounds: function( level, x, y, isSource ) {
        var dimensionsScaled = this.dimensions.times( this.getLevelScale( level ) ),
            tileWidth = this.getTileWidth(level),
            tileHeight = this.getTileHeight(level),
            px = ( x === 0 ) ? 0 : tileWidth * x - this.tileOverlap,
            py = ( y === 0 ) ? 0 : tileHeight * y - this.tileOverlap,
            sx = tileWidth + ( x === 0 ? 1 : 2 ) * this.tileOverlap,
            sy = tileHeight + ( y === 0 ? 1 : 2 ) * this.tileOverlap,
            scale = 1.0 / dimensionsScaled.x;

		// --- ini - Prado partial patch (openseadragon-2.4.0.js) ---
		if ( this.tilesOrigin === "BOTTOM_LEFT" ) {
			var numTiles = this.getNumTiles( level );
			var empty_pels_y = ( numTiles.y * tileHeight ) - dimensionsScaled.y;
			py = py - empty_pels_y;
		}
		// --- end - Prado partial patch (openseadragon-2.4.0.js) ---

        sx = Math.min( sx, dimensionsScaled.x - px );
        sy = Math.min( sy, dimensionsScaled.y - py );

        if (isSource) {
            return new $.Rect(0, 0, sx, sy);
        }

        return new $.Rect( px * scale, py * scale, sx * scale, sy * scale );
    },
'
'
-------------[ html to view 14 masterpieces of the Prado Museum, Madrid ]-------------
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Custom Tile Source | OpenSeadragon 2.4.0</title>
	<link rel="stylesheet" type="text/css" media="screen" href="https://openseadragon.github.io/css/style.css">
	<style type="text/css">body, .openseadragon { background-color: #ffffff; }</style>
	<script src="https://openseadragon.github.io/openseadragon/openseadragon.js"></script>
</head>
<body>
    <div id="container">
    <div id="OpenSeadragonViewer" class="openseadragon"></div>
<script>
/**
   <TileInfo tile_width="256" tile_height="256" full_pyramid_depth="10" origin="BOTTOM_LEFT">
   <pyramid_level num_tiles_x="3" num_tiles_y="4" empty_pels_x="98" empty_pels_y="253" />
 
    tiles Prado z=2         tiles Art Project z=2
   +-----+-----+-----+      +-----+-----+-----+
   | 0,3 | 1,3 | 2,3 |      | 0,0 | 1,0 | 2,0 |
   +-----+-----+-----+      +-----+-----+-----+
   | 0,2 | 1,2 | 2,2 |      | 0,1 | 1,1 | 2,1 |
   +-----+-----+-----+      +-----+-----+-----+
   | 0,1 | 1,1 | 2,1 |      | 0,2 | 1,2 | 2,2 |
   +-----+-----+-----+      +-----+-----+-----+
   | 0,0 | 1,0 | 2,0 |      | 0,3 | 1,3 | 2,3 |
   +-----+-----+-----+      +-----+-----+-----+
   origin="BOTTOM_LEFT"     origin="TOP_LEFT"
*/
var cuadrosArray = [
// Dir    preTile  name maxWidth maxHeight sizeClip maxZoom
['P00015', 'img', 'Fra Angelico - La Anunciación, 1426', 86539, 85398, 256, 9],
['P00299', 'img', 'Rafael - El Cardenal, 1510', 33392, 43012, 256, 8],
['P00363', 'img', 'Tiepolo - Inmaculada Concepción, 1767-1769', 51952, 95470, 256, 9],
['P00410', 'img', 'Tiziano - El emperador Carlos V, a caballo, en Mühlberg, 1548', 58990, 69995, 256, 9],
['P00749', 'img', 'Goya - El 3 de mayo de 1808 en Madrid: Los fusilamientos en la montaña del Príncipe Pío, 1814', 58689, 45252, 256, 8],
['P00809', 'img_recortada', 'El Greco - El caballero de la mano en el pecho, 1580', 12673, 16238, 256, 6],
['P01117', 'img', 'José de Ribera - El sueño de Jacob, 1639', 52560, 39755, 256, 8],
['P01174', 'meninas', 'Velázquez - La familia de Felipe IV, o Las Meninas, 1656', 42923, 49403, 256, 8],
['P01670', 'img', 'Rubens - Las Tres Gracias, 1635', 54654, 66596, 256, 9],
['P02132', 'img', 'Rembrandt - Artemisa, 1634', 36898, 34320, 256, 8],
['P02179', 'img', 'Durero, Alberto - Autorretrato, 1498', 19047, 24047, 256, 7],
['P02823', 'img', 'El Bosco - El jardín de las Delicias, 1500-1505', 156547, 89116, 256, 10],
['P02825', 'img', 'Roger van der Weyden - El Descendimiento, 1435', 90608, 70303, 256, 9],
['P07878', 'img', 'Juan de Flandes - La Crucifixión, 1509-1518', 69273, 50061, 256, 9],
];
var [cDir, cPreTile, cName, cMaxWidth, cMaxHeight, cSizeClip, cMaxZoom] = [0,1,2,3,4,5,6];

Array.prototype.random = function(){
	var rand = Math.floor(this.length * Math.random());
	return this[rand];
}
var cuadro = cuadrosArray.random();

var viewer = OpenSeadragon({
	id: "OpenSeadragonViewer",
	prefixUrl: "https://openseadragon.github.io/openseadragon/images/",
	showNavigator: !0,
	navigatorAutoResize: !0,
	navigatorAutoFade: !1,
	tileSources:   {
		// Prado: tilesOrigin="BOTTOM_LEFT", ArtProyect: tilesOrigin="TOP_LEFT"
		tilesOrigin: "BOTTOM_LEFT",
		width: cuadro[cMaxWidth],
		height: cuadro[cMaxHeight],
		tileSize: cuadro[cSizeClip],
		minLevel: 0,
		maxLevel: cuadro[cMaxZoom],
		getTileUrl: function( z, x, y ){

			var tiledImage = viewer.world.getItemAt(0); // Assuming it's the first image in the viewer. 
			tiledImage.setClip(new OpenSeadragon.Rect(0, 0, cuadro[cMaxWidth], cuadro[cMaxHeight]));

			y = this.getNumTiles(z).y - y - 1; // invert y
			return "https://mw2.google.com/mw-earth-vectordb/gallery_layers/prado/"+
			cuadro[cDir]+"/img/"+cuadro[cPreTile]+"_"+z+"_"+x+"_"+y+".jpg";
		}
	}
});
</script>
</div>
</body>
</html>
'

**Comment by metrogoldimeyer** [comment]
Thank you very much Ian.
Attachment code working correctly.
'
-------------[ changes in openseadragon-2.4.0.js ]-------------
getTileBounds: function( level, x, y, isSource ) {
var dimensionsScaled = this.dimensions.times( this.getLevelScale( level ) ),
tileWidth = this.getTileWidth(level),
tileHeight = this.getTileHeight(level),
px = ( x === 0 ) ? 0 : tileWidth * x - this.tileOverlap,
py = ( y === 0 ) ? 0 : tileHeight * y - this.tileOverlap,
sx = tileWidth + ( x === 0 ? 1 : 2 ) * this.tileOverlap,
sy = tileHeight + ( y === 0 ? 1 : 2 ) * this.tileOverlap,
scale = 1.0 / dimensionsScaled.x;

	// --- ini - Prado partial patch (openseadragon-2.4.0.js) ---
	if ( this.tilesOrigin === "BOTTOM_LEFT" ) {
		var numTiles = this.getNumTiles( level );
		var empty_pels_y = ( numTiles.y * tileHeight ) - dimensionsScaled.y;
		py = py - empty_pels_y;
	}
	// --- end - Prado partial patch (openseadragon-2.4.0.js) ---

    sx = Math.min( sx, dimensionsScaled.x - px );
    sy = Math.min( sy, dimensionsScaled.y - py );

    if (isSource) {
        return new $.Rect(0, 0, sx, sy);
    }

    return new $.Rect( px * scale, py * scale, sx * scale, sy * scale );
},

-------------[ html to view 14 masterpieces of the Prado Museum, Madrid ]-------------

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Custom Tile Source | OpenSeadragon 2.4.0</title>
	<link rel="stylesheet" type="text/css" media="screen" href="https://openseadragon.github.io/css/style.css">
	<style type="text/css">body, .openseadragon { background-color: #ffffff; }</style>
	<script src="https://openseadragon.github.io/openseadragon/openseadragon.js"></script>
</head>
<body>
    <div id="container">
    <div id="OpenSeadragonViewer" class="openseadragon"></div>
<script>
/**
   <TileInfo tile_width="256" tile_height="256" full_pyramid_depth="10" origin="BOTTOM_LEFT">
   <pyramid_level num_tiles_x="3" num_tiles_y="4" empty_pels_x="98" empty_pels_y="253" />
 
    tiles Prado z=2         tiles Art Project z=2
   +-----+-----+-----+      +-----+-----+-----+
   | 0,3 | 1,3 | 2,3 |      | 0,0 | 1,0 | 2,0 |
   +-----+-----+-----+      +-----+-----+-----+
   | 0,2 | 1,2 | 2,2 |      | 0,1 | 1,1 | 2,1 |
   +-----+-----+-----+      +-----+-----+-----+
   | 0,1 | 1,1 | 2,1 |      | 0,2 | 1,2 | 2,2 |
   +-----+-----+-----+      +-----+-----+-----+
   | 0,0 | 1,0 | 2,0 |      | 0,3 | 1,3 | 2,3 |
   +-----+-----+-----+      +-----+-----+-----+
   origin="BOTTOM_LEFT"     origin="TOP_LEFT"
*/
var cuadrosArray = [
// Dir    preTile  name maxWidth maxHeight sizeClip maxZoom
['P00015', 'img', 'Fra Angelico - La Anunciación, 1426', 86539, 85398, 256, 9],
['P00299', 'img', 'Rafael - El Cardenal, 1510', 33392, 43012, 256, 8],
['P00363', 'img', 'Tiepolo - Inmaculada Concepción, 1767-1769', 51952, 95470, 256, 9],
['P00410', 'img', 'Tiziano - El emperador Carlos V, a caballo, en Mühlberg, 1548', 58990, 69995, 256, 9],
['P00749', 'img', 'Goya - El 3 de mayo de 1808 en Madrid: Los fusilamientos en la montaña del Príncipe Pío, 1814', 58689, 45252, 256, 8],
['P00809', 'img_recortada', 'El Greco - El caballero de la mano en el pecho, 1580', 12673, 16238, 256, 6],
['P01117', 'img', 'José de Ribera - El sueño de Jacob, 1639', 52560, 39755, 256, 8],
['P01174', 'meninas', 'Velázquez - La familia de Felipe IV, o Las Meninas, 1656', 42923, 49403, 256, 8],
['P01670', 'img', 'Rubens - Las Tres Gracias, 1635', 54654, 66596, 256, 9],
['P02132', 'img', 'Rembrandt - Artemisa, 1634', 36898, 34320, 256, 8],
['P02179', 'img', 'Durero, Alberto - Autorretrato, 1498', 19047, 24047, 256, 7],
['P02823', 'img', 'El Bosco - El jardín de las Delicias, 1500-1505', 156547, 89116, 256, 10],
['P02825', 'img', 'Roger van der Weyden - El Descendimiento, 1435', 90608, 70303, 256, 9],
['P07878', 'img', 'Juan de Flandes - La Crucifixión, 1509-1518', 69273, 50061, 256, 9],
];
var [cDir, cPreTile, cName, cMaxWidth, cMaxHeight, cSizeClip, cMaxZoom] = [0,1,2,3,4,5,6];

Array.prototype.random = function(){
	var rand = Math.floor(this.length * Math.random());
	return this[rand];
}
var cuadro = cuadrosArray.random();

var viewer = OpenSeadragon({
	id: "OpenSeadragonViewer",
	prefixUrl: "https://openseadragon.github.io/openseadragon/images/",
	showNavigator: !0,
	navigatorAutoResize: !0,
	navigatorAutoFade: !1,
	tileSources:   {
		// Prado: tilesOrigin="BOTTOM_LEFT", ArtProyect: tilesOrigin="TOP_LEFT"
		tilesOrigin: "BOTTOM_LEFT",
		width: cuadro[cMaxWidth],
		height: cuadro[cMaxHeight],
		tileSize: cuadro[cSizeClip],
		minLevel: 0,
		maxLevel: cuadro[cMaxZoom],
		getTileUrl: function( z, x, y ){

			var tiledImage = viewer.world.getItemAt(0); // Assuming it's the first image in the viewer. 
			tiledImage.setClip(new OpenSeadragon.Rect(0, 0, cuadro[cMaxWidth], cuadro[cMaxHeight]));

			y = this.getNumTiles(z).y - y - 1; // invert y
			return "https://mw2.google.com/mw-earth-vectordb/gallery_layers/prado/"+
			cuadro[cDir]+"/img/"+cuadro[cPreTile]+"_"+z+"_"+x+"_"+y+".jpg";
		}
	}
});
</script>
</div>
</body>
</html>
'
