### ISSUE TITLE
areControlsEnabled: Typo in src/viewer.js 

### ISSUE THREAD

**Issue by 96dpi** [openseadragon/openseadragon#1557]
When I tried to use setControlsEnabled(false) I encountered an error in release 2.4.0.
`
[Error] TypeError: this.controls[e].isVisibile is not a function. (In 'this.controls[e].isVisibile()', 'this.controls[e].isVisibile' is undefined)
	areControlsEnabled (openseadragon.min.js:8:66339)
	(anonyme Funktion) (main.js:173)
	dispatch (jquery-3.3.1.min.js:2:41778)
`

Changing the function areControlsEnabled from `isVisibile()` to `isVisible()` fixed this. I think that this might be an unintended error.

https://github.com/openseadragon/openseadragon/blob/f6559e6c170e4429417a55ff9b7a6219f323e7e5/src/viewer.js#L838

**Comment by iangilman** [comment]
Good catch! Would you be up for making a patch to fix it?

**Comment by 96dpi** [comment]
Thanks. I'll try to create a patch. This is the first time I reported an issue at Github, so I am not 100% sure if this approach is correct. Please excuse my newbie question:

I created a fork, commited the change and created a pull request afterwards. Is this ok?

**Comment by iangilman** [comment]
Yes, you did it perfectly! Thank you :) 

Just one minor suggestion: I see you mentioned this issue in your commit, but it would also be good to include the issue number in the pull request description too, to make it easy to get back and forth. 

Closing now; fixed by #1562.
