### ISSUE TITLE
First loaded tiles are NOT async.

### ISSUE THREAD

**Issue by ucyildirim** [openseadragon/openseadragon#1558]
Hi there,

All of the tiles are loaded **synchronously** on first init.
But the tiles from panning / zooming are loaded **asynchronously**.

Is there any option / way to make first tiles load **async**?

Best regards.

![first init](https://user-images.githubusercontent.com/38659860/47786337-8a111c00-dd1c-11e8-9e23-7a3698c0e53b.png)
![zoom and pan](https://user-images.githubusercontent.com/38659860/47786338-8a111c00-dd1c-11e8-915f-3fb5104f9da6.png)

**Comment by iangilman** [comment]
What kind of tile source are you using? Are you using more than one? Why does it load a text file between each tile? That's not expected with a single DZI at least. 

Here's a snap of the network view of the initial load on openseadragon.github.io (with network throttling on so it's easier to see what it's doing): 

![image](https://user-images.githubusercontent.com/338989/47803692-4e605d00-dcf0-11e8-8661-8f0c260b9e7f.png)

As you can see it's definitely loading tiles simultaneously. 

There must be something about your tile source that's creating this serial loading, and I suspect it may have to do with those text files.
