### ISSUE TITLE
Cancel unnecessary tile requests. 

### ISSUE THREAD

**Issue by ucyildirim** [openseadragon/openseadragon#1559]
Hi all,

I'm working with very large images. 
IF I pan / zoom sequentially, too many tile requests are being queued. 
Is there a way to cancel unnecessary tiles ? (Like 'the tiles that are not visible')

Best regards.

**Comment by iangilman** [comment]
You should be able to cancel pending tile requests manually using `viewer.imageLoader.clear()` if you want (as mentioned in https://github.com/openseadragon/openseadragon/issues/1327). You can also create your OpenSeadragon viewer with `imageLoaderLimit: 1` or something so it doesn't start a lot of simultaneous requests.

**Comment by grehh** [comment]
Perhaps an relevant note: 

If the value for `imageLoaderLimit` is not setted, than the default is 0 and no requests to clear are registered. In this case the calling of `viewer.imageLoader.clear()` has no effect. 

But: It seems that this issue occurred in the version 5.0.1 and earlier. Meanwhile it seems to be solved with the commit:
https://github.com/openseadragon/openseadragon/commit/cdb89ff5adaf64af8912c3e6ada1550184989b3f

**Comment by iangilman** [comment]
@grehh Thanks for pointing this out!
