### ISSUE TITLE
Tile failed for IIIF image server zoom

### ISSUE THREAD

**Issue by AK-Bharath** [openseadragon/openseadragon#1565]
Hi There,

I am getting this following error on the console of the browser.  

``
 Tile $.Tile failed to load: http://54.252.86.234/iiif/11f41b56-bcde-4772-a6cd-b18c9debace7/full/625,/0/default.jpg - error: Image load aborted
``
Please help me in resolving this issue.

With Many thanks,

Bharath AK

**Comment by AK-Bharath** [comment]
I am sorry to say I can't share the repository it is not opensource.

**Comment by iangilman** [comment]
Can you share the IIIF image link itself (not for the individual tile, but the whole image)? The issue probably has something to do with the specific image.

BTW, when I try that tile link in my browser (http://54.252.86.234/iiif/11f41b56-bcde-4772-a6cd-b18c9debace7/full/625,/0/default.jpg), I get a 401 (not authorized). Is that what you're getting, or can you see the image (because you're logged in)?

**Comment by AK-Bharath** [comment]
Hi
IIIFImage server is running on a docker.  for working image http://54.252.92.17/iiif/8a75b02d-248d-466b-9b10-aa50350f74a9/full/!1150,768/0/default.jpg.  

non-working image is http://54.252.92.17/iiif/11f41b56-bcde-4772-a6cd-b18c9debace7/full/!1138,768/0/default.jpg

console logs for non-working image is 

default.jpg:1 GET http://54.252.86.234/iiif/11f41b56-bcde-4772-a6cd-b18c9debace7/full/625,/0/default.jpg 404 (NOT FOUND)
Image (async)
start @ search-ba25d23859b2f575ecdf.js:78485
addJob @ search-ba25d23859b2f575ecdf.js:78558
loadTile @ search-ba25d23859b2f575ecdf.js:83157
_updateViewport @ search-ba25d23859b2f575ecdf.js:82787
draw @ search-ba25d23859b2f575ecdf.js:82021
draw @ search-ba25d23859b2f575ecdf.js:84271
drawWorld @ search-ba25d23859b2f575ecdf.js:72595
updateOnce @ search-ba25d23859b2f575ecdf.js:72547
updateMulti @ search-ba25d23859b2f575ecdf.js:72470
(anonymous) @ search-ba25d23859b2f575ecdf.js:71742
requestAnimationFrame (async)
$.requestAnimationFrame @ search-ba25d23859b2f575ecdf.js:64962
scheduleUpdate @ search-ba25d23859b2f575ecdf.js:71741
(anonymous) @ search-ba25d23859b2f575ecdf.js:69675
(anonymous) @ search-ba25d23859b2f575ecdf.js:65372
raiseEvent @ search-ba25d23859b2f575ecdf.js:65394
addItem @ search-ba25d23859b2f575ecdf.js:84119
processReadyItems @ search-ba25d23859b2f575ecdf.js:70782
(anonymous) @ search-ba25d23859b2f575ecdf.js:70818
success @ search-ba25d23859b2f575ecdf.js:71614
(anonymous) @ search-ba25d23859b2f575ecdf.js:73767
(anonymous) @ search-ba25d23859b2f575ecdf.js:65372
raiseEvent @ search-ba25d23859b2f575ecdf.js:65394
callback @ search-ba25d23859b2f575ecdf.js:74091
success @ search-ba25d23859b2f575ecdf.js:74113
request.onreadystatechange @ search-ba25d23859b2f575ecdf.js:64541
XMLHttpRequest.send (async)
makeAjaxRequest @ search-ba25d23859b2f575ecdf.js:64571
getImageInfo @ search-ba25d23859b2f575ecdf.js:74107
$.TileSource @ search-ba25d23859b2f575ecdf.js:73819
(anonymous) @ search-ba25d23859b2f575ecdf.js:71606
setTimeout (async)
getTileSourceImplementation @ search-ba25d23859b2f575ecdf.js:71603
addTiledImage @ search-ba25d23859b2f575ecdf.js:70813
doOne @ search-ba25d23859b2f575ecdf.js:69997
open @ search-ba25d23859b2f575ecdf.js:70002
$.Viewer @ search-ba25d23859b2f575ecdf.js:69788
OpenSeadragon @ search-ba25d23859b2f575ecdf.js:63063
_updateImage @ search-ba25d23859b2f575ecdf.js:24989
componentDidMount @ search-ba25d23859b2f575ecdf.js:25013
(anonymous) @ search-ba25d23859b2f575ecdf.js:41652
measureLifeCyclePerf @ search-ba25d23859b2f575ecdf.js:41463
(anonymous) @ search-ba25d23859b2f575ecdf.js:41651
notifyAll @ search-ba25d23859b2f575ecdf.js:20660
close @ search-ba25d23859b2f575ecdf.js:43577
closeAll @ search-ba25d23859b2f575ecdf.js:9310
perform @ search-ba25d23859b2f575ecdf.js:9257
perform @ search-ba25d23859b2f575ecdf.js:9244
perform @ search-ba25d23859b2f575ecdf.js:2067
flushBatchedUpdates @ search-ba25d23859b2f575ecdf.js:2150
closeAll @ search-ba25d23859b2f575ecdf.js:9310
perform @ search-ba25d23859b2f575ecdf.js:9257
batchedUpdates @ search-ba25d23859b2f575ecdf.js:43251
batchedUpdates @ search-ba25d23859b2f575ecdf.js:2075
dispatchEvent @ search-ba25d23859b2f575ecdf.js:43407
search-ba25d23859b2f575ecdf.js:83185 Tile $.Tile failed to load: http://54.252.86.234/iiif/11f41b56-bcde-4772-a6cd-b18c9debace7/full/625,/0/default.jpg - error: Image load aborted

there is no login required.  I have to run my application(ntdl - it is not running in docker) to list all images as thumbnails. once I click the image iiifimage server displays the image. once again if I click it loads in openseadragon with zoom.

my ntdl is application is not running on a docker where as iiifimage server is running on docker.
there is info.json on IIIF
and the link is http://54.252.92.17/iiif/11f41b56-bcde-4772-a6cd-b18c9debace7/info.json
the above link is for non-working 
the working image info.json is

http://54.252.92.17/iiif/8a75b02d-248d-466b-9b10-aa50350f74a9/info.json  

I dont know much about iiifimageserver as well as openseadragon.

Please help me in resolving this issue.

With many thanks,
Bharath AK

**Comment by xgui3783** [comment]
Might be related to this issue?
https://github.com/openseadragon/openseadragon/issues/1561#issuecomment-434781902

**Comment by iangilman** [comment]
@xgui3783 Good thought! I don't think @AK-Bharath is using level 0, though (but I could be wrong). 

@AK-Bharath I don't think the missing number (the way OSD constructs the URL) is a problem. Presumably by leaving the height off it's telling the server to provide whatever height it has. You can test this by taking your working URL: 

http://54.252.92.17/iiif/8a75b02d-248d-466b-9b10-aa50350f74a9/full/!1150,768/0/default.jpg

... and removing the exclamation point (which presumably means "exact size") and the height number, and it still works:

http://54.252.92.17/iiif/8a75b02d-248d-466b-9b10-aa50350f74a9/full/1150,/0/default.jpg

The big difference I am seeing is the IP address. All of your working images are served on 54.252.92.17 and your broken images are served on 54.252.86.234. Perhaps you've just mixed up your servers?

**Comment by AK-Bharath** [comment]
Hi Iangilman,

I think what you say is correct, the ip address 54.252.86.234 is our demo machine ipaddress.  I think there lies the problem.  and also in info.json, id  has 54.252.86.234 ipaddress,  I have no idea why info.json is used and where it is set and loaded.   I will try to find the issue and fix it.   Thank you so much for identifying the issue.

With Many thanks,
Bharath AK

**Comment by AK-Bharath** [comment]
Hi Ian Gilman,

Could you please remove all the IP address references in this issue for security reasons.  or fake the IP address or change the IP address with '*'

with many thanks,
Bharath AK
