### ISSUE TITLE
Combine behaviors of pixelFromPoint() and pixelFromPointNoRotate()?

### ISSUE THREAD

**Issue by elby22** [openseadragon/openseadragon#1566]
I'm using the SVG Overlay plugin to display annotations over an image which rotate, scale and translate with the image. The implementation in the plugin creates a translation transform with something like 
```
p  = viewer.viewport.pixelFromPoint(new OpenSeadragon.Point(0, 0), true)
this._node.setAttribute('transform', 'translate(' + p.x + ',' + p.y + '));

```
I have another "static" layer which i've extended the plugin to only scale and translate with the image because I don't want these annotations to rotate. When rotating the canvas using the same translation logic as the other layer (using pixelFromPoint), my annotations in the static layer will move and scale with the others and not rotate, as expected. But when I rotate the canvas they move about as if they were being rotated.
However when I use` pixelFromPointNoRotate()` to translate my static layer, the annotations move differently than the other layer (opposite when rotation == 180) but maintain the desired position when rotating. 
Is there a way to get the desired effects from both of these methods? As I play with the source code, I can manage to get one, the other, or neither, but not both of the behaviors I want for my static SVG layer.

**Comment by iangilman** [comment]
@avandecreme @nelsonn3c You guys know this part of the code better than I... any thoughts?

**Comment by nelsonn3c** [comment]
@antonioxdias

**Comment by nelsonn3c** [comment]
@antonioxdias may have faced some of this issues on his annotations plugin =) Anyway, I will try to see it

**Comment by antonioxdias** [comment]
I'm not really sure if i fully understood the question, but if you are using osd overlays and want them to not rotate with the canvas, while maintaining one same reference point, isn't the behavior shown here the one you are looking for?

[http://openseadragon.github.io/examples/ui-overlays/](http://openseadragon.github.io/examples/ui-overlays/)

On the _Overlays and rotation_ section take a look at the red arrow example.
