### ISSUE TITLE
collection mode - collectionTileMargin:0 still has margin between images

### ISSUE THREAD

**Issue by quiltTooShort** [openseadragon/openseadragon#1568]
Hi,

I'm trying to use collectionMode with multiple images and I want the margin between them to be zero or very small.  I'm currently using the most recent release (2.4) and I've done a lot of google searches about this issue and thought i was resolved with https://github.com/openseadragon/openseadragon/pull/446.
I've looked at the following examples and the problem does not exist:
https://bl.ocks.org/fabiovalse/7705d5acb1cdd8678d39a74031e07580
http://iangilman.com/osd/test/demo/m2/

So obviously I'm doing something wrong and I'm about to lose whatever hair I have left :(
I've tried passing x and y coordinates and these seem non-responsive no matter what I set it to.  Also, I'm using simple jpg images and not dzi if that makes any difference.  Any help/guidance is much appreciated.  Thanks.

Here is how I instantiate OSD:
			var viewer = OpenSeadragon({
				id:            "osd",
				prefixUrl:     "/includes/js/openseadragon-bin-2.4.0/images/",
				constrainDuringPan: true,
				visibilityRatio: 1,
				blendTime: 0.2,
				zoomPerClick: 1.5,
				nextButton:     "nextPage",
				previousButton: "previousPage",			
				preserveViewport: true,
				collectionMode:       true,
				collectionRows:       1,
				collectionTileSize: 256,
				collectionTileMargin: 0,
				tileSources: imageSource
			});

**Comment by iangilman** [comment]
Are your images square? If not, there will always be gaps between them using collectionMode, since it puts the images in a square grid, centering each image in its grid cell. 

If that's not the issue, can you share a screenshot or a link?

**Comment by iangilman** [comment]
I might add: the collectionMode arrangement is pretty naive... if you want something more relevant to your needs, you might want to build one yourself. Here's the code that collectionMode uses:

https://github.com/openseadragon/openseadragon/blob/master/src/world.js#L321

You basically just go through each of the images and set its position however you want.

**Comment by quiltTooShort** [comment]
Thanks for the quick response.  Okay, that explains it, my images are not squares.  It's like a portrait where the height is bigger than the width.  I will look into modifying the code in arrange function.  Just a quick question about the coordinates (x,y, width, height, position) used in the function, are these measured in px?

**Comment by iangilman** [comment]
Good question! No, they are in viewport coordinates, which is an arbitrary coordinate system. 

http://openseadragon.github.io/examples/viewport-coordinates/

That said, since it's arbitrary, you can define it however you want. Just use `setWidth` on your tiledImages and that's how wide they are in viewport coordinates.
