### ISSUE TITLE
defaultZoomLevel

### ISSUE THREAD

**Issue by ArekZGate3** [openseadragon/openseadragon#1571]
Was wondering if any one is expericing an issue with the defaultZoomLevel and minZoomLevel. 
I wanted to be able to zoom a bit out and start at defaultZoomLevel: 1, but when I set minZoomLevel: .5. My viewer loads at .5 instead of 1.  Options are below and I used the npm to download.
{
          id: "openseadragon",
          showNavigator:  true,
          showNavigationControl: false,
          visibilityRatio: 1,
          constrainDuringPan: true,
          defaultZoomLevel: 1,
          minZoomLevel: 0.5,
          maxZoomLevel: 10,
          tileSources: {
            type: 'legacy-image-pyramid',
            levels:[
              {
                url: ...,
                height: 20000,
                width: 28000,
              },
            ],
          },
        }

**Comment by iangilman** [comment]
Hmm... Seems like it should work as you expect. Can you share a repro, like a CodePen?

**Comment by ArekZGate3** [comment]
I was not able to replicate in CodePen.  I moved it in my code and worked as expected. There is an issue with vue-carousel that I was using it with. Thank You.

**Comment by iangilman** [comment]
I see. Thanks for reporting back!
