### ISSUE TITLE
Overlay height:1 is equal in pixels to width:1

### ISSUE THREAD

**Issue by CezCz** [openseadragon/openseadragon#1572]
With such setup:
```
overlays: [{
    id: 'example-overlay',
    x: 0,
    y: 0,
    width: 1,
    height: 1,
    className: 'irrelevant'
 }]
```

It results in such overlay:
![image](https://user-images.githubusercontent.com/11783702/49503094-eb299380-f876-11e8-9b41-6ce4c6607f69.png)

It is related to the fact that height:1 means equal to width:1.
You can see on [overlay examples page](https://openseadragon.github.io/examples/ui-overlays/) in the very first sample the same behaviour. When analysing the image you can get impression that x,y should be bottom left corner, but in fact it is top left.

I debugged the problem and found out that it due to 
```
var scaledSize = viewport.deltaPixelsFromPointsNoRotate(
                    new $.Point(this.width || 0, this.height || 0), true);
```
in __getSizeInPixels_ in _overlay.js_

Which looks like that:
```
deltaPixelsFromPointsNoRotate: function(deltaPoints, current) {
        return deltaPoints.times(
            this._containerInnerSize.x * this.getZoom(current)
        );
    }
```

Then both points in deltaPoints get multiplied by _containerInnerSize.x. 

Is this intended behaviour? I was looking through documentation and found no mention of it anywhere.

In case you would like to do it in a way where height:1 is equal to image height I'd be glad to implement it.

Best regards

**Comment by iangilman** [comment]
Yes, the overlay is specified in viewport coordinates. If you prefer the viewport coordinates to be something different, you can specify that when you create the image. For instance, if you want 1 to be the height, you can do this:

```
var viewer = OpenSeadragon({
  tileSources: {
    tileSource: myTileSource,
    height: 1
  },
  // Additional properties go here
});
```
