### ISSUE TITLE
How to cut TIF image with deep zoom?

### ISSUE THREAD

**Issue by JerryGit1** [openseadragon/openseadragon#1573]
Hello, we tried this framework and found it very good. Our server got 5G TIF images, and the back end was python. Because the images are too big to be converted to jpg, how to cut TIF images with deep zoom? Or give me a suggestion. Thanks

**Comment by iangilman** [comment]
Many of the tools here should work:

http://openseadragon.github.io/examples/creating-zooming-images/

I generally prefer VIPS, and I know it supports TIF.

**Comment by JerryGit1** [comment]
Thank you very much for your reply. I have been studying this problem recently, and it has been solved now. My solution is to use the OpenSeadragon Canvas Overlay HD plug-in. Firstly, the 5G map is divided into six blocks, and then cut separately. Finally, we use this plug-in to stitch up the complete picture.

**Comment by iangilman** [comment]
Clever solution! Thank you for letting us know how you got it working :)
