### ISSUE TITLE
How can I get viewport coordinates of visible part of image relative to the BottomLeft point of the Image

### ISSUE THREAD

**Issue by ysmanohar** [openseadragon/openseadragon#1580]
Hello,
    I have tried some of the methods like bounds.getTopLeft() & bounds.getBottomLeft() but they are giving coordinates relative to the Top Left Point of the Image. But I need those coordinates relative to the Bottom Left. I tried to do some Math around that but I'm unable to get the height of the Image during various actions like (pan & Zoom). Could you please tell me? Really appreciate for your response!

**Comment by iangilman** [comment]
I'm not sure I understand exactly what you're asking for, but perhaps this example will help:

```
var viewportBounds = viewer.viewport.getBounds();
var tiledImage = viewer.world.getItemAt(0); // Assuming you're interested in the first image
var imageBounds = tiledImage.getBounds(); 
var intersection = viewportBounds.intersection(imageBounds);
if (intersection) {
  var intersectionBottomLeft = intersectionBounds.getBottomLeft();
  var imageBottomLeft = imageBounds.getBottomLeft();
  var x = imageBottomLeft.x - intersectionBottomLeft.x;
  var y = imageBottomLeft.y - intersectionBottomLeft.y;
}
```

**Comment by ysmanohar** [comment]
Thanks @iangilman . It has solved most of my problem.
When I rotate an Image to 90clockwise, I see that even the origin (0,0) is also rotating with the Image. 
After 90clockwise rotation now the origin is Top Right of rotated Image.
Is there a possibility to make the Top Left as origin of an Image irrespective of rotation???

**Comment by iangilman** [comment]
I actually don't know that much about rotation in OpenSeadragon, but I think the viewport and image bounds are properly rotated (note that the rectangle object has a `degrees` property for rotation). The `intersection` call, however, removes the rotation, giving you the smallest un-rotated rectangle that contains the intersection. You might play around with creating your own intersection function and/or paying attention to the degrees of the two bounds.

Also be aware you can either rotate the viewport or the image; I'm not sure which would serve your purposes better. Also note that you can call `getBoundsNoRotate` on either to get their un-rotated versions, if that would be of help in your calculations.

**Comment by ysmanohar** [comment]
New year greetings @iangilman . If I have an Image inside the viewport & I rotate the viewport, I see that the Image is getting rotated but If I check the Image Bounds, I still the rotation as 0. Can you please confirm If this is an expected scenario or Am I doing something wrong??
I was excepting the viewport bounds and Image bounds would be in Sync.

**Comment by iangilman** [comment]
I could be wrong, but I believe that is expected. Think of the viewport as a camera. If you've rotated the camera it doesn't mean all of the images are rotated... the images are still wherever you left them.
