### ISSUE TITLE
Change tooltip icons?

### ISSUE THREAD

**Issue by adoniscyp** [openseadragon/openseadragon#1582]
Hey, 

How can we easily change the tooltip icons?

The only documented tooltip API that I could find is: OpenSeadragon.setString("Tooltips.PreviousPage", "Previous page dude!");

Would like to use the flat icons from: https://github.com/peterthomet/openseadragon-flat-toolbar-icons

Thanks

**Comment by iangilman** [comment]
You mean you just want to use different toolbar icons? The tool tips themselves are just bits of text. 

Anyway, just grab the flat icons and point to them using `prefixUrl`. There shouldn't be any additional configuration needed.
