### ISSUE TITLE
Show data from info.json in external div on thumbnail click

### ISSUE THREAD

**Issue by bonaventure** [openseadragon/openseadragon#1584]
I'm able to successfully load images from a Cantaloupe image server into OpenSeadragon. Is there any way to pull data from each info.json as each thumbnail is clicked and show it (or push it) in(to) a div outside of the OpenSeadragon viewer? For example, if there are 100 tileSources in the viewer, I'd like to be able to display the URI for info.json in an external div. This would allow us to evaluate large batches of images in OpenSeadragon and quickly identify the info.json source for select images in the collection. Ultimately, I'm trying to create a sorting room so that we can use the elements of info.json to create a manifest for use in Mirador or the Universal Viewer. 

Although not directly related to OpenSeadragon, I'm just as interested in this feature for UV or Mirador (or any of the IIIF viewers). In other words, it would be great to be able to associate image annotations (transcriptions, metadata, image data, etc.) to HTML content outside of the viewer.

**Comment by iangilman** [comment]
Take a look at `viewer.world.getItemAt(0).source` and see if the info you want is there. For instance, there's `@id` and `profile`. If not, perhaps we need to update the IIIFTileSource to retain more information.

**Comment by bonaventure** [comment]
@iangilman It seems simple on the surface, but I don't know javaScript well enough to do it quickly. Is there a chance I could pay you help me do this, even if its simple (I prefer to support any help I get, when appropriate...I assume I can donate through your website, yes)? For starters I need to figure out how to write the source for each image when clicked (in my case they will be info.json urls). Eventually I'd like to have a button that will allow our curator to add the url to an array field in my content construction kit for my CMS. I can tackle that after I figure out how to get the value. I hope this makes sense. I'd be happy to chat via Slack or other if its easier. 

Here's an example of my openSeadragon application. I don't have any javascript for the class "imageSource"...I just put it there so you can see where I want to render the source url as each thumbnail is clicked. I can always move it later (or add it to a button, etc.). 

```
<body>
  <div class="row">
  <div class="col-12" id="toolbarDiv" style="height: 50px; background-color: #000;"></div>
  <div class="col-12" id="openseadragon1" style="width: 100%; height: 800px; background-color: #000;"></div>
  <div class="imageSource">This is where the source url will print</div>
  </div>

<script src="openseadragon/openseadragon.min.js"></script>
<script type="text/javascript">
    var viewer = OpenSeadragon({
        id: "openseadragon1",
        sequenceMode: true,
        showReferenceStrip: true,
        referenceStripScroll: 'vertical',
        toolbar: "toolbarDiv",
        tileSource: "source1",
        showNavigator: true,
        navigatorBackground: '#000',
    tileSources: ["https://iiif-image-server-url.firstImage.jp2/info.json",
        https://iiif-image-server-url.secondImage.jp2/info.json",
        https://iiif-image-server-url.thirdImage.jp2/info.json",
        ...
        ]
});
let tileSource = viewer.world.getItemAt(0).source;
</script>
</body>
```

**Comment by iangilman** [comment]
@bonaventure Sure, we can get you some hands on help. In fact @msalsbery is probably a good choice; he's quite familiar with OSD, and I believe he's got more available time than I at the moment. You can find us both on Gitter: 

https://gitter.im/openseadragon/openseadragon

... And we can chat further :)

**Comment by bonaventure** [comment]
@msalsbery  and @iangilman 
Thank you both for your help. @msalsbery code was enough for me to see how to grab the id. Now I can start playing with how to apply it to my sorting room for iiif manifests. I'll be in touch via Gitter. Hopefully @msalsbery can help. Thanks again. 
```
viewer.addHandler('open', function (event) {
	var tileSource = viewer.world.getItemAt(0).source;		
	document.getElementById("image-source").innerHTML = "Image Source: " + tileSource["@id"] + "/info.json";
```
