### ISSUE TITLE
Overlay lags when zooming or panning on image

### ISSUE THREAD

**Issue by hcwong** [openseadragon/openseadragon#1585]
Hey,

I was trying to implement an overlay on top of an image in Angular. However, when I pan or zoom in on the image, the overlay box lags and takes a while before updating and moving itself to the correct position. Thanks! I've attached my code below.

````
// style.scss
.highlight {
  outline: 1px solid blue;
}

//image.component.ts
 this.viewer = osd({
    id: 'seadragon-viewer',
    prefixUrl: '../../../assets/zoom-image/',
    tileSources: this.image_url,
    overlays: [{id: "overlay1", x: 0.3, y: 0.4, width: 0.1, height: 0.1, className: 'highlight'}]
  });
````

**Comment by iangilman** [comment]
Hmm... your code looks reasonable. Are you getting the same sort of lag on this page? 

http://openseadragon.github.io/examples/ui-overlays/

If so, what device/browser are you using? If not, can you share a link to a repro of your issue?

**Comment by hcwong** [comment]
Actually, it the ui-overlay page runs smoothly on Chrome. But, I'm using openseadragon for an electron project.
Also, the image I'm using is extremely big. Could this be a possible reason for the lag? Thanks!

**Comment by iangilman** [comment]
What sort of tile source is it? Is it a tiled image like DZI or IIIF, or are you using the simple image or legacy tilesource? If it's the latter of the options, then yes, the size could make a big difference.

**Comment by hcwong** [comment]
It's a DZI. Thanks!

**Comment by iangilman** [comment]
Hmm... Even a gigantic DZI shouldn't cause slowness in animation. 

Are you able to run your page outside of Electron? Does it behave differently there? Perhaps it's somehow related to being in Electron, though I'm not sure what difference it would make.

**Comment by iangilman** [comment]
Your overlay is just an empty div with some color, right? That's what your code implies, but I thought I should verify...
