### ISSUE TITLE
Dragging image with overlay with MouseTracker

### ISSUE THREAD

**Issue by CezCz** [openseadragon/openseadragon#1586]
I have an overlay on an image. When MouseTracker is added to track the overlay's events, image is no longer draggable when dragging from within an overlay. 

Please see http://jsfiddle.net/EQz34/70/ (drag each box)

Error:
![image](https://user-images.githubusercontent.com/11783702/50694690-ddfcf180-103a-11e9-93a0-98c7ec757743.png)

**Comment by CezCz** [comment]
Google Chrome 71.0.3578.98 64-bit

**Comment by CezCz** [comment]
I have investigated the problem further. I found out that I have two issues here rather than one, namely:

1. I didn't expect an overlay to be draggable handled by browser mechanisms (link appears) 
2.  I expected whole image to be draggable, when I didn't explicitly provide override for onPress event

Ad 1.
This happens only when providing an id when creating overlay, not an actual element. OSD created `<a>` element with `"href"` attribute, this is handled by browser in a way that is draggable. When you drag such an element link appears and `pointercancel` event is dispatched. Error is caused because **mousetracker.onPointerCancel:2472** function lacks `currentPos: getMouseAbsolute( event )` in `gPoint` initialization. `currentPos` is later used by **mousetracker.updatePointersUp:2940** in **mousetracker.getPointRelativeToAbsolute**. I didn't find any particular need for this element to be `<a>` is there any? This error never happens when it is not an <a> since we need `pointercancel` to be emitted.

Ad 2.
This doesn't happen as when we create new MouseTracker all events are overridden old trackers are still registered but event is prevented from bubbling (haven't tracked where). If we don't provide any function for given functionality a default one is being presented. In order to canvas dragging working correctly we need adequate pressHandler_(*)_, however default one is an empty one **pressHandler:468** in mousetracker.js.
As a mitigation I thought I could pass **viewer.onCanvasPress:2944** however this seems to be a private function

_*_ why we need pressHandler in order to canvas drag to work
We need this function to be called in **mousetracker.updatePointersDown:2824** in order for drag to work correctly later. I haven't investigated what happens in pressHandler, however this is the only difference between draggable and not draggable solution.

What could we do:

Ad 1.
- Add `draggable="false"` attribute to <a> element created by OSD
- Add `currentPos: getMouseAbsolute( event )`

2.
- Make set of canvas functions public, so parent behaviour can be preserved manually
- Do not override parent handlers if not provided

**Comment by msalsbery** [comment]
@CezCz 

In the meantime...have you looked at (or tried using) the [OpenSeadragonViewerInputHook](https://github.com/msalsbery/OpenSeadragonViewerInputHook) plugin? It allows you to attach to any MouseTracker instance and insert handlers AHEAD of any handlers already attached to the tracker (the hook handlers get called first) so you have a chance to prevent further handlers from being called. It doesn't help with the original DOM events, but can be helpful for certain scenarios...

**Comment by CezCz** [comment]
@msalsbery 

Thanks for quick response. There's some hope for consistent event model since microsoft favoured Chromium. We have to believe ;). 

**mousetracker.onPointerCancel:2472** is being invoked after trying to drag `<a>` element that is an overlay. 

Function initializes gPoint in such way 

```
gPoint = {
            id: event.pointerId,
            type: getPointerType( event )
        };
```

Later it invokes two event handlers
```
updatePointersUp
updatePointersExit
```
In `updatePointersUp` on **mousetracker.updatePointersUp:2939** we invoke `getPointRelativeToAbsolute` with parameter `gPoints[0].currentPos` where `gPoints[0]` is our earlier created object. `currentPos` is undefined thus when invoking `return point.minus( offset );` in **mousetracker.getPointRelativeToAbsolute:1561** it throws an error.

From what I've seen it doesn't necesarily break anything from users point of view, but is a first culprit when you think image should move on drag.

Thank you for saying about OpenSeadragonViewerInputHook, I'll certainly take a look at it.

By the way, I'll be happy to contribute some coding work.

**Comment by msalsbery** [comment]
> There's some hope for consistent event model since microsoft favoured Chromium. We have to believe

@CezCz  ...and recently discovered pointer events model in development on WebKit. Hard to believe, but could actually come to Safari!?

**Comment by msalsbery** [comment]
@CezCz 

Now that #1872 has landed, it should be much easier to get control of the pointer events

[Here's a CodePen](https://codepen.io/msalsbery/pen/dyOeXqO) that shows what can be done...

**Comment by msalsbery** [comment]
[This CodePen](https://codepen.io/msalsbery/pen/dyOeXqO) should demonstrate use cases for handling events on overlays.

Closing this...feel free to reopen if there's still an issue!
