### ISSUE TITLE
chang the viewport navigator 

### ISSUE THREAD

**Issue by yz-novice** [openseadragon/openseadragon#1588]
hello,I am a student from China.And now I've met a problem with openseadragon.
First I've initialized the viewer and the tilesource has the unique value.
The problem is that if I can change the tilesource when I click a button.

**Comment by msalsbery** [comment]
@575900931 you found a solution or did you close this issue accidentally?

**Comment by 575900931** [comment]
@msalsbery Thank you for your reply .Actually，it's my problem.I've not seen the API doc carefully.Yes,I've found a way to solve it.I'm sorry to trouble you,

**Comment by 575900931** [comment]
@msalsbery now I've met a new issue.If I can use a new tileSource to replace the original tileSource that when I initialize the viewer?

**Comment by 575900931** [comment]
@msalsbery  ok,ok,ok I got it.I forget to remove the original tileSource.If I often communicate with you, I think it will be very helpful to improve my English.Thank you again.

**Comment by iangilman** [comment]
:) Keep up the good work!

**Comment by 575900931** [comment]
@iangilman  Thank you for your reply.To be honest ,I am a newbie.And now I want to know if there provided a way to chang the viewport navigator？like this:
![issue](https://user-images.githubusercontent.com/32389287/51423167-8f348780-1bf6-11e9-91d1-5475e03ed2b0.jpg)
if i can use the heatMap to replace the original?I think it's a good idea.

**Comment by iangilman** [comment]
So you want the navigator to be showing a different image than the viewer? That's not directly supported, but if you're willing to dig into it I'm sure it could be done. The navigator is actually just a little viewer, so you could potentially just call `viewer.navigator.open` with a different tileSource once the main viewer is created (watch for the main viewer's open event). For example:

```
var viewer = OpenSeadragon({
    tileSources: originalTileSource,
    showNavigator: true,
    // ... 
});

viewer.addHandler('open', function() {
  viewer.navigator.open(heatmapTileSource);
});
```

I haven't tested that code, so I don't know if it works, but it should give you the idea.

**Comment by 575900931** [comment]
@iangilman 
Thank you for your reply.I've tried the way you provided me but it didn't work. It's still the original tilesource.Maybe I did something wrong,and I hope you check it for me.Thank you again。
![1](https://user-images.githubusercontent.com/32389287/51511939-5555c200-1e3e-11e9-9f46-d4cb2c2d50e9.png)
![2](https://user-images.githubusercontent.com/32389287/51511947-5850b280-1e3e-11e9-8bb9-d18d608c9419.png)

**Comment by iangilman** [comment]
Sure enough... it took a little more than that. I've now tested some code that seems to work:

https://codepen.io/iangilman/pen/MLYWKK

Here's the key bit:

```
viewer.addHandler('open', function() {
  var tiledImage = viewer.world.getItemAt(0);
  viewer.navigator.addTiledImage({
    tileSource: heatmapTileSource,
    originalTiledImage: tiledImage
  });
});
```

**Comment by 575900931** [comment]
@iangilman  Thank you very much.I've done it as the way you provided.It solved a big problem for me.
![66b3f374082f30da9e14588bf17fb3c](https://user-images.githubusercontent.com/32389287/51577613-644b7b80-1ef5-11e9-958f-b490368b6e29.png)

**Comment by iangilman** [comment]
Great to hear!

**Comment by mingyaodagege** [comment]
嘿，你好。我就不用英文了，哈哈中国人，我想请教你一些关于openseadragon的问题。可以吗，如果可以留下你的邮箱或者qq，我来联系你

**Comment by iangilman** [comment]
@mingyaodagege Hello! I am happy to discuss here, or you can file a new issue, or you can email me at ian@iangilman.com. I don't speak Chinese, but hopefully with Google Translate we can communicate. I imagine what is best is for us to each write in our own language and the other person can use translation software to understand. Sound good?

Here's a Google Translate version:

@mingyaodagege 你好！ 我很高兴在这里讨论，或者您可以提交新的问题，或者您可以发送电子邮件至ian@iangilman.com。 我不会说中文，但希望通过谷歌翻译，我们可以沟通。 我想最好的是每个人用我们自己的语言写作，而另一个人可以使用翻译软件来理解。 听起来不错？
