### ISSUE TITLE
 On the Measurement of Medical Section

### ISSUE THREAD

**Issue by sprogjavasprog** [openseadragon/openseadragon#1589]
My problems and problems Similar to "Medical image viewer #34" , 
But I use fabric. JS to draw lines. The length of the lines I draw is known, but the actual length I calculate is always inaccurate.

//sc   is Actual zoom-in
var size = parseFloat(80 / parseFloat(sc) * 0.26410002 * Math.sqrt((currentX - startX) * (currentX - startX) + (currentY - startY) * (currentY - startY))).toFixed(1);
Here's an example for me to refer to.That's what I did with an example, but he's wrong. I don't know if you have any ideas about it.

**Comment by iangilman** [comment]
Assuming you're using https://github.com/altert/OpenseadragonFabricjsOverlay it looks like it uses viewport coordinates. You need to convert from that to whatever the full measurements are. Default viewport coordinates go from 0 on the left to 1 on the right, so if you know the length of your line in viewport coordinates and the width of your image in your target measurement units, you can find the result. For instance, if your line is 0.2 viewport coordinates long, and your image represents something that's 6mm across, your line is 1.2mm long. 

Does that help?

**Comment by sprogjavasprog** [comment]
What do you mean by measuring the width of the unit image? Pixel or something else, Width parameter in tileSources?

**Comment by msalsbery** [comment]
@sprogjavasprog The full width of the source image, in any units you’d prefer. If all you know is width in pixels then your distance is in pixels, but if you know your image width in mm then your distance is in mm.

A cool thing about viewport/logical coordinates is they’re agnostic so one can quickly calculate a value in any units once an image width calibration to the desired units  is done

**Comment by sprogjavasprog** [comment]
@iangilman @msalsbery  
Thank you for your help. I've dealt with this problem. Finally, I used image coordinates to do the calculation, because I found that in the case of enlargement, the coordinates of the viewport are the same under a small movement.
