### ISSUE TITLE
imageSmoothingEnabled's value is reset to "true" on resize

### ISSUE THREAD

**Issue by doutsh** [openseadragon/openseadragon#1593]
When setting imageSmoothingEnabled = false, the image is pixelized as expected, but when resizing the window the value is reset to 'true'.
In Chrome, on some intial window sized the value is set to true even without resize, regardless of the user's choice.
In IE11 it seems to work correctly for all initial sizes, but suffer from the same issue on resize.

**Comment by doutsh** [comment]
OK, some more info:
I get why it happens on resize - resize resets this canvas'es property, and at the moment setImageSmoothingEnabled() is called only once, in initialization.

Regarding the sizes, I found that it happens (in Chrome) on some size where in:
 /**
     * Clears the Drawer so it's ready to draw another frame.
     */
    clear: function()

viewportSize gets a non-integer value in x or y.
This triggers a fake resize (to the same size) because (this.canvas.width != viewportSize.x || this.canvas.height != viewportSize.y ) evaluates to 'true' (canvas.height/width are always integers), and the imageSmoothingEnabled is being reset to 'true'.

In IE as far as I can see, the size returned is always integer, so the issue only occurs on manual resize.

The solution (IMHO) should be to set imageSmoothingEnabled to the user defined (or default) value on every canvas resize.

**Comment by iangilman** [comment]
Sounds good, and I guess maybe we should set the viewport size to integer values? Bravo on tracking this down! Please make a pull request to patch it if you can :)
