### ISSUE TITLE
Updating an overlay dimensions in event handler?

### ISSUE THREAD

**Issue by mgiacomelli** [openseadragon/openseadragon#1596]
I'm putting simple overlays on top of an openseadragon image so that users can mark features.  So far I've implemented a drag handler that lets the user reposition the overlays using some examples posted online.  Now I would like to implement resizing, possibly by checking if the user clicked on the edge and then rescaling the x,y,height,width to shrink or expand the overlay.  

I've gotten this far:

```
new OpenSeadragon.MouseTracker({
		element: elt,
		dragHandler: function(event) {
			let windowCoords = new OpenSeadragon.Point(event.originalEvent.x, event.originalEvent.y);
			let viewportCoords = viewer.viewport.windowToViewportCoordinates(windowCoords);
			let overlay = viewer.getOverlayById(this.element);

			//todo: somehow calculate these values to update the overlay size as the user drags
			deltax=0;
			deltay=0;					
			let r = new OpenSeadragon.Rect(viewportCoords.x, viewportCoords.y, overlay.width+deltax, overlay.height+deltax);
			overlay.update(r, OpenSeadragon.Placement.CENTER);
			overlay.drawHTML(this.element.parentNode, viewer.viewport);
			
			console.log("drag delta: " + event.delta + " viewportCoords: " + viewportCoords + "windowCoords: " + windowCoords);
		}
	}).setTracking(true);
```

I thought I could use the event.delta to generate the deltax, deltay so that the overlay would expand or shrink in proportion to which way the user drags it, but that fails and gives me a randomly resized overlay, I think because the delta is in pixels, but the overlay is in viewport coordinates.  Next I tried converting the delta to viewport coordinates:

```
deltaInViewportCoord = viewer.viewport.windowToViewportCoordinates(event.delta); 
```

But this also doesn't seem to be right, or at least it isn't scaled as I would expect.  Is there a straightforward way to figure out how far the mouse was dragged in viewport coordinates so that I can update the overlay?  I must be missing something obvious.

**Comment by mgiacomelli** [comment]
After more reading, I discovered viewport.deltaPointsFromPixels, but I'm still struggling with viewport coordinates.  In the following I am trying to see which side of the box the user clicked on:

`
overlay = viewer.getOverlayById(this.element);
toppos = overlay.bounds.y;
botpos = overlay.bounds.y+overlay.bounds.height;
leftpos = overlay.bounds.x;
rightpos = overlay.bounds.x+overlay.bounds.width;

pos = viewer.viewport.pointFromPixel( event.position);
`
Apparently I'm using the wrong values (or pointFromPixel isn't right to use here?), because the pos.x/pos.y don't appear to be inside overlay bounds even though I'm clicking on the overlay object.  Conceptually I think I am missing something, I think the overlay bounds should be in the overall viewport coordinates, and pointFromPixel should convert the event position (in web coordinates) to viewport coordinates, but that doesn't seem to be the case.

**Comment by iangilman** [comment]
Yes, it can be confusing! 

What's going on in this case is that the MouseTracker gives its `event.position` relative to the upper left corner of your overlay in web coordinates; that's because the mouse tracker is independent of your Viewer, so it doesn't know about its coordinate system. You'll have to handle the conversion yourself. Fortunately it shouldn't be too hard... something like this should do it:

```
var offset = viewer.viewport.deltaPointsFromPixels(event.position);
var eventViewportPosX = leftpos + offset.x; 
var eventViewportPosY = toppos + offset.y; 
```

Does that make sense?

**Comment by mgiacomelli** [comment]
Thank you that works great!  My final code for resizing overlays in the dragHandler:

	
	//Calculate the edges of the overlay
	toppos = overlay.bounds.y;
	botpos = overlay.bounds.y+overlay.bounds.height;
	leftpos = overlay.bounds.x;
	rightpos = overlay.bounds.x+overlay.bounds.width;
       
      //convert event location to the overlay's coordinates 
	var offset = viewer.viewport.deltaPointsFromPixels(event.position);
	var eventViewportPosX = leftpos + offset.x; 
	var eventViewportPosY = toppos + offset.y;

    //calculate distances to each of the edges
	topdist = Math.abs(eventViewportPosY-toppos);
	bottomdist = Math.abs(eventViewportPosY-botpos);
	leftdist = Math.abs(eventViewportPosX-leftpos);
	rightdist = Math.abs(eventViewportPosX-rightpos);

     //finally get how far the user dragged
	viewportDeltaPoint = viewer.viewport.deltaPointsFromPixels(event.delta);

    //check which distances are smallest and then update overlay
      ...

Then I just look to see which side they dragged on, and add the viewportDeltaPoint as needed to scale that side.  Thanks again Ian!

**Comment by iangilman** [comment]
Excellent. Thank you for sharing the final code :)
