### ISSUE TITLE
TIFF File not loading in the Plain Javascript

### ISSUE THREAD

**Issue by farookshaik** [openseadragon/openseadragon#1597]
```
<html>
<body>
<div id="openseadragon1" >
</div>

<script src="tiff.min.js"></script>
<script src="openseadragon.min.js"></script>
<script src="jquery-2.0.3.min.js"></script>
<script src="imaginghelper.js"></script>
<script type="text/javascript">

  var viewer = OpenSeadragon({
    id: "openseadragon1",
        prefixUrl: "images/",
		 crossOriginPolicy: 'Anonymous',
		   ajaxWithCredentials: false,
		    
		sequenceMode:  true,
		preload:true,
		  tileSources: [{
            x: 0.883,
            y: 1,
            width: 100,
            tileSource: "file_example_TIFF_1MB.tiff"
        },
        {
            x: 1,
            y: 1,
            width: 200,
            tileSource: "file_example_TIFF_1MB.tiff"
        }
   ] 
});

 

/*viewer.addHandler("page", function (data) {
viewer.open();
   viewer.addTiledImage({
    tileSource: '20190022.177000.01.tif',
    x: 5,
    y: 0,
    width: 10
});
	
});*/

 
function FnOnlcik()
{
	alert(11)
}
</script>
</body>
</html>
```

**Comment by farookshaik** [comment]
This is my code,<html>
<body>
<div id="openseadragon1" >
</div>

<script src="tiff.min.js"></script>
<script src="openseadragon.min.js"></script>
<script src="jquery-2.0.3.min.js"></script>
<script src="imaginghelper.js"></script>
<script type="text/javascript">

  var viewer = OpenSeadragon({
    id: "openseadragon1",
        prefixUrl: "images/",
		 crossOriginPolicy: 'Anonymous',
		   ajaxWithCredentials: false,
		    
		sequenceMode:  true,
		preload:true,
		  tileSources: [{
            x: 0.883,
            y: 1,
            width: 100,
            tileSource: "file_example_TIFF_1MB.tiff"
        },
        {
            x: 1,
            y: 1,
            width: 200,
            tileSource: "file_example_TIFF_1MB.tiff"
        }
   ] 
});

 

/*viewer.addHandler("page", function (data) {
viewer.open();
   viewer.addTiledImage({
    tileSource: '20190022.177000.01.tif',
    x: 5,
    y: 0,
    width: 10
});
	
});*/

 
function FnOnlcik()
{
	alert(11)
}
</script>
</body>
</html>

**Comment by msalsbery** [comment]
I believe TIFF would need to be supported by the browser. More info here: #1380

**Comment by farookshaik** [comment]
i am using IE, but the browser does not show anything

**Comment by msalsbery** [comment]
Console output may have clues. Could be an unsupported TIFF format...

**Comment by farookshaik** [comment]
Thanks for your reply,

 No TileSource was able to open image.tif [object Document]

What is the meant by an error message in the edge/chrome browser?

**Comment by farookshaik** [comment]
Also i am using Xml for tilesources and setting tiff file for https.
i am getting below errror
![new](https://user-images.githubusercontent.com/42048241/52724277-ae63d200-2f74-11e9-97e3-6465cf91a4d3.png)

**Comment by iangilman** [comment]
So you only need this to work in IE/Edge? You don't have any users on Firefox or Chrome? If you do, you're better off converting the image to something all browsers can read.

Also, how big is your image? If it's more than a couple thousand pixels wide, you're better off converting the image to a tiled format that can load progressively. See http://openseadragon.github.io/examples/creating-zooming-images/.

Anyway, the problem you're having is that you're loading the image as if it's a tiled format, but what you have is just an untiled image. For that you need to use http://openseadragon.github.io/examples/tilesource-image/. For instance: 

```
tileSources: [{
  tileSource: {
    type: 'image',
    url:  'file_example_TIFF_1MB.tiff'
  },
  x: 0.883,
  y: 1,
  width: 100
}]
```

If that doesn't work, be aware you're in uncharted territory; since most browsers don't support TIFF, OSD doesn't have official TIFF support. I assume you've tried loading the TIFF directly in the browser and it's worked fine?

**Comment by farookshaik** [comment]
I appreciate it.. its worked for me...

Then my tiff files has 5 pages, so the browser show first page only.

Do i need add any config here?

**Comment by iangilman** [comment]
Sure, there are lots of options for multiple images. The most basic is to just provide more of them in your array, like so:

```

tileSources: [
  {
    tileSource: {
      type: 'image',
      url:  'file_example_TIFF_1MB.tiff'
    },
    x: 0,
    y: 0,
    width: 100
  },
  {
    tileSource: {
      type: 'image',
      url:  'file_example_TIFF_1MB_2.tiff'
    },
    x: 100,
    y: 0,
    width: 100
  },
  {
    tileSource: {
      type: 'image',
      url:  'file_example_TIFF_1MB_3.tiff'
    },
    x: 200,
    y: 0,
    width: 100
  }
]
```

For more ideas, check out the multi-image features section of http://openseadragon.github.io/#examples-and-features.

**Comment by farookshaik** [comment]
Yeah.. But my tiff has 5 pages like notices(page 1,2..), when i was open a tiff from window photo viewer, the number of paging count is 5, i am following same way using openseadragon, but its look like showing only one page in the browser.

Do i split the tiff image and set the tilesource array ?

or do you have some other option?

**Comment by msalsbery** [comment]
OpenSeadragon relies on the browser to load images, and I've never heard of or seen multi-page TIFF support in a browser so far...that's something you'll probably need to handle externally

**Comment by farookshaik** [comment]
Alright, i am using external js tiff.min.js [https://github.com/seikichi/tiff.js/tree/master]

So how can set the tilesource?

<html>

<body>
  <div id="openseadragon1">
  </div>
  <script src="jquery-2.0.3.min.js"></script>
  <script src="tiff.min.js"></script>
  <script src="openseadragon.min.js"></script>
  <script type="text/javascript">

    var viewer = OpenSeadragon({
      id: "openseadragon1",
      prefixUrl: "images/",
      crossOriginPolicy: 'Anonymous',
      ajaxWithCredentials: false,
      buildPyramid: false,
      sequenceMode: true,
      preload: true,
      showNavigator: true,
      tileSources: [{
        x: 0.883,
        y: 1,
        width: 100,
        tileSource: {
          type: 'image',
          url: [fnLoadData()]
        }
      }
      ]
    });



    function fnLoadData() {
      try {
        var xhr = new XMLHttpRequest();
        xhr.open('GET', "A1001001A19B13B55647B25937.tif");
        xhr.responseType = 'arraybuffer';
        xhr.onload = function (e) {
          var tiff = new Tiff({ buffer: xhr.response });
          alert(tiff.countDirectory())
          for (var i = 0, len = tiff.countDirectory(); i < len; ++i) {
            tiff.setDirectory(i);
            var canvas = tiff.toCanvas();
            document.body.append(canvas);
          }
        };

        xhr.send();
      }
      catch (e) {
        alert(e.description);
      }
    }

  </script>
</body>

</html>

**Comment by iangilman** [comment]
I don't think OSD currently supports directly loading from canvas (though that's an interesting feature idea). You would need to convert it to a dataURL and then add the image once it's ready. Something like so:

```
var viewer = OpenSeadragon({
  id: "openseadragon1",
  prefixUrl: "images/",
  crossOriginPolicy: 'Anonymous',
  ajaxWithCredentials: false,
  sequenceMode: true,
  preload: true,
  showNavigator: true
});

function fnLoadData() {
  var width = 100;
  try {
    var xhr = new XMLHttpRequest();
    xhr.open('GET', "A1001001A19B13B55647B25937.tif");
    xhr.responseType = 'arraybuffer';
    xhr.onload = function (e) {
      var tiff = new Tiff({ buffer: xhr.response });
      alert(tiff.countDirectory());
      for (var i = 0, len = tiff.countDirectory(); i < len; ++i) {
        tiff.setDirectory(i);
        var canvas = tiff.toCanvas();
        viewer.addTiledImage({
          tileSource: {
            type: 'image',
            url: canvas.toDataURL(),
            buildPyramid: false
          },
          x: i * width,
          y: 0,
          width: width
        });
      }
    };

    xhr.send();
  }
  catch (e) {
    alert(e.description);
  }
}

fnLoadData();
```

BTW, note that I'm providing positioning info with each of the images, but you're creating the viewer with `sequenceMode: true`, which means it'll override that positioning info. You can try it both ways to see which you prefer.

Also note that I've mode `buildPyramid: false` into the tileSource; it's not a viewer option.

**Comment by farookshaik** [comment]
Thank you. Your approach works perfectly for me.
