### ISSUE TITLE
Updating overlay stops after several updates

### ISSUE THREAD

**Issue by ErikDahlinghaus** [openseadragon/openseadragon#1599]
OpenSeadragon Version: `2.4.0`

I'm trying to draw an overlay underneath the mouse cursor, but the overlay stops updating after several cycles. If I pan or zoom then the overlay updates again for a few cycles and then stops.

I'm getting the mouse position from `MouseTracker`. `drawMouseOverlay` is called whenever `viewerMousePosition` is updated.

```javascript
drawMouseOverlay = () => {
    const { selectedSlideViewer } = this.props;

    const createCursorElement = (viewerId: number): HTMLSpanElement => {
      const element: HTMLSpanElement = document.createElement('span');
      element.className = 'synch-cursor fa fa-crosshairs fa-2x';
      element.id = `sharedview-mouse-cursor-${viewerId}`;
      return element;
    };

    const element: HTMLSpanElement = createCursorElement(0);
    const { x, y } = this.props.viewerMousePosition;

    const existingOverlay = selectedSlideViewer.getOverlayById(element.id);

    if (existingOverlay) {
      const { width, height } = existingOverlay.element.getBoundingClientRect();

      existingOverlay.update(
        selectedSlideViewer.viewport.pointFromPixel(
          new OpenSeadragon.Point(x - (width/2), y - (height/2))
        ),
        OpenSeadragon.Placement.TOP_LEFT
      );
    } else {
      selectedSlideViewer.addOverlay({
        element: element,
        location: selectedSlideViewer.viewport.pointFromPixel(
          new OpenSeadragon.Point(x, y)
        ),
        placement: OpenSeadragon.Placement.TOP_LEFT
      });
    }
  };
```

I've also tried destroying the overlay and readding it but this leaves artifacts of the destroyed overlays when I pan or zoom.

Any idea what is going on here? I've verified that the `existingOverlay.location` is updated when I call `existingOverlay.update()` but the overlay stops moving.

**Comment by iangilman** [comment]
Hmm... you might try calling `selectedSlideViewer.forceRedraw()` after doing your `update`, to see if that helps. 

Beyond that, I'd probably have to see a running example to get to the bottom of it.

**Comment by ErikDahlinghaus** [comment]
`selectedSlideViewer.forceRedraw()` fixed my issue completely. Thank you very much for your reply.
