### ISSUE TITLE
Some about using "addOverlay"

### ISSUE THREAD

**Issue by sprogjavasprog** [openseadragon/openseadragon#1601]
When I use "addOver" to add text coverage, I need to fix the height and width of the coverage I add without changing with the zoom-in and zoom-out.If it's not fixed, when I zoom in, the cover will become larger and cover the layer below. It's not what I want. I don't know if there are any relevant methods. If not, I can only monitor the change cycle of the rollers to set the width of the cover. This is a more troublesome thing.

Here is the implementation code：

                let textDiv = document.getElementById(id);

                if (textDiv != null) {
                    this.viewer.removeOverlay(id);
                }

                textDiv = document.createElement("div");
                textDiv.id = "text" + canvasObject.index;
                textDiv.style.fontSize = "18px";
                textDiv.style.color = "blue";
                textDiv.style.background = "black";
                textDiv.style.maxHeight = "30px";
                 textDiv.style.maxWidth = "190px";

                textDiv.innerHTML = “123587912a”

                var jk = this.viewer.viewport.getContainerSize().x;
                let widthPx = 120;
                let heightPx = 30;

                var viewportPoint = new OpenSeadragon.Point(this.mouseTo.viewPointX, this.mouseTo.viewPointY);

                var imagePoint = this.viewer.viewport.pointFromPixel(viewportPoint);

                var textRect = new OpenSeadragon.Rect(imagePoint.x, imagePoint.y, widthPx / jk / this.viewer.viewport.getZoom(),heightPx / jk / this.viewer.viewport.getZoom());

                this.viewer.addOverlay(textDiv, textRect);

**Comment by iangilman** [comment]
By adding the overlay with a rectangle, you're asking OSD to resize its width/height along with the zoom. If you add it with a point instead, OSD will leave the size alone. Something like: 

```
var textPoint = new OpenSeadragon.Point(imagePoint.x, imagePoint.y);

this.viewer.addOverlay(textDiv, textPoint);
```

**Comment by sprogjavasprog** [comment]
Thank you. This method works perfectly for me.

**Comment by sprogjavasprog** [comment]
I used this method, but I recently found a new problem. When I zoomed in, the cover I added seemed to be out of place before the reduction.

**Comment by iangilman** [comment]
I'm not sure what you're referring to. Can you share a link or some screenshots? At any rate, depending on the CSS on your element, that might affect the positioning.
