### ISSUE TITLE
OpenSeadragon Image Flipbook Codepen doesn't work

### ISSUE THREAD

**Issue by EunsungKoh** [openseadragon/openseadragon#1602]
Hi @iangilman ! 
I was surfing your Codepon.io and found that your [OpenSeadragon Image Flipbook](https://codepen.io/iangilman/pen/PjdyGv) is broken.

The OSD just show 
```Unable to open [object Object]: HTTP 0 attempting to load TileSource``` .

Thanks!

**Comment by iangilman** [comment]
Thanks for reporting! I'm not seeing it broken for me, though (in Mac Firefox and Chrome). What browser are you using? Do you have a proxy on your network connection? Any other clues?

**Comment by EunsungKoh** [comment]
This is a capture of [OpenSeadragon Image Flipbook](https://codepen.io/iangilman/pen/PjdyGv)
![screenshot from 2019-02-14 14-34-19](https://user-images.githubusercontent.com/26691192/52765013-b485ab80-3065-11e9-9361-facaddf21211.png)

My browser, OS is Google Chrome Version 72.0.3626.96 (Official Build) (64-bit) in Ubuntu 18.04 . 
I don't activate any proxy stuff now. Though, I have nginx in docker for develop.

**Comment by iangilman** [comment]
Strange. Here's what I'm seeing:

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/338989/52805453-71164780-303b-11e9-9e74-0a192ad7ce6b.png">

Looks like we're using CORS to be able to access files like:

https://openseadragon.github.io/example-images/pnp/ppmsca/05900/05954/05954.dzi

Without CORS on openseadragon.github.io, we wouldn't be able to load that Cross-Domain content (it's an XML file, which is normally restricted for Cross-Domain requests). I wonder if your browser is handling those loads differently. Do you see any errors in the console? What happens if you inspect the network calls for those files? 

I've tried adding `crossOriginPolicy: 'Anonymous'` to the viewer options on creation, to see if that helps. It doesn't make any difference on my browser, but maybe it'll help on yours?

**Comment by EunsungKoh** [comment]
This is my console state in Chrome :
![screenshot from 2019-02-15 10-07-00](https://user-images.githubusercontent.com/26691192/52827773-79d54f00-3109-11e9-871e-d2e6164cbff1.png)

--------------------------
And This is my network state of dzi file in Chrome :
![screenshot from 2019-02-15 10-07-59](https://user-images.githubusercontent.com/26691192/52827816-a5583980-3109-11e9-84d8-7bd049c8a7d1.png)

--------------------------
When I open Chrome with deactivate CORS option like 
```bash $ google-chrome  --disable-web-security``` , the result was same.
Do I have to activate CORS deactivate extensions for Chrome? :thinking:

**Comment by iangilman** [comment]
Pretty strange. Here is my network state for that file: 

![image](https://user-images.githubusercontent.com/338989/52878515-ad1bdc00-3111-11e9-9c65-339804322eb6.png)

My Chrome version is Version 72.0.3626.109 (Official Build) (64-bit) for MacOS. 

I don't really know what it would be that's causing this... some difference in our browsers or our OSs or our networks. Hmm... what country are you in? I'm in the US, if that makes a difference.

The files in question are being hosted on GitHub, so hopefully they are doing it right (but who knows I suppose). 

At any rate, I suspect it's just an issue on your end somehow. I'm happy to continue helping you track it down, but I don't know that the CodePen itself needs fixing for other people's purposes (I guess depending on whether they have the same issue you're having).

I'm also happy to help you get it running in a different way for your own use. For instance if you run it locally you could have a server side proxy for the DZI info. Alternately you could use this technique to avoid the cross-site call (without needing a server side proxy):

https://codepen.io/iangilman/pen/gpejpJ

What do you think?

**Comment by EunsungKoh** [comment]
Hi
I'm in South Korea.
Actually most of your codepen works fine.
Also, I'm using OpenSeaDragon in my local environment and it works fine too.

Honestly says, I'm not using that feature.
I just wanted to let you know the bug. 
If you think most of users can use it properly and it's not a big deal,
I think you can ignore this issue. :sweat_smile:

**Comment by iangilman** [comment]
Cool... thank you for reporting it! We'll see if anyone else runs into it...
