### ISSUE TITLE
  On the Combination of "addOverlay" and "MouseTracker"

### ISSUE THREAD

**Issue by sprogjavasprog** [openseadragon/openseadragon#1605]
Hello
   I want to achieve a similar effect in the first example of [https://openseadragon.github.io/examples/ui-overlays/]()，But I found that the "MouseTracker" I added would not work. I don't know why, but when I clicked on my text cover, the event didn't trigger, it just magnified the layer.

                let id = "text" + canvasObject.index;
                let textDiv = document.getElementById(id);

                if (textDiv != null) {
                    this.viewer.removeOverlay(id);
                }

                textDiv = document.createElement("div");
                textDiv.id = "text" + canvasObject.index;
                textDiv.style.fontSize = "14px";
                textDiv.style.color = "white";
                textDiv.style.background = "black";
                textDiv.style.height = "24px";
                textDiv.style.width = (this.fabricFrom.measureLine.length * 9) + "px";

                textDiv.innerHTML = this.fabricFrom.measureLine;

                var viewportPoint = new OpenSeadragon.Point(this.mouseTo.viewPointX, this.mouseTo.viewPointY);

                var imagePoint = this.viewer.viewport.pointFromPixel(viewportPoint);

                var textPoint = new OpenSeadragon.Point(imagePoint.x ,imagePoint.y);
                this.viewer.addOverlay(textDiv, textPoint, "LEFT", false);
           
                let track = new OpenSeadragon.MouseTracker({
                        element: textDiv,
                        clickHandler: function(e) {
                           console.info(12344555);
                        }
                });

**Comment by iangilman** [comment]
You might take a look at https://codepen.io/iangilman/pen/mEkKaY and see if that helps. If not, let me know!

**Comment by sprogjavasprog** [comment]
I found the reason, because I used fabric. js, so adding overlay added with "addOverlay" is not at the top level, so it can't trigger events. I added a "z-index = 9999999" attribute to the overlay to achieve the effect.

**Comment by iangilman** [comment]
Oh! Good to know :)
