### ISSUE TITLE
Bring overlay to centre of viewport after click with combined zoom and pan

### ISSUE THREAD

**Issue by nikreations** [openseadragon/openseadragon#1606]
I have multiple overlays (hotspots) on my gigapixel image. On clicking on any of the hotspots, I would like to zoom into that hotspot but make sure that the hotspot alongwith the gigapixel image is moved to the centre of the viewport (so the area of interest is in good view without the user having to pan and adjust manually). Currently, I am doing a zoomto and then a panto after settimeout. Is there a way to combine the zoom pan action. I tried setting the delay lesser than the time it takes to zoom, but the hotspot does not accurately go to the center.

**Comment by nikreations** [comment]
Ok.. I solved it by using fitbounds and rectangle, instead of using points. The overlay image had to be forced into size using !important in css because, the overlay image was resizing to fit into the rectangle. width, height in the overlay did not have any effect for some reason.

**Comment by iangilman** [comment]
Apologies for the delayed response, but yes, `fitBounds` is exactly the right solution :)

**Comment by msalsbery** [comment]
Closing this...feel free to re-open if there's any more questions or issues!
