### ISSUE TITLE
How to Set up navigator like Radar

### ISSUE THREAD

**Issue by mywsat** [openseadragon/openseadragon#1608]
![image](https://user-images.githubusercontent.com/23549273/52996970-1412fb00-345a-11e9-9176-66aa30f8a8b1.png)
https://med.motic.com/MoticGallery/Slides/07E0C5F4-A8B6-4C95-8209-61351302A669?user=any
Is there support for native API？or a plug-in to implement it?

**Comment by iangilman** [comment]
Meaning you want to add crosshairs to the existing navigator? I'm not aware of there being a plugin for that, but you could certainly write one. Take a look at the navigator code: 

https://github.com/openseadragon/openseadragon/blob/master/src/navigator.js

... To see how you might integrate it. I think you'd want to override the `update` function.

**Comment by mywsat** [comment]
thanks
