### ISSUE TITLE
Tile edges are visible with embedded viewer

### ISSUE THREAD

**Issue by ghost** [openseadragon/openseadragon#1612]
Hi
The tile edges are visible with an OpenSeadragon viewer embedded into ExtJS/Sencha:
http://cmbn-navigator.uio.no/navigator/filmstrip/index.html?blockId=982

Here is the same dataset with a pure OpenSeadragon viewer:
http://cmbn-navigator.uio.no/navigator/openseadragon/index.html?id=17028
No tiles visible.

The issue arises in Firefox, Safari, IE but not in Chrome. The overlap is 1. I do understand it's somehow related to all these divs Sencha generates and the canvas implementation but I can't pinpoint the exact spot. Any help is appreciated.

**Comment by iangilman** [comment]
I'm guessing this is probably the same issue as https://github.com/openseadragon/openseadragon/issues/1591. Do you need your images to be PNG?

**Comment by roybatty2016** [comment]
On 26.02.2019 22:13, Ian Gilman wrote:
> Do you need your images to be PNG?
You mean the tiles? Yes, the preferred format in our lab is PNG.

**Comment by iangilman** [comment]
Cool. Sorry about this issue! You can either modify your local OSD by reverting the https://github.com/openseadragon/openseadragon/pull/1470/files change, or you can join in on #1591 to try to help find a fix that works for all cases.

**Comment by iangilman** [comment]
While we have been unable to find an automatic fix for this issue, we've now landed a set of options that allow you to fix the issue based on your needs and preferences: #2075. I'm going to close this issue and we can start a fresh one if there are new ideas for how to fix it more robustly and/or automatically.
