### ISSUE TITLE
Overlay does not flip with source image and moves incorrectly

### ISSUE THREAD

**Issue by hyooeun** [openseadragon/openseadragon#1614]
Hi ! ✋ 

When i click flip button, tilesSource image flips properly 
But the overlay that I attach using `viewer.addOverlay()` does not flip with the tile source. 

In flipped state, the image panning works, but overlay moves opposite direction along the x-axis( only left and right). 

has this issue been reported?

**Comment by iangilman** [comment]
I don't think this issue has been reported, thank you!

@nelsonn3c any thoughts?

**Comment by astrozot** [comment]
As a side comment, it would be useful to have a flag that prevents flipping completely. In some cases, flipping is not desired, and it is desirable to disable it. The same goes for the rotation, but this is already possible by setting `rotationIncrement: 0`.

**Comment by iangilman** [comment]
@astrozot You mean prevent flipping of overlays when the image is flipped? Or just flipping in general? If you don't want the user to flip, you can hide the flip button.

**Comment by astrozot** [comment]
I mean preventing flipping in general. I am hiding the flip button, but if the user presses the F key the image will flip anyway.

**Comment by iangilman** [comment]
I see! Good point. Can you file that as a separate issue (it doesn't really belong bundled with this one)?

**Comment by claycoleman** [comment]
@iangilman any updates on this? Looks like the latest master still has this issue, you can verify on the https://openseadragon.github.io/examples/ui-overlays/ page. Looks like it might be related to #1695

**Comment by iangilman** [comment]
@claycoleman nothing that I'm aware of. Would you be interested in taking a whack at it? 

I'm glad you like OpenSeadragon! It's definitely a group effort... I'm just doing traffic control, trying to keep the information flowing :)

**Comment by barryspearce** [comment]
This issue is still present on 3.0.0.

**Comment by BeebBenjamin** [comment]
I have a fix for this in: https://github.com/openseadragon/openseadragon/pull/2546
