### ISSUE TITLE
I need help navigating within the collection view

### ISSUE THREAD

**Issue by salmasalma93** [openseadragon/openseadragon#1615]
hello , everyone. I am new here and trying the OpenSeaDragon and i have been enjoying it so much so far. i was wondering how can i use more than one mood for example here in my sample : https://codepen.io/salmashawky/pen/OqWYge
i used the collection mode and i now want to use the collection mood with the sequence mode , how can i do that ?

i want to navigate through the  images using next and previous buttons while they are on collection mode

**Comment by iangilman** [comment]
Welcome! You can't mix modes, but it shouldn't be too hard to get what you want. Sounds like you want a "next" button that takes you to the next image? Here's an example of that:

https://codepen.io/iangilman/pen/oVWNxJ
