### ISSUE TITLE
Feature to include watermark as image on osd viewer at particular location such as bottom right..

### ISSUE THREAD

**Issue by VenkateshwarRaoB** [openseadragon/openseadragon#1616]
Hi ,
how to add watermark as image on osdviewer at particular location?

**Comment by iangilman** [comment]
The easiest way to do this would be to just make a regular `<div>` on the page and use CSS to position it over the viewer in the bottom right. 

A more involved way would be to paint it on to `viewer.drawer.canvas` every frame.
