### ISSUE TITLE
IIIF: option to prefer canonical URLs

### ISSUE THREAD

**Issue by eroux** [openseadragon/openseadragon#1617]
OSD would often make requests to non-canonical URLs while having all the information available to compute the canonical one. This is not a bug per se as it is a SHOULD in the [specification](https://iiif.io/api/image/2.1/#canonical-uri-syntax), but it would make caching and processing time easier on the server side. 

The problem is especially inconvenient with the `{region}` and `{size}` parts of the URLs, that are not replaced by `full`. For instance OSD, for an image of width `w` and height `h` it would make requests to

```
http://example.com/0,0,w,h/w,/0/default.jpg
```

instead of

```
http://example.com/full/full/0/default.jpg
```

**Comment by iangilman** [comment]
I assume this is a IIIF-specific enhancement? Any ideas how to trigger it?

**Comment by eroux** [comment]
something like this: https://github.com/openseadragon/openseadragon/pull/1619
