### ISSUE TITLE
How to disable navigation in mobile only?

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#1620]
I'm considering moving to a full-screen modal option for better behavior in mobile vs. full-screen button.
How would I hide the navigation controls only in mobile (based on screen sizes like media queries or other method)?

**Comment by iangilman** [comment]
You could include something like `showNavigationControl: window.innerWidth < 768` or whatever as part of your viewer creation.

**Comment by SamHall** [comment]
showNavigationControl: window.innerWidth > 768
Works perfectly!
Thanks.

**Comment by iangilman** [comment]
Oh yeah, `>`… Good catch :-)

**Comment by msalsbery** [comment]
Closing this...feel free to re-open if there's any more questions or issues!
