### ISSUE TITLE
About"tileSources" and "Navigator"

### ISSUE THREAD

**Issue by sprogjavasprog** [openseadragon/openseadragon#1623]
hello
Recently, I found a problem using openseadragon and asked how to deal with it. When I used it 

     getTileUrl: function (level, x, y) {
         return "/guest/" + level + "/" + x + "_" + y + ".jpg";
     },

Hint the error, the network caused the picture not to be brought back.

      Tile $.Tile failed to load: /guest/8/0_0.jpg - error: Image load aborted
      Tile $.Tile failed to load: /guest/9/1_0.jpg - error: Image load aborted
      Tile $.Tile failed to load: /guest/9/0_0.jpg - error: Image load aborted
      Tile $.Tile failed to load: /guest/10/1_1.jpg - error: Image load aborted
      Tile $.Tile failed to load: /guest/10/0_0.jpg - error: Image load exceeded timeout

When the network is good and my other levels of pictures are returned, look at these pictures are still 
blurred. In addition, the navigation window is black screen, there is no navigation map in it. Is there any good way to deal with this caching problem?

**Comment by iangilman** [comment]
Do those tiles exist? Any idea why they are getting aborted? What kind of server are you running?

**Comment by sprogjavasprog** [comment]
Ceramic tiles are acquired on Windows machines by stream requests on Linux servers. Maybe the first view of acquisition does not exist (the windows machine will process, access will exist later). The first reason is that it does not exist at the beginning（ceramic tile generation）, and the second reason is that the network abnormalities lead to acquisition failure when acquisition occurs.

**Comment by iangilman** [comment]
Interesting. Sounds like what you need is some sort of mechanism to be able to retry later? It's possible this patch (which is not yet merged) could address this issue: https://github.com/openseadragon/openseadragon/pull/1386

**Comment by sprogjavasprog** [comment]
Okay, thank you for your reply. I'll pay attention to this.

**Comment by iangilman** [comment]
Continuing conversation from https://github.com/openseadragon/openseadragon/pull/1627. 

Interesting that you're using the legacy tile source... I don't think that it's meant to be used that way?  How are your images structured? Sorting that out is probably the first step. 

Another thought: If every time you hit an image you first get an error and then get a real image later, there might be something to be said about making your own pre-loader or something.

Anyway, please let me know the structure of your images.

**Comment by sprogjavasprog** [comment]
The image structure is the traditional pyramid structure, which is the same as the image generated by Deep Zoom Composer.
![image](https://user-images.githubusercontent.com/11442227/54888856-f4994300-4edb-11e9-8c5a-dc87a3d533c5.png)
![image](https://user-images.githubusercontent.com/11442227/54888865-febb4180-4edb-11e9-8192-f3ff1ebe53ea.png)

I wonder if you know about using openslide.
https://openslide.org/
My image is a display image obtained by parsing NDPI format files with it.

**Comment by iangilman** [comment]
Seems like you should use a DZI tilesource then, not a legacy tilesource. That might be part of your problem. In other words:

```
tileSources: "/api/guest/getImage/" + decodeURI(dizPathName),
```

**Comment by sprogjavasprog** [comment]
Okay, I'll try to do that.

**Comment by sprogjavasprog** [comment]
Sorry, I've been dealing with other things recently. I've tried this method before. This method can only use ceramic tiles locally. If I need to remotely acquire relevant tiles through HTTP and other requests, then this method should not be applied, otherwise my usage is wrong. And I don't know if you have tried cross-domain access. This method is not supported now.

**Comment by dbhuvanapalli** [comment]
I have the same issue, some of my tiles fail to load with timeout error. Any tips on how to handle this error? I use the dzi files.
tileSources:   "/data/000/000/447/e2f0971dc605abef164fac49d5d93588c192a614/04.dzi"

**Comment by iangilman** [comment]
@dbhuvanapalli Is your server really slow? You can always try giving a longer `timeout` in the options when you create your viewer. The default is 30000 milliseconds.

**Comment by linruicheng1997** [comment]
Have you solved it, can you share the solution?
