### ISSUE TITLE
Html Overlay Table is jittering when zooming

### ISSUE THREAD

**Issue by cueqzapper** [openseadragon/openseadragon#1624]
When zooming in, I overlay a html table over the zoomable image.  But this Html Overlay Table jitters as long as I move in.

Here is the example code:
https://jsfiddle.net/4msc9hwx/1/

Is this a bug in openseadragon?

**Comment by cueqzapper** [comment]
The demo is much faster when I remove the box-shadow from the td (yes, this one is obvious):

https://jsfiddle.net/qr2zLeok/

**Comment by iangilman** [comment]
Hmm... I'm actually impressed the HTML table is making such a good grid! I think that bit of jitter is probably inevitable. If you want more control over how your grid is drawn you might use https://github.com/altert/OpenSeadragonCanvasOverlay or https://github.com/joshua-gould/OpenSeadragonCanvasOverlayHd (or any of the other drawing-based overlays). 

Awesome image, BTW!

**Comment by cueqzapper** [comment]
Thanks a lot for the compliment! 

Do you have any idea where this jitter might come from? 

I will definitely try out your suggestions.

**Comment by iangilman** [comment]
I imagine the HTML table is trying to orient itself to exact pixel coordinates, whereas to be truly smooth it would need to draw to fractional pixel coordinates. It's making the right choice for an actual table, since keeping it on exact pixels makes it sharper, and normally tables aren't involved in smooth animation like this.

**Comment by cueqzapper** [comment]
You should write a book one time, the inner life of a table ;-) Yes, your answer makes sense, so the only way to go is to use canvas. Thanks a lot!

**Comment by iangilman** [comment]
Tables have feelings too! ;-)
