### ISSUE TITLE
Arrows keys bypass panHorizontal/panVertical = false

### ISSUE THREAD

**Issue by Riclim** [openseadragon/openseadragon#1630]
Even if panHorizontal/panVertical are set to false the user is still able to pan around using the arrows keys.

**Comment by iangilman** [comment]
Good point! That should be relatively easy to take care of, in the code starting here:

https://github.com/openseadragon/openseadragon/blob/517be7db49a049d79b9a13fcc4cdc0a8458f1ac5/src/viewer.js#L2517

Would you be interested in taking a whack at it?

**Comment by Riclim** [comment]
Ok, I'll take it! Thanks.
