### ISSUE TITLE
Tiles keep loading when useCanvas is set to false

### ISSUE THREAD

**Issue by ciegunov** [openseadragon/openseadragon#1633]
Hello,

I'm going to give a bit of context first before explaining my issue.
I'm working on a project where I'm trying to set OpenSeadragon as an alternative to a basic image viewer. We use an image element inside a svg element to display the image and we are also able to draw things on top of it, zoom, and drag the image across the screen but we have big performance issues when the images are bigger, that's why we thought of using a tiled image, but we still want to use our implementation of zoom, etc...

So I got some good results by placing the OpenSeadragon div inside a foreignObject so we can directly replace image. I can draw on top of the image and all but for resizing purposes I had to set useCanvas to false.
Now the issue is that when we display the image with OpenSeadragon, it starts loading tiles from level 8 and doesn't stop until everything above is loaded. 

I have tried to modify some parameters like maxImageCacheCount but it didn't work, I'd really appreciate some help on this topic

**Comment by iangilman** [comment]
Interesting. And if you change `useCanvas` back to true, it doesn't load those extra tiles? 

I tried this with our basic.html demo (https://github.com/openseadragon/openseadragon/blob/master/test/demo/basic.html) with both true and false for useCanvas, and both times it loaded the same number of tiles. Presumably there's more to your set up than that... any thoughts about how your viewer differs? I don't quite understand how you are using your own zooming on the OSD viewer. Is there something you can link to?

**Comment by ciegunov** [comment]
Oh I just noticed I skipped quite a few words from my previous post.
We are actually not able to use our own zoom instead of OSD's, do you think that will be doable ?

We use an svg element to display our image and we are trying to use OSD instead of the image :


<pre style="color:#000000;background:#ffffff;"><span style="color:#808030; ">&lt;</span>svg
        <span style="color:#808030; ">.</span><span style="color:#808030; ">.</span><span style="color:#808030; ">.</span> <span style="color:#800000; font-weight:bold; ">some</span> parameters <span style="color:#808030; ">.</span><span style="color:#808030; ">.</span><span style="color:#808030; ">.</span>
        viewBox<span style="color:#808030; ">=</span><span style="color:#800080; ">{</span><span style="color:#800000; ">`</span><span style="color:#800000; ">${</span><span style="color:#797997; ">viewBox</span><span style="color:#808030; ">.</span><span style="color:#797997; ">x</span><span style="color:#800000; ">}</span><span style="color:#0000e6; "> </span><span style="color:#800000; ">${</span><span style="color:#797997; ">viewBox</span><span style="color:#808030; ">.</span><span style="color:#797997; ">y</span><span style="color:#800000; ">}</span><span style="color:#0000e6; "> </span><span style="color:#800000; ">${</span><span style="color:#797997; ">viewBox</span><span style="color:#808030; ">.</span><span style="color:#797997; ">width</span><span style="color:#800000; ">}</span><span style="color:#0000e6; "> </span><span style="color:#800000; ">${</span><span style="color:#797997; ">viewBox</span><span style="color:#808030; ">.</span><span style="color:#797997; ">height</span><span style="color:#800000; ">}</span><span style="color:#800000; ">`</span><span style="color:#800080; ">}</span>
<span style="color:#808030; ">&gt;</span>
        <span style="color:#808030; ">&lt;</span>image
          className<span style="color:#808030; ">=</span><span style="color:#800080; ">{</span>className<span style="color:#800080; ">}</span>
          href<span style="color:#808030; ">=</span><span style="color:#800080; ">{</span>getImageUrl<span style="color:#808030; ">(</span>image<span style="color:#808030; ">.</span>id<span style="color:#808030; ">)</span><span style="color:#800080; ">}</span>
          x<span style="color:#808030; ">=</span><span style="color:#800000; ">"</span><span style="color:#0000e6; ">0</span><span style="color:#800000; ">"</span>
          y<span style="color:#808030; ">=</span><span style="color:#800000; ">"</span><span style="color:#0000e6; ">0</span><span style="color:#800000; ">"</span>
          width<span style="color:#808030; ">=</span><span style="color:#800080; ">{</span>width<span style="color:#800080; ">}</span>
          height<span style="color:#808030; ">=</span><span style="color:#800080; ">{</span>height<span style="color:#800080; ">}</span>
<span style="color:#0000e6; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color:#800000; ">/</span><span style="color:#0000e6; ">&gt;</span>
<span style="color:#0000e6; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color:#808030; ">.</span><span style="color:#808030; ">.</span><span style="color:#808030; ">.</span><span style="color:#0000e6; "> other options </span><span style="color:#808030; ">.</span><span style="color:#808030; ">.</span><span style="color:#808030; ">.</span><span style="color:#0000e6; "></span>
<span style="color:#0000e6; ">&lt;</span><span style="color:#800000; ">/</span>svg<span style="color:#808030; ">&gt;</span>
</pre>


I am currently trying to replace image with OSD :


<pre style="color:#000000;background:#ffffff;"><span style="color:#808030; ">&lt;</span>svg
   viewBox<span style="color:#808030; ">=</span><span style="color:#800080; ">{</span><span style="color:#800000; ">`</span><span style="color:#800000; ">${</span><span style="color:#797997; ">viewBox</span><span style="color:#808030; ">.</span><span style="color:#797997; ">x</span><span style="color:#800000; ">}</span><span style="color:#0000e6; "> </span><span style="color:#800000; ">${</span><span style="color:#797997; ">viewBox</span><span style="color:#808030; ">.</span><span style="color:#797997; ">y</span><span style="color:#800000; ">}</span><span style="color:#0000e6; "> </span><span style="color:#800000; ">${</span><span style="color:#797997; ">viewBox</span><span style="color:#808030; ">.</span><span style="color:#797997; ">width</span><span style="color:#800000; ">}</span><span style="color:#0000e6; "> </span><span style="color:#800000; ">${</span><span style="color:#797997; ">viewBox</span><span style="color:#808030; ">.</span><span style="color:#797997; ">height</span><span style="color:#800000; ">}</span><span style="color:#800000; ">`</span><span style="color:#800080; ">}</span>
<span style="color:#808030; ">&gt;</span>
   <span style="color:#808030; ">&lt;</span>foreignObject
       x<span style="color:#808030; ">=</span><span style="color:#800080; ">{</span><span style="color:#800000; font-weight:bold; ">this</span><span style="color:#808030; ">.</span>props<span style="color:#808030; ">.</span>x<span style="color:#800080; ">}</span> <span style="color:#696969; ">// ViewBox's position</span>
       y<span style="color:#808030; ">=</span><span style="color:#800080; ">{</span><span style="color:#800000; font-weight:bold; ">this</span><span style="color:#808030; ">.</span>props<span style="color:#808030; ">.</span>y<span style="color:#800080; ">}</span> <span style="color:#696969; ">// ViewBox's position</span>
       style<span style="color:#808030; ">=</span><span style="color:#800080; ">{</span><span style="color:#800080; ">{</span> position<span style="color:#800080; ">:</span> <span style="color:#800000; ">'</span><span style="color:#0000e6; ">relative</span><span style="color:#800000; ">'</span><span style="color:#808030; ">,</span> width<span style="color:#800080; ">:</span> <span style="color:#800000; font-weight:bold; ">this</span><span style="color:#808030; ">.</span>props<span style="color:#808030; ">.</span>width<span style="color:#808030; ">,</span> height<span style="color:#800080; ">:</span> <span style="color:#800000; font-weight:bold; ">this</span><span style="color:#808030; ">.</span>props<span style="color:#808030; ">.</span>height <span style="color:#800080; ">}</span><span style="color:#800080; ">}</span>
   <span style="color:#808030; ">&gt;</span>
       <span style="color:#808030; ">&lt;</span>div
          id<span style="color:#808030; ">=</span><span style="color:#800080; ">{</span><span style="color:#800000; font-weight:bold; ">this</span><span style="color:#808030; ">.</span>id<span style="color:#800080; ">}</span>
          style<span style="color:#808030; ">=</span><span style="color:#800080; ">{</span><span style="color:#800080; ">{</span> width<span style="color:#800080; ">:</span> <span style="color:#800000; font-weight:bold; ">this</span><span style="color:#808030; ">.</span>props<span style="color:#808030; ">.</span>width<span style="color:#808030; ">,</span> height<span style="color:#800080; ">:</span> <span style="color:#800000; font-weight:bold; ">this</span><span style="color:#808030; ">.</span>props<span style="color:#808030; ">.</span>height <span style="color:#800080; ">}</span><span style="color:#800080; ">}</span>
          className<span style="color:#808030; ">=</span><span style="color:#800080; ">{</span><span style="color:#800000; font-weight:bold; ">this</span><span style="color:#808030; ">.</span>props<span style="color:#808030; ">.</span>className<span style="color:#800080; ">}</span>
<span style="color:#0000e6; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color:#800000; ">/</span><span style="color:#0000e6; ">&gt;</span>
<span style="color:#0000e6; ">&nbsp;&nbsp;&nbsp;&lt;</span><span style="color:#800000; ">/</span>foreignObject<span style="color:#808030; ">&gt;</span>
<span style="color:#808030; ">&lt;</span><span style="color:#808030; ">/</span>svg<span style="color:#808030; ">&gt;</span>
</pre>

I need foreignObject to put a div into the svg element, but when I use the canvas it seems to break the resizing ability, probably because of that foreignObject because OSD resize just fine in other projects.  When I don't use the canvas the resizing works so I tried going that way.
If I enable the canvas it also loads all the images, but the image displayed at start is super zoomed in.

**Comment by iangilman** [comment]
Wow, sounds like you're really pushing the envelope here. I've never tried to do something like that. 

Is it possible to not have the OSD viewer inside the SVG? It might be better to have them separate and just synchronize them. You might also look at https://github.com/openseadragon/svg-overlay as an option. 

Otherwise I think you are in uncharted territory, though I'm happy to be a sounding board if you want.
