### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by Tune55** [openseadragon/openseadragon#1635]
I can't get this to work! I uploaded Openseadragon to my website. I am using code from their site. The only thing I have changes is the paths to the code and images. Nothing works. I am not an experienced programmer, Basic in the 1980's don't count. I would be thankful for any help.

```
<div id="openseadragon1" style="width: 800px; height: 600px;"></div>
<script src="http://dartmouthhas.org/uploads/1/0/0/2/100287044/openseadragon.min.js"></script>
<script type="text/javascript">
    var viewer = OpenSeadragon({
        id: "openseadragon1",
        prefixUrl: "/openseadragon/images/",
        tileSources: [{
    type: 'legacy-image-pyramid',
    levels:[{
        url: "http://dartmouthhas.org/uploads/1/0/0/2/100287044/map-2-copy-small_orig.jpg",
        height: 889,
        width:  600
    },{
        url: "http://dartmouthhas.org/uploads/1/0/0/2/100287044/map-2-copy-medium_orig.jpg",
        height: 2201,
        width:  1485
    },{
        url: "http://dartmouthhas.org/uploads/1/0/0/2/100287044/map-2-copy-large_orig.jpg",
        height: 7441
        width:  10555
     });
</script>    
```

**Comment by iangilman** [comment]
Looks like you're almost there... the big issue I see is that you are missing a couple of brackets on the second to last line. Change `});` to `}]});`. Also, a couple of lines up you need a comma after `height: 7441`. 

One more minor point: I'm guessing you don't actually have the OpenSeadragon button images at `/openseadragon/images/`, so the buttons will show up as broken icons. This isn't a functional issue, but at some point you'll want to make sure the `prefixUrl` points to a folder with the OpenSeadragon button images. 

BTW, one way to track down errors is to open up your browser developer console; they should be listed there.

**Comment by Tune55** [comment]
Fantastic! Thanks Ian. Just the help I needed.
