### ISSUE TITLE
Multi-image initial view & relative sizes

### ISSUE THREAD

**Issue by SoTCA** [openseadragon/openseadragon#1636]
I have a number of dzis of artworks which I'd like to arrange as if they were laid out around each other. I'm using `addTiledImage` to bring each image in and am using the x and y values so that I can arrange them more organically than simple rows or columns (as they are all different shapes and sizes).

However, the starting view always centres on the first image rather than encompassing the group, and it looks like the relative sizes of each image aren't correct (e.g. I know that one of the images is half the size of another but they are almost the same size in the viewer). I'm very new to OSD and multi-image especially so any help would be great, including if there's actually a better way to call up the multi-images in the first place!

**Comment by iangilman** [comment]
You can actually do multi image layout either with the initial viewer creation or with `addTiledImage`. If you want the starting view to encompass the group, doing it on viewer creation (or `open`) may be a better choice. 

As for the size, you just need to specify a width or a height. 

For example: 

```
var viewer = OpenSeadragon({
  ...,
  tileSources: [
    {
      tileSource: 'a.dzi',
      x: 0,
      y: 0,
      width: 100
    },
    {
      tileSource: 'b.dzi',
      x: 105,
      y: 0,
      width: 30
    }
  ]
});
```

**Comment by SoTCA** [comment]
Many thanks Ian, that's a lot easier way of calling them up! Is there any limit to the number of `tileSource` elements I can add to the viewer? Also, I hadn't considered using the width/height for some reason but that will work in fine.

**Comment by iangilman** [comment]
We don't have an explicit max, but of course, eventually your browser might run out of memory or something. Certainly hundreds are fine, possibly thousands. 

One thing to be aware of is if your tile sources are URLs to something to DZI files, it'll be one network connection per URL. You can avoid that by bundling all of the DZI information into a single file and using the "inline" configuration mentioned in http://openseadragon.github.io/examples/tilesource-dzi/
