### ISSUE TITLE
 fitBounds did not move to the center

### ISSUE THREAD

**Issue by mywsat** [openseadragon/openseadragon#1639]
map.viewport.fitBounds(react,flalse) 
It can zoom to a specified size.
But did not move to the center of the boundary。
only in same zoom,it can be used.
i must use 
map.viewport.fitBounds(react,flalse) 
map.viewport.panTo(point,true);

**Comment by iangilman** [comment]
Can you share an example of this problem? `fitBounds` usually works for this.

**Comment by mywsat** [comment]
i have a annotaion.
Its pixel coordinates (x: 10000px, y: 10000px, width: 300px, height: 300px).
`let  react=map.viewport.imageToViewportRectangle(10000,10000,100,100);`
`map.viewport.fitBounds(react,false);`

It zoom to annotation size, but does not move to annotation Center

**Comment by iangilman** [comment]
It seems to be working as far as I can tell: 

https://codepen.io/iangilman/pen/WWEbJm
