### ISSUE TITLE
Zoom and Image Size

### ISSUE THREAD

**Issue by cueqzapper** [openseadragon/openseadragon#1640]
Let's say I want the image to be 100x100 pixels in dimension when loading the site. 

I tried doing this with:

viewer.viewport.zoomTo

but the problem seems to be, that the initial image has always different size depending on the size of the browser window. And when I apply a zoomTo Value, this value is in correlation with the initial size of the image. Is there a way to make the image always the same size in pixel on load?

**Comment by iangilman** [comment]
A zoom of 1 means the image is displayed at the full width of the viewer. A zoom of 0.5 means that it's displayed at half the width of the viewer. You just need to determine what proportion of the viewer 100px is, like so:

```
viewer.viewport.zoomTo(100 / viewer.element.clientWidth);
```
