### ISSUE TITLE
Get image data of a DZI image at a specified zoom level

### ISSUE THREAD

**Issue by AngryNeox** [openseadragon/openseadragon#1641]
My problem is a bit weird but what I need is the image data of the currently used image but at a different zoom level. The navigator is also on a different zoom level, so I can't use that either. (Also I'm using DZI images)

The first question is if that's even possible with openseadragon. I tried getting the "2d context" by using the the tilesource, drawer and other classes but only the the basic ImageTilesource for single images has the `getContext("2d")` function. Does it even exist for other tile sources "before" it is placed on the canvas? I think using a new TiledImage would be the answer but I'm not sure how to create one manually.

The alternative would be to just not use anything by openseadragon and open the correct images manually or with another library but that would be more work I think.

Is there a solution I'm missing?

**Comment by iangilman** [comment]
Depending on what you are trying to do, one solution would be to open a fresh viewer that has the right size and zoom it to the right level and wait for the tiles to load. Then you can grab its pixels from `viewer.drawer.canvas`. BTW, it might be helpful to look at https://github.com/KTGLeiden/Openseadragon-screenshot for reference.

If you don't want to or can't open a separate viewer for this purpose, then yes, you might need to reconstruct that level yourself... you'll need to grab all the tiles and lay them out properly. Here's some additional info on the DZI format:

https://github.com/openseadragon/openseadragon/wiki/The-DZI-File-Format
