### ISSUE TITLE
 Loading Rendering of Ceramic Tiles

### ISSUE THREAD

**Issue by sprogjavasprog** [openseadragon/openseadragon#1642]
Helllo
       When I use openseadragon, I find the display is blurred. I don't know what the specific problem is. In debug mode, I find that the image is not rendered. I look at the browser's console and the corresponding position of the image is returned.
![image](https://user-images.githubusercontent.com/11442227/56178556-47769e00-6035-11e9-9034-a96723078036.png)

![image](https://user-images.githubusercontent.com/11442227/56178581-5fe6b880-6035-11e9-875a-6f7f3b713c6f.png)

It seems that there is a problem with rendering. Besides, this problem does not occur every time. Occasionally, it occurs more frequently when I zoom in and out or drag faster.

**Comment by iangilman** [comment]
Does it correspond with failed tile loads? I believe if we fail to load a tile we never try again. That's what https://github.com/openseadragon/openseadragon/pull/1627 is supposed to address, but no one is working on it.

**Comment by sprogjavasprog** [comment]
@iangilman 
     He doesn't seem to have anything to do with the problem of #27. I found that the timeout caused the corresponding picture not to be rendered on the page. I set the timeout a little longer so that it won't be blurred after waiting for a period of time, instead of the situation that has been blurred before me.

    In addition, I found a situation where when I zoomed in to the maximum, he loaded non-existent hierarchical tiles, which is also the cause of my normal tile timeout.

   I've closed this issue for the time being. Recently, I won't deal with anything related. I'll continue to give you feedback based on this item when I have time.

**Comment by iangilman** [comment]
Thank you for the update!
