### ISSUE TITLE
Prevent the zoom from being reset at each page change?

### ISSUE THREAD

**Issue by jlarvers** [openseadragon/openseadragon#1644]
We use OSG with Mirador.
I do not know if the question really concerns OSD.

In Mirador, and for an image collection, we added a small feature to keep and block the zoom ratio from one image to another (in the example, the padlock at the top right).

http://ad53-recette.pleade.com/ark:/37963/r275zzjlsj8kbk/f1

When you change pages, the zoom ratio starts by re-initializing to the default value (home) and then the zoom ratio is applied.
This causes a zoom in effect at each page change (this is more visible when pages are already cached).

Is there a way to prevent the zoom from being reset at each page change?

Thank you !

**Comment by iangilman** [comment]
How is Mirador moving from image to image? If it's using sequence mode or something similar, you could create the viewer with `preserveViewport: true`.
