### ISSUE TITLE
How to  add multiple navigator control in openseadragon viewport

### ISSUE THREAD

**Issue by VenkateshwarRaoB** [openseadragon/openseadragon#1649]
I want to add multiple navigator control in openseadragon viewport.
One is for normal view and other for heat map.
Both navigator should visible on viewport and should have same function as normal navigator.

Any help/suggestions would be appreciated.

**Comment by iangilman** [comment]
OSD doesn't have built in support for doing that, but you can probably make it happen. The navigator is more or less just another viewer, with a little bit of extra logic. I would suggest using the built in navigator for the normal view, and then make a fresh viewer for the heat map and lay it on top of the main viewer just like the navigator does. 

Then pay attention to the `animation` events fired from the main viewer and draw a rectangle in your heat map to correspond with the main viewer's viewport bounds.

**Comment by VenkateshwarRaoB** [comment]
Thanks ian.
Can you please provide some example/demo.

**Comment by iangilman** [comment]
Here's a rough example to get you started: https://codepen.io/iangilman/pen/yrGzYZ

**Comment by msalsbery** [comment]
@VenkateshwarRaoB  Closing this...feel free to re-open if you still have questions or issues!
