### ISSUE TITLE
Rotate openseadragon Image with paper.js annotations

### ISSUE THREAD

**Issue by PpyMohan** [openseadragon/openseadragon#1650]
Hi,
  i am able to rotate image. problem in image have paper.js Annotations  circle or rectangle  on inside openseadragon image, if i rotate the image, only rotating image. i need to keep that annotation in exact point where i drawn. 
Original Image ::
![1](https://user-images.githubusercontent.com/25381060/56575721-1e7d7c80-65e4-11e9-8714-6f147f121202.png)

After Rotation ::
![Untitled](https://user-images.githubusercontent.com/25381060/56575725-23423080-65e4-11e9-9069-238a476b8857.png)

**Comment by iangilman** [comment]
Looks like maybe the Paper overlay doesn't yet support rotation. I see you've [filed an issue](https://github.com/eriksjolund/OpenSeadragonPaperjsOverlay/issues/7) on that project... I've added some thoughts there.
