### ISSUE TITLE
How to compare between the two images and highlight the difference?

### ISSUE THREAD

**Issue by tufail** [openseadragon/openseadragon#1653]
Hi @iangilman ,
I need to compare two DZI images source and highlight the difference with color.
Is there any option to add CSS class each of the DZI image or any method available to add the filters on each of the image.
Here is the exact requirement i need.
https://stackoverflow.com/questions/55587561/how-to-compare-between-the-two-images-and-highlight-the-difference

my current code is 
```
var viewer = OpenSeadragon({
    id: "openseadragon1",
    prefixUrl: "https://openseadragon.github.io/openseadragon/images/",
    panHorizontal: false,
    panVertical: false,
    minZoomLevel: 0.25,
    tileSources: [
        {
            tileSource: "plan1.dzi",
            x: 0
        },
        {
            tileSource:"plan1extended.dzi",
            opacity: .7,
            x: 1.1
        }
    ]
});

viewer.addHandler('open', function() {
    viewer.viewport.fitBounds(new OpenSeadragon.Rect(-1, -1, 3, 3));
});

var drag = null;

viewer.addHandler('canvas-drag', function(event) {
    var box, i, image;

    var pos = viewer.viewport.pointFromPixel(event.position);

    if (drag) {
        box = drag.image.getBounds(true);
        console.dir(drag.image)
        var diffX = pos.x - drag.lastPos.x;
        var diffY = pos.y - drag.lastPos.y;
        box.x += diffX;
        box.y += diffY;
        drag.image.setPosition(new OpenSeadragon.Point(box.x, box.y), true);
        drag.lastPos = pos;
    } else {
        var count = viewer.world.getItemCount();
        for (i = 0; i < count; i++) {
            image = viewer.world.getItemAt(i);
            box = image.getBounds(true);
            if (pos.x > box.x && pos.y > box.y && pos.x < box.x + box.width &&
                    pos.y < box.y + box.height) {
                break;
            } else {
                image = null;
            }
        }

        if (image) {
            drag = {
                image: image,
                lastPos: pos
            };
        } else {
            viewer.panHorizontal = true;
            viewer.panVertical = true;
        }
    }
});

viewer.addHandler('canvas-drag-end', function() {
    drag = null;
    viewer.panHorizontal = false;
    viewer.panVertical = false;
});
```

**Comment by iangilman** [comment]
@tufail If you have two images in the viewer, you can apply a composite operation to the top one to have it draw differently. For instance:

```
var topImage = viewer.world.getItemAt(1);
topImage.setCompositeOperation('difference');
```

Another option would be to have two viewers stacked on top of each other, each with their own image. You could then add a CSS filter to the top viewer. This would of course require synchronizing the viewers, so it would be more work than the first approach.

**Comment by tufail** [comment]
@iangilman  Thank you so much this works for me!"

> @tufail If you have two images in the viewer, you can apply a composite operation to the top one to have it draw differently. For instance:
> 
> ```
> var topImage = viewer.world.getItemAt(1);
> topImage.setCompositeOperation('difference');
> ```
> 
> Another option would be to have two viewers stacked on top of each other, each with their own image. You could then add a CSS filter to the top viewer. This would of course require synchronizing the viewers, so it would be more work than the first approach.
