### ISSUE TITLE
Canvas-focus event

### ISSUE THREAD

**Issue by btzr-io** [openseadragon/openseadragon#1657]
Is there a `canvas-focus` event implemented ?
I need to be able to display a custom toolbar (controls) for the viewer on `:hover` or `:focus` for accessibility, but I can't find it on the docs.

https://github.com/btzr-io/Villain

**Comment by btzr-io** [comment]
I tried to use just `css` but the controls are outside the viewer hierarchy :thinking:

**Comment by btzr-io** [comment]
Never mind, it was really easy :stuck_out_tongue: 
```JS
    this.viewer.canvas.addEventListener('focus', (e) => {
      console.info("focus!", this.viewer.canvas);
    });
```

**Comment by btzr-io** [comment]
I'm still not sure if there should be something like:
```JS
this.viewer.addHandler('focus', () => {
...
})
```

**Comment by iangilman** [comment]
Yeah, seems like we might as well add that to the API. In fact, MouseTracker already has blur and focus events, so it shouldn't be hard to use one of the mouse trackers the viewer already has.

Would you be interested in writing a patch for this? If not, we can leave it open for someone else to try.

**Comment by btzr-io** [comment]
Ok, I'll try but I'm not sure where to start, can you point me the right files :upside_down_face:  ?

**Comment by iangilman** [comment]
Great!

I'm actually not sure whether it should be the innerTracker or outerTracker, but I'm guessing it's the innerTracker, which is set up here: 

https://github.com/openseadragon/openseadragon/blob/e7108f23602575fc6eb152d4b82a8b44b2ca698e/src/viewer.js#L289

Just add a couple extra handlers there like the other ones. The handlers themselves can just raise events; there isn't anything else that needs to happen (I think).

**Comment by btzr-io** [comment]
Ok, thanks, I'll see if a have some time this week :v:

**Comment by iangilman** [comment]
Cool. Let me know if you run into any trouble :)

**Comment by msalsbery** [comment]
@btzr-io 

Making any progress on this? I'm doing some MouseTracker work and could roll this enhancement in with that work if you're not finding the time to tackle it

Thanks!

**Comment by btzr-io** [comment]
@msalsbery sorry I'm really busy (ATM) to work on this.
 Yeah sure go for it, thanks! :v:

**Comment by 340rahul** [comment]
Hello, @msalsbery were you able to find time to complete this? If not, I will be happy to pick this up.

**Comment by iangilman** [comment]
@340rahul while @msalsbery did a major overhaul of the event system this year, it doesn't look like he added `canvas-focus` as part of that. I think you should feel free to take it on :)

**Comment by 340rahul** [comment]
Would it be okay if I add both `canvas-focus` and `canvas-blur` events?

**Comment by iangilman** [comment]
@340rahul yes, that seems like a good idea!

**Comment by 340rahul** [comment]
Sorry, I got busy and wasn't able to attend to this for a while. I've finally opened a [PR](https://github.com/openseadragon/openseadragon/pull/2029) for this. This is my first time contributing here. Please let me know if this looks okay. I would be happy to make changes to the documentation [here](https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html) to add focus and blur events if you can direct me on how make changes. Thank you.

**Comment by msalsbery** [comment]
Bump (note to self)

**Comment by MohitBansal321** [comment]
would you assign this issue to me

**Comment by MohitBansal321** [comment]
https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L3154-L3181 
I thought we should replace this onCanvasEnter with onCanvasFocus 
It works same as the focus 
@iangilman

**Comment by msalsbery** [comment]
> https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L3154-L3181 I thought we should replace this onCanvasEnter with onCanvasFocus It works same as the focus @iangilman

pointer enter/leave events are different than focus/blur events. We need to add canvas focus/blur events driven from the corresponding MouseTracker events (from the Viewer.innerTracker)

@340rahul  has a [pull request nearly completed](https://github.com/openseadragon/openseadragon/pull/2029) to draw inspiration from - there's good info there

**Comment by MohitBansal321** [comment]
> > https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L3154-L3181 I thought we should replace this onCanvasEnter with onCanvasFocus It works same as the focus @iangilman
> 
> pointer enter/leave events are different than focus/blur events. We need to add canvas focus/blur events driven from the corresponding MouseTracker events (from the Viewer.innerTracker)
> 
> @340rahul has a [pull request nearly completed](https://github.com/openseadragon/openseadragon/pull/2029) to draw inspiration from - there's good info there

There are some property which is not used in canvas-enter 
I check manually without it they are working fine
```
function onCanvasEnter( event ) {
    /**
     * Raised when a pointer enters the {@link OpenSeadragon.Viewer#canvas} element.
     *
     * @event canvas-enter
     * @memberof OpenSeadragon.Viewer
     * @type {object}
     * @property {OpenSeadragon.Viewer} eventSource - A reference to the Viewer which raised this event.
     * @property {OpenSeadragon.MouseTracker} tracker - A reference to the MouseTracker which originated this event.
     * @property {Object} originalEvent - The original DOM event.
     */

    this.raiseEvent( 'canvas-enter', {
        tracker: event.eventSource,
        originalEvent: event.originalEvent
    });
    
}
```
So I can remove the unused properties?

**Comment by msalsbery** [comment]
@MohitBansal321 no there's not unused properties, that's the event object passed to event subscriber's handler function

**Comment by msalsbery** [comment]
The base class (OpenSeadragon.EventSource) adds the eventSource and userData properties

**Comment by MohitBansal321** [comment]
> @MohitBansal321 no there's not unused properties, that's the event object passed to event subscriber's handler function

It was working fine with above-given code

**Comment by MohitBansal321** [comment]
@msalsbery  We need to do this nah if someone clicks on the photo it should be call to focus event when someone click outside the photo it should call the blur event

**Comment by msalsbery** [comment]
> @msalsbery  We need to do this nah if someone clicks on the photo it should be call to focus event when someone click outside the photo it should call the blur event

The focus and blur DOM events are already captured on the viewer.canvas element by the Canvas.innerTracker. All that needs to be done is adding handlers for those events to the tracker and raising new canvas-focus and canvas-blur events from those new handler functions.

See the previous pull request from @340rahul for an example

**Comment by MohitBansal321** [comment]
> > @msalsbery  We need to do this nah if someone clicks on the photo it should be call to focus event when someone click outside the photo it should call the blur event
> 
> The focus and blur DOM events are already captured on the viewer.canvas element by the Canvas.innerTracker. All that needs to be done is adding handlers for those events to the tracker and raising new canvas-focus and canvas-blur events from those new handler functions.
> 
> See the previous pull request from @340rahul for an example

you are talking about enterHandler and leaveHandler?
But i can't see the already captured focus and blur event

**Comment by msalsbery** [comment]
> > > @msalsbery  We need to do this nah if someone clicks on the photo it should be call to focus event when someone click outside the photo it should call the blur event
> 
> > 
> 
> > The focus and blur DOM events are already captured on the viewer.canvas element by the Canvas.innerTracker. All that needs to be done is adding handlers for those events to the tracker and raising new canvas-focus and canvas-blur events from those new handler functions.
> 
> > 
> 
> > See the previous pull request from @340rahul for an example
> 
> 
> 
> you are talking about enterHandler and leaveHandler?
> 
> But i can't see the already captured focus and blur event 

I never mentioned enter/leave handler.

Viewer has a member property called innerTracker. The focus and blur DOM events are handled there. Those need to be handled by viewer and re-raised as new events.

I'm pretty sure that's what's in your PR. Nothing else needs to change

**Comment by MohitBansal321** [comment]
> > > > @msalsbery  We need to do this nah if someone clicks on the photo it should be call to focus event when someone click outside the photo it should call the blur event
> > 
> > 
> > > 
> > 
> > 
> > > The focus and blur DOM events are already captured on the viewer.canvas element by the Canvas.innerTracker. All that needs to be done is adding handlers for those events to the tracker and raising new canvas-focus and canvas-blur events from those new handler functions.
> > 
> > 
> > > 
> > 
> > 
> > > See the previous pull request from @340rahul for an example
> > 
> > 
> > you are talking about enterHandler and leaveHandler?
> > But i can't see the already captured focus and blur event
> 
> I never mentioned enter/leave handler.
> 
> Viewer has a member property called innerTracker. The focus and blur DOM events are handled there. Those need to be handled by viewer and re-raised as new events.
> 
> I'm pretty sure that's what's in your PR. Nothing else needs to change

No need to change in PR?

**Comment by MohitBansal321** [comment]
> > @msalsbery  We need to do this nah if someone clicks on the photo it should be call to focus event when someone click outside the photo it should call the blur event
> 
> The focus and blur DOM events are already captured on the viewer.canvas element by the Canvas.innerTracker. All that needs to be done is adding handlers for those events to the tracker and raising new canvas-focus and canvas-blur events from those new handler functions.
> 
> See the previous pull request from @340rahul for an example

from the example of this user it did the same thing

**Comment by MohitBansal321** [comment]
let me know what i am missing

**Comment by msalsbery** [comment]
> let me know what i am missing

It looks good to me except the doc comments I requested changes on :)
