### ISSUE TITLE
viewer.addOverlay returns reference to Viewer instead of created Overlay

### ISSUE THREAD

**Issue by bente** [openseadragon/openseadragon#1658]
Hi, 
It seems to me that when I use 

var overlay = viewer.addOverlay(elm, position, OpenSeadragon.Placement.CENTER);

the variable overlay contains a reference to the Viewer instance.
I expected a reference to the created Overlay instance. Is this correct behaviour?

You can test this in the Basic OpenSeadragon Example with Overlay, by dumping the overlay variable at the end of the code:
https://codepen.io/iangilman/pen/vyWabR

**Comment by iangilman** [comment]
Yeah, at some point a number of the viewer functions were written to make them "chainable", so you could call a bunch of them all in a single statement. I actually don't think it's terribly useful, so we're not doing that with newer functions, but I don't really want to remove the chainable aspect of the old functions, for fear of breaking people's existing code. At any rate, it's a design flaw, not a bug. 

To get what you want, it's two statements:

```
viewer.addOverlay(elm, position, OpenSeadragon.Placement.CENTER);
var overlay = viewer.getOverlayById(elm);
```

...And I'm open to suggestions on how to deprecate the chaining for future versions without breaking people's code!
