### ISSUE TITLE
How to get current instance of created Viewer?

### ISSUE THREAD

**Issue by MortezaMohseni66** [openseadragon/openseadragon#1659]
Hi
i know that i can get access to Viewer instance by this code:
`var viewer = OpenSeadragon({ option});`
what if i need this instance on other functions or triggered events.
for example i created a Viewer on div#myviewer and now i want access it by some thing like
`var createdViewer=OpenSeadragon('#myviewer')`

**Comment by iangilman** [comment]
There's nothing like that; you just need to keep a hold of the viewer object you got when you created it. Is there something particular you're trying to do that makes that awkward?

**Comment by MortezaMohseni66** [comment]
I'm writing single page document management that views documents in multiple tabs and each viewer can navigate through files, sections and...
I need it for a clean and more readable code. 
thanks.

**Comment by iangilman** [comment]
Cool. Well, I suppose it could be added if you're up for writing a patch to make it happen.
