### ISSUE TITLE
Navigator viewport is incorrect

### ISSUE THREAD

**Issue by cmbasnett** [openseadragon/openseadragon#1660]
I'm running into an issue trying to add the navigator to our OpenSeaDragon viewer. It appears as though the viewport of the navigator is incorrectly positioned. The full image should be showing up in the navigator, but it isn't, it looks like it' just zoomed into a small subset of the image.

<img width="1668" alt="Screen Shot 2019-06-12 at 1 43 49 PM" src="https://user-images.githubusercontent.com/5035660/59384907-23bf9380-8d18-11e9-842c-3f24a8420353.png">

Here is the code I'm using to initialize the viewer:

```
    this.viewer = OpenSeadragon({
      id: "orbit-viewer",
      preserveViewport: true,
      zoomPerScroll: 1.1,
      prefixUrl: this.path,
      showNavigationControl: false,
      constrainDuringPan: true,
      defaultZoomLevel: 1,
      minZoomLevel: 1,
      maxZoomPixelRatio: 4,
      visibilityRatio: 1,
      sequenceMode: true,
      initialPage: this.currentSlide,
      tileSources: this.tileSources,
      nextButton: "next-item",
      previousButton: "previous-item",
      autoResize: true,
      preserveImageSizeOnResize: true,
      zoomPerSecond: 0.2,
      showNavigator: true,
    });
```

**Comment by peteszym** [comment]
@cmbasnett , if you're adding any custom CSS that effects the `openseadragon-container` class (for example width and height), you'll want to make sure it's specific enough not to effect all instances of `.openseadragon-container`. 

Basically, when you add the navigator in, it adds another div with the same class name. If you want to target the element with CSS, you'll need to do something like `.navigator > .openseadragon-container`, as an example.
