### ISSUE TITLE
Openseadragonfillter CONVOLUTION grid line issue 

### ISSUE THREAD

**Issue by PpyMohan** [openseadragon/openseadragon#1663]
After Adding CONVOLUTION Openseadragonfillter i am getting grid lines on image how to hide this grid lines ?? And it is clearly visible when i zoom image
OpenSeadragon.Filters.CONVOLUTION([
                                            0, -1,  0,
                                           -1,  5, -1,
                                            0, -1,  0]),

**Comment by iangilman** [comment]
This is an OpenSeadragonFiltering plugin issue... more comments at: https://github.com/usnistgov/OpenSeadragonFiltering/issues/18
