### ISSUE TITLE
Change Animation Duration for zoomTo and panTo

### ISSUE THREAD

**Issue by cueqzapper** [openseadragon/openseadragon#1665]
As I learned the default animation time is 1200 ms. Is there a way to change this?

**Comment by msalsbery** [comment]
> As I learned the default animation time is 1200 ms. Is there a way to change this?

You can use the animationTime property in the viewer options object

**Comment by msalsbery** [comment]
Closing this...feel free to re-open if issue persists!

**Comment by joedf** [comment]
Just as a note to future readers... To change it after creation, i,e. when it's running... You can modify the `animationTime` like so:
```js
var newAnimationTime = 0.8; // seconds
viewport.centerSpringX.animationTime = newAnimationTime; // for animation when panning horizontally
viewport.centerSpringY.animationTime = newAnimationTime; // for animation when panning vertically
viewport.zoomSpring.animationTime = newAnimationTime; // for animation when zooming in/out
```
You could save the values, before setting the new ones to restore the original values later...
Reference: https://stackoverflow.com/a/25108446/883015

**Comment by iangilman** [comment]
@joedf, thanks for sharing this!
