### ISSUE TITLE
How to access raw image data?

### ISSUE THREAD

**Issue by lk-jeffpeck** [openseadragon/openseadragon#1666]
I am attempting to load a dzi that uses 16-bit pngs.

I would like to use an `update-viewport` handler to update the canvas with those values converted to 8-bit. (Yes, I realize this sounds inefficient, but I am simplifying the use-case here.)

How can I access the original data? Is this even possible?

**Comment by iangilman** [comment]
By default the image is copied to a canvas when it's first drawn and the image is discarded: 

https://github.com/openseadragon/openseadragon/blob/eafdc452c9e312f1f69a44bbb0db0023826da92d/src/tilecache.js#L72

I believe you can circumvent that and draw the image to canvas in your own way if you want by hooking it to the `tile-loaded` event. Something like:

```
viewer.addHandler('tile-loaded', function(event) {
  var canvas = document.createElement('canvas');
  canvas.width = event.image.width;
  canvas.height = event.image.height;
  event.tile.context2D = canvas.getContext('2d');
  event.tile.context2D.drawImage(event.image, 0, 0);
});
```

You'd still be converting it to 8-bit, but you could do it however you wanted to.

Does that help?

**Comment by lk-jeffpeck** [comment]
Thank you. It does help to point me in the right direction.

I am realizing that I will need to load the image via XMLHttpRequest and use a png parser to get at the 16-bit data, which adds additional complication. (There is no good way that I am aware of to get at the raw data of an image element without first dumping it into a canvas, at which point it automatically becomes 8-bit.)

Essentially the use-case is that I have multiple layers that I want to composite with their 16-bit values and then convert to 8-bit and deliver the result to the OSD canvas.

I am wondering if I could maybe make a custom TileSource for this. Is that possible?

The other option is to composite the images server-side and return the 8-bit values and keep things simple for OSD.

**Comment by iangilman** [comment]
It does seem like it should be possible within OSD, but you're right that it would be easier on the server. For the OSD side, take a look at the discussion in https://github.com/openseadragon/openseadragon/issues/1643.
