### ISSUE TITLE
Best way to pass custom parameters to a dzi tile source?

### ISSUE THREAD

**Issue by lk-jeffpeck** [openseadragon/openseadragon#1670]
Let's say this is my tile source:
```
const tileSource = new OpenSeadragon.DziTileSource({
  width: 19200,
  height: 19200,
  tileSize: 1023,
  tileOverlap: 1,
  tilesUrl: "http://localhost:4000/dzi_test/",
  fileFormat: "jpeg"
});
```

How would I go about passing custom args to the server, like "brightness" or "channels", etc.?

Would I be able to attach custom args to every request (i.e. `http://localhost:4000/dzi_test/12/1_0.jpeg?brightness=4&channels=blu,grn`)

Alternatively, is there a way to pass custom headers with the request?

I realize there are many ways I could do this including using a custom tile source, but I am looking for the ideal/best way to accomplish this.

Thank you!

**Comment by lk-jeffpeck** [comment]
Forget it. I just discovered that any args passed to the .dzi file will automatically be passed to the tile image requests. Easy. Great feature!

So, `tileSource = "http://localhost:4000/dzi_test/test.dzi?foo=bar"` will request images like `http://localhost:4000/dzi_test/test_files/...jpg?foo=bar`

That's exactly what I need for this.

**Comment by iangilman** [comment]
Excellent :)

**Comment by msalsbery** [comment]
🤘

**Comment by palytoxin** [comment]
> Forget it. I just discovered that any args passed to the .dzi file will automatically be passed to the tile image requests. Easy. Great feature!
> 
> So, `tileSource = "http://localhost:4000/dzi_test/test.dzi?foo=bar"` will request images like `http://localhost:4000/dzi_test/test_files/...jpg?foo=bar`
> 
> That's exactly what I need for this.

I found change the parameters after initialization, this solution won’t work

**Comment by iangilman** [comment]
> I found change the parameters after initialization, this solution won’t work

I'm not sure what you mean by this. Can you give an example, or explain more fully?

**Comment by palytoxin** [comment]
sorry for that.
I mean that it's work not fine if I'll changed `tileSource = "http://localhost:4000/dzi_test/test.dzi?foo=bar"` to `xxxi?foo=bar1`

but, I found a way to change it
```ts
  changeMode(mode: string) {
    const url = (this.viewer as any).tileSources;
    const bounds = this.viewer.viewport.getBounds();

    this.viewer.close();
    (this.viewer as any).open(url);
    setTimeout(() => { // waiting for viewer opend
      (this.viewer as any).source.queryParams = [`?mode=${mode}`];
      this.viewer.viewport.fitBounds(bounds, true);
    }, 500);
  }
```
