### ISSUE TITLE
Error when reference strip used with Shadow DOM

### ISSUE THREAD

**Issue by dmcalpin** [openseadragon/openseadragon#1674]
When including a viewer inside a web component (with Shadow DOM), with a reference strip enabled, i get the error: `TypeError: Cannot read property 'style' of null` and the selected thumbnail in the reference strip is not highlighted

Error Example: https://jsbin.com/beyunawuhu/1/edit?js,output

it looks like this is due to the `$.getElement` call here:
https://github.com/openseadragon/openseadragon/blob/c7aa6eda84931c1fc3454f1b8404d8c58d16948c/src/referencestrip.js#L239

would it be possible to do something like this:
`$.getElement( this.element.children[page] )`
so that it's scoped to the element, instead of the light dom

(sry, im not very familiar with your codebase)

**Comment by iangilman** [comment]
I'm not familiar with working with the shadow DOM, so I guess we'll have to meet in the middle somehow! 

Would this work?

```
var element = this.element.querySelector(this.element.id + '-' + page)
```

That way we can stick with the ID structure.

**Comment by dmcalpin** [comment]
I'm all for meeting in the middle. Just tested my app, works good
`var element = this.element.querySelector('#' + this.element.id + '-' + page)`
i'll get a PR opened if that sounds good to you

**Comment by PCailly** [comment]
I solved this by passindg th element instead.
this._rootDiv = document.createElement ( "div");
this.shadow.appendChild(this._rootDiv);

THEN
OpenSeadragon({
	        element: this._rootDiv,
	        
	        tileSources:  xxxxx
   });

BUT 
I got the 'move' and 'fulscreen' BUGS as described in my post CustomElements

**Comment by dmcalpin** [comment]
@PCailly i did the same thing. Passing HTML Elements for `element`, or the different buttons `zoomInButton` worked well. But the reference strip doesn't allow for that which is why we end up with this error

**Comment by msalsbery** [comment]
Closing this...feel free to re-open if issues persist!
