### ISSUE TITLE
refPoint v.s. center?

### ISSUE THREAD

**Issue by lk-jeffpeck** [openseadragon/openseadragon#1675]
I am updating a tile source when a user toggles a slider.

I want to keep the location, so I first capture the current zoom and center and then immediately update back to that zoom/position after it loads. It works well like this:

```
const currZoom = viewer.viewport.getZoom();
const currCenter = viewer.viewport.getCenter();

const hasTiledImage = viewer.world.getItemAt(0) !== undefined;

viewer.addTiledImage({
  tileSource,
  index: hasTiledImage ? 0 : null,
  replace: hasTiledImage,
  crossOriginPolicy: "Anonymous",
  success: () => {
    viewer.viewport.zoomTo(currZoom, null, true)
    viewer.viewport.panTo(currCenter, true)
  }
})
```

I am wondering about this part however:
```
    viewer.viewport.zoomTo(currZoom, null, true)
    viewer.viewport.panTo(currCenter, true)
```

I think that I should be able to do this in a single call to `.zoomTo`, and indeed, the second argument to `zoomTo` is a `refPoint`, however when I try to do this:
```
    viewer.viewport.zoomTo(currZoom, currCenter, true)
```
it takes me to the wrong place.

I am looking for some clarification on what is the best way to do this.

Thanks!

**Comment by iangilman** [comment]
The `refPoint` in `zoomTo` is to support zooming around the cursor when you use the scroll wheel. So it doesn't specify where the new panning location will be, it just says "zoom around this point".

If you want to do zooming and panning with a single call, use `fitBounds`. Of course you'll have to do a little math to provide the proper bounds, but I believe the animation is a little cleaner.

**Comment by lk-jeffpeck** [comment]
Aha, thank you!

Didn't even require math :) :
```
const currBounds = this.viewer.viewport.getBounds();

// ... update tile source ...
// on success:
    this.viewer.viewport.fitBounds(currBounds, true);
```

**Comment by iangilman** [comment]
Looks good!
