### ISSUE TITLE
Openseadragon not loading dzi images from remote location

### ISSUE THREAD

**Issue by 1ankit8** [openseadragon/openseadragon#1679]
I was able to work with dzi on my local system. But it does not load when i am giving a remote location.

`
viewer = OpenSeadragon({
    id: 'floor-plan-container',
    prefixUrl: '../../assets/vendor/osd/openseadragon/images/',
    tileSources: '../../assets/vendor/osd/openseadragon/dzi_test/helloworld.dzi',
    maxLevel: 15
  });
`
this works for me, but

`
viewer = OpenSeadragon({
    id: 'floor-plan-container',
    prefixUrl: '../../assets/vendor/osd/openseadragon/images/',
    tileSources: 'https://github.com/LearningApp111/DZI/tree/master/DZI/helloworld.dzi',
    maxLevel: 15
  });
`

the files are currently placed at https://github.com/LearningApp111/DZI/tree/master/DZI

**Comment by xgui3783** [comment]
Can you see what is printed in the console when it does not work? I suspect it is because of CORS

**Comment by msalsbery** [comment]
If that’s the actual link you’re using I don’t think that’ll work even if no CORS required...it points to a github page, not the actual file I think (I could be wrong). 

If you want to host on github you could probably put the data in your github site there (ie LearningAp111.github.com) if you’ve set that up

**Comment by msalsbery** [comment]
Also, quickest way to see if a URL is the issue is plug it right into a browser address bar and see what comes back ;)

**Comment by msalsbery** [comment]
@xgui3783 I just noticed your edit...I didn’t know the direct URL to raw project data, thanks!
