### ISSUE TITLE
fitbounds to tilesource in a collection?

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#1681]
I'm presenting many images in a collection and want to allow users to also navigate to a tilesource in the collection vs. display only that tilesource.
I've used fitbounds to 'zoom to' coordinates, and I can navigate to tilesources in sequence (one at at time), but cannot figure out how to maintain the collection view and 'fitbounds' to a page(tilesource).
See working page & note the behavior of the buttons labeled 'image 3' and 'image 4'.
Using:
`        $('.w003').click(function() {
          viewer.goToPage(3);
        }`
https://chattanoogahistory.com/marr-field

![collectionnav](https://user-images.githubusercontent.com/4950023/61586414-49269500-ab41-11e9-8e79-6b4313d512c7.JPG)

**Comment by iangilman** [comment]
Something like this should do the trick:

```
var index = 2; // The third image, counting from 0
var tiledImage = viewer.world.getItemAt(index);
var imageBounds = tiledImage.getBounds();
viewer.viewport.fitBounds(imageBounds);
```

**Comment by SamHall** [comment]
THANK YOU. That works and saves me a lot of time setting coordinates to target.
I'm again showing my mental block in javascript. But I try to make up for it with creative use.

Ha.

**Comment by iangilman** [comment]
Yeah, your site continues delight me! So much great stuff, and I love how you keep developing new ways to present the material :)
