### ISSUE TITLE
Change/Update/Refresh single simple image in tilesource? 

### ISSUE THREAD

**Issue by udiatcimd** [openseadragon/openseadragon#1682]
I'm working with _legacy-image-pyramid_ for simple images to allow zoom.

Is there any way to change and refresh a single image on a tilesource with multiple images without updating the full tilesource? It's important to mantain the same order.

Redrawing the full tilesource takes a little while since there are a lot of images.

Thanks for your help!

**Comment by iangilman** [comment]
I'm having a hard time visualizing what you're trying to do. Are you showing a collection of images on the screen at the same time? Or do you have a single image that is composed of multiple tiles? What are you trying to update?

**Comment by udiatcimd** [comment]
Sorry I was not clear enough!
I made this codepen to try to convey better what I mean:
https://codepen.io/anon/pen/XvXjLR

What I need to do is change one of these images without changing the full tilesource, saving reload time since I usually have more than 2 images.

**Comment by iangilman** [comment]
Great, thank you. Sounds like what you want is `viewer.addTiledImage`... That allows you to add new images without reloading the other ones. If you do want to selectively remove items, you can do that with `viewer.world.removeItem`.

**Comment by udiatcimd** [comment]
Thank you!
That does it, I don't know how I did not see it before... 

I'm closing the question!
