### ISSUE TITLE
Is there Any Option to Set Scalebar width fixed.

### ISSUE THREAD

**Issue by PpyMohan** [openseadragon/openseadragon#1684]
How to set scale bar fixed width, it should not change the width but it should change only the value while zoom-in or zoom-out

**Comment by iangilman** [comment]
I'm not familiar with that plugin, so I don't know. Good to see you've filed an issue there as well: https://github.com/usnistgov/OpenSeadragonScalebar/issues/10 

You might try digging into the code to take a look?

**Comment by shyamkumaryadav** [comment]
if u comment out this line https://github.com/usnistgov/OpenSeadragonScalebar/blob/master/openseadragon-scalebar.js#L266 and  https://github.com/usnistgov/OpenSeadragonScalebar/blob/master/openseadragon-scalebar.js#L277 than your scalebar only update change value not width of scalebar.
