### ISSUE TITLE
Hittest not working after 2.2?

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#1688]
I've used 'hitTest' code to auto-center on items in collections. And it works with 2.2.0, but nothing later.  Could someone point me in the right direction to enable it in newer versions?

Example of working using 2.2.0 ->
https://chattanoogahistory.com/marr-field

Example of same page using 2.4.1 (not working / not throwing errors): -> https://chattanoogahistory.com/marr

hitTest code:

```
var hitTest = function(position) {
            var box;
            var count = viewer.world.getItemCount();
            for (var i = 0; i < count; i++) {
              box = viewer.world.getItemAt(i).getBounds();
              if (position.x > box.x && 
                  position.y > box.y && 
                  position.x < box.x + box.width &&
                  position.y < box.y + box.height) {
                return i;
              }
            }
            return -1;
          };
          var $viewerElement = $('#openseadragon-canvas')
          .on('mousemove', function(event) {
            var pixel = new OpenSeadragon.Point(event.clientX, event.clientY);
            pixel.y -= $viewerElement.position().top;
            var index = hitTest(viewer.viewport.pointFromPixel(pixel));
            $('.output').text(index === -1 ? '' : 'Image ' + index);
          }
             );
          viewer.addHandler('canvas-click', function(event) {
            if (!event.quick) {
              return;
            }
            var index = hitTest(viewer.viewport.pointFromPixel(event.position));
            if (index !== -1) {
              viewer.viewport.fitBounds(viewer.world.getItemAt(index).getBounds());
            }
          }
                           );

```

**Comment by maskgk** [comment]
After some test, I conclude that this is caused by the click to zoom setting. If disable the clickToZoom option in gestureSettingsMouse, it works well. So you have to disable the default click to zoom handler when you just need fit the selected item bounds, which you can disable preventDefaultAction of event to realize.

**Comment by SamHall** [comment]
That works! Thank you.

**Comment by SamHall** [comment]
Now that I need the current version to do 'other stuff', I'd like to see HitTest working without disabling clickToZoom 
 in gestureSettingsMouse.
Any help in doing that? 
FYI - the hitTest failure occurs only on desktop after version 2.2.0.

**Comment by iangilman** [comment]
Seems like it should work... in what way is it failing? What are you hoping that it'll do that it's not doing? Do you have an example to share?

**Comment by SamHall** [comment]
Specifically,  to make it work after 2.2.0 you have to disable the clickToZoom option in gestureSettingsMouse.
Not terrible, but removes the option for a user to click outside tiles and zoom (normal expected behavior). At least this is the only fix I'm aware of.
Working example here in a modal:  https://chattanoogahistory.com/hittest

**Comment by iangilman** [comment]
I still don't understand what you mean by it not working. If you don't disable `clickToZoom`, the hit detection doesn't happen at all? Or the hit detection happens, but in response it doesn't zoom correctly? If it's the latter, that makes sense, because the click to zoom behavior would override any additional navigation you might be adding. 

If you want to override the click to zoom behavior dynamically, you can use `event.preventDefaultAction = true` like so:

```
viewer.addHandler('canvas-click', function(event) {
  if (!event.quick) {
    return;
  }
  
  var index = hitTest(viewer.viewport.pointFromPixel(event.position));
  if (index !== -1) {
    event.preventDefaultAction = true;
    viewer.viewport.fitBounds(viewer.world.getItemAt(index).getBounds());
  }
});
```

**Comment by SamHall** [comment]
The 'fix' requires that click to zoom is disabled for all areas around the tiles (shown in red in example), but does work for the tiles themselves. Both worked for v 2.2.0.
Again, not a huge deal, but would be ideal if Hittest worked without disabling the zoom.
Without the 'fix' - Hittest won't zoom to fill/contain per tile after 2.2.0.

![image](https://user-images.githubusercontent.com/4950023/127415880-96abffdf-4c98-4967-a6f8-d12a73c01b83.png)

**Comment by iangilman** [comment]
Cool, makes sense. My suggestion above should work for that. Have you given it a try?

**Comment by SamHall** [comment]
I misread that suggestion. 
Tested and confirmed. It works!
Thank you.

**Comment by iangilman** [comment]
Excellent :)
