### ISSUE TITLE
Image viewer is referring to icons in https://openseadragon.github.io/openseadragon/images/home_hover.png for menu icons

### ISSUE THREAD

**Issue by Rafi993** [openseadragon/openseadragon#1691]
Image viewer is referring to icons in https://openseadragon.github.io/openseadragon/images/home_hover.png for menu icons it should refer to the local icons instead.

**Comment by alvaromartmart** [comment]
You should probably refer to the specific code where you found that.

**Comment by Rafi993** [comment]
Im not sure about the file. But I found it in SRC attribute of img tag of the icons in image viewer.

**Comment by iangilman** [comment]
@Rafi993 Can you share viewer construction code you're using (e.g. `viewer = OpenSeadragon(`)?

**Comment by Rafi993** [comment]
Hello there. Thanks for this awesome library I don't face this issue anymore. I'm closing this issue for now. please feel free to open it back if needed.
