### ISSUE TITLE
Does retina screen need different tile sources?

### ISSUE THREAD

**Issue by maskgk** [openseadragon/openseadragon#1692]
Firstly, it's really an amazing project!
I have read documents and some code. And I have a question,

Does the retina screen device need different tile sources? As you know, images feed to a retina screen always need sizes of _x_ times of the display size for plain web, where _x_ is the device pixel ratio.  So does Openseadrgon have the similar requirement, for instance, width field in custom tilesource option should be half of actual size when devicepixelratio is 2?

After I dig into the code for some time. I feel the answer is **NO** since the canvas is scaled up by device pixel ratio before tiles are drawn on. 

But I'm not sure, it would be better someone competent can confirm with me.

Thanks!

**Comment by iangilman** [comment]
You're correct: You do not need a different tilesource. OpenSeadragon takes care of drawing as many pixels as you need for the screen you have. Your tilesource should be as high resolution as you can make it, and if you're on a small or low resolution screen, OpenSeadragon will just use the low resolution parts of the tilesource.

**Comment by maskgk** [comment]
Thanks for your answer! @iangilman
