### ISSUE TITLE
How to disable drag event and resize event on annotation

### ISSUE THREAD

**Issue by siddharthray** [openseadragon/openseadragon#1693]
Hi, 
I am trying to disable drag and resize of the annotation. Can you help to give insight how to disable drag and resize on the annotation.

**Comment by iangilman** [comment]
Sounds like you're using the annotations plugin? You should file an issue there: 

https://github.com/Emigre/openseadragon-annotations/issues

For what it's worth, I don't know the answer to your question.

**Comment by siddharthray** [comment]
Thanks for reverting it back. I am using openseadragon-fabricjs-overlay.js

**Comment by iangilman** [comment]
I see! Then you might want to file an issue here instead: 

https://github.com/altert/OpenseadragonFabricjsOverlay/issues

When you say disable drag and resize, are you speaking about the ability inside Fabric itself to resize objects? If so, perhaps it's just a Fabric function you're looking for.
