### ISSUE TITLE
viewer.addOverlay & updateOverlay "placement" argument seems optional

### ISSUE THREAD

**Issue by alvaromartmart** [openseadragon/openseadragon#1694]
Documentation describes the `placement` argument in `viewer.addOverlay` and `viewer.updateOverlay` methods as required, but it seems to me that it's actually optional as the `Overlay` class constructor has a default value of `Placement.TOP_LEFT` if none is provided.

I have actually tested calling both methods without the `placement` parameter and it seems to work fine.

I'd be willing to open a PR modifying both methods documentation with regard to that argument.

**Comment by iangilman** [comment]
Good catch! Yes, please fix the docs, thank you!

**Comment by alvaromartmart** [comment]
Hi @iangilman, I just submitted the PR.

However, can you explain me how to proceed with regard to the *site-build* and *openseadragon.github.com* repositories? I'm not sure if I'm supposed to:
- `grunt publish` from *openseadragon* repo dir and `grunt doc` from *site-build* to rebuild the documentation.
- Submit PR to `site-build`
- `grunt publish` from *site-build* to rebuild the web.
- Submit PR to `openseadragon.github.com`

Am I expected to submit these two PR too or there's some CI workflow in charge of that?

**Comment by iangilman** [comment]
@alvaromartmart I'll take care of propagating these changes to `site-build` and then on to `openseadragon.github.com` when we release the next version. We don't really have a mechanism for updating the docs between versions.

Thank you for making the fix!

**Comment by iangilman** [comment]
Closed by #1696
