### ISSUE TITLE
Animate tilesource images separately?

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#1697]
I want to present two layers (JPG base and a PNG with transparency on top)
I can animate/transition them together.
My goal is to present them together, but allow for separate animation /transition (simultaneously).
https://chattanoogahistory.com/multi-test

Any suggestions would be appreciated.  Thank you.

```
            var box1 = new OpenSeadragon.Rect(
              0.2094,0.2088,0.7143,0.3042
            );
            var box2 = new OpenSeadragon.Rect(
              0.0061,0.0246,1.0286,0.4381
            );
            var transition1 = function() {
              viewer.viewport.zoomSpring.animationTime = 5.0;
              viewer.viewport.zoomSpring.springStiffness = 1;
              viewer.viewport.centerSpringX.animationTime = 50.0;
              viewer.viewport.centerSpringX.springStiffness = 0;
              viewer.viewport.centerSpringY.animationTime = 50.0;
              viewer.viewport.centerSpringY.springStiffness = 0;
              viewer.viewport.fitBounds(box1);
            };
            var transition2 = function() {
              viewer.viewport.zoomSpring.animationTime = 15.0;
              viewer.viewport.zoomSpring.springStiffness = 5;
              viewer.viewport.centerSpringX.animationTime = 30.0;
              viewer.viewport.centerSpringX.springStiffness = 5;
              viewer.viewport.centerSpringY.animationTime = 30.0;
              viewer.viewport.centerSpringY.springStiffness = 5;
              viewer.viewport.fitBounds(box2);
            };
            var transitions = [transition1, transition2];
            var step = 0;
            // Calling this function will move us to the next transition animation in our
            // list of transitions.
            var animate = function(){
              transitions[step++ % transitions.length]();
            };
            var viewer = new OpenSeadragon.Viewer({
              id: "openseadragon-canvas",
              prefixUrl: "/openseadragon/images_TEST/",
              tileSources: [
                {
                  type: 'image',
                  url:  'img/16background_bottom.jpg',
                  x: 1, 
                  y: 1, 
                  width: 2,
                }
                ,
                {
                  type: 'image',
                  url:  'img/16background_lg.png',
                  x: 1, 
                  y: 1, 
                  width: 2
                }
              ],
              mouseNavEnabled: false,     
              showFullPageControl: false,
              showNavigator:  false,
              showHomeControl: false,
              showZoomControl: false,
              showReferenceStrip:  false,
              defaultZoomLevel: 0.9,
            }
                                                 );
            // Every 10 seconds move to the next step in the animation cycle and repeat
            // so it continues indefinitely.
            viewer.addHandler('open', function(){
              // Call the first animation
              animate();
              // Schedule the rest of the animations each x seconds
              setInterval(animate, 8000);
            }
                             );
```
![Image](https://chattanoogahistory.com/img/16background_bottom.jpg)
![Image](https://chattanoogahistory.com/img/16background_lg.png)

**Comment by iangilman** [comment]
Cool! That's a neat idea :)

To get them to animate separately (I assume you want the foreground to grow a little quicker or something), you'll have to animate the images themselves. 

You could either forget about animating the viewport (as you normally do with fitBounds) and animate both of the images separately: 

```
var backgroundImage = viewer.world.getItemAt(0);
var foregroundImage = viewer.world.getItemAt(1);

backgroundImage.setPosition(new OpenSeadragon.Point(0.5, 0.1));
backgroundImage.setWidth(2.5); // Also animates the height appropriately

foregroundImage.setPosition(new OpenSeadragon.Point(0.4, 0));
foregroundImage.setWidth(3); // Also animates the height appropriately
```

...Or you could rely on the viewport for the main thrust of the animation and just animate one of the images as needed to adjust:

```
var foregroundImage = viewer.world.getItemAt(1);

viewer.viewport.fitBounds(box1)

foregroundImage.setPosition(new OpenSeadragon.Point(0.4, 0));
foregroundImage.setWidth(3); // Also animates the height appropriately
```

I'm thinking the latter is probably going to be easiest/best, but give them a try and see what you think. Of course you'll have to come up with your own numbers... Those are just made up for the example :)

**Comment by SamHall** [comment]
I've switched from images to DZIs - not sure if this changes your suggestions.
Now I'll stumble through the JavaScript and try to put things in the right place.
To get the effect I'm looking for, I'd need to zoom in on a point but each image would do so at a slightly different rate to give the 3D illusion effect.  
What I'm going for here:  https://vimeo.com/sph/review/354789802/7e11d1b4c4

**Comment by iangilman** [comment]
Yeah, the suggestions I gave you should work for any kind of tile source, including DZI. Make sure the foreground image has PNG tiles with transparency.

I can't see that video... Is it something you haven't published?

It occurs to me another option would be to actually have two viewers laid on top of each other. My recommendation, though, would be to first try the "all in one viewer, animating the viewport plus animating the foreground image" suggestion I have above.

Let me know how it goes!

**Comment by SamHall** [comment]
Corrected video link / edited. And thank you - I'll work with it.

**Comment by iangilman** [comment]
The video test looks lovely!

Another variation on the code that's occurred to me would be to animate the foreground layer in direct response to whatever changes were made to the overall viewport. In other words, set it up so that just zooming in is enough to trigger the foreground layer to change its size and position. Here's an example: 

```
function mapLinear(x, a1, a2, b1, b2, clamp) {
  var output = b1 + ((x - a1) * (b2 - b1)) / (a2 - a1);
  if (clamp) {
    var min = Math.min(b1, b2);
    var max = Math.max(b1, b2);
    return Math.max(min, Math.min(max, output));
  }

  return output;
}

viewer.addHandler('open', function() {
  var foregroundImage = viewer.world.getItemAt(1);
  var originalPosition = foregroundImage.getPosition();
  var originalWidth = foregroundImage.getWidth();
  
  viewer.addHandler('animation', function() {
    var zoom = viewer.viewport.getZoom(true);
    var xOffset = mapLinear(zoom, 1, 3, 0, -1);
    var yOffset = mapLinear(zoom, 1, 3, 0, -1);
    var widthScale = mapLinear(zoom, 1, 3, 1, 4);
    
    foregroundImage.setPosition(new OpenSeadragon.Point(originalPosition.x + xOffset, originalPosition.y + yOffset));
    foregroundImage.setWidth(originalWidth * widthScale, true); // Also changes the height appropriately
  });
  
  viewer.viewport.fitBounds(box1)
});

```

I think that might produce the most solid results.

The version above needs refinement, though, regarding the scale and positioning... You'll want to play with the numbers going into the three `mapLinear` calls to get it to do what you want.

**Comment by SamHall** [comment]
I truly appreciate the advice and I must again admit just how lousy I am at JavaScript. 

I don't believe I know exactly how to implement that code. (using the first post as an example).

After trying many ways, I keep getting:

**Comment by iangilman** [comment]
Whoops! I didn't actually test that code. Instead of:

```
var originalPosition = foregroundImage.getPosition();
var originalWidth = foregroundImage.getWidth();
```

It should be:

```
var bounds = foregroundImage.getBounds();
var originalPosition = bounds.getTopLeft();
var originalWidth = bounds.width;
```

I haven't tested that either, but it matches what's in the docs! Sorry for the confusion...

**Comment by SamHall** [comment]
Ah - I feel slightly less lousy : )
Some progress mixing and testing approaches. I'll keep at it.

https://chattanoogahistory.com/multi-test-too.php

https://chattanoogahistory.com/multi-test.php

**Comment by iangilman** [comment]
Cool! Looks like it's working :) now you just need to tweak the values. 

Also, another mistake in my code:

```
foregroundImage.setPosition(new OpenSeadragon.Point(originalPosition.x + xOffset, originalPosition.y + yOffset));
```

...should have a `true` at the end, like so:

```
foregroundImage.setPosition(new OpenSeadragon.Point(originalPosition.x + xOffset, originalPosition.y + yOffset), true);
```

That'll keep the motion more in sync with the viewport zooming, and should help avoid the "swoop" that it's currently doing.

**Comment by SamHall** [comment]
I believe this is going to work well. 
I included 4 layers. This is a fairly low resolution version - so it will only gets better.

https://chattanoogahistory.com/multi-test-too.php

Next improvement idea - allow for limited mouse/ touch interaction (mouseNavEnabled: true, 
) without 'destroying the canvas'.  
https://chattanoogahistory.com/multi-test-three.php

**Comment by iangilman** [comment]
That looks pretty great! Except for the slow frame rate, of course.

Do you still get the same slow frame rate with those four layers if you disable the extra animation stuff? Knowing the answer to that will help us figure out what to optimize.

BTW, you could combine all of the animation handlers into a single one which might be a little more efficient (though I don't know that it'll make a big difference), like so:

```
viewer.addHandler('animation', function() {
  var zoom = viewer.viewport.getZoom(true);
  
  var xOffset = mapLinear(zoom, 1, 40, 0, -1);
  var yOffset = mapLinear(zoom, 1, 60, 0, -1);
  var widthScale = mapLinear(zoom, 1, 60, 1, 3);
  foregroundImage.setPosition(new OpenSeadragon.Point(originalPosition.x + xOffset, originalPosition.y + yOffset),true);
  foregroundImage.setWidth(originalWidth * widthScale, true);

  xOffset = mapLinear(zoom, 1, 50, 0, -1);
  yOffset = mapLinear(zoom, 1, 70, 0, -1);
  widthScale = mapLinear(zoom, 1, 70, 1, 3);
  dogImage.setPosition(new OpenSeadragon.Point(originalPosition.x + xOffset, originalPosition.y + yOffset),true);
  dogImage.setWidth(originalWidth * widthScale, true);

  xOffset = mapLinear(zoom, 1, 20, 0, -1);
  yOffset = mapLinear(zoom, 1, 30, 0, -1);
  widthScale = mapLinear(zoom, 1, 30, 1, 3);
  treeImage.setPosition(new OpenSeadragon.Point(originalPosition.x + xOffset, originalPosition.y + yOffset),true);
  treeImage.setWidth(originalWidth * widthScale, true);
});
```

**Comment by SamHall** [comment]
That's certainly cleaner : )
Thank you.
I suspect the number of layers is the biggest issue.

**Comment by iangilman** [comment]
Agreed. I suppose if some of the layers are just small elements, you might try cutting them down to just the visible area... Having a lot of transparent tiles still takes up resources.

**Comment by SamHall** [comment]
I was making great progress by using cropped PNG tile sources but have hit a snag. 
Upon loading - the positions are not set until I interact with the canvas or apply a fitbounds.
Even then, the initial sizes cause the canvas to have to re-center, which is distracting.
What can I add to align upon opening (without having to animate into position)??

Example with a fitbounds event firing on open: 
https://chattanoogahistory.com/multi-test-six.php
![2019-09-08_00-17-23](https://user-images.githubusercontent.com/4950023/64483399-2aeb2600-d1cf-11e9-8e12-fff09165a004.png)
Example without - note images align on interaction: 
https://chattanoogahistory.com/multi-test-seven.php

![2019-09-08_00-17-16](https://user-images.githubusercontent.com/4950023/64483401-2f174380-d1cf-11e9-8c79-af796db9175c.png)

**Comment by iangilman** [comment]
It's looking good! The floaters are fun :)

And yeah, if you want everything to line up originally, you'll need to do the animation handler immediately on open, in addition to whenever it animates. Something like this:

```
            var foregroundImage, treeImage, floatersImage, originalPosition, originalWidth;
             
            function updateLayers() {
              var zoom = viewer.viewport.getZoom(true);

              var xOffset = mapLinear(zoom, 1, 80, .26, -1);
              var yOffset = mapLinear(zoom, 1, 80, .32, -1);
              var widthScale = mapLinear(zoom, 1, 80, .61, 3);
              foregroundImage.setPosition(new OpenSeadragon.Point(originalPosition.x + xOffset, originalPosition.y + yOffset),true);
              foregroundImage.setWidth(originalWidth * widthScale, true);

              xOffset = mapLinear(zoom, 1, 50, .05, -1);
              yOffset = mapLinear(zoom, 1, 50, .10, -1);
              widthScale = mapLinear(zoom, 1, 50, 0.30, 3);
              treeImage.setPosition(new OpenSeadragon.Point(originalPosition.x + xOffset, originalPosition.y + yOffset),true);
              treeImage.setWidth(originalWidth * widthScale, true);

              xOffset = mapLinear(zoom, 1, 8, .5, -1);
              yOffset = mapLinear(zoom, 1, 30, .32, -1);
              widthScale = mapLinear(zoom, 1, 10, .20, 3);
              floatersImage.setPosition(new OpenSeadragon.Point(originalPosition.x + xOffset, originalPosition.y + yOffset),true);
              floatersImage.setWidth(originalWidth * widthScale, true);
            }
            
            viewer.addHandler('open', function() {
              foregroundImage = viewer.world.getItemAt(1);
              treeImage = viewer.world.getItemAt(2);
              floatersImage = viewer.world.getItemAt(3);
              var bounds = foregroundImage.getBounds();
              originalPosition = bounds.getTopLeft();
              originalWidth = bounds.width; 
              
              updateLayers();
              viewer.addHandler('animation', updateLayers());        
            });
```

**Comment by SamHall** [comment]
That works!
I think I've futzed with this enough and will move in this direction with some transition steps added.
Thank you for all the help as usual - now to finish the actual page content.

https://chattanoogahistory.com/multi-test-8.php

**Comment by iangilman** [comment]
Sweet! I love that you keep pushing the envelope like this!

**Comment by SamHall** [comment]
The final published result.
Thanks for all the help!
https://chattanoogahistory.com/whiteoak

**Comment by iangilman** [comment]
Beautiful! Fun idea for a page header :)
