### ISSUE TITLE
ajaxHeaders not applied when retrieving reference strip thumbnails

### ISSUE THREAD

**Issue by eslawski** [openseadragon/openseadragon#1700]
Hello!

If I understand correctly the `ajaxHeaders` and `loadTilesWithAjax` configs can either be specified as a top level `OpenSeadragon` config, or on a per level basis as a `TileSource` config. 

We are currently providing the viewer an array of strings as the `tileSources` and using the `ajaxHeaders/loadtilesWithAjax` configs on the top level `OpenSeadragon` object. 

The main image loads correctly as the headers are applied as expected, however the each of the thumbnail requests for the reference strip DO NOT get the headers, and thus they do not load correctly.

I noticed the reference strip actually creates a handful of "mini viewers": https://github.com/openseadragon/openseadragon/blob/9506d6e5392e24aefa63608c9bb123f86f26424b/src/referencestrip.js#L441

Wondering if it would make sense to pass along the `ajaxHeaders/loadtilesWithAjax` configs from the parent viewer down to these mini viewers in order to preserve the top level setting?

Thanks!

**Comment by iangilman** [comment]
Yes, that sounds like exactly the right fix! I believe `loadTilesWithAjax` was added long after the reference strip and nobody thought to pipe it down into there.

Are you up for making the fix?

**Comment by eslawski** [comment]
Sweet! Yes we would be honored to make that enhancement!

**Comment by iangilman** [comment]
Awesome! Let me know if you need any pointers :)

**Comment by iangilman** [comment]
Fixed by #1701
