### ISSUE TITLE
Zoomify tilesets break between 2.3.1 and 2.4.1.

### ISSUE THREAD

**Issue by bluehaoran** [openseadragon/openseadragon#1704]
Hey there,

I have encountered an issue after upgrading from OSD 2.3.1 to 2.4.1, using Zoomify tiles.

I have created a side-by-side comparison. Left is 2.3.1, right is 2.4.1.

Initial load
![osd-231-v-241](https://user-images.githubusercontent.com/3521663/63904124-49288780-ca53-11e9-938d-3657bfdaa717.png)

Zooming in two clicks:
![osd-zoom-231-v-241](https://user-images.githubusercontent.com/3521663/63904129-4ded3b80-ca53-11e9-987e-7d92f086cf8a.png)

For reference, the Zoomify XML file is:
```
<IMAGE_PROPERTIES WIDTH="5472" HEIGHT="3648" NUMTILES="121" NUMIMAGES="1" VERSION="1.8" TILESIZE="512" />
```

The Code calling this is:
```
let image_url = '<<< S3 Bucket >>>';
let viewer = OpenSeadragon({
    id: "photo-viewer",
    debugMode: true,
        prefixUrl: "/assets/plugins/openseadragon-bin-2.4.1/images/",
        tileSources: {
                type:       "zoomifytileservice",
                width:      5472,
                height:     3648,
                tilesUrl:   image_url
        },
        maxZoomLevel: 12,
        navigatorHeight: 50,
        navigatorWidth: 50,
        animationTime: 0.5,
        ajaxWithCredentials: true
});
```
(The s3 bucket is a private one with specific CORS policies so I can't share that, and it wouldn't do much good besides.)

I don't know enough about OSD internals to know if it's a bug with our original zoomify tiling that's been fixed, or something introduced between 2.3 and 2.4.

Happy to provide more data.

**Comment by iangilman** [comment]
Yow! That's no good. 

It looks like it's still showing all of the correct tiles, but it's taking the upper left quadrant of each and zooming that to fill the tile space.

I'm guessing maybe it's related to https://github.com/openseadragon/openseadragon/pull/1426. Could you try verifying that? If so, then it has something to do with how we are calculating the tile source bounds in the case of Zoomify.

Any thoughts, @foobarable?

**Comment by foobarable** [comment]
I can have a closer look next week or the week after.
I have not updated to 2.4.1 yet so I didn't stumble upon the error.

Also: The zoomify tilesource still does not consider the XML file 
generated by zoomify. Maybe this could also cause some error here.

**Comment by iangilman** [comment]
@foobarable Great! I look forward to hearing what you find :)

**Comment by bluehaoran** [comment]
I'm not an expert with the OSD code, but if the XML is not being parsed properly, then it might not notice we're using a tilesize that's probably double the normal (512)? Because each of the tiles on te right is about half what it should be.

**Comment by iangilman** [comment]
Yes, that would be exactly it! Note this line in the code: 

https://github.com/openseadragon/openseadragon/blob/f803fb9ad432c39dc49c79a24534405ae57eacb8/src/zoomifytilesource.js#L21

Strange that it worked in 2.3.1, though... I think it's always been hardcoded. Hmm... I guess it is #1426, which now does a better job of honoring the tile size that the tilesource comes up with.

So... I think the solution is to update the Zoomify tilesource to recognize the tile size instead of just hardcoding it to 256.

**Comment by iangilman** [comment]
Fixed by https://github.com/openseadragon/openseadragon/pull/1868

@abrlam if you're up for it, it might be worth adding `tileSize` to the example on:

https://github.com/openseadragon/site-build/blob/master/www/tilesource-zoomify.html
