### ISSUE TITLE
Error with Chromium over Raspbian OS

### ISSUE THREAD

**Issue by jpereiranet** [openseadragon/openseadragon#1705]
Hello: 
I am working in a project with Chromium (74.0.3) over Raspbian 10 and DZI images, the render show as:  

![Captura de pantalla 2019-08-29 a las 16 26 21](https://user-images.githubusercontent.com/7705267/63949112-26f63000-ca7a-11e9-9cf6-738fb7ea4469.png)

Anybody has some advice about the error?

Thanks!
jose

**Comment by iangilman** [comment]
Strange! Looks like that's http://openseadragon.github.io/examples/tilesource-dzi/, and I assume it's working fine on your other browsers? Is that browser showing trouble in other areas?

**Comment by jpereiranet** [comment]
Hello: 

Yes, it is the DZI example from Openseadragon website! 
Chromium fails with all Openseadragon DZI Viewers that I could test it.  On Raspian 10: Firefox, Midori and Suckless Surt  run fine with Openseadragon and DZI files.

**Comment by iangilman** [comment]
Well, I don't know that I have any good theories. It looks like it's loading the tiles wrong some how, but I'm not sure why. Let me know if you have questions I can answer, but otherwise you'll probably have to be the one to debug this, since you're the one on that device/browser combo.
