### ISSUE TITLE
Local file JPG support

### ISSUE THREAD

**Issue by dw41020** [openseadragon/openseadragon#1706]
I'm trying to load a JPG from a local directory (C:\xxx\xxxx) but when I change the "url:" to 
"url: 'file:\\\C:/xxx/xxx/yyy.jpg'",  it fails to load the JPG file and the Browser I'm using will load it if I type "file:\\\C:/xxx/xxx/yyy.jpg" in the url address bar.

OpenSeadragon({
    ...
    tileSources: {
        type: 'image',
        url:  '/example-images/grand-canyon-landscape-overlooking.jpg',
        buildPyramid: false
    }
    ...
});

**Comment by msalsbery** [comment]
Is it just the backslash? Try \\\\ instead of \\

**Comment by dw41020** [comment]
It's actually "file:///c:\xxx\xxx\yyy.jpg",   not "file:\\......,  mis-typed it.

The code actually has "\\" instead of "\",   I've also tried changing all of the "\\" to "/".

Here's what the HTM file contains:

<div id="openseadragon1" style="width: 800px; height: 600px;"></div>
<script src="/openseadragon-bin-2.4.1/openseadragon.min.js"></script>
<script type="text/javascript">
		var viewer = OpenSeadragon({
			id: "openseadragon1",
			prefixUrl: "/openseadragon-bin-2.4.1/images/",
		tileSources: {
			type: "image",
			url:  "file:///C:/Temp/rfidtag280.jpg",
			buildPyramid: false
			}
		});
</script>

**Comment by aleeex325** [comment]
Hi, I think you could have a look at this page (http://openseadragon.github.io/docs/). At the end of it, it says 
"If you are working directly from the file system (accessing your web page from file:///path/to/your/file.htm) you may need to change your browser's local files security policy so that your zooming image data can be loaded. Alternatively, you can run a local server. You can find help on both methods in three.js documentation." 
And you may find some useful information about osd with local file.
Hope it will help you.

**Comment by dw41020** [comment]
I looked at the information,  but the browser allows for the JPG to load if I type the same string into the url address bar.  It's only from openseadragon that the image will not load.
So I believe it's how openseadragon is processing the url or local file string.

**Comment by iangilman** [comment]
Yes, OpenSeadragon draws the images onto a canvas, and there are stricter security rules around doing that. If you don't want the smoothness of Canvas, you can include `useCanvas: false` in your options when you create your viewer; that may help with this issue.

**Comment by dw41020** [comment]
OK, I will give that try.  Thanks.

**Comment by dw41020** [comment]
Using  useCanvas: false   did not help.  Same issue.  
It turns out the JPG files that will be accessed is on a remote server,  so I tested setting up a local Web Server on it and was able to access the JPGs using a http:\.... url.

On a side note, on the local server I was able to access the JPGs if the files were located under the 
local Web server folder and used the http path to it vs file:///.....   I was hoping to give the user  the option of storing file anywhere locally.

**Comment by msalsbery** [comment]
There may browser-dependent ways to override security policy to allow reading local files, but in general it’s not allowed except for user action (click) and the File API, which isn’t going to work for the image tiles

**Comment by dw41020** [comment]
On a side note:   Is there a cache used by OpenSeaDragon?  I've seen it when the JPG I'm trying to load doesn't but display the previous JPG,  although the HTML called contains a different JPG name.  I tried adding code to the HTML to turn off browser caching.  If OpenSeaDragon has a cache how can it be turned off?   The Canvas is turned off.

**Comment by iangilman** [comment]
Are you talking about when the page refreshes, or when you change things while the page is still running?

**Comment by dw41020** [comment]
When the page refreshes,  when I load a new HTML which opens the OpenSeaDragon viewier with a new JPG.

**Comment by iangilman** [comment]
OpenSeadragon doesn't do any sort of local caching that would survive a refresh. I'm not sure what would be causing the issue you're seeing.

**Comment by xgui3783** [comment]
Possible that the server of the tiles has a cache or unchanging etag header?

Either way, for development, one can always open development tool in
Chrome/FF, and check the box "disable cache" under "network".

Or use an incognito window, which should also ignore caches.
