### ISSUE TITLE
Question: how image loader handle raw pixel data?

### ISSUE THREAD

**Issue by WindVestige** [openseadragon/openseadragon#1708]
For pyramid image, I used 'getTileUrl' to build the request url and the Image load will send ajax request to get data.

But actually, my back end API will response blob data which is not image blob but the image pixels array. I need to process this data firstly, and change it to image then send it to OpenSeaDragon.

Is there any way I could handle this kind of situation?

**Comment by iangilman** [comment]
That sort of scenario was just discussed in https://github.com/openseadragon/openseadragon/issues/1707. I think your options are the same as listed there.
