### ISSUE TITLE
Question: How can I use OpenSeaDragon in Angular 8 in combination with OpenSeadragonSelection Plugin or other Plugins?

### ISSUE THREAD

**Issue by ArgV04** [openseadragon/openseadragon#1709]
I want to use OSD for a deep zoom images case in my Angular 8 App.  For this I installed the Types declaration stuff for OpenSeadragon library from [here](https://github.com/alvaromartmart/types-openseadragon).

This works and I was able to instantiate a Viewer instance and get some DZI-Images displayed. Now I want to use the OpenSeadragonSelection from [here](https://github.com/picturae/openseadragonselection) too.

But I am not able to access to the plugin extension methods provided in the plugin. So roughly the Plugin add some additional methods to the Viewer for example:

`$.Viewer.prototype.selection ... `

... But I am not able to access these extensions. Do someone know how I can use the plugin in my angular components typescript file?

Thanks

**Comment by marksabado-pulsar** [comment]
> > Can I ask for a clarification of the question? Is it that you would like the plugin to work (with or without types), or you already have the plugin working, but would like the benefit of types?
> > I work with angular and osd on two separate projects, and may be able to help with something.
> 
> Hi :)
> 
> so yes, I got the core OSD Lib working and also in combination with some OSD Plugins in Angular 8.
> 
> There was a strange issue with the OSDSelection Plugin, which is not the newest version in the npm repository when using npm install, so I needed to add the Lib directly from their git-repo.
> 
> There is a type support for the OSD Lib here available: https://github.com/alvaromartmart/types-openseadragon
> 
> But currently having trouble when using types supporting for the OSD core functionality in combination with plugins where there are currently no typescript type support. There for example I am getting errors when trying to access some plugin-extension methods: **ERROR, function does not exist and so on**. I already asked the guys there for support :)
> 
> So currently it works only with combination of plugins when using the imported OSD Libs directly in typescript.
> 
> How do you using the OSD in your angular apps?

Hi, can you show me how to use the OSDselection in angular? Somehow I don't have any luck with this

**Comment by marksabado-pulsar** [comment]
> > > Can I ask for a clarification of the question? Is it that you would like the plugin to work (with or without types), or you already have the plugin working, but would like the benefit of types?
> > > I work with angular and osd on two separate projects, and may be able to help with something.
> > 
> > 
> > Hi :)
> > so yes, I got the core OSD Lib working and also in combination with some OSD Plugins in Angular 8.
> > There was a strange issue with the OSDSelection Plugin, which is not the newest version in the npm repository when using npm install, so I needed to add the Lib directly from their git-repo.
> > There is a type support for the OSD Lib here available: https://github.com/alvaromartmart/types-openseadragon
> > But currently having trouble when using types supporting for the OSD core functionality in combination with plugins where there are currently no typescript type support. There for example I am getting errors when trying to access some plugin-extension methods: **ERROR, function does not exist and so on**. I already asked the guys there for support :)
> > So currently it works only with combination of plugins when using the imported OSD Libs directly in typescript.
> > How do you using the OSD in your angular apps?
> 
> Hi, can you show me how to use the OSDselection in angular? Somehow I don't have any luck with this

Nevermind I followed this steps: https://github.com/alvaromartmart/types-openseadragon/issues/5#issuecomment-532053867

**Comment by omerbenzvi** [comment]
regarding to this issue does anyone knows where can I find support to OpenSeadragonFilter Plugin for 
typescript (an update index.d.ts file that support this plugin)

thanks

**Comment by dhandeeswaran** [comment]
I am integrated OpenSeaDragon, fabricjs with Angular 10. its working fine for me. please refer the link. 

https://github.com/dhandeeswaran/annotation.git

**Comment by iangilman** [comment]
@dhandeeswaran thank you for sharing this!
