### ISSUE TITLE
Add a drawing tool with fixed shape

### ISSUE THREAD

**Issue by luistelmocosta** [openseadragon/openseadragon#1710]
Hello, I would like to add a fixed polygon shape to my drawing tool in OpenSeaDragon.

Is there any simple and straightforward example on how to do this?

kind regards

**Comment by iangilman** [comment]
There are a few plugins that could help you with this sort of thing: http://openseadragon.github.io/#plugins

Take a look at the Fabric, Paper, Canvas, and SVG plugins. You'll still have to draw the polygon yourself, but they give you a surface you can use to draw it on.

**Comment by luistelmocosta** [comment]
Thank you very much. This is almost what I am looking for. I want something like Fabric.js but instead of having a free tool, I want a default shape (a rectangle) and only that shape can be used to draw.

**Comment by iangilman** [comment]
Cool. You might be looking for https://github.com/picturae/openseadragonselection then.
