### ISSUE TITLE
Use keyboard to go through all overlays

### ISSUE THREAD

**Issue by luistelmocosta** [openseadragon/openseadragon#1711]
Hello, is there any example on how to do this? 

How can I configure my keyboard arrows to go from one overlay to another?

**Comment by iangilman** [comment]
Do you mean you want keyboard focus to move from one overlay to the next when you hit tab? What's in your overlays that you would want keyboard focus for (just so I understand the scenario)?

**Comment by luistelmocosta** [comment]
I added several overlays to my viewer using `addOverlay()` function. Now, I want to be able to go through all the overlays using my keyboard arrows (go to the next/previous one) so the person that uses the app can check if the annotations are correct.

**Comment by antonioxdias** [comment]
I brewed you a quick codepen example.
You just need to fit your viewport using the bounds of your overlay.

[https://codepen.io/antonioxdias/pen/VwZEodV](https://codepen.io/antonioxdias/pen/VwZEodV)

(I wouldn't recommend using your arrow keys, as osd uses those for movement by default. If you do want them, consider preventing the default osd behaviour from happening.)

**Comment by luistelmocosta** [comment]
Thank you!
However, I dont have an overlays array, I added my annotations using `addOverlay` function. Is there any way to use what you sent with the `currentOverlays`?

**Comment by luistelmocosta** [comment]
Also, I used your snippet and the arrows are still with the default action. Any idea what's wrong?

**Comment by antonioxdias** [comment]
> Thank you!
> However, I dont have an overlays array, I added my annotations using `addOverlay` function. Is there any way to use what you sent with the `currentOverlays`?

Isn't currentOverlays just an array of all overlays in your viewer? If so you can just iterate it the same way and use the bounds to set your viewport.



> Also, I used your snippet and the arrows are still with the default action. Any idea what's wrong?

Not sure what you mean.... Are the arrows not working at all?

**Comment by luistelmocosta** [comment]
> Isn't currentOverlays just an array of all overlays in your viewer? If so you can just iterate it the same way and use the bounds to set your viewport.

Well, I'm having some problems because currentOverlays is always empty.

> Not sure what you mean.... Are the arrows not working at all?

Its not working at all, I actually changed to J and K since these keys are not being used but the same happens

Here's a [gist](https://gist.github.com/luistelmocosta/dbba827f2a1eb9dded95494973179e85) with my code

Thank you for your help, much appreciated!

**Comment by antonioxdias** [comment]
@iangilman I'll pm @luistelmocosta with some more specific help. I'd say the issue could be closed as is, since the main question has been answered.

Else, we could further the discussion here :+1:

**Comment by luistelmocosta** [comment]
How are you going to DM me? Should I give my email or something?

**Comment by antonioxdias** [comment]
I just assumed your github email would be correct... :D

**Comment by iangilman** [comment]
@antonioxdias Thank you for helping @luistelmocosta on this!
