### ISSUE TITLE
Rectangle selection

### ISSUE THREAD

**Issue by PpyMohan** [openseadragon/openseadragon#1712]
Hi,

i have rotated open sea dragon viewer after that if i use rectangle selection it is drawing some other  place

**Comment by iangilman** [comment]
Are you referring to the https://github.com/picturae/openseadragonselection/ plugin? Looks like there's already an issue filed for this: 

https://github.com/picturae/openseadragonselection/issues/1

...And it looks like someone has even proposed a fix there.

**Comment by PpyMohan** [comment]
Hi,
Thanks for your replay i have attached the image in that i have mention
what's the issue i am facing.

And my code :

var rectButton = document.getElementById("rect");
                    $scope.viewerSelection = $scope.viewer.selection({
                        restrictToImage: true,
                        toggleButton: rectButton,
                        onSelection: function (rectangle) {
                            $scope.strokeArray.length = 0;
                            var x1 = parseInt(rectangle.x);
                            var y1 = parseInt(rectangle.y);
                            var arr = [x1, y1];
                            $scope.strokeArray.push(arr);
                            var x2 = x1 + rectangle.width;
                            var y2 = y1 + rectangle.height;
                            var arr2 = [x2, y2];
                            $scope.strokeArray.push(arr2);
}
});

**Comment by iangilman** [comment]
You should try the fix I mentioned above... It's the code in this PR: 

https://github.com/picturae/openseadragonselection/pull/24

**Comment by PpyMohan** [comment]
Did you saw my output

**Comment by iangilman** [comment]
Yes, the image you shared looks consistent with the bug described in https://github.com/picturae/openseadragonselection/issues/1 so I expect it can be fixed by the code changes listed in https://github.com/picturae/openseadragonselection/pull/24/files.

**Comment by PpyMohan** [comment]
Thanks for your reply. I will check this

**Comment by PpyMohan** [comment]
I tried it. but not working same problem.

**Comment by iangilman** [comment]
So you applied those changes to the plugin and used that one instead? Did you see any difference at all?

You might try posting in https://github.com/picturae/openseadragonselection/issues/1 and seeing if they have any thoughts.
