### ISSUE TITLE
Question: could we store the tilesource(dzi file and images folder) on 3rd party server? 

### ISSUE THREAD

**Issue by Robinxbnie** [openseadragon/openseadragon#1715]
I am trying to use  OpenSeaDragon to show some big images. The idea is to store the dzi file and images served by another server. I am trying to provide the url for tileSource which is "http://localhost: 8001/dzi/xxx.dzi"(this url is good and I can use any browser to download the dzi file manually) instead of the relative path shown in the examples (like 'dzi/xxx.dzi' which means the local server which openseadragon is served and which is on localhost:8080 in my case.
The fetching data quietly failed (no complaints/errors) but only show the buttons and navigator frame, without giving the images itself. It seems I am not able to make the images to display cross domains/servers. 
I am very new to the OpenSeadragon, and my question is: how to make the data fetching from different server/place?

**Comment by iangilman** [comment]
Discussed on Gitter, but adding here for posterity: Sounds like you need to set up CORS, but there are techniques to work around that if you'd rather, such as: 

https://codepen.io/iangilman/pen/gpejpJ

More discussion here: 

https://gitter.im/openseadragon/openseadragon?at=5d93757f47de0a719d440790
