### ISSUE TITLE
Overlays select area

### ISSUE THREAD

**Issue by luistelmocosta** [openseadragon/openseadragon#1717]
Hello, 

Is there any example/plugin that uses a rectangle to select a group of annotations (and changes the color when those are selected)? 

Instead of going through the annotations one by one, I would like to select a group of annotations and label them simultaneously

Can you suggest me something related to this?

**Comment by iangilman** [comment]
There are a number of OpenSeadragon plugins: 

http://openseadragon.github.io/#plugins

...But I'm not aware of anything that's exactly like that. You might be able to use the code from the selection plugin:

https://github.com/picturae/openseadragonselection

...As a starting point.
