### ISSUE TITLE
Keyboard nav for sequence: next/previous?

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#1718]
I may have overlooked it, but cannot find a keyboard event for next > previous < sources when using sequence mode.
If there isn't one built-in, what code would be used to make it so?
I use a localized version of Openseadragon on a laptop for presentations at speaking events - having more keyboard interaction would be nice.

Thanks.

**Comment by iangilman** [comment]
There is not such a keyboard event, but I agree it would be handy! If you want to build it on top of OSD, you just need to listen for key events and figure out what key was pressed. For the actual next/previous, you can steal the code from here:

https://github.com/openseadragon/openseadragon/blob/92904b7ac9f46583a3ba9237446c0608a0eb2ca0/src/viewer.js#L3525

If you wanted to make a patch to OSD to support this, you'd want to make those functions actually members of the Viewer, and then add handlers here:

https://github.com/openseadragon/openseadragon/blob/92904b7ac9f46583a3ba9237446c0608a0eb2ca0/src/viewer.js#L2583

Any thoughts about what keys would be good for this feature?

**Comment by RammasEchor** [comment]
Hi! I'm interested in this issue, and I'm going to give it a try.

**Comment by iangilman** [comment]
Please do! :)

**Comment by iangilman** [comment]
Fixed by #2007

**Comment by joedf** [comment]
@iangilman Shouldn't this issue be closed? Just checking...

**Comment by iangilman** [comment]
@joedf Sure looks like it! I must have spaced out when I wrote the "fixed" comment and missed the "close with comment" button :D

**Comment by joedf** [comment]
No worries! I thought it was open and up for grabs. Just want to contribute what I can to the project. I don't mean to be annoying or bureaucratic. Love openseadragon, thanks for keeping it alive!

**Comment by iangilman** [comment]
@joedf Not at all... I really appreciate all of your help!
