### ISSUE TITLE
Tile Map Services for Openseadragon or how to get dzi - Files

### ISSUE THREAD

**Issue by hhentschel** [openseadragon/openseadragon#1720]
Hello,
i read through all the questions and topics regarding the issue with TMS support for
openseadragon, but cannot get any further, or there are some questions left.

I got openseadragon to work with a basic image, but i will have larger images than
2000 x 2000px. 
Because i have MapTile from another project, i tried to use these files, but it does`nt work.
Then i clicked me through different services for generating .dzi Files, but i cannot get it to work. Partly because some links don´t work anymore, partly because i do not know what to do, partly because it is only for WIndows.
I tried MagickSlicer, but no luck.

So, before i post Code Examples; what would be the best way in end 2019 to generate (on a mac) dzi image Files to use openseadragon ?
Best would be to be able to use MapTile because then my customer could use it easily to generate the image by herself, but open for other suggestions.
Thank you very much.
Kind regards,
Henrik

**Comment by iangilman** [comment]
I'm afraid I don't know a lot about TMS; is it the same as MapTile? What is the issue you're having with it? It would be great to improve our TMS support.

As for creating DZI on a Mac, my favorite these days is VIPS: 

https://libvips.github.io/libvips/

...using `dzsave`: 

https://libvips.github.io/libvips/API/current/Making-image-pyramids.md.html

It's fast, it works with giant images, it's reliable, and it works on Mac (as well as Windows and Linux, I believe).

**Comment by hhentschel** [comment]
Thanks a lot.
I tried VIPS and i got it to work. Now i only have to connect it to my CMS (Craft) somehow.

Regarding TMS. I am not so familiar with it either. I just have the Programm MapTile from my Client, for which i redo their Website. So they could make these large Map-File of the Images by themself.
Now they would like a different viewer (before they had a leadlet adaption) and actually i found the connection between TMS and MapTile on your website.
Anyway, if i produce files via MapTile and try to show them via openseadragon, nothing shows. It seems the files cannot be found, or the file structure is different.

But now it works via VIPS, it is just not so convinient for my client, to go over the terminal,
to get the images.

**Comment by iangilman** [comment]
Well, if you'd like to debug the TMS connection, I'm happy to help answer questions. Are there any errors in the console?

Anyway, I'm glad you got the VIPS working :)
