### ISSUE TITLE
Js error with short multitouch

### ISSUE THREAD

**Issue by j-hudecek** [openseadragon/openseadragon#1724]
When I touch a OSD viewer with multiple fingers and quickly remove one I get this error:

    openseadragon.js:4652 Uncaught TypeError: Cannot read property 'minus' of undefined
    at getPointRelativeToAbsolute (openseadragon.js:4652)
    at updatePointersUp (openseadragon.js:6099)
    at updatePointersCancel (openseadragon.js:6420)
    at onPointerCancel (openseadragon.js:5577)
    at HTMLDivElement.pointercancel (openseadragon.js:3331)

It seems to be cause by the GPoint coming from onPointerCancel where it's initialized just with type and id and not position.

**Comment by msalsbery** [comment]
On all browsers or specific browser(s)?

**Comment by j-hudecek** [comment]
Chrome and Vivaldi so far. It's kinda hard to replicate - touch one finger, touch second, remove first and remove second finger very quickly.

**Comment by iangilman** [comment]
I think I've encountered stuff like this before. We need to be better about not assuming that our pointer arrays have as many elements as we think they do.

@j-hudecek  would you be up for doing some debugging on this?

@msalsbery  how's your work in this area coming?

**Comment by j-hudecek** [comment]
@iangilman Sure, I got this new touchscreen laptop so I gotta put it to good use

**Comment by iangilman** [comment]
Great! Interesting you're on a touch screen laptop... Have you been able to reproduce this on a phone or tablet? Just curious if it's specific to laptops.

Anyway, the code file in question is mousetracker.js, and it's a pretty gnarly one! It's designed to support mouse, touch, and the pen events that you can get on e.g. a Microsoft Surface. Looks like you've already taken a look at it, but let me know if you have questions.

@msalsbery any thoughts on the difference between pointercancel vs pointerup? Is that a clue?

One approach here would be to just make sure updatePointersUp never calls getPointRelativeToAbsolute with an undefined point. Of course beyond that it would be good to know why it's happening, in case it's a symptom of some deeper issue.

**Comment by iangilman** [comment]
Here's another report on the same issue (I think): https://github.com/openseadragon/openseadragon/issues/1728

**Comment by sanli** [comment]
I will try on some lower OSD release(2.3.x), and let you know the result.

**Comment by iangilman** [comment]
@sanli good to know.

If you are interested in debugging the problem, you can coordinate with @j-hudecek here so you are working together on it :)

**Comment by deminoth** [comment]
`gPoint.currentPos` can be undefined if you use iPad-specific gestures (e.g. Swipe up with four (or five) fingers).
![스크린샷 2019-11-29 오후 2 52 16](https://user-images.githubusercontent.com/495412/69846649-0b3c3900-12b8-11ea-8e5a-0a773bff0f7a.png)
so `updatePointersExit`, `updatePointersMove`, `updatePointersUp` (and other functions that I didn't find out) have same issue. 
Would I make PR for this issue? or someone is working on it?

**Comment by j-hudecek** [comment]
I didn't have time to start working on it yet, 13.1 broke more things on my app. So, feel free to work on it.

**Comment by iangilman** [comment]
@deminoth Yes, if you have a fix, please share it!

**Comment by deminoth** [comment]
I made a fix and testing internally in my company. If there are no error reports on real uses, I'll send a PR.
https://github.com/lunit-io/openseadragon/commit/831c06c49919c9c2ef6faadf47cf5de59505b914

**Comment by iangilman** [comment]
@deminoth Awesome... looks reasonable to me. I look forward to hearing how the testing goes, and hopefully seeing a PR :)

@msalsbery you might want to take a look...

**Comment by iangilman** [comment]
Okay, I've merged the PR from @deminoth (thank you!)... can everyone else test the latest master and see if it fixes this issue for them?
