### ISSUE TITLE
show cross hair on click location on openseadragon image 

### ISSUE THREAD

**Issue by sampathchowdary** [openseadragon/openseadragon#1725]
I want to show the last click position on image as some (cross hair)image

```
            const img = new Image();
            img.src='http://cdn.onlinewebfonts.com/svg/img_79088.png';          
            let imgpoint = new OpenSeadragon.Point(imagePoint.x, imagePoint.y);
            let canvas = document.getElementsByTagName("canvas")
            let ctx = canvas[0].getContext("2d");
            ctx.clearRect(0,0,canvas.width,canvas.height);
            ctx.beginPath();
            ctx.drawImage(img,imgpoint.x,imagePoint.y,25,25);
            ctx.stroke();
```
This code is working for some clicks i am able to see the image on openseadragon image, but not for every click, and all old clicks are still visible(clear Rect is not working)

Thanks

**Comment by msalsbery** [comment]
Are you sure you’re getting the right canvas element every time?

**Comment by sampathchowdary** [comment]
yes, clicks visibility is like 1: no, 2:yes,3: yes, 4:removes all points( 2,3), 5.No, 6. yes........11 or 12:no (removes all previous) its going loop 
Thanks

**Comment by iangilman** [comment]
If you want to draw with Canvas on an OpenSeadragon viewer, I highly recommend using the Canvas Overlay plugin:

https://github.com/altert/OpenSeadragonCanvasOverlay

If you really want to do it yourself (without the plugin), make sure you get right canvas, which you can access directly from `viewer.drawer.canvas` and then make sure to draw your stuff again after every time the viewer updates (watch for the `update-viewport` event).

**Comment by sampathchowdary** [comment]
I implemented without plugin, but i am able to log the click position but not able to show the every click position on image.
The values viewer.drawer.canvas for clearRect is clearing the original image
Thanks

**Comment by iangilman** [comment]
Yes, the canvas is cleared every frame. You need to do something like:

```
viewer.addHandler('update-viewport', function() {
  // Redraw all of your points to viewer.drawer.canvas
});
```

**Comment by sampathchowdary** [comment]
Thanks a lot.
 Both(plugin and clearing canvas) ways are working fine.
