### ISSUE TITLE
Scalable overlay text

### ISSUE THREAD

**Issue by 742617000027** [openseadragon/openseadragon#1726]
Hey, first of all, thanks for this awesome library! I'm using OSD [to create a visual representation of the board state of an SciFi MMO game](https://farverona.742617000027.de/) usually exclusively played through spreadsheets.¹ Right now, for the planet names (displayed at the bottom of the grey circles representing planets), I'm using .png files as overlays. Since I'm planning to make the whole thing more dynamic, what I would like to do is replace those .png files with actual HTML text. Unfortunately, I can't seem to figure out how to create text overlays with OSD that scale according to the zoom level of the map. Have I just missed a simple solution? Help would be greatly appreciated, and thanks in advance!

 ¹ It's based on the Faction Turn of the Stars Without Number RPG, [you can check the whole thing out here](https://www.youtube.com/watch?v=H7jv7soOj3g) if you're interested.

**Comment by iangilman** [comment]
Wow, that's cool use for OpenSeadragon! Do you mind if we add it to our examples page?

http://openseadragon.github.io/examples/in-the-wild/

Probably the easiest way to add scalable overlay text is with the SVG overlay plugin: 

https://github.com/openseadragon/svg-overlay

You can see an example of it in action here (click on one of the photos):

https://iangilman.com/openseadragon/flickr/

**Comment by 742617000027** [comment]
Awesome, thanks for the quick reply, will check out SVG overlays! And by all means, I'd be flattered if you added my project to the examples page! Just don't look too closely at the messy code 😄

**Comment by iangilman** [comment]
Awesome. I've added it to the issue for "In the Wild": 

https://github.com/openseadragon/site-build/issues/200

It may take a while before someone gets around to actually adding it. You're welcome to do so if you'd like; just make a PR against:

https://github.com/openseadragon/site-build/blob/master/www/in-the-wild.html
