### ISSUE TITLE
I'm missing something simple !

### ISSUE THREAD

**Issue by iainrs** [openseadragon/openseadragon#1727]
[testing locally with Xubuntu, VisualStudioCode and Chromium-browser ]
I've  got a 4000x4000 px  image which I can view with seadragon (zooming and dragging)  as 
follows

```
<div id="openseadragon1" style="width: 800px; height: 600px; background-color: #434343;">/div>
<script src="./seadragon/openseadragon.min.js"></script>
    var viewer = OpenSeadragon({
        id: "openseadragon1",
        prefixUrl: "./seadragon/images/",
        tileSources: {
            url: "./tile_source/bigmap.jpg",
            type: 'image
        }});
</script>
```

I then created tiles (apparently successfully) with  MagickSlicer. bigmap.dzi :
```
<?xml version="1.0"?>
<Image TileSize="256" Overlap="0" Format="jpg" xmlns="http://schemas.microsoft.com/deepzoom/2008">
<Size Width="4000" Height="4000"/>
</Image>
```

When I replace the viewer with
```
var viewer = OpenSeadragon({
    id: "openseadragon1",
    prefixUrl: "./seadragon/images/",
    tileSources: "./tile_source/bigmap.dzi"
});
```

I get  "Unable to open [object Object]: Unable to load TileSource"

DevTools Console shows

```
Access to XMLHttpRequest at 'file:///home/iain/Data/iain/doxeyca/www/tile_source/bigmap.dzi' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

tilesource.js:692 No TileSource was able to open ./tile_source/bigmap.dzi #document

tile_source/bigmap.dzi:1 Failed to load resource: net::ERR_FAILED
﻿```

Where should I be looking ?

(as you can probably tell my js knowledge is very limited)
thanks

**Comment by iangilman** [comment]
[I've edited your comments to fix the code blocks, using ```.]

It looks like you're running your web page directly from your file system without starting a local web server. You're likely to run into a number of issues doing that. See the note at the bottom of this page: 

http://openseadragon.github.io/docs/

I'd recommend getting that sorted out first.

Another thing you might try is changing the `dzi` extension to `xml`; OSD expects either (and DZI is just a specialized XML), but some servers know what to do with XML better.
