### ISSUE TITLE
Is there any way to use Openseadragon viewer, with Leaflet, Leaflet Draw?

### ISSUE THREAD

**Issue by davidbu01** [openseadragon/openseadragon#1729]
Hi!
I want to use the leaflet draw (http://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html) elements (placing markers, rectangles, circles on the screen), with the OSD viewer. 
Yes, leaflet has his own viewer, but in leaflet, zooming and dragging is not that fluid, smooth as in Openseadragon. 
Is there any integration between Leaflet and Openseadragon?
Basically, i want to use the Openseadragon  fluid, smooth viewer with the Leaflet Draw, because i want to place markers, circles, rectangles, etc. Is there any chance or advice?
Thanks!

**Comment by iangilman** [comment]
I'm glad you like our fluid movement! :)

There's no integration between OSD and Leaflet, so Leaflet Draw won't work. We do have a number of drawable overlay plugins, though (canvas, svg, Fabric, and Paper)... See: 

http://openseadragon.github.io/#plugins

**Comment by davidbu01** [comment]
Of course I like it. :)

I understand, thank you for your answer Ian!
