### ISSUE TITLE
Aspect ratio on small images

### ISSUE THREAD

**Issue by Giancarlos** [openseadragon/openseadragon#1730]
Somewhat related to #323 except I'm unable to get the image to zoom out to it's 1:1 size. My image is small it is 125x125 and on 1080p OpenSeadragon forces it to stretch out. Is there some configuration I have to define to allow this image to be zoomed out to it's original size and to default it to said size?

Also if there's a related issue that might help let me know and I will try. I've been experimenting with the configuration and yielded poor results thus far.

**Comment by iangilman** [comment]
You need to adjust the `minZoomLevel` to allow it to zoom out that far. For instance: 

```
        viewer.addHandler('open', function() {
          var naturalZoom = viewer.viewport.imageToViewportZoom(1);
          viewer.viewport.minZoomLevel = naturalZoom;
          viewer.viewport.zoomTo(naturalZoom, null, true);
        });
```

**Comment by Giancarlos** [comment]
This worked! I knew I was missing something along those lines, thanks!
