### ISSUE TITLE
Animate the rotation when button to rotate viewport is clicked

### ISSUE THREAD

**Issue by nikreations** [openseadragon/openseadragon#1736]
I have created a button which when clicked rotates the viewport. Is there a way to animate this (similar animation when zoom is clicked)? At the  moment rotation happens instantly. I found that there is optional "Immediately" in setRotation method of TiledImage but no such option on Viewport's setRotation method and I couldn't get the TiledImage's method to work.

**Comment by nikreations** [comment]
For anyone interested, I managed to animate the rotation using jquery animation like this:
function rotateView () {
                               currentRotation +=180;
								
				var someValue;
				var startValue = vp.getRotation();
				
				$({someValue: startValue}).animate({someValue: currentRotation}, {
					  duration: 2000,
					  easing:'swing', 
					  step: function() {
						  vp.setRotation(Math.round(this.someValue));
					  },
					  complete:function(){
						  currentRotation = vp.getRotation();
					  }
				  });
}

Wondering if it is an efficient code.

Thanks

**Comment by iangilman** [comment]
Indeed... when we originally added the viewport rotation we didn't put it on springs (unlike panning and zooming), and so far no one has followed up to add that functionality. Here's the issue: https://github.com/openseadragon/openseadragon/issues/1060

Your jQuery solution seems like a reasonable work around. 

I'm curious to find out how the TiledImage setRotation didn't work for you; what went wrong?

**Comment by nikreations** [comment]
I managed to get TiledImage setRotation working (using viewer.world.getItemAt(0) ) however couldn't figure out a way to rotate it around my clicked hotspot. The hotspot overlays also changed their location (it was like the image rotated independently of the hotspots overlays) Using viewport's setRotation did not do this. I am unable to release the project at this stage, but once it's launched, I will post links.

**Comment by iangilman** [comment]
I see. Thank you for letting me know. Yeah, sounds like the viewport's version is what you need.

I look forward to seeing your project once it's ready!

**Comment by iangilman** [comment]
Fixed by #2136.
