### ISSUE TITLE
Use of mozImageSmoothingEnabled is deprecated.

### ISSUE THREAD

**Issue by btzr-io** [openseadragon/openseadragon#1739]
I keep getting this warning:
```
Use of mozImageSmoothingEnabled is deprecated.
Please use the unprefixed.imageSmoothingEnabled property instead.
```

I guess this is here for old browsers:

https://github.com/openseadragon/openseadragon/blob/68e9efebe699c5c47f274b572a9409d267bafaa7/src/drawer.js#L636

Is this still relevant to keep ?

Also we should look into the other browsers prefix...

**Comment by iangilman** [comment]
Good point! Looks like we can just get rid of that line. According to MDN, they lost the browser prefix in version 51 (twenty versions ago): 

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled

According to the same page, Chrome stopped using the browser prefix in version 30 (48 versions ago), and Safari isn't using it either, so we could kill the webkit line.

According to Can I Use, those browser versions really aren't being used anymore: 

https://caniuse.com/usage-table

...so there's no problem in just removing those lines. Looks like we need to leave the one for `ms` in, though.

@btzr-io would you be up for making a pull request for this change?

**Comment by iangilman** [comment]
Fixed by https://github.com/openseadragon/openseadragon/pull/1740
