### ISSUE TITLE
When useCanvas is set to false the setting does not filter down to thumbnail viewers

### ISSUE THREAD

**Issue by greggarson** [openseadragon/openseadragon#1741]
Just curious if this was by design or an oversight?  I'm dealing with a version of this https://github.com/openseadragon/openseadragon/issues/381 and it seems that iOS will still get angry about the thumbs, if enough are loaded.

**Comment by iangilman** [comment]
Good point! I think that's just an oversight.

Would you be up for making a patch to fix it? You'd need to pass `this.useCanvas` into the `ReferenceStrip` here: 

https://github.com/openseadragon/openseadragon/blob/ce75ea9770e991940bc03b14e5d2add6f271386b/src/viewer.js#L2221

...and then pipe it through so it's used here:

https://github.com/openseadragon/openseadragon/blob/ce75ea9770e991940bc03b14e5d2add6f271386b/src/referencestrip.js#L441

**Comment by greggarson** [comment]
Happy to.

**Comment by greggarson** [comment]
https://github.com/openseadragon/openseadragon/pull/1742

**Comment by iangilman** [comment]
Fixed by #1742
