### ISSUE TITLE
"MouseTacker.scrollHandler" doesn't work, is that a bug?

### ISSUE THREAD

**Issue by Thomas365** [openseadragon/openseadragon#1745]
I created two viewer objects

```
var viewer1 = new OpenSeadragon({})
var viewer2 = new OpenSeadragon({})
```

I want viewer2 will srcoll when I scroll viewer1, so

```
viewer1.addHandler('canvas-scroll', e => {
    viewer2.innerTracker.scrollHandler(e)
})

```
but it doesn't work, what's wrong?

**Comment by Thomas365** [comment]
by the way, I am Using the Version 2.3.1

**Comment by Thomas365** [comment]
I found the solution

viewer1.addHandler('canvas-scroll', e => {
    e.pointerType = 'mouse'
    viewer2.innerTracker.scrollHandler(e)
})

**Comment by iangilman** [comment]
Interesting. Thank you for sharing the solution!
