### ISSUE TITLE
openseadragon-bookmark-url as a dynamically updating value?

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#1750]
I want to add a 'copy view' button using the bookmark-url script & clipboard.js.
It works, but the URL is only read after a page refresh.
I'd like the current page position to dynamically update the text to be copied.
My lack of JavaScript skills is showing here, but I suspect there's a relatively simple fix.

See working example here:

https://chattanoogahistory.com/north2.php

**Comment by iangilman** [comment]
Interesting... I tried to see if there was a way to query the browser for a notification, but I couldn't find one. I think the easiest way is to update the plugin to support this scenario. I've made a pull request with the change: 

https://github.com/openseadragon/bookmark-url/pull/3

Please give it a try and let me know if it does what you're hoping!

**Comment by SamHall** [comment]
That helped me get it where I needed it - thank you!

**Comment by iangilman** [comment]
Excellent :)
