### ISSUE TITLE
openseadragon viewer goes blank on iPad when zooming in DZI images

### ISSUE THREAD

**Issue by fszale** [openseadragon/openseadragon#1751]
On an iPad pro or other iPad devices, when pinch-zooming or using the +/- zoom buttons in the browser to view a DZI image the display goes blank while zooming in and over 50% zoom in.  Once the screen goes blank, I can zoom back out and the image comes back into view.

The zooming works fine on desktops with Chrome, IE, Firefox, etc.  The only place we are seeing this issues is on the iPad devices.

What could be the issue? How can I help to debug this to fix it?

**Comment by iangilman** [comment]
Where are you seeing this? I can't reproduce it on my iPad Air (iOS 12.4.2) on either of these sites:

http://openseadragon.github.io/

http://www.in2white.com/

The latter is a truly massive image, so you are definitely zooming in way over 50%.

Can you repro on those pages? If so, what iPad/OS? If not, what page are you getting it on?

Thank you for reporting this!

**Comment by fszale** [comment]
I did additional testing on iPad with 12.4.1 and 13.3 iOS using Chrome and Opera and here is what I found:

1. Testing http://openseadragon.github.io/ - seems to work fine, I was not able to break it easily.  It took a while but somehow I managed to lock the display in such a way where the browser viewer was locked and zoom was no longer working but I was still able to drag the image around a bit.

2. Testing http://www.in2white.com/ - broke the viewer.  Scrolling around and pinch zooming in/out eventually got it into locked state where the zoom image was simply stuck zoomed in and nothing else could be done with the browser tab.

3. My situation, where the image would disappear after 50% pinch zoom in, has behaved differently when the other tab in the browser was in the condition from #2 above.  I noticed that when the other tab was locked due to condition #2, my tab where I was testing the image disappearing seemed to stop at that 50% zoom.  Basically I was able to pinch zoom the image in/out but only up to the point where previously it would blank out on the screen.  So this time around it simply remained displaying the image but would not zoom in beyond that 50% mark.

4. I noticed that my issue only appears with SVS images converted to DZI format with the vips utility.  When I tested with JPG images converted with vips everything works just fine on the iPad.  

5. I have been trying a variety of SVS and conversion options, zooming works just fine on any desktop.  On iPad the issues are consistently reproducible.

How can I help to debug this better?

**Comment by iangilman** [comment]
Did you test in Safari as well?

Very odd that it only happens with SVS images. What format are the tiles after the images are converted? Are there any other differences between the images?

BTW, we seem to have a number of iPad related issues being reported lately. See https://github.com/openseadragon/openseadragon/issues/1662, https://github.com/openseadragon/openseadragon/issues/1724, https://github.com/openseadragon/openseadragon/issues/1728, and https://github.com/openseadragon/openseadragon/issues/1753.

There's also the patch https://github.com/openseadragon/openseadragon/pull/1754 that has just landed on master; not necessarily related to this issue, but maybe.

**Comment by iangilman** [comment]
I wonder if it's related to the browser detection issue mentioned at the bottom of https://github.com/openseadragon/openseadragon/issues/1728? You might try adding `iOSDevice: true` to the config to see if that helps.

**Comment by fszale** [comment]
I have been debugging this for a while on the iPads, here is a set of images that may prove to be helpful with the debugger turned on.  When you open up the images, focus in on the debugging box in the upper left corner.  The working image is at level 13, note the size of (5970.61,2137.19), going to level 14 in the non working image the level changes to 14 and the size now shows (3074.1,2200.76).  The first dimension is cut in half and all the images disappear from the canvas.  I noticed this pattern to be consistent with this issue independent of the images.  On the desktops when zooming in the higher level the size numbers displayed in parenthesis increase greatly and consistently.  The first dimension is never reduced like it happens on the iPads. 

I am adding debugging messages in the openseadragon js code to further debug how the dimensions are calculated since this appears to be related to how the viewport dimension calculation works but the code is vast and its taking a while to learn the code base.  

Could you share any tips or give me hints on where else in code to look in order to better diagnose it?

![issue_debug_not_working](https://user-images.githubusercontent.com/10144565/70854968-3d8d8f00-1e91-11ea-9f7b-4fa7185738b3.jpg)
![issue_debug_working](https://user-images.githubusercontent.com/10144565/70854969-3e262580-1e91-11ea-91b3-51a888d8329c.jpg)

.

**Comment by iangilman** [comment]
Wow, those are big tiles! Is that a DZI? What is the tile size on it?

I believe the size in parentheses is the size of the tile in web coordinates. Typically (depending on your options) it shouldn't be bigger than the tile size (since then we would switch to a higher resolution layer).

Having 6000 pixel tiles certainly seems like the sort of thing that could cause problems on an iPad!

**Comment by fszale** [comment]
Yep, that is the issue.  I am testing with smaller tiles and those do work on iPads.  Is there anything else we could do in the code to address this?

**Comment by iangilman** [comment]
So they are DZIs but with giant tiles? Is there more than one tile per level? Why are you using such big tiles?

I think in general you're going to have trouble with big tiles like that... it sort of circumvents the point of the DZI format. It means they'll take longer to transfer, and on some devices (like you're finding with the iPad) the big tiles won't work well.

As for what could be done, I think it comes down to breaking into tiles somehow. The easiest would be at the DZI level, but if that's not possible for some reason, I suppose you could try creating a tile source that does it on the client side. Note that the "simple image" tile source: 

http://openseadragon.github.io/examples/tilesource-image/

...automatically builds a pyramid, but it doesn't break the levels into tiles, so that's not enough.

Anyway, I highly recommend going to smaller tiles in your DZI. A tile size of 510 with overlap of 1 is a good setting.

**Comment by fszale** [comment]
We scaled the images down to recommended sizes, so far its working, thank you.
