### ISSUE TITLE
Image zoom status is different after first loading

### ISSUE THREAD

**Issue by kangchals** [openseadragon/openseadragon#1755]
Images looks differently when after first loading. It becomes zoomed

It might be bug or mis configuration.
I made sample code like below. ( it contains vue, vue-bootstrap. the issue might related to 
those but... I am not sure)

https://codepen.io/kangchals/pen/NWProOq

if you click the button, the image already zoomed out.
After hiding, If you click the button, the image is fit to the modal.

Can you help me to show the image consistently? 
Thank you!!!

**Comment by iangilman** [comment]
Interesting. I think it probably has to do with the automatic animation that Bootstrap is providing... somehow when the viewer initially decides how what level to zoom, it's getting the wrong size. If you introduce a little delay and have it "go home" afterwards, it does go to the right place. I tested that by adding this to your CodePen (thank you for providing that!) after the viewer creation. 

```
var viewer = this.viewer;
this.viewer.addHandler('open', function() {
  setTimeout(function() {
    viewer.viewport.goHome();
  }, 1000)
});
```

Obviously that's not ideal, though. What you want is for it to already be in the right place. I think you'll have to figure out what Bootstrap is doing. Typically OSD is pretty good about filling the space you give it.

BTW, I see you are creating a new viewer each time the modal is shown? You should destroy the viewer when you close the modal so they don't keep piling up.
