### ISSUE TITLE
Use of decodeURIComponent when retrieving Browser information throws uncaught exception

### ISSUE THREAD

**Issue by AaronPlave** [openseadragon/openseadragon#1757]
Improperly escaped url characters can lead to an unhandled exception when using `decodeURIComponent` when retrieving Browser information. This bit of code runs when OpenSeaDragon is imported making it necessary to ensure the safety of the url before import of the module. This isn't ideal in the context of say, a React application, where OpenSeaDragon is imported before any real application logic can safety check the url. Are there any workarounds to prevent this code from running initially? My solution so far has been to check url safety outside the context of my React application before OpenSeaDragon has been imported but it means I can't properly alert the user about the malformed URL and have to remove the offending URL parameters so that OpenSeaDragon does not cause crash the application. Improperly escaped url characters are rare but it would be nice to still be able to gracefully handle these cases.

Relevant bit of code:
https://github.com/openseadragon/openseadragon/blob/dffec1ff5cae75fd366590225238f0287f5298c2/src/openseadragon.js#L2590

Failure in the wild:
![image](https://user-images.githubusercontent.com/4419607/71125716-5ac9a280-219c-11ea-8114-7538703968ef.png)

**Comment by iangilman** [comment]
Wow... I didn't even realize that was in there, nor did I know it could throw an exception. Thank you for highlighting this!

The fix should be super easy... Just wrap that line in a try/catch. I figure if the URL is malformed, we can safely ignore it.

Would you be up for making a patch to that effect?

**Comment by AaronPlave** [comment]
Sure thing! Just put in the PR to safely decode each URL parameter with a try-catch: https://github.com/openseadragon/openseadragon/pull/1758

**Comment by iangilman** [comment]
Fixed by #1758
