### ISSUE TITLE
If my collections source Tile are rectangles instead of squares, but I make them 0 margins, is it supported? 

### ISSUE THREAD

**Issue by smallcoderofme** [openseadragon/openseadragon#1759]
> OpenSeadragon({
>     ...
>     collectionMode:       true,
>     collectionRows:       1, 
>     collectionTileSize:   1024,
>     collectionTileMargin: 0,
>     ...
> });
> 

If my collections source Tile are rectangles instead of squares, but I make them 0 margins, is it supported? 
How to do？

**example:** 
    _collectionTileWidth:   1024,
    collectionTileHeight:   768,_

**Comment by iangilman** [comment]
The collection mode is pretty rudimentary. Check out https://github.com/openseadragon/openseadragon/issues/1723 for some thoughts on things that can be done in this situation.
