### ISSUE TITLE
a11y: browser zoom

### ISSUE THREAD

**Issue by ronnymikalsen** [openseadragon/openseadragon#1763]
Users with low vision may prefer to have their browser zoom into page content to make it easier to read. Openseadragon should select a tile with a resolution that is not blurry

#### Detailed Reproduction Steps:
1. Go to http://openseadragon.github.io/examples/developer-debug-mode/
2. Change browser zoom to 500%

### What is the expected behavior?
The image should be in a good resolution

### What is the current behavior?
The image is blurry

**Comment by iangilman** [comment]
Good point! Any thoughts on how to do this? Presumably we're loading low res tiles because we think the viewer element is much smaller than it really is.

**Comment by ronnymikalsen** [comment]
@iangilman PR ready :-)

**Comment by ronnymikalsen** [comment]
@iangilman Thank you for your review! 

I have made the changes that you requested. Please review again.
