### ISSUE TITLE
Setting 'zoomPerSecond' option causes zoom buttons to reverse intended zoom direction on click and hold

### ISSUE THREAD

**Issue by peteszym** [openseadragon/openseadragon#1767]
I'm noticing an odd behaviour when I include `zoomPerSecond` as an option when initializing OpenSeadragon. 

Basically, if you click and hold the zoom in button, it'll actually zoom out. Single clicks do correctly zoom in the direction that you want, but if you click and hold, that is when the reverse seems to happen.

As an example, I've taken this documentation example for Custom Buttons:
https://openseadragon.github.io/examples/ui-binding-custom-buttons/

and created a demo to show the bug in action by just adding `zoomPerSecond: 0.2,` to the options.
https://jsfiddle.net/kegm6jfd/

**Comment by iangilman** [comment]
`zoomPerSecond` is a multiplier... when it's 1 it has no effect, when it's greater than 1 it zooms in, and when it's less than 1 it zooms out. If you want a slow zoom in, you might try something like 1.2.

This seems like an area where the documentation could be improved!

**Comment by msalsbery** [comment]
Assigned to myself, fixing docs in next patch...

**Comment by msalsbery** [comment]
Documentation fixed/enhanced for v2.5.0 (#1872)

Feel free to reopen if issue persists!
