### ISSUE TITLE
How many images(collection mode) can we load in the browser using openseadragon

### ISSUE THREAD

**Issue by gaganscanup** [openseadragon/openseadragon#1770]
Ex:

I have WidthxHeight = 1280x960 each image and converted each image with tiles with "256".

how many images can we load in collection mode (to extent) ?

Till how many images it supports to load in collection mode ?

**Comment by iangilman** [comment]
It's theoretically limited only by how much memory is on the device. Once you have a few hundred there are probably things you'll want to do to make it more efficient. How many do you have in mind?

**Comment by gaganscanup** [comment]
Around 5.5k to 6k Images

**Comment by iangilman** [comment]
That's quite a few! So, your biggest challenge is going to be all of the file transfers. You definitely don't want to have to load a separate DZI file for each image. Fortunately you can use the "inline configuration" option mentioned here: 

http://openseadragon.github.io/examples/tilesource-dzi/

That way you can send all of the DZI information as a single file and then break it up into tilesource info on the client side. Assuming you're using DZI and you have it in the standard XML, this CodePen gives some code for converting into the "inline" style:

https://codepen.io/iangilman/pen/gpejpJ

That should help a good deal. Of course you'll still need to load tiles for all the images, which is also a lot! There is an optimization for that in the "Deep Zoom Collection" format, but OSD doesn't yet support that feature... Here's the issue: https://github.com/openseadragon/openseadragon/issues/67 Of course we'd love to support that feature but nobody has stepped up to implement it.

**Comment by iangilman** [comment]
BTW, do all of these images need to be able to move independently of each other, or be rearranged dynamically? If not, another approach is to build them all into a single giant image and DZI that. Until we have the DZC optimization, that's the most efficient way to do this sort of thing at the kind of scale you're talking about.
