### ISSUE TITLE
Openseadragon tiles source rotation 

### ISSUE THREAD

**Issue by MounikaAV** [openseadragon/openseadragon#1771]
Hi,
I am new to Openseadragon & paperJs overlay, need suggestions on a few points.

- [1] I want to rotate the tilesource of the image while initializing the OpenSeaDragon. I tried with like this
 this.viewer = OpenSeadragon({
                id: "osd",
                prefixUrl: "https://openseadragon.github.io/openseadragon/images/",
                debugMode: false,
                visibilityRatio: 1.5,
                constrainDuringPan: true,
                showNavigator: true,
                zoomPerScroll: 1.8,
                degrees: 180,              
            });
 var paint_circles = function (overlay, event) {
                var circle = new paper.Path.Circle(new paper.Point(5000, 5000), 400);
                circle.fillColor = 'red';
                circle.visible = true;
            }
            this.viewer.addTiledImage({
                tileSource: "http://openseadragon.github.io/example-images/highsmith/highsmith.dzi",
                x: 0,
                y: 0,
                success: paint_circles,
            });

 Is this the correct way of initializing?

- [2] By following the above configuration, my paperjs Overlay is not moving in a proper way (like If I scroll the tileSource image to right, The paperjs overlay path items are moving towards left.

After 2hours of continuous de-bugging, I am still not able to figure out the route cause of this issue.
Can someone help me in solving this issue. ?

Apology if any grammatical errors.
Thanks for your help.

**Comment by MounikaAV** [comment]
> Hi,
> I am new to Openseadragon & paperJs overlay, need suggestions on a few points.
> 
> * [1] I want to rotate the tilesource of the image while initializing the OpenSeaDragon. I tried with like this
>   this.viewer = OpenSeadragon({
>   id: "osd",
>   prefixUrl: "https://openseadragon.github.io/openseadragon/images/",
>   debugMode: false,
>   visibilityRatio: 1.5,
>   constrainDuringPan: true,
>   showNavigator: true,
>   zoomPerScroll: 1.8,
>   degrees: 180,
>   });
>   var paint_circles = function (overlay, event) {
>   var circle = new paper.Path.Circle(new paper.Point(5000, 5000), 400);
>   circle.fillColor = 'red';
>   circle.visible = true;
>   }
>   this.viewer.addTiledImage({
>   tileSource: "http://openseadragon.github.io/example-images/highsmith/highsmith.dzi",
>   x: 0,
>   y: 0,
>   success: paint_circles,
>   });
> 
> Is this the correct way of initializing?
> 
> * [2] By following the above configuration, my paperjs Overlay is not moving in a proper way (like If I scroll the tileSource image to right, The paperjs overlay path items are moving towards left.
> 
> After 2hours of continuous de-bugging, I am still not able to figure out the route cause of this issue.
> Can someone help me in solving this issue. ?
> 
> Apology if any grammatical errors.
> Thanks for your help.

**Comment by iangilman** [comment]
Unfortunately the PaperJS overlay doesn't yet support rotation. Here's the issue for that: 

https://github.com/eriksjolund/OpenSeadragonPaperjsOverlay/issues/7

...which includes a pointer for how you might implement it if you want.

**Comment by MounikaAV** [comment]
ok, Thanks
