### ISSUE TITLE
Access specific image in sequence

### ISSUE THREAD

**Issue by martinantonmueller** [openseadragon/openseadragon#1773]
Say I have 4 images in a sequence. Is it possible to immediately open image 3? I.e. if there is a parameter to say which should be the image shown? I could reorder the sequence but maybe there exists an easier solution?

**Comment by iangilman** [comment]
You should be able to include `initialPage: 3` (remembering that it starts counting from 0, so that would be the fourth image) in the OpenSeadragon options when creating your viewer.

**Comment by martinantonmueller** [comment]
great, thank you!
