### ISSUE TITLE
Openseadragon fabricjsOverlay

### ISSUE THREAD

**Issue by Jithesh363** [openseadragon/openseadragon#1774]
I'm using angular 7. I found issue regarding fabricjsOverlay. It will throw error this.imageZoom.fabricjsOverlay is not a function

Here is related code:

```
 this.imageZoom = new OpenSeadragon.Viewer({

        id: "openseadragon1",
        prefixUrl: "/assets/images/",
        showNavigator: true,

        tileSources: {
          Image: {
            id: "seadragonimg",
            xmlns: "http://schemas.microsoft.com/deepzoom/2008",
            Url: "http://localhost/" + this.selectedImage + "/",
            Format: "jpeg",
            Overlap: "2",
            TileSize: "256",
            Size: {
              Height: "15000",
              Width: "11800"
            },
          }
        }
      });

      var options = {
        scale: 1000
      }
    
   var a= this.imageZoom.fabricjsOverlay(options);
```

Angular config plugin

      "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/geojs/geo.min.js",
              "node_modules/fabric/dist/fabric.min.js",
              "node_modules/openseadragon/build/openseadragon/openseadragon.min.js",
              "node_modules/openseadragon-annotations/dist/openseadragon-annotations.js",
              "node_modules/openseadragon-paperjs-overlay/openseadragon-paperjs-overlay.js",
              "node_modules/openseadragon-fabricjs-overlay/openseadragon-fabricjs-overlay.js"   
            ]

**Comment by iangilman** [comment]
Might be related to https://github.com/openseadragon/openseadragon/issues/1709.

**Comment by Jithesh363** [comment]
Hi @iangilman thank you for your replay i got solution. I missed out frabic.js import statement in angular.json.

         "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/geojs/geo.min.js",
              "node_modules/openseadragon/build/openseadragon/openseadragon.min.js",
              "node_modules/openseadragon-annotations/dist/openseadragon-annotations.js",
              "node_modules/openseadragon-fabricjs-overlay/fabric/fabric.adapted.js",
              "node_modules/openseadragon-fabricjs-overlay/openseadragon-fabricjs-overlay.js"
   
            ]

**Comment by iangilman** [comment]
Great, thank you for posting the solution!
