### ISSUE TITLE
Question: Tile cache of identical images

### ISSUE THREAD

**Issue by zero41120** [openseadragon/openseadragon#1776]
I have identical images loaded in the viewer, say `slide A` and `slide B`

Assume that both image are loaded with same URL, user zooms into `slide A`, does `B` reference cached tiles from `A`?

**Comment by iangilman** [comment]
Yes, I believe it's designed to do so. You might want to verify by testing it, though.

**Comment by zero41120** [comment]
![image](https://user-images.githubusercontent.com/10471270/74687033-18b2e200-5188-11ea-9f7c-f1ea7ba32c5b.png)

In the above image,
157mb for 50 extra identical images,
110mb for 10 extra identical images,
105mb for no extra image.

Seems like it takes about 1mb per image, I'm not sure what's the best way to test this.

**Comment by iangilman** [comment]
Interesting. So there's definitely some overhead! Is it the same as the original image?

BTW, the mechanism that handles detecting whether the image has already been loaded is here: 

https://github.com/openseadragon/openseadragon/blob/3adb001b9f6a5da98bb4a7056e0063c737207d21/src/tiledimage.js#L1371
