### ISSUE TITLE
Drawing  rectangle using mouse

### ISSUE THREAD

**Issue by Jithesh363** [openseadragon/openseadragon#1777]
Drawing rectangle  using mouse is not possible in openseadragon-fabricjs-overlay.js.

**Comment by iangilman** [comment]
I think this question belongs over here: 

https://github.com/altert/OpenseadragonFabricjsOverlay/issues

Please file an issue there with more detail about what you're trying to accomplish and how it's not working. I don't know a lot about that plugin but feel free to tag me and I can see if I have any ideas.

**Comment by Jithesh363** [comment]
Hi Openseadragon/Openseadragon,

        I need https://codepen.io/jbeezley/pen/xqoZLa feature using
openseadragon-fabricjs-overlay.js or using viewer.addOverlay() method.
Please help me to get out of the problem

Regards,
Jithesh

**Comment by iangilman** [comment]
Okay, here's an example using OSD overlays:

https://codepen.io/iangilman/pen/qBdabGM

**Comment by Jithesh363** [comment]
Hi  Ian Giman,

                         Thank you so much you made my day and saved lots
of time.


Regards,
Jithesh

**Comment by iangilman** [comment]
@Jithesh363 Glad to hear it!
