### ISSUE TITLE
Want to embed multiple images into DZI image

### ISSUE THREAD

**Issue by libin85** [openseadragon/openseadragon#178]
I want to embed multiple images into DZI image, something similar to Andrea's work. I obviously do not need lamb or rabbit as a shadow image. Can find seadragon implementation in the following link: http://www.soulsolutions.com.au/silverlight/perumosaic/.

I have written a C# class to embed thumbnail images into a background image, and it works ok, however when i zoom it I am not getting the quality as the example mentioned above.

Any suggestions. I realise tile collection is a good way to embed multiple images ( by making them into a dzi file). But in my project there might be huge collection ranging from (100,000 to 1 million). I feel its impractical to download those many dzi files from server. 

Please share your thoughts on how I could do this efficiently.

**Comment by iangilman** [comment]
I'm closing old question threads. I'll just add here that we do now have working collection support (though not yet released or merged into master): #446.
