### ISSUE TITLE
openseadragon-annotations.js will not work after using openseadragon-svg-overlay.js

### ISSUE THREAD

**Issue by Jithesh363** [openseadragon/openseadragon#1780]
Scenario 1: If i call let overlay = this.viewer.svgOverlay(). Pencil draw openseadragon-svg-overlay will not work. I can not draw(pencil draw). Image will move when i try to draw with mouse.

Scenario 2:  If i call this.viewer.clearOverlays();. Pencil draw openseadragon-svg-overlay will not work (this.viewer.annotations.set(data)).

Please help me to get out of this problem

**Comment by iangilman** [comment]
Hmm... those plugins weren't necessarily designed to work together, so it's not surprising there are issues. I can take a look, though... can you make a CodePen with a basic example of the two together and one of the scenarios above?

**Comment by Jithesh363** [comment]
Hi  Ian Gilman,

                         Can not make code because
openseadragon-annotation.js is not present in github. I can share some code
snipped.


I have included  openseadragon-annotation.js and d3.js file.

           let overlay = viewer.svgOverlay();

            var d3Rect = d3.select(overlay.node()).append("circle")
              .style('fill', '#f00')
              .attr("cx", 0.2)
              .attr("cy", 0.2)
              .attr("r", 0.02)
              .style("opacity", 0.5)


After executing above code. pencil draw of  openseadragon-annotation.js  is
stoped working. If i comment above code it will start working.


        viewer.initializeAnnotations();
        viewer.areAnnotationsActive();

above two line codes i'm executing when initializing the application.
Thanking you in advance.


Regards,
Jithesh

**Comment by dbhuvanapalli** [comment]
Hi Ian,

I need help with this issue as well. I'm trying to draw shapes as annotations with svg-overlay and d3.js. But the annotation plugin functions won't work after the svgoverlay is added. Any help is appreciated.

**Comment by iangilman** [comment]
@Jithesh363 I went ahead and made a CodePen: 

https://codepen.io/iangilman/pen/PoqpqmL

You can pull anything from `npm` into a script tag using https://unpkg.com/, so that's how I got openseadragon-annotations.js in it.

Turns out the issue you're encountering is because the SVG overlay is catching the pointer events. I've added this line to fix that:

```
overlay.node().parentNode.style.pointerEvents = 'none';
```

Other than that, it seems to be working properly.

**Comment by iangilman** [comment]
Note that this issue is filed in the SVG overlay project: https://github.com/openseadragon/svg-overlay/issues/16

**Comment by dbhuvanapalli** [comment]
Will try that out, thank you!

**Comment by Jithesh363** [comment]
It is working cool!!!.Thank you so much @iangilman

**Comment by msalsbery** [comment]
@iangilman  @Jithesh363 

Now that #1872 has landed, it should be much easier to get control of the pointer events

[Here's a CodePen](https://codepen.io/msalsbery/pen/dyOeXqO) that shows a bit of what can be done...
