### ISSUE TITLE
Zoom in and Zoom out in the Navigator.

### ISSUE THREAD

**Issue by samyuan31515** [openseadragon/openseadragon#1787]
Hello, I am a student who are writing a project with OpenSeaDragon from Taiwan. 
I am wondering if there's a function that enabled user to zoom in and zoom out with the mouse wheel while the mouse is on the Navigator.
Thanks for the guidance.

**Comment by zero41120** [comment]
You can add a custom mouse handler on the navigator object.
```
function scrollHandler(e) {
  var viewport = viewer.viewport;
  viewport.zoomBy(e.scroll === 1 ? 1.1 : 0.9);
  viewport.applyConstraints();
}

viewer.navigator.mouseTracker= new OpenSeadragon.MouseTracker({
  element: navigatorId,
  scrollHandler: scrollHandler
});
```

Since navigator is a viewer, you may also do it on the `canvas-scroll` event

**Comment by samyuan31515** [comment]
Thanks for your help!
I have set the navigatorId as viewer.navigator.element and it works perfectly.

**Comment by msalsbery** [comment]
@zero41120  @samyuan31515 

No need to create and attach another MouseTracker...Viewer exposes a 'navigator-scroll' event...
```javascript
    viewer.addHandler('navigator-scroll', (event) => {
      var viewport = viewer.viewport;
      viewport.zoomBy(event.scroll === 1 ? 1.1 : 0.9);
      viewport.applyConstraints();
    });
```
