### ISSUE TITLE
Replace between 2 images in smoothy way

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1790]
HI 
is the plugin support to switch between images without flicking the screen? 

I have 2 images 
1 is jpg, and seconds is TIF 
there are a few seconds between the images, the first jpg appears and the viewer will open the jpg image, then I would like to replace to image with high quality (TIF).

I Would like a smooth way and also want to keep the zoom level without resetting it

is there any example? , do I need to use pages or play with opacity or something?

thanks  a lot

**Comment by iangilman** [comment]
Here's an example of how to accomplish this:

https://codepen.io/iangilman/pen/YXRLea

**Comment by johnico** [comment]
Hi, thanks  I am using angular does it matter?

and in your example I can see this lines :

`var viewer = OpenSeadragon({
    id: "seadragon-viewer",
    prefixUrl: "//openseadragon.github.io/openseadragon/images/",
    tileSources: [
        {
            x: 0,
            y: 0,
            opacity: 1,
            tileSource: duomo
        },
        {
            x: 0,
            y: 0,
            opacity: 0.001,
            tileSource: highsmith
        }
    ]
});`

here you use 2 images in the viewer when the page is loaded.
How can I add a tile source and then change between them?  because I don't have the images ready,  i have only one and I create a openseadragon object with 1 tilesource

thanks

**Comment by iangilman** [comment]
I know plenty of people use OpenSeadragon in Angular, but I don't personally have experience doing so, so I can't say if there are any differences you need to be aware of.

If you want to start with just a single image and add a second image, use `addTiledImage` to add the second image when it's ready:

http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#addTiledImage
