### ISSUE TITLE
dicom image support 

### ISSUE THREAD

**Issue by sathishravula** [openseadragon/openseadragon#1795]

**Comment by alvaromartmart** [comment]
@sathishravula while the idea behind this issue may be obvious to you, it would be helpful if you took the time to describe what you're looking for, provide some context, etc.
An issue with just the title and no description is not that helpful.

**Comment by iangilman** [comment]
Indeed. For starters, do DICOM images work in browsers? If not, you'll need some sort of server-side translation, perhaps into one of the formats OpenSeadragon already supports, in which case there might not be anything to do directly on the OpenSeadragon side (beyond perhaps publishing links to the appropriate resources on the OpenSeadragon website).

**Comment by speedyankur** [comment]
There are few Dicom parsers(eg [DIOCM js](https://www.npmjs.com/package/dicomjs)) available which can return the pixeldata. but Im not sure if we can load that pixel data in OpenSeaDragon viewers.

@iangilman : is there any way we can load pixel data inside OpenSeaDragon viewers?

**Comment by iangilman** [comment]
@speedyankur unfortunately OSD doesn't have a smooth mechanism for loading non-file-based pixels into the viewer. There's some discussion about it in https://github.com/openseadragon/openseadragon/issues/1699 and https://github.com/openseadragon/openseadragon/issues/119. That might give you some ideas for how to do it within OSD. Of course if you're interested in expanding OSD to support that scenario more cleanly, that would be awesome as well!

**Comment by KempWatson** [comment]
@sathishravula sure, DICOM images work in browsers. See WADO and DICOMweb standards. But there's a lot more to supporting DICOM in OSD that there is to say pulling a DZI or other zoomable 2D image. Most DICOM images are 3D for a start, and you'll need to translate backend compression codecs into something a browser understands. And take care of window/level and other presentation issues. IMO I'd look to Orthanc Stone Viewer, Cornerstone, OHIF, etc for a GUI front-end before OSD.
