### ISSUE TITLE
Simpliest way to insert multiple DIV

### ISSUE THREAD

**Issue by Salitehkat** [openseadragon/openseadragon#1797]
Good morning, 
Please can you guide me on how to insert in the simpliest way, this HTML code inside the OSD? thanks so much. 

div id="smoke"
 span class="s0"span
span class="s1"span
span class="s2"span
 span class="s3"span
 span class="s4"span
 span class="s5"span
 span class="s6"span
div

**Comment by zero41120** [comment]
Have you checked out the [overlay html example](https://openseadragon.github.io/examples/ui-overlays/)?

You would need to add overlay with the html id to the viewer
```
OpenSeadragon({
    ...
    overlays: [{ px: 0, py: 0, id: 'smoke' }],
    ...
})
```

**Comment by Salitehkat** [comment]
Thank you!. Ill give it a try. Thanks again.

**Comment by msalsbery** [comment]
@Salitehkat 

You can also use [Viewer.addOverlay](http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#addOverlay) to add HTML overlays to an already-existing viewer.

Here's an example that programmatically creates and adds an overlay when the user clicks in the viewer
```
    viewer.addHandler('canvas-click', (event) => {
      if (event.quick) {
        let overlayElement = OpenSeadragon.makeNeutralElement('div');

        overlayElement.className = 'my-overlay-class';

        let style = overlayElement.style;
        style.fontSize = '20px';
        style.color = '#000';
        style.background = 'rgba(0,255,255,0.5)';
        style.padding = '20px';
        style.pointerEvents = 'auto';
        style.cursor = 'grab';

        let clickPoint = viewer.viewport.pointFromPixel(event.position);

        viewer.addOverlay({
          element: overlayElement,
          location: new OpenSeadragon.Rect(clickPoint.x, clickPoint.y, 0.1, 0.1)
        });

        // Prevent default click-to-zoom behavior
        event.preventDefaultAction = true;
      }
    });
```
