### ISSUE TITLE
Dimensions of overlay does not match the image

### ISSUE THREAD

**Issue by peterjcaulfield** [openseadragon/openseadragon#1799]
Creating an overlay frame to match the viewable image dimensions is defeating me currently. It's always slightly off.

I created a codepen using the canonical basic example to show the issue:

https://codepen.io/peterjcaulfield/pen/JjdxjJo

It's easier to see the delta when you zoom out fully.

**Comment by iangilman** [comment]
Apologies for not getting to this sooner! The quarantine has thrown my schedule for a loop...

Anyway, I think it's just a CSS issue. If I change the `box-sizing` in your example to `border-box`, it seems to work perfectly. Does that work for you as well?

**Comment by kisurb** [comment]
> 
> 
> Apologies for not getting to this sooner! The quarantine has thrown my schedule for a loop...
> 
> Anyway, I think it's just a CSS issue. If I change the `box-sizing` in your example to `border-box`, it seems to work perfectly. Does that work for you as well?

Hallelujah. Thank you really much. Fixed my issue.

**Comment by peterjcaulfield** [comment]
@iangilman 

> Apologies for not getting to this sooner! The quarantine has thrown my schedule for a loop...

No need to Apologise, I really appreciate the effort you have put in to create this fantastic library :)

Re your fix suggestion, I still encounter essentially same issue. Using `border-box` sometimes causes the canvas to bleed outside the overlay (can happen on the vertical or horizontal plane).

I had to use a different image to repro the issue with `border-box`:

https://codepen.io/peterjcaulfield/pen/qBOveOp

**Comment by iangilman** [comment]
> No need to apologise, I really appreciate the effort you have put in to create this fantastic library :)

Thank you :-)

So the issue with https://codepen.io/peterjcaulfield/pen/qBOveOp is that the image is visible outside of the line to the bottom and right?

I'm not sure what the best solution would be here… It's possible there's something we could be doing with the overlay math to fix it, or it's possible there's just too much weirdness in HTML/CSS. If you really want absolute precision in your overlay, you might be better off with the SVG overlay or one of the Canvas overlays.

What do you think?

**Comment by peterjcaulfield** [comment]
> So the issue with https://codepen.io/peterjcaulfield/pen/qBOveOp is that the image is visible outside of the line to the bottom and right?

Yep exactly.

Is https://github.com/altert/OpenSeadragonCanvasOverlay the recommended solution for implementing canvas overlays with OSD?

I tried to use this plugin but looks like it is not functioning with the latest version of OSD. I reproduced the canvas overlay repo demo using the current build of OSD [here](https://codesandbox.io/s/infallible-thunder-gd5ej).

**Comment by peterjcaulfield** [comment]
I've just come across https://github.com/joshua-gould/OpenSeadragonCanvasOverlayHd will try with this plugin and report back!

**Comment by peterjcaulfield** [comment]
The same issue occurs when trying to use a canvas overlay unfortunately. I guess this makes sense as it's consuming the same dimensions as input to define its size as the DOM element overlay. Looks like this will need to be fixed in the overlay math?

**Comment by iangilman** [comment]
Interesting. Can you share a repro? It wouldn't be the overlay math... just the regular OSD conversion functions, right?
