### ISSUE TITLE
Loading multiple SVG with svg-overlay

### ISSUE THREAD

**Issue by Salitehkat** [openseadragon/openseadragon#1800]
Good Morning, 
I am using the svg-overlay.js component to load an SVG. My question is : If I need to load multiple SVG do I need to create multiple SVG overlays aswell or there is a cleaner way to achieve it? Thanks you so much for  any guidelines. 
This is the code I am using to load one svg: 
``` 
// LOAD SVG
var svgOverlay = viewer.svgOverlay();
var path = 'images/money.svg';
function loadSVG(path, callback) {
  var xhr = new XMLHttpRequest();
  xhr.onreadystatechange = function(e) {
    try {
      if (xhr.readyState == 4 && xhr.status == 200) {
        callback(xhr.responseXML.documentElement);
      }
    } catch (e) {
      console.log(e);
    }
  };
  //
  xhr.open('GET', path, true);
  xhr.overrideMimeType('text/xml');
  xhr.responseType = 'document';
  xhr.send();
}
loadSVG(path, function(data) {
  var g = data.getElementById('moneyG');
  svgOverlay.node().appendChild(g);
}); // END LOAD SVG
```

**Comment by iangilman** [comment]
That should work fine with multiple SVGs… You just need the one `svgOverlay`, and you can `appendChild` to it as many times as you want.

**Comment by Salitehkat** [comment]
Thank you! and hope you and your relatives are safe. Greetings, Sali.

**Comment by iangilman** [comment]
Thank you… We are. I hope you are as well!

It's done funny things to my schedule, though, so I'm finally getting a chance to catch up on OpenSeadragon stuff…

**Comment by Salitehkat** [comment]
And we appreciate it. ;)
From this chaos and sadness some things have to turn into positive things.. Greetings from France.

**Comment by msalsbery** [comment]
Closing this, feel free to re-open if there's any issues!
