### ISSUE TITLE
How to get image co ordinates of , the zoomed image , the part of image which is on viewport? 

### ISSUE THREAD

**Issue by QuratulainAkhtar** [openseadragon/openseadragon#1806]

**Comment by iangilman** [comment]
Assuming your OpenSeadragon viewer is named `viewer`, you can get the current location like so:

```
var viewportRect = viewer.viewport.getBounds();
```

That'll get you the current visible area in viewport coordinates. If you want to convert that into image coordinates, this would work (assuming you just have a single image or only care about the first image in the viewer):

```
var imageRect = viewer.world.getItemAt(0).viewportToImageRectangle(viewportRect);
```

For more information on the difference between viewport and image coordinates, see:

https://openseadragon.github.io/examples/viewport-coordinates/
