### ISSUE TITLE
Embedding working code in website 

### ISSUE THREAD

**Issue by HelloSynaesthesia** [openseadragon/openseadragon#1809]
Disclaimer, I'm a noob with basic JavaScript coding skills!

I have the code working great on a local host. Now I want to embed the zooming image on a website and am looking at WIX and other website builders so I can easily design the pages around the zooming image. 

Has anyone had OpenSeaDragon working on WIX, Cargo, Squarespace etc?

**Comment by zero41120** [comment]
Those drag and drop websites doesn't really want their customer to execute their own code, I think it has to do with security issue.

Typically they allows you to embed iframe, here is [support from WIX](https://support.wix.com/en/article/using-iframes-to-display-visible-content-on-your-site).
You can learn more about iframe [here](https://www.w3schools.com/tags/tag_iframe.asp)

You can host your OSD viewer on a free static website server, then embed that as an iframe in WIX.

Here are some options, 
- [GitHub](https://pages.github.com/), which is easiest one in my opinion
- [Amazon S3 bucket](https://aws.amazon.com/s3/)
- [Google Cloud Storage](https://cloud.google.com/storage/docs/hosting-static-website)
There are a ton more, but those are the one I have personally used.

My work uses S3 bucket but it is tedious to configure.  The counter part of the S3 is Google Cloud Storage, which has basically same restriction as S3 for free users.
