### ISSUE TITLE
how to convert Rect to image url?

### ISSUE THREAD

**Issue by h26liu** [openseadragon/openseadragon#1812]
Hello there,

By using openseadragon selection plugin, I am having a Rect object, however, I am trying to convert the selected area (the Rect) to an actual image or an URL so that I can use this selected region of the image in the backend of my app. 

Any solution would be appreciated!

Thanks for the help in advance!

**Comment by Gijsjan** [comment]
You can use [viewportToImageRectangle](https://openseadragon.github.io/docs/OpenSeadragon.Viewport.html#viewportToImageRectangle) to get the rectangle on the image in pixels.

```js
const viewportRect: OpenSeadragon.Rect /* you've got this from the selection plugin */
const imgRect: OpenSeadragon.Rect = viewer.viewport.viewportToImageRectangle(viewportRect)
```

Depending on you server configuration, you can use the IIIF scheme to request the part of the image you are interested in:
`{scheme}://{server}{/prefix}/{identifier}/{region}/{size}/{rotation}/{quality}.{format}`
The region part will be `${imgRect.x},${imgRect.y},${imgRect.width},${imgRect.height}`
