### ISSUE TITLE
how to make referenceStrip work for tilesources other than IIIF?

### ISSUE THREAD

**Issue by alhuber1502** [openseadragon/openseadragon#1819]
I'm struggling to get the referenceStrip to display for `image` and `zoomifytileservice` tilesource types.  While everything works fine out of the box for IIIF manifests, the referenceStrip won't diplay for me for other tilesources.  

At the moment, all I'm doing is add a `referenceStripThumbnailUrl: path_to/thumbnail-image` to every tilesource that I pass into `tileSources`.  I can see that the referenceStrip is being created in the resulting HTML, but no thumbnail images show up.  Any help gratefully received!

**Comment by iangilman** [comment]
`referenceStripThumbnailUrl` is just an optimization… If you want to use the original tile source in the reference trip, just leave that property off. That should work for all tile source types.

If you do want the referenceStripThumbnailUrl optimization, you'll have to pass it the URL of a standard image, not a tile source.

**Comment by alhuber1502** [comment]
OK, sorry this doesn't work for me at all.  Do you have/run a test suite that verifies expected behaviour for all supported tilesources?  I can't get this to work for either "image" or "zoomifytileservice".  Any ideas?

**Comment by iangilman** [comment]
Interesting. Can you share your code? We don't have specific tests for each combination of tile source with the reference strip.

The reference strip example page uses legacy tile source:

http://openseadragon.github.io/examples/ui-reference-strip/

You might take a look at the source for that page to see if it illuminates anything.
