### ISSUE TITLE
Zooming speed inconsistent across browsers/hardware

### ISSUE THREAD

**Issue by j-hudecek** [openseadragon/openseadragon#1820]
When using different browsers/OS/hardware (precision touchpad, normal touchpad, mouse, mighty mouse) the zoom speed is inconsistent.  Scrolling on precision touchpad emits events with deltaY 1.25 in Chrome and 0.01 in Firefox on W10, so zooming speed is 100 times slower there for example.

One way to normalize it would be using a method similar to https://www.npmjs.com/package/normalize-wheel (coming from https://github.com/facebookarchive/fixed-data-table/blob/master/src/vendor_upstream/dom/normalizeWheel.js). This code is BSD-licensed and hasn't changed in the past 4 years so it could also be just copied wholesale.

**Comment by msalsbery** [comment]
Nice find, thank you! Definitely worth a try!

**Comment by iangilman** [comment]
I believe we already do some mouse wheel normalization, but nothing as sophisticated as the Facebook package. It would be great to improve this area! Pulling in that code seems like a reasonable way to go about it.

We'll want to test the result on a wide variety of devices, of course.

@j-hudecek would you be up for making a pull request?

**Comment by j-hudecek** [comment]
I've tested the Facebook code and I'm still not happy with the results - FF and Chrome on Windows have different scrolling speeds for me. I'll investigate some more.

**Comment by stephenwf** [comment]
The [wheel event](https://www.w3.org/TR/uievents/#event-type-wheel) will produce an "expected amount the page will move" in the `deltaY` even if that element does not scroll. Could this be used to get a more accurate input. ([demo](https://codesandbox.io/s/lucid-sunset-h94f6?file=/src/index.js))

**Comment by msalsbery** [comment]
> The [wheel event](https://www.w3.org/TR/uievents/#event-type-wheel) will produce an "expected amount the page will move" in the `deltaY` even if that element does not scroll. Could this be used to get a more accurate input. ([demo](https://codesandbox.io/s/lucid-sunset-h94f6?file=/src/index.js))
> 
> edit: I suppose browser compatibility may come into that, I notice that the normalized wheel events above use that and fallback to a shim of the wheel event.

Interesting, and definitely something to try, thank you! I too wonder if that will have the same browser inconsistencies, but I will check into it if someone doesn’t do it first
