### ISSUE TITLE
How to accurately convert the tile viewport coordinate to main viewer's viewport coordinate?

### ISSUE THREAD

**Issue by zero41120** [openseadragon/openseadragon#1822]
If a viewer has multiple tile images, 
a warning shows when you call `imageToViewportCoordinates`.
It asks you to call `TiledImage.imageToViewportCoordinates` instead of it.

Let's say I have a 100px by 100px image, I want to get the point say (x:25, y:25).
`TiledImage.imageToViewportCoordinates` will give me (0.25, 0.25) as viewport coordinate.
![image](https://user-images.githubusercontent.com/10471270/82708171-78f76b00-9c32-11ea-858e-685544838c3e.png)_(image not to scale)_

After a canvas drag, I want to get that exact point in the main viewer viewport coordinate.
Let's say that we drag the image to the right bottom corner, 
how can I translate the (x:25, y:25) in the main view's viewport coordinates? 
The below example image, it will roughly be (0.75, 0.75)
![image](https://user-images.githubusercontent.com/10471270/82708233-962c3980-9c32-11ea-8aac-09a2a9f5ba54.png)

I have some initial experiment for this 
```
function pointToMainViewportCoords(imagePoints, viewer)  {
    // Below uses viewer.viewport
    // Something needs to be done here to get the correct viewport coordinate
    return imagePoints.map(p => viewer.viewport.imageToViewportCoordinates(p.x, p.y), );
}
function viewportCoordsToPoint(viewportCoords, viewer) {
    const image = viewer.world.getItemAt(1);
    // Below uses tileImage
    return viewportCoords.map(p => image.viewportToImageCoordinates(p.x, p.y, true));
}
```

**Comment by iangilman** [comment]
When you say you are dragging the image, do you mean panning the viewer? If so, the viewport coordinates aren't going to change in relation with the image. They will change in relation to the "web coordinates" of the viewer, though. This page goes into more detail on the three coordinate systems, and has an interactive example that shows the effect of panning:

https://openseadragon.github.io/examples/viewport-coordinates/

In your example, the 0.75 you're looking for would be the web coordinates (assuming you are panning the viewport with your canvas drag, rather than repositioning the image). You can use `TiledImage.imageToViewerElementCoordinates` to get that information. Of course it won't be literally 0.75, because it'll be in web pixels, but it'll be the right proportion.

**Comment by zero41120** [comment]
Thank you for the information. I have resolved my problem with web coordinate approach.

I was trying to create 2+ viewers with different images and mirror overlay at same viewport location as annotation (not the same image location or zoom level).

If anyone is interested, here are relevant code for the conversion.

#### Common conversion
First I have a function that converts my custom point array into OSD Points which will take another function to actual conversion
```
/**
 * This function converts the given point array into OSD.Point array, then map the
 * given convert function for each OSD.Point.
 * @param {[{x, y}]} points - an array of point like objects
 * @param {({x, y})=>*any} convertFunc - a function to execute for each point after convert
 * to OpenSeadragon.Point
 */
function osdConvert(points, convertFunc) {
    const xyToOSDPoint = (p) => new OpenSeadragon.Point(p.x, p.y);
    const convert = R.pipe(
        R.map(xyToOSDPoint),
        R.map(convertFunc),
    );
    return convert(points);
}
```
#### Image points to web coordinates
By giving the polygon array point of my annotation, I can get the annotation polygon in terms of web coordinates at runtime, that value ignores the zoom and pan location after capture
```
/**
 * This function converts given image into the coordinate in web element.
 * @param {[{x, y}]} imagePoints - image points to convert
 * @param {OpenSeadragon.Viewer} viewer - the viewer to provide conversion function
 * @return {[OpenSeadragon.Point]} - an array of OSD.Point representing the web coordinate.
 * @see https://openseadragon.github.io/examples/viewport-coordinates/
 */
function imagePointsToWebCoords(imagePoints, viewer)  {
    const image = viewer.world.getItemAt(1); // Background image at position 0, actual at 1
    const pointToWeb = (p) => image.imageToViewerElementCoordinates(p);
    return osdConvert(imagePoints, pointToWeb);
}
```
#### Web coordinates to images points
After I get the web coordinates from the last function, I can give the web coordinates to a _different viewer_, convert it to image point to get the annotation at its viewport location and zoom level.
```
/**
 * This function converts given coordinate in web element into image map to the coordinate.
 * @param {[{x, y}]} webCoords - web coordinate to convert
 * @param {OpenSeadragon.Viewer} viewer - the viewer to provide conversion function
 * @return {[OpenSeadragon.Point]} - an array of OSD.Point representing the image point.
 * @see https://openseadragon.github.io/examples/viewport-coordinates/
 */
function webCoordsToImagePoints(webCoords, viewer) {
    const image = viewer.world.getItemAt(1); // Split view image is always at 1
    const webToPoint = (p) => image.viewerElementToImageCoordinates(p);
    return osdConvert(webCoords, webToPoint);
}
```

The 2 annotations will have different image points but same web coordinates.

**Comment by iangilman** [comment]
Great! Thank you for sharing your approach :-)
