### ISSUE TITLE
Change controls show/hide with fullscreen

### ISSUE THREAD

**Issue by AnasGhrab** [openseadragon/openseadragon#1823]
How to set these values differently with the fullscreen ?

```
var viewer = OpenSeadragon({
...
        showHomeControl: true,
        showZoomControl: true,
        showFullPageControl: true,
        showRotationControl: true,
        showFlipControl: true,
        showSequenceControl: true,
        ...
    });
```

**Comment by iangilman** [comment]
I don't think we have a mechanism for that, exactly; presumably it would be part of https://github.com/openseadragon/openseadragon/issues/1817 if that happens.

Meanwhile, you could probably do something like:

```
viewer.addHandler('full-screen', function(event) {
  viewer.homeButton.setVisible(event.fullScreen);
  // … etc.
});
```

To find the names of the buttons, you can look through this function:

https://github.com/openseadragon/openseadragon/blob/2ed99077eb364884103b61285975017071fa210a/src/viewer.js#L1685

**Comment by AnasGhrab** [comment]
Thank you for you answer, but it doesn't seem to work... :/

**Comment by iangilman** [comment]
Well, I didn't test it… Just giving an impression of what I thought might work.

What part doesn't work? Are there errors in the console? What device/browser are you on?
