### ISSUE TITLE
Trying to set initial pan position

### ISSUE THREAD

**Issue by chamster** [openseadragon/openseadragon#1827]
I have an image that is very wide but not very tall. When the viewer loads, I want the initial view to be panned all the way to the left edge of the image.

I read in a couple issues (e.g. 1467) the following:

> The best way to move the viewer around is using fitBounds. For instance:
> 
> ```
> var bounds = new OpenSeadragon.Rect(0.25, 0.25, 0.5, 0.5);
> viewer.viewport.fitBounds(bounds, true);
> ```
> 
> You just need to do the math to create a rectangle that suits your needs.

But when I add that code, and change the numbers in the arguments, nothing changes.

Here's my code:

```
var viewer = OpenSeadragon({
  	id: "seadragon-viewer",
	defaultZoomLevel: 8,
	panVertical: false,
	visibilityRatio: 1.0,
    constrainDuringPan: true,
	minZoomLevel: 8,
	maxZoomLevel: 8,
    tileSources: {
        type: 'image',
        url:  'timeline.jpg'
    }
});

viewer.addHandler('open', function() {
  var bounds = OpenSeadragon.Rect(0.25, 0.25, 0.5, 0.5);
  viewer.viewport.fitBounds(bounds, true);
});
```

Am I doing something wrong? Thanks!

**Comment by zero41120** [comment]
If you know the zoom level and pan location, you can do something like this:
```
var zoomLevel = 0.8;
var panPoint = new new OpenSeadragon.Point(1, 0.5); // x at 0 meaning left most, y at 0.5 is middle
viewer.viewport.zoomTo(zoomLevel);
viewer.viewport.panTo(panPoint);
```

**Comment by iangilman** [comment]
@chamster Looks like you're doing the right thing in general, but I suspect some of the navigation restrictions you've added are fighting with the fitBounds. Try commenting all of these lines out:

```
	defaultZoomLevel: 8,
	panVertical: false,
	visibilityRatio: 1.0,
	constrainDuringPan: true,
	minZoomLevel: 8,
	maxZoomLevel: 8,
```

… And see if it works then. If so, you can start adding them back in to isolate what's restricting the movement.

**Comment by chamster** [comment]
Thanks for the replies.
I got it working like this:

```
var viewer = OpenSeadragon({
  	id: "seadragon-viewer",
	defaultZoomLevel: 6,
	panVertical: false,
	visibilityRatio: 1.0,
    constrainDuringPan: true,
	minZoomLevel: 6,
	maxZoomLevel: 8,
    tileSources: {
        type: 'image',
        url:  'timeline.jpg'
    }
});

viewer.addHandler('open', function() {
    var bounds = new OpenSeadragon.Rect(0, 0, 0, 0.5);
    viewer.viewport.fitBoundsWithConstraints(bounds);
});
```
I'm not sure if the `fitBoundsWithConstraints` is what made the difference, or if it was the dimensions on the` .Rect,` or ??

I tried the suggestion above from zero41120, and didn't have success. But I didn't do much to troubleshoot because I solved it with the `fitBoundsWithConstraints` as shown above. I don't know if `fitBoundsWithConstraints` is preferable to `zoomTo` and `panTo`, but it's working for me so for now, I'm going with it. Thanks!

**Comment by iangilman** [comment]
Interesting. I'm not sure why fitBoundsWithConstraints would do the trick, but I'm glad it's working! Thank you for sharing your solution :-)
