### ISSUE TITLE
Multi-image viewer with navigator: clipping an image re-centers navigator

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#1831]
As discussed here:

https://github.com/cuberis/openseadragon-curtain-sync/issues/4#issuecomment-637681675

… In a multi-image viewer (where the images are stacked directly on top of each other) with a navigator, clipping one of the images causes the entire navigator to reposition its contents. The position of the navigator contents should be based on the entire stack of images, not just one of them. If they all get clipped, it makes sense that they would get repositioned, but with just one of them clipped, the overall content space is still the same and shouldn't be repositioned.

Here's an example before clipping:

<img width="493" alt="Screen Shot 2020-06-04 at 9 53 55 AM" src="https://user-images.githubusercontent.com/338989/83787921-5d845b00-a649-11ea-8556-153906b26ea1.png">

… And after clipping:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/338989/83787971-70972b00-a649-11ea-8c4d-3f60cf379aef.png">

It kind of looks like it's trying to center the intersection of the images, rather than the union of them.

**Comment by RammasEchor** [comment]
Hi! I have been working on this issue, but I do think this is not an issue of openseadragon, but of another library. I'm not sure if I'm breaking any rules linking a pull request of another project, but in any case, I think I may solved it.

Link to pr: https://github.com/cuberis/openseadragon-curtain-sync/pull/9

**Comment by iangilman** [comment]
@RammasEchor awesome! Yes, thank you for posting a note here about the fix! I shall close this issue :)
