### ISSUE TITLE
Can't create an OpenSeadragon viewer

### ISSUE THREAD

**Issue by Mikesteinberg** [openseadragon/openseadragon#1834]
Hi guys, I'm pretty new to Javascript and have been trying to avoid it as much as possible, but I need to add a OSG viewer to a Flask site. I have the dzi created successfully and I thought I was basically done when I realized that I simply could not get around this error. I'm using the sample block of code from the documentation:
```
<div id="openseadragon1" style="width: 955px; height: 693px;"></div>
<script src="/static/openseadragon/build/openseadragon/openseadragon.min.js"></script>
<script type="text/javascript">

    var viewer = OpenSeadragon({
        id: "openseadragon1",
        prefixUrl: "/openseadragon/images/",
        tileSources: "/repos/analysis/output/img.dzi",
    });

</script>
```

Every time I run this I get nailed with an "Uncaught ReferenceError: OpenSeadragon is not defined"

Further investigation shows that the script source is apparently not being found, "Failed to load resource: the server responded with a status of 404 ()"

I'm pretty sure I installed the OSG package properly with npm but I can't be sure. I installed it under the Flask static folder which I believe is correct but I almost never use Javascript or flask so I wouldn't know. 

I suspect that the source path for the js function might be incorrect but I have tried a bunch of different ones with very little changes in results. 

Does anyone have any idea what is wrong here? 
Thanks!

**Comment by nein09** [comment]
Hi Mike!

It sounds to me like your suspicion is correct. Are you serving other static files (like images and css) with that in the path, and are those working? 

What happens if you take out the first `/static` from your script src tag?

**Comment by Mikesteinberg** [comment]
No luck. :/

I'm not sure if I'm serving any other files with that path. The css is reference somewhere else in the code like this 
```
 <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
```
I've tried a variety of paths, and using 

```
<script src="../static/node_modules/openseadragon/build/openseadragon/openseadragon.min.js"></script>
```

I can right click on the filepath to get to the file. Unfortunately the results do not improve with this path either.

**Comment by nein09** [comment]
Ah, ok. So Flask is building a static url for you somehow, and it makes sense to let it do that here too - where is your `main.css` relative to where you put openseadragon.min.js? It looks like you did an `npm install` to get it, so maybe something like this might work:

`<script src="{{url_for('static', filename='ode_modules/openseadragon/build/openseadragon/openseadragon.min.js') }}"></script>`

**Comment by Mikesteinberg** [comment]
Thanks again for the help. It appears I'm getting the same error still but it's slightly different this time, as I'm getting two counts of 404 response now. 

```
Failed to load resource: the server responded with a status of 404 ()
Failed to load resource: the server responded with a status of 404 ()
Uncaught ReferenceError: OpenSeadragon is not defined
```

**Comment by nein09** [comment]
That looks like progress. Where's your main.css, and where is your openseadragon js file relative to that? I think that's the key here to help you put the correct relative path in `filename` for that static tag, so Flask can find it.

**Comment by Mikesteinberg** [comment]
My main.css is in the static folder, while my openseadragon.js file is nested several layers within the static folder, under 
```
static/node_modules/openseadragon/build/openseadragon/openseadragon.js
```

**Comment by nein09** [comment]
Hmmm. what does your Flask setup file look like?

**Comment by Mikesteinberg** [comment]
I believe __init__.py is what you're referring to. Here it is.
```
from flask import Flask
 
class ReverseProxied(object):
  def __init__(self, app):
      self.app = app
  def __call__(self, environ, start_response):
      script_name = environ.get('HTTP_X_SCRIPT_NAME', '')
      if script_name:
          environ['SCRIPT_NAME'] = script_name
          path_info = environ['PATH_INFO']
          if path_info.startswith(script_name):
              environ['PATH_INFO'] = path_info[len(script_name):]
      host = environ.get('HTTP_X_FORWARDED_HOST')
      if host:
          environ['HTTP_HOST'] = host
      scheme = environ.get('HTTP_X_FORWARDED_PROTO')
      if scheme:
          environ['wsgi.url_scheme'] = scheme
 
      return self.app(environ, start_response)
 
 
app = Flask(__name__, static_url_path="/static")
app.wsgi_app = ReverseProxied(app.wsgi_app)

```

**Comment by nein09** [comment]
OK, that all looks to me like it *should* work! I'm not sure what's going on here, honestly, unless you have something like two static folders or something really unusual going on. Sorry!

**Comment by Mikesteinberg** [comment]
Thanks again, I managed to sidestep the issue using the CDN version instead of npm. Most of it is working now apart from rendering the actual image. Currently getting the following when trying to do that:

```
Tile h.Tile failed to load: output/img.dzi/11/3_0.jpg - error: Image load aborted
```

**Comment by msalsbery** [comment]
@Mikesteinberg Glad you got it sorted! Closing this for now...feel free to reopen if the issue persists!
