### ISSUE TITLE
Implementing interactive overlay grid 

### ISSUE THREAD

**Issue by NEXCO-WestUSA** [openseadragon/openseadragon#1836]
Dear openseadragon team,

First of all I would like to thank you for creating and maintaining openseadragon. I have been using different zooming system for my apps, and this one is, no doubt, the best and more fluid I could ever find in the market.

I am trying to implement a interactive overlay grid on top of the images displayed in the viewer, so that the users can mark certain areas of the pictures with different colors.

This is an example of the code:

```
<script type="text/javascript">
			var chunkData = [{i:"67yj5xqg-rnpw-2lvz-twg2-600i0rcwdoco",r:1,c:1,w:256,h:256},
i:"8j7wwp04-lz9n-ifrb-c7cn-a8ky1todxd90",r:2,c:1,w:256,h:256},{i:"g1iwt1o8-lx15-n7kr-81vj-e5vxw9q80qkt",r:3,c:1,w:256,h:256}]; 
			var viewer = OpenSeadragon({
				id: "smarteagle-rsv",
				prefixUrl: "/assets/buttons/",
				showNavigator:  true,
				navigatorId: "rsv-navigator",
				tileSources: [{
					type:       "zoomifytileservice",
					width:      79280,
					height:     2048,
					tileSize:	256,
					tilesUrl:   "path_to_zoomify_pyramid",
				}],
				gestureSettingsMouse: {
					clickToZoom: false,
					dblClickToZoom: true
				}
			});
			chunkData.forEach(function(chunk,i) {
				var chunkLabel = document.createElement("div");
				chunkLabel.id = chunk.i;
				chunkLabel.className = "chunk no-distress";
				viewer.addOverlay({
					element: chunkLabel,
					location: new OpenSeadragon.Rect(chunk.c, chunk.r, chunk.w, chunk.h)
				});
				var tracker = new OpenSeadragon.MouseTracker({
					element: chunkLabel,
					clickHandler: function(event) {
						console.log(chunk.col, chunk.row)
					}
				});
			});
			
		</script>
```
In this example there are only 3 overlays; however, the overlays are generated dynamically. There are around 2500 rectangles per viewer. The issue is that I am receiving one of the next violations per overlay:

> openseadragon.js:1994 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

I am also receiving several

> [Violation] Forced reflow while executing JavaScript took <N>ms

AND

> [Violation] 'requestAnimationFrame' handler took <N>ms

Each time I try to zoom in/out or pan the picture

Lastly, I am receiving;

> [Violation] 'setTimeout' handler took 102ms

Only once at loading.

I need to figure out how to remove this waiting times to improve the efficiency of the app. Especially the first one commented, with this amount of overlays, is crucial.

I have been reading your documentation carefully, as well as trying different solutions, but I do not get to remove the violations. Can you give me any clue on how to attack this issue?

**Comment by iangilman** [comment]
I imagine 2500 HTML overlays is enough to bog the system down, causing those errors. I recommend using one of our graphics-oriented overlay plug-ins. In your case, this is probably best:

https://github.com/joshua-gould/OpenSeadragonCanvasOverlayHd

With it, you draw the grid in canvas every frame, which means you can draw just the part that's visible, and you can also draw less grid detail when zoomed out if necessary.

Other options include:

https://github.com/altert/OpenSeadragonCanvasOverlay
https://github.com/openseadragon/svg-overlay

You can find the whole list of plug-ins here:

http://openseadragon.github.io/#plugins

**Comment by NEXCO-WestUSA** [comment]
Thanks a lot! I will try these plugins and get back to you!

**Comment by msalsbery** [comment]
> Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

Assigning to myself as reminder to address this passive event listener issue.

Note that it may not change...we kind of have to call preventDefault() on the wheel events to prevent scrolling of underlying elements.

@iangilman Thinking out loud, I'm not sure how to address that. One fix is to mark it passive to eliminate the warning, but that affects the out-of-the-box behavior of OpenSeadragon viewers, and could mean a (possibly breaking) API change...

I don't know....I know it's not crucial -the warning was added so wheel event handlers on window, document, and document.body wouldn't have their handling burdened, none of which applies to us...

Anyway, assigning to self so I remember to address this! :)
