### ISSUE TITLE
Can't zoom in past 1.1

### ISSUE THREAD

**Issue by Mikesteinberg** [openseadragon/openseadragon#1837]
Hi, I'm trying to zoom in on an image rendered with Openseadragon. For some reason I can only zoom in to the 1.1 level, according to debugmode. Any idea why this might be the case? Thanks!

(this appears to be happening regardless of the tilesize of my dzi)

**Comment by Mikesteinberg** [comment]
Solved by changing MaxZoomPixelRatio

**Comment by iangilman** [comment]
Glad you got it sorted out :-)

**Comment by msalsbery** [comment]
> Solved by changing MaxZoomPixelRatio

@Mikesteinberg 

I'm curious...was it a value you were using or the default that caused an issue?

**Comment by msalsbery** [comment]
...and can we close this issue? ;)

**Comment by iangilman** [comment]
Sure!

That reminds me, I should go through and close out some of the old questions sometime… Of course you're welcome to as well ;-)
