### ISSUE TITLE
HTML overlays trembling on mouse pan and zoom

### ISSUE THREAD

**Issue by Medwar** [openseadragon/openseadragon#1842]
Greetings!

1) On zoom and pan with the mouse, particularly on animation, the HTML overlays are trembling +-1 px, creating a nasty visual effect.
If animationTime is set to 0,  no trembling occurs.
Could you please give an advice, why it happens and is there a way to get rid of it?

2) Moreover, when one of the overlays is dragged in chrome, the text or the lower line of some OTHER overlays noticeably trembles. This
I don't really understand how dragging one overlay can affect the other ones here. 
This second issue occurs in chrome only, probably only after some zoom with the wheel was made, and may be not reproduceable from the 1st try (but from me with 2-3 F5 retry it usually works). Maybe dragging should begin when animation is not yet finished, and after that the effect persist stably till the next wheelzoom.
More presizely:  style.left of other overlays in this case changes as exactly +- 1px,  eg.  390.652px => 391.652px and back,
and that creates trembling. Considering the value is fractional, exactly +-1 is a bit suspicious.
This second effect also does not occur if   animationTime = "0"

Here is an example of overlays (draggable) for test: 
https://codepen.io/Medwar/pen/PoZjZXZ

How to reproduce:
the effect is strongest in chrome, 
the effect is easier to notice on non-retina screens, 
the effect is best seen when panning slowly.

On touch zoom and pan - there is almost no or no trembling.

**Comment by Medwar** [comment]
Sorry. I found that this issue has already been raised.

Overlays wobble on drag (sub-pixel offsets rounding problem) #1474

**Comment by iangilman** [comment]
Yes, that looks like the issue! I would say the proposed fix is still probably a good one, if you're up for tackling it.

Another approach is to use one of the alternative overlay systems available here:

http://openseadragon.github.io/#plugins
