### ISSUE TITLE
Bundle only a single tilesource

### ISSUE THREAD

**Issue by lovasoa** [openseadragon/openseadragon#1850]
Hello,
  First, thank you very much for this great piece of software. 
  I am currently adding a new feature to [dezoomify-rs](https://lovasoa.github.io/dezoomify-rs/) where I am bundling openseadragon. It's working great, but the library itself is quite voluminous (>200Kb minified). I think a large part of it is implementation of other tile sources that I will never use.
  Could OpenSeadragon distribute minified files containing a single tile source ? I think I am not the only one using a single tile source.

**Comment by iangilman** [comment]
It's hard to say exactly how each file contributes to the overall minified version, but if you compare the original source files, all of the tile sources together comprise only 7% of the overall total, so no, they aren't a major proportion of the total file size.

It looks like if we throw in the other optional modules (navigator, reference strip, and overlays), you get another 7% for a total of 14%. That leaves 86% of the file size in core modules.

It would be interesting to see if there are ways to slim down our deliverable, but splitting out optional modules doesn't seem like it would make a huge difference, and it's likely to add complexity, both for the developers and the end users. 

I do like the idea of spinning some of the optional features out as plug-ins, mostly so they can evolve and blossom into multiple versions (the reference strip especially could be taken in so many directions), but so far no one has taken up the challenge. The tile sources seem like they belong in the core, though.

**Comment by lovasoa** [comment]
Thank you for the detailed answer, @iangilman !
