### ISSUE TITLE
Wrong paper.view when moving between canvases

### ISSUE THREAD

**Issue by EinavSB** [openseadragon/openseadragon#1851]
Hi,

My page contains 2 canvases. For each of them I call:
paper.setup(this._canvas);

I register to the Mouse Move event in the following way:
paperTool = new paper.Tool();
paperTool.activate();
paperTool.attach('mousemove', PaperJSOnMouseMove);

I'm drawing a circle that moves together with the cursor.
When the cursor is passing between one canvas to another, the circle is rendered in a wrong position.
The reason - the event point is on the new canvas system while the paper.tool.view contains the old canvas.

I figured it out in the following way:
I put a breakpoint on my event handler function - PaperJSOnMouseMove.
When I move the cursor between the canvases and stop at the breakpoint, I watch the paperjs function _handleMouseEvent (down in the call stack):
"this" contains the new canvas view while paper.tool.view contains the old canvas.
The "point" is calculated according to the new canvas and propagated to my event handler.
Thus, in the event handler I get the point in the new canvas, while the activated canvas is the old canvas.

In addition, each of the canvas document elements has 'mousemove' event handler in which I activate its project. The problem is that this event handler is called after the paperTool MouseMove event.
Therefore, before this event is called (exactly when passing between the canvases), the old canvas is still active and my drawing is done on the wrong canvas.

Am I doing something wrong here? What is the best way to solve this? 

I use version v0.10.2.

Thanks,
Einav.

**Comment by iangilman** [comment]
Sounds like you're using https://github.com/eriksjolund/OpenSeadragonPaperjsOverlay? You might want to file an issue there.

I'm afraid I don't know that much about that plug-in. When you say you have two canvases, do you mean two OpenSeadragon viewers?

**Comment by msalsbery** [comment]
@EinavSB 
Did you get this sorted? I'm unable to picture what the DOM tree looks like in your scenario.

Is this just moving the mouse between canvases or dragging (moving with a button pressed) between canvases?

I do know this is solvable, but I can't give a specific suggestion as I'm unclear what your DOM structure looks like ;-)

**Comment by EinavSB** [comment]
Thank you for your replies!

@iangilman 
No, I'm not using OpenSeadragon.

@msalsbery
This is just moving the mouse between the canvases (the button is NOT pressed).
The (simplified) DOM structure:
<body>
    <div id="div1">
        <canvas id = "canvas1">
    </div>
    <div id="div2">
        <canvas id = "canvas2">
    </div>
</body>

Thanks,
Einav.

**Comment by EinavSB** [comment]
<body>
    <div id="div1">
        <canvas id = "canvas1">
    </div>
    <div id="div2">
        <canvas id = "canvas2">
    </div>
</body>

**Comment by iangilman** [comment]
Oh, if you're not using OpenSeadragon, you've filed this issue in the wrong repository! You probably want https://github.com/paperjs/paper.js/issues.
