### ISSUE TITLE
Overlays in SequentialMode disappear

### ISSUE THREAD

**Issue by gunmiosb** [openseadragon/openseadragon#1861]
If there are multiple overlays for each sequential image only the first overlay is visible. Every overlay after that is set to "display:none"

You can see the problem on the example page for [Overlays](http://openseadragon.github.io/examples/ui-overlays/) on the Overlaying Complex HTML Example.

Culprit is this part in overlay.js
https://github.com/openseadragon/openseadragon/blob/84dd5cd6a737aec00f4132453d3253077b24b8e6/src/overlay.js#L292-L295

When I remove the "display !='none'" check in the chrome debugger, the overlays work as intended.

**Comment by iangilman** [comment]
Now that you mention it, I have no idea why we're doing that check! Seems like we should be able to just get rid of it. Would you be up for writing a pull request with that fix?

Note that this issue was first reported in https://github.com/openseadragon/openseadragon/issues/774.

**Comment by iangilman** [comment]
Fixed by https://github.com/openseadragon/openseadragon/pull/1865
