### ISSUE TITLE
Synchronize animations between the two viewers

### ISSUE THREAD

**Issue by Medwar** [openseadragon/openseadragon#1862]
In this example:
https://codepen.io/iangilman/pen/BpwBJe
If synchronize 2 viewers like here, syncronization works, but except for the touch devices.
If one image is touch-moved, the second animates to the new position with delay, so they are desyncronized. 
 
Do you have any idea how to solve this?

A quick half-workaround is to set springStiffness to 100 if we detect touch device. 
But I would like to find a more universal solution, so that animations will look the same on all devices.

**Comment by msalsbery** [comment]
Hi @Medwar 

Try using the immediately parameter set to true on the Viewport.zoomTo() and Viewport.panTo() calls when on touch devices. That may give you what you want

Try this code in the codepen example:
```javascript
// If you like my work, please consider supporting it at https://www.patreon.com/iangilman

var duomo = {
  Image: {
    xmlns: "http://schemas.microsoft.com/deepzoom/2008",
    Url: "//openseadragon.github.io/example-images/duomo/duomo_files/",
    Format: "jpg",
    Overlap: "2",
    TileSize: "256",
    Size: {
      Width:  "13920",
      Height: "10200"
    }
  }
};

var viewer1 = OpenSeadragon({
  id: "viewer1",
  prefixUrl: "//openseadragon.github.io/openseadragon/images/",
  tileSources: duomo
});

var viewer2 = OpenSeadragon({
  id: "viewer2",
  prefixUrl: "//openseadragon.github.io/openseadragon/images/",
  tileSources: duomo
});

var viewer1Leading = false;
var viewer2Leading = false;

var viewer1Handler = function() {
  if (viewer2Leading) {
    return;
  }

  viewer1Leading = true;
  viewer2.viewport.zoomTo(viewer1.viewport.getZoom(), null, true);
  viewer2.viewport.panTo(viewer1.viewport.getCenter(), true);
  viewer1Leading = false;
};

var viewer2Handler = function() {
  if (viewer1Leading) {
    return;
  }

  viewer2Leading = true;
  viewer1.viewport.zoomTo(viewer2.viewport.getZoom(), null, true);
  viewer1.viewport.panTo(viewer2.viewport.getCenter(), true);
  viewer2Leading = false;
};

viewer1.addHandler('zoom', viewer1Handler);
viewer2.addHandler('zoom', viewer2Handler);
viewer1.addHandler('pan', viewer1Handler);
viewer2.addHandler('pan', viewer2Handler);

```

**Comment by iangilman** [comment]
@MSalsbery that seems like the perfect solution.

Some background: The difference is that with mouse actions, OpenSeadragon employs springs to animate the movement, and with touch actions, the movements are mirrored directly without springs. 

@msalsbery any suggestions for how best to detect touch? Is there any facility in OpenSeadragon to do so?

**Comment by msalsbery** [comment]
> @msalsbery any suggestions for how best to detect touch? Is there any facility in OpenSeadragon to do so?

@iangilman Sure! Now, if I would have had the foresight to include the pointerType ('touch', 'mouse', 'pen') in the canvas-drag and canvas-pinch events, this could be much cleaner and would work on devices that have both mouse and touch (touchscreen desktops for example). I am adding it in my MouseTracker patch (today actually!) for the future, but for now here's a quick and dirty way to detect a touch-only device (works on my iPhone anyway)...try this in the codepen @Medwar :
```javascript
// If you like my work, please consider supporting it at https://www.patreon.com/iangilman

var duomo = {
  Image: {
    xmlns: "http://schemas.microsoft.com/deepzoom/2008",
    Url: "//openseadragon.github.io/example-images/duomo/duomo_files/",
    Format: "jpg",
    Overlap: "2",
    TileSize: "256",
    Size: {
      Width:  "13920",
      Height: "10200"
    }
  }
};

var viewer1 = OpenSeadragon({
  id: "viewer1",
  prefixUrl: "//openseadragon.github.io/openseadragon/images/",
  tileSources: duomo
});

var viewer2 = OpenSeadragon({
  id: "viewer2",
  prefixUrl: "//openseadragon.github.io/openseadragon/images/",
  tileSources: duomo
});

var isTouchDevice = false;
var viewer1Leading = false;
var viewer2Leading = false;

var viewer1Handler = function() {
  if (viewer2Leading) {
    return;
  }

  viewer1Leading = true;
  viewer2.viewport.zoomTo(viewer1.viewport.getZoom(), null, isTouchDevice);
  viewer2.viewport.panTo(viewer1.viewport.getCenter(), isTouchDevice);
  viewer1Leading = false;
};

var viewer2Handler = function() {
  if (viewer1Leading) {
    return;
  }

  viewer2Leading = true;
  viewer1.viewport.zoomTo(viewer2.viewport.getZoom(), null, isTouchDevice);
  viewer1.viewport.panTo(viewer2.viewport.getCenter(), isTouchDevice);
  viewer2Leading = false;
};

viewer1.addHandler('zoom', viewer1Handler);
viewer2.addHandler('zoom', viewer2Handler);
viewer1.addHandler('pan', viewer1Handler);
viewer2.addHandler('pan', viewer2Handler);

viewer1.addOnceHandler('canvas-press', (event) => {
  isTouchDevice = event.pointerType === 'touch';
});
viewer2.addOnceHandler('canvas-press', (event) => {
  isTouchDevice = event.pointerType === 'touch';
});
```

**Comment by Medwar** [comment]
Great idea, thank you! 
But this doesn't work in the following case:
 
https://codepen.io/Medwar/pen/MWKxaMG
When I make a "throwing gesture", the 'active' image keeps inertia and moves with animation in the direction, while the second image teleports to destination instantly when the finger is lifted up. 

Maybe some actions on canvas-drag-end can be added.   Simply turning 'isTouchDevice = false' doesn't help.

**Comment by Medwar** [comment]
events calling sequence is:  canvas-drag, pan, canvas-drag-end, so on canvas-drag-end it is too late.

**Comment by msalsbery** [comment]
@Medwar  Yeah there's definitely more adjustments needed than what I put in the example ;-) 

Anyway, this is what you really want (hehe just kidding @iangilman ):
```javascript
// If you like my work, please consider supporting it at https://www.patreon.com/iangilman

var duomo = {
  Image: {
    xmlns: "http://schemas.microsoft.com/deepzoom/2008",
    Url: "//openseadragon.github.io/example-images/duomo/duomo_files/",
    Format: "jpg",
    Overlap: "2",
    TileSize: "256",
    Size: {
      Width:  "13920",
      Height: "10200"
    }
  }
};

var viewer1 = OpenSeadragon({
  id: "viewer1",
  prefixUrl: "//openseadragon.github.io/openseadragon/images/",
  tileSources: duomo
});

var viewer2 = OpenSeadragon({
  id: "viewer2",
  prefixUrl: "//openseadragon.github.io/openseadragon/images/",
  tileSources: duomo
});

var viewer1Leading = false;
var viewer2Leading = false;

var viewer1AnimationHandler = function() {
  if (viewer1Leading) {
    viewer2.viewport.zoomTo(viewer1.viewport.getZoom(true), null, true);
    viewer2.viewport.panTo(viewer1.viewport.getCenter(true), true);
  }
};

var viewer2AnimationHandler = function() {
  if (viewer2Leading) {
    viewer1.viewport.zoomTo(viewer2.viewport.getZoom(true), null, true);
    viewer1.viewport.panTo(viewer2.viewport.getCenter(true), true);
  }
};

viewer1.addHandler('animation', viewer1AnimationHandler);
viewer2.addHandler('animation', viewer2AnimationHandler);
viewer1.addHandler('animation-finish', viewer1AnimationHandler);
viewer2.addHandler('animation-finish', viewer2AnimationHandler);

viewer1.addHandler('canvas-press', (event) => {
  viewer1Leading = true;
  viewer2Leading = false;
});
viewer2.addHandler('canvas-press', (event) => {
  viewer1Leading = false;
  viewer2Leading = true;
});
```

**Comment by msalsbery** [comment]
I think that works perfectly everywhere!

**Comment by msalsbery** [comment]
@Medwar Ok I fixed mousewheel handling in my last example above...still pondering the zoom buttons...

**Comment by msalsbery** [comment]
@Medwar Got it! That should work regardless of touch/mouse/pen pointer device used

**Comment by msalsbery** [comment]
@Medwar Took a while but I got it, code updated above!

**Comment by Medwar** [comment]
I didn't know of this second solution. Great idea.
Thank you for your work on tuning it up!
However this sync on animations seems to be more resource-heavy, as I noticed with animationTime = 0.5 it lags more even when working with the mouse.
And I still notice, that on high zoom levels the images still desync a bit. 

I also want to try what will happen if I will be spawning mouse events on touch events like this -- 
`    function touchHandler(event) {
      var touch = event.changedTouches[0];

      var simulatedEvent = document.createEvent("MouseEvent");
          simulatedEvent.initMouseEvent({
          touchstart: "mousedown",
          touchmove: "mousemove",
          touchend: "mouseup"
      }[event.type], true, true, window, 1,
          touch.screenX, touch.screenY,
          touch.clientX, touch.clientY, false,
          false, false, false, 0, null);

      touch.target.dispatchEvent(simulatedEvent);
      if(event.type == "touchmove"){
          event.preventDefault();
      }
    }` 

The 'old' solution with sync on pan and zoom events syncs perfectly when working with the mouse.

**Comment by msalsbery** [comment]
> The 'old' solution with sync on pan and zoom events syncs perfectly when working with the mouse.

Yeah...I believe the only way to make touch behave the same as mouse without some workarounds is to disable the flick gesture for touch. You'd lose the gesture but it should work identical to mouse.

**Comment by Medwar** [comment]
I found this:
http://insidebruegel.net/#p/v=udroom&lan=en&a=1026&x=s:3_l:6_v1:1026,vis_v2:1026,ir

Incredible.
Here the 'old' solution with sync on pan and zoom is used, and  it works 100% ideal sync, like a single image moving at pan.
On zoom there is no such sync, it zooms with a little delay, but it doesn't matter for me if I understand how pan sync works in this case. 
However I can't understand how it works.

**Comment by msalsbery** [comment]
> I found this:
> http://insidebruegel.net/#p/v=udroom&lan=en&a=1026&x=s:3_l:6_v1:1026,vis_v2:1026,ir

That's cool! It has a "heavy" feeling on touch...did they tune the spring and touch gesture settings?

**Comment by Medwar** [comment]
OSD module that is used is standard.
In jquery.uddragonviewer.js in override mode  I added:    line:60   animationTime: 0.5  - and it is now not so heavy on touch, but still keeps perfectly in sync.  
From first glance looks like spring settings are untouched.
Openseadragon manipulation and sync part seems identical to our 'pan zoom method' codepens above.
Can't find anything related to touch manipulation. If disable the two touch-related plugins:     
<script type="text/javascript" src="plugins/jquery.ui.touch-punch.min.js"></script>
<script type="text/javascript" src="plugins/jquery.touchSwipe.min.js"></script>
than nothing changes - sync still works.

I really can't understand why it works so perfect there.

**Comment by Medwar** [comment]
Looks like
"constrainDuringPan: true"  
in OSD options was the key.

**Comment by msalsbery** [comment]
> From first glance looks like spring settings are untouched.

Indeed. They did set constrainDuringPan: true, on the viewer...have you tried that? It feels heavy as well but seems to sync (not sure about pinch though)

**Comment by msalsbery** [comment]
LOL you beat me to it, never mind :-)

**Comment by Medwar** [comment]
Combining Ian and your advice and 'constrainDuringPan: true', I managed to synchronize both pan (perfectly) and zoom (99% perfectly)!
Thank you very much.

Finally it looks like:
```
...
constrainDuringPan: true,
...
zoomPanHandler(event) {
...
        this.viewers[i].viewport.zoomTo(newzoom, null, this.isTouchDevice);
        this.viewers[i].viewport.panTo(newpos);
...
}
```
Now it's time to get some sleep, 3.24 am and I get up at 6.

**Comment by msalsbery** [comment]
> Combining Ian's and your advice and 'constrainDuringPan: true', I managed to synchronize both pan (perfectly) and zoom (99% perfectly)!
> Thank you very much.

Awesome, thank you for the brain teaser and the update! Cheers!
