### ISSUE TITLE
Clear full website cache on new build in asp.net core 3.1 MVC?

### ISSUE THREAD

**Issue by sunnylubana1** [openseadragon/openseadragon#1866]
I have a website https://iamebook.com/ which is created in **ASP.net core 3.1 using c#.** This website contains ebooks. The most of content is static so I use cache in my website. I used response cache like [ResponseCache(Duration = (7 * 24 * 60 * 60))] and memcache like MemoryCache. all working perfectly fine. As most of the part is static so I can cache things for long time.

But I have a problem. As I host my website on a shared window server. Where they provide me Plesk for manage my website. In plesk there is no option to reset my website or do IIS restart to my website. This arises the problem, When I publish my new build to server. It retains all cache. So my changes on views are not reflect immediately. I need to know is there any way to remove or clear all cache while new build uploaded. Or Any get hit which do all clear process.

Please help me ASAP. Thanks in advance. Any other idea related to this are welcome.

**Comment by sunnylubana1** [comment]
sorry wrong group

**Comment by msalsbery** [comment]
@sunnylubana1  I just Remote Desktop to the server and use IIS management tools
