### ISSUE TITLE
OSD uses size URL parameter 'max' but support of 'max' by services is not required in IIIF Image API 2

### ISSUE THREAD

**Issue by lutzhelm** [openseadragon/openseadragon#1870]
On the Mirador Slack channel an error has been reported which I believe is linked to the behavior of OpenSeadragon. The report said that an image could not be displayed and the console read:

> Tile 5/0_0 failed to load: https://iiif.library.utoronto.ca/image/v2/bsr%3Absr%2FM5ef66…_4d122ac29f99d5c56413be1a972da52e.jp2/full/max/0/default.jpg - error: Image load aborted

The error can be reproduced here: https://lutzhelm.github.io/osd-max.html

The size parameter is set here:

https://github.com/openseadragon/openseadragon/blob/84dd5cd6a737aec00f4132453d3253077b24b8e6/src/iiiftilesource.js#L401

If tile width is the same as the image width, the size parameter is set to `max`. While `max` is a valid size parameter value in [IIIF Image API 2](https://iiif.io/api/image/2.1/#size) and the API states that the `full` size parameter is deprecated and will be (or in the meantime: has been) replaced with `max` in version 3, `max` is not [required](https://iiif.io/api/image/2.1/compliance/#size) to be supported by IIIF v2 services on any compliance level.

It would be trivial to replace `max` with `full` for v2, however, if a service does not support the requested full size because the requested tile is above a specified `maxWidth` or `maxArea` or `maxWidth`/`maxHeight`, an error might appear for services with those size restrictions.

**Comment by eroux** [comment]
I think going back to "full" (with a conditional on the api version) is a good option

**Comment by lutzhelm** [comment]
Code is already version conditional both for `full` region and `x,y,w,h` region, so this would be trivial.

https://github.com/openseadragon/openseadragon/blob/84dd5cd6a737aec00f4132453d3253077b24b8e6/src/iiiftilesource.js#L400-L403

https://github.com/openseadragon/openseadragon/blob/84dd5cd6a737aec00f4132453d3253077b24b8e6/src/iiiftilesource.js#L422-L425

**Comment by MImranAsghar** [comment]
Created a pull request: https://github.com/openseadragon/openseadragon/pull/1871
