### ISSUE TITLE
How to use OSD in a CMS, or how to handle different Image Dimensions dynamically

### ISSUE THREAD

**Issue by hhentschel** [openseadragon/openseadragon#1874]
Hi, 
i implemented OSD in my CMS (Craft CMS), working with .dzi Files (generated via VIPS),
like in this Codepen:
https://codepen.io/iangilman/pen/gpejpJ?editors=1010

I have a Detailpage for each Image and the access for each image file (_files) for the variable
`var dziFilesUrl = ...` is working correctly.
This is my code:
`var dziFilesUrl = "/user_assets/images/kelimImageDetail/{{ entry.title }}_files/";`

Now each images has different dimensions, so i cannot put a hard-coded .dzi file in the dziData, like:
`var dziData = '<?xml version="1.0" encoding="utf-8"?><Image TileSize="254" Overlap="1" Format="jpg" xmlns="http://schemas.microsoft.com/deepzoom/2008"><Size Width="13920" Height="10200"/></Image>';`

If i put the path to the .dzi, like this:
`var dziData = "../../web/user_assets/images/kelimImageDetail/{{ entry.title }}_files/{{ entry.title }}.dzi";`

i get an error:
Uncaught Error: Invalid XML: 

what i am doing wrong here?

thanks

**Comment by msalsbery** [comment]
> i get an error:
> Uncaught Error: Invalid XML

I would start with browser dev tools and look at the response to the request and make sure you're getting the file you're requesting. If you're getting the XML then perhaps it's malformed?

**Comment by iangilman** [comment]
That Codepen is just for cross site DZI access (where your code is on one server and your DZI data is on another server) where you can't set up CORS on the DZI server for whatever reason. That used to be fairly common, but now it's much more rare. Have you determined if that's your situation?

If you're either on the same server, or your DZI server has CORS, you should be able to just use the URL for the DZI file directly as your tile source and not bother with this stuff.

If you are dealing with a DZI server that doesn't have CORS and you're using this technique, you'll have to put actual XML in the `dziData` variable; putting a URL there doesn't work. One way to get that XML data would be to store it in a database and load it for each image.
