### ISSUE TITLE
How to add loading screen.icon in OSD images?

### ISSUE THREAD

**Issue by ghost** [openseadragon/openseadragon#1876]
Hello, I currently have a page with many images and it takes longtime to load them all, is there a way to add a loading icon on each image until they load, so user knows something is populating? I am currently using openseadragon plugin for wordpress.

https://suarrmaterials-test.syr.edu/materials-index/glass/different-types-of-glass/

**Comment by haseebrahman7** [comment]
This is my current code for the OSD image, how do i add the code that your referenced above.

    <div class="gallery_image-wrapper">
      <div class="gallery_image">
<div id="materials-0158" class="suarrmaterials-zoomable-image" style="height:400px; width:400px;" data-image="2020/06/DSC_0158-1.jpg"></div> <div class="gallery_image-description"><h3>DSC-0158</h3></div>     </div>
    </div>

**Comment by iangilman** [comment]
@haseebrahman7 You'll need to have access to the OpenSeadragon viewer via JavaScript. Is that possible with the WordPress OpenSeadragon plug-in?

BTW, do you have a different viewer for each image, or a lot of images in one viewer? Depending on the design of your page (the link you included in the issue description isn't working right now, so I can't tell), a single viewer might be a better solution. Of course I don't know if the WordPress OpenSeadragon plug-in supports that.
