### ISSUE TITLE
Navigator in Custom Location - Exception Thrown on destroy()

### ISSUE THREAD

**Issue by msalsbery** [openseadragon/openseadragon#1878]
When the Navigator is used in a custom location, e.g.
```
    OpenSeadragon({
        ...
        showNavigator:  true,
        navigatorId:   "navigatorDiv",
        ...
    });
```
If destroy() is called on the navigator's Viewer, an exception is thrown. This occurs when Control.destroy() calls Node.removeChild() to remove the Navigator, which isn't a child of any control container.

**Comment by iangilman** [comment]
@msalsbery good catch!

@Zero41120 excellent, thank you for connecting the dots.

@JoFrMueller would you be up for fixing this as a follow-up to your #1832?

This seems worth fixing before our next deploy, so I've added it to the 2.5.0 milestone.

**Comment by zero41120** [comment]
I did the following in `control.js` to silence the error 
```javascript
 destroy: function() {
        this.wrapper.removeChild( this.element );
        try {
            this.container.removeChild( this.wrapper );
        } catch(err) {
            this.wrapper.parentElement.removeChild(this.wrapper);
        }
    },
```

**Comment by msalsbery** [comment]
@zero41120  Thank you for that. I don't think we should even be calling removeChild if the navigator is placed in an external element, Hopefully just a check for the anchor being $.ControlAnchor.NONE should be done

@JoFrMueller would you be up for fixing this as a follow-up to your #1832?

If not, I'll take this one...

**Comment by woodchuck** [comment]
This works for me:
```javascript
    destroy: function() {
        this.wrapper.removeChild( this.element );
        if ( this.anchor !== $.ControlAnchor.NONE ) {
            this.container.removeChild( this.wrapper );
        }
    },
```

**Comment by msalsbery** [comment]
> This works for me:
> 
> ```js
>     destroy: function() {
>         this.wrapper.removeChild( this.element );
>         if ( this.anchor !== $.ControlAnchor.NONE ) {
>             this.container.removeChild( this.wrapper );
>         }
>     },
> ```

@woodchuck excellent, that’s what I had in mind! I haven’t got around to making sure ControlAnchore.NONE can be interpreted that way but seems logical.

Are you up for submitting a patch?

Thank you!

**Comment by JoFrMueller** [comment]
@msalsbery sorry for the late reply.

I'm too busy currently to investigate but it seems that @woodchuck already found a solution. Thanks a lot and sorry for causing this mess in the first place!

**Comment by msalsbery** [comment]
> @msalsbery sorry for the late reply.
> 
> I'm too busy currently to investigate but it seems that @woodchuck already found a solution. Thanks a lot and sorry for causing this mess in the first place!

@JoFrMueller 

No worries!

Wait...YOU're the one that caused this mess??? ;) lol

But seriously, thank YOU for your work!

**Comment by zero41120** [comment]
@JoFrMueller 
woodchuck solution fixes the bug reported here.
However, I still see error on `.destroy`, line 163 fails.
![image](https://user-images.githubusercontent.com/10471270/92666514-5317d400-f2be-11ea-9039-ab71a4aa3f17.png)
![image](https://user-images.githubusercontent.com/10471270/92666568-73479300-f2be-11ea-877a-16d4ec0de21d.png)

Look at my source code, 
I think if one calls `viewer.navigator.destroy()` before calling `viewer.destroy()`, then the error will occur.

**Comment by JoFrMueller** [comment]
@zero41120 thanks for pointing this out. I'm unable to investigate the topic currently for sure for the next 3-4 weeks because of too much work.

So in the end we'd need something that checks if the wrapper contains `this.element` like [Node.contains()](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) but with browser compatibility issues in mind? And then still, the *external* navigator has to get cleaned up somehow. A 2nd `destroy()` method call from the outside would create memory leaks for incautious cases otherwise.

**Comment by msalsbery** [comment]
@zero41120 

I’ll be fixing this soon if someone else doesn’t first

I don’t plan on using the first proposed solution as there shouldn’t be an exception thrown so I’m not a fan of just wrapping in a try block.

I like @JoFrMueller solution but I will make sure it covers hopefully all use cases

**Comment by woodchuck** [comment]
I don't yet understand all the implications of what I'm doing, but #1884 is a start on trying to address my use-case.

**Comment by mattwolff** [comment]
I think I might be experiencing something similar to this... I've set custom elements for my `zoomInButton` and `zoomOutButton`. After destroying a Viewer and creating a new one, zooming still works the following errors get logged to the console:
– `Cannot set property 'lastZoomTime' of undefined`
– `Cannot set property 'zooming' of undefined`

Screenshot of the console included as well:
<img width="1036" alt="Screen Shot 2020-11-20 at 7 32 05 PM" src="https://user-images.githubusercontent.com/21694984/99862297-265a2580-2b67-11eb-9b0e-153819dc320f.png">

**Comment by iangilman** [comment]
@mattwolff that does appear to be similar, but unrelated to this navigator issue, so it might be worth filing a separate issue for it.

Would you be interested in working on a patch for it? It seems that your custom button's click handler isn't being removed when the viewer is destroyed. This may be because the button itself isn't being destroyed, or maybe the button's destroy function isn't cleaning itself up properly. I'd start by putting some logging in Button.destroy to see if it's getting called properly.

BTW, why are you destroying the viewer and re-creating it? Another option might be to close the image and open a new one, but keep the same viewer, depending on your stereo.

**Comment by mattwolff** [comment]
Yes, I can try looking into this further and filing it as a separate issue. I'll give a shot at working on a patch, though I might be in a bit over my head. Will definitely start from Button.destroy though.

Also good to be reminded of those open / close methods. That might make more significantly more sense here...
