### ISSUE TITLE
"Permission denied to access property Symbol.toStringTag" and "OpenSeadragon.Viewer is not a constructor"

### ISSUE THREAD

**Issue by CoreyRo** [openseadragon/openseadragon#1883]
I am receiving these script error in my error logs when OSD is initializing.
The following errors are happening dozens of times a day in all major browsers, devices, and viewports. (Safari, iOS Safari, Firefox, Edge Chromium, Chrome, Android Chrome).

I've been trying to reproduce them, but I have not been able to, I'm kinda turning here as a last resort to see if anyone else has seen these particular errors. 

This is also my first issue I've opened on github, I don't know if I'm posting this in the right place.

### First Error
key| val
-- | --
  client_Type | Browser
  client_OS | Mac OS X 10.13
  client_Browser | Chrome 85.0
  sdkVersion | javascript:2.5.8
  Type | Permission denied to access property Symbol.toStringTag
  problemId | Permission denied to access property Symbol.toStringTag at n.type
  assembly | .../openseadragon2.4.2/openseadragon.min.js?v=2020.9.9.10:8:701
  method | n.type
  outerType | Permission denied to access property Symbol.toStringTag
  outerMessage | Permission denied to access property Symbol.toStringTag
  outerAssembly | .../openseadragon2.4.2/openseadragon.min.js
  outerMethod | n.type

In version 2.4.2
Line: 829 in  openseadragon.js
Line: 8:701 in openseadragon.min.js
```javascript
/**
 * Taken from jQuery 1.6.1
 * @function type
 * @memberof OpenSeadragon
 * @see {@link http://www.jquery.com/ jQuery}
 */
$.type = function( obj ) {
    return ( obj === null ) || ( obj === undefined ) ?
        String( obj ) :
        class2type[ toString.call(obj) ] || "object";
};
````
### Second Error
These errors are corresponding to these errors we are also getting.

a | b
-- | --
client_Type | Browser
client_OS | Mac OS X 10.13
client_Browser | Chrome 85.0
sdkVersion | javascript: 2.5.8
type | OpenSeadragon.Viewer is not a constructor
problemId | OpenSeadragon.Viewer is not a constructor at OpenSeadragon
assembly | /openseadragon2.4.2/openseadragon.min.js?v=2020.9.9.10:8:34
method | OpenSeadragon
outerType | OpenSeadragon.Viewer is not a constructor
outerMessage | OpenSeadragon.Viewer is not a constructor
outerAssembly | https://cdnjs.cloudflare.com/ajax/libs/openseadragon/2.4.2/openseadragon.min.js
outerMethod | OpenSeadragon

In version 2.4.2
Line: 745 in  openseadragon.js
Line: 8:34 in openseadragon.min.js
```javascript
function OpenSeadragon( options ){
    return new OpenSeadragon.Viewer( options );
}
```
### My code using OSD
This is happening on page load when we create the osd object. Here's a snippet out of that.

```javascript
//earlier in the code
var productImages = [];
//grabs the data-attributes for the zoom images off images in a carousel
$('.js-image-slide').each(function () {
    var _tempObj = {
        type: 'image',
        url: $(this).data('zoom'),
        thumbnail: $(this).attr('src'),
        crossOriginPolicy: 'Anonymous',
        ajaxWithCredentials: false
    };
    productImages.push(_tempObj);
});

//then we get down here
var zoomer = OpenSeadragon({
    element: $('#OSD').get(0), //this needs to be an element, *not* a string corresponding to an element *or* a jquery object
    debugMode: false, //obvs
    toolbar: 'OSD-tools', //this needs to be an ID.
    ajaxWithCredentials: false,
    crossOriginPolicy: 'anonymous',
    prefixUrl: '/Content/images/OSDGlyphs/',
    navImages: {
        zoomIn: {
            REST: 'zoom-in.png',
            HOVER: 'zoom-in--hover.png',
            DOWN: 'zoom-in--hover.png',
            GROUP: 'zoom-in.png'
        },
        zoomOut: {
            REST: 'zoom-out.png',
            HOVER: 'zoom-out--hover.png',
            DOWN: 'zoom-out--hover.png',
            GROUP: 'zoom-out.png'
        },
    },
    buildPyramid: true,
    visiblityRatio: .25,
    homeFillsViewer: true,
    autoHideControls: false,
    sequenceMode: true,
    showFullPageControl: false,
    showHomeControl: false,
    showSequenceControl: false,
    initialPage: 0,
    navPrevNextWrap: true,
    tileSources: productImages
});
```

I've been seeing a lot of these errors every day, however I cannot reproduce them in any browser. I'm kinda at a dead end here.

**Comment by iangilman** [comment]
Wow, that's a strange one! Your code looks fine to me. Is your code being processed in any sort of way, or running in an unusual environment?

**Comment by CoreyRo** [comment]
> 
> 
> Wow, that's a strange one! Your code looks fine to me. Is your code being processed in any sort of way, or running in an unusual environment?

It's trans-piled in gulp, the actual vendor files are not touched by gulp though. The environment it's running in is in the client info tables up there in the original post, its just Chrome 85

Here's what it looks like after the files run through gulp. Its the same.
```javascript
try {
	var zoomer = OpenSeadragon({
		element: $("#OSD").get(0),
		debugMode: !1,
		toolbar: "OSD-tools",
		ajaxWithCredentials: !1,
		crossOriginPolicy: "anonymous",
		prefixUrl: "/Content/images/OSDGlyphs/",
		navImages: {
			zoomIn: {
				REST: "zoom-in.png",
				HOVER: "zoom-in--hover.png",
				DOWN: "zoom-in--hover.png",
				GROUP: "zoom-in.png"
			},
			zoomOut: {
				REST: "zoom-out.png",
				HOVER: "zoom-out--hover.png",
				DOWN: "zoom-out--hover.png",
				GROUP: "zoom-out.png"
			}
		},
		buildPyramid: !0,
		visiblityRatio: .25,
		homeFillsViewer: !0,
		autoHideControls: !1,
		sequenceMode: !0,
		showFullPageControl: !1,
		showHomeControl: !1,
		showSequenceControl: !1,
		initialPage: 0,
		navPrevNextWrap: !0,
		tileSources: o
	}),
}
```
