### ISSUE TITLE
Change how internal console messages are written

### ISSUE THREAD

**Issue by geoff-harper** [openseadragon/openseadragon#1886]
Please change your console messages to info or debug instead of log so they can be disabled easily. Playing "spot the actually useful log I wrote for myself" in a sea of Openseadragon spam isn't a fun dev experience. Of course I could filter them every time I open the dev tools but why? It also spams remote analytics tools which requires extra filtering etc.

![Annotation 2020-09-21 141817](https://user-images.githubusercontent.com/7593910/93805239-707d6400-fc15-11ea-986a-89a54ec4e5c7.png)

**Comment by iangilman** [comment]
Good point! Someone should go through and audit which things should be what level. We already have a number of console.error, console.warn, and console.assert that should stay as is. Probably anything that's console.log should either become console.error (where it's an error message), console.info (if it's still worthwhile information), or removed/commented out (if it's entirely unnecessary).

You're welcome to make a pull request to that effect if you'd like. If not, hopefully someone else will pick this up.

**Comment by Abhishek-90** [comment]
Hi @iangilman, I am new to open source. I would like to start by contributing to this issue. Can you help me understand it completely or any guidance on how I can solve this would be really great and helpful.

**Comment by iangilman** [comment]
@Abhishek-90 welcome! This is a wonderful issue to work on :)

My recommendation is to search the `src` folder for `console.log` and look at all the ones that aren't commented out (if they are commented out we don't need to worry about them). If they are logging an error, change them to `console.error` and if they are just logging some information, change them to `console.info`. 

Don't change any of the logging in the `test` folder; those are all fine. 

If you need info about making a pull request, check out https://github.com/openseadragon/openseadragon/wiki/Making-a-Pull-Request

Thank you!

**Comment by Abhishek-90** [comment]
@iangilman thankyou very much. I will get to it now.

**Comment by bonysureliya** [comment]
Hi @iangilman , I want to contribute to issue can you help me further

**Comment by iangilman** [comment]
@bonysureliya Great! It looks like this issue is actually fixed (by #2073), so I'll close it. There are a number of other issues you can start with: 

https://github.com/openseadragon/openseadragon/labels/good%20first%20issue

Just pick one and get started! Let me know if you have questions. Here's more info on contributing: 

https://github.com/openseadragon/openseadragon/blob/master/CONTRIBUTING.md
