### ISSUE TITLE
how to get the current level 

### ISSUE THREAD

**Issue by xlb** [openseadragon/openseadragon#1888]
em,now I use 
`openSeadragon.world.getItemAt(0).lastDrawn ` 
to get  all the images and get the max Level of them .
is there any other ways to get the level directly?
thx.

**Comment by iangilman** [comment]
The system is set up as much as possible to make you not have to worry about things like tile level, so no, I don't think we have a convenient way to get that information.

I'm curious, what's your scenario? Why do you need to know the current tile level? Perhaps we should provide some sort of accessor for it for such occasions.

**Comment by xlb** [comment]
> The system is set up as much as possible to make you not have to worry about things like tile level, so no, I don't think we have a convenient way to get that information.
> 
> I'm curious, what's your scenario? Why do you need to know the current tile level? Perhaps we should provide some sort of accessor for it for such occasions.

I want to capture the current screen，but i dont konw how to  implement it, so I want to pass it to the background for recalculation to obtain.i has solved this problem yet,thank you for your reply

**Comment by iangilman** [comment]
@BeebBenjamin Thank you for sharing this!

**Comment by Dainerx** [comment]
What about: 

```js
  this.viewer.addHandler('tile-drawn', (tileEvent) => {
    console.log("Tile drawn:", tileEvent.tile.level); // this contains dzi level 
  });
```

But be careful this event will be fired an insane amount of times. A more prod friendly approach would be getting your image zoom. 1 being the slide level 0:

```js 
    this.viewer.addHandler("zoom", (zoomEvent: ZoomEvent) => {
      console.log("Image Zoom:", this.viewer.viewport.viewportToImageZoom(zoomEvent.zoom));
    })
```

**Comment by iangilman** [comment]
Converting from viewport zoom to a zoom level (according to the tile pyramid) can be a little tricky, though. I don't know that we have a built in facility for that.

**Comment by iangilman** [comment]
Note that with either the `lastDrawn` or the `tile-drawn` technique you will likely get more than one level, since most of the time OSD is working with tiles of more than one level.

**Comment by Dainerx** [comment]
> Note that with either the `lastDrawn` or the `tile-drawn` technique you will likely get more than one level, since most of the time OSD is working with tiles of more than one level.


True, what about the update-level event?

**Comment by iangilman** [comment]
I believe that fires once per level that gets considered per image per frame, so you'll get fewer of them than `tile-drawn` at least. You'll definitely get more than one level.

I suppose the thing to do is to just consider the highest level you get as being the "current" level.
