### ISSUE TITLE
Display Current Filename in Sequence Mode

### ISSUE THREAD

**Issue by barryRayPal** [openseadragon/openseadragon#1892]
Using seadragon in Sequence Mode on our website to display pathology slides.
Some are very similar. How can I display the 'current' filename ? 
seems like there is a simple way to specify a div id, but I cannot see it.
I could provide a DIV ID but cannot see where to add code using
innerHTML.

**Comment by iangilman** [comment]
My recommendation is to keep track of the names of the files in an array that matches the order of the tile sources you give to OpenSeadragon. Then when the viewer switches to a different page (watch for the "page" event), you can get the index of the page (available from the event, and also from the `currentPage` method on the viewer), and use that to look up the file name. You can then display that anywhere on your page, using normal web techniques.
