### ISSUE TITLE
Tiles are mixing up by zooming

### ISSUE THREAD

**Issue by erikradisch** [openseadragon/openseadragon#1894]
Has anybody experianced problems by zooming in images from a tiles-source? some pictures do have mixed up tiles by zooming in:
![grafik](https://user-images.githubusercontent.com/34335811/95778092-ac14c680-0cc7-11eb-90c3-781237e9f18b.png)

![grafik](https://user-images.githubusercontent.com/34335811/95778127-bfc02d00-0cc7-11eb-88b6-c5c2b01980ba.png)

The imageserver is cantaloupe. I do not get any errors. Strangely enough, this happens only one a few pictures. The majority is shown correctly.

**Comment by iangilman** [comment]
In my experience, that's usually due to some problem with the tiles or the tile source specification. Have you taken a look at the tiles? Does cantaloupe make it possible to do so? What tile source format are you using?
