### ISSUE TITLE
Zoom by Scroll gesture

### ISSUE THREAD

**Issue by Fil** [openseadragon/openseadragon#1895]
Hello,

sorry this is more a question than a bug report:

I'm evaluating OSD for a project similar to https://madmeg.org/delizie/ (which is currently using [d3-zoom](https://github.com/d3/d3-zoom) and a lot of custom code). OSD could be a replacement, with two caveats:
- a) the URL tracking part (I've found https://github.com/openseadragon/bookmark-url which I could adapt to a less verbose format)
- b) the "springing" methods used to change panning and zoom level: they make me ‘sea-sick’, iow I feel I'm not in control of the movement.

Re: **panning**, I've managed to have it work about the same by using a quite high value for springStiffness: 2 (or more makes it almost linear—ideally I'd want a totally linear change).

Re: **zooming** however, I haven't been able to find how to do the same. The case where I'm failing is on the faux wheel event generated by the scroll gesture on a Macbook's touchpad (image below).

In that case, OSD seems to be following its own logic of "zooming through several levels", where I'd want to fit it tightly to the scroll gesture as it does on the d3-zoom version. I think I've tried all the different OSD parameters and couldn't find the right one.

Have I missed something? Is this something that could be changed with a plugin? Should I instead use d3-zoom to pilot OSD?

Thank you

![](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/keyboards/trackpad2-two-finger.png)

**Comment by iangilman** [comment]
Wow, that's an amazing image! Is it your work?

Anyway, regarding the zooming, I think there are two factors potentially at work here. One is the springs, and the other is the fact that scroll wheel handling on the browser is unfortunately very idiosyncratic.

On the spring front, changing the stiffness is good. You might also try setting the `animationTime` down to something very small. Looks like zero is a valid value; perhaps that will fix it right there. If not, and if you're willing to build your own custom OpenSeadragon, you could try adding `, false` at the end of this line:

https://github.com/openseadragon/openseadragon/blob/4ab8cc748188f6c4dc5ad7d23e91945dd0194173/src/viewer.js#L3159

That will disable the springs entirely for zooming with the scroll wheel (and by "scroll wheel" I mean anything that generates the browser's wheel event, which includes the scroll gesture on the Magic Trackpad). Of course if setting animationTime to zero does the trick, you don't need to bother with this.

On the wheel handling front, I would first disable the springs somehow as above, but if that's not enough, then it's likely a difference in how OpenSeadragon tries to normalize the wheel events versus how D3 does it. If so, you can still use OpenSeadragon, but handle the wheel events yourself, and inform OpenSeadragon when it needs to zoom as appropriate. If you end up going that route, I can give you pointers if needed.

**Comment by Fil** [comment]
Thanks for pointing out this location! I inserted D3's code like so and the result is now "correct" (at least according to one person's opinion).


```patch
     thisScrollTime = $.now();
     deltaScrollTime = thisScrollTime - this._lastScrollTime;
+
+    function defaultWheelDelta(event) {
+          return -event.deltaY * (event.deltaMode === 1 ? 0.05 : event.deltaMode ? 1 : 0.002) * (event.ctrlKey ? 10 : 1);
+    }
+
     if (deltaScrollTime > this.minScrollDeltaTime) {
         this._lastScrollTime = thisScrollTime;

@@ -3153,7 +3158,7 @@ function onCanvasScroll( event ) {
         if ( !event.preventDefaultAction && this.viewport ) {
             gestureSettings = this.gestureSettingsByDeviceType( event.pointerType );
             if ( gestureSettings.scrollToZoom ) {
-                factor = Math.pow( this.zoomPerScroll, event.scroll );
+                factor = Math.pow( this.zoomPerScroll, 5 * defaultWheelDelta(event.originalEvent) );
                 this.viewport.zoomBy(
                     factor,
```

(I had to multiply d3's "wheel delta" by 5 because the base for D3 is 2, and for OSD it is 1.2).


`animationTime = 0` doesn't solve this issue (but it does solve the other issue as well as setting stiffness to 2).

See https://observablehq.com/d/bff8fb5a70c8f3f2 for my tests (and the current settings I'm using). (note: Observable has a "fullscreen" menu item which I encourage you to try.)


One last (but minor) problem is that when I pan quickly by clicking and dragging on the trackpad, then release the click, the image suddenly "jumps" to some final destination a bit farther than where I stop the movement.

**Comment by iangilman** [comment]
It's looking great! I may be biased, but it seems like it's already smoother than the D3 version, and it'll probably be smoother yet with the debug overlay turned off.

> One last (but minor) problem is that when I pan quickly by clicking and dragging on the trackpad, then release the click, the image suddenly "jumps" to some final destination a bit farther than where I stop the movement.

I tried to reproduce this (I have a magic trackpad) on your observable in full screen, and I managed to get it to happen once or twice out of dozens of tries. Is it something that happens more frequently for you? Does it only happen when you move quickly? Does it happen with other pointing devices besides the magic trackpad? Anyway, I'm not sure what would be causing it. My recommendation would be to throw some logging in and see if any patterns emerge.

BTW, regarding the scroll wheel fix, be sure to test on a variety of devices, browsers, and operating systems, to make sure you're happy. Unfortunately the scroll wheel support isn't very uniform.

I don't know if you're interested in trying to bring your scroll wheel improvement into OpenSeadragon (instead of having your own patched version)… We're interested in improving our scroll wheel support (https://github.com/openseadragon/openseadragon/issues/1820), but we'd want to make sure it's robust. Another option would be to make our scroll wheel support more pluggable, so people could provide their own code if they wanted to. Just thinking out loud.

**Comment by Fil** [comment]
I can reproduce the problematic pattern systematically. I hold a point, scroll to the left (or right), and release _in the same movement._ The point under the mouse never ends up being the point that I had clicked on at the beginning of the gesture.

See https://www.dropbox.com/s/kkx55t3nhttov6u/screengrab.mp4?dl=0

(Maybe I am just too used to D3's behavior, but I'm much more comfortable if I "feel" that I'm holding to the image rather than have it slip under my fingers.)

Re: the wheel improvement, I was happy to test this patch, but I certainly don't want to maintain a forked version of OSD.  I think that including a well-tested library (either this snippet from D3 or the facebook thing) would ease the burden of testing.
