### ISSUE TITLE
Jiggling edges on contrasty lines and overlays

### ISSUE THREAD

**Issue by janokay** [openseadragon/openseadragon#1905]
Hello, 

I have a simple question regarding edges/lines of mainly smaller zoomed out images:
I always recognize same jiggle on the edges or contrasty lines... somekind of lag/jumping into final position.

Is there anything I can do to fix it? I think it comes from the zoom smoothing? Or can someone point me into a direction where to investigate further...? 

![edges](https://user-images.githubusercontent.com/38293779/98292441-01818200-1fad-11eb-974c-650a638a9d5b.gif)

Thank you so much & sorry for my bad English! :)

**Comment by iangilman** [comment]
I don't know that there's much that can be done about that… You might try adjusting the `minPixelRatio`, which controls at what point between levels to switch from higher resolution to lower. The default is 0.5; see if setting it lower changes anything.
