### ISSUE TITLE
Converting between 'viewport zoom' and 'image zoom' 

### ISSUE THREAD

**Issue by kimberashman** [openseadragon/openseadragon#1906]
I'd like to convert 'viewport zoom' to 'image zoom' from a log where only viewport zoom was recorded. However, when I use the definitions from the documentation, the image zoom isn't correct (I checked this by looking at the numbers displayed on the sidebar when using the application. 

Viewport zoom: ratio of the displayed image’s width to viewport’s width.
Image zoom: ratio of the original image size to displayed image size.  

Rearranging these equations, image zoom = original image size / [(viewport width * viewport zoom) * (viewport height * viewport zoom)]

My original image size is: 
height = 33423
width = 64256 

As an example, I've logged viewport zoom = 148.36, viewport size = (433 x 252). The displayed image zoom is 2.77. 
When I use the equation, I get image zoom = (64256*33423)/[(433*148)*(252*148)] = 0.9

Is there something I'm missing or perhaps I'm misunderstanding what 'displayed image size' is?

**Comment by iangilman** [comment]
I don't think you should include the height at all, so it should be:

image zoom = original image width / (viewport width * viewport zoom)

Using your numbers, I find that 433 * 148.36 = 64239.88. Dividing 64256 by that number gives an image zoom of 1.00025093, which seems about right to me. I'm not sure how to explain the 2.77 you're getting, though.

One thing to be aware of is that the viewport zoom formula (ratio of the displayed image’s width to viewport’s width) only holds true if you are leaving the image to its default viewport coordinates. If you explicitly set it to some other width in the viewport, it'll be a different ratio.

**Comment by kimberashman** [comment]
Hi Ian, 
Thank you for your quick reply. I'm still trying to work backwards to understand the numbers I'm getting. I see how the equation would work, but the 2.77 image zoom makes more sense to me because when I replicate the viewport size/zoom with my pathology image it seems past the native image resolution. 

I believe the image is left to its default viewport coordinates, but I'll check. 

The image is tiled as a pyramidal jpg since its so large. I'm wondering if this would cause an issue with the zoom values? I see the documentation says "  Note: not accurate with multi-image. "

**Comment by iangilman** [comment]
> The image is tiled as a pyramidal jpg since its so large. I'm wondering if this would cause an issue with the zoom values? I see the documentation says " Note: not accurate with multi-image. "

Whether it's a tiled pyramid or not shouldn't have an effect. Either way, it's still considered a single "image", even if it's made of multiple tiles. What's meant by "multi-image" is if there are more than one such image displayed in the viewport… Then of course it's not possible to know the image zoom at the viewport level because it doesn't know which image you're referring to. In those cases, you would need to access the image's conversion functions. Anyway, you have just a single (tiled pyramid) image, right? So it doesn't affect you.

**Comment by kimberashman** [comment]
I figured out where my numbers are coming from. The image zoom is the width of the displayed image canvas (which in my case, 1200 px wide) divided by the viewport width.  Alternatively, the viewport zoom * 1200 px / original image width. For instance, if I am fully zoomed out (showing the entire image in the display and viewport), the image zoom is displayed as 0.02  (or 1200 / 64256 px). 
<img width="1315" alt="Screen Shot 2020-12-22 at 6 58 50 PM" src="https://user-images.githubusercontent.com/52216269/102947197-62dfb080-4488-11eb-8abc-fcb792c8d98a.png">
