### ISSUE TITLE
how to switch between only two images with button click (speed matters)?

### ISSUE THREAD

**Issue by ahmed4end** [openseadragon/openseadragon#1907]
the following code works but it's a bit slow when switching between the images i hope there is a better way to switch between two images .
`
var viewer = OpenSeadragon({
        id: "wheelzoom.exe",
        prefixUrl: 'https://openseadragon.github.io/openseadragon/images/', 
});

viewer.open( [{type: 'image', url: images_viewer_container[0] }, {type: 'image', url: images_viewer_container[1] }] ); 

//the toggle button.
var curr_page = 0
    $( "#ToggleImages" ).click(function() {
        if (curr_page==0){
            viewer.goToPage(1);
            curr_page = 1;
        }else{
            viewer.goToPage(0);
            curr_page = 0;
        }
    });
`

**Comment by iangilman** [comment]
This should do the trick: https://codepen.io/iangilman/pen/erjyBP

**Comment by ahmed4end** [comment]
> This should do the trick: https://codepen.io/iangilman/pen/erjyBP

thanks it did help .
