### ISSUE TITLE
[Performance] loading new tiles with .open() makes TAPS lag for seconds!

### ISSUE THREAD

**Issue by ahmed4end** [openseadragon/openseadragon#1909]
i'm using multiple taps on my site, one of the taps has the openseadragon viewer inside it, when clicking certain button js fires ->
viewer.open(tiles) which causes navigating between taps lags for 2 seconds, what can i do to make it load new images smoothly without doing anything with the performance of the taps switching !

var viewer = OpenSeadragon({
        id: "wheelzoom.exe",
        immediateRender: true,
        prefixUrl: 'https://openseadragon.github.io/openseadragon/images/',
    });

$('#btn').on('click', function() { viewer.open( tiles );})

**Comment by msalsbery** [comment]
@ahmed4end 

The majority of the work done when opening a tile source is asynchronous so your UI _shouldn't_ be slowed much. Do you have any event handlers on your viewer that wait for anything?

**Comment by ahmed4end** [comment]
@msalsbery yeah i do have handlers.... i use .open() to open two images then the handlers are for the swapping between the images in the viewer .
