### ISSUE TITLE
how to translate location from one openseadragon view to the other 

### ISSUE THREAD

**Issue by wentong12** [openseadragon/openseadragon#1910]
I have two openseadragon views, A 10nm/pixel resolution , B is 1nm/pixel resolution, B has 10 times higher resolution than A, but both A and B contain the same object.

People would view A first, and when they look at one location and want to zoom in, they would click B channel, and B would give a deeper zoom in image, and if people want to zoom out, they would click A and find themselves same location in A before they zoom in using B channel.

This requires to translates the location people are viewing in A into image B, and when people come back from B to A, they will be still look at the same location they were viewing before at the same magnification. 

What would be the best way to do it?

**Comment by iangilman** [comment]
If both viewers have the same object, but at different resolutions, then their viewport coordinates are actually still the same. You can just grab the zoom/pan info from viewer A and set it into viewer B. You could also do a `getBounds` on viewer A and call `fitBounds` with that value in viewer B. 

Here's an example of keeping two viewers synchronized in real time: https://codepen.io/iangilman/pen/BpwBJe Perhaps its code can help give you ideas for how to achieve your scenario.

[Apologies for the late response... I assume you've already solved your problem, but I'm answering here in case this is helpful for anyone else.]
