### ISSUE TITLE
Opening a .zip or .szi instead of a .dzi openseadragon

### ISSUE THREAD

**Issue by pr8448bristol** [openseadragon/openseadragon#1911]
I'm setting up a website to display a variety of zoology histology slides. I will preface this by saying that I'm not a web developer so my explanations and understanding might be a bit off!

I have written the code for the website in Python using the Django framework with hosting on a DigitalOcean droplet. The static files are being stored on a remote AWS server which requires a password and security key to serve up the static files. This works fine for single images, but doesn't seem to work for .dzi and openseadragon.

My work around for this was to have the .dzi files on the remote server as compressed files (either .zip or .szi). Is there a way that openseadragon can deal with these compressed files to display the .dzi within?

**Comment by msalsbery** [comment]
@pr8448bristol 

There's no support for extracting images or image tiles from files.

.dzi tile sets should work in your situation, however...what problems are you encountering there?

**Comment by jo-chemla** [comment]
Hi @iangilman, noticed the issue was just closed. Has zipped dzi directory or szi support been integrated inro OSD? Thanks!

**Comment by iangilman** [comment]
@jo-chemla It has not. This issue was marked as a question, and I closed it recently while bulk closing questions older than a year. Looking at it more closely, I'm seeing it's actually a duplicate of https://github.com/openseadragon/openseadragon/issues/944, so I'll keep it closed in favor of that issue. You might follow along there... Looks like progress is happening!

**Comment by jo-chemla** [comment]
Perfect, thanks for getting back, and the gratr work regarding osd! Will follow the progress there. Best,

**Comment by jbhanks** [comment]
Any progress on this? Even some example code of the uncompressed zip by reading the zip index would be great. I've seen it suggested in several places but not having experience in JS it will be a heavy lift to turn the advice into something I can use.

All I really want is a way to host DZI images on Backblaze B2 (where unfortunately, uploading folders is not a thing).

**Comment by iangilman** [comment]
@jbhanks This issue has been closed in favor of #944... You might take a look and/or ask questions there.

**Comment by Benomrans** [comment]
@jbhanks 
Just a side note!
I gave up using Backblaze B2, switched to z1storage.com and tebi.io S3-compatibles, no fuss there at all. and managing both with [S3Browser](https://s3browser.com) would make things so much easier.
