### ISSUE TITLE
Fullscreen not working when code is executed from outside

### ISSUE THREAD

**Issue by tonycstech** [openseadragon/openseadragon#1913]
Folder structure:
P:\WWW\openseadragon\openseadragon.php located along side with all javascript files
P:\WWW\search.php located in the root. Calls openseadragon\openseadragon.php
Calling for openseadragon.php outside makes fullscreen not working.

**Comment by iangilman** [comment]
How are you calling fullscreen from outside the page? Is it in an iframe or something?

**Comment by tonycstech** [comment]
Calling from iframe.
Both are in the same iframe.

Purpose: for mobile, it's easier and faster to navigate the image when it's
in full screen.
For desktop, it's not so much.

**Comment by iangilman** [comment]
There are definitely restrictions in the browser on when you can go into fullscreen. I think it's not possible to do it automatically; I believe it requires user interaction. That's just a browser restriction; nothing to do with OSD specifically. 

As for displaying fullscreen inside an iframe, you need to add the allowfullscreen attribute (see https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen#compatible_elements).

**Comment by tonycstech** [comment]
>
> Understood.

Thank you for the clarification

>
