### ISSUE TITLE
Configurations dont work inside openseadragon.js

### ISSUE THREAD

**Issue by tonycstech** [openseadragon/openseadragon#1914]
I tried changing             maxZoomPixelRatio:      2.1, //-> higher allows 'over zoom' into pixels
no effect at all.
None of the options i change seem to have any noticeable effect.

**Comment by msalsbery** [comment]
@tonycstech 

Once a viewer is created, try changing the value on the viewer's viewport object (e.g. viewer.viewport. maxZoomPixelRatio)
