### ISSUE TITLE
Extend the openseadragon types  and adding opensedragon selection types

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1916]
Hi 

I am using the following package for types :
`    "@types/openseadragon": "^2.4.2",
`

Now i would like to add the openseadragonselection plugin that does not have a type.
I found a nice GitHub with the types I need. :
https://github.com/alvaromartmart/types-openseadragonselection/blob/master/index.d.ts 

my question is how can I extend the openseadraogn.viewer types without overriding it 

when I tried the following :

declare module 'openseadragon' { } 

even only while I declare the module is will override all current types

**Comment by alvaromartmart** [comment]
Hi @johnico, sorry for the late response. To be honest I'm not being able to dedicate time to the typings lately.
Maybe this helps:
https://github.com/alvaromartmart/types-openseadragon/issues/5#issuecomment-532053867
Good luck!
