### ISSUE TITLE
How to display heatmap in tile level

### ISSUE THREAD

**Issue by MounikaAV** [openseadragon/openseadragon#1917]
Hi, I am using openseadragon for my project to visualize medical pyramidal images. I want to display heatmap-like data at the tile level based on my algorithm prediction colors.
Can anyone help me how to achieve this?

Thanks in Advance :)

**Comment by jlevy44** [comment]
One way of doing this could be blending a heatmap and image in python before converting to a dzi-like format, here's another interesting alternative that I found:

https://github.com/CancerDataScience/HistomicsML2/blob/66b9a4e35bc9f772093f48d32a40a475eb38648f/web_app/js/heatmaps.js#L113
https://github.com/CancerDataScience/HistomicsML2/blob/66b9a4e35bc9f772093f48d32a40a475eb38648f/predict-rest-api/heatmap.py

It would be really nice to have a realtime updating or overlay component without heavy I/O.
@sumanthratna
