### ISSUE TITLE
how disable pan/zoom not using setMouseNavEnabled

### ISSUE THREAD

**Issue by sevaTechoPark** [openseadragon/openseadragon#1923]
story:
I must disable pan/zoom on `canvas-press` by some logic
And must enable pan/zoom after `canvas-release`

The only solution that I found is `setMouseNavEnabled`(but this turn off handle `canvas-release`).
To handle `canvas-release`:
```
MouseTracker.releaseHandler:
if (!this.viewer.isMouseNavEnabled()) {
    this.onCanvasRelease(evt);
}
```
and it works, but may be I can use native solution?

**Comment by nikushx** [comment]
viewer.panHorizontal = false;
viewer.panVertical = false;

should do the trick in your case.

**Comment by msalsbery** [comment]
@sevaTechoPark

When version OpenSeadragon 3.0.0 is released you can do something like this:
```javascript
    let disablePanZoom = false;

    viewer.addHandler('canvas-press', (event) => {
      disablePanZoom = true;
    });

    viewer.addHandler('canvas-release', (event) => {
      disablePanZoom = false;
    });

    viewer.addHandler('canvas-click', (event) => {
      event.preventDefaultAction = disablePanZoom;
    });

    viewer.addHandler('canvas-drag', (event) => {
      event.preventDefaultAction = disablePanZoom;
    });

    viewer.addHandler('canvas-scroll', (event) => {
      event.preventDefaultAction = disablePanZoom;
    });

    viewer.addHandler('canvas-pinch', (event) => {
      event.preventDefaultPanAction = disablePanZoom;
      event.preventDefaultZoomAction = disablePanZoom;
      event.preventDefaultRotateAction = disablePanZoom;
    });
```
You can try it now by building off the master branch here or [there's test builds here](https://github.com/openseadragon/openseadragon/pull/1872#issuecomment-673608460)
