### ISSUE TITLE
Trying to implement image comparison slider on large set of images (500+)

### ISSUE THREAD

**Issue by fnandoz21** [openseadragon/openseadragon#1926]
I am trying to implement something similar to this image comparison slider in a web app that utilizes OSD: https://codepen.io/imoskvin/pen/yOXqvO.

However, when I try to implement this on a large set of image, some over 500 images, the performance greatly decreases. By this I mean that there is a great decrease in frame and this lingers even after I toggle off the slider with a button on my UI. I am a bit confused as to why is this the case, since when I run this same slider on a smaller set of images, under 10, everything seemingly works fine with no drops in performance. Also, when I leave the slider toggled off, there are no issues with performance. If someone could perhaps indicate exactly where a bunch of extraneous calls might be being made in the background based on the codepen code, that would be very helpful.

**Comment by abrlam** [comment]
For clarity, could you provide some starter code? Are you comparing 500 images all at the same time? Or are you comparing 2 images at a time, but there's a selection where you can choose other images?
