### ISSUE TITLE
Multi-overlayed images and advanced features example?

### ISSUE THREAD

**Issue by manoaman** [openseadragon/openseadragon#1927]
Hi,

I'm interested if openseadragon supports the following features by default.  The features are similar to what Adobe Photoshop/Illustrator provide on the desktop app, and I was wondering if I could do the same on a web platform.  If not, it would be great if someone can point me to the closest examples available.  

Thank you.
-m

Use cases:
1. User wants to overlay multiple images. (5~6 layers, or could be more.)
2. User wants to change the opacity levels of each layer.
3. User wants to zoom in/out when layers are on top of one another.
4. User may want to overlay svg image on the top, and click on region of interests.  e.g.) A image which is border lines of a map with transparent background.

**Comment by msalsbery** [comment]
@manoaman 

Your first three use cases are supported, although you'll need to provide the UI for users to use those features.

For SVG overlays, OpenSeadragon doesn't have that built-in, but there's plugins available that may help out, or t least get you started (see [OpenSeadragon Plugins](http://openseadragon.github.io/#plugins))

**Comment by iangilman** [comment]
Here's info on the API for multiple images: http://openseadragon.github.io/examples/multi-image/
