### ISSUE TITLE
event.PreventDefaultAction behavior

### ISSUE THREAD

**Issue by darshats** [openseadragon/openseadragon#1929]
Hi,
What is the right way to suppress an event from bubbling up after a handler has been called?
In my case, I am hooking up the mousetracker for nonPrimaryPress. In the event handler I set the event.preventDefaultAction to true to indicate (in my understanding) that the framework should not invoke any other handlers. But I do see the browser's default context menu also popup.

At line 2781 of openseadragon.js, the _return value_ from the handler is used like:
```
                if ( propagate === false ) {
                    $.cancelEvent( event );
                }
```
So is my understanding correct - the argument property is not used but return value from the handler is utilized? I tried that too but it made no difference.
Would appreciate if someone can clarify the semantics, or maybe I am doing something incorrect.
Thank you,
Darshat Shah

**Comment by msalsbery** [comment]
Hi @darshats  There's a large overhaul of MouseTracker that will hopefully land soon. It's being tested and some final changes being tinkered with, but if you want to check it out [see here](https://github.com/openseadragon/openseadragon/pull/1872#issuecomment-673608460)

Once it's finalized in the next day or three I'll be able to offer possible solutions...
