### ISSUE TITLE
Navigator still visible

### ISSUE THREAD

**Issue by lledieu** [openseadragon/openseadragon#1933]
Hi,

I am trying to hide navigator on user demand using OpenSeadragon.Navigator.setVisible( false )

The contents of navigator is hidden but the dark rectangle is still there (2 parents div as i can see). Maybe I am not supposed to act directly on navigator... Where can I found a working example ?

**Comment by lledieu** [comment]
It seems to work with this : 

`viewer.navigator.element.classList.toggle( "inactive" );`

With CSS : 

```
.inactive {
	display: none !important;
	z-index: -5 !important;
}
```

**Comment by iangilman** [comment]
When you say you were using `OpenSeadragon.Navigator.setVisible( false )` do you mean you literally called that? Or did you do `viewer.navigator.setVisible( false )`? The former shouldn't work, but I am surprised if the latter didn't work.

Anyway, your workaround looks reasonable.
