### ISSUE TITLE
How to get image corner position after rotate?

### ISSUE THREAD

**Issue by jaroslawwroblewski** [openseadragon/openseadragon#1935]
I found many examples of how to pan an image, but I don't know how to get information about the position of the image in the viewport... How can I get the image corner position after rotation?

![osd_rotate](https://user-images.githubusercontent.com/40166450/106578564-edafd280-653f-11eb-916f-f78ec8f7ceaa.png)

**Comment by zero41120** [comment]
If you set rotation on the tile image, not viewer, then you can do this:
```
viewer.world.getItemAt(0).setRotation(33)
viewer.world.getItemAt(0).imageToViewportCoordinates(0,0)
// a.Point {x: 0.438059858489113, y: -0.1664542532764257}
```
