### ISSUE TITLE
Toggle control button

### ISSUE THREAD

**Issue by fr75** [openseadragon/openseadragon#1939]
Hi,

I have added a new control button named below "customButton" to toggle masking/displaying layers by this way :

      customButton = new OpenSeadragon.Button({
                 tooltip: 'Masque/Démasque les couches (Toggle layers visibility)',
      
                  srcRest: '../bouton_visibilite_couches_inactif.png',
                  srcGroup: '../bouton_visibilite_couches_inactif.png',
                  srcHover: '../bouton_visibilite_couches_survol.png',
                  srcDown: '../bouton_visibilite_couches_survol.png',
                  onClick: inverseMasquageCouches // or for testing : function(event){console.log("click bouton")}
      });
      
      var coll_10_4 = OpenSeadragon({
               id: "coll_10_4",
                prefixUrl: "../plans_zoomables_outils/openseadragon/openseadragon-bin/images/", //Path to icons controls
                tileSources: 
                    // $tuiles
                    [
                        {tileSource: "../plans/coll/zoom/coll_10_4.dzi", opacity: 1}, 
                        {tileSource: "../plans/coll/zoom/coll_10_4_a.dzi", opacity: document.querySelector('.slider_1_coll_10_4_a').value/1}, 
                    ],
                    // $tuiles fin,
                showNavigator: true,
                navigatorAutoFade: true,
                showNavigationControl: true,
                maxZoomPixelRatio: 3,
                preserveViewport: true,
        });
        
        coll_10_4.buttons.buttons.push(customButton);
        coll_10_4.buttons.element.appendChild(customButton.element);

My question
------------
Is there a way to dynamically change the icon of the button so that it reflects the toggeling state ?

Thank you.

**Comment by fr75** [comment]
I have succeded in toggling the button appearence by updating the DOM directly. This is done by the fucntion below.
But maybe there is a better way ?

        // Assume in this example, boutonGroupe = coll_10_4.buttons
      
        // Change the button appearance
            function etatBoutonCouchesMasquees(boutonsGroupe, etat) {
                if (customButton == null) {
                    console.log("!!! customButton pas encore défini");
                    return;
                }
                if (etat == true) { // Affiche le bouton indiquant que les couches sont masquées
                    let msg = "Affiche les couches (display the layers)";
                    customButton.element.title = msg;
                    customButton.element.childNodes[0].src = '../bouton_nvisibilite_couches_inactif.png';
                    customButton.element.childNodes[1].src = '../bouton_nvisibilite_couches_inactif.png';
                    customButton.element.childNodes[2].src = '../bouton_nvisibilite_couches_survol.png';
                    customButton.element.childNodes[3].src = '../bouton_nvisibilite_couches_survol.png';
                    for (i  = 0 ; i < 4 ; i ++)
                        customButton.element.childNodes[i].alt = msg;
        
                }
                else { // Affiche le bouton indiquant que les couches sont démasquées
                    let msg = "Masque les couches (do not display the layers)";
                    customButton.element.title = msg;
                    customButton.element.childNodes[0].src = '../bouton_visibilite_couches_inactif.png';
                    customButton.element.childNodes[1].src = '../bouton_visibilite_couches_inactif.png';
                    customButton.element.childNodes[2].src = '../bouton_visibilite_couches_survol.png';
                    customButton.element.childNodes[3].src = '..//bouton_visibilite_couches_survol.png';
                    for (i  = 0 ; i < 4 ; i ++)
                        customButton.element.childNodes[i].alt = msg;
                }
                boutonsGroupe.element.removeChild(customButton.element);
                boutonsGroupe.element.appendChild(customButton.element);
            }

**Comment by iangilman** [comment]
Unfortunately this area of customization isn't very robust in OpenSeadragon. Your solution looks reasonable :-)
