### ISSUE TITLE
png pyramid artifacts 

### ISSUE THREAD

**Issue by kimberashman** [openseadragon/openseadragon#1942]
Hi, 
I noticed when I use an image pyramid of png tiles, grey lines appear in the viewer. I made the pyramid using the same method ([libvips](https://libvips.github.io/libvips/API/current/Making-image-pyramids.md.html)) I used for creating jpeg pyramids (without the artifacts). There are the same number of tiles in both the jpeg and png pyramids. 

There is a 1 pixel overlap. The xml file: 
<?xml version="1.0" encoding="UTF-8"?>
<Image xmlns="http://schemas.microsoft.com/deepzoom/2008"
  Format="png"
  Overlap="1"
  TileSize="254"
  >
  <Size
    Height="33423"
    Width="64798"
  />
</Image>

The artifacts disappear if image zoom > 1 
![Capture](https://user-images.githubusercontent.com/52216269/107798920-6114c980-6d22-11eb-9c24-8c3b50bf06ce.PNG)

**Comment by alvaromartmart** [comment]
This may actually be related to #1683

**Comment by kimberashman** [comment]
@alvaromartmart thank you for the link, it is a firefox issue. I just tried it in chrome and the lines disappeared.
