### ISSUE TITLE
Fixing the translation offset between a pair of images

### ISSUE THREAD

**Issue by ruqayya** [openseadragon/openseadragon#1946]
Hi,

I have pairs of histology images that I display side by side as shown in the screenshot below. There is some offset in the images that I want to fix. I was previously using Tkinter interface and was able to fix the translation offset using phase correlation. With openseadragon, I am not sure, how to access tiles (for phase correlation) before they are displayed on the viewer. Any help, please?

![image](https://user-images.githubusercontent.com/18444369/109613455-14562e80-7b29-11eb-8ce4-1ebb667d1f94.png)

**Comment by iangilman** [comment]
@ruqayya are you saying you want access to the pixels so you can do computer vision stuff to them? Or are you just wanting to shift the images around by some known amount?
