### ISSUE TITLE
tile source with referenceStripThumbnailUrl and url?

### ISSUE THREAD

**Issue by mnyrop** [openseadragon/openseadragon#1952]
Hello, 

**My Tl;dr questions are:** 
- Can I add tile sources each with a IIIF json `url` AND a `referenceStripThumbnailUrl`?
- Is there a way to get the `referenceStrip` to work without this? (e.g., different config settings or standard derivative sizes I should be generating?)

**Context:** 
I've been following along with some issues in the repo and stealing ideas, but I'm still struggling **to get reference strip thumbnails working for IIIF level 0 (static derivative) sources.**

I made a [repo](https://github.com/mnyrop/osd_test) to demonstrate. So far, I can get my `tileSources` working OR my `referenceStrip`, but not both.
- Working tile sources:
  + [demo](http://marii.info/osd_test/)
  + [js osd config](https://github.com/mnyrop/osd_test/blob/main/src/osd-1.js)
- Working reference strip (with `referenceStripThumbnailUrl`):
  + [demo](http://marii.info/osd_test/thumbs/)
  + [js osd config](https://github.com/mnyrop/osd_test/blob/main/src/osd-2.js)

My [manifest](http://marii.info/osd_test/img/derivatives/iiif/obj12/manifest.json) and each loaded [canvas](https://github.com/mnyrop/osd_test/blob/main/img/derivatives/iiif/canvas/obj12_000.json) have thumbnails and I have `useCanvas` set to `true`, but OSD has not been requesting the existing thumbnail derivatives.

Ref:
```
//! openseadragon 2.4.2
//! Built on 2020-03-05
//! Git commit: v2.4.2-0-c450749
//! http://openseadragon.github.io
//! License: http://openseadragon.github.io/license/
```

Thanks!

**Comment by SamHall** [comment]
I abandoned the reference strip and used flickity.js instead. It seems to work well. 
In this example I use styled numbers in boxes, but you could use small thumbnails instead.

https://chattanoogahistory.com/williamspapers.php

**Comment by iangilman** [comment]
@mnyrop in https://github.com/mnyrop/osd_test/blob/main/src/osd-2.js you should change line 10: 

```
url: val.images[0].resource.service['@id'] + '/info.json',
```

...to:

```
tileSource: val.images[0].resource.service['@id'] + '/info.json',
```

**Comment by mnyrop** [comment]
thanks @iangilman! that works perfectly. i'll leave the repo up (with fix added) in case this ticket is useful to anyone else.
