### ISSUE TITLE
Remote DZI and webp

### ISSUE THREAD

**Issue by cheuksing** [openseadragon/openseadragon#1955]
I have my dzi and image host on 1 server and all images are cached by an CDN.
Unfortunately, my CDN doesn't support .dzi caching.
However it supports returning a webp image instead if users browser support.

2 Question,
Can I know my .dzi from mydomain.com, and all other tiles form cdn.mydomain.com?
Can Osd handle webp format?

Thank you very much.

**Comment by iangilman** [comment]
One approach is to use the information from the DZI file and give that directly to OSD, like so: 

https://codepen.io/iangilman/pen/gpejpJ

BTW, `.xml` is a valid extension for DZI files, so if your CDN supports that, you could solve the issue that way. 

As for handling webp, we've just landed a patch to help with that: https://github.com/openseadragon/openseadragon/pull/1954 If you want to use it, you'll have to build the latest OSD from master (until we do a new release, which may still be a few months away). Note that of course you're responsible to verify that the user's browser can support webp.
