### ISSUE TITLE
Openseadragon with openSeaDragonFabricJsoverlay plugin issue on rotate with drawer annotation

### ISSUE THREAD

**Issue by dhandeeswaran** [openseadragon/openseadragon#1963]
am using openseadragon , openseadragonfabricoverlay plugin, I have successfully integrate with angular 10 its working fine. I can draw rectangle, circle, line, polyline , etc.., on the images, and also panning, zooming is working excellent with annotation, but the issue is rotate the select single tile (image)  from multiple images with  annotation like rectangle, circle, etc.. when rotating the image the annotation is not  positioned correctly.

* how to get center point for each images for rotation.

--> please help resolve this issue, and if you have and example code regarding this issue please forward the link

Note: I can able to rotate single image tile with annotation, its working fine

**Comment by iangilman** [comment]
Looks like this issue might be relevant: https://github.com/altert/OpenseadragonFabricjsOverlay/issues/9
