### ISSUE TITLE
Overlay to Imageposition in every Tile

### ISSUE THREAD

**Issue by aslan-itc** [openseadragon/openseadragon#1965]
Hi,

i have a overlay, for example at position x1=0.75210682645089000, x2=0.77021505589436000, y1=0.40701790039554000, y2=0.41883590276918000 and if the user zooms and mouseover it he see the full resulting rect at this coordinates.
Then i try to find out the imagecoordinates of this overlay for every tile becaus i want to replace the overlay with an other image.

```
var point = new Point(0, 0);
var pixel = viewer.viewport.pixelFromPoint(new OpenSeadragon.Point(x, y));
var faktorX = tiletouse.size.x / img.width;
var xBeginn = pixel.x - tiletouse.position.x;
xBeginn = xBeginn / faktorX;
var faktorY = tiletouse.size.y / img.height;
var yBeginn = pixel.y - tiletouse.position.y;
yBeginn = yBeginn / faktorY;
point.x = xBeginn;
point.y = yBeginn;
return point;
```

This works fine and i get the correct image coordinates for this overlay. The coordinates changes between +/- 0.1. Then i try to find every Tile bevor the current Tile for that Overlay. For Example the User has the maximum zoom and is in Tile:

Level: 13
Column: 17
Row: 9

Now i try to find out the image coordinates for that Overlay in the Tiles before for this Image

```
var viewportPos = viewer.viewport.pointFromPixel(event.position);
var tiledImage = viewer.world.getItemAt(0);
var imgtile = new Image();
var weiteretiles = new Array();

if (tiledImage) {
    var viewportPosRect = new OpenSeadragon.Rect(viewportPos.x, viewportPos.y, 0, 0);
    var tileSourcePosRect = tiledImage._viewportToTiledImageRectangle(viewportPosRect);
    var tileSourcePos = tileSourcePosRect.getTopLeft();
    var source = tiledImage.source;
    if (tileSourcePos.x >= 0 && tileSourcePos.x <= 1 && tileSourcePos.y >= 0 &&
        tileSourcePos.y <= 1 / source.aspectRatio) {

        var level, tilePoint;
        for (level = source.maxLevel; level >= source.maxLevel - neededTileDepth; level--) {
            if (level == source.maxLevel) {
                continue;
            }

            tilePoint = source.getTileAtPoint(level, tileSourcePos);
            var nexttile = tiledImage.tilesMatrix[level][tilePoint.x][tilePoint.y];

            var imgtile = new Image();
            $(imgtile).on('load', function () {
                var beginnPos = getImagePosition(imgtile, clickableObject.xBeginn, clickableObject.yBeginn, nexttile);
                var endPos = getImagePosition(imgtile, clickableObject.xEnd, clickableObject.yEnd, nexttile);
                var widthimg = endPos.x - beginnPos.x;
                var heightimg = endPos.y - beginnPos.y;

                console.log(beginnPos.x + " - " + beginnPos.y + " - " + widthimg + " - " + heightimg);

                weiteretiles.push(new tilesbefore(beginnPos.x, beginnPos.y, widthimg, heightimg, nexttile.url));
                coundDoneTileDepth++;

                openplace(beginnPos, widthimg, heightimg, weiteretiles);
            });
            imgtile.src = nexttile.url;
        }
    }
}

function getImagePosition(img, x, y, tiletouse) {
    var point = new Point(0, 0);
    var pixel = viewer.viewport.pixelFromPoint(new OpenSeadragon.Point(x, y));
    var faktorX = tiletouse.size.x / img.width;
    var xBeginn = pixel.x - tiletouse.position.x;
    xBeginn = xBeginn / faktorX;
    var faktorY = tiletouse.size.y / img.height;
    var yBeginn = pixel.y - tiletouse.position.y;
    yBeginn = yBeginn / faktorY;
    point.x = xBeginn;
    point.y = yBeginn;
    return point;
}
```

I get the Tiles before but when i zoom the image coordinates changes enourmus. For example when i max zoom the coordinates gets negative. How can i get the correct image coordinates for an Overlay in every Tile for that Overlay without Zoom-Factor ? So that i get every time the correct coordinates without manipulated by zoomfactor.

**Comment by aslan-itc** [comment]
Before it gets to complex i need the imagecoordinates of an overlay for any Tile normalized. So that the zoom level doesnt affects to this coordinates.

**Comment by iangilman** [comment]
So you want to know where the overlay overlaps each tile? In the tile's coordinate system? Or the image's coordinate system? I'm curious, what do you want to do with that information? In general, most things can be accomplished without thinking at the individual tile level. 

Anyway, getting the overlay location in image coordinates is the first step. Seems like you've got that working. Then you would go through all the tiles and figure out the relationship. You might start with looking at the tile's `bounds` property. I don't know off the top of my head what coordinate system that rectangle is in, but it shouldn't be too hard to figure out. 

Potentially useful resources:

https://openseadragon.github.io/examples/viewport-coordinates/

https://github.com/openseadragon/openseadragon/wiki/The-DZI-File-Format

**Comment by aslan-itc** [comment]
![image](https://user-images.githubusercontent.com/81740529/113474366-ed648280-946f-11eb-88cc-1367dc2da1dc.png)

Ok let me explain better. I have an overlay which is clickable that works fine. After a click i manipulate/edit exactly the image on the positions of that overlay with another image. For that i need the image coordinates of that overlay in every tile.

![image](https://user-images.githubusercontent.com/81740529/113474751-34ec0e00-9472-11eb-8d37-76f3ad5788f0.png)

The Problem is that i have to replace other tiles to. Otherwise the replaced image is only shown in the current zoomed tile. So i iterate over the tiles which are shown before and try to find the image coordinates of the overlay for every tile.

![image](https://user-images.githubusercontent.com/81740529/113474768-43d2c080-9472-11eb-87c0-5f88d51bdb00.png)

Try to figure out that if you zoom in to the picture there are possible overlays which are replaceable with any other image. But if you replace a part of an image for a overly it has do be done for every Tile before. Otherwise the replaced part is only visible if you zoom in.

I see the bounds and realize that they are normalized for every Tile but i cant figure out how i can get the image coordinates of an Overlay for any Tile with the Bounds information. I cant transform them to get valid coordinates.

**Comment by iangilman** [comment]
Thank you for the context! I suppose this is exactly what the TiledImage does as it draws (identifying which tiles are currently visible), but I don't think we really expose an easy API to access that information. You might take a look at the TiledImage drawing code for ideas. 

At any rate, each successive layer of the pyramid is twice as big (or twice as small, depending on which way you're going) as the last, so, given your example above, if you need to change tile 17,9 of level 13, when you go to level 12, you should divide by 2 (and floor), which gets you tile 8,4 of level 12. Then it's tile 4,2 of level 11, tile 2,1 of level 10, etc.
