### ISSUE TITLE
viewer.addTiledImage why not adding tileSources or tileSource 2 pages?

### ISSUE THREAD

**Issue by umitoguz** [openseadragon/openseadragon#1966]
```
for (var i = 0; i < len; ++i) {
                      
                            if (len > 1) {
                                switch (i) {
                                    case 0:
                                        tiff.setDirectory(i);
                                        var canvas1 = tiff.toCanvas();
                                        var im1 = tiff.toDataURL();
                                        break;


                                    case 1:
                                        tiff.setDirectory(i);
                                        var canvas2 = tiff.toCanvas();
                                        var im2 = tiff.toDataURL();                                     
                                        break;
                                    default:
                                        break;
                                }
                          
                             viewer.addTiledImage({

                                    tileSources: [
                                        {
                                            type: "image",
                                            url:im1
                                        },
                                        {
                                            type: "image",
                                            url: im2
                                        }


                                    ],

                                });                            
                            }
                            else {
                                tiff.setDirectory(i);
                                var canvas = tiff.toCanvas();
                                  viewer.addTiledImage({


                                    tileSource: {
                                        type: 'image',
                                        url: canvas.toDataURL(),
                                        buildPyramid: false
                                    },


                                });
                                

                         
                         

                            }
                        }
```

**Comment by iangilman** [comment]
@umitoguz I'm not sure what your question is. If you want to add multiple tiled images, you can certainly call `addTiledImage` as many times as you want. Also `viewer.open` can take an array, as can the `tileSources` property of the viewer creation config object.

**Comment by umitoguz** [comment]
i have 2 page(multi tiff) image.When i want to show them.I success only directly write `var viewer = OpenSeadragon({
                            id: "openseadragon1",
                            prefixUrl: "/Scripts/openseadragon/images/",
                            crossOriginPolicy: 'Anonymous',
                            sequenceMode: true,
                            ajaxWithCredentials: false,
                            //preload: true,
                            showNavigator: true,
                            showRotationControl: true,

                            tileSources: [
                                {
                                    type: "image",
                                    url: im1
                                },
                                {
                                    type: "image",
                                    url: im2
                                }
                            ],
                        });`
But I wrote this when I was code.Problem arising 2 or more openseadragon viewers occurs.

**Comment by msalsbery** [comment]
@umitoguz 

In the original code you posted you were calling the OpenSeadragon function in every iteration of the for loop. If you want one viewer then one should be constructed outside the loop then images added inside the loop.

is your code working now?

**Comment by umitoguz** [comment]
Viewer is out of the For loop.But i call url with GET  XMLHTTPREQUEST.Has the openseadragon  close or flush?

**Comment by umitoguz** [comment]
in the light of this event Am I use addTiledImage with multiple tilesources?

**Comment by umitoguz** [comment]
Am i open multiple tilesources? Look like that;

       viewer.open({
                                    tileSources: [
                                        {
                                            type: 'image',
                                            url:im1
                                          },
                                        {
                                            type: "image",
                                            url: im2
                                        }

                                    ],

                                });
i dont see any image in openseadragon

**Comment by iangilman** [comment]
This should work:

```
viewer.open([
  {
    type: "image",
    url:im1
  },
  {
    type: "image",
    url: im2
  }
]);
```

**Comment by umitoguz** [comment]
you are awesome.it worked thank you so much. I'm closing the issue.
