### ISSUE TITLE
Unable to open [object Object]: HTTP 404 attempting to load TileSource

### ISSUE THREAD

**Issue by Graynomad** [openseadragon/openseadragon#1967]
I see this has been reported before but although the issue was closed it was not resolved as far as I could tell.

```
<script type="text/javascript">
    var viewer = OpenSeadragon({
	type:       "zoomifytileservice",
        id: 		"openseadragon1",
        prefixUrl: "../js/openseadragon/images/",
	width:      7026,
        height:     9221,
        tileSources: "<see below>"
    });
</script>
```
I've tried the following

`tileSources: "../photos/_zoomables/21124/"`
403 error

`tileSources: "../photos/_zoomables/21124/ImageProperties.xml"`
404 error

`tileSources: "www.robgray.com/photos/_zoomables/21124/ImageProperties.xml"`
404 error

If I just type the fully-qualified URL into the browser I get this
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<IMAGE_PROPERTIES WIDTH="13037" HEIGHT="2926" NUMTILES="828" NUMIMAGES="1" VERSION="1.8" TILESIZE="256"/>
```
So the file exists and I assume it is in the correct format because I have many of these that used to work with Zoomify before I decided to swap over to Seadragon.

Rob

**Comment by iangilman** [comment]
I think you may need the `http://`, like so: 

`tileSources: "http://www.robgray.com/photos/_zoomables/21124/ImageProperties.xml"`

Assuming the HTML file is on www.robgray.com, this relative URL should also work: 

`tileSources: "/photos/_zoomables/21124/ImageProperties.xml"`

**Comment by Graynomad** [comment]
Neither option helps unfortunately

![9-04-2021 11-27-50 AM](https://user-images.githubusercontent.com/388406/114116736-87bd3e00-9928-11eb-849a-9e2d673fab8f.jpg)

Same result with both options.

Rob

**Comment by iangilman** [comment]
Oh! I finally paid closer attention to the file at http://www.robgray.com/photos/_zoomables/21124/ImageProperties.xml... it's not in the correct format. I assume it's supposed to be a DZI? This is what a DZI should look like:

```
<?xml version="1.0" encoding="UTF-8"?><Image TileSize="254" Overlap="1" Format="jpg" xmlns="http://schemas.microsoft.com/deepzoom/2008"><Size Width="1000" Height="1000"/></Image>
```

Where did you get that file?

**Comment by Graynomad** [comment]
A year or two back I had working Zoomify images on the site. All the tiles and this XML were produced by the Zoomify app at the time.

It seems though that DZI is the going thing these days so maybe I should swap over. I would hate to have to redo all the tiles though.

**Comment by msalsbery** [comment]
@Graynomad 

I haven't looked yet to see what's already there, but if necessary it should be relatively easy to make a tile source that'll work with your images without you having to change the images...

**Comment by Graynomad** [comment]
OK I seem to have it working, but only after much Googling.

I looked at the simple example on the SD web site but that points to a DZI file. I downloaded the DZI composer but there are so many options it's hard to figure out what to export. No option exports a DZI file.

Eventually I find a forum post where MS says "Oh didn't you know, the dzc_output.xml file is actually a dzi file. 

So I point to that and things seem to work with a new test image.

[http://www.robgray.com/test/test-seadragon.php](url)

Now what about reusing all my old tiles? The old folders don't have the SparseImageSceneGraph.xml and scene.xml files, so I deleted them from the new test folder and everything still works. Are they required?

Am I correct in saying that if I create modified versions of dzc_output.xml and modify the old Zoomify folder structure to match that produced by the DZI composer those tiles should work?

OR

I don't mind recreating things, should I export as a single file and forget the tiles?

Rob

**Comment by iangilman** [comment]
Oh, it's Zoomify! We support that format as well, but not in the way you were trying. Take a look at:

http://openseadragon.github.io/examples/tilesource-zoomify/

In your case it might be something like:

```
OpenSeadragon({
    ...
    tileSources: [{
        type:       "zoomifytileservice",
        width:      15870,
        height:     4829,
        tilesUrl:   "/photos/_zoomables/21124/"
    }]
    ...
});
```

I'm not sure if the tilesUrl is correct... you know your folder structure better than I. 

With an image that big, I think it is better to go with a tiled system... 15000 pixels is a bit much to load as a single image.

I would say give a try to getting it working with Zoomify (as above). If it doesn't work out and you do want to work with DZI, there are a number of options:

http://openseadragon.github.io/examples/creating-zooming-images/

...and yes, you don't need SparseImageSceneGraph.xml and scene.xml... DeepZoomTools has a bunch of features OSD doesn't use.

**Comment by Graynomad** [comment]
All working well now. I gave up on using the Zoomify tiles and swapped over to DZ. All good now.

What I would like to do now is launch an image into full screen mode by clicking on another image. Is there some example JS code and an API call to do this?

**Comment by iangilman** [comment]
You should be able to launch the viewer into fullscreen with `viewer.setFullScreen(true)`.

**Comment by Graynomad** [comment]
This doesn't work,

```
<script type="text/javascript">
    var viewer = OpenSeadragon({
        id: "openseadragon1",
        prefixUrl: "/js/openseadragon/images/",
        tileSources: "/photos/_zoomables/35012-test/dzc_output.xml"
    });
   viewer.setFullScreen(true);
</script>
```

which was a quicky to see if anything happened (nothing did).

But anyway I want to invoke the view from another image's onClick() function.

I've Goggled 'till I'm blue in the face and can't find an example of doing this.

**Comment by Graynomad** [comment]
Looks like you don't need an onClick() function, I have a working test file, here is the relevant code for future searches.

```<script src="../js/openseadragon/openseadragon.min.js"></script>

<div id="openseadragon1" style=" align: center; width: 1500px; height: 500px; border: 1px solid grey;"></div>

<div id="full-page" href="#full-page">
	<img border="1" border-color="#bbbbbb"  src="..\graphics\zoomable.gif">
</div>

<script type="text/javascript">
    var viewer = OpenSeadragon({
        id: "openseadragon1",
        prefixUrl: "/js/openseadragon/images/",
		fullPageButton: "full-page",
		showNavigator:  true,
        tileSources: "/photos/zoomables/35012/dzc_output.xml"
    });

</script>
```

**Comment by iangilman** [comment]
Right on. That definitely works. I think the reason the other one wasn't working is that the browser requires user interaction before going fullscreen. Calling the fullscreen function from within a click handler satisfies that requirement.
