### ISSUE TITLE
Getting the current level (zoom)

### ISSUE THREAD

**Issue by ibrrus** [openseadragon/openseadragon#1969]
Hello.
I am making an interactive map on which I plot several hundred points of interest and I want them to decrease as these points approach (depending on the level/zoom).

Now I am using the following code to get the level:
`viewer.world.getItemAt(0).lastDrawn[0].level`

Is there a function for better obtaining such a simple value?

**Comment by iangilman** [comment]
The current zoom is available from `viewer.viewport.getZoom()`.
