### ISSUE TITLE
Rotation: Performance improvements for rotation

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#197]
See comment at: https://github.com/openseadragon/openseadragon/blob/aefe7f361038369092a68565bbdbc18086a406e5/src/drawer.js#L1212

Also, at https://github.com/openseadragon/openseadragon/blob/aefe7f361038369092a68565bbdbc18086a406e5/src/drawer.js#L541 perhaps we can calculate that rectangle once per rotation and cache it?

Perhaps there are other things that can be done as well. Also it would be interesting to know the performance difference between rotated and not.

See #88 and #185 for more discussion on rotation.

**Comment by avandecreme** [comment]
The first 2 points have been fixed.

**Comment by iangilman** [comment]
Since the remainder is open ended, closing this.
