### ISSUE TITLE
Multitouch Zooming beyond image limits causes jitter

### ISSUE THREAD

**Issue by zng-jacky** [openseadragon/openseadragon#1978]
Attempting to zoom out/in beyond any limits using pinch-to-zoom gesture causes image to expand/contract beyond limit then snap back to limit. 
Using any type of mouse scroll on image enforces the limits just fine and does not cause any jitter, however, using any touch enabled device with pinch zoom gesture will cause the image to behave as described.

This behavior is present on all examples found on the github. I've tried disabling image constraints `visibilityRatio` , `constrainDuringPan`, and `minZoomLevel` but it doesn't seem to fix the issue.

Videos with the behavior - recorded using an iPad

https://youtu.be/QlLuD3eZA1A
https://youtu.be/yfnaIvzkV8c

**Comment by zng-jacky** [comment]
I solved this issue by adding a handler that checks to see if the user is zooming out and if the zoom level they are trying to zoom out to is beyond `minZoomLevel`

`
this.viewer.addHandler('canvas-pinch', (e) => {
      let zoom = this.viewer.viewport.getZoom(true);
      let distance = e.distance - e.lastDistance;
      if (zoom < osdOptions['minZoomLevel'] && distance < 0) {
        console.log('zooming out');
        this.viewer.gestureSettingsTouch.pinchToZoom = false;
      } else {
        this.viewer.gestureSettingsTouch.pinchToZoom = true;
      }
    });
`

A similar scenario could likely be written to handle pinch to zoom in.

**Comment by iangilman** [comment]
@zng-jacky glad you found a solution!

@msalsbery any thoughts from an event handling perspective?
