### ISSUE TITLE
Console errors galore when attempting HTML overlays with a 2nd DZI

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#1981]
I've utilized the OpenSeadragonHTMLelements plugin to display overlays on the canvas - and it works fine. 
I want to also have a 2nd dzi toggle option using a method shared here previously.

Both of these demos work, but the 2nd one with the toggle option is throwing errors by the thousands. 
I know what the error is saying, but cannot figure out where/how to appease viewer.js. Any help would be appreciated.
Thank you.

**Demo with one dzi:**   https://chattanoogahistory.com/htmloverlaytest.html
**Demo with two dzi's spewing errors:**   https://chattanoogahistory.com/htmloverlaytestTWO.html

It appears to work fine, but I'd rather suppress the errors or fix it.

_Errors example:_
viewport.js:1217 [Viewport.imageToViewportCoordinates] is not accurate with multi-image; use TiledImage.imageToViewportCoordinates instead.
viewport.js:1259 [Viewport.imageToViewportRectangle] is not accurate with multi-image; use TiledImage.imageToViewportRectangle instead.

**Comment by iangilman** [comment]
Looks like it's an issue with the plugin... we can discuss further in https://github.com/antonioxdias/OpenSeadragonHTMLelements/issues/12 (thank you for filing that).
