### ISSUE TITLE
Is it possible to apply a colormap to a dzi image in OpenSeadragon?

### ISSUE THREAD

**Issue by jmontoyam** [openseadragon/openseadragon#1982]
Hi, 

first of all, thank you very much for this amazing open source project!, great work guys!.
I am a beginner user, I just discovered OpenSeadragon very recently, but since then I have been eager to learn 
more and more about it, I have been going through all of the tutorials, examples and documentation available in the OSD website, they are very beginner friendly, they have helped me a lot! :-).

In my use case, I need to visualize a huge single channel data array. To do so, I have generated a grayscale dzi pyramid image 
(by replicating the same single channel as R, G and B). Thanks to the wonderful examples and documentation I have been able to
visualize such huge data array using the OSD viewer. As a second step, I would like to dynamically select a colormap from a dropdown and apply it to the dzi image currently showed in the viewer. I would also like to be able to change the dynamic range of the colormap (e.g., using sliders to modify the vmin and vmax of the colormap), and see "in real time" the effect of such changes in the colormap applied to the dzi image showed in the OSD viewer. Is it possible to accomplish this in OpenSeadragon?...I have not been able to find an example/tutorial similar to this particular use case.
Any help, suggestions and advices are truly welcome.

Thank you very much! ;)

**Comment by iangilman** [comment]
Fantastic! I'm glad you're enjoying OSD :) 

I think there are probably a few possible approaches, but I would recommend trying https://github.com/usnistgov/OpenSeadragonFiltering first. You'll have to write your own filter, I imagine, to get exactly the color map you want, but it gives instructions for how to do that. 

Another possibility would be https://github.com/thejohnhoffer/viaWebGL but only if you're comfortable with GLSL.

**Comment by jmontoyam** [comment]
Thank you very much @iangilman , I will give it a try to your suggestions! ;)…Once again thank you very much for maintaining this amazing project!...At the moment I am a beginner user, but I hope to become soon familiar enough with the codebase so that I can contribute to this wonderful open source project :-).
