### ISSUE TITLE
addSimpleImage JavaScript removes existing images first - is this as per design?

### ISSUE THREAD

**Issue by Garet-Jax** [openseadragon/openseadragon#1984]
From the name of the JavaScript method and the documentation, it seems like addSimpleImage is supposed to append new images in "sequenceMode" to the viewer.  Instead, it is removing all previous images and then opening the new one.  I have played around with "replace" and "index", but they don't seem to change the functionality.

I am opening the viewer using:

```
	window.onload = function() {
		viewer = OpenSeadragon({
			id: "openseadragon",
			prefixUrl: "images/",
			tileSources: [],
			sequenceMode: true,
			showReferenceStrip: true
		});
		  
		var anno = OpenSeadragon.Annotorious(viewer, {
			locale: 'auto', allowEmpty: true
		});
		
		var toolToggle = document.getElementById('current-tool');
		toolToggle.addEventListener('click', function() {
			if (toolToggle.innerHTML == 'TOOL: RECTANGLE') {
				toolToggle.innerHTML = 'TOOL: POLYGON';
				anno.setDrawingTool('polygon');
			} else {
				toolToggle.innerHTML = 'TOOL: RECTANGLE';
				anno.setDrawingTool('rect');
			}
		});
		
		var modeBtn = document.getElementById('mode');
		modeBtn.addEventListener('click', function() {             
			if (modeBtn.innerHTML == 'MODE: VIEW') {
				modeBtn.innerHTML = 'MODE: ANNOTATE';
				anno.setDrawingEnabled(true);
			} else {
				modeBtn.innerHTML = 'MODE: VIEW';
				anno.setDrawingEnabled(false);
			}
		});
		
		anno.on('createSelection', function(selection) {
			console.log('selection', selection);
		});
		
		anno.on('selectAnnotation', function(annotation) {
			console.log('selected', annotation);
		});
		
		anno.on('cancelSelected', function(a) {
			console.log('cancelSelected', a);
		});
		
		anno.on('mouseEnterAnnotation', function(annotation) {
			// console.log('mouseEnter', annotation);
		});
		
		anno.on('mouseLeaveAnnotation', function(annotation) {
			// console.log('mouseLeave', annotation);
		});
	}
```

Then at some later point, I call to add a new image:
```
	viewer.addSimpleImage({type: "image", url: filesToLoadAsArray[counter]}
```

The work around I am using right now is that I am sending all existing images plus the new one to the open method as an array.  This sort of works, but I am worried it is reloading all the previous images.  Is the addSimpleImage supposed to add a new image to the viewer removing all previous ones or is it supposed to just add the new image?

**Comment by iangilman** [comment]
Good point... I can see how that's a little confusing! There's no facility for modifying the sequence after you've opened it. If you want a different sequence entirely, you can call `viewer.open` with the new sequence, and it'll remove the old sequence and replace it with the new one.

In your case, I think just including all of the images you want on the initial open is fine... that's the way sequence mode is designed to work. Behind the scenes it's actually only opening one image at a time, so it's not inefficient.
