### ISSUE TITLE
Combining openstreetmap and dzi source 

### ISSUE THREAD

**Issue by dmandreev** [openseadragon/openseadragon#1987]
I'm new in openseadragon, and still learning, can someone help me to find proper way to achieve such goal: I need to display openstreetmap source and from certain zoom level for some coordinates also display dzi source from big image, like it "mapped" over openstreetmap (aerial photo). Thanks for tips!

**Comment by iangilman** [comment]
That's definitely supported... you'll want to learn about our multi-image feature: http://openseadragon.github.io/examples/multi-image/

Basically, when you create your viewer, you can do something like this for your `tileSources` option:

```
tileSources: [
  {
    tileSource: {
      type: 'openstreetmaps'
    }, 
    x: 0,
    y: 0,
    width: 1
  },
  {
    tileSource: '/path/to/my/image.dzi', 
    x: 0.25,
    y: 0.25,
    width: 0.5
  }
]
```

That'll create an OSM map that's one unit wide (the units are arbitrary, so you can go with 100 or 1000 or whatever you prefer), and on top of it a DZI that's half a unit wide and centered in the middle.

**Comment by dmandreev** [comment]
Thank you for answer!

**Comment by nadahmed** [comment]
Is there anyway I can add live locations markers here? Any help would be appreciated. Thanks!

**Comment by iangilman** [comment]
@nadahmed There are a number of ways to create overlays, either using the built-in overlays or any of a number of overlay plugins.
