### ISSUE TITLE
Pan to centre on click

### ISSUE THREAD

**Issue by jamtechdev** [openseadragon/openseadragon#1988]
I need to pan the clicked object to the center every time. It works when I set the ` _viewer.viewport.goHome(true);` before re pan / Zoom but when I remove it does not bring the object to the center of the screen. Please let me know where I'm wrong. Thanx

```
export function setTransformationLevel(scaleLevel, x, y) {
 _viewer.viewport.goHome(true);
    let point = snapDragon.getMousePosition({ pageX: x, pageY: y });
    let vp = _viewer.viewport.pointFromPixel(point, true);
    let vpX = vp.x;
    let vpY = vp.y;
    if (x <= 146 || x >= 1275 || y < 47 || y>624.9793700777778) {
      _viewer.viewport.zoomTo(scaleLevel, new snapDragon.Point(vpX, vpY), false);
      return true;
    }else{
    _viewer.viewport.panTo({ x:vpX, y:vpY}); 
    _viewer.viewport.zoomTo(scaleLevel,null, false);
    }
  return true;
}
```

**Comment by iangilman** [comment]
I'm not sure what's causing trouble in your scenario, since I don't know the details of your app. At any rate, I've confirmed that this code will pan the clicked point to the center of the viewer:

```
        viewer.addHandler('canvas-click', function(event) {
            if (event.quick) {
                const point = event.position;
                let vp = viewer.viewport.viewerElementToViewportCoordinates(point);
                viewer.viewport.panTo(vp);
            }
        })
```

Note that I've used `viewerElementToViewportCoordinates`, but if your coordinates are relative to the entire page (as your code implies) you should use `windowToViewportCoordinates`. 

Note also that the viewer by default wants to zoom in on whatever point you click, so you'll need to include this in your viewer options: 

```
            gestureSettingsMouse: {
                clickToZoom: false
            }
```

Also note that while `panTo` and `zoomTo` don't enforce viewport constraints (trying to keep the image in the viewport), any subsequent dragging will, which could cause some strange jumps. You could try disabling viewport constraints (with the `visibilityRatio: 0` option) to eliminate that from the equation, though you'll probably want them for the final app. One option is to call `viewer.viewport.applyConstraints()` after you do the zooming/panning, so it's consistent.

**Comment by jamtechdev** [comment]
@iangilman Sir I let you know the progress after implementing the same.
 Thank you sir for your reply :).

**Comment by jamtechdev** [comment]
@iangilman Sir I implement the same but things are not working as an aspect on my side. let me explain my project first. project is based on Leap Motion Device users can interact with a project through LMD there is no mouse interaction. 
I'm using SVG overlay on top of OSD container on top of SVG overlay. I plotted points like (c,c++,java,php) and cursor image (pointer).

When the user starts interaction with the leap device. I start moving the pointer image so its works like a mouse pointer. when the user hovers over any plotted point let assume (c++) so I'm collecting the (x,y) of point in this method setTransformationLevel(5, x, y) and start zoom/pan to center the point (c++) inside the container. this works cool when I select the point when the application is in its initial state means no any (Zoom/pan) it smoothly centers the selected point (c++) after that if I try to select some other closet point (java)  then the container is not panning it to the center it moves the way the screen.
I don't understand why things are not working in the second section.

This application has the same feature that I'm trying to achieve through OSD. they are using d3 scale / translate to bringing selected point to the center Sir please take a look: https://gmg-world-media.github.io/skymap-v1dev/

My OSD setup please take a look
```
 OpenSeadragon({
        id: "render",
        tileSources: "./images/kiss.js",
        prefixUrl: "./images/kiss_files",
        showNavigationControl: false,
        homeFillsViewer: true,
        visibilityRatio: 1,
        preserveOverlays: true,
        preserveViewport: true,
        preserveImageSizeOnResize: true,
        animationTime: 1.0,
        blendTime: 1,
        maxZoomLevel:25,
        minZoomLevel: 1,
        clickToZoom: false,
        defaultZoomLevel: 1,
        zoomPerScroll: 1.5,
    });
    
SVG Overlay resize function 
export function resize() {
  if (_containerWidth !== _viewer.container.clientWidth) {
    _containerWidth = _viewer.container.clientWidth
    _svg.setAttribute("width", _containerWidth)
  }
  if (_containerHeight !== _viewer.container.clientHeight) {
    _containerHeight = _viewer.container.clientHeight
    _svg.setAttribute("height", _containerHeight)
  }
  let p = _viewer.viewport.pixelFromPoint(new snapDragon.Point(0, 0), true)
  zoom = getZoom(true)
  scale = (1 * zoom)
  _node.setAttribute("transform",
    "translate(" + p.x + "," + p.y + ") scale(" + scale + ")")
}

// Simple Zoom function working well

export function setMotionZoomIn(scaleLevel, x, y) {
  let point = snapDragon.getMousePosition({ pageX: x, pageY: y });
  let vp = _viewer.viewport.pointFromPixel(point, true);
  let vpX = vp.x;
  let vpY = vp.y;
  _viewer.viewport.zoomTo(scaleLevel, new snapDragon.Point(vpX, vpY), false);
  return true;
}

// Simple Zoom Out working well

export function setMotionZoomOut(immediately) {
  _viewer.viewport.goHome(immediately);
  return true;
}
```

**Comment by iangilman** [comment]
Sounds like a great project! 

Are you expecting the `zoomTo` call to center you on a point? The point that's given to that call is not the point that ends up as the center... it's the point around which the zooming happens. You'll definitely want to include a `panTo` as well. Another option is to use `fitBounds`... that can be easier to work with. Just specify an appropriately-sized rectangle around your point of interest (in viewport coordinates).

**Comment by jamtechdev** [comment]
Sir, I just need to center the zoomed point in the viewport.I saw the _fitbound function code in API and found why my code working when I set goHome(true). but I think I'm not adult enough to completely understand this function right now :).
//from your api
  if (oldZoom === 0 || Math.abs(newZoom / oldZoom - 1) < 0.00000001) {
            this.zoomTo(newZoom, true);
            return this.panTo(center, immediately);
        }
        
        **Another option is to use fitBounds... which can be easier to work with. Just specify an appropriately-sized rectangle around your point of interest (in viewport coordinates)**        
            
Do I need to make rect on every object like this?
 var newBounds = new $.Rect(
            bounds.x,
            bounds.y,
            bounds.width,
            bounds.height,
            bounds.degrees + this.getRotation())
            .getBoundingBox();

I request you sir if you any minimal example that implements the same zoom/pan feature like this  https://gmg-world-media.github.io/skymap-v1dev/ app have please share or guide me.

**Comment by iangilman** [comment]
Sure, here's an example using fitBounds: 

https://codepen.io/iangilman/pen/poeqovO

**Comment by jamtechdev** [comment]
@iangilman Sir, Thank you for giving your time for making an example for me.
 I implement the solution, and it's working well on mouse click. but as I share previously application works with the Leap device and I don't have a mouse option. When I implement the same with leap device is not working as it works on canvas-click. 

When I perform click through Leap it's working well for the first time but after that, it moves the points outside of the screen. Is there is any way by which I pass the (x,y) collected through into the canvas-click function and fire that function programmatically without clicking the mouse?

I check the (x,y) values come through leap they are the same as canvas-click (event.position) value.

// Working well on mouse click
```
    _viewer.addHandler('canvas-click', function(event) {
      if (event.quick) {
        var point = event.position;
        var vp = _viewer.viewport.viewerElementToViewportCoordinates(point);
        var box = new snapDragon.Rect(vp.x - size / 2, vp.y - size / 2, size, size); 
        _viewer.viewport.fitBounds(box);
        _viewer.viewport.applyConstraints();
      }
   });

```   
//same code for Leap but not working it moves the object out of the screen on second click
export function setTransformationLevel(scaleLevel, x, y) {
     let point = snapDragon.getMousePosition({ pageX: x, pageY: y });
        var vp = _viewer.viewport.viewerElementToViewportCoordinates(point);
        var box = new snapDragon.Rect(vp.x - size / 2, vp.y - size / 2, size, size); 
        _viewer.viewport.fitBounds(box);
        _viewer.viewport.applyConstraints();
    return true;
 }

**Comment by jamtechdev** [comment]
[
![image](https://user-images.githubusercontent.com/30105044/122418929-32e11800-cfa8-11eb-83f0-35b6c621b8c9.png)
](url)

**Comment by iangilman** [comment]
Are you sure the values are the same? The `canvas-click` event's `position` is web coordinates relative to the viewer element. If your position is  web coordinates relative to the window (which is what's implied by your use of `pageX`), then you'll need to use `windowToViewportCoordinates` instead of `viewerElementToViewportCoordinates`. 

You shouldn't have to simulate a `canvas-click` event... you should be able to get it to work with your own event handler.

**Comment by jamtechdev** [comment]
Sir, I got why Leap is not working after the first leap click and things are working with a mouse click.

suppose I have objected on point (300,200) on the initial screen when I click through the leap it takes (300,200) as (pageX,pageY) same in case of canvas-click.

 >Second Click
Now the object is moved to the center and the new position of the object is (600,400) and all the objects new to this will change on the actual screen relative to this object like the object belong to point (310,190) will come to (610,390) when I click through mouse it takes the new value (610,390) and centers it accordaningly. but when I simulate click through leap device it takes the original (x,y) value that fed to object SVG (310,190) and center. that means centering is working fine but the coordinates make a problem.

**Comment by iangilman** [comment]
This is very strange. I don't know how much I can do to help without seeing it in action. Is it possible for you to share an example? I have a Leap Motion device, so I could test. 

One thought: how are you detecting the "click" from the Leap? Does it send its own click event already? I wonder if its click is fighting with the follow-up action you make. 

Have you tried removing the Leap from the equation and just programmatically performing the centering function, maybe on a timer? I still don't think you need to trigger a `canvas-click`... it must be a matter of getting the coordinates right.

**Comment by jamtechdev** [comment]
@iangilman Sir please clone this repo https://github.com/jamtechdev/map-testing.git for example.
> I'm using Leap v2 SDK on Linux.

> Actually sir there is no actual click event perform I'm just collecting the cursor (x,y) coordinates when I point my index finger with close pam and thumb on top of the object then I stop the cursor movement and pass the collected points to the setTransformationLevel function for further actions.
Inside the setTransformationLevel function, I write the code you provided me and pass the collected (x,y) into it.

```
export function setTransformationLevel(scaleLevel, x, y) {
     let point = snapDragon.getMousePosition({ pageX: x, pageY: y });
        var vp = _viewer.viewport.viewerElementToViewportCoordinates(point);
        var box = new snapDragon.Rect(vp.x - size / 2, vp.y - size / 2, size, size); 
        _viewer.viewport.fitBounds(box);
        _viewer.viewport.applyConstraints();
    return true;
 }
```
Yes, Sir, it's just a matter of coordinates OSD thinks the leaps points I'm passing are wrong and I am not able to get why because other things and Leap cursor visualization on-screen are working fine. I try to make changes In leap calculation but then the cursor starts making problems as it goes outside from the screen somewhere in the leap virtual interaction box area.

**Comment by jamtechdev** [comment]
>Have you tried removing the Leap from the equation and just programmatically performing the centering function, maybe on a timer?
Sir, I conduct the random screen coordinate test but it behaves the same as the leap cursor does.

   setInterval(()=>{
     var x = (Math.random() * ((osdWidth) - parseFloat(d3.select('#leapPointer').attr('width')))).toFixed();
     var y = (Math.random() * ((osdHeight) - parseFloat(d3.select('#leapPointer').attr('width')) )).toFixed();
     let point = [x,y]
     console.log(point)
    drawCursor(point)
    selectObject(point)
   },2500)

**Comment by jamtechdev** [comment]
Sir I'm testing it and found that after 
canvas scale the leap pointer values are going totally different when we compare them with mouse pointer values. I think that's why the centre will work when I performed first zoom.

**Comment by iangilman** [comment]
Thank you for sharing the project! That helps a lot. You have quite a number of coordinate systems going on in there... OSD already has web coordinates versus viewport coordinates versus image coordinates, but your project also has the SVG overlay, which looks like it is more or less in viewport coordinates but possibly not exactly, and you also have the Leap coordinate system! No wonder things are getting confused :)

So, in your `selectObject` function in `leap-manager.js`, you are getting the Leap coordinates and converting them to your SVG overlay coordinates, and then calling `hoveredObjectClick` with them, which eventually goes to OpenSeadragon via `setTransformationLevel` where you first convert it to viewport coordinates via `windowToViewportCoordinates`. This creates a problem because `windowToViewportCoordinates` is expecting web coordinates but you're giving it the SVG overlay coordinates. The SVG overlay coordinates change as you zoom in and out, whereas web coordinates do not... this is why things act different after the first zoom, as you pointed out. 

There are a number of ways you could sort this out, but I think the easiest is to convert straight from Leap coordinates to web coordinates in `selectObject`'s `hoveredObjectClick` call, thereby skipping the unnecessary trip into the SVG overlay coordinates. Here is the relevant line:

```
hoveredObjectClick(hoveredObject,points[0] * window.innerWidth,(1 - points[1]) * window.innerHeight);
```

I had a good time playing around with the project... I hadn't thought to mix Leap with OSD before!

**Comment by jamtechdev** [comment]
@iangilman Sir Thank you for giving you time. I implement the same and let you know about the things going on after this.

**Comment by jamtechdev** [comment]
@iangilman Sir Thank you for giving you time. I implement the same and let you know about the things going on after this.

**Comment by jamtechdev** [comment]
@iangilman Sir, Thank you so much. Things are working as expected now. It would never have happened without your guidance.
