### ISSUE TITLE
Prevent over pan

### ISSUE THREAD

**Issue by iantearle** [openseadragon/openseadragon#1993]
Been scouring the api docs, but cant see an option for this, so hope its possible.

Am I able to prevent the over panning beyond the size of the image, basically I want to stop the white background when you pan to the extremes of the image, rather than the edges able to pan to the middle they would stop on the edge of the viewer.

**Comment by INPUTsys-Chris** [comment]
You are looking for this option: 
constrainDuringPan: true

See https://openseadragon.github.io/examples/ui-zoom-and-pan/

**Comment by iantearle** [comment]
Brilliant. 

Thank you. 

Exact options required for the effect I needed were:

```
    constrainDuringPan: true,
    visibilityRatio: 1,
    minZoomLevel: 1,
```
