### ISSUE TITLE
List of composite ops "valid values" is missing one

### ISSUE THREAD

**Issue by tdiprima** [openseadragon/openseadragon#1994]
Hey there, 

I'm looking at openseadragon.js, lines [196-199](/openseadragon/openseadragon/blob/master/src/openseadragon.js#L196-L199), and it lists 11 valid values for setCompositeOperation.  It's missing one, mentioned in issue #1653 : `difference`.

Aside from adding `difference` to the list of valid values... might there be any other values that aren't listed?  Or does it do all of them (all of the usual ones; composite by color and composite by shape)?

Thanks!
Tammy

**Comment by iangilman** [comment]
Good catch! I believe we just pass the value into the canvas context's `globalCompositeOperation`, so any value the browser accepts for that API should be fine. It's probably worth mentioning that explicitly in the comment there. We could potentially update the comment to include all the values listed in https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation, though it's quite a few!

**Comment by tdiprima** [comment]
Thanks @iangilman!
I was trying to follow along in the code to see if I could determine what was actually handling that, but I didn't see it.  Thank you for clarifying. 
Would it be acceptable to say: "For the complete list of operations, see: [CanvasRenderingContext2D.globalCompositeOperation](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation)"?

**Comment by iangilman** [comment]
Yeah, that seems like a good solution :)
