### ISSUE TITLE
feat: track the original target in canvas-click

### ISSUE THREAD

**Issue by ronnymikalsen** [openseadragon/openseadragon#1997]
We were not able to use the old mousetracker in v2, so we have added custom click handling in our component. One thing that has changed in v3 is event.originalEvent.target on overlays. In v2 when we listen to canvas-click events then the target event is the element that we clicked on, but in v3 the target event is always the openseadragon canvas. We need to know which element is clicked on.

I commented this on issue https://github.com/openseadragon/openseadragon/issues/1985#issuecomment-863910473 and @msalsbery  has proposed a solution in https://github.com/openseadragon/openseadragon/issues/1985#issuecomment-866243342

**Comment by iangilman** [comment]
@msalsbery are you going to be able to get this in for the 3.0.0 release?

**Comment by iangilman** [comment]
It looks like @msalsbery hasn't been able to get to it, so someone else is going to need to look at it. If there are no volunteers, I'll try to take a look when I get a chance.

**Comment by iangilman** [comment]
Okay, I'm taking a look at this. @ronnymikalsen can you help me understand this scenario better? I'm giving it a try like so:

```
var viewer = OpenSeadragon({
    // ...
    overlays: [{
        id: 'example-overlay',
        x: 0.33,
        y: 0.75,
        width: 0.2,
        height: 0.25,
        className: 'highlight'
    }]
});

viewer.addHandler('canvas-click', function(event) {
});
```

...and I click on the overlay. I'm running it with a customized version of OpenSeadragon that logs the `target` of the original `pointerdown` event, and it's the canvas even there. Is that the sort of thing that you were doing, or are you setting up your overlays or event handlers differently somehow?

**Comment by ronnymikalsen** [comment]
Yes, that is how I do it. I have created a stackblitz where I show the difference between v2 and v3 (https://stackblitz.com/edit/web-platform-zcibru?file=index.html and https://stackblitz.com/edit/web-platform-zcibru?file=openseadragon-3.html)

@iangilman

**Comment by iangilman** [comment]
@ronnymikalsen great, thank you! I've modified my test code to use your overlay creation, but I'm getting the same results. I've made a draft with my attempted fix, in the hopes that you or @msalsbery have some insight.

**Comment by msalsbery** [comment]
@iangilman @ronnymikalsen Try setting pointer-events:auto on the target (overlay) div element's style

I haven't looked close yet at the code fix but first glance looked good...hopefully it's just a CSS thing here :)

**Comment by iangilman** [comment]
@msalsbery that fixes it (together with my #2037)! I was confused at first about why, but now I see that all of the overlays are added to a div that has `pointer-events: none` on it. It looks like that's a change from OSD 2.4.2, and it seems problematic... not only does it interfere with this sort of click handling, but it also causes problems with hover CSS. 

Looks like you added that change here: 

https://github.com/openseadragon/openseadragon/commit/e74d83f1045e18df80c0d07a82a481fdd18f9ae9

Do you remember why? Is there some other way we can accomplish the same thing? 

Note that we're also setting the touch actions off; I imagine that will cause similar problems.

**Comment by msalsbery** [comment]
@iangilman Ugh, sorry about that! 

The reason is to ensure, if possible, that elements with MouseTrackers attached (specifically the viewer "canvas" element) are the top-level target because pointer capture is handled implicitly by the user agent for touch events which makes tracking for drag gestures problematic when a child element has the implicit capture. 

I did, however, spend a lot of time on a solution for that issue. So hopefully I added the code that sets pointer-events and touch-actions before I did the implicit capture issue code, and just should have removed that code. 

I'll need to do some full testing to make sure, which I will do right away!

**Comment by iangilman** [comment]
@msalsbery sounds good... feel free to update #2037 with what you find!

**Comment by msalsbery** [comment]
@iangilman I've fixed the issue with pointer-events:none inheriting from the overlay DIV element...see #2042

**Comment by iangilman** [comment]
@ronnymikalsen okay, #2037 is merged. Can you give it a try and verify that it gives you what you need?

**Comment by ronnymikalsen** [comment]
@iangilman @msalsbery It works perfectly for me, thanks a lot!

**Comment by iangilman** [comment]
Awesome... thank you for testing it!
