### ISSUE TITLE
Tiles appear off by 1px

### ISSUE THREAD

**Issue by iantearle** [openseadragon/openseadragon#2004]
![Screenshot 2021-07-05 at 17 37 51](https://user-images.githubusercontent.com/201174/124500494-c9d70e00-ddb7-11eb-85a2-7f3af07736e2.png)

Have an interesting fault which really only appears visible on the portion of the image where I have diagonal lines in the detail. Is this anything to do with OSD or is happening in the image generation - using magick-slicer.sh

**Comment by iantearle** [comment]
This isn't just down to our image either. I can see the same tiles offset on Open Sea Dragons own image preview: 

![Screenshot 2021-07-06 at 13 55 04](https://user-images.githubusercontent.com/201174/124603552-f182b080-de61-11eb-88f5-f4354146496d.png)

You can clearly see the tiles are not aligned correctly. Is this something that can be fixed?

**Comment by iangilman** [comment]
Yes, it certainly does seem to be off! I have confirmed with the "duomo" image using both OSD 2.4.2 and the latest master. I don't know if it's always been like this or was somehow introduced by 2.4.2. 

I suppose the way to debug it would be to make sure to generate a clean tile set (perhaps with no overlap for starters) and then dig through the TiledImage drawing code. 

Thank you for filing this issue! Hopefully someone will find it worth looking at. If you want to get involved in debugging it, I'm happy to help answer questions.

**Comment by iantearle** [comment]
Have finally figured this out. We were creating tiles with Magick-Slicer (https://github.com/VoidVolker/MagickSlicer) as I think the "duomo" image was done. 
Magick-Slicer doesn't properly support Overlap pixels - we rebuilt our tiles with libvips https://github.com/libvips/libvips (which incidentally is 100x faster) and added the 1px Overlap and everything lines up perfectly. 

So not an issue with OSD per se, unless Overlap is set by default, I couldn't see a way of explicitly turning it off?

```php
$ vips dzsave image.jpg tiles --suffix .jpg[Q=95]
```

**Comment by iangilman** [comment]
Interesting! I'm glad you were able to track it down.

OpenSeadragon should base its overlap entirely on the information it gets from the DZI file; there is no override beyond that.
