### ISSUE TITLE
Having difficulties retrieving the current display image dimensions 

### ISSUE THREAD

**Issue by hjb1694** [openseadragon/openseadragon#2006]
I am attempting to set width and height dimensions for an overlay to match the current width and height of the image at all times, but I am struggling to obtain the current displayed image dimensions. How do I retrieve those values?

EDIT: I am also needing the zoom factor in relation to the original image size.

**Comment by iangilman** [comment]
What kind of overlay is this? Many overlays work in viewport coordinates, which are unaffected by zoom/pan. For instance, the default viewport coordinates go from 0 on the left to 1 on the right. Some overlays work in image coordinates, which are also unaffected by zoom/pan. 

At any rate, `viewer.viewport` has a number of coordinate system conversion functions: 

http://openseadragon.github.io/docs/OpenSeadragon.Viewport.html

**Comment by hjb1694** [comment]
@iangilman 
I am using a KonvaJS overlay to create lines and drag them. This is for a card grading app.

**Comment by iangilman** [comment]
I see, so it's custom overlay code and you're having to line things up manually. We have a number of overlay plug-ins, but not one for Konva. You might look at the code for this canvas overlay plug-in and base your solution off of their math:

https://github.com/altert/OpenSeadragonCanvasOverlay

They are using image coordinates, I believe.

Here's another overlay plug-in (SVG) that has slightly simpler math, and is based on viewport coordinates:

https://github.com/openseadragon/svg-overlay/

Between those two, it should give you a pretty good idea how to approach the problem.
