### ISSUE TITLE
Need a 'loader' display method

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#2010]
I'm building a page that presents several pages of newspaper clippings in collection mode. 
The load time is slower than I'd prefer under less than ideal connectivity. 

I'd like to present a 'loading' gif while the tiles populate. I'm a 'noob' when it comes to JavaScript, so will need specifics on where/how to place the code. 

An example of one page of clippings is here:  https://chattanoogahistory.com/marr-field.php

The method I'm using it to define links to dzi's in the collection, then load the tilesources onClick of the variable.
The abbreviated code is below.

Suggestion needed on what and where to place the loader.
Thank you.

```
      var cha194901 ="https://dzchattzoom.s3.amazonaws.com/LOVELL/1949-CHAnews_Page_01.dzi";
      var cha194902 ="https://dzchattzoom.s3.amazonaws.com/LOVELL/1949-CHAnews_Page_02.dzi";
      var cha194903 ="https://dzchattzoom.s3.amazonaws.com/LOVELL/1949-CHAnews_Page_03.dzi";


 $('.pg1949').click(function() {
        viewer.open([
          {
            tileSource: cha194901}
          ,
          {
            tileSource: cha194902}
          ,
          {
            tileSource: cha194903}
          ,    
```

**Comment by iangilman** [comment]
Cool! Nice feature :)

To add a loading indicator you'll need two things: to know when it's done loading, and to actually display the indicator somehow. Displaying the indicator is entirely up to you... it doesn't need to interact with OSD at all. Knowing when it's done loading can be accomplished with the code suggestions in this issue: https://github.com/openseadragon/openseadragon/issues/1257

**Comment by SamHall** [comment]
Thank you - I would love to see a working example.
I played around with that code, but wasn't sure if it was 'seeing' the tile completion or not.
Please forgive my lack of script savviness : /

**Comment by iangilman** [comment]
Sure, here's an example: https://codepen.io/iangilman/pen/jOmLYvd

**Comment by SamHall** [comment]
> Sure, here's an example: https://codepen.io/iangilman/pen/jOmLYvd

Ah - thank you.
However, I couldn't get it to work in collection mode (.loading remains displayed). 
Getting closer!

**Comment by iangilman** [comment]
Hmm, strange! When I add `collectionMode: true,` to the CodePen, it works fine for me. 

My suggestion would be to add some console.logs to the detection code to see when it's happening, to see if there is any unexpected behavior.

**Comment by SamHall** [comment]
Solved one issue, but still haven't quite gotten to the result.
I was using v. 2.2.0 instead of current.  It works, and in collection mode.
However, I cannot get it work when presenting the openseadragon canvas in a modal (Bootstrap 4).
The .loading class is continuously set to _display: none._
I'll continue to dig.

**Comment by iangilman** [comment]
Oh yeah, good to have the latest version for this :) 

Have you done any console logging? Would be interesting to know when the loading class gets hidden.

**Comment by SamHall** [comment]
After digging into console I think I know what the issue is.
It's not a modal thing - but instead, something I didn't make clear. 
Within the modal, I have sets of DZIs that are selectable by buttons. 
If I interpret the comments in the solution correctly, that loader class is set to display: none only once.  
I tried a toggle class, but got inconsistent results.  Perhaps the 'isFullyLoaded' test needs to reset at each TileSource load(?)

![example](https://user-images.githubusercontent.com/4950023/126729558-e5ffa821-8142-45b8-8f85-f10d9d2eddc1.JPG)

**Comment by iangilman** [comment]
Oh, I see! Yes, you'll want to re-show the loader every time you switch tile sources. Based on the code in my example above, that would be as simple as calling this:

```
    document.querySelector('.loading').style.display = 'block';
```

...once every time you load a new set. The rest of the logic should work fine.

**Comment by SamHall** [comment]
EUREKA! 
That works. Thank you.

**Comment by iangilman** [comment]
Awesome :)
