### ISSUE TITLE
How to allow 'homeFillsViewer' option to show the top part of the image?

### ISSUE THREAD

**Issue by YashAgrawal9265** [openseadragon/openseadragon#2011]
When I am using the homeFillsViewer option. It is showing the image from the center part.
![Screenshot (161)](https://user-images.githubusercontent.com/69956695/126076038-d25e0900-e051-44d6-8e4f-91b665fac5e8.png)

I want that is should show the top part of the image like this:
![Screenshot (163)](https://user-images.githubusercontent.com/69956695/126076109-c7ab52ce-58ab-4a94-8ecc-f38b57cb51d4.png)

Can anyone tell me how can I achieve that?
This is my code:

> this.viewer = new OpenSeadragon( {
> 		element: this.$openseadragonDiv[ 0 ],
> 		zoomInButton: 'openseadragon-zoomIn',
> 		zoomOutButton: 'openseadragon-zoomOut',
> 		homeButton: 'openseadragon-home',
> 		showNavigator: true,
> 		showFullPageControl: false,
> 		navigatorHeight: '140px',
> 		navigatorWidth: '80px',
> 		useCanvas: false,
> 		visibilityRatio: 1,
> 		homeFillsViewer: true,
> 		tileSources: {
> 			type: 'legacy-image-pyramid',
> 			levels: [ {
> 				url: url,
> 				height: 889,
> 				width: 600
> 			},
> 			{
> 				url: url2,
> 				height: 2201,
> 				width: 1485
> 			},
> 			{
> 				url: url3,
> 				height: 4402,
> 				width: 2970
> 			}
> 			]
> 		}
> 		
> 	} );

**Comment by iangilman** [comment]
Unfortunately we don't have a good mechanism for customizing the home location. My suggestion is we should reinstate `setHomeBounds` (issue https://github.com/openseadragon/openseadragon/issues/1090). There's also some discussion on workarounds in https://github.com/openseadragon/openseadragon/issues/643.
