### ISSUE TITLE
how to take osd canvas image as background of a div tag to implement magnifier

### ISSUE THREAD

**Issue by sinamcr7** [openseadragon/openseadragon#2013]
Hi there
I'm using osd to implement an app for medical images and I need to implement a magnifier for it that shows magnifier next to mouse pointer for example it just shows on right-click hold and drag but anything I tried it didn't work so I decided to just show and hide it on right mouse click event
next I need to draw canvas image inside this magnifier but any code I tried it didn't show anything, what should I do? please help me if you have any idea about what it can be done

**Comment by iangilman** [comment]
So you have an image in an OSD viewer and you want to show a zoomed-in version of that same image? It seems to me you could do that with a second viewer by keeping them synchronized but with one more zoomed in. I don't know of an example of that exactly, but here is two viewers synchronized: 

https://codepen.io/iangilman/pen/BpwBJe

**Comment by sinamcr7** [comment]
yes exactly, there is and osd magnifier plugin but it just zooms when i move mouse on it and scroll but i want it be like an magnifier sticked on mouse pointer and when i press and hold right mouse button it shows and hides when i release right mouse button

**Comment by iangilman** [comment]
Cool. My recommendation is to make a second viewer and synchronize it like the example above (but just with a higher zoom value).

**Comment by sinamcr7** [comment]
thanks, is it possible that I can stick the magnifier on the mouse? like when I drag the right mouse button magnifier shows and hide when I release the right mouse button

**Comment by iangilman** [comment]
Sure... you could move the viewer around to match the mouse position... style its containing div (the one you give it when you create the viewer) with `position: absolute` and make its `left` and `top` follow the mouse cursor. Don't forget to give it a `width` and `height`! If you want it centered on the cursor (rather than hanging off the upper left corner) you can use `transform: translate(-50%, -50%)`. I imagine you should also give it `pointer-events: none` so it doesn't interfere with the other viewer's mouse events.

**Comment by sinamcr7** [comment]
thanks, I tried to sync their zoom levels but it didn't work, do you have any examples on syncing magnifier viewer with the main viewer? I need like 3x zoom in magnifier but with that example, it doesn't zoom correctly

**Comment by iangilman** [comment]
To get a 3x zoom, you would modify https://codepen.io/iangilman/pen/BpwBJe like so:

```
var magFactor = 3;

var viewer1Handler = function() {
  if (viewer2Leading) {
    return;
  }

  viewer1Leading = true;
  viewer2.viewport.zoomTo(viewer1.viewport.getZoom() * magFactor);
  viewer2.viewport.panTo(viewer1.viewport.getCenter());
  viewer1Leading = false;
};

var viewer2Handler = function() {
  if (viewer1Leading) {
    return;
  }

  viewer2Leading = true;
  viewer1.viewport.zoomTo(viewer2.viewport.getZoom() / magFactor);
  viewer1.viewport.panTo(viewer2.viewport.getCenter());
  viewer2Leading = false;
};
```

Only the lines with `magFactor` have been changed. 

As for following the mouse, you'll need to use OSD's MouseTracker, like so: 

```
const tracker = new OpenSeadragon.MouseTracker({
  element: viewer.container,
  moveHandler: event => {
    // event.position is in web coordinates relative to the viewer container; you can use this vector 
    // to position the magnifier where the mouse is 
  }
});
```

You can just use regular CSS with `position: absolute` to position the magnifier like I mentioned above. 

BTW, have you taken a look at this plugin? https://github.com/picturae/OpenSeadragonMagnifier Perhaps it has some useful code ideas at least?

**Comment by sinamcr7** [comment]
thank you, how can I update the magnifier viewer with mouse movement? it is well with pan and zoom but when I move the mouse it doesn't change the magnifier viewer to mouse location and shows just the last position that I panned or zoomed but not updating with mouse free move without pan and zoom, is it possible to set magnifier to just show when right mouse button drag?

**Comment by iangilman** [comment]
You can base the pan of viewer2 off of the position of the mouse in viewer1 like so:

```
const tracker = new OpenSeadragon.MouseTracker({
  element: viewer1.container,
  moveHandler: event => {
    const viewportPos = viewer1.viewport.viewerElementToViewportCoordinates(event.position);
    viewer2.viewport.panTo(viewportPos, true);
  }
});
```

This will only work if you disable the pan synchronization from the CodePen example.

**Comment by sinamcr7** [comment]
thank you it saved me. but for zoom level, it seems that little numbers like 2 or 3 it doesn't zoom and the image is smaller than the original image, has it any calculations for zoom?

**Comment by sinamcr7** [comment]
thank you it saved me. but for zoom level, it seems that small numbers like 2 or 3 it doesn't zoom and the image is smaller than the original image, has it any calculations for zoom?

**Comment by iangilman** [comment]
Zoom is a multiplier, so 2 means "double size". Depending on how you have things set up, your default zoom should be around 1. Perhaps it would be helpful for you to use `console.log` to see what your zoom values are?

**Comment by sinamcr7** [comment]
thank you
is there any tool for creating a ruler for measuring lengths and calculating area and perimeter of shapes?

**Comment by iangilman** [comment]
I don't think there is a plugin that is quite what you're looking for, but you might take a look at the code for https://github.com/usnistgov/OpenSeadragonScalebar to see if it gets you started in the right direction.

**Comment by sinamcr7** [comment]
thank you I'm going to use it but is there any tool that can draw a line on the viewer like a ruler and show distance on it?
I want to make a distance measurement tool for medical images and it should get 2 points by clicking on the image and using their coordinates to measure the distance or length of the line, you know any tool for it? or have any idea how it should be?

**Comment by iangilman** [comment]
I don't think anyone has made a ruler plugin. You'll want some sort of overlay to be able to draw the line. There are a number of options here: 

http://openseadragon.github.io/#plugins

The SVG overlay (https://github.com/openseadragon/svg-overlay) is a pretty basic option, as long as you're comfortable with SVG. You might also consider the Fabric or Paper overlays. 

Once you have the length from the line, you should be able to come up with the distance in the proper units in a similar way to how the scale bar does it.
