### ISSUE TITLE
Deep Zoom Image view keeping image tiles on google drive.

### ISSUE THREAD

**Issue by CopotronicRifat** [openseadragon/openseadragon#2015]
As my dzi_files are kept in google drive (public folder), is it possible to show the deep zoom image with the following code like this--

https://stackoverflow.com/questions/16451256/how-do-i-get-started-using-openseadragon/16452141#16452141

It worked for GitHub repository, but as my tilesource folder crossed 1GB quota, I had to keep my files in google drive.

I tried [this](https://codepen.io/iangilman/pen/gpejpJ) option too, but it seems like the webpage cannot fetch the google drive link.

My google drive link where the files are kept - https://drive.google.com/drive/folders/13zgWeO88OJWumktB42URK_UOwIgeilgV?usp=sharing

**Comment by CopotronicRifat** [comment]
The html code that I am trying-

`<html>
  <head>
  
    
  </head>
  <body>
  <style type="text/css">
      #mesh {
        width: 1000px;
        height: 1000px;
      }
    </style>
    <div id="mesh"></div>
    <script src="openseadragon/openseadragon.min.js"></script>
    <script>
      
		var dziFilesUrl = 'https://drive.google.com/drive/folders/13zgWeO88OJWumktB42URK_UOwIgeilgV?usp=sharing';
		var dziData = '<?xml version="1.0" encoding="utf-8"?><Image TileSize="1024" Overlap="1" Format="png" xmlns="http://schemas.microsoft.com/deepzoom/2008"><Size Width="600000" Height="600000"/></Image>';
		var tileSourceFromData = function(data, filesUrl) {
		var $xml = $($.parseXML(data));
		var $image = $xml.find('Image');
		var $size = $xml.find('Size');

		var dzi = {
			Image: {
					xmlns: $image.attr('xmlns'),
					Url: filesUrl,
					Format: $image.attr('Format'),
					Overlap: $image.attr('Overlap'),
					TileSize: $image.attr('TileSize'),
					Size: {
						Height: $size.attr('Height'),
						Width: $size.attr('Width')
							}
					}
				};  
  
				console.log(dzi);
				return dzi;
				};

// This creates the actual viewer. 
	var viewer = OpenSeadragon({
  id: 'mesh',
  prefixUrl: 'openseadragon/images/',
  tileSources: tileSourceFromData(dziData, dziFilesUrl)
});
    </script>
  </body>
</html>`

**Comment by iangilman** [comment]
I don't know enough about Google Drive to know if there's a way to get a "raw" file URL from it. A link like https://drive.google.com/drive/folders/13zgWeO88OJWumktB42URK_UOwIgeilgV?usp=sharing just gives you a page that is user-facing, but won't serve the files like they are needed for code. Perhaps there's some way to ask Google Drive to serve the files like a regular web server? If not, maybe it's possible with Dropbox or box.com or something? 

I know it's definitely possible with Amazon s3, and there are lots of other web hosting options that would allow it as well.

**Comment by CopotronicRifat** [comment]
I found a solution using google drive as web server using [Drive to Web](https://drv.tw/). 
Just need to organize the files in a public folder in google drive like [this](https://stackoverflow.com/questions/16451256/how-do-i-get-started-using-openseadragon/16452141#16452141), courtesy to @iangilman, and it is ready to go.

**Comment by iangilman** [comment]
Lovely! Good to know that service exists :)
