### ISSUE TITLE
Adding Featherlight for Popups. Show modal on click - works only on PC, not Android's Chrome. Why?

### ISSUE THREAD

**Issue by Karoleekk** [openseadragon/openseadragon#2016]
Hello.
Like I said in tittle - showing modals works only on PC web browsers (tested IE, Opera, Chrome).
When I single tap on OpenSeaDragon image in Android's Chrome - modals show and immediately closes.
It looks like OpenSeaDragon think, that my single tap is doubble click? Like first click to open modal, and next - to close.

I've used "canvas-click" and with allert everythings is allright. But with Featherlight something is not good. Maybe I must use other method to open modal?

I'm fighting with this error about one week... and now - with tears in eyes - im begging for help there.

URLs:
My SeaDragon with Featherlight: http://karoleekk.cfolks.pl/final/index2.html
Featherlight: https://noelboss.github.io/featherlight/

Wishes, and thanks for help.

**Comment by iangilman** [comment]
Just for the sake of crosslinking, I'm noting that this question is asked as well here: https://stackoverflow.com/questions/68723887/openseadragon-with-featherlight-on-mobile-chrome-on-android-modal-window-imme

As I mentioned there, I can't think of anything in OSD that would cause this issue. Have you tried with just Featherlight in Android Chrome? 

One thing to try would be to add a `setTimeout` in the click handler before you open the Featherlight... maybe by changing the timing you'll get past the "click" that dismisses the modal.
