### ISSUE TITLE
DZI loads one tile only in ASP.NET Core

### ISSUE THREAD

**Issue by peaeater** [openseadragon/openseadragon#2023]
I'm having a problem loading dzi tiles in a very basic setup in ASP.NET Core 3.1. I have used the same setup previously in ASP.NET websites running on IIS, where the same dzi tiles work just fine. 

```html
<body style="width: 100%; height: 100%;">
  <div id="seadragon1" role="application" aria-label="seadragon viewer" style="width:100%; height: 100%">
  </div>
  <script src="~/js/openseadragon-2.4.2.js"></script>
  <script>
    var seadragon = OpenSeadragon({
      id: 'seadragon1',
      prefixUrl: '/img/',
      tileSources: '/media/sample.dzi'
    });
  </script>
</body>
```

The .dzi file is passed to the OpenSeadragon object as a relative url, and is fetched successfully. All the nav images are fetched successfully. However, only a single tile is ever fetched: `/media/sample/sample_files/0/0_0.jpg`. No errors appear in the console. The canvas gets all set up okay, it's just completely empty. There's no indication as to why no further tiles are fetched - there is just no attempt to fetch them. If I manually attempt to reach any of the tiles in the browser (e.g. `/media/sample/sample_files/10/0_0.jpg`) they are available and load okay. I.e. the tile images are there and can be served.

When I pass the same dzi file and tiles to the same setup in an ASP.NET website running on IIS, everything works fine. The html and javascript in both scenarios are literally the same. The fundamental difference between the two scenarios is that asp.net core is running on the built-in Kestrel server, not IIS. I am flummoxed as to why that would make any difference to OpenSeadragon's behaviour. 

Any explanation or educated guess would be helpful. Even which line/s to pay attention to in openseadragon's source code.

**Comment by peaeater** [comment]
To be thorough, I published the asp.net core site to an IIS server. Technically, IIS proxies to Kestrel on the server but that's as much as I can close the gap between an asp.net core website and an older style asp.net website based on the .net framework.

And... same problem. Here is the published site for reference: [https://andi2.andornot.com/seadragon?dzi=/media/seadragon/sample.dzi](https://andi2.andornot.com/seadragon?dzi=/media/seadragon/sample.dzi).

**Comment by iangilman** [comment]
This is a common gotcha! If the OSD container (in your case `#seadragon1`) doesn't have any height, there won't be any content. Unfortunately giving the body and container `height: 100%` isn't enough. You can fix it by also giving the `html` tag `height: 100%` or you can change the body and/or container to having `height: 100vh`. Hopefully that gets things working!

**Comment by peaeater** [comment]
Oh my goodness. It was the height. Setting it to 100vh does the trick. THANK YOU!!
