### ISSUE TITLE
Unable to open [object Object]: unable to load TileSource using DZI format

### ISSUE THREAD

**Issue by bruno-31** [openseadragon/openseadragon#2025]
I'm trying to get started with openseadragon but I still don't manage to make it work on a simple example using DZI. I always get the "unable to load TileSource error" even tough the file destination seems to be correct.

I generated the tiles using the python script deepzoom.py as shown in the tutorial (I also tried using the MagickSlicer
 shell script but it also does not work). And I also tried to follow exactly the file structure shown in the tutorial.  

Here is my file structure :

[dir]   dzi
--[file] helloworld.dzi
--[dir]   helloworld_files
[dir]   openseadragon
[file] index.html

And here is my simple index.html :

```
<html>
  <head>
    <style type="text/css">
      #foo {
        width: 400px;
        height: 300px;
      }
    </style>
  </head>
  <body>
    <div id="image" style="width:800px; height:600px;"></div>
    <script src="openseadragon/openseadragon.min.js"></script>
    <script>
      var viewer = OpenSeadragon({
        id:            'image',
        prefixUrl:     'openseadragon/images/',
        tileSources:   'dzi/helloworld.dzi'
      });
    </script> 
  </body>
</html>
```

Do you think there is a problem with my dzi files ?

Thanks

PS : i don't know if it is uselful but my helloworld.dzi is the following : 
`<?xml version="1.0" encoding="UTF-8"?><Image xmlns="http://schemas.microsoft.com/deepzoom/2008" TileSize="128" Overlap="2" Format="png"><Size Width="640" Height="447"/></Image>`

**Comment by bruno-31** [comment]
This may be similar to [issue 1924](https://github.com/openseadragon/openseadragon/issues/1924), but I thinkt that no solution was found for this.

**Comment by bruno-31** [comment]
Hi, I solved my problem by looking at [issue 1727]( https://github.com/openseadragon/openseadragon/issues/1727)
I used to open the page locally instead of doing it with a local server. It works perfectly now. (I also missed the note on the getting stared page.)
I close the issue.

**Comment by UmangSharma5** [comment]
@bruno-31 you are correct, thanks for the solution.
