### ISSUE TITLE
I want to draw circles and polygons, but I don't know what to do

### ISSUE THREAD

**Issue by liyuewen** [openseadragon/openseadragon#2027]
I need to use the mouse to draw graphics after the picture is loaded

**Comment by iangilman** [comment]
You'll need an overlay that supports such things. We have a number of options listed in http://openseadragon.github.io/#plugins. For what you're doing, I recommend starting with https://github.com/altert/OpenseadragonFabricjsOverlay. Take a look at the demo code for ideas.
