### ISSUE TITLE
Download image after annotations 

### ISSUE THREAD

**Issue by ayamany224** [openseadragon/openseadragon#2028]
i would like to download image after making annotations on it not the original image so can anyone help me

**Comment by kausha15** [comment]
we were facing the similar requirement and we took the way getting screenshot using html2canvas library and later saved it on server.

**Comment by iangilman** [comment]
One approach would be to do your annotations with one of the canvas-based plugins... that way they would have already burned the annotations into the OSD canvas and you can save the whole thing together. Note this only works if you want just what's shown in the viewer at the moment. If you want the entire image, you'll need to come up with a way to draw the annotations onto the image yourself, perhaps even on the server side. 

You can find the plugins here: http://openseadragon.github.io/#plugins

These plugins all use canvas:

https://github.com/altert/OpenSeadragonCanvasOverlay
https://github.com/altert/OpenseadragonFabricjsOverlay
https://github.com/eriksjolund/OpenSeadragonPaperjsOverlay
