### ISSUE TITLE
Aspect ratio is not preserved in full screen

### ISSUE THREAD

**Issue by DominiqueDeCordova** [openseadragon/openseadragon#2032]
Aspect ratio is not preserved in full screen
![Original](https://user-images.githubusercontent.com/90426910/132774912-36924877-8f1e-4395-b020-57228f13b7b6.png)
![fullscreen](https://user-images.githubusercontent.com/90426910/132774923-dfb07066-ac74-4c6f-8f2e-7119f3306056.png)

**Comment by iangilman** [comment]
Strange! It's working for me on http://openseadragon.github.io/. Is it broken for you there as well? If so, what browser/OS/device are you using? If not, can you share a repro?

**Comment by DominiqueDeCordova** [comment]
Hi Ian,

Thank you for your reply!
It does work for me on http://openseadragon.github.io/. No complaints!
Browser – Google Chrome 92.0.4515.131 (Official Build) (64-bit)
OS – Windows 10 Enterprise.

I cannot share repo, unfortunately – it is Intel proprietary.
However, I would like to share a piece of code below.
The application is developed in Angular framework.
The application generates a set of images. The number of the images in the sequence is unknown in the compile time. Requirement is to display images in sequence mode (sequenceMode: true) with left and right navigation buttons.
Every time the sequence of images changes, I remove and recreate OSD viewer <div>, because I did not find another way to change number of images in the sequence. I do not load images’ urls on creating OSD viewer, because for each page different images can be displayed, based on options in component dropdown. For example, on the same page with 3-option dropdown three images can be displayed in different time (not in the same time).

I added 'pre-full-screen' and ‘full-screen’ events trying to adjust image size in full screen. The console shows that the values were set, but there was no effect on the image in full screen mode at all.

Thank you!
Dmitriy


            let sdOld = document.getElementById("seadragon-viewer")
            let parent  = sdOld?.parentElement
            sdOld?.remove();
            parent?.insertAdjacentHTML('afterbegin', '<div id="seadragon-viewer" #seaDragon ></div>')
            var sd = parent?.firstChild
            let sdHTMLElement: HTMLElement = sd as HTMLElement
            sdHTMLElement.style.width = "500px";
            sdHTMLElement.style.height = "500px";

            var self = this;
            setTimeout(function(){
                self.osdViewer = self.ngZone.runOutsideAngular(() => OpenSeadragon({
                    element: sdHTMLElement,
                    prefixUrl: '//openseadragon.github.io/openseadragon/images/',
                    showNavigator: true,
                    maxZoomPixelRatio: 10,
                    constrainDuringPan: true,
                    autoResize: false,
                    preserveViewport: true,
                    sequenceMode: true,
                    tileSources: Array(self.entries.length).join(".").split(".") // assign empty string to each place
                }));
                self.currIndex = self.entries.findIndex(x => x.imageFileName === data.imageFileName);

                self.osdViewer.goToPage(self.currIndex)
                const ts = {
                    type: 'image',
                    url: !!data.imageFileName ? href + data.imageFileName : 'assets/no_image.png',
                    buildPyramid: false
                }
                self.osdViewer.open(ts);
                self.navigationTracker.value = [0, self.currIndex]
                self.osdViewer.addHandler('page', e => self.setImagebyPage(<number>e.page))
                self.osdViewer.addHandler('pre-full-screen', e =>{
                    if(!!e.eventSource) (<any>e.eventSource).navigatorMaintainSizeRatio = true
                    if(!!e.eventSource) (<any>e.eventSource).navigatorSizeRatio = 1
                    if(!!e.eventSource) (<any>e.eventSource).navigatorHeight = 600
                    if(!!e.eventSource) (<any>e.eventSource).navigatorWidth = 600
                    if(!!e.eventSource) (<any>e.eventSource).preserveImageSizeOnResize = true

                    //debugger
                    console.log("OSD pre-full screen")
                })
                self.osdViewer.addHandler('full-screen', e =>{
                    //debugger
                    console.log("OSD full screen" + (<any>e.eventSource).navigatorMaintainSizeRatio)
                    console.log("OSD full screen" + (<any>e.eventSource).navigatorSizeRatio)
                })
            }, 500)
    }

    public setImagebyPage(index: number): void {
        this.currIndex = index
        this.DisplayImage();
    }

    public DisplayImage() {
        let imageFileName = chosen based on options
        this.osdViewer?.open({type: 'image',
            url: !!imageFileName ? href + imageFileName : 'assets/no_image.png',
            buildPyramid: false
        });
    }

    public DisplayImage2(imagePath: string) {
        this.osdViewer?.open({
            type: 'image',
            url: !!imagePath ? href + imagePath : 'assets/no_image.png',
            buildPyramid: false
        });
    }

**Comment by iangilman** [comment]
Hmm... I'm not seeing anything in there that would explain the aspect ratio thing. Would it be possible for you to make something like a CodePen that just shows the problem without including any of your proprietary code/data? You might be able to just use some simple non-tiled images for instance.

**Comment by DominiqueDeCordova** [comment]
Good morning Ian,

Please let me know if you can see it on https://jsfiddle.net/DmitriyShornikov/zkqgrnx8/8/
Thank you,
Dmitriy

**Comment by iangilman** [comment]
Great, I can! Looks like you have `autoResize: false` in your OSD options. If you remove that, everything works fine. Why did you want to disable autoResize? If you do want it, you'll have to resize manually on fullscreen.

**Comment by DominiqueDeCordova** [comment]
I removed ‘autoResize’ and that fixed the issue. Thanks a lot!

**Comment by msalsbery** [comment]
@DominiqueDeCordova  Just FYI, that autoResize flag was added for a specific purpose - a need I had to preserve the zoom factor and center point (relative to the image) when the viewer element's size changed. This was/is a desired feature when using OpenSeadragon in a pathology/medical imaging setting, and OpenSeadragon didn't do that at the time. So I added the autoResize flag which can be set to false then manually zoom and pan the image whenever the viewer element's size changes.

If that's something you were trying to do by setting autoResize to false, and you're having trouble implementing a solution, I may be able to help  :)

**Comment by DominiqueDeCordova** [comment]
Thank you Mark! I have not found any explanation yet why the flag was set to false. Reverting to default setting seems to fix the issue. In case, somebody would come back with an explanation that it indeed was set to false for specific purpose, I will ask for your help 😊
