### ISSUE TITLE
Landmarks getting drawn on older Viewport

### ISSUE THREAD

**Issue by tanreaper** [openseadragon/openseadragon#2034]
Hello Everyone, 

I would really appreciate if I can get any help on this. I have set of Images which I get dynamically by using slider and display it on Openseadragon. When I use the slider, I also get landmark points specific to that image and lay over it on the image. The images vary in resolution, also when the slider is used I update the tileSource to get the new image url. Now my problem arises, when ever I use slider to jump to the next image whose resolution is different from the current image and try to layover the landmark (recieved from api), it draws it on the old viewport. How can I reinitialize the viewer so that I can layover the Landmarks on the current viewport.

**Comment by iangilman** [comment]
Can you share a repro? It's hard to visualize what you are dealing with. How are you laying out the images? What are you using to draw the landmarks with? Are you working in viewport coordinates?
