### ISSUE TITLE
Is it possible to use openseadragon for visualizing high-resolution streaming images?

### ISSUE THREAD

**Issue by jmontoyam** [openseadragon/openseadragon#2035]
Hi,

first of all, thank you very much for keeping this amazing project up and running! ;).
I am a beginner JS user (but eager to learn more about JS and web technologies). In my use-case, I am interested in creating a web application that allows to visualize high-resolution streaming images acquired by an xray system (the server) while scanning objects on a moving conveyor belt. I would like to visualize the streaming raw images as the acquisition systems writes them to disk to check that the experiment is going well and the images are acquired as expected. Every "dt" milliseconds the acquisition system acquires a new "snapshop" and writes it to disk, this image is of dimension 64 x 10240. The number of images acquired during an experiment is variable (it could be thousands, tens-of-thousands, or even millions, it depends on the duration of the experiment). I am planning extending the acquisition systems such that not only write the raw images to disk, but also generate the image tiles to be used by openseadragon. I would like to use openseadragon for visualizing such stream of images while they are generated and exposed by the server (the acquisition system). At any given moment, the user can interact with the viewer (zoom-in/out, panning, etc), while the acquisition system continues streaming the new data. Do you guys think is it possible to use openseadragon to accomplish such goal?

Thank you very much!

All the comments, suggestions and advices are truly welcome ;).

**Comment by iangilman** [comment]
Interesting! What kind of stream is this? Is it basically a high-resolution video, with each snapshot being an entire frame? Or is it like a long scroll, with each new strip added to the end? I'll assume it's the latter. You could potentially use the OSD "multi-image" functionality and load each strip in turn as a "legacy tilesource". Then the user could pan and zoom around it as they wanted to. 

So yeah, I think it would be possible, though I don't know that OSD adds a lot to this scenario; you could use some other system for panning and zooming if you wanted to. That said, if you wanted to use OSD, it seems worth a try.

**Comment by jmontoyam** [comment]
Thank you very much @iangilman for your kind reply!...Yes, the stream is like a long scroll, where each new image chunk is added to the end. Each upcoming image from the streaming is of dimension 64x10240. I followed your advice and I was able to generate the effect that I want it:
![osd_streaming_demo](https://user-images.githubusercontent.com/3098532/133942324-5ff69c46-b2bc-41d6-85e4-f366034bc232.gif)
As you can see, at the beginning everything looks ok, but then it starts to become very laggy, the program can't keep up with the task of receiving and visualizing the data at the same time (the evidence of this behavior is the white strips the appear in the gif). I think the problem is my lack of knowledge about openseadragon and JS: in the current implementation, in order to obtain the effect shown in the gif, everytime a new image-chunk arrives, I move up all the previous received images, one by one!:
```javascript
const moveAllTiles = () => {

    let tiledImage;
    let count = viewer.world.getItemCount();
    let y;

    for (let i = 0; i < count; i++) {
        tiledImage = viewer.world.getItemAt(i);
        y = tiledImage.getBounds().y;
        tiledImage.setPosition(new OpenSeadragon.Point(0, y-aspectRatio));
    }
};
```
Please excuse me, I know this is very inefficient, but I do not know another more efficient alternative to generate such 
smooth-streaming-visualization...Could you please recommend me some openseadragon magic to generate the desire smooth-streaming-visualization?

BTW @iangilman , I saw an issue where you mentioned that you were creating a in-depth openseadragon course, is it already available?...I would really love to take your course as soon as possible!, I want to learn the internals of openseadragon in order to use it efficiently, but due to my JS beginner level, reading and trying to understand the documentation of the osd API by myself in taking me too much time :).

**Comment by iangilman** [comment]
Cool! And yes, you don't need to move all the images individually, because panning is built into OSD! Just do `viewer.viewport.panBy(new OpenSeadragon.Point(0, 0.01))` (or whatever value works for you) whenever you get a new strip. 

I'm not sure the white lines are because of the movement though... there may be other issues like tile load failures or rounding errors. I suppose we shall see! 

One thing you might want to do is remove strips once they have scrolled off the top, so you're not just filling up memory/processing forever. 

I'm glad to hear you're interested in the course! It's coming along, but it'll be a while before it's ready, because I'm doing it in my spare time. I can add you to the beta list for it if you're interested, though.

**Comment by jmontoyam** [comment]
Thank you very much @iangilman , I followed your advice and now the visualization is very smooth!. However, I have found another strange behavior. I am implementing the scrolling/panning effect inside the tile-loaded event, as follows:
```
viewer.addHandler('tile-loaded', function(event) {
    console.log(`tile-loaded: ${currentImage}, ${event.tiledImage.getBounds().y}`);

    counterTiles = viewer.world.getItemCount();
    console.log(`Current number of tiles: ${counterTiles}`);

    if(counterTiles===maximumNumberOfTiles){
        tiledToBeRemoved = viewer.world.getItemAt(0);
        viewer.world.removeItem(tiledToBeRemoved);
    }
    
    currentY += aspectRatio;

    if(firstTile){
        viewer.viewport.panBy(new OpenSeadragon.Point(0, 0.5), true);
        firstTile = false;
    } else {
        viewer.viewport.panBy(new OpenSeadragon.Point(0, aspectRatio));
    }

    console.log("-".repeat(50));
});
```
I want to be able to continue interacting with the viewer (using panning/zooming with the mouse) while the data continue arriving and the visualization continues showing the scrolling/panning effect. If I zoom or pan with the mouse, and the resulting image can still be fully displayed in the viewer, then there is problem, the tile-loaded event continues firing ok and the scrolling/panning effect continues working just fine. But as soon as I pan "too much" and I cross the lower margin of the viewer, then the tile-loaded event is not fired anymore, therefore the scrolling/panning effect does not work anymore (as you can see in the attached gif). The same happens if I zoom "too much" and the resulting image fully cover the whole viewer. Is it possible to zoom and pan with the mouse as much as I want, and still be able to show the continue scrolling/panning effect?
![output](https://user-images.githubusercontent.com/3098532/134775769-8879412f-a268-40f3-bbc6-710696533aa1.gif)

Regarding your OSD course, yes!, I am very interested in the course!, please feel free to add me to the beta list!, perhaps I can give you interesting feedback and comments from my beginner point of view :).

**Comment by iangilman** [comment]
Hmm... interesting issue! For starters, do you want the automatic panning mixed with user panning? When I suggested panning the scene, I hadn't been thinking about the fact the user could also pan. One possibility would be to go back to moving all of the images rather than using panning to move down them. 

On the other hand, if you like this combination of automatic and manual panning, maybe it's not such a bad thing that the automatic panning stops when you get away from the leading edge? It's probably worth thinking through what the user wants at that moment... maybe they want to focus on a particular portion of the image and don't want it scrolling away? 

Anyway, if you do want to keep things moving, maybe instead of basing the panning off of the tile loading event, you could base it off of whatever it is that causes you to add the new strip in the first place?

**Comment by iangilman** [comment]
Regarding the course beta, please email me at ian@iangilman.com :)

**Comment by jmontoyam** [comment]
Thank you very much @iangilman , I will follow your advice and I will explore in more detail both use cases.
Regarding the course, I just sent you an email as you suggested me ;).
