### ISSUE TITLE
Is there any theoretical limit to how big an image we view

### ISSUE THREAD

**Issue by SpeedOfSpin** [openseadragon/openseadragon#2036]
I am looking to create an extremely large pyramid of maybe 21 to 22 levels and I was wondering if there was any limit in the viewer itself which would stop me from displaying a deepzoom this big,

Thanks!

**Comment by iangilman** [comment]
There's no explicit limit, but you may eventually run into rounding errors or something. I haven't heard any reports of people hitting such limits. The biggest OpenSeadragon image I know of is https://www.in2white.com/ which is 365 gigapixels. 

Let me know if you run into any issues, and of course I'd love to see the image once it's up!

**Comment by SpeedOfSpin** [comment]
Thanks Ian. We are looking to do one many times that size (with a twist ;-) ). I will definitely let you know when its up.

thanks again

**Comment by iangilman** [comment]
Awesome! I look forward to it :)
