### ISSUE TITLE
Scroll image request threshold

### ISSUE THREAD

**Issue by Vicnovais** [openseadragon/openseadragon#2038]
Hello!

Is it possible to delay the request to get the image tiles after scrolling? I would like to apply some kind of "debounce" to wait some time before firing the request to get the zoomed tile, so my server could save some resources.
The `imageLoaderLimit` property kinda does this job, but I would like to know if it's possible to make max concurrent calls while still waiting some time to fire them.

Example: 
1. User scrolls to max zoom
2. After some delta time (eg 200ms), OSD makes the request only to the zoomed tile

Best regards

**Comment by iangilman** [comment]
We don't have a mechanism like that (that I can think of). You might try experimenting with replacing `OpenSeadragon.ImageLoader.addJob` with a debounced version. It would skip all but the last requested tile, so I don't know if that would cause any confusion. Worth a try, though!

**Comment by Vicnovais** [comment]
Thanks for answering @iangilman! I'll try to implement what you described.
