### ISSUE TITLE
Large image jpg - fail 

### ISSUE THREAD

**Issue by valeriofinazzo** [openseadragon/openseadragon#2044]
Hi, 
when openseadragon load an image with 30750x9729 it's showed white screen after loaded
thanks for your reply

**Comment by iangilman** [comment]
Is this a single image or have you converted it into tiles? If it's a single image, it seems like it's a bit too big for that and would be best converted. Here's a collection of tools for that:

http://openseadragon.github.io/examples/creating-zooming-images/

**Comment by valeriofinazzo** [comment]
it's a single image. If i download image ed open it with browser the image is showed, but if i open it with openseadragon there is not error in console, only white screen.

**Comment by iangilman** [comment]
What browser are you testing on? I know Safari has some limitations on how big of a canvas you can make. 

At any rate, that image is big enough that it's worth converting into a DZI or something; not only will it fix this issue, but it'll load faster for your end users.

**Comment by KARTHI2710** [comment]
the issue is resolved or not?

**Comment by iangilman** [comment]
@KARTHI2710 This was just a discussion; no action item came out of it. Is there some issue you're experiencing?
