### ISSUE TITLE
collection mode - avoid gaps between images in multiple tiled image loading

### ISSUE THREAD

**Issue by roshtha** [openseadragon/openseadragon#2050]
Hello,

I use OpenSeaDragon for displaying cytology images. We are displaying images from multiple tiled sources. There are 864 tiled image folders and .dzi files. They are to be arranged as a grid in 54 rows and 16 columns. All .dzi file has the following details:

`<?xml version="1.0" encoding="UTF-8"?><Image xmlns="http://schemas.microsoft.com/deepzoom/2008" TileSize="128" Overlap="2" Format="png"><Size Width="4096" Height="2160"/></Image>`

I could load the images using the following code:

    viewer = OpenSeadragon({
		id: "openseadragon",
		prefixUrl: "../../DZIImages/openseadragon-bin-2.4.2/images/",
		homeFillsViewer: true,
		showNavigator: true,
		showRotationControl:true,
		collectionMode: true,
		collectionTileSize: 128, 
		collectionTileMargin: 0		
	});

    var numberofrows = 54;
    var numberofcols = 16;
    var tr;
    var tc;
	
    for (r = 1; r <= numberofrows; r++) 
    {		
	if( r<10 )
	{
		tr = "0" + r;
	}
	else
	{
		tr = "" + r;
	}
	for (c = 1; c <= numberofcols; c++) 
	{
		if( c<10 )
		{
		tc = "0" + c;
		}
		else
		{
		tc = "" + c;
		}
		vartilesource = '../../DZIImages/ImageName_r00' + tr + '_c00' + tc + '.dzi'; //dynamically forms tiled source filename
		
		//Setting OSD viewer properties
		viewer.collectionRows = numberofrows;
		viewer.collectionColumns = numberofcols;
		viewer.addTiledImage({
			tileSource: vartilesource 
		});			
		
	}	
   }
    
The screenshot of loaded images:

![osd](https://user-images.githubusercontent.com/5310634/137078197-7ed0d16a-15cc-47fb-a182-76f9f5643b93.png)

Issue1:
Now, I want to show the images continuously without gaps in between. 
I tried setting collectionTileMargin property as 0 in the viewer object. 
But could not get desired image output. How can I display images without gaps?

Issue 2:
Though all images load, the following variable count returns 0
    var count = viewer.world.getItemCount();
    console.log("count of loaded images " + count)

Thanks all!

**Comment by iangilman** [comment]
Excellent :)

**Comment by Sadhikakichu** [comment]
> viewer.addHandler('open', function() {
>   var count = viewer.world.getItemCount();
>   console.log("count of loaded images " + count);
> });
> ```
> 
> BTW, one optimization you might consider, since you have so many images on the screen at the same time, is not to load the DZI file for each one. This will save a lot of trips to the server.
> 
> Actually, here, let me show you what I'm talking about:
> 
> ```
> 
> var tileSources = [];
> var width = 4096;
> var height = 2160;
> var numberofrows = 54;
> var numberofcols = 16;
> var tr;
> var tc;
> 
> for (r = 1; r <= numberofrows; r++) 
> {		
> if( r<10 )
> {
> 	tr = "0" + r;
> }
> else
> {
> 	tr = "" + r;
> }
> for (c = 1; c <= numberofcols; c++) 
> {
> 	if( c<10 )
> 	{
> 	tc = "0" + c;
> 	}
> 	else
> 	{
> 	tc = "" + c;
> 	}
> 	var url = '../../DZIImages/ImageName_r00' + tr + '_c00' + tc + '_files/'; //dynamically forms tiled source filename
> 	
> 	var tileSource = {
> 			Image: {
> 					xmlns: "http://schemas.microsoft.com/deepzoom/2008",
> 					Url: "../../data/testpattern_files/",
> 					Format: "png",
> 					Overlap: "2",
> 					TileSize: "128",
> 					Size: {
> 							Width:  "4096",
> 							Height: "2160"
> 					}
> 			}
> 	};
> 	
> 	tileSources.push({
> 		tileSource: tileSource,
> 		x: c * width,
> 		y: c * height,
> 		width: width,
> 		// It figures out height automatically
> 	});
> }	
> 
> 
> viewer = OpenSeadragon({
> 	id: "openseadragon",
> 	prefixUrl: "../../DZIImages/openseadragon-bin-2.4.2/images/",
> 	homeFillsViewer: true,
> 	showNavigator: true,
> 	showRotationControl:true,
> 	tileSources: tileSources
> });
> ```
> 

How to work annotorious in this. When i click on annotation i get  [Viewport.imageToViewportRectangle] is not accurate with multi-image; use TiledImage.imageToViewportRectangle instead.

**Comment by iangilman** [comment]
Good question! 

@recogito, does Annotorious support multi-image?
