### ISSUE TITLE
Moving along image without clicking mouse esch time

### ISSUE THREAD

**Issue by selko** [openseadragon/openseadragon#2052]
Hi,
I would like to know if it's possible to click one time with mouse and then moving along the image  without clicking again.

if not, if someone can tell me with which events i must work to develop it i really appreciate it. 

I think it could be nice to move without clickin snd draggin each time.

Kind regards and thank you all!!

**Comment by selko** [comment]
Yes,
 
 i'm going to try today this and if i get it, i can share for all. My intention os with a button activate this for not loosing the other option of dragging. I think this implementation is cool for no dragging all time

**Comment by selko** [comment]
But yes, one click activate for non dragging and second click desactivate it. It is a good choice

**Comment by iangilman** [comment]
Cool. I look forward to seeing what you come up with!
