### ISSUE TITLE
Little gap between png tile images

### ISSUE THREAD

**Issue by dluo222** [openseadragon/openseadragon#2058]
Greetings,

I have used openseadragon for a while. It is an awesome js library.  
I met this little gap issue before when I generate tile images in png format. So I decided to switch to jpg. The issue was gone.
But this time I need to keep the alpha channel with transparent background in tile images. Only png can keep the info. I still can see the gap between tiles. Is there any method I can fix the issue?

Thanks

**Comment by alvaromartmart** [comment]
I recommend you refer to https://github.com/openseadragon/openseadragon/issues/1683, I think it's the same issue you're facing.

**Comment by iangilman** [comment]
While we have been unable to find an automatic fix for this issue, we've now landed a set of options that allow you to fix the issue based on your needs and preferences: #2075. I'm going to close this issue and we can start a fresh one if there are new ideas for how to fix it more robustly and/or automatically.
