### ISSUE TITLE
After zooming in, the value of viewer.viewport.deltaPixelsFromPoints seems to be wrong.

### ISSUE THREAD

**Issue by jhbum01** [openseadragon/openseadragon#2060]
I am programming to make a cursor with a size of 128 x 128 and move the cusor using the arrow keys, and move the viewport by 128 when the cursor is out of the viewport.
After zooming out to the maximum, it was programmed as follows.
// to get the size and position of the viewport
viewBounds = viewer.viewport.getBounds(true);
// Get the start x,y and end x,y of the viewport as point values.
firstX = viewBounds.x;
firstY = viewBounds.y;
lastX = viewBounds.x + viewBounds.width;
lastY = viewBounds.y + viewBounds.height;
// Change the starting x, y and last x, y point values ​​of the viewport to pixels
firstPoint = new OpenSeadragon.Point(firstX, firstY);
lastPoint = new OpenSeadragon.Point(lastX, lastY);
firstPos = viewer.viewport.deltaPixelsFromPoints(firstPoint, false);
lastPos = viewer.viewport.deltaPixelsFromPoints(lastPoint, false);

In this way, it was confirmed that it was imported normally.
But after zooming in to viewport.zoomBy(0.5)
If you try to get the pixel value of the above viewport again, I cannot get a normal value.
For example, it initially gets the following values:
viewBound Start Position(pixel) : 8422.04, 16943.38
viewBound Last Position(pixel) : 8782.04, 17358.38

And after zoom in to viewport.zoomBy(0.5),
If I try to get the pixel value of the viewport again, I get smaller values.
viewBound Start Position(pixel) : 4121.02, 8367.94
viewBound Last Position(pixel) : 4481.02, 8782.94

After zooming in, how do I get a value within the same range instead of a smaller value?

**Comment by iangilman** [comment]
What are you trying to do with these values? Do you really want the delta conversion, which doesn't take into account position but is just for sizes? 

If you're trying to pan by 128 web pixels no matter how zoomed in or out you are, you could do something like: 

```
var isRightArrowPressed; // Set this based on your event handling
if (isRightArrowPressed) {
  viewer.viewport.panBy(viewer.viewport.deltaPointsFromPixels(new OpenSeadragon.Point(128, 0)));
}
```

**Comment by jhbum01** [comment]
Thank you very much for your reply.
As you mentioned, if you press the key to move the cursor one space at a time by 128 pixels, the viewport needs to be updated again when the cursor leaves the viewport.
For example, if you press the right arrow key to move 128px out of the viewport of the screen, you want to move the viewport itself to the right by 128px to continue showing it to the user. So, as you mentioned, in addition to moving the cursor 128px, the purpose is to make sure the cursor is out of the viewport area and move the viewport itself by 128px. As I said above, when zooming in, the viewport becomes smaller, which is a problem. Is there a way to get the exact position of the viewport in web pixels when zooming out and zooming in? Thank you so much for your kind reply.

**Comment by iangilman** [comment]
Sure, to get the current viewport bounds in web coordinates, you can do `viewer.viewport.viewportToViewerElementRectangle(viewer.viewport.getBounds())`.
