### ISSUE TITLE
Query negative coordinates in tileSources

### ISSUE THREAD

**Issue by n-chicken** [openseadragon/openseadragon#2062]
OpenSeadragon({
        id:            "canvas",
        // navigatorSizeRatio: 0.25,
        showNavigator:      false,
        wrapHorizontal:     false,
        visibilityRatio: 1.0,
        constrainDuringPan: false,
        minZoomLevel: 0.00001,
        maxZoomLevel: 2,
        tileSources:   {
            height: 20*256,
            width:  20*256,
            tileSize: 256,
            minLevel: 1,
            maxLevel: 1,
            getTileUrl: function( level, x, y ){
                return "http://localhost:2718/" + x + "," + y + ".png";
            }
        }
    });

Given this configuration, I only see non negative coordinates being loaded. Is there a way to have them be loaded?

I guess I could do some manual offsetting with links or something but is there an easier way?

**Comment by iangilman** [comment]
Yeah, OSD's tile X/Y system goes from 0, 0 in the upper left and counts up from there. Your system has negative numbers? If so, you'll have to subtract something from the X and Y. 

Out of curiosity what did you use to create your tiles? How do the numbers go on them?

**Comment by n-chicken** [comment]
Minecraft chunk coordinates :P

Should range from about -100k x and y (or, z, actually)

**Comment by iangilman** [comment]
Nice! Mapping a Minecraft world seems like a great use for OSD :)

You say it ranges from -20K to 20K, but in your tile source definition you say `width:  20*256`, which would just be 20 tiles, not 40,000 tiles. Is it really 40,000 tiles? If so, you would want to do `width:  40000*256`. Actually, I guess it would be 40,001, because of the 0 tile. 

Anyway, if it starts at -20,000, then you should be able to just modify your `getTile` like so:

```
return "http://localhost:2718/" + (x - 20000) + "," + (y - 20000) + ".png";
```

**Comment by n-chicken** [comment]
Thanks!

I was actually just playing around with low values for height and width. What's actually going to happen is that the width and height of the map should keep increasing as the map is explored, so it always changes. I don't know how I didn't think of changing getTile for this though, thanks for this too

**Comment by n-chicken** [comment]
![image](https://user-images.githubusercontent.com/50345823/142503633-bfdc31b5-ce3f-44a5-a321-df0838ca9335.png)

That worked! But now I see that I have a lot of gaps in-between my tiles. Is there a way to "go to" a specific coordinate?

**Comment by iangilman** [comment]
Cool! I assume that's all of the space you've explored so far in this world? 

By gaps, do you mean the grid of seam lines? That's a known issue with PNG: https://github.com/openseadragon/openseadragon/issues/1683 I assume it wouldn't be easy to convert over to JPG? You can see some discussion of the problem in that issue. 

If you want to "go to" a specific area, you can use `viewer.viewport.fitBounds`... pass in the rectangle you want to zoom/pan to, in viewport coordinates. If you want to use image coordinates instead, the viewport has conversion functions. 

You can call `viewer.world.getItemAt(0).reset()` to clear out all tiles and reload them, but that's not really what you're wanting. Adding a new reset that just resets the "not found" flags seems like a cool idea. If you want, you can file a fresh issue for that, and if you're up for working on making it happen, I could point you in the right direction :)

**Comment by n-chicken** [comment]
The thing is, this is just a tiny portion of the already explored part of the map. By gaps I wasn't refering to the grid (I actually thought that was a feature lol), I was refering to the long distances between tiles.

`viewer.viewport.fitBounds` does exactly what I wanted, thanks!

Actually I don't mind refreshing this is working great and you don't wanna see my javascript lol

Thanks again for the help mate

**Comment by iangilman** [comment]
@n-chicken great, I'm glad you got what you needed! As long as your code gets you what you want, it's all good :)
