### ISSUE TITLE
Image annotation and list of tools

### ISSUE THREAD

**Issue by Zvyozdo4ka** [openseadragon/openseadragon#2063]
Is it available to add image annotation? And is there any lists with all tools that is available in your project?

**Comment by iangilman** [comment]
You can see all of the available plugins here: http://openseadragon.github.io/#plugins

There are several annotation plugins. I believe https://github.com/recogito/annotorious-openseadragon is the most advanced. 

If you don't find what you want, there are also more general overlay plugins that you can build your annotations on top of.
