### ISSUE TITLE
Question about updateOverlay 

### ISSUE THREAD

**Issue by Canees** [openseadragon/openseadragon#2068]
hi:
    The updateOverlay method updates other DOM elements, but does not update the SVG view position in openSeadragon-SVG-overlay. 

exp：
       const newSvg = document.createElementNS('http://www.w3.org/2000/svg', 'circle')
      newSvg.setAttributeNS(null, 'cx', 100)
      newSvg.setAttributeNS(null, 'cy', 100)
      newSvg.setAttributeNS(null, 'r', 100)
      newSvg.setAttributeNS(null, 'fill', 'red')
      newSvg.setAttributeNS(null, 'stroke-width', 2)
      newSvg.setAttributeNS(null, 'id', 'test')
      svgG.append(newSvg)
      this.viewer.updateOverlay('test', new OpenSeadragon.Point(100, 100), OpenSeadragon.Placement.CENTER)

**Comment by iangilman** [comment]
You're referring to this plugin, right? https://github.com/openseadragon/svg-overlay

That plugin does not utilize the built-in OSD overlay methods, so yes, `updateOverlay` will have no effect. Instead, to move your SVG elements around, change their attributes directly.

**Comment by Canees** [comment]
> You're referring to this plugin, right? https://github.com/openseadragon/svg-overlay
> 
> That plugin does not utilize the built-in OSD overlay methods, so yes, `updateOverlay` will have no effect. Instead, to move your SVG elements around, change their attributes directly.

thanks,
