### ISSUE TITLE
Safari browser - double tap gesture not recognized to zoom in

### ISSUE THREAD

**Issue by liveman1** [openseadragon/openseadragon#2070]
Hi,

Safari 15 on iOS does not recognize the double tap gesture anymore in order to zoom in.
It perfectly works in Chrome.

Is there any way to fix that?
Thanks

**Comment by iangilman** [comment]
Interesting. Perhaps they added something around double tap in version 15 that makes it harder for the webpage to see the event? Someone will have to do some experimentation to see if there's a way to capture the event. I believe the way we do it in OpenSeadragon is to watch touchstart and touchend events and if there are two sets close enough we consider it a double tap. Maybe there's a special double tap event in the new Safari that masks some of these other events or something? 

I found this, but it's not necessarily all that helpful: 

https://developer.apple.com/forums/thread/691478

@liveman1 thank you for reporting this! Are you up for debugging it? If so, I can point you in the right direction.

**Comment by liveman1** [comment]
Hi, 
thanks a lot for your reply and the explanation.
Sorry for the confusion, I think it is caused by a custom script to trigger a context menu on tap. It is a strange behaviour works quite differently on different devices & browsers.
It would be great if there would be a straight forward recognition of a double tap that does not conflict with an on tap event too easily. Unfortunately, I am no programmer and can‘t help here.
Best regards

**Comment by liveman1** [comment]
Just to be precise, double tap does not work in Safari on iPhones since the latest release of iOS 15. 
It works in Chrome on iPhones.
There is no issue on tablets (iPad, Windows) no matter which browser is used.
I could not test it for Android devices.

**Comment by iangilman** [comment]
I see. Well, it's possible we're going to have to wait for a fix from Apple. Still, hopefully someone can do some experimentation in the meantime to see if there are any workarounds. Thanks again for the info!

**Comment by liveman1** [comment]
Hi, 
iOS 15 introduced new zoom controller settings.
Obviously, there is a dedicated setting to zoom in on double tab.
When selecting to do nothing on a double tab, everything works great!
I wonder if there is any other way than changing the iOS settings.
Best regards

**Comment by iangilman** [comment]
Good to know!

**Comment by liveman1** [comment]
Hi, this works again. Not sure if there was any change on iPhone/Safari side.  :)

**Comment by iangilman** [comment]
Wild... thanks for the update!
