### ISSUE TITLE
Relative position & size of overlays

### ISSUE THREAD

**Issue by liveman1** [openseadragon/openseadragon#2074]
Hi,
is it possible to define a relative position & size of an overlay in relation to the underlying deep zoom image?
This would be very helpful, if the resolution of the underlaying image would be updated.

Thanks a lot!

**Comment by iangilman** [comment]
I'm not sure what you mean. By default, overlays are positioned relative to the underlying image. You can make their size change as well, though the text contents of an overlay do not scale as you zoom.

**Comment by liveman1** [comment]
Hi, I mean to define the position not as a fixed coordinate but as a relative metric (e.g. 10% from top & 30% from left).
Same with the dimension of an overlay.

**Comment by iangilman** [comment]
By default your image goes from 0 on its left side to 1 on its right side (though you can change that if you want). If you put an overlay at 0.3, it'll always start 30% across the image no matter how you zoom or pan. If you specify a width for the overlay, it will be proportional just the same. You can see some examples here: 

http://openseadragon.github.io/examples/ui-overlays/ 

Are you finding this not to be the case somehow? Can you share an example?

**Comment by liveman1** [comment]
Thanks a lot for the explanation. I didn't know. That's perfect! Thanks!
