### ISSUE TITLE
How to use svgOverlay with OpenSeadragon in Typescript

### ISSUE THREAD

**Issue by shyamkumaryadav** [openseadragon/openseadragon#2076]
@alvaromartmart can you help ?

**Comment by alvaromartmart** [comment]
> @alvaromartmart can you help ?

Sorry, I didn't yet figure out how to add types support for OpenSeadragon plugins.
The only option I can think of if you want to use `OpenSeadragon`+`@types/openseadragon` and some plugin is to cast to `any` when trying to access plugin methods/properties so typescript doesn't yell at you. Something like:
```ts
(viewer as any).svgOverlay();
```

I hope it helps

**Comment by shyamkumaryadav** [comment]
https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-namespaces

**Comment by alvaromartmart** [comment]
> https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-namespaces

Hey @shyamkumaryadav! I haven't worked on this for a while now but I'm glad you found a solution. Would you be so kind to provide an example of how you made it work for OpenSeadragon + plugin? May be useful towards being able to add plugin type definitions to `DefinitelyTyped`
