### ISSUE TITLE
One touch zoom in & out function

### ISSUE THREAD

**Issue by liveman1** [openseadragon/openseadragon#2077]
Hi,
it would be cool to have a one finger zoom in and out functionality like Google Maps.
Meaning to touch and hold with one finger & moving finger up to zoom in & moving finger down to zoom out again.

**Comment by iangilman** [comment]
This happens in Google Maps? The app or the website? Desktop or mobile? I've never seen this in Google Maps. Are you talking about pressing in the map itself or on some sort of control?

At any rate, you could certainly write it with OSD by overriding the normal mouse controls.

**Comment by liveman1** [comment]
yes, Google Maps provides this quite handy functionality on mobile devices, when touching the map.  :)
Would be cool, to have it ootb in OSD.

**Comment by iangilman** [comment]
The Google Maps app? Or the website? Is this on iOS or Android? I've tried it on iOS in both the app and the website and I can't make it happen.

**Comment by liveman1** [comment]
For me it works on the website (Safari & Google on iPad & iPhone) & in the app.
You need to double tap & keep holding the finger on the second tap. When moving the finger up you are zooming in, when moving the finger down you are zooming out.

**Comment by iangilman** [comment]
Oh! Double tap first! Yup, I see it now. Cool… I had no idea that existed!

I wonder how common knowledge of this gesture is… I don't know that we want to add it to OpenSeadragon directly, but I imagine you should be able to build it on top, using a MouseTracker.

**Comment by SMA-cgn** [comment]
Hi,
this sound like a cool feature to improve accessibility and usability!
I would be happy if you would add to your roadmap.

Thanks!

**Comment by iangilman** [comment]
@SMA-cgn Nice! That's a great idea! When I follow the link, however, it says "You don't currently have access to this page". Do you need to publish it or something?

**Comment by SMA-cgn** [comment]
Thanks for the note! Not sure how to share a public link? Probably on will need an account. Development will start soon now.
It would be great if you could advice how to integrate it best.
The developer will join the discussion here soon.

**Comment by SMA-cgn** [comment]
How many hours effort would you estimate to get that done?
The alignment on Upwork is already to heavy for such a small feature 😵‍💫

**Comment by HamzaTatheer** [comment]
Thanks @SMA-cgn, I just had a look at the code.

Based on my initial understanding, there is a onCanvasClick() function defined in Viewer.js
Would it be a good decision to implement this feature in that function as clickToZoom is also implemented there
I think that another property such as doubleTouchDrag should also be added in settings which will be then used to override clickToZoom if it is turned on. Any help is highly appreciated :)

**Comment by HamzaTatheer** [comment]
The double tap zoom in functionality should only be enabled for mobile web view and mobile app but not for desktop view of OSD. Going with this approach. If anyone thinks different, let me know

**Comment by SMA-cgn** [comment]
Hi Hamza,
right, this should only be available on mobile touch devices. On desktop PCs the mouse wheel already does the job :)

Thanks!

**Comment by HamzaTatheer** [comment]
Gesture Settings exist for each pointer type. 

            gestureSettingsMouse {...}
            gestureSettingsTouch {...}
            gestureSettingsPen {...}
            gestureSettingsUnknown {...}


These settings are as follows

                dragToPan: true,
                scrollToZoom: true,
                clickToZoom: true,
                dblClickToZoom: false,
                pinchToZoom: false,
                zoomToRefPoint: true,
                flickEnabled: false,
                flickMinSpeed: 120,
                flickMomentum: 0.25,
                pinchRotate: false            


I have to add mine for this feature. Any idea what should I name it or if there is a proper name for it. Maybe DoubleTapDrag ?

**Comment by HamzaTatheer** [comment]
Another Thing Possible is that it should follow the setting of dblClickToZoom. I think it is a better approach because this feature is actually an extended feature of dblClickToZoom and follows the same boolean value for each screen type

**Comment by HamzaTatheer** [comment]
When do gesture settings change, How do I test the feature on mobile.

**Comment by liveman1** [comment]
Sry, not sure if I got the question right.
I would expect to execute this feature when you double tap on the screen & keep your finger hold on the screen on the second tap. In this hold position move up to zoom in and move down to zoom out.
It should still be possible to just double tap (without hold) in order to zoom in.

**Comment by SMA-cgn** [comment]
Hi, this would be fine for me!

**Comment by iangilman** [comment]
@HamzaTatheer Welcome! Thank you for tackling this! 

Implementing it in `onCanvasClick` seems like a good start, though that might not be the exact right place. I think I would keep track of the most recent click event there, but then in `onCanvasPress` note whether it was soon enough to be considered a double click, and then in `onCanvasDrag` do the right thing based on that information. 

> I would prefer to have a new feature called dblTapHoldToZoom which is disabled by default.

Sounds good, or how about `dblTapDragToZoom`? Also, it should probably be click, rather than tap, just to be consistent with `dblClickToZoom` (which also supports both mouse and touch). So `dblClickDragToZoom`?

> When do gesture settings change, How do I test the feature on mobile.

I believe it's based on the type of event. To get touch events on your computer, you need to switch into mobile mode in the development tools.

**Comment by HamzaTatheer** [comment]
@iangilman Okay, great. That clear things out. I am stuck in a weird problem. I am testing my code using http://localhost:8000/test/demo/basic.html

However, whenever I Zoom It zooms in  or zooms out too much. This is the code I wrote for zooming in while dragging 


    if (gestureSettings.dblClickToZoom && THIS[ this.hash ].draggingToZoom){
        var factor = Math.pow( this.zoomPerDblTapDrag, event.delta.y );
        this.viewport.zoomBy(factor);
        this.viewport.applyConstraints();
    }

I know that the factor comes out to be a huge number but even if i hard code factor by 0.1, it gives the result.
Can you please have a look at my repo and give me some insight on how i can make it zoom less.

**Comment by HamzaTatheer** [comment]
I finally found one equation that works much better now. Do let me know some improvements. Hardcoding 100 means i get a less zoom factor.

    if (gestureSettings.dblClickToZoom && THIS[ this.hash ].draggingToZoom){
        var factor = Math.pow( this.zoomPerDblTapDrag, event.delta.y / 100 );
        this.viewport.zoomBy(factor);
        this.viewport.applyConstraints();
    }

**Comment by SMA-cgn** [comment]
@iangilman  from my perspective the new zoom functionality works fine! It would be great to have it in the core of openseadragon!
Hamza still needs your feedback on the code for the zoom speed. It would be great if you could review it please.

@HamzaTatheer thanks for the great work! Would you mind to share the link to your test environment here in order to demo the new zoom functionality?

Thanks a lot!

**Comment by HamzaTatheer** [comment]
Sure,
Demo: https://master--vocal-wisp-c1e55d.netlify.app/test/demo/collections/index.html
Code: https://github.com/HamzaTatheer/openseadragon

**Comment by iangilman** [comment]
@HamzaTatheer, I'm blanking on the proper equation at the moment, but basically what you want is something where if you drag in one direction x pixels, the factor is 2, and if you drag in the other direction the same amount, the factor is 0.5. You can then multiply that by `zoomPerDblTapDrag` so the user can help specify how fast it goes. I don't think what you have here is quite that. 

I went to take a look at your demo just now, and it seems it's not showing the new feature at the moment? I couldn't get it to do it.

I also took a quick look over your code, and it looks like a good start. Maybe it's time to start a pull request, so we can be discussing various aspects directly in the code?

**Comment by iangilman** [comment]
Hmm... Looks like the scroll handler does exactly what you're doing, so yeah, I guess you've got it! It's just been a while since I thought about that part of the code.

**Comment by SMA-cgn** [comment]
@HamzaTatheer i just tested it again in the posted test environment. It seems that there is again this behaviour that it zooms only when releasing the finger after the double tap and then drag up/down. Could you please check?
Could you also please set viewer maxZoomLevel = 1000 to enable a deeper zoom in the test environment?

**Comment by HamzaTatheer** [comment]
@SMA-cgn Regarding zoom in after releasing the double tap and then dragging, can you tell me that does it also work for the situation where you dont release the finger on double tap and keep dragging.

Moreover, yes i wil change the zoom level in the morning

**Comment by HamzaTatheer** [comment]
@iangilman Sure. I will create the PR. Moreover, i am not sure why the feature is not working for you because when i test it on my own mobile and laptop, it is working.

are you double tapping and then not releasing finger on second tap but instead dragging up and down ?

**Comment by iangilman** [comment]
@HamzaTatheer I've just retested and I'm still getting the same results. I double click and on the second click, I don't release the mouse button, but instead drag up and down. The image pans just like a normal drag. When I look at the code: 

https://master--vocal-wisp-c1e55d.netlify.app/test/demo/collections/main.js

... I don't see any special double tap drag options in the `config` object at the top. Shouldn't there be? 

Tested on Mac Firefox and Chrome.

**Comment by HamzaTatheer** [comment]
Look at the 5th option. I added this in openseadragon.js, should it be some place else ?

            gestureSettingsMouse:   {
                dragToPan: true,
                scrollToZoom: true,
                clickToZoom: true,
                dblClickToZoom: false,
                dblTapDragToZoom: false,
                pinchToZoom: false,
                zoomToRefPoint: true,
                flickEnabled: false,
                flickMinSpeed: 120,
                flickMomentum: 0.25,
                pinchRotate: false
            },

**Comment by HamzaTatheer** [comment]
The Reason it was not working on your laptop was because it is disabled through gesture settings on laptop. Besides this regarding the formula, I originally tried to avoid throttling in the original formula used by onCanvasScroll but upon analyzing it further, It seems that I should follow the same approach. I will make this change and one other change regarding a bug mentioned by @SMA-cgn  and then create a PR so we can proceed ahead by code

**Comment by HamzaTatheer** [comment]
I added the same formula as used in onCanvasScroll, it seems to be not giving smooth results. I will try some other approach. I have also created PR now

**Comment by iangilman** [comment]
@HamzaTatheer I'm not seeing any reference to `gestureSettingsMouse` in your demo file: 

https://master--vocal-wisp-c1e55d.netlify.app/test/demo/collections/main.js

Perhaps that's why it's not working there? Anyway, now that you have the PR in, I can test locally :)

**Comment by iangilman** [comment]
@SMA-cgn @liveman1 The conversation is continuing in #2225 if you want to check in there :)
