### ISSUE TITLE
Images wider than 2048 pixels distorted on zooming

### ISSUE THREAD

**Issue by gbassham** [openseadragon/openseadragon#2078]
We have a source image that is 2079 pixels wide. When zooming, the first strip (the first 2048 pixels) are scaled down by half, to be 1024 pixels wide. The second strip, however (pixels 2049 - 2079) remain 31 pixels wide instead of scaling down. This causes a visible jag in the image upon zooming.

It seems to us that the second strip should also be scaled down, so as to be 15 or 16 pixels instead of 31.

**Comment by iangilman** [comment]
Are you using a custom tilesource? Do you have a repro you can share? It generally doesn't do this...
