### ISSUE TITLE
Synchronise rotated and transformed images

### ISSUE THREAD

**Issue by ChristianMarzahl** [openseadragon/openseadragon#2080]
Hi,

First of all, thanks to you for this great open source project.

I have a question regarding the rotation properties and their behaviour. 

My idea is to show two images in sync, independent of their rotation. Please have a look at the prepared [CodePen](https://codepen.io/christianmarzahl/pen/OJxQZgM) example. By clicking on the canvas of each image, you get the viewport and image coordinates (for example the blue dot at the right ear in the following image) for that image. You can verify with this example that the applied affine transformation is correct but unfortunately, the visualisation shows not the same image patch.

![image](https://user-images.githubusercontent.com/22664224/147744117-738d424c-a9a5-47c6-ba41-6e1d55b54f41.png)

The function ***affineCorrectionWithRotation*** from the [CodePen](https://codepen.io/christianmarzahl/pen/OJxQZgM) example, transforms the source image coordinates from the left image to the right image.

 ```js
var affineCorrectionWithRotation = function () {
  // some know parameters
  let [mpp_x_scale, mpp_y_scale, rotation_angle] = [1, 1, 45];

  // rotate target image with the known angle of 45°
  viewer3.viewport.setRotation(rotation_angle);

  // Original image coordinates
  let bounds = viewer1.viewport.getBounds(true);
  let imageRect = viewer1.viewport.viewportToImageRectangle(bounds);

  // transform original (white dog) coordinates affine to target image (red dog)
  let [xmin_trans, ymin_trans] = TransformAffine(imageRect.x, imageRect.y);

  // Transform target image coordinates to target image (red dog) viewport
  const vpRect = viewer3.viewport.imageToViewportRectangle(
    new OpenSeadragon.Rect(
      xmin_trans,
      ymin_trans,
      imageRect.width * mpp_x_scale,
      imageRect.height * mpp_y_scale,
      rotation_angle
    )
  );

  // Set target image viewport
  viewer3.viewport.fitBoundsWithConstraints(vpRect);
};

```

Even with the correct image coordinate transformation, I cannot bring the two images in sync. If someone has an idea, I would be very grateful.

With kind regards,
Christian

**Comment by ChristianMarzahl** [comment]
Hi,

I was able to solve the issue by rotating the viewport with setRotation Clockwise:
```js
 // rotate target image with the known angle of 45°
 viewer3.viewport.setRotation(rotation_angle);
```

and the imageToViewportRectangle counter clockwise.
```js
// Transform target image coordinates to target image (red dog) viewport
 const vpRect = viewer3.viewport.imageToViewportRectangle(
   new OpenSeadragon.Rect(
     xmin_trans,
     ymin_trans,
     imageRect.width * mpp_x_scale,
     imageRect.height * mpp_y_scale,
     -rotation_angle  // invert angle to make it work
   )
 );
```

With kind regards,
Christian

**Comment by iangilman** [comment]
@ChristianMarzahl great! Thank you for sharing the solution you found :)
