### ISSUE TITLE
Fix Ben Vanik links in the wiki

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#2083]
On https://github.com/openseadragon/openseadragon/wiki/The-DZI-File-Format there are a number of links at the bottom  to his Tumblr which doesn't exist anymore. We should grab the archive.org links and replace the broken ones. Here's a starting point:

https://web.archive.org/web/20180128073203/http://benvanik.tumblr.com/post/13883153608/high-res-zooming-images-are-easy

**Comment by shyamkumaryadav** [comment]
Can i replace it broken url to archive.org url ?

**Comment by iangilman** [comment]
@shyamkumaryadav thank you for offering, but @Amit-Tomar has already taken care of it :-)
