### ISSUE TITLE
Add Simple Image on http request

### ISSUE THREAD

**Issue by liekeheijne** [openseadragon/openseadragon#2086]
Hi, first time openSeadragon user here, so still struggeling a bit.

I have an image with an overlay svg.
The image is static and loaded via http request. 
OpenSeadragon is initialized like this:
```
viewer= OpenSeadragon({
    id: "example-xmlhttprequest-for-info-json",
    prefixUrl: "https://static.zoomhub.net/openseadragon-images/",
  
    tileSources: {
    //   static image
      type: "image",
      url: "",
      buildPyramid: false,
      overlays: [
        {
          id: "svg-overlay-1",
          x: 0,
          y: 0,
          width: 1,
          height: 1
        },
      ]
    },
});
```

When I click on a button I do a new http request to the server and get a new image. On page load I don't know the image yet, that is why the url is empty in the initialization.

After the api call is done I get the link to the image and set it like this: 
`viewer.addSimpleImage({'url': newImageUrl}).`

The problem is that the image is nog visible on the screen. I only see the svg overlay but not the image.
Could anybody help in what I am doing wrong?

**Comment by liekeheijne** [comment]
Sorry for my late response. I couldn't find the time to work on this project.

I am now destroying the viewer and initializing a new one. Some options may have changes in de api call, that's why I destroy it.

But, the overlay with the svg in it is not visible. It is in the DOM and is updating on zoom and pan but is is not displayed. It is only visible the first time
hope this short video helps:
https://gyazo.com/7901428e1cd98bcffe794e577fbeff4a

**Comment by iangilman** [comment]
Hmm, I'm not sure why they wouldn't be visible. If this is still happening, could you share a repro of it so I could look at the code?
