### ISSUE TITLE
imageToViewportRectangle not working as expected

### ISSUE THREAD

**Issue by gregster7** [openseadragon/openseadragon#2089]
I am using OpenSeadragon to view an image and crop regions from it. The cropped regions are stored in a database using their image coordinates (in pixels). I want the cropped images to appear when I reopen the page. 

I can add the overlay if I do the following

```
var overlayElement = document.createElement('div');
overlayElement.id = 'region_box_' + String(region_num);
overlayElement.style.border = "4px solid green";
var rect = new OpenSeadragon.Rect({{region.x}}/viewer.source.width;, {{region.y}}/ viewer.source.height, {{region.width}}/viewer.source.width;, {{region.height}}/viewer.source.height)

viewer.addOverlay(overlayElement, rect);
```

Is there a better way to do this? I had expected this to work, but it does not transform the coordinates at all so I must be using it incorrectly:
`rect = viewer.viewport.imageToViewportRectangle({{region.x}}, {{region.y}}, {{region.width}}, {{region.height}})`

**Comment by shyamkumaryadav** [comment]
may be this help [http://openseadragon.github.io/examples/ui-tiledimage-polygon-cropping/](http://openseadragon.github.io/examples/ui-tiledimage-polygon-cropping/)

```javascript
const x1 = region.x , y1 = region.y
const x2 = region.x + region.width , y2 = region.y + region.height
var examples = [
  [ { x: x1, y: y1 }, { x: x2, y: y1 }, { x: x2, y: y2 }, { x: x1, y: y2 } ]
]
var tiledImage = viewer.world.getItemAt(0);
tiledImage.setCroppingPolygons(examples);
viewer.forceRedraw();
```

**Comment by gregster7** [comment]
That is very interesting - thank you for sharing. I am not currently cropping, but useful to know.

On a related note, viewer.source is null and errors when I view my page in Firefox, but it works in Safari. 

Oddly, on some deep zoom images, the boxes are the in the correct position, but for others they are not. Is there a better way to convert from image coordinates to viewer coordinates?

**Comment by shyamkumaryadav** [comment]
I think you looking for how we convert image coordinate system to OpenSeadragon viewer coordinate system [imageToViewportCoordinates](https://openseadragon.github.io/docs/OpenSeadragon.Viewport.html#imageToViewportCoordinates)

**Comment by gregster7** [comment]
You are completely right. I was trying to use imageToViewportCoordinates the other day and it wasn't working, but now I suspect I just had a typo :)

**Comment by shyamkumaryadav** [comment]
Happy to know that you resolve the issue!

**Comment by gregster7** [comment]
Correction, the problem is stranger than I thought. The code works in Safari and Chrome, but in Firefox, imageToViewportRectangle and imageToViewportCoordinates just return the values that are passed in (the image coordinates). On top of that, viewer.source is null in Firefox as well. I'm wondering if this has something to do with the viewer not being loaded when the code is executed (I seem to remember an issue like this existing in the past). However, to avoid this, the viewer is loaded first, and then all my calls to it regarding coordinates and adding blocks are in a $(document).ready() block.

**Comment by iangilman** [comment]
Yeah, you'll definitely want to make sure the image is loaded. Put it inside a `viewer.addHandler('open', function() { ... })`.

**Comment by gregster7** [comment]
> Yeah, you'll definitely want to make sure the image is loaded. Put it inside a `viewer.addHandler('open', function() { ... })`.

That fixed it - thanks!
