### ISSUE TITLE
Custom toolbar takes all the canvas width on full page mode

### ISSUE THREAD

**Issue by fr75** [openseadragon/openseadragon#2090]
Hi,
In full screen mode, when using the default toolbar, the image goes behind the toolbar, which is fine.

But if defining a custom toolbar, in full screen, the toolbar takes all the width of the canvas.
You can test the example : https://openseadragon.github.io/examples/ui-toolbar/

I have tested a kind of 
// css
#toolbarDiv.fullpage {
        position: absolute !important;
}
but with position absolute, the controls cannot be reached. Mouse controls only the position and zoom of the image.
Is there a way to improve the custom toolbar ?
It is annoying when  many controls  ( input type="range") take all the place on a mobile phone screen.

Thanks a lot

**Comment by shyamkumaryadav** [comment]
I have used custom toolbar using `viewer.addControl()`. It has all the functionality like fade in/out.
```javascript
viewer.addControl(
      document.getElementById('toolbarDiv'),
      {
        anchor: OpenSeadragon.ControlAnchor.TOP_LEFT
      }
    )
```

**Comment by fr75** [comment]
Thank you, 
that seems to be the right way !
The image goes behind the toolbar,  like in default button mode.

Fade in/out does not work in full screen mode on desktop computer because the mouse cannot leave the canvas. It works on mobile phone.
I will see if I can implement an entry in fade-in when the mouse does not move for a time.
