### ISSUE TITLE
Adding markers on button toggle event.

### ISSUE THREAD

**Issue by mohitks77** [openseadragon/openseadragon#2091]
I am adding markers on openseadragon viewer. This is the function I am using for this:

`if (cellLabeler) {
   if (!viewer) return;
   console.log("calling celllabel", cellLabeler);

   viewer.addHandler("canvas-click", function (event) {
   const viewerPoint = viewer.viewport.pointFromPixel(event.position);
   console.log("Clicking coordinates:", viewerPoint.x, viewerPoint.y);

   var img = document.createElement("img");
   img.src = { logo };
   viewer.addOverlay(img, viewerPoint);
});}`

Celllabeler is a state variable I am using for toggling modes for adding markers. There is a button which toggles celllabeler state variable. It works when celllabeler is true, but it also works if I toggle it to false after labelling. Is this an issue with addHandler event that I am using?

**Comment by shyamkumaryadav** [comment]
Hay @mohitks77, The code you wrote is not correct. May be you try the below code.

```javascript
viewer.addHandler("canvas-click", function (event) {
  if (cellLabeler) {
    if (!viewer) return;
    console.log("calling celllabel", cellLabeler);
    // no need to convert your points into pixel add Overlay using viewport coordinate system
    const viewerPoint = event.position;
    console.log("Clicking coordinates:", viewerPoint.x, viewerPoint.y);

    var img = document.createElement("img");
    img.src = "https://dummyimage.com/600x400/000/fff";
    viewer.addOverlay(img, viewerPoint);
  }
});

```

**Comment by mohitks77** [comment]
Thanks for help @shyamkumaryadav. However the code you have provided breaks my viewer. Apparently I have to first check if my viewer contains any image or not and then go into addHandler event.

**Comment by iangilman** [comment]
@mohitks77 what makes you think you need a check if the viewer contains an image? Are you getting an error? 

Also, as discussed in https://stackoverflow.com/questions/70768731/adding-markers-in-openseadragon-viewer-even-if-state-variable-is-false/70776590 you need to just call `addHandler` once. That would probably be right after creating the viewer.
