### ISSUE TITLE
MouseTracker and corner-case scenarios

### ISSUE THREAD

**Issue by Aiosa** [openseadragon/openseadragon#2094]
I was having trouble with `fabricJS` plugin over OSD. Once I've started developing an advanced application and registered more event listeners (mostly on overlay canvases), it so happened that with a key-based app behavior mode control (hit Shift to draw...) that obviously used a lot `setMouseNavEnabled(...)`, `MouseTracker` started giving me 'event on untracked pointer' warnings that meant the next click on a canvas was being ignored (served as some sort of 'reset' action). I am still unsure about the cause (happened mainly only when key down/up handlers took action), but I've found the solution (along with a bug inside OSD). In the end, it's better when OSD is more robust and recovers from untracked pointers since in advanced applications it can happen very quickly that the mouse gets tracked in various states (coming in from other browser windows/tabs, being enabled by a key -e.g. `Shift`- while held down, etc.).

### The bug
Following the warnings (and one error) from my application, I found out that if 
https://github.com/openseadragon/openseadragon/blob/055699a00aeae886582a3e7f9db2f9f2edf83809/src/mousetracker.js#L3421
is not found, 
https://github.com/openseadragon/openseadragon/blob/055699a00aeae886582a3e7f9db2f9f2edf83809/src/mousetracker.js#L3440
is never executed and
https://github.com/openseadragon/openseadragon/blob/055699a00aeae886582a3e7f9db2f9f2edf83809/src/mousetracker.js#L3365
remains false since
https://github.com/openseadragon/openseadragon/blob/055699a00aeae886582a3e7f9db2f9f2edf83809/src/mousetracker.js#L3423
evaluates to false. Then, 
https://github.com/openseadragon/openseadragon/blob/055699a00aeae886582a3e7f9db2f9f2edf83809/src/mousetracker.js#L3563
branch is taken and possibly
https://github.com/openseadragon/openseadragon/blob/055699a00aeae886582a3e7f9db2f9f2edf83809/src/mousetracker.js#L3574
line executed, using an undefined parameter `releasePoint`

### The fix (bug + behavior described above)
I am not sure why this comment
https://github.com/openseadragon/openseadragon/blob/055699a00aeae886582a3e7f9db2f9f2edf83809/src/mousetracker.js#L3443
should be true, so I propose:

- remove warn, because we are able to recover, and it only bloats the console https://github.com/openseadragon/openseadragon/blob/055699a00aeae886582a3e7f9db2f9f2edf83809/src/mousetracker.js#L3293
- remove `return` statement since we artificially started tracking, why not complete the process? https://github.com/openseadragon/openseadragon/blob/055699a00aeae886582a3e7f9db2f9f2edf83809/src/mousetracker.js#L3299
- remove warn, because we are also able to recover from this situation, and it only bloats the console https://github.com/openseadragon/openseadragon/blob/055699a00aeae886582a3e7f9db2f9f2edf83809/src/mousetracker.js#L3443
- use `if ( tracker.releaseHandler && releasePoint )` to avoid the bug described above https://github.com/openseadragon/openseadragon/blob/055699a00aeae886582a3e7f9db2f9f2edf83809/src/mousetracker.js#L3467

After that, no matter when I enable `MouseTracking`, the OSD adapts immediately. I am aware that there might be also other cases where it fails to recover with a similar code design, I provided only steps I made in order to get my app flawless controls...

**Comment by iangilman** [comment]
Thank you for tracking this down! You've documented the issue beautifully :) 

Would you be up for making a pull request with your proposed fix?

**Comment by Aiosa** [comment]
The bug is indeed worth fixing, however, I am not sure whether I should also include my other updates... I still feel like those comments/warns were there for some reason, although I still fail to see it. But I will happily do it since these changes are rather important to me for UI friendliness...

**Comment by iangilman** [comment]
The comments are probably fine, though you might update them to reflect the new reality. Maybe the warns can be turned into similar comments? 

Thank you for taking this on! Let me know if you need any info :)

**Comment by iangilman** [comment]
Fixed by #2134.
