### ISSUE TITLE
Disabling navImages

### ISSUE THREAD

**Issue by edsilv** [openseadragon/openseadragon#210]
I'm not displaying any of the default zoomin/out etc buttons:

viewer.clearControls();
viewer.setControlsEnabled(false);

Except it's still trying to load the images, which results in a bunch of 404s.

Is there a way to overload options.navImages so that these aren't used?

**Comment by leesei** [comment]
I suppose this can be closed.

**Comment by iangilman** [comment]
@leesei Good catch, thank you!
