### ISSUE TITLE
fill image to object fit in container

### ISSUE THREAD

**Issue by liekeheijne** [openseadragon/openseadragon#2102]
Hi, I want to have an openseadragon container with a height of 90vh. 
When i set the height in css this is working fine.

However, I want my image to fill up the space. I think it needs zo zoom in to achieve this.
Is there an easy way to do this?

![image](https://user-images.githubusercontent.com/25478858/152512838-caa7d895-d85f-43ec-8067-25a91ba2c134.png)

**Comment by iangilman** [comment]
@shyamkumaryadav Those are some good ideas, but actually we do have a feature for this... @liekeheijne Try using `homeFillsViewer: true` in your Viewer options.
