### ISSUE TITLE
addOverlay Not Working With Pixels (px and py)

### ISSUE THREAD

**Issue by AnderSco01** [openseadragon/openseadragon#2104]
Hi, hope you're well. I'm having an issue with applying dynamic overlays to my viewer.

After initialising my viewer, I'm trying to add overlays via viewer.addOverlay, but the icons I'm using are in the completely wrong spot, so much so they go off the screen.

If I use the overlays property when first creating the viewer it works fine and positions accordingly. But as soon as I try using them with viewer.addOverlay, it's completely wrong.

Is addOverlay not compatible with pixel positioning properties, px and py? Or does it need a slightly different configuration to the overlays property when the viewer is first made?

Here is my code, when first generating the viewer, and my attempt at using addOverlay:

    const viewer = OpenSeaDragon({
      id: "openSeaDragon",
      maxZoomPixelRatio: 20,
      gestureSettingsMouse: {
        clickToZoom: false
      },
      tileSources: {
        url: imageURL,
        type: 'image'
      },
    });
    
    viewer.addOverlay({
      "id": "11499",
      "px": 342.777777778,
      "py": 348.888888889,
      "placement": "RIGHT",
      "checkResize": false
    });

Any help would be most appreciated. Thanks!

**Comment by shyamkumaryadav** [comment]
As mentioned on doc [addOverlay](http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#addOverlay) Adds an html element to the current viewport as an overlay.

We have three coordinate systems that you find on the 
 [Coordinates](https://openseadragon.github.io/examples/viewport-coordinates/) Page.

it looks like you are using wrong code to add overlay if you are looking for how to add overlay here we have an [example](https://openseadragon.github.io/examples/ui-overlays/)

**Comment by iangilman** [comment]
@AnderSco01 I suspect this is a timing issue. By using `px` you are wanting to lay things out based on the image coordinates, but that's not possible immediately after creating the viewer because the image hasn't been loaded yet. Try putting your `addOverlay` call inside a `viewer.addHandler('open', function() { ... })`.
