### ISSUE TITLE
OpenSeaDragon Is Undefined When Using Rect

### ISSUE THREAD

**Issue by AnderSco01** [openseadragon/openseadragon#2106]
Hello, hope you are well. I'm trying to use addOverlay but OpenSeaDragon keeps coming up as undefined when trying to use it in any other manner except for first generating the viewer. I'm trying the same code as in the documentation:

var overlay = false;
document.querySelector('#toggle-overlay').addEventListener('click', function() {
    if (overlay) {
        viewer.removeOverlay("runtime-overlay");
    } else {
        var elt = document.createElement("div");
        elt.id = "runtime-overlay";
        elt.className = "highlight";
        viewer.addOverlay({
            element: elt,
            location: new OpenSeadragon.Rect(0.33, 0.75, 0.2, 0.25)
        });
    }
    overlay = !overlay;
});

Any help would be most appreciated. Thanks!

**Comment by shyamkumaryadav** [comment]
may be you forget to link OpenSeadragon javascript file inside head tag?

Or can you paste the error here !
