### ISSUE TITLE
Flat icons for Openseadragon

### ISSUE THREAD

**Issue by Benomrans** [openseadragon/openseadragon#2114]
Hello everyone,
Have made icons for openseadragon with a simple flat design in PNGs, (based on Tom Brossman's recently updated svg icons at : https://gitlab.com/tombrossman/openseadragon-svg-icons/)
Perhaps they would be used by others as well.

Links :

https://github.com/Benomrans/openseadragon-icons
https://cdn.jsdelivr.net/gh/Benomrans/openseadragon-icons@main/images/
https://cdn.jsdelivr.net/gh/Benomrans/openseadragon-icons@main/images.zip

Sample : 
![sample](https://user-images.githubusercontent.com/75787532/154521956-b4bec3f1-044e-4f52-8b19-c11308d7ec46.png)

@iangilman

**Comment by iangilman** [comment]
@Benomrans These are great! How would you feel about adding them to the official list on http://openseadragon.github.io/#plugins (under the Icon Packs section)?

**Comment by iangilman** [comment]
@Benomrans Great! Would you be up for adding the link? It's in a different project... Here's the place: 

https://github.com/openseadragon/site-build/blob/6a29c0043b222f58f60b7ef1e5f461bab6ef4f0f/www/index.html#L206

If you make a pull request against that file, I'll merge and deploy it :)

**Comment by Benomrans** [comment]
Well, I'm just an old history teacher, almost an hour passed and I couldn't figure out the pull request maze :) . Would need much extra time to learn. (help is needed here) , or maybe just add the link to the plugins section skipping all other steps?.

**Comment by iangilman** [comment]
@Benomrans Sure, I can take care of it, but I like to give people the chance to do it themselves if they are up for it. I don't mind helping you through the process if you want! Here's some starter info: 

https://github.com/openseadragon/openseadragon/wiki/Making-a-Pull-Request

**Comment by iangilman** [comment]
@Benomrans Okay, I've added them to the icon packs area. Here's the pull request, in case you're curious: 

https://github.com/openseadragon/site-build/pull/255

Thank you again for sharing these! 

BTW, it's great that you have provided jsdelivr links... Is that just automatic these days? Anyway, you might add that info to your readme at https://github.com/Benomrans/openseadragon-icons so anyone can find it when they go there.

**Comment by Benomrans** [comment]
@iangilman 
Thank you so much indeed. (Sorry, got so busy with the finals, couldn't find time to learn!. Next time will do it myself, promise.)
