### ISSUE TITLE
 [question] load tile with delay

### ISSUE THREAD

**Issue by supbg1** [openseadragon/openseadragon#2122]
Hi, 
Sorry for bad english and question, using this first time. I am trying to use this to watch our school's microscope website. It was built with old flash zoomify server, so I use openseadragon as frontend to get the data from it. The original viewer is also flash too, which is really inconvenient.
So Is there a way to slow down the request  of tile source? The viewer seems to load lots of tile simultaneously, and our school's server cannot handle so many request at the same time.(I don't know if it's because it look like ddos or just too many task for potato server) Is it possible to request new tile after the previous tile loaded instead of loading them at same time? 
Thanks.

**Comment by shyamkumaryadav** [comment]
@supbg1 You can set this option on Viewer [imageLoaderlimit](https://openseadragon.github.io/docs/openseadragon.js.html#line301) to `1`

> Which set The maximum number of image requests to make concurrently. By default it is set to 0 allowing the browser to make the maximum number of image requests in parallel as allowed by the browsers policy.

```javascript
var viewer = OpenSeadragon({
  id: "openseadragon1",
  prefixUrl: "/openseadragon/images/",
  tileSources: "/path/to/my/image.dzi",
  // Allows the browser to request only one image at a time
  imageLoaderlimit: 1
});
```

**Comment by supbg1** [comment]
oh wow, thanks!
I thought  it means  loading one whole picture in a collection instead of a tile. Thanks for your help!
