### ISSUE TITLE
How to distinguish between mouse drag and mouse click?

### ISSUE THREAD

**Issue by ChunxuYang** [openseadragon/openseadragon#2131]
I was trying to add a MouseTracker on a overlay. When setting MouseTracker as below, dragging on the overlay does't cause the whole slide to move around. Instead, the clickHandler is fired. 

```typescript 
new OpenSeadragon.MouseTracker({
    element: elt,
    clickHandler: function (_event: any) {
      console.log("clicked");
    },
  });
```

Specifically, the mouseup action triggers the clickHandler. How can I detect click while preserving the default dragging event? Thanks.

**Comment by shyamkumaryadav** [comment]
As i think you can use [viewer.setMouseNavEnabled(false)](https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#setMouseNavEnabled)

it's make viewer drag to false.

**Comment by iangilman** [comment]
@ChunxuYang The `clickHandler`'s `event` has a `quick` property that is `true` when it's fired on a click rather than the end of a drag. Is that the information you're looking for, or is there more you're trying to do?

**Comment by ChunxuYang** [comment]
> u

@iangilman That's exactly what I need, thx a lot!
