### ISSUE TITLE
SVG-Overlay plugin in React

### ISSUE THREAD

**Issue by gerstej9** [openseadragon/openseadragon#2171]
Hi, 
I am able to successfully use the svg-overlay plugin when working with a vanilla js prototype of what I am attempting to accomplish but when I try to import or utilize the svg-overlay plugin within my React application I am unable to get it to work. I came across  this issue https://github.com/openseadragon/svg-overlay/issues/34 and have been attempting to replicate the solution with no luck. Any suggestions or help you could provide would be greatly appreciated! Thank you!

**Comment by iangilman** [comment]
I've replied in https://github.com/openseadragon/svg-overlay/issues/34, but anyone else who has thoughts, please chime in!

**Comment by gerstej9** [comment]
Thank you for replying in the svg-overlay thread, apologies I meant to open this issue in that repo.
