### ISSUE TITLE
Use `navigatorElement` for Viewer and id-overwrite bug

### ISSUE THREAD

**Issue by joedf** [openseadragon/openseadragon#2174]
As mentioned [here](https://github.com/openseadragon/openseadragon/pull/2166#issuecomment-1154444096), The Viewer needs to be updated so we can use `navigatorElement` as an option. Currently, it is using `navigatorId` when the viewer is created.
https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L434

**Comment by iangilman** [comment]
Closed by #2175.
