### ISSUE TITLE
Toolbar Icons from URL

### ISSUE THREAD

**Issue by gerstej9** [openseadragon/openseadragon#2179]
Hey @iangilman hope all is well, is it possible to have the toolbar icons like 'zoom in' be sourced from a url as opposed to an images folder? I'm hoping to pull the icons from a url to an S3 bucket, for instance, as opposed to a local or server path to the images but not having any luck. I've seen a few people create custom toolbar divs when working in html but I'm not sure how that would work in React and if possible would love to just change the src on the images of the icons. Thanks in advance!

**Comment by iangilman** [comment]
Nice :)
