### ISSUE TITLE
getTileHashKey error when using the ImageTileSource 

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#2188]
I received this report on Discord:

> Hi, I'm trying to add a simple `image viewer.open({ type: "image", url})` but keep getting this error:
> `Tile constructor needs 'cacheKey' variable: creation tile cache in Tile class is deprecated. TileSource.prototype.getTileHashKey will be used.`
> I can see the same error on this example:
> https://openseadragon.github.io/examples/tilesource-image/

@Aiosa I believe this was introduced as part of https://github.com/openseadragon/openseadragon/pull/2138. Would you be up for addressing this? I figure all of our internal tile sources, including the ImageTileSource, should provide a `cacheKey`. 

Also, while we're in there, I think it would be good to change that error message to a `console.warn`, since it's not truly an error.

**Comment by Aiosa** [comment]
Yes, will fix this. Thank you for the report.

**Comment by Aiosa** [comment]
Though I do not understand how this can happen unless there's a custom tile source that returns undefined on the cache generation. `getTileHashKey ` is probably not somewhere implemented and returns `undefined`, inline configuration probably does not define the function - will add.

**Comment by Aiosa** [comment]
Can be closed I believe.

**Comment by iangilman** [comment]
Fixed by #2190.
