### ISSUE TITLE
Consolidate viewer keyboard handling into keydown handler

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#2191]
We have some of our standard keys hooked up via keydown and others via keypress. It might be good to sort that out at some point as well. I think we should stick with keydown for all of them.

**Comment by hrghauri** [comment]
Hi @iangilman , I would like to tackle this one.

I understand the idea is to roughly move code from keypress handler https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2828-L2909 
and place it somewhere here https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2793 under keydown handler whilst respecting the new keycodes of the keydown event.

I just need a bit of clarity where there are 2 keycodes involved triggering some event. For instance, https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2828-L2829 in keypress event, the codes are 43 and 61. However, I do understand that (=|+) keystroke - 61 of keypress is  187 in keydown . So I can move it there but I do not understand what would 43 corresponds to?

**Comment by iangilman** [comment]
Great! Yes, that's the idea. 

And, good point on the keycodes... There will need to be some translation done. Basically, I guess, just make sure that hitting both `+` and `=` fires the zoom in. 

As for keycode 43, I have no idea! According to https://www.toptal.com/developers/keycode/table-of-all-keycodes, it's "execute"... I'm guessing it's just a mistake of some sort. The key thing is to keep an eye on the comments, which specify what the intended key is. 

One thing I'm not sure about, is how different keyboard layouts might affect this stuff. Do you know anything about that? 

Thank you for digging into this!

**Comment by hrghauri** [comment]
Thanks for your response!

Yes, 43 keycode seems like a mystery to me right now, but I will definitely keep an eye on the comments as well as thoroughly test each keycode event after moving it to the new place.

As of now, I do know much about different keyboard layouts too. I'll try to keep that in consideration while patching this up.

FYI, I'm currently looking at these for reference:
https://unixpapa.com/js/key.html
https://www.quirksmode.org/js/keys.html

**Comment by iangilman** [comment]
Great... That's all we can ask!

**Comment by MohitBansal321** [comment]
Is this issue resolved

**Comment by iangilman** [comment]
I believe @hrghauri is still working on it... How is it going, @hrghauri ?

**Comment by MohitBansal321** [comment]
okay @iangilman  if is it not resolve ping me we will discuss and i do pr

**Comment by hrghauri** [comment]
Unfotunately, I may not be able to complete it for sometime. @MohitBansal321  please feel free to go ahead on this one.

**Comment by MohitBansal321** [comment]
so i think we need to change some codes and which you are mention here too

> Hi @iangilman , I would like to tackle this one.
> 
> I understand the idea is to roughly move codeblock from keypress handler https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2828-L2909 and place it somewhere here https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2793 under keydown handler whilst respecting the new keycodes of the keydown event.
> 
> I just need a bit of clarity where there are 2 keycodes involved triggering some event. For example, https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2828-L2829 in keypress event, the codes are 43 and 61. However, I do understand that (=|+) keystroke - 61 of keypress is 187 in keydown . So I can move it there but I do not understand what would 43 corresponds to?

**Comment by MohitBansal321** [comment]
I thought I need to cut cases of keypress to move to keydown cases
and remove all the  stuff of keypress is it right approach if yes let me know

**Comment by MohitBansal321** [comment]
@iangilman  I will change to combine keyhandler to keydown
  let me know where i mistook it does not pass all the checks

**Comment by MohitBansal321** [comment]
@iangilman now my commit working well can you checkout it 
if changes needed let me know
