### ISSUE TITLE
npm install gets stuck

### ISSUE THREAD

**Issue by Aiosa** [openseadragon/openseadragon#2194]
`npm install` keeps pending on `pupeteer` dependency. I've tried two different independent machines (macOS and Windows), two internet connections, two versions of npm/node (8.11.0/16.16.0 and 8.15.0/18.7.0). Not once I've been successful in installing all the dependencies.

> npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
> npm WARN deprecated puppeteer@5.5.0: Version no longer supported. Upgrade to @latest
> (##################) ⠴ reify:lodash: timing metavuln:cache:get:security-advisory:qunitjs:….    <-- hangs here

So I end up killing it CtrlC:
> npm info run puppeteer@5.5.0 install { code: null, signal: 'SIGINT' }

Tried clearing cache, node_modules, package-lock.json... 
Since I have no problems with my old machines, all has been performed on new OSs with new npm install, I think the new version of npm could be the case.

**Comment by Aiosa** [comment]
OK nevermind.  I spent the whole day trying out different versions and found out that my internet is slow - pupeteer downloads a lot of data (chromium engine) and newer versions of `nom` do not show download progress bar anymore - a mistake IMHO. Anyway, although the console (even the loading ascii animation) looks lagged, I just had to wait for more than 15 minutes for the engine to download.

**Comment by iangilman** [comment]
Good to know!
