### ISSUE TITLE
clicking on Navigator causes Viewport to zoom

### ISSUE THREAD

**Issue by GRSuggitt** [openseadragon/openseadragon#2202]
If my image is zoomed to the point where it fills the viewport, clicking on the Navigator works as expected.

However, if I have zoomed out so that the images is less than the viewport, clicking on the Navigator causes the viewport to zoom from its current size to almost filling the Viewport at the end of the animation.

For example, my current zoom is 0.24665939374432364

When I click on the Navigator I first get an "animate-start" event followed by an "animation" event
On each "animation" event I call getZoom(true) and getZoom(false)
On the first "animation" event, the current zoom is 0.24665939374432364 and the target zoom is 0.24665939374432364
(all good so far)

Then I get a "zoom" event with "immediately" undefined and a value of 0.730681067165689

A series of "animation" events follow, the current and target zooms are as follows:

```
0.356769535723414        0.730681067165689
0.43277752052818863      0.730681067165689
0.49557292724960134      0.730681067165689
0.5758611692829617       0.730681067165689
0.6174957282360439       0.730681067165689
0.6670779609377104       0.730681067165689
0.6994278251095688       0.730681067165689
0.7194902451789433       0.730681067165689
0.730681067165689        0.730681067165689
```

Of course, I don't expect any zooming to occur.

**Comment by iangilman** [comment]
How are you telling the viewer that it's okay to zoom out that much? Are you zooming out there via the UI or programmatically? If you haven't loosened the constraints on zooming and you programmatically zoom outside of those constraints, then when you interact with the navigator, it will force you back inside the constraints. 

I tested by including `minZoomImageRatio: 0` in my viewer options, and I'm not getting any unwanted zooming.

**Comment by GRSuggitt** [comment]
Yes, I was zooming programmatically so I went beyond the limits. I have added limit checking and all is well now

**Comment by iangilman** [comment]
Great, good to know!
