### ISSUE TITLE
Is there a way to make the viewer non accelerative?

### ISSUE THREAD

**Issue by Victoriam7** [openseadragon/openseadragon#2204]
I'm trying to prevent the viewer from continuing to zoom after I release the scroll wheel. As it is, the zoom feels floaty. I have the same question for panning as well. Is there a way to disable acceleration?

**Comment by pearcetm** [comment]
You can try changing the `animationTime` property on the viewer to `0`. Would that achieve the effect you're looking for?

**Comment by Victoriam7** [comment]
That worked. Thank you!
