### ISSUE TITLE
How to zoom in or out to a specified multiple

### ISSUE THREAD

**Issue by Loverz55** [openseadragon/openseadragon#2221]
How to zoom in and out to a specified multiple, such as clicking the button to set 10x

**Comment by Loverz55** [comment]
Sorry, I didn't find the API before I saw it hhh

**Comment by Loverz55** [comment]
I haven't seen it for a long time. Then I asked questions and went to find it

**Comment by iangilman** [comment]
So you found the answer, or you still need help?
