### ISSUE TITLE
Deprecation warning 'Viewer.buttons' - potentially dangerous implementation of OpenSeadragon.extend

### ISSUE THREAD

**Issue by Aiosa** [openseadragon/openseadragon#2226]
Some of the recent updates deprecated `get buttons()` method of `Viewer` class. I ignored this warning for some time but now I wanted to get rid of it and found out it's bundled :) 

In essence, `get` is treated as a property rather than function, so the manual implementation of `OpenSeadragon.extend` copies it over as a property, i.e. invoking the method at line
https://github.com/openseadragon/openseadragon/blob/ed66c2d1518e919dffa335e68c34f469607273b3/src/viewer.js#L489

Don't have time to fix it RN but leaving the description here for someone who can.

**Comment by Aiosa** [comment]
Note that this might actually be more complex issue than it seems, consider the following

```
OpenSeadragon.X = function (condition) {
     this.condition = true;
};
OpenSeadragon.X.prototype = {
    get input() {
         if (this.condition) {
             return "value";
         }
         return {some: "value"};
    }
}

OpenSeadragon.ChildX = function (condition) {
     //should also extend the constructor but for simplicity...
     this.condition = true;
};
OpenSeadragon.extend(OpenSeadragon.X.prototype, OpenSeadragon.ChildX.prototype, {
   // implement more stuff
});

//what does output
console.log(new OpenSeadragon.X(true).input); 
console.log(new OpenSeadragon.ChildX(true).input); 
```
I did not test this code but since our `get / set` methods get invoked in `OpenSeadragon.extend` my guess is the first line will output `"value"` while the second `"{some: "value"}"` since at the time of cloning, `this.condition` was undefined and thus evaluated to false, `OpenSeadragon.ChildX.input` is the actual object returned, not a `get` getter...

**Comment by pearcetm** [comment]
Is this an issue caused by the recent PR https://github.com/openseadragon/openseadragon/pull/2201? Or is it the same issue, and potentially fixed by that PR?

**Comment by Aiosa** [comment]
@pearcetm thanks looks like that's it. Closing.
