### ISSUE TITLE
Smooth transition between sources

### ISSUE THREAD

**Issue by spedemon** [openseadragon/openseadragon#223]
When displaying multiple images, e.g. with the reference strip enabled, the transition between images is abrupt. I am trying to figure out how to animate the transition from one image to the other, so that when the new image is selected (with the reference strip or the 'next' button), the old image fades out and the new one fades in. Any ideas of how to do this?

**Comment by iangilman** [comment]
Starting with OpenSeadragon 2.0.0 this is not possible to build. See https://github.com/openseadragon/openseadragon/issues/687
