### ISSUE TITLE
Deploy 4.0.0

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#2236]
It's getting to be about that time!

**Comment by SMA-cgn** [comment]
Hi, do you have any rough estimate when 3.2 will be available. Thanks a lot!

**Comment by iangilman** [comment]
@SMA-cgn I expect to release it this week :)

**Comment by iangilman** [comment]
Though, it may depend on how https://github.com/openseadragon/openseadragon/pull/2239 goes... Since it fixes an issue with #2160, which was introduced in this milestone, it seems like it would be good to get the fix in before we release it.

**Comment by iangilman** [comment]
Almost ready... I've reached out to the IIIF community to see if anyone is up for reviewing #2206. One way or the other, we'll release next week!

**Comment by iangilman** [comment]
I'm hoping for some additional feedback from @AaronPlave on #2249. It would be nice to get that patch in before we release. 

Also, I'm starting to think we should call this new version 4.0.0, since it does have some new behaviors, and bumping the major version would be the right thing to do from a semantic versioning standpoint (not that we've been very diligent about that in the past).

**Comment by iangilman** [comment]
Okay, everything is set, so I'm deploying! We have enough changes in behavior that I'm going with 4.0.0 after all.

**Comment by iangilman** [comment]
And it's done! OpenSeadragon 4.0.0 is released! https://github.com/openseadragon/openseadragon/releases/tag/v4.0.0 Thank you to all the contributors!!

**Comment by iangilman** [comment]
@SMA-cgn 😊 Thank you for contributing to it! ❤️
