### ISSUE TITLE
Navigator display rectangle is off when the page has box-sizing: border-box

### ISSUE THREAD

**Issue by Aiosa** [openseadragon/openseadragon#2264]
I was trying to implement viewport tracking, and noticed my tracked positions are off. Further inspection led me to realize the OSD's implementation does not display the viewport correctly.

I shouldn't have modified the navigator in any way that would cause this, but I am not 100% sure.

What I am doing: 
````
        const size = 250;
        this.record = document.createElement("canvas");

        const homeBounds = VIEWER.viewport.getHomeBounds();
        homeBounds.width += 2*homeBounds.x; //consider setting 1 since it is computed to be 1 anyway
        homeBounds.height += 2*homeBounds.y;
        homeBounds.x = 0;
        homeBounds.y = 0;

        const w = size * homeBounds.width, h = size * homeBounds.height;
        this.record.width = w;
        this.record.height = h;
        this.recordCtx = this.record.getContext('2d');
        this.recordCtx.globalCompositeOperation = "lighten";

        ....

        VIEWER.addHandler("update-viewport", e => {
                const viewport = e.eventSource.viewport;

                ....

                const bounds = viewport.getBoundsNoRotate(true);
                _this.recordCtx.fillRect(size*bounds.x, size*bounds.y, size*bounds.width, size*bounds.height);
        });
````

(tissue blurred)
![image](https://user-images.githubusercontent.com/34658867/209953400-d9ba1716-68a8-42aa-b4e7-41c714b6e689.png)
If you look closer you can see that while the whole bottom part of the tissue is visible, the viewport position indicator is off. Note that the display is cut and the OSD renders behind the menu too, the reason the rectangle is so wide.

I tried loading just a single TiledImage with the same result.

What OSD is doing (for reference):

````
            bounds      = viewport.getBoundsNoRotate(true);
            topleft     = this.viewport.pixelFromPointNoRotate(bounds.getTopLeft(), false);
            bottomright = this.viewport.pixelFromPointNoRotate(bounds.getBottomRight(), false)
                .minus( this.totalBorderWidths );

            //update style for navigator-box
            var style = this.displayRegion.style;
            style.display = this.world.getItemCount() ? 'block' : 'none';

            style.top    = Math.round( topleft.y ) + 'px';
            style.left   = Math.round( topleft.x ) + 'px';

            var width = Math.abs( topleft.x - bottomright.x );
            var height = Math.abs( topleft.y - bottomright.y );
            // make sure width and height are non-negative so IE doesn't throw
            style.width  = Math.round( Math.max( width, 0 ) ) + 'px';
            style.height = Math.round( Math.max( height, 0 ) ) + 'px';
````
Any ideas? Thanks.

**Comment by pearcetm** [comment]
@Aiosa I just tried this with my setup, and also with https://openseadragon.github.io/examples/ui-viewport-navigator/

It seems to be working as I'd expect. The one thing I'm noticing, while looking closely, is that the bounds of the viewport correspond to the *outer* part of the red rectangle in the navigator, not the inside of the frame. Could that be what you're seeing, or is it more than that?

**Comment by Aiosa** [comment]
I tried vanilla OSD now and also seems fine. The problem seems to be in the rectangle _size_, the top left corner seem aligned correcntly. [I could include interactive example right away](https://rationai-vis.ics.muni.cz/visualization-demo/client/redirect.php#%7B%22params%22%3A%7B%22bypassCookies%22%3Atrue%2C%22viewport%22%3A%7B%22zoomLevel%22%3A2.075095810451122%2C%22point%22%3A%7B%22x%22%3A0.5307473691994286%2C%22y%22%3A1.4321936859387532%7D%7D%7D%2C%22meta%22%3A%7B%7D%2C%22data%22%3A%5B%22CancerDetection%2Ftissue.tif%22%2C%22CancerDetection%2Fannotation.tif%22%2C%22CancerDetection%2Fprobability.tif%22%2C%22CancerDetection%2Fexplainability.tif%22%5D%2C%22background%22%3A%5B%7B%22dataReference%22%3A0%7D%5D%2C%22visualizations%22%3A%5B%7B%22name%22%3A%22Automated%20cancer%20detection%22%2C%22shaders%22%3A%7B%22probability%22%3A%7B%22name%22%3A%22Probability%20Layer%22%2C%22type%22%3A%22heatmap%22%2C%22visible%22%3A1%2C%22dataReferences%22%3A%5B2%5D%2C%22params%22%3A%7B%22color%22%3A%22%23fff705%22%7D%2C%22cache%22%3A%7B%22heatmap%22%3A%7B%22color%22%3A%22%23bbff00%22%2C%22threshold%22%3A%2252%22%7D%7D%2C%22index%22%3A0%2C%22rendering%22%3Atrue%7D%2C%22explainability%22%3A%7B%22name%22%3A%22Explainability%20Layer%22%2C%22type%22%3A%22bipolar-heatmap%22%2C%22visible%22%3A1%2C%22dataReferences%22%3A%5B3%5D%2C%22params%22%3A%7B%7D%2C%22cache%22%3A%7B%22bipolar-heatmap%22%3A%7B%7D%7D%2C%22index%22%3A1%2C%22rendering%22%3Atrue%7D%2C%22annotation%22%3A%7B%22name%22%3A%22Annotation%20Layer%22%2C%22type%22%3A%22edge%22%2C%22visible%22%3A1%2C%22dataReferences%22%3A%5B1%5D%2C%22params%22%3A%7B%22color%22%3A%22%2300eeff%22%2C%22ctrlThreshold%22%3A0%7D%2C%22cache%22%3A%7B%22edge%22%3A%7B%7D%7D%2C%22index%22%3A2%2C%22rendering%22%3Atrue%7D%7D%2C%22params%22%3A%7B%7D%2C%22order%22%3A%5B%22probability%22%2C%22explainability%22%2C%22annotation%22%5D%7D%5D%2C%22shaderSources%22%3A%5B%5D%2C%22plugins%22%3A%7B%7D%2C%22dataPage%22%3A%7B%7D%7D)

**Comment by Aiosa** [comment]
Hmm, using `VIEWER.navigator.totalBorderWidths={x:0,y:0}` in console improved it almost fully....

**Comment by pearcetm** [comment]
Maybe the issue is that the top and left are rounded to the nearest pixel, while the width and height are computed from the original un-rounded values? Depending on how the sizes work for specific image and viewport dimensions, you could end up rounding down (or up) twice and throw off the bottom and right positions more for that reason? It might make more sense to round `topLeft` and `bottomRight` independently first, and then calculate `width` and `height` from there...

**Comment by pearcetm** [comment]
Aha! In your example, I disabled `box-sizing: border-box` in the CSS for the navigator panel (can be found with selector `#panel-navigator-displayregion.displayregion` (among others) ) and the bottom right positioning seems much better.

**Comment by Aiosa** [comment]
Wow, you're right. Thanks a lot! Hard to notice especially when assigned by third-party style bootstrap.

**Comment by pearcetm** [comment]
I feel like it might be worth considering how to make the indicator rectangle robust to external CSS like this. I can't imagine why it would be beneficial for a user to intentionally apply a different `box-sizing` model that makes it inaccurate, and it is highly likely to happen by accident like it did to you.

@iangilman Thoughts? Perhaps inline CSS defined on the element itself could be used to override any such changes made by an external stylesheet...

**Comment by iangilman** [comment]
@pearcetm Yes, good point! We should apply `box-sizing: content-box` to the navigator display region. I'll reopen this issue as an enhancement. @Aiosa Thanks for drawing attention to it!
