### ISSUE TITLE
Custom buttons are duplicating each other when nivigating between sequence pages

### ISSUE THREAD

**Issue by digounet** [openseadragon/openseadragon#2272]
I'm trying to add new custom buttons to the existing toolbar and also change the default icons for existing buttons. The problem is that when I'm navigating between sequences these buttons are duplicating each other.  Here is the code that I am using: 

`	var anno;
	var annoConfig;
	initImageCanvas();

	function initImageCanvas() {
		OpenSeadragon.setString("Tooltips.FullPage", "Mostrar imagem em tela cheia");
		OpenSeadragon.setString("Tooltips.Home", "Ajustar imagem");

		viewer = OpenSeadragon({
			id: "canvasImage",
			prefixUrl: "/openseadragon/images/",
			showNavigator: true,
			navigatorPosition: "BOTTOM_RIGHT",
			showZoomControl: false,
			showFullPageControl: false,
			showHomeControl: false,
			autoHideControls: false,
			navigatorBorderColor: '#000',
			maxZoomPixelRatio: 3, 
			minPixelRatio: 1,
			preserveOverlays: true,
			preserveViewport: false,
			preload: true,
			sequenceMode: true,
			nextButton: "nextImageButton",
			previousButton: "previousImageButton",
			tileSources: [
				{ type: 'image', url: 'put your image url' },
				{ type: 'image', url: 'put your image url' },
				{ type: 'image', url: 'put your image url' },
				{ type: 'image', url: 'put your image url' },
				{ type: 'image', url: 'put your image url' },
				{ type: 'image', url: 'put your image url' },
				{ type: 'image', url: 'put your image url' }
			]
		});

		//Desabilita zoom na imagem ao clicar com o mouse
		viewer.gestureSettingsMouse.clickToZoom = false;

		AddCustomButton(
			'open',
			Resources.SharedResource.Mostrar_imagem_em_tela_cheia,
			'/openseadragon/images/custom/fullscreen_rest.png',
			'/openseadragon/images/custom/fullscreen_rest.png',
			'/openseadragon/images/custom/fullscreen_hover.png',
			'/openseadragon/images/custom/fullscreen_pressed.png',
			function () { return SetFullScreen(isFullScreen); },
			OpenSeadragon.ControlAnchor.TOP_RIGHT
		);

		AddCustomButton(
			'open',
			Resources.SharedResource.Ajustar_imagem,
			'/openseadragon/images/custom/ajustar_imagem_rest.png',
			'/openseadragon/images/custom/ajustar_imagem_rest.png',
			'/openseadragon/images/custom/ajustar_imagem_hover.png',
			'/openseadragon/images/custom/ajustar_imagem_pressed.png',
			GoHome,
			OpenSeadragon.ControlAnchor.TOP_RIGHT
		);

		AddCustomButton(
			'open',
			Resources.SharedResource.Cancela_a_selecao,
			'/openseadragon/images/custom/cancel_selected.png',
			'/openseadragon/images/custom/cancel_selected.png',
			'/openseadragon/images/custom/cancel_selected.png',
			'/openseadragon/images/custom/cancel_selected_pressed.png',
			function () { anno.cancelSelected(); ApplyAnnotationsUser(); loadAllDefect() },
			OpenSeadragon.ControlAnchor.TOP_RIGHT
		);

		AddCustomButton(
			'open',
			Resources.SharedResource.Adicionar_marcacao,
			'/openseadragon/images/custom/marcacao_rest.png',
			'/openseadragon/images/custom/marcacao_rest.png',
			'/openseadragon/images/custom/marcacao_hover.png',
			'/openseadragon/images/custom/marcacao_pressed.png',
			enableDrawBB_global,
			OpenSeadragon.ControlAnchor.TOP_RIGHT
		);

		AddCustomButton(
			'open',
			Resources.SharedResource.Baixar_imagem_original,
			'/openseadragon/images/custom/download_rest.png',
			'/openseadragon/images/custom/download_rest.png',
			'/openseadragon/images/custom/download_hover.png',
			'/openseadragon/images/custom/download_pressed.png',
			downloadOriginalImage,
			OpenSeadragon.ControlAnchor.TOP_RIGHT
		);

		viewer.addHandler("page", function (e) {
			paginate(e.page);
		});

		annoConfig = {
			disableEditor: true,
			allowEmpty: true
		};

		if (anno != undefined) {
			anno = anno.destroy();
		}

		anno = OpenSeadragon.Annotorious(viewer, annoConfig);
	}

	function AddCustomButton(handlerName, tooltip, srcRest, srcGroup, srcHover, srcDown, onClickFunction, controlAnchor) {
		viewer.addHandler(handlerName, () => {
			let newButton = new OpenSeadragon.Button({
				tooltip: tooltip,
				srcRest: srcRest,
				srcGroup: srcGroup,
				srcHover: srcHover,
				srcDown: srcDown,
				onClick: onClickFunction
			});

			viewer.addControl(newButton.element, { anchor: OpenSeadragon.ControlAnchor.TOP_RIGHT });
		});
	}`

**Comment by pearcetm** [comment]
The `AddCustomButton` function is attaching the code to add the button as a handler to be called on the `open` event; so each time that event is fired (like when you navigate between pages), the buttons all get added. Try adding the buttons immediately, instead of within the `open` handler.

**Comment by digounet** [comment]
> The `AddCustomButton` function is attaching the code to add the button as a handler to be called on the `open` event; so each time that event is fired (like when you navigate between pages), the buttons all get added. Try adding the buttons immediately, instead of within the `open` handler.

Thank you for your reply, do you have any sample?

**Comment by digounet** [comment]
> The `AddCustomButton` function is attaching the code to add the button as a handler to be called on the `open` event; so each time that event is fired (like when you navigate between pages), the buttons all get added. Try adding the buttons immediately, instead of within the `open` handler.

Thank you for your repply. I removed the handler as you sad and it's working now!
