### ISSUE TITLE
IIIF examples do not work on openseadragon.github.io

### ISSUE THREAD

**Issue by themcoo** [openseadragon/openseadragon#2278]
The examples provided on https://openseadragon.github.io/examples/tilesource-iiif/ do not render any image. The second one displays error message;
![image](https://user-images.githubusercontent.com/2964157/214274021-82ec83b9-9367-460a-a798-6205666c8978.png)

**Comment by pearcetm** [comment]
This example is working for me. Perhaps there was a network error or something that stopped the tile source info from being loaded for some reason?
