### ISSUE TITLE
Drop Internet Explorer 11 support?

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#2286]
With https://github.com/openseadragon/openseadragon/issues/1863, we dropped support for all IE versions prior to 11. Maybe it's now time to drop support for 11 as well? 

IE11 was introduced in 2013 and replaced with Edge in 2015. According to https://caniuse.com/usage-table, IE11 usage is down to 0.57%, and I feel like the industry has pretty well moved on. 

The biggest benefit to dropping IE11 is that we can start using ES6, as it's supported in all other browsers (see https://caniuse.com/?search=es6). 

Of course if we do this, we'll want to make it a major version (5.0.0) and make it clear that 4.0.0 is the last version for people who still need IE11. For that matter, it could be a good time to actually document which browsers we support (https://github.com/openseadragon/openseadragon/issues/106). 

What do y'all think?

**Comment by msalsbery** [comment]
That would be lovely! No objection from me!

**Comment by pearcetm** [comment]
I'm in full support! Moving on from IE and thus enabling ES6 seems like a great idea.

**Comment by catherineomega** [comment]
I hate to say this as a rationale, but if anyone's still using IE11 at this point, they're already used to half the web being broken. I say drop it.

**Comment by alvaromartmart** [comment]
Yes please

**Comment by iangilman** [comment]
Okay, it seems to be unanimous! Let's go ahead and make it official :) 

Actually I'm not sure what making it official means... I guess we just allow ES6 code in future pull requests. 

I suppose one other thing that would be nice is to release 4.0.1 as the last IE11 compatible version. 

Also, as mentioned above, it would be nice to explicitly publish our browser support, maybe here: 

https://openseadragon.github.io/#download

**Comment by msalsbery** [comment]
Browser Support related:  #2300

**Comment by iangilman** [comment]
Okay, 4.1.0 is released and I've added a note that it's the last IE11 version (https://github.com/openseadragon/site-build/pull/278), so I think this is done!
