### ISSUE TITLE
Weird Image distortions (Moiré patterns)

### ISSUE THREAD

**Issue by jonasengelmann** [openseadragon/openseadragon#2290]
I recently noticed some unwanted Moiré patterns when zooming in and out of iiif images. I am not quite sure what is causing it, but I think it has do to with a combination of image viewer size and image source quality.

![ezgif-3-fd4b544354](https://user-images.githubusercontent.com/40031476/217053868-b77e07ce-ccc4-4769-bec1-ec3a5e42a1bb.gif)

Here is an example using version 4.0.0 (zooming in and out of the bird in the center is especially triggering it):

[4.0.0](https://codepen.io/jonen/pen/WNKWbLW)

I also noticed that it used to be better, here is the same image using version 2.4.1:

[2.4.1](https://codepen.io/jonen/pen/rNrbaRe)

Any idea what to do and how to prevent this from happening?

**Comment by iangilman** [comment]
Interesting! I'm not surprised that image is showing moire, but I have no idea why it's happening more dramatically in 4.0.0.

One thought for taming it would be to adjust `minPixelRatio`. In your CodePen, I'm finding a value of 1 is enough to make it look better. Basically, it's telling OSD not to use the high res tiles as much when you are zoomed out. Moire shows up more when scaling down thin lines than it does when scaling up.

**Comment by jonasengelmann** [comment]
`minPixelRatio ` was exactly what I was looking for! Thanks!
