### ISSUE TITLE
some NPM packages are outdated. 

### ISSUE THREAD

**Issue by MohitBansal321** [openseadragon/openseadragon#2295]
**CODE REFACTOR**
These packages are outdated we need to update it

![OutDated packages](https://user-images.githubusercontent.com/78220157/218751248-66f090b1-f84e-42d1-9cd6-6f8e44c6dae9.png)

Solution:
I will update these package
using some commands

**Comment by iangilman** [comment]
Great, please do! Once you've done so, please test to make sure there aren't any side effects :)

**Comment by MohitBansal321** [comment]
@iangilman I'm getting error after updating 
grunt-contrib-uglify
```
Uglifying source build/openseadragon/openseadragon.js failed.
Warning: Uglification failed.
Maximum call stack size exceeded.
```

grunt (working fine after update)
grunt-contrib-clean (working fine after update)
grunt-contrib-concat (working fine after update)
but when I update the grunt-contrib-uglify 
I see the error which mention above

**Comment by msalsbery** [comment]
@MohitBansal321  Do you see this error?
```
(node:93935) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by msalsbery** [comment]
> @iangilman I'm getting error after updating grunt-contrib-uglify
> 
> ```
> Uglifying source build/openseadragon/openseadragon.js failed.
> Warning: Uglification failed.
> Maximum call stack size exceeded.
> ```
> 
> **grunt** (working fine after update) **grunt-contrib-clean** (working fine after update) **grunt-contrib-concat** (working fine after update) but when I update the grunt-contrib-uglify I see the error which mention above

You didn't see this error before updating grunt-contrib-uglify? I saw the same error a few days ago on my Windows laptop but I hven't seen it since on Mac or Windows.

**Comment by MohitBansal321** [comment]
> @MohitBansal321  Do you see this error?
> ```
> (node:93935) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
> (Use `node --trace-warnings ...` to show where the warning was created)
> ```

I see the error what didn't get where it is

**Comment by msalsbery** [comment]
> > @MohitBansal321  Do you see this error?
> > ```
> > (node:93935) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
> > (Use `node --trace-warnings ...` to show where the warning was created)
> > ```
> 
> I see the error what didn't get where it is

Something in grunt, I don't know

**Comment by iangilman** [comment]
Unfortunately, grunt is not as popular as it once was, so I'm not surprised if it's falling behind. It may be that we should just stick with the older versions, at least with uglify, if the new version doesn't work. Another approach would be to look for other grunt modules that do the same thing uglify does (pack all the files together and minify them). 

Of course, a much bigger thing would be to evaluate replacement options for grunt or at least parts of our grunt stack. I don't know that there are currently any problems with our grunt (apart from it being out of date and the newer version not working), so I don't know that there's really any need for this. 

What do y'all think?

**Comment by msalsbery** [comment]
I use webpack for my plugins but that's outdated these days too. Rollup got popular, but now I'm considering vite (which uses rollup I believe) for packaging my libs. I'm still investigating so I can't expertly comment more ;)

Grunt still builds OpenSeadragon just fine though!

**Comment by iangilman** [comment]
@msalsbery Do let us know what you find! I don't really want to get on the flavor of the week rollercoaster, so as long as grunt still works, I'm happy to stick with it. That said, no doubt eventually we should move on.

**Comment by MohitBansal321** [comment]
From my point of view i updated  the package which doesn't lead to any error
I didn't update unify because I saw the issue of it for a large code file to get this type of error maximum stack size 
Else other working fine 
Let  me know so I should create PR for it

**Comment by MohitBansal321** [comment]
> > > @MohitBansal321  Do you see this error?
> > > ```
> > > (node:93935) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
> > > (Use `node --trace-warnings ...` to show where the warning was created)
> > > ```
> > 
> > I see the error what didn't get where it is
> 
> Something in grunt, I don't know 

But this doesn't lead to any error

**Comment by iangilman** [comment]
I guess I'm not too worried about the warning, and as @MohitBansal321 says, it's not because of this patch. 

Updating the ones that do work seems like a fine approach :)
