### ISSUE TITLE
Add Topics to the repository

### ISSUE THREAD

**Issue by MohitBansal321** [openseadragon/openseadragon#2303]
# Adding topics makes it easier for other users to find and contribute to your project. 

Include topics in your repositories that are related to your project’s intended affinity groups, subject area, purpose, and other essential qualities.   

Topics in GitHub allow you to do the following:

_Explore repositories in specific subject areas
Find projects to add or contribute to
Uncover new solutions to certain problems_

**Comment by MohitBansal321** [comment]
@iangilman @msalsbery

**Comment by iangilman** [comment]
@MohitBansal321 Cool! I wasn't aware of this feature. I've now added some topics. What do you think of the list? Anything I should add or remove?

**Comment by MohitBansal321** [comment]
It is sufficient @iangilman
