### ISSUE TITLE
Hide custom toolbar if fullscreen mode?

### ISSUE THREAD

**Issue by dosstx** [openseadragon/openseadragon#2307]
Wonderful library. 

I am making a custom toolbar and it's working good. However, when user selects full screen mode, I want to hide the custom toolbar. How can I programmatically know when the viewer is in full screen mode? 

This is a snippet of how I am instantiating the viewer (Vue3):

```
viewer.value = OpenSeadragon({
    element: osdContainer.value,
    tileSources: {
      type: 'image',
      url: 'https://ik.imagekit.io/XXX/users%2F5cnu6iDlTsa5mujH2sKPsBJ8OKH2%2Fposts%2Fview-from-an-observation-post-in-france-during-ww1_K_V0?alt=media&token=c521a542-909d-4666-9506-8416eafcbb9e&tr=pr-true,dpr-auto'
    },
    defaultZoomLevel: 1,
    toolbar: props.toolBarDiv,
    zoomInButton: props.zoomInBtn,
    zoomOutButton: props.zoomOutBtn,
    homeButton: props.resetBtn,
    fullPageButton: props.fullPageBtn
  })
  ```

**Comment by pearcetm** [comment]
Check out the `Viewer` event `full-screen`: https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#.event:full-screen

**Comment by dosstx** [comment]
> Check out the `Viewer` event `full-screen`: https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#.event:full-screen

Yes, thank you that works!
