### ISSUE TITLE
Is it possible to add a custom button to the default toolbar button group? 

### ISSUE THREAD

**Issue by dosstx** [openseadragon/openseadragon#2313]
I am not talking about adding buttons outside the viewer, but rather, add to the default shown here:

![image](https://user-images.githubusercontent.com/6342102/223170860-5c470e85-6077-406f-b74a-d1c8074b7f72.png)

My case I want to add a custom "close" viewer button because the viewer will be a fullscreen modal window that I'll need to programmatically close when user is done viewing image.

**Comment by dosstx** [comment]
I got it figured out.

**Comment by SuhaibMaraqa** [comment]
@dosstx How ?

**Comment by iangilman** [comment]
@SuhaibMaraqa I don't have a lot of experience in this area, but something like this should work:

```
viewer.buttonGroup.addButton(new OpenSeadragon.Button(buttonOptions));
```

For your `buttonOptions` see the constructor on https://openseadragon.github.io/docs/OpenSeadragon.Button.html.
