### ISSUE TITLE
How to overlay segmentation png image over dzi images with panning&zooming in sync

### ISSUE THREAD

**Issue by humoyun91** [openseadragon/openseadragon#2327]
> Sorry for long description, just wanted to give as much info as possible. However, can be directly go to `Problem statement`

## Background
First of all, I would really like to thank for the authors and contributors of this awesome large image handling library. We are using it in our web based annotation tool to display WSI (whole slide image) pathology images to enable medical researchers to do various tasks like grid based annotation so that annotated images can be fed into our ML pipeline to train models which is aimed to detect cancerous cases.

We have some overlays like svg grids (previously implemented with `viewer.addOverlay`) but recently refactored with `React.Portals`:
```
<Portal container={viewer.canvas}>
  {isVisible &&
    slide.grids.map((grid) => {
      const texts = pairwiseChunk(grid.tags.map((tag) => tag.name));
      return (
        <ExistingGridBox key={grid.id} viewer={viewer} gridRect={grid.rect} onClick={handleClickGrid(grid)}>
          <svg style={{ overflow: 'visible', pointerEvents: 'none' }} viewBox="0 0 100 100">
            {texts.map((wordPairs, index) => (
              <text key={wordPairs.join(', ')} style={{ fontSize: 10 }} y={(index + 1) * 10}>
                {wordPairs.join(', ')}
              </text>
            ))}
          </svg>
        </ExistingGridBox>
      );
    })}
</Portal>
```
And here is actual GridBox component which is using viewer to calculate coordinates whenever viewport changes:
```
const GridBox = ({...}: PropsWithChildren<Props>): JSX.Element => {
  const ref = useRef<HTMLDivElement>(null);
  const [windowCoord, setWindowCoord] = useState<GridRect>(() => convertImageToViewerElementCoord(viewer, gridRect));

  useEffect(() => {
    const handleViewportChange = () => {
      setWindowCoord(convertImageToViewerElementCoord(viewer, gridRect));
    };
    viewer.addHandler('viewport-change', handleViewportChange);

    return () => {
      viewer.removeHandler('viewport-change', handleViewportChange);
    };
  }, [viewer, gridRect]);

  return (
    <Box
      ref={ref}
      className={className}
      data-grid-box
      style={{
        top: `${windowCoord.origin.y}px`,
        left: `${windowCoord.origin.x}px`,
        width: `${windowCoord.width}px`,
        height: `${windowCoord.height}px`,
      }}
      onClick={onClick}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
    >
      {children}
    </Box>
  );
};
```
#### here is the screenshot of our annotation tool with grids

<img width="1534" alt="Screen Shot 2023-03-30 at 12 30 54 PM" src="https://user-images.githubusercontent.com/85469622/228721503-47bb872b-af90-44dc-b2b0-5bdf054357e8.png">

#### Here is how we are using `OSDViewer` (OSDViewer from @lunit/osd-react-renderer which is React wrapper for OpenSeaDragon library)
```
<>
  <OSDViewer options={OSDOptions} ref={viewerRef} className={className}>
    <viewport
      zoom={viewportZoom}
      rotation={0}
      refPoint={refPoint}
      onOpen={handleViewportOpen}
      onZoom={handleViewportZoom}
      onCanvasKey={handleCanvasKey}
      onCanvasClick={handleCanvasClick}
    />
    <tiledImage tileSource={tileSource as OSD.TileSource} />
    <canvasOverlay onRedraw={handleOverlayRedraw} />
    <mouseTracker onMove={handleMouseMove} />
  </OSDViewer>
  {useZoomController && (
    <ZoomController zoom={viewportZoom} minZoomLevel={0.125} maxZoomLevel={160} onZoom={handleControllerZoom} />
  )}
</>
```

## Problem statement

So far so good. Recently, we are requested to accelerate annotation process by introducing **Inference Assisted Annotation** which is simply to overlay segmentation mask image (grayscale png) over WSI which is generated by already deployed models. 
Requirements are straightforward: inference result, the png mask, should be displayed as a translucent colored area overlaid on the WSI. We are already using dzi images for WSI but now our backend is short of resources so they cannot tile segmentation mask image as dzi tiles. They are providing 3 masks which is identical but with different resolutions, namely, 
```
{
  "tissue_masks": {
    "small": "https://...",
    "medium": "https://...",
    "large": "https://...",
  }
}
```
and initial plan was to apply them at certain fixed zoom levels. But, I don't think this works as expected as it is not part of OSD render flow, and handling this manually outside of OSD does not seem promising. So, I just want to use only highest resolution png  (actually its size is very small compared to WSI, so it can be loaded very fast). 

Problems I facing:

- overlay png mask image over WSI and it should be in sync with WSI when panning&zooming, etc.. (should be resized automatically by OSD like other overlays)
- how to efficiently convert grayscale mask into RGB colored mask (is there any helpers in OSD for this)

When I looked through the Issue list about what I want to achieve, there are only bits and pieces about it, but honestly I could not find detailed info either because of my poor search or it does not exist.

Hence, I would really appreciate if someone can direct me to the right direction if possible with actual code samples.

**Comment by pearcetm** [comment]
> * overlay png mask image over WSI and it should be in sync with WSI when panning&zooming, etc.. (should be resized automatically by OSD like other overlays)

For this part of it, you could use `viewer.addTiledImage()` to add your PNG at the appropriate position (using `x`, `y`, and either `width` or `height`). When you navigate (zoom/pan), the underlying DZI and the PNG would stay in sync.

**Comment by humoyun91** [comment]
@pearcetm 
Thank you for the response. Let me try what you have suggested and get back to you with the result

**Comment by humoyun91** [comment]
@iangilman 
I was able to render mask image over WSI with two approaches:

1. using viewer.addOvelay() method
```
// omitted for brevity
const maskImage = document.createElement('img');
maskImage.crossOrigin = 'Anonymous';
maskImage.src = maskPath;
const overlayLocation = new OpenSeadragon.Rect(0, 0, 1, 1);

maskImage.onload = async () => {
  const updatedImage = await grayscaleToColorfulImage(maskImage);
  viewer.addOverlay({
    element: updatedImage,
    location: overlayLocation,
    placement: OpenSeadragon.Placement.CENTER,
  });
};
```

3. using viewer.addTiledImage() method

```
// omitted for brevity
const maskImage = document.createElement('img');
maskImage.crossOrigin = 'Anonymous';
maskImage.src = maskPath;
const overlayLocation = new OpenSeadragon.Rect(0, 0, 1, 1);

maskImage.onload = async () => {
  const updatedImage = await grayscaleToColorfulImage(maskImage);
  viewer.addTiledImage({
    tileSource: {
      type: 'image',
      url: updatedImage.src,
    },
    x: 0,
    y: 0,
    width: 1,
    opacity: 0.6,
  });
};
```
Both of them are working as expected. But I noticed performance difference, tileImage has noticeable lag wile zooming compare to overlayed image. It is small but still I can feel it. I assumed the reason of the performance difference between `addTiledImage()` and `addOverlay()` in this scenario is likely due to the extra operations related to handling tiled images that addTiledImage() performs, even when working with a non-tiled image (OpenSeadragon still treats it as if it were a tiled image, but with only one tile). Using addOverlay() can provide better performance for non-tiled images, as it avoids this overhead and focuses on positioning and scaling the provided HTML element. 

Can you confirm the assumption, if right, or could you give better explanation if my assumption is wrong. Thanks in advance

**Comment by pearcetm** [comment]
> tileImage has noticeable lag while zooming compare to overlayed image

I'm a little surprised this would cause a noticeable difference, but especially if the PNG is fairly large, there is definitely going to be a cost with compositing it onto the underlying image, especially because it has transparency.

I think your approach with `addOverlay()` is probably better, since as you point out, it's not really a tiled image anyway.

**Comment by iangilman** [comment]
@humoyun91 I agree with @pearcetm that `addOverlay` is a fine choice. I do want to mention, however, that if you want to take advantage of all three sizes of image that you have available, you could do so with `addTiledImage` and this tile source: 

https://openseadragon.github.io/examples/tilesource-legacy/
