### ISSUE TITLE
Navigator rotates with animation when viewport.setRotation(90, true) is called

### ISSUE THREAD

**Issue by robertjcolley** [openseadragon/openseadragon#2332]
OSD Version 4.0.0

Reloading the page [here](https://codepen.io/bobbycolley/pen/XWxWedb?editors=1111) shows that `viewport.setRotation(90, true)` animates the OSD viewer immediately without animation. However, the navigator animates and ignores the `immediate` property.

**Comment by pearcetm** [comment]
Looks like the code making the navigator mirror the main viewer's rotation needs to be updated to account for `immediately`:

https://github.com/openseadragon/openseadragon/blob/b45d500f1eeb3869caa807365f4cd5de03e074d8/src/navigator.js#L227-L241

**Comment by iangilman** [comment]
Good catch! 

@pearcetm Thank you for spotting the cause! 

@robertjcolley Would you be up for making a patch?
