### ISSUE TITLE
Unable to get real-time position during animation

### ISSUE THREAD

**Issue by donotloveshampo** [openseadragon/openseadragon#2335]
set
` animationTime = 2;`
During the animation process, the current position cannot be obtained, but the position at the end of the animation is obtained

**Comment by msalsbery** [comment]
> set
> 
> ` animationTime = 2;`
> 
> During the animation process, the current position cannot be obtained, but the position at the end of the animation is obtained

Many of the position methods take a current parameter that needs to be passed as true (default is false)

**Comment by donotloveshampo** [comment]
> > set
> > ` animationTime = 2;`
> > During the animation process, the current position cannot be obtained, but the position at the end of the animation is obtained
> 
> Many of the position methods take a current parameter that needs to be passed as true (default is false)
> 
> Edit: ...or are you saying there's a bug when you set animation time to 2? :)

Thank you very much, I was careless and didn't check the document carefully
