### ISSUE TITLE
new Navigator constructor fails (viewer undefined)

### ISSUE THREAD

**Issue by svchostdotexe** [openseadragon/openseadragon#2336]
Calling the Navigator constructor fails because of line 11607:
```    options.minPixelRatio = this.minPixelRatio = viewer.minPixelRatio;```
or in repo line 138:
https://github.com/openseadragon/openseadragon/blob/master/src/navigator.js

viewer is undefined. Any help would be greatly appreciated.
Using Angular and Typescript if that helps :)

**Comment by svchostdotexe** [comment]
i am calling it manually after the viewer construction. even after opening a tile image in the viewer

**Comment by pearcetm** [comment]
You need to pass the viewer to the constructor in the options object - see the first couple of lines of the constructor to see where it's accessed.

**Comment by svchostdotexe** [comment]
oh, makes sense! is it possible that the types are broken then?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/openseadragon/index.d.ts
the options dont include the viewer field

**Comment by pearcetm** [comment]
I'm not very familiar with typescript but it does seem that the definition of the constructor and options object are missing for the Navigator class. You are welcome to create a patch that fixes this, I'm afraid I'm not the right person to help though.

**Comment by svchostdotexe** [comment]
awesome, thank you a million times for the hint!

**Comment by msalsbery** [comment]
> oh, makes sense! is it possible that the types are broken then?
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/openseadragon/index.d.ts
> 
> the options dont include the viewer field

Yes the types are broken, I'm currently patching the types on DefinitelyTyped, will be done soon
