### ISSUE TITLE
Get http status code when error occurred in the tile image ajax request

### ISSUE THREAD

**Issue by LuckyLuo** [openseadragon/openseadragon#2340]
When Ajax request to load tile image failed, in the tile-load-failed event handler, we expect to get the http status code so that we can take different actions from there. For example, when token expires, we expect to detect the 401/403 error and redirect user to the login page. 

I checked the message, eventSource and tileRequest field, there is no clue in terms of the http status code. The message only says: "Image load aborted - XHR error: Ajax returned 0". tileRequest showed 0 status.

<img width="414" alt="Screenshot 2023-04-26 at 4 49 40 PM" src="https://user-images.githubusercontent.com/3184550/234473768-0225dd12-4052-48c3-8d6b-3238e95e0766.png">

**Comment by iangilman** [comment]
This should be possible when we are loading tiles with AJAX (as in your example). It's worth noting that as far as I know, it's not possible when loading tiles via the regular `img.src` method (unless there's some browser feature I'm unaware of). 

If you want to work on a fix, the task is basically to get the `request.status` from this line: 

https://github.com/openseadragon/openseadragon/blob/60a6a610e04983a3ebcdb4273c8b8edca188fb33/src/tilesource.js#L811

... through the various layers, to this line: 

https://github.com/openseadragon/openseadragon/blob/60a6a610e04983a3ebcdb4273c8b8edca188fb33/src/tiledimage.js#L1614

... where you can add a `status` to the event. 

I figure we should always have a `status`, so our failure comes from `img.src`, we should set the status to `null`. While you're in there, it might be nice to separate abort from error here: 

https://github.com/openseadragon/openseadragon/blob/60a6a610e04983a3ebcdb4273c8b8edca188fb33/src/tilesource.js#L768

... so the message can be different between them.

**Comment by LuckyLuo** [comment]
Thanks, @iangilman let me take a look 👍

**Comment by LuckyLuo** [comment]
@iangilman I had a further look, actually the openseadragon works fine, it does return the http status in the tileRequest object from the event. For my case, when 403 error occurred, the server response does not contain Access-Control-Allow-Origin header, which makes the browser block ajax request to read the response status. 

I tried another mock API with Access-Control-Allow-Origin returned when request failed, I can see the http status code and text are correct in tileRequest object, so I am happy to close this issue. Thanks

<img width="709" alt="Screenshot 2023-05-02 at 4 18 00 PM" src="https://user-images.githubusercontent.com/3184550/235582116-03ec6d94-ace6-45be-9d1f-676fc98bec85.png">
<img width="618" alt="Screenshot 2023-05-02 at 4 21 56 PM" src="https://user-images.githubusercontent.com/3184550/235582128-2b98cf58-2601-4aa4-bf1b-7316ac5d6b72.png">

**Comment by iangilman** [comment]
Oh! I didn't realize the request was in there. Excellent... Thank you for following up on this! I'll go ahead and close it.
