### ISSUE TITLE
How to optimise for portrait mobile display

### ISSUE THREAD

**Issue by cleverlight** [openseadragon/openseadragon#2342]
I'm working on an image viewer.  It's early days, but there's a prototype here:
https://i.scrowl.com/@alex/scrowl1

This (early) demo works fine on desktop and mobile, when in landscape.  However when I flip the phone to portrait, the scrolling and zooming becomes very slow.

I'd be immensely grateful of any tips on how to optimise the canvas for portrait display.

**Comment by iangilman** [comment]
Looks neat! 

You'll want to add this meta tag to your `head`: 

```
<meta name="viewport" content="width=device-width, initial-scale=1" />
```

Without that, the browser loads a much wider page and then zooms it down, which means the device doing a lot more work than it has to.

**Comment by iangilman** [comment]
You might also check out https://github.com/openseadragon/openseadragon/issues/1569 and https://github.com/openseadragon/openseadragon/issues/678 if you're still having trouble after you add the meta tag.

**Comment by cleverlight** [comment]
> ```
> <meta name="viewport" content="width=device-width, initial-scale=1" />
> ```

This worked brilliantly thank you.

**Comment by ozanyetkin** [comment]
Fixed my issue as well, thanks for the suggestion @iangilman
