### ISSUE TITLE
Overlay as canvas for freehand drawing

### ISSUE THREAD

**Issue by mhellfeuer** [openseadragon/openseadragon#235]
I'm working on a viewer for construction designs. I wan't to add a fullsize overlay for freehand drawing. I'm using fabric.js (http://fabricjs.com/) and need a canvas for drawing. I tried this:
![code](https://f.cloud.github.com/assets/4731267/1239617/803c9ae2-29fd-11e3-9e73-2d2997b35dd4.jpg)
The result is an overlay with the freehand drawing and a smaller canvas for drawing:
![freehanddrawing](https://f.cloud.github.com/assets/4731267/1239624/9b1e5ea4-29fd-11e3-9dd6-6a4f23d9e498.jpg)
Is there any other solution? Can I draw direct to an overlay?

**Comment by iangilman** [comment]
Note that this new plugin might be helpful for this scenario: https://github.com/openseadragon/svg-overlay

Be warned that it doesn't work on any other branch than #446 for the moment. Soon enough we'll merge that in, though.
