### ISSUE TITLE
Deprecate/Remove unused function `createCallback`

### ISSUE THREAD

**Issue by AndrewADev** [openseadragon/openseadragon#2365]
I noticed recently that there is a util-like method, [`createCallback`](https://github.com/openseadragon/openseadragon/blob/master/src/openseadragon.js#L2269) that is not currently used within the main OSD codebase.

It seems it was last touched 11 years ago, and it doesn't look to be something that would be needed currently. Even back then, it seems it was hardly used (I checked for usages as of 3bfb693872668cdc8386022a1660f6031c2023c1) [A search for any discussion or issues related to it also turned up empty](https://github.com/search?q=repo%3Aopenseadragon%2Fopenseadragon%20createCallback&type=code) (aside from the one reference in the source)

As it is not used in the main OSD codebase, might it be worth at least deprecating it for future removal? That would give plugin authors a chance to migrate away, on the off chance they are using the method. (Unless there's high enough confidence to remove it already?)

**Comment by iangilman** [comment]
Nice! Good to spot these cleanup opportunities. 

Since it is officially documented, I think deprecating it first would be the way to go, just to be safe.

**Comment by akansjain** [comment]
Hey @AndrewADev 
Can I work on this issue?

**Comment by AndrewADev** [comment]
> Hey @AndrewADev 
> 
> Can I work on this issue?

Sure!

**Comment by shrutisingh17** [comment]
Hey @AndrewADev,

I'm a beginner and would like to contribute to this issue regarding the createCallback method. Could you please let me know if someone is already assigned to this issue? If not, I would like to work on it. Are there any specific steps or guidelines I should follow?

**Comment by iangilman** [comment]
@shrutisingh17 Looks like @akansjain is already working on it. I believe that there are other issues you could tackle. Here are some: https://github.com/openseadragon/openseadragon/labels/good%20first%20issue

@akansjain Let me know if you have any questions, and also if you end up deciding not to work on it.

**Comment by akansjain** [comment]
Hey @iangilman , I am still working on this.

**Comment by kakashi2020** [comment]
Hi, @AndrewADev 

I hope you are doing well. 

I'm just starting to try to contribute to open source, and I would like to support solving this issue. However, I saw that I few people tackled it already in the past. Is it still open? If it is, can I give it a go?

**Comment by AndrewADev** [comment]
Hi @kakashi2020, welcome! 

Indeed someone picked up the issue earlier, and the associated PR has since been merged: https://github.com/openseadragon/openseadragon/pull/2367

I'm not sure how many good first issues there are at the moment, but feel free to take a look around! Note that there are also a number of plugins for OSD. I'm not sure if there are any good first issues for them either, but the plugin codebases might be easier to understand to start with.

**Comment by kakashi2020** [comment]
Awesome, @AndrewADev ! Defo will look around. I've been learning to code for about a year formally now and it seems that syntax knowledge doesn't fully cut it for real-life programming haha.  But I'll give it a go to anything that doesn't seem too far from my knowledge gap. Thanks!
