### ISSUE TITLE
is it possible to merge two Images in OSD?

### ISSUE THREAD

**Issue by tofetpuzo** [openseadragon/openseadragon#2369]
@iangilman Hello please is it possible to merge two images , more like one is an overlay of the other , so one image and the other is like a corresponding area of interest.

like in the diagram bellow, not a good diagram, hey I wish I was an artist
<img width="374" alt="_2023-06-07 at 11 37 36" src="https://github.com/openseadragon/openseadragon/assets/54607597/72bd3e9b-d0be-4a86-937f-e04ced40aa6f">

Then can I tell OSD to switch off the layers, so the two images are tiff images one is the normal image while the other is the overly , can I tell OSD to switch off each layers.

**Comment by iangilman** [comment]
Sure, you can load two images on top of each other in the viewer, and you can control which one is on top of the other and which one is visible. Here's a good starting point: 

https://openseadragon.github.io/examples/multi-image/

**Comment by tofetpuzo** [comment]
viewer.addTiledImage({
    tileSource: 'my-image.dzi',
    x: 5,
    y: 0,
    width: 10
});
first question: Please the x, y  are what values exactly and how do I get them? the docs says aspect ratio, apologies I am new, and I am sure you know I am jumping here and there lol indulge me. 

Second question is the width? from this dzi xml file

<?xml version="1.0" encoding="UTF-8"?><Image xmlns="http://schemas.microsoft.com/deepzoom/2008" TileSize="128" Overlap="2" Format="png"><Size Width="8014" Height="15275"/></Image> 


3rd question, I have not specified x , y , width and I do not see the addedImage, then what method on OSD helps to switch off the addedImage?

**Comment by iangilman** [comment]
The x, y, and width are in viewport coordinates. You can learn more about them here: 

https://openseadragon.github.io/examples/viewport-coordinates/

They are arbitrary... You can pick whatever you want. One option is to use the width from the DZI, and that can make it easier to do other calculations, but you don't have to. 

If you're not seeing the new image after you load it, you might need to press the "home" button in the viewer, as it may be outside the current view. If you want that to happen automatically, you can add a `success` handler that calls the home function.

**Comment by tofetpuzo** [comment]
Thank you so much for your help. so here is another question the two images have black tiles as background, so I can only see one at the foreground which is the roi. Can I ask OSD to make the ROI have a transparent tile, so that only the shape of the roi shows. i.e I want the top dzi image transparent to the one behind but leaving the shape of the roi

**Comment by iangilman** [comment]
If you make a transparent PNG and convert it to a DZI with PNG tiles, it should retain its transparency. 

BTW, how big is the ROI image? If it's less than 2000 pixels wide, you can use http://openseadragon.github.io/examples/tilesource-image/ or http://openseadragon.github.io/examples/tilesource-legacy/ without having to convert it.

**Comment by tofetpuzo** [comment]
![Screenshot 2023-06-14 at 09 33 25](https://github.com/openseadragon/openseadragon/assets/54607597/f1f41e91-81ed-4431-a936-19b96b00f346)
<img width="447" alt="Screenshot 2023-06-13 at 18 47 00" src="https://github.com/openseadragon/openseadragon/assets/54607597/4f51f74e-fca8-46bf-aafd-28623fbc0104">



Hello @iangilman, so the images are not transparent but haVE a black background, 
ROI image is like 14559 x 8000; weight and height, total image before running deepzoom converter is 800MB


So Ideally, we have two dzi images,
I will use the image above to illustrate, you can see there are two eyes, let us say the ROIs -> the white dots on the eye and the eyes -> second image, you can see they both have black background, so if I superimpose the white dot(DZI IMAGE) onto to the eyes(DZI IMAGE), the eyes disappear leaving only the white dot with the black background, I will like to make the white dot have a transparent background so I can see both the eyes and the dot at the same time.

**Comment by iangilman** [comment]
Do you have just one of these ROI images, or is this a problem you need to solve a lot of times in many images? If it's just one image, by far the easiest thing to do is to load it into Photoshop, select the black, and make it transparent (then convert to DZI). 

Even if this is something you need to do a lot of, it still might be worth putting the transparency creation in your pipeline before the DZI conversion. 

At any rate, if you want to do it on the fly on the client-side, you would do what @Aiosa suggests here: https://github.com/openseadragon/openseadragon/issues/2343#issuecomment-1585096970. It's basically the technique https://github.com/usnistgov/OpenSeadragonFiltering uses... You can look at its code for ideas. Basically, you want this function: https://github.com/usnistgov/OpenSeadragonFiltering/blob/f1e350c08e8bf050fdc84b89e9b04ad041c861b9/openseadragon-filtering.js#L78. Something like: 

```
this.viewer.addHandler('tile-loaded', function (event) {
    var tile = event.tile;
    var image = event.data;
    if (image !== null && image !== undefined) {
        var canvas = window.document.createElement('canvas');
        canvas.width = image.width;
        canvas.height = image.height;
        var context = canvas.getContext('2d');
        context.drawImage(image, 0, 0);
        tile._renderedContext = context;

        // Do whatever you want with the context, like getting the pixels, turning all the black transparent, and setting the pixels again
    }
});
```

**Comment by tofetpuzo** [comment]
@iangilman @Aiosa
You guys are the best,
I know it is off topic but please I can only get both of you in one place which is unbelievable, please indulge me a lot. we are brothers in code.

first question, How can I convert a dziImage back to a full object, since html object understands only one full imageUrl rather the ones in folders which is produced when you do deepzoom converter?

how can I get the getImageData(sx, sy, sw, sh, settings) from dziImage?

How do I calculate this for dziImage from the docs of html reference:
[canvas](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData) ?

which is sx = The x-axis coordinate of the top-left corner of the rectangle from which the ImageData will be extracted.
sy
The y-axis coordinate of the top-left corner of the rectangle from which the ImageData will be extracted.

sw
The width of the rectangle from which the ImageData will be extracted. Positive values are to the right, and negative to the left.

sh
The height of the rectangle from which the ImageData will be extracted. Positive values are down, and negative are up.

please here is my code for trying to convert one dzi image(roi) to transparent

function createIDforROITilledImage() {

    const image = tileSourceFromData(dziImageDataROI, dziFilesForTiffImagesROILocationUrl);
    image.id = "image_added_image";

    // add the image url 
    viewer_.addTiledImage({tileSource: image, success: function getImageDatafromDZI(params) {}, crossOriginPolicy: true});

    // create the canvas to have same height and width of the image 
    var canvas = document.createElement("canvas");
    canvas.width = image.Image.Size.Width;
    canvas.height =  image.Image.Size.Height;

     // add canvas to document body 
    document.body.appendChild(canvas);
    var ctx = canvas.getContext("2d");


   // decode image
    var newImageforTilledImage  =  new Image();
    newImageforTilledImage.decoding = "sync";
    newImageforTilledImage.src = image.Image.Url;

    document.body.appendChild(newImageforTilledImage)
    console.log(newImageforTilledImage)
    ctx.drawImage(newImageforTilledImage, 0,  0);
    var imageDataROIImage = ctx.getImageData(0, 0, image.Image.Size.Width, image.Image.Size.Height), pixelROIData = imageDataROIImage.data;
    // console.log(pixelROIData);
    // loop from the addedROITilledImage using the canvas.
    // for (var i = 0, n = pixelROIData.length; i < n; i += 4) {
    //     console.log(pixelROIData);

    // }
    
    console.log(typeof image, image.Image.Url);
    // console.log(el, ctx, images, image);
    }
    createIDforROITilledImage()@iangilman @Aiosa
You guys are the best,
I know it is off topic but please I can only get both of you in one place which is unbelievable, please indulge me a lot. we are brothers in code.

first question, How can I convert a dziImage back to a full object, since html object understands only one full imageUrl rather the ones in folders which is produced when you do deepzoom converter?

how can I get the getImageData(sx, sy, sw, sh, settings) from dziImage?

How do I calculate this for dziImage from the docs of html reference:
[canvas](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData) ?

which is sx = The x-axis coordinate of the top-left corner of the rectangle from which the ImageData will be extracted.
sy
The y-axis coordinate of the top-left corner of the rectangle from which the ImageData will be extracted.

sw
The width of the rectangle from which the ImageData will be extracted. Positive values are to the right, and negative to the left.

sh
The height of the rectangle from which the ImageData will be extracted. Positive values are down, and negative are up.

please here is my code for trying to convert one dzi image(roi) to transparent

function createIDforROITilledImage() {

    const image = tileSourceFromData(dziImageDataROI, dziFilesForTiffImagesROILocationUrl);
    image.id = "image_added_image";

    // add the image url 
    viewer_.addTiledImage({tileSource: image, success: function getImageDatafromDZI(params) {}, crossOriginPolicy: true});

    // create the canvas to have same height and width of the image 
    var canvas = document.createElement("canvas");
    canvas.width = image.Image.Size.Width;
    canvas.height =  image.Image.Size.Height;

     // add canvas to document body 
    document.body.appendChild(canvas);
    var ctx = canvas.getContext("2d");


   // decode image
    var newImageforTilledImage  =  new Image();
    newImageforTilledImage.decoding = "sync";
    newImageforTilledImage.src = image.Image.Url;

    document.body.appendChild(newImageforTilledImage)
    console.log(newImageforTilledImage)
    ctx.drawImage(newImageforTilledImage, 0,  0);
    var imageDataROIImage = ctx.getImageData(0, 0, image.Image.Size.Width, image.Image.Size.Height), pixelROIData = imageDataROIImage.data;
    // console.log(pixelROIData);
    // loop from the addedROITilledImage using the canvas.
    // for (var i = 0, n = pixelROIData.length; i < n; i += 4) {
    //     console.log(pixelROIData);

    // }
    
    console.log(typeof image, image.Image.Url);
    // console.log(el, ctx, images, image);
    }
    createIDforROITilledImage()

**Comment by tofetpuzo** [comment]
@iangilman Thank you so much for your help,
This is a full project so there is no way I can do that by hand .

I had a think about trying to make it a pipeline one of the image which is the one I want transparent .
1. First the two images are more than 500MB , so I had to download the PNG format of the ROI image-> which I want transparent as a test run, I soon realise that canvas has its limits, I am not sure lol, but when I started using canvas to try and manipulate I forgot that the dimensions of the image will be a problem, take a lot at this dimensions it basically killed the browser.(16027 × 30548), and I do not want to resize, I suspect if I do I will not get the full power of dzi image thing. so I am kinda of skeptical, plus after the canvas manipulation (changing the pixels to black) how do I download the image from the canvas? Iol, if you have the answer please share lol.
Plus if you have any thoughts on how do to this pipeline please share, but I guess not lol... either ways its all good.


**Back to the code:** 

1. Please how do I know what "event" is in this code above? 
2. because I have two images(ROI which I want transparent) and (the one I don't want transparent) overlapping each other at the moment, the one I want to make transparent, is above and I have this output from the Unit8ClampedArray(69696) see below.  {"0": 0, "1": 0,  "2": 0, "3": 255, "4": 0,  "5": 0, "6": 0, "7": 255, "8": 0, "9": 0,..... "63789": 255} 
THEN ANOTHER (69696) see below.  {"0": 34, "1": 89,  "2": 30, "3": 255, "4": 0,  "5": 0, "6": 30, "7": 255, "8": 67, "9": 80,..... "63789": 255}  
5. This Unit8ClampedArray(69696) was gotten when I did a console.log on (   var tile = event.tile; var image = event.data), 

My question is how do I deal specially to the image(ROI) without it affecting the other image which is under?

**Comment by iangilman** [comment]
Good questions! The event is this guy: 

https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#.event:tile-loaded

You can use `event.tiledImage` to determine which image it is. Presumably, your base image is the bottom image in your viewer, so you can get that with `viewer.world.getItemAt(0)` and the ROI image is the next image on the stack, so you can get that with `viewer.world.getItemAt(1)`.

**Comment by tofetpuzo** [comment]
Thank you so much, my next image is the one on stack:

```
   document.body.onload = createIDforROITilledImage;
    function createIDforROITilledImage() {

    const image = tileSourceFromData(dziImageDataROI, dziFilesForTiffImagesROILocationUrl);
    // give the image; an id 
    image.id = "image_added";

    // add the image url 
    viewer_.addTiledImage({tileSource: image, success: function getImageDatafromDZI(params) {}, crossOriginPolicy: true});
   
    viewer_.addHandler('tile-loaded', function (event=image) {

      var tile = event.tile;
      
      var image = event.data;
      // var tiledImag = event.tiledImage;

      // console.log(image, tile);
      var tileImage = viewer_.world.getItemAt(1); 
      // console.log("tile and image from event", tileImage)

      if(image !== null && image !== undefined){
        var canvas = window.document.createElement('canvas');
        console.log(image.width, image.height);
        canvas.width = image.width;
        canvas.height = image.height;
        var context = canvas.getContext('2d');
        context.drawImage(image, 0, 0);
        tile._renderedContext = context;
        // console.log(tileImage)
   // Do whatever you want with the context, like getting the pixels, turning all the black transparent, and setting the pixels         again
        var imagesObject =  context.getImageData(0, 0, image.width, image.height);

        var imageData =  imagesObject.data, length = imageData.length;
        console.log(imageData);

        for(var i=3; i < length; i+=4){  
            imageData[i] = 50;         
        }
        imagesObject.data = imageData;
      context.putImageData(image, 0, 0);
          
      }
```



Please see my code above after trying this it gives: 
ERROR: Cannot assign to read only property 'data' of object '#<ImageData>' TypeError: Cannot assign to read only property 'data' of object '#<ImageData>' Does it mean I can not change the imagesObject.data  values in from a dzi image

Please advise

**Comment by Aiosa** [comment]
@tofetpuzo we are happy to help, though we are not paid coding guru nor your personal searching engine. The error clearly tells you that the object you are trying to write to is read-only. Typing a few words to a search engine can give you [all you need to know](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas). Happy coding :)

**Comment by tofetpuzo** [comment]
@Aiosa  that was a brutal jab *laughs hard* "Searching for your solutions before asking will train you well, you will learn more" damn!!! , so you presume I am new to coding, very well then, it is allowed, a beggar never has a choice. 

So having said that-

I just thought it was an openseadragon error perhaps something to do with strict policy on changing read_only objects (if you see these things my mind raced to immutable objects) , so maybe the method suggested might not work after all(my thoughts); that was my thinking. I dropped that error so that people could learn from it , as you @Aiosa  and @iangilman  have helped. 

All I wanted to know was this question which you failed to answer.  " Does it mean I can not change the imagesObject.data values from a dzi image?" 

Lastly, thank you for pointing me to a reference point. Make No mistake I will still keep asking questions, and I hope in the future my findings might others in the future. Thank you PS: thought you said you wouldn't respond to me till JUNE 20TH

**Comment by Aiosa** [comment]
Yeah, I am too busy to keep long conversations, but I hint and help here and there occasionally :) The origin of the error can be found in a developer tools (clicking on it will give you the exact line), if it was OSD error you would get the exact location where it was raised. This is a language-level error, similar to trying assign a value to `const` variable in C++ for example. IMHO questions like this rather pollute the discussion than help others.

**Comment by iangilman** [comment]
There's nothing wrong with being new to coding! @Aiosa is just trying to help you help yourself. 

In this case, you put a reference to the data into a variable: 

```
var imageData =  imagesObject.data
```

... Then, make some changes to that data then try to copy it back on top of itself: 

```
 imagesObject.data = imageData;
```

That last line is what's causing the error, because the `data` property is read-only. It's also pointless, since `imageData` is a reference to the same object in the first place. All of the changes you've made through `imageData` are already in `imagesObject.data` since they are the same object. 

That kind of mistake is something an experienced coder can make sometimes, but it's very common with new coders... That's probably why @Aiosa assumed your experience level. Also, to be honest, we get all sorts here, from barely knowing how to program to extremely advanced! Anyway, I'm sure he meant no offense. 

BTW, the line below also needs to be fixed:

```
context.putImageData(image, 0, 0);
```

... Should be:

```
context.putImageData(imagesObject, 0, 0);
```

**Comment by tofetpuzo** [comment]
@iangilman Ah, I see spot on many thanks let me try it. Hey please no offense taken at all at what @Aiosa said. i don't know anything believe me, I will never say I am an experienced coder or a newbie, I learn everyday, I just need this to work as it has the potential to save lives. I will revert back thanks.

**Comment by tofetpuzo** [comment]
@iangilman thank you for your help so far, the quality was not that great but progress, I might just try other tools such Imagemagic,
just a quick question is there an OSD method that can switch off/on the layers using a button for example?

**Comment by iangilman** [comment]
Lovely! Just easy to have misunderstandings online... 😄

To turn off visibility of the top layer, you could do this:

```
viewer.world.getItemAt(0).setOpacity(0);
```

It's up to you to decide how to trigger it… You don't need to OpenSeadragon for that. Just make a regular button on your page or something.
