### ISSUE TITLE
Pathology Images inconsistent magnifications / zoom levels

### ISSUE THREAD

**Issue by ade90036** [openseadragon/openseadragon#2370]
Hi, 

I have been integrating the opensead dragon library to generate a viewer for to display pathology images for my university project.

I have implemented a custom tile-server based on this: `http://localhost:8083/slide/{slideId}/{level}/{x}/{y}.jpeg` 

To explain the issue bellow I'm going to refer to this pathology images (pyramid, tiled), which we can access using the url above. (see screen shot bellow)

| width      | height | level | magnification |
| ----------- | ----------- | ----------- | ----------- |
| 59759      | 35825       |5       |20       |
| 29880 | xxx | 4 | 10 |
| 14940 | xxx | 3 | 5 |
| 7470, | xxx | 2 | 2.5 |
| 3735, | xxx | 1 | 1.25 |
| 1868, | xxx | 2 | 0.625 |

and I configured a custom tile source with this.

```javascript

    <script type="text/javascript">

		//contentDiv width, height 100% 
        var viewer = OpenSeadragon({
            // debugMode: true,
            id: "contentDiv", 
			 tileSources: {
	          	tileSize: 512,
	          	minLevel: 0,
	          	maxLevel: 5,
	          	height: 40_000,
	          	width: 60_000,
	        	getTileUrl: function (level, x, y) {
	        		return "http://localhost:8083/slide/0001/{level}/{x}/{y}.jpeg"
	        	}
		      },
            showNavigator: true
        });
    </script>

```

So for most of the parts the openseadragon library has been flawless, except in trying to reproduce the objectives / magnification from microscope or native viewer (provided by manufacturing scanner)

What I have observed is that if we initialize the viewer at full screen resolution which is 2560X1440 I can very closely able to reproduce magnification hence, the real world aspect of an object.

Here is an example, same config, looking at a small white blob/tissue using objective / magnification 5x on left is openseadragon, image on the right is native viewer. (They are very closelly matching but not bang on)

![image](https://github.com/openseadragon/openseadragon/assets/6196152/27de1add-dc22-4425-b02e-00d616db614a)

Now where is the interesting part, is if I initialise the opensea dragon with half of the screen size 1280x720 and I zoom in to the same area at the same objective / magnification which is 5x, they are million miles away.

![image](https://github.com/openseadragon/openseadragon/assets/6196152/75ab701e-4554-42c7-b8fe-fe0a6a17092e)

We have been utilising the suggestion from #1462 (https://github.com/openseadragon/openseadragon/issues/1462) so we are using `viewportToImageZoom` to display current zoom, but something is not adding up. 

As an observation, I have hard-coded the initial div size to be exactly the dimension of the image at 1x. 
therefore the initial `contentDiv` width is `2988px` and we can now match the exact aspect ration as the original microscope and/or native viewer. 

Do you have some suggestions on what is going on here, or what we are not doing right?

Is there any additional information we need to provide the library at initialisation?

Please forgive me if i have not included enough information or too much. 

Best Regards

ade

**Comment by iangilman** [comment]
OSD zoom values are always relative to whatever size fills the width of the viewport. When the image exactly fills the viewport horizontally, that's zoom 1. When you can see only half of the image width in the viewport, that's zoom 2. This allows you to create experiences that are consistent across a wide range of devices. 

Sounds like in your case, you're not as concerned about the overview, but the individual pixels. In that case, you're interested in the image zoom, not the viewport zoom. If you want to zoom to where the image is at full resolution, that's image zoom of 1. To go there, you can use: 

```
viewer.viewport.zoomTo(viewer.viewport.imageToViewportZoom(1));
```

I guess I'm just repeating myself from #1462, and it sounds like you were on the right track; you were just using `viewportToImageZoom` when you should have used `imageToViewportZoom`. 😄

**Comment by ade90036** [comment]
Hi, 

Thanks for the prompt reply.

Apologies, i know your pain, i hate too repeating  :smile_cat: 

After re-reading #1462 with the suggestions above it started to make proper sense. 

I guess still very much confused between the zoom types (`image`, `viewport`) although even if i don't understand the need for it i assume there is a good use case of this. 

Although if you are displaying an CAD data, GIS Data, Pathology data, Google Maps, where you need to interpret the virtual image to a real world dimension working with the `image` zoom would be the most intuitive?

Is there any pages / wikis that explain the inner working of openseadragon library.

Regards

ade

**Comment by iangilman** [comment]
No worries :) 

Unfortunately there isn't really a good overview of the inner workings. Would be a good thing to create sometime! This has some good info though:

https://openseadragon.github.io/examples/viewport-coordinates/

As for image versus viewport zoom, I guess you can think about it as the difference between "bottom up" versus "top down". You're doing scientific imaging, so you care a lot about the individual pixels, so your perspective is bottom up (image zoom). This is the same perspective that Photoshop has. You want to think about things in terms of ratios of actual pixels.  

Lots of people use OpenSeadragon to display artworks or manuscripts, and they don't care about the individual pixels as much as they care about the overall piece. When the viewer opens, they want the entire artwork to appear in whatever space is available. Their perspective is top down (viewport zoom). Maybe they want to zoom the user in to a particular detail that is 25% of the overall image area. Viewport zoom allows them to do this without worrying about the resolution of the image. In fact, you can replace a low resolution image with a high resolution one, and all of the viewport zoom calculations are the same. You can say "her earring is here" in coordinates that are relative to the entire image and therefore don't change when the resolution changes. 

Of course one of those perspectives has to be dominate in the library, and the choice originally made was viewport zoom, as the original Seadragon philosophy was in moving away from thinking about pixels at all... You just have an image and you can assume it has infinitely deep pixels. We're still not fully living in that world, but as our imaging technology gets better and our displays get better, we keep getting closer. 

I hope that helps shed some light!

**Comment by iangilman** [comment]
Indeed... Perhaps in the future, we could add a more direct API for the image zoom perspective. 

Glad it's working! :)
