### ISSUE TITLE
Question about IIIF extensions

### ISSUE THREAD

**Issue by brecht-vermeersch** [openseadragon/openseadragon#2372]
From the docs:
Request information beyond the scope of the existing parameters could be passed to an image server as query parameters.  (https://iiif.io/api/image/3.0/#49-extensions)

I don't think it is currently possible to add query parameters. How can I extend the IIIFTileSource?

**Comment by brecht-vermeersch** [comment]
My use case is rendering a pdf in separate layers

**Comment by brecht-vermeersch** [comment]
Current workaround
`
/** @ts-ignore */
extend(IIIFTileSource.prototype, {
  _originalGetTileUrl: IIIFTileSource.prototype.getTileUrl,

  getTileUrl(level: number, x: number, y: number): string {
    return this._originalGetTileUrl(level, x, y) + "?layer=1";
  },
});
`

**Comment by pearcetm** [comment]
> Current workaround

This seems like a fine approach to me. Are you still having problems with it?
