### ISSUE TITLE
any way to control the tile request order?

### ISSUE THREAD

**Issue by chengdonglin** [openseadragon/openseadragon#2383]
when I panning , scroller the image quickly, It will fetch much tiles, when I end the action, so the visibility area image can not load immediately，so it cause delay , not smooth enough. I have optimization server response at within 100ms, see below image.  can I seeting by openseadragon to optimization it?
![image](https://github.com/openseadragon/openseadragon/assets/28192795/edbd0654-18fb-4c94-b472-75835a285935)

here are some my openseadragon options:

`
 
     animationTime: 0.5,
    blendTime: 0.5,
    immediateRender: true,
     imageLoaderLimit: 0
     
     
       this.viewer.addHandler('pan', () => {
        this.viewer.imageLoader.jobLimit = 1;
        this.viewer.addOnceHandler('animation-finish', () => {
          this.viewer.imageLoader.jobLimit = 100;
        });
      });
`

**Comment by iangilman** [comment]
That code you shared is what I would suggest. Is it not helping?

**Comment by iangilman** [comment]
An answer to your question about controlling the tile request order, no, there's not a mechanism for that. Whenever there's a chance to load a tile, OSD loads whatever is optimal for the current viewport. The best you can do is limit it from queueing up images during the pan, like you've done.

**Comment by chengdonglin** [comment]
> imageLoaderLimit

yes, It can help, But not smooth, the edge visible area delay obvious， flow the  network waterflow, I think the get tiles not parallel request? maybe imageLoaderLimit setting not work.

**Comment by iangilman** [comment]
By "edge visible area delay obvious" you mean that you can see empty space before the tiles load in? This is caused by `immediateRender`. If you turn that back off, you'll never see empty space. 

And yes, multiple tile requests are never in parallel... Each frame we pick a single tile to load.

**Comment by iangilman** [comment]
Regarding the waterfall, here's some discussion on possibly doing things in parallel: https://github.com/openseadragon/openseadragon/issues/2384.

**Comment by chengdonglin** [comment]
> By "edge visible area delay obvious" you mean that you can see empty space before the tiles load in? This is caused by `immediateRender`. If you turn that back off, you'll never see empty space.
> 
> And yes, multiple tile requests are never in parallel... Each frame we pick a single tile to load.

if immediateRender set false, will request more tiles, so I set true, "edge visible area delay obvious" I mean when I move the edge image beigin is blurred, after 1s load complete

**Comment by iangilman** [comment]
Okay, cool; just making sure. 

Well, I'm not sure what else to suggest. The discussion in #2384 may lead to an improvement. Also, as mentioned there, if you can, going to a higher tile size might help.
