### ISSUE TITLE
gesture Rotate image question

### ISSUE THREAD

**Issue by chengdonglin** [openseadragon/openseadragon#2388]
I want to rotate image by gesture, from gesture config by below, It not work,

`
        gestureSettingsPen: {
          pinchRotate: true
        },
        gestureSettingsUnknown:{
          pinchRotate: true
        },
`

**Comment by iangilman** [comment]
I think the only input device that supports pinch rotate is touch, since it's the only one that supports multiple simultaneous touch points. 

`gestureSettingsTouch: { pinchRotate: true }`

I'm curious, though, how were you imagining it might work with pen?

**Comment by chengdonglin** [comment]
> I think the only input device that supports pinch rotate is touch, since it's the only one that supports multiple simultaneous touch points.
> 
> `gestureSettingsTouch: { pinchRotate: true }`
> 
> I'm curious, though, how were you imagining it might work with pen?

I think maybe draw an arc shape, then it can rotate

**Comment by iangilman** [comment]
> I think maybe draw an arc shape, then it can rotate

Cool idea!
