### ISSUE TITLE
SVG filter not applied when using full screen

### ISSUE THREAD

**Issue by R-W-C** [openseadragon/openseadragon#2391]
In my HTML page I have got a checkbox. When it is it checked, a SVG filter is applied to the image. This works just fine, except when switching to full screen mode.

**My question What should I do to have the filter also applied in full screen mode?**

See https://codepen.io/r-w-c/pen/bGQZMJb

Check the checkbox, click on the 'full page button' and see what I mean. The filter is not applied.

**Comment by iangilman** [comment]
For historical reasons, our fullscreen implementation takes the viewer out of the normal DOM location and hides the other elements. This means your SVG element is getting hidden (and the viewer element is no longer next to it).

There's an issue to change this, but no one has taken it on yet: 

https://github.com/openseadragon/openseadragon/issues/2205

If you're interested, you could take it on. There's also some discussion of workarounds there.

**Comment by R-W-C** [comment]
@iangilman : Thank you for your reply. 

Unfortunately I don't have the time to pick this up, but your remark "hides the other elements" pushed me in the right direction. 

I wondered what would happen if I put my SVG in a div which is not removed. 
I have my bar with buttons outside the viewer, and it is displayed in full screen mode, so it is not removed and a good candidate to see if my filters would be applied... and yes they are applied as hoped/expected. 
I could also hide my SVG with display:none. 

I will add a new CodePen to show the workaround.

**Comment by R-W-C** [comment]
Issue closed. Thanks @iangilman

**Comment by iangilman** [comment]
Great! Glad it illuminated the solution. 

Your CodePen looks good. It doesn't seem to work on Firefox though, FYI.
