### ISSUE TITLE
OpenSeadragon constructor Cannot read appendChild of null

### ISSUE THREAD

**Issue by Edo2610** [openseadragon/openseadragon#2396]
Sometimes when I use the Openseadragon contructor I get this error.

![image](https://github.com/openseadragon/openseadragon/assets/39258457/eb9d0ace-6f46-4792-a2d9-26dd8e630285)

There isn't a regular pattern to reproduce the error, maybe 2 or 3 times on 10 contructor will go in this error.  
My simple code is the following

![image](https://github.com/openseadragon/openseadragon/assets/39258457/35c1909c-b384-4c37-85c1-e1ffe47b8f94)

And it also occurs when if I use ngZone for performance like official guide suggets
![image](https://github.com/openseadragon/openseadragon/assets/39258457/82d3671e-490b-4e54-aca8-21c948afa98a)

Do someone have a solution? It is a known bug or do I missing somthing?

**Comment by iangilman** [comment]
Sounds like it's unable to find the containing element it's supposed to attach itself to. How are you specifying its container? Can you check to make sure it exists before creating the viewer?

**Comment by Edo2610** [comment]
You are right!! Thank you.
I have an *ngIf on the container that was activated when the image is ready and after that I create the viewer; but sometimes the DOM require more time to render the container and the contructor went in error.

**Comment by iangilman** [comment]
@Edo2610 Good to know!
