### ISSUE TITLE
Trouble with Zoomify Tiles

### ISSUE THREAD

**Issue by jthommes** [openseadragon/openseadragon#2401]
I am trying to convert from Zoomify to openseadragon. I would like to use my existing Zoomify tile files. I am not getting an image (the page is blank except for the pan/zoom controls from openseadragon). I have tried to implement the "in line" parameters since the zoomify "Image Properties .XML file is non standard for openseadragon. I am pretty sure I am getting something wrong in the code or folder paths.

Here is a link to my zoomify image:
https://jthommes.com/Astro/Zoom/NGC6823_FSQ_PI1_AF2.htm

Here is a link to the openseadragon (non) image:
https://jthommes.com/Astro/Zoom/NGC6823_FSQ_PI1_AF2x.htm

I have attached a snipped image of my file folders.

Can you spot what I am doing wrong? Maybe I just need to collapse the TileGroup_n (0, 1, 2) into one folder?? Any help you can provide would be a great help. Also, let me know if it is not possible for some reason to use my zoomify tiles. If that is the case, I need a desktop App to convert full size images to tiles that are compatible with openseadragon.

You can get source code from the (non) image openseadragon page, but I have included it below:

========================================= 

![Code](https://github.com/openseadragon/openseadragon/assets/143911582/ced85771-762a-406b-929d-b03de0dc07c0)

===========================================
![Folder paths](https://github.com/openseadragon/openseadragon/assets/143911582/2acdc7f9-d7b2-42f6-b981-5b5a04e963a7)

**Comment by Benomrans** [comment]
Hello,
It seems to me that the tiles url should be like this :

tilesUrl:   "https://jthommes.com/Astro/Zoom/NGC6823_FSQ_PI1_AF2/",

as it should point to the folder of the tiles.

**Comment by jthommes** [comment]
> Hello, It seems to me that the tiles url should be like this :
> 
> tilesUrl: "https://jthommes.com/Astro/Zoom/NGC6823_FSQ_PI1_AF2/",
> 
> as it should point to the folder of the tiles.

That did it! (Sometimes I can be a real klutz). Thanks for the help!
