### ISSUE TITLE
Asynchronous load of getTileUrl

### ISSUE THREAD

**Issue by abiswas97** [openseadragon/openseadragon#2403]
Hi,

Opening an issue for a follow up on this [discussion](https://github.com/openseadragon/openseadragon/discussions/2400). 

I'm trying to implement reading DZIs from the filesystem, and my current bottleneck is the synchronous function call of getTileUrl in OSD 3.0.0. 

Here's some relevant code of what I'm trying to do (forgive the unorganized thoughts, this is a very rough idea)
```js
  // Function to get a handler to the DZI file, and populate a tileSource state with the base dzi data (width, height, tileSize, tileOverlap)
  const fileAccessHandler = async () => {
    try {
      const [fileHandle] = await window.showOpenFilePicker({
        types: [
          {
            description: "DZI File",
            accept: {
              "application/xml": [".dzi"],
              "application/json": [".dzi"],
            },
          },
        ],
        multiple: false,
        excludeAcceptAllOption: true,
      });
      
      // Reset folder handle if file handle changes
      if (fileHandle !== dziFileHandle) {
        setDziFolderHandle(null);
      }
      setDziFileHandle(fileHandle);

      const file = await fileHandle.getFile();
      const dziData = await parseDzi(fileHandle);

      // Set the TileSource with the height, width, tileSize, tileOverlap
      setTileSource({
        ...dziData,
      });
    } catch (e) {
      console.log(e);
      setDziFileHandle(null);
    }
  };

  const directoryAccessHandler = async () => {
    try {
      const directoryHandle = await window.showDirectoryPicker();

      setDziFolderHandle(directoryHandle);
      
      // Add the getTileUrl handler to the existing tileSource state
      setTileSource((prev) => ({
        ...prev,
        getTileUrl: async (level, x, y) => {
          // Utility function that handles getting a nested file from a given root directory handle
          const fileHandle = await getNestedFileHandle(directoryHandle, `${level}/${x}_${y}.png`);
          const file = await fileHandle.getFile();
          
          // Since a URL is required, create a blob URL that can be read for the image data
          const fileUrl = URL.createObjectURL(file);
          return fileUrl;
        },
      }));
    } catch (e) {
      console.log(e);

      setDziFolderHandle(null);
    }
  };
```

This currently fails as filesystem api calls are async. I found some similar discussions ([1672](https://github.com/openseadragon/openseadragon/issues/1672), [1699](https://github.com/openseadragon/openseadragon/issues/1699), [1707](https://github.com/openseadragon/openseadragon/issues/1707)), but wasn't able to get much traction on how to proceed.

**Comment by pearcetm** [comment]
I implemented something similar to what you're trying to do in the GeoTiffTileSource plugin.

The gist of it is to let `getTileUrl` remain synchronous, and just define the async method to actually get the data - but don't do the asynchronous data loading there. Then, override `downloadTileStart` to perform the load asynchronously. 

https://github.com/pearcetm/GeoTIFFTileSource/blob/a66e0e6376a708da6a55772f30751e6eb13c4ed0/GeoTIFFTileSource.js#L169-L196

**Comment by abiswas97** [comment]
Thanks!! This gives me a better idea, but I'll have to revisit this to wrap my head around it. This looks like an implementation that works purely as a plugin without having to maintain a forked OSD?

I came across another great repository [towa](https://github.com/pandaxtc/towa) that maintains a [fork of OSD](https://github.com/pandaxtc/openseadragon) with an ImageLoader that can accept a fileHandle. 

The geoTIFF plugin looks great btw, I'll have to play around with it!

**Comment by abiswas97** [comment]
Closing this as @pearcetm and @pandaxtc 's approaches have clarified my questions here.
