### ISSUE TITLE
Using fullscreen causes duplication of the viewer each time

### ISSUE THREAD

**Issue by SamGalanakis** [openseadragon/openseadragon#2406]
![image](https://github.com/openseadragon/openseadragon/assets/47306720/5f1ea40e-02f5-4791-a8fb-ee41c0fa1491)

I am initializing the viewer as  so :

```
 let image_container = document.getElementById( `image_container_${row_data['sequence_id']}`) 
  let tilesources = [];
  Object.values(row_data.images).forEach(image => {
    tilesources.push({
      type:'image',
      url:image["image_url"]
    })
  });
  let openseadragon_viewer = OpenSeadragon({
    element: image_container,
    sequenceMode: true,
    showReferenceStrip:true,
    prefixUrl:
      'https://cdn.jsdelivr.net/npm/openseadragon@4.1.0/build/openseadragon/images/',
    tileSources: tilesources
  })
```

The viewer works fine until I press full screen which works but when returning to page after full screen the image is duplicated below the original. This happens each time full screen is used. The problem happens with single or multiple images (sequence) in the viewer.
Each duplicated viewer is fully interactive as the original.
In other places where I have multiple viewers If I click full page on one of them others also get duplicated.

This is the html snippet of the duplicated element (original + 2 here)
[html_snippet.txt](https://github.com/openseadragon/openseadragon/files/12547225/html_snippet.txt)

I am using openseadragon@4.1.0

Thanks in advance

**Comment by iangilman** [comment]
That's very strange! There's nothing in the code you shared that seems like it would cause this, and it certainly doesn't happen normally (e.g. https://openseadragon.github.io/). Can you share a link to your project, or make a simplified repro on CodePen or such?

**Comment by SamGalanakis** [comment]
Was able to reproduce it here:

https://codepen.io/Sam-Galanakis/pen/KKbaoyw

It seems to be because I am calling init in alpine js, if I just call initialize_row in the script it seems to work fine, Any idea why that might be?

**Comment by SamGalanakis** [comment]
Yeah that was it, was able to skip it by storing the number of call on an outer x-data and skipping if called before. Updated the codepen in case someone else comes across this. Thanks for the help and the very useful library.
