### ISSUE TITLE
Navigator Display region position might not be correct on a high zoom level

### ISSUE THREAD

**Issue by aciurea** [openseadragon/openseadragon#2408]
Hello and very good work with Openseadragon,

I have a scenario where the display region of the navigator on a very deep zoom level (>20x) is not positioned correctly.

I have a border of 3px for the display region and when zooming (mouse position stays fix) after 20x zoom level, the displayRegion box doesn't stay in the same position but moves a few pixels to the right/left or to the bottom/top.

Is it possible that the `left and top` position when zooming to not update correctly?

I want to mention that at 40x zoom level, the width and height of the displayRegion box has 1px.
In the official docs, the zoom level is not that deep and you cannot spot the misalignment very well.

It might be related to this issue but I am not 100% sure. https://github.com/openseadragon/openseadragon/issues/2127

Greetings

**Comment by pearcetm** [comment]
Is it the same as the issue described in https://github.com/openseadragon/openseadragon/issues/2264? In that case it had to do with `box-sizing: border-box` CSS, which messed with the display rectangle positioning. It's since been fixed.

**Comment by aciurea** [comment]
Hey, I am using 4.0.0. I updated to 4.1.0 as you suggested and the problem is gone.
Thanks a million

**Comment by aciurea** [comment]
Since my issue
