### ISSUE TITLE
scale and level has any relation?

### ISSUE THREAD

**Issue by chengdonglin** [openseadragon/openseadragon#2412]
My tiff file have multi scale, I want to set multi button to zoomTo the target scale, so what the scale and  level has any relation? can I calculator the level by scale?

**Comment by nein09** [comment]
Hi - the answer is yes, depending on what you want to do. Have you had a look at https://github.com/openseadragon/openseadragon/wiki/FAQ#zoom ? Did that help at all? It sounds like you might need to use https://openseadragon.github.io/docs/OpenSeadragon.Viewport.html#imageToViewportZoom for your buttons.

**Comment by chengdonglin** [comment]
> Hi - the answer is yes, depending on what you want to do. Have you had a look at https://github.com/openseadragon/openseadragon/wiki/FAQ#zoom ? Did that help at all? It sounds like you might need to use https://openseadragon.github.io/docs/OpenSeadragon.Viewport.html#imageToViewportZoom for your buttons.

Thanks, I will try it.
