### ISSUE TITLE
Problems using `new OpenSeadragon.MouseTracker`

### ISSUE THREAD

**Issue by zmomozq** [openseadragon/openseadragon#2424]
Hello, can I prevent the event bubbling and default events of the bound element when using `new OpenSeadragon.MouseTracker`? For example, the bound element is an `overlay`, and I can avoid the event when I click on this `overlay` Bubbling delivers this event to the view

**Comment by msalsbery** [comment]
@zmomozq 

[This pen](https://codepen.io/msalsbery/pen/dyOeXqO) has examples of most of the ways you can fine tune event propagation
