### ISSUE TITLE
Fit canvas to the scaled image OR prevent panning unless the image overflows

### ISSUE THREAD

**Issue by jmichalicek** [openseadragon/openseadragon#2441]
I would like to prevent panning unless the image itself goes outside of the bounds of the viewer. So if a user zooms out, no panning because there's no need, or if the scaled image doesn't take the full height of the viewer there's no reason to pan up and down (which looks like moving the image up and down), etc.

My thoughts on how to do this have been:

* Find the size of the scaled image after it loads and then update my div OpenSeadragon mounts into to match that size
* Determine if the container has overflow and disable panning in each direction it does not
* Figure out what size the scaled image will be and set the height and width on the div before initializing OpenSeadragon

I feel like the first two bullet points should be doable and I'm just missing it. Everything I have tried so far either matches the size of my div container I mount OpenSeadragon to or the original full size of the image I am loading.

**Comment by msalsbery** [comment]
@jmichalicek I think the second bullet point is the easiest option. I personally wouldn't want to also have to handle potential html layout issues when a viewer zoom changes.

The [OpenSeadragon.Viewport class](https://openseadragon.github.io/docs/OpenSeadragon.Viewport.html) has the methods to handle the coordinates and any conversions you need.

A [Viewer canvas-drag event](https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#.event:canvas-drag) handler could be used to prevent dragging when necessary

**Comment by jmichalicek** [comment]
Thanks @msalsbery I had been looking at those methods for coordinates on the Viewport class and playing with them, but straight up brainfarting on it.

I ended up with this to get the functionality I wanted when going at it with a fresh brain instead of doing it after work.

```
viewer.addHandler('canvas-drag', (dragEvt) => {
      const imageBounds = viewer.world.getItemAt(0).getBounds()
      const viewportBounds = viewer.viewport.getBounds()

      const hasTopOverflow = viewportBounds.y > 0
      const hasBottomOverflow = viewportBounds.y + viewportBounds.height <= imageBounds.height
      const hasLeftOverflow = viewportBounds.x > 0
      const hasRightOverflow = viewportBounds.x + viewportBounds.width <= imageBounds.width

      const preventDragUp = dragEvt.delta.y < 0 && !hasBottomOverflow
      const preventDragDown = dragEvt.delta.y > 0 && !hasTopOverflow
      const preventDragRight = dragEvt.delta.x > 0 && !hasLeftOverflow
      const preventDragLeft = dragEvt.delta.x < 0 && !hasRightOverflow
      if (preventDragUp || preventDragDown) {
        dragEvt.delta.y = 0
      }
      if (preventDragLeft || preventDragRight) {
        dragEvt.delta.x = 0
      }
    })
```
