### ISSUE TITLE
Load tiles from the closest level before tiles from "covered" layers

### ISSUE THREAD

**Issue by ibex-lior** [openseadragon/openseadragon#2442]
Hi,
In our project we are using OSD to load tiles from a remote server since they are created on the spot.
When a user zooms fast it seems like the tiles are loaded from the farthest level to the closest one by one, and the render time and load time of each causes a bad experience to the user.

Is there a way to make the viewer render the tiles that are in the FOV before (or instead of) loading the ones that will be covered by them?

Thanks.

**Comment by iangilman** [comment]
Yes, use `immediateRender: true` in your options when creating the viewer.

**Comment by ibex-lior** [comment]
I went over the properties a lot and somehow still missed it :)
