### ISSUE TITLE
CORS - loading simple image by HTML element

### ISSUE THREAD

**Issue by TomDijkema** [openseadragon/openseadragon#2444]
Hi,

We have been using OSD for quite some time now and really enjoy the benefits of the package!
Only recently we have been encountering issues with the CORS protocol.

As we are loading simple images from a foreign origin, by using the image tile with given url, it relies upon the foreign image server to provide the CORS headers upon request.
Some of these servers (which are not under our control) do not or strictly provide the CORS headers blocking the request from OSD.
Fetching the image server apart from OSD or using HTML image elements to load the images by url work as expected.

I was wondering if you could explain why the fetch request from OSD fails to do so, compared to the default HTML image element?

Secondly, as a solution to this I thought of providing the loaded HTML image element, since this can be successfully loaded, to OSD as the source for the tile.
However, I am not able to find any documentation or similar questions about this particular topic.

Would it be possible to load an already fetched image in OSD?

Thanks in advance!

~ Tom

**Comment by pearcetm** [comment]
Could you make a demo to reproduce? codepen or similar?

**Comment by iangilman** [comment]
That's strange... OSD should open image files just fine even without CORS. Or are you referring to the DZI file? Like @pearcetm says, it would be good to see your code.

**Comment by pearcetm** [comment]
Have you tried the various options related to CORS (`crossOriginPolicy`, `axaxWithCredentials`, and (indirectly) `buildPyramid`)? See https://openseadragon.github.io/docs/OpenSeadragon.ImageTileSource.html#ImageTileSource

**Comment by TomDijkema** [comment]
Hi, sorry for the late reply.

I am using OSD integrated with the Annotorious version 3 package for React.
Currently, this my (simplified) setup:

```
const OSDOptions: OpenSeadragon.Options = {
        prefixUrl: "https://cdn.jsdelivr.net/npm/openseadragon@3.1/build/openseadragon/images/",
        crossOriginPolicy: 'Anonymous',
        ajaxWithCredentials: false,
        gestureSettingsMouse: {
            clickToZoom: false
        }
};
    
/* OnLoad: fetch image details */
useEffect(() => {
       new Promise((resolve, reject) => {
            const image = new Image();

            image.src = digitalMedia.digitalEntity['ac:accessUri'];

            image.onload = (image) => resolve(image);
            image.onerror = () => reject;
        }).then((image: any) => {
            setImage(image.target);

            if (viewerRef.current) {
                viewerRef.current.open({
                    type: 'image',
                    url: digitalMedia.digitalEntity['ac:accessUri']
                });
            }
        });
}, [mediaUrl]);

return (
        <div className="w-100 h-100">
            <OpenSeadragonAnnotator className="h-100"
                adapter={W3CImageFormat('https://iiif.bodleian.ox.ac.uk/iiif/image/af315e66-6a85-445b-9e26-012f729fc49c')}
                keepEnabled={false}
                drawingEnabled={annotoriousMode}
                pointerSelectAction={SelectAction}
            >
                <OpenSeadragonViewer className="openseadragon h-100"
                    ref={viewerRef}
                    options={OSDOptions}
                />

                <OpenSeadragonPopup
                    popup={() => (
                        tooltip
                    )}
                />
            </OpenSeadragonAnnotator>
        </div>
);
```
First I define the OSD options with a very basic configuration, using the CrossOriginPolicy and AjaxWithCredentials as mentioned here: https://openseadragon.github.io/examples/tilesource-image/.
The second part renders the image into OSD, it gets triggered when the user selects a new image (mediaUrl).
It fetches the image for other purposes, and if it gets through, tries to call the load method from a ref that refers to the OSD viewer.
The last part returns the Annotorious Annotator which holds the OSD canvas inside of it.

I tried playing around with the parameters, I can get the image to load when I set CrossOriginPolicy to false, but then I get a:
`Uncaught DOMException: The operation is insecure.`

If I to the CrossOriginPolicy to 'Anonymous', I get a CORS error in the console and it displays the following message in the canvas:
`Unable to open [object Object]: Error loading image at https://mediaphoto.mnhn.fr/media/1681821627482HLYgnWjzyeRM9kvB`

When I try to load any image from a server which does not enforce CORS, everything works as expected.

**Comment by pearcetm** [comment]
For images from servers without CORS support you probably need to use the `buildPyramid: false` option for your tile source. To build a pyramid the library needs access to pixel data via canvas operations, which isn't allowed on "tainted" canvases (those with data from other origins without CORS). My guess is the pyramid building step is where you're getting the  `Uncaught DOMException: The operation is insecure.` See https://openseadragon.github.io/examples/tilesource-image/ for some example configurations.

**Comment by TomDijkema** [comment]
That sounds like the logical solution!
It might be the Annotorious package, but the `buildPyramid` option does not seem to be available upon the OpenSeaDragon Options type or the tile sources type.
Disabling the typing does not help unfortunately.

Just of a side note: the DOMException also seems to disable all the behavior of the canvas like moving around and zooming.

**Comment by iangilman** [comment]
Are you saying you're using TypeScript and `buildPyramid` isn't part of the types you're using? It should be part of the tile source, but it could be missing from the types.

**Comment by pearcetm** [comment]
@TomDijkema I see from the discussion at https://github.com/annotorious/annotorious/issues/202 that the root of the issue was an image server that doesn't support https. Unfortunately there's nothing that can be done client-side to get around that. However, if you have a server in the future that serves you images over https without CORS settings, hopefully the settings you've tried here will get it to work for you.

**Comment by TomDijkema** [comment]
Hi, apologies again for the late response.

Yes that is right. I thought that I could maybe find a workaround for the CORS protocol, now realising this is not possible and really a problem with the image server rather than OSD or the way I fetch the data.
I tried the setup you provided above with one of the image servers that does enforce CORS, which perfectly displays the image as expected.

Thanks for the explanations! The CORS protocol is always a bit of a issue, trying to find out how to get it working properly.
I'll close the issue as this answers my question.
