### ISSUE TITLE
have some packages for Android app  ? 

### ISSUE THREAD

**Issue by chengdonglin** [openseadragon/openseadragon#2446]
have some packages for Android app  ?

**Comment by iangilman** [comment]
I don't understand what you mean. Are you looking for a Java/Kotlin version of OSD?

**Comment by chengdonglin** [comment]
> I don't understand what you mean. Are you looking for a Java/Kotlin version of OSD?

yes, have version for Kotlin?

**Comment by iangilman** [comment]
I'm not aware of any version of OSD that's not JavaScript. Presumably there are tiled image zoomable viewers written in Java or Kotlin, but I don't know what they are.

Another option would be to create a webview in your Android app and run OSD inside that.
