### ISSUE TITLE
Overlays don't get horizontally fliped when the image it's flipped

### ISSUE THREAD

**Issue by Zardoz89** [openseadragon/openseadragon#2450]
So, you open an image with an overlay that draws a rectangle over it. If using the OSD intrface, an user flips horizontally the image, the overlay don't get flipped. At least, it's strange, specially when it works correctly using the rotation buttons. Here is a example :

Original image + overlay :
![image](https://github.com/openseadragon/openseadragon/assets/888483/c627f754-5c87-4010-9103-e8873d382ae0)

Flipped image + overlay : 
![image](https://github.com/openseadragon/openseadragon/assets/888483/0b6989db-30fa-486c-9863-3d573aac627c)

**Comment by iangilman** [comment]
Indeed, this is a known issue: https://github.com/openseadragon/openseadragon/issues/1614

Evidently no one has decided to take it on. Let me know if you are interested in working on it and I can point you in the right direction.

**Comment by BeebBenjamin** [comment]
I need this fixed at some point too.  I can attempt to fix it under guidance.

**Comment by Zardoz89** [comment]
Also, I could try to help with it.

**Comment by iangilman** [comment]
@BeebBenjamin @Zardoz89 Fantastic! Presumably the fix will go into this function:

https://github.com/openseadragon/openseadragon/blob/6abcc76a93ee3369267908f0a80641dc171440ed/src/overlay.js#L296

You can probably get some inspiration from the rotation handling.

I expect the typical user will want the overlay position flipped but not the actual overlay contents flipped (i.e. they wouldn't want the overlay text to be backwards). Though I could see an argument for the other way. What do you think?

I'll leave it to you to figure out who is taking the lead on this.

**Comment by BeebBenjamin** [comment]
I think I have something working for rotate, I'm in the right place.  However, I am currently wrestling with rotate + flip.  Might have something to look at soon though.

**Comment by BeebBenjamin** [comment]
When flipped, the overlay rotates in the opposite direction.  If I can get some help narrowing down where the rotation happens I might be able to change the direction of the rotation when flip is detected.

**Comment by BeebBenjamin** [comment]
OK, I figured it out.  There needed to be an inversion in the `drawHTML` rotate value if `viewport.flipped`.  I'll put in the PR later today.
