### ISSUE TITLE
i18n not working correctly

### ISSUE THREAD

**Issue by Zardoz89** [openseadragon/openseadragon#2451]
So, following the example of i18n, I call OpenSeaDragon.setString(XXX, YYY), but when OSD is instantiaded to create the OSD viewer, the setted i18n values are reset on some way and I get the default English values !

Here is a example : https://www.digibis.com/digibisbib_rwd_qa/es/media/group/7.do?presentation=page&position=4 (use "invitado" as user and password , I can't find now an example of this outside our QA environment to show this and we haave put on a temporally access under simple http auth)

The most weird thing, it's that debuging this, I see that the I18N object it's begin modified by setString() with the translated values correctly ... and at a some point, it get replaced by the default I18N values ! And I can't find where or how this is happening

setString() being called and the I18N object being modified by it correctly :
![setString being called and the I18N object being modified by it correctly](https://github.com/openseadragon/openseadragon/assets/888483/f5f664b9-4f4a-483a-81a9-32d5ed3a5be6)

Before instantiating OSD, getString returns the correct value :
![imagen](https://github.com/openseadragon/openseadragon/assets/888483/a799d09e-07f0-4134-90ae-505f23a3940c)

And I18N being replaced by the original values ! : 
![imagen](https://github.com/openseadragon/openseadragon/assets/888483/eee34980-0a5d-498f-be2f-a4f21c8c208a)

And the most funny thing, it's that I can't see this happening on the example page about I18N

**Comment by iangilman** [comment]
That certainly shouldn't be happening! 

Looking at your code, I see the OpenSeadragon script is loaded twice, once at line 41 and once at line 17555. Perhaps this is the source of the problem? You load OpenSeadragon, then customize the strings, then replace it with another fresh OpenSeadragon that has the strings reset.

**Comment by Zardoz89** [comment]
Wow! I didn't noticed it. Indeed, was that the problem. I just removed the duplicated load on our development code and fixed the issue. Thanks!
