### ISSUE TITLE
Fix JSDocs for new drawers

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#2460]
@pearcetm After merging #2310 it occurred to me to test the JSDocs for the new classes. It looks like a number of methods in the various drawers aren't showing up. Here's what I see for `DrawerBase`:

<img width="906" alt="image" src="https://github.com/openseadragon/openseadragon/assets/338989/96f9402e-140d-41ea-8f5c-4e3daa1ef808">

I know you wrote lots of great documentation for the class! Looking at it it looks like JSDoc should be picking them up, and JSDoc isn't giving any errors when I run `grunt doc`, so I'm not sure what the problem is. Hopefully it's a simple fix!

**Comment by pearcetm** [comment]
That's weird... I agree, hopefully an easy fix, but I am not a jsdoc guru unfortunately! I'll try to look into it though.

**Comment by pearcetm** [comment]
Seems like this problem arises at the intersection of two things:
1) it affects ES6 classes
2) when they use `@memberof OpenSeadragon` to put the class into the `OpenSeadragon` namespace

Removing `@memberof OpenSeadragon` from the class makes the docs work great, but then the class doesn't link to the namespace correctly.

**Comment by iangilman** [comment]
I'm not a JSDoc guru either, but we seem to be muddling through somehow 😄 

I was able to get it to work by getting rid of the `@memberof` and explicitly stating the class to be `OpenSeadragon.DrawerBase`. I also had to change the actual class definition to `OpenSeadragon.DrawerBase` rather than `$.DrawerBase`. Like so:

```
/**
 * @class OpenSeadragon.DrawerBase
 * @classdesc Base class for Drawers that handle rendering of tiles for an {@link OpenSeadragon.Viewer}.
 * @param {Object} options - Options for this Drawer.
 * @param {OpenSeadragon.Viewer} options.viewer - The Viewer that owns this Drawer.
 * @param {OpenSeadragon.Viewport} options.viewport - Reference to Viewer viewport.
 * @param {Element} options.element - Parent element.
 */

OpenSeadragon.DrawerBase = class DrawerBase{
```

**Comment by pearcetm** [comment]
Ok cool. I was getting it to sort of work with a combination of other tricks, but this is cleaner. I've updated the docs for `DrawerBase` and the three new drawer classes, and opened a PR.

**Comment by iangilman** [comment]
Looks great!
