### ISSUE TITLE
Setting dragToPan to false has no effect for touch gestures

### ISSUE THREAD

**Issue by jonasengelmann** [openseadragon/openseadragon#2463]
Setting dragToPan to false for ~~either mouse or~~ touch gestures has no effect. I was able to track the issue down to the [onCanvasDragEnd](https://github.com/openseadragon/openseadragon/blob/f9a8b97cf965f4625977021859d7aaa0cb6a272f/src/viewer.js#L3203) function. If we add the condition `gestureSettings.dragToPan` [here](https://github.com/openseadragon/openseadragon/blob/f9a8b97cf965f4625977021859d7aaa0cb6a272f/src/viewer.js#L3239), it fixes the issue. However, I am not quite sure if this would break something else. For example what is `dragToZoom` and how can I test it? It is not listed in the [gestureSettings documentation](https://openseadragon.github.io/docs/OpenSeadragon.html#.GestureSettings).

**Comment by pearcetm** [comment]
When I set `gestureSettingsMouse.dragToPan = false` in the demo (i.e. at https://openseadragon.github.io) it correctly disables panning. You can do this by opening the debugging console and typing `Array.from(OpenSeadragon._viewers)[0][1].gestureSettingsMouse.dragToPan = false;`

I haven't tested it with touch gestures.

What version of OpenSeadragon are you using?

**Comment by jonasengelmann** [comment]
Right, I forgot to mention, I was testing on the master branch.

**Comment by pearcetm** [comment]
Strange. Testing against master on my machine works as expected, the same as in the online demo page.

**Comment by jonasengelmann** [comment]
Actually, I was mistaken, it does work for mouse gestures in 4.1 and on the current master, however, it doesn't work for touch gestures on 4.1 and the current master. I tested this using dev tools and emmulating a device, which correctly returns `touch` for `pointerType`.

**Comment by pearcetm** [comment]
I see, I can reproduce that way. Looks like it does actually stop panning if you don't end the gesture with a flick, but the logic related the the flick isn't accounting for the setting. This makes sense with where you pointed out in the code.

`draggingToZoom` is a private internal state (hence not present in the docs) that relates to https://github.com/openseadragon/openseadragon/issues/2077 and was introduced by https://github.com/openseadragon/openseadragon/pull/2225. If you're making use of this, you're already not dragging to pan, so adding the check you propose shouldn't break anything. You could test the one-touch zoom in your emulator - just double-tap and move the cursor/finger up and down after the second tap.

**Comment by jonasengelmann** [comment]
Thanks for pointing that out, it's a nice feature. 

It seems that the combination `dragToPan: false` and `flickEnabled: true` is causing the issue for both mouse and touch gestures.

I will create a PR!
