### ISSUE TITLE
Use DZI with AWS S3 Signed URL, not working

### ISSUE THREAD

**Issue by BSNagaraj** [openseadragon/openseadragon#2467]

**Comment by BSNagaraj** [comment]
getTileUrl: function( level, x, y ){
            const adjustedY = y % 3;
            
            return generateSignedUrl(level, x, adjustedY);          
            }
  },
  
   const generateSignedUrl = (level, x, y) => {    
      const apiUrl = `0,TileGroup${level},${x}-${y}.jpg`; 
      // Make the API call asynchronously using Axios or any other preferred library
      api.getSignedUrl(apiUrl).then((response) => { 
        if (response != null && response.status == 200) {    
            return response.data; 
        }
      });     
  }

**Comment by iangilman** [comment]
We'll need more information than that to help you!

**Comment by BSNagaraj** [comment]
> We'll need more information than that to help you!

Thanks, for reply. It worked, I was trying with signed url to generate tiles directly to s3. Now using direct url with proper s3 access. Its working

**Comment by iangilman** [comment]
Great! Thank you for letting us know :)
