### ISSUE TITLE
Tiles in FOV hidden while zooming for certain Viewport & TiledImage rotation combinations

### ISSUE THREAD

**Issue by jbakarich** [openseadragon/openseadragon#2477]
Looks like some logic that calculates whether tiles are in view is not correctly taking into account a rotation/flip value. 

[osd_rotation_bug-2024-02-21_10.18.38.webm](https://github.com/openseadragon/openseadragon/assets/22227739/19027821-9fdb-41ba-95cc-e9e31b5f475d)

[Here is a link to an example sandbox](https://codesandbox.io/p/sandbox/openseadragon-sandbox-forked-7hcfw7?file=%2Fsrc%2Findex.js%3A37%2C15&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsw0ywvg00072v6hngtlh49h%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsw0ywvg00032v6hd9h3xqfw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsw0ywvg00042v6h99qbxple%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsw0ywvg00062v6hbwdu5ral%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsw0ywvg00032v6hd9h3xqfw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsw0ywvg00022v6hauu15b2t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A37%252C%2522startColumn%2522%253A15%252C%2522endLineNumber%2522%253A37%252C%2522endColumn%2522%253A15%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clsw0ywvg00032v6hd9h3xqfw%2522%252C%2522activeTabId%2522%253A%2522clsw0ywvg00022v6hauu15b2t%2522%257D%252C%2522clsw0ywvg00062v6hbwdu5ral%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsw0ywvg00052v6h080o8ppl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsw0ywvg00062v6hbwdu5ral%2522%252C%2522activeTabId%2522%253A%2522clsw0ywvg00052v6h080o8ppl%2522%257D%252C%2522clsw0ywvg00042v6h99qbxple%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsw0ywvg00042v6h99qbxple%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Exact repro steps:
- Add an image to OSD, then rotate, and flip the viewport:
```js
$.addTiledImage({
  tileSource: duomo,
  success: function () {
    $.viewport.setRotation(45, true);
    $.viewport.setFlip(true);
  },
});
```
- Add a second image that is rotated and flipped at the TiledImage level
```js
$.addTiledImage({
  composition: "source-over",
  index: 1,
  tileSource: duomo,
  success: function (evt) {
    evt.item.setRotation(45, true);
    evt.item.setFlip(true);
  },
});
```
- Zooming in/out should cause some tiles that are in the FOV to disappear

**Comment by pearcetm** [comment]
The sandbox isn't working for me - does it require a login?

Looking at the drawer comparison demo page on the master branch, it looks like the tile positioning issues you're seeing are already fixed in the WebGLDrawer, but still affect the CanvasDrawer.

**Comment by jbakarich** [comment]
Sorry about that, Ive updated the permissions on the sandbox!

**Comment by iangilman** [comment]
@jbakarich Thank you for reporting this!

@pearcetm Thank you for taking a quick look at it. Do you have thoughts about what the fix might entail?

**Comment by pearcetm** [comment]
There are a number of places where logic related to the viewport being flipped is only done in certain conditions.

For example, here, it only is applied when `sketchScale` is false:
https://github.com/openseadragon/openseadragon/blob/7dfc60a97fa2ce88213d7a1228749fd7f444aa65/src/canvasdrawer.js#L294C9-L312C10

Here, different logic is used depending on whether the viewport or the tiled image are rotated:
https://github.com/openseadragon/openseadragon/blob/7dfc60a97fa2ce88213d7a1228749fd7f444aa65/src/canvasdrawer.js#L317-L337

In `_offsetForRotation`, the context is saved and scaled to do the flipping, but this can happen twice in the same draw which probably leads to issues with the save/restore of the context state. And there's potentially some logic within that function that might be causing bad results:

https://github.com/openseadragon/openseadragon/blob/7dfc60a97fa2ce88213d7a1228749fd7f444aa65/src/canvasdrawer.js#L975-L991

The canvas drawer pipeline is pretty complicated and I don't entirely understand it still. I didn't touch this stuff as part of the webgl patch other than to separate it out into the `CanvasDrawer`. I'll try to look into how this could be fixed but if anyone else wants to take a crack at it too that would be most welcome!

**Comment by iangilman** [comment]
@pearcetm Thank you for the analysis!

@jbakarich Would you be interested in pursuing a fix, based on what @pearcetm has found?

**Comment by eug-L** [comment]
I noticed the Viewport is being flipped one too many times if both Viewport and TiledImage are rotated, which causes the this behavior.

https://github.com/openseadragon/openseadragon/assets/53654577/0d429e7c-c554-4273-ad75-4b16b10b7988


So I attempted to fix it by ensuring the Viewport is flipped only once for each ```_offsetForRotation``` batch, it seems to fix the clipping issue as well, though I cannot explain why.

https://github.com/openseadragon/openseadragon/assets/53654577/c387e01f-09c6-4646-8dba-612e651a1c67



Should I proceed to open  a PR?

**Comment by pearcetm** [comment]
Thank you for looking into this! I think a PR would be useful to be able to review the code and continue working through the issue.

From the videos, your changes appear to have altered the behavior of the viewer as well as - and this may be a good thing! In the top video, setting `temp0.item.setRotation(45)` appears to have undone the flip operation and returns the image back to an unflipped, unrotated state. In the bottom image, the same thing leaves the image flipped and rotates it an additional 45 degrees.

Further testing would be useful, and a PR would help with this process too.

**Comment by pearcetm** [comment]
In a coincidence of timing, I just came across this buggy behavior related to `TiledImage` rotation and viewer `flip` in a project I'm working on. From my testing (which confirms observations already noted above) this is already fixed in `WebGLDrawer` but still affects `CanvasDrawer`, in addition to affecting v4.1.0. I'm very interested in your fix for the `CanvasViewer`, @eug-L  - I think it would be valuable to fix this bug for anyone who wants to continue using the `canvas` drawing pipeline moving forward.

**Comment by pearcetm** [comment]
> In a coincidence of timing, I just came across this buggy behavior related to TiledImage rotation and viewer flip in a project I'm working on. 

Also, I want to thank @jbakarich for reporting this as well as @eug-L for helping isolate the issue and proposing a fix - having read about this bug report likely saved me hours of tracking down the issues in my project!

**Comment by pearcetm** [comment]
I believe this issue will be fixed by https://github.com/openseadragon/openseadragon/pull/2511. Any chance you could test it out, @jbakarich?

**Comment by pearcetm** [comment]
Thanks for testing, @jbakarich. To confirm, you were testing on the PR branch with `drawer: 'canvas'`, correct?

**Comment by jbakarich** [comment]
@pearcetm, yes, tested on branch `fix-canvas` with `drawer:  'canvas'`, viewport flipped, and with an added image also flipped and rotated.
