### ISSUE TITLE
Initialize a Viewer without opening the Tilesource

### ISSUE THREAD

**Issue by Sharpbarb** [openseadragon/openseadragon#248]
I am working on a project that uses multiple tilesources. I'd like to be able to load the n-th image when a user presses the n-th button. 

Currently I create a viewer like so:
var viewer = new OpenSeadragon.Viewer(options);

Which automatically loads the first image. If I want to load the desired image in the set I then call:
viewer.goToPage(n-th +1);

The above method works, but it seems like there should be a way to initialize the Viewer without automatically loading the first image and then loading the desired page.

Is there a way to do this?

**Comment by iangilman** [comment]
With multi-image in, we now have much more control over the sort of scenario (though we haven't made  an `initialPage` option). I think at this point adding additional options to sequence mode should be done as part of spinning it out as a plug-in (https://github.com/openseadragon/openseadragon/issues/649).
