### ISSUE TITLE
rendering JP2 images

### ISSUE THREAD

**Issue by gennadywexler-BLM** [openseadragon/openseadragon#2513]
I've been trying to find a solution for displaying JP2 images in an OSD viewer. Currently, when I direct the viewer to a JP2 image, it opens an empty window. One workaround that has been somewhat effective involves using ImageMagick to convert JP2 files into JPG format before rendering. However, this process introduces a noticeable delay that negatively impacts user experience. Could you provide any advice, including detailed instructions, on how to configure the system to either directly or indirectly render JP2 images without such drawbacks?

Thank you!

**Comment by pearcetm** [comment]
I'm able to open jp2 images, but only in Safari - see https://stackoverflow.com/q/60382331/1214731 for a discussion about this. If you want to support more than just Safari, I think you'll need to convert your images to a format that all browsers support (jpg, png, webp). Rather than converting on-demand each time a file is accessed, which will cause delays like you've noticed, converting them all up front would likely give you a better user experience.

**Comment by gennadywexler-BLM** [comment]
thank you! this is a very good answer!!

**Comment by iangilman** [comment]
If your JP2 images are large, you can convert them into tiled pyramids. Here are various options for that: 

https://openseadragon.github.io/examples/creating-zooming-images/

**Comment by gennadywexler-BLM** [comment]
Thank you, Ian, for the excellent suggestion! I was actually considering this as my next step, which would involve an initial investment to convert the images on demand at the rendering delays. If it becomes necessary to move away from JP2, I could potentially convert all the original TIFFs to JPG or WebP. My only worry is the sheer volume of images I'm dealing with — over 1,500,000, with the number increasing every day. 😊 I just need to decide on the best format to use going forward, main factor is for OSD rendering efficiency while keeping the stored sizes relatively small.

**Comment by gennadywexler-BLM** [comment]
Thanks, that aligns with what I was considering exploring next. The only hesitation is that we'd prefer not to set up an additional server to support rendering from the existing source. However, considering that the original source format was always TIFF, it might be worthwhile to bypass the MRSID and JP2 formats entirely.

**Comment by pearcetm** [comment]
> considering that the original source format was always TIFF

If your original TIFFs are compatible with GeoTIFF you could use the [GeoTIFFTileSource plugin](https://pearcetm.github.io/GeoTIFFTileSource/demo/demo.html) to view them directly. The demo page will let you enter a URL to one of your images to try it out.
