### ISSUE TITLE
Bad lag and choppy panning in mobile portrait orientation

### ISSUE THREAD

**Issue by brett3am** [openseadragon/openseadragon#2516]
Experiencing bad lag and choppy panning in mobile portrait orientation only. Desktop and mobile landscape are super smooth. I am using openseadragon to load a grid of images and treat them as a large zoomable image. I tested with small images to make sure it was not a resource issue. The Test code is attached.

[test.txt](https://github.com/openseadragon/openseadragon/files/15055769/test.txt)

**Comment by pearcetm** [comment]
See if following the instructions in this [FAQ wiki entry](https://github.com/openseadragon/openseadragon/wiki/FAQ#openseadragon-doesnt-work-well-on-mobile-devices-in-portrait-orientation) helps you out.
