### ISSUE TITLE
Flipped viewport causes image to be flipped again when going fullscreen or resizing 

### ISSUE THREAD

**Issue by jbakarich** [openseadragon/openseadragon#2517]
[2024-04-26 11-51-18.webm](https://github.com/openseadragon/openseadragon/assets/22227739/594bfe4d-ba93-44f0-8d9b-48215c3a6e2e)

Likely related to https://github.com/openseadragon/openseadragon/issues/2477

It appears that when `doViewerResize` is called, the viewer is re-drawn but the flip logic in `draw` of `canvas-drawer` is not fired again. 

code sandbox: https://codesandbox.io/p/sandbox/flipping-on-resize-bug-commit-c36f09712d-forked-6y68hc?file=%2Fsrc%2Findex.js%3A20%2C21

Repro steps:
1. Flip the OSD viewport
2. Perform any action that causes viewer resizing (fullscreen, etc)
3.  Observe that the image is flipped

**Comment by jbakarich** [comment]
A simple fix would be to reset the `_viewportFlipped` flag when `doViewerResize` is fired:

```js
function doViewerResize(viewer, containerSize){
    var viewport = viewer.viewport;
    var zoom = viewport.getZoom();
    var center = viewport.getCenter();

    viewer.drawer._viewportFlipped = false;

    viewport.resize(containerSize, viewer.preserveImageSizeOnResize);
    viewport.panTo(center, true);
    var resizeRatio;
    // ...
}
```

This seems to work, I'm not sure if it would be better to reset this flag later in the drawing pipeline.

**Comment by pearcetm** [comment]
@jbakarich I initially tried an approach similar to yours but using event handlers to keep the logic within `CanvasDrawer` but came across different issues (as noted in the pull request I just opened). I think I found a good solution though - this bug should be fixed by https://github.com/openseadragon/openseadragon/pull/2518. Can you give it a try?

**Comment by jbakarich** [comment]
@pearcetm tested on branch `fix-canvas`, confirmed your changes fix the issue when going fullscreen or resizing.
