### ISSUE TITLE
 How to cut out several small pictures from the main one

### ISSUE THREAD

**Issue by 7selik7** [openseadragon/openseadragon#2538]
I open a picture in dzi format, then using one of the buttons I draw squares on the main picture. After this, I want to click on a button, regardless of the current zoom level or coordinates, to cut out pieces from the main image in these areas and get one or several file objects
` 
useEffect(() => {
    const viewer = OpenSeadragon({
      id: "seadragon-viewer",
      prefixUrl: "//openseadragon.github.io/openseadragon/images/",
      tileSources: "...dzi",
      crossOriginPolicy: "Anonymous",
      maxZoomLevel: 100,
    });
    viewerRef.current = viewer;

    return () => {
      if (viewerRef.current) {
        viewerRef.current.destroy();
      }
    };
  }, []);
  
  const drawBoundaryBoxes = () => {
    const imageWidth = viewerRef.current.world.getItemAt(0).source.dimensions.x;
    const imageHeight = viewerRef.current.world.getItemAt(0).source.dimensions.y;
    const boundaryBoxesValues = [{start_x: 150, start_y: 200, roi_size: 100}];

    boundaryBoxesValues.forEach(({start_x, start_y, roi_size}) => {
      if (!start_x || !start_y) {
        return
      }
      const relativeX = (start_x / imageWidth);
      const relativeY = (imageHeight / imageWidth) * (start_y / imageHeight);

      const blockElement = document.createElement('canvas');
      blockElement.style.border = '2px solid rgb(0, 0, 0, 0.5)';
      blockElement.style.width = '100px';
      blockElement.style.height = '100px';
      canvasRef.current = blockElement;

      viewerRef.current.addOverlay(blockElement, new OpenSeadragon.Point(relativeX, relativeY));
    });
}

const handleCutOutSmallImages = async () => {
   // -------------Here----------
};
  
`
 
![photo_2024-05-30_20-16-38](https://github.com/openseadragon/openseadragon/assets/73950639/be9aafb9-3bc6-4037-bd54-cd1d84302259)

**Comment by 7selik7** [comment]
Yes, I want in full-resolution. I tried to write custom solution to get all tiles I need for the area, then cropp each tile and then glue pieces together. Here is my code, it works fine but a littile bit slow and not pixel perfect, maybe you can check and also it will be helpfull as a new feature 

`
 function getTilesCoveringArea(startX, startY, areaSize, tileSize, imageWidth, imageHeight) {
    const startTileX = Math.trunc(startX / tileSize);
    const startTileY = Math.trunc(startY / tileSize);
    let endTileX = Math.ceil((startX + areaSize) / tileSize);
    let endTileY = Math.ceil((startY + areaSize) / tileSize);

    var maxTileX = Math.ceil(imageWidth / tileSize);
    var maxTileY = Math.ceil(imageHeight / tileSize);

    endTileX = Math.min(endTileX, maxTileX);
    endTileY = Math.min(endTileY, maxTileY);

    var tiles = [];

    for (var x = startTileX; x < endTileX; x++) {
      for (var y = startTileY; y < endTileY; y++) {
        var tileStartX = x * tileSize;
        var tileStartY = y * tileSize;
        var clipStartX = Math.max(startX - tileStartX, 0);
        var clipStartY = Math.max(startY - tileStartY, 0);
        var clipEndX = Math.min(startX + areaSize - tileStartX, tileSize);
        var clipEndY = Math.min(startY + areaSize - tileStartY, tileSize);

        var clipWidth = clipEndX - clipStartX;
        var clipHeight = clipEndY - clipStartY;

        tiles.push({
          tileX: x,
          tileY: y,
          clipStartX: clipStartX,
          clipStartY: clipStartY,
          clipWidth: clipWidth,
          clipHeight: clipHeight
        });
      }
    }
    return tiles;
  }

  async function loadImage(url) {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.crossOrigin = "Anonymous";
      img.onload = () => resolve(img);
      img.onerror = (err) => reject(err);
      img.src = url;
    });
  }

const cropAndLoadImages = async (areaSize, tiles) => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    canvas.width = areaSize;
    canvas.height = areaSize;

    let destX = 0;
    let destY = 0;

    let column = tiles[0].tileX;
    let columnWidth = tiles[0].clipWidth;

    for (const tile of tiles) {
      const tileUrl = `.../13/${tile.tileX}_${tile.tileY}.jpg`;

      try {
        const img = await loadImage(tileUrl);

        if (tile.tileX > column) {
          destX = destX + columnWidth;
          destY = 0;

          column = tile.tileX;
          columnWidth = tile.clipWidth;
        }

        ctx.drawImage(
          img,
          tile.clipStartX, tile.clipStartY, tile.clipWidth, tile.clipHeight,
          destX, destY, tile.clipWidth, tile.clipHeight
        );

        destY = destY + tile.clipHeight;

      } catch (err) {
        console.error('Failed to load image:', tileUrl, err);
      }

    }
    const dataUrl = canvas.toDataURL();
    handleCropedFile(dataUrl);
  }
  
//--------------- Main Code --------------
const image = viewerRef.current.world._items[0].source.dimensions
const imageWidth = image.x;
const imageHeight = image.y;
const tileSize = 256;

boundaryBoxesValues.forEach((box) => {
  const tiles = getTilesCoveringArea(
    Number(box.start_x),
    Number(box.start_y),
    Number(box.roi_size),
    tileSize,
    imageWidth,
    imageHeight
  );
  cropAndLoadImages(Number(box.roi_size), tiles);
})  
`

**Comment by iangilman** [comment]
Cool. Sounds like you're on the right track :)
