### ISSUE TITLE
CrossOriginPolicy for OSD Plugins not Working

### ISSUE THREAD

**Issue by adriandarian** [openseadragon/openseadragon#2545]
Does anyone know why or how to fix a CORS issue for OpenSeadragon + ViaWebGL Plugin? Right now I have my Viewer and TileSources and TiledImages all routed with "use-credentials" for the deployment and false for local dev. But when using the ViaWebGL Plugin the whole TileSource turns black and no tiles load in the canvas. I made sure to pass the same crossOriginPolicy to the custom `"tile-loaded"` and `"tile-drawing"` handlers in the ViaWebGL plugin and inside on the `.getContext("webgl", { crossOrigin })` is set to the same. But still on deployments I get zero errors, just a black canvas.

**Comment by Aiosa** [comment]
Aren't you looking for this? https://github.com/openseadragon/openseadragon/issues/2470

**Comment by Aiosa** [comment]
Basically if you fetch from non-localhost cross domain source, you cannot bypass cors. You have to use it and the data server has to allow your domain to access the data.

**Comment by adriandarian** [comment]
@Aiosa not quite the same issue here, I am using directly this plugin https://github.com/thejohnhoffer/viaWebGL. the issue comes up because we are updating by reference the image that is already loaded into OSD which triggers the update callbacks. If you want to replicate the scenario, I am using the "tile-loaded" handler from that plugin.

```
openSD = OpenSeadragon({
        tileSources: '../tiles.dzi',
        prefixUrl: '../your/icons/',
        id: 'viaWebGL'
});
seaGL = new openSeadragonGL(openSD);
seaGL.addHandler('tile-loaded');
seaGL.vShader = '../fileV.glsl';
seaGL.fShader = '../fileF.glsl';
seaGL.init();
```

**Comment by pearcetm** [comment]
> I am using directly this plugin https://github.com/thejohnhoffer/viaWebGL.

Have you cross-posted over at the repo for viaWebGL? I'm not sure your issue can/should be fixed directly here in OpenSeadragon (but I haven't really dug into it, so I could be wrong).

**Comment by Aiosa** [comment]
The fact that OpenSeadragon loads the data does not mean that the data is not tained. `tile-loaded` event happens just after an image object (by default) was created, IMHO image objects can be transformed into a canvas and can he still tained, the issue shows up once you try to load it to a GPU. So I would check if it's not marked as tained.

I played with that plugin a lot. I remember that when using WebGL1 I had to once force all textures to be rectangular to be successfully loaded without having the input data zeroed (black), but I don't remember why it helped or why it should help in the first place. This is just a wild guess.

And as I always do, I recommend having a look on a small WebGL lib I created (starting from viaWebGL) for OSD visualizations. It's a bit harder to use, but it has far more features (such as a clip mask). https://github.com/RationAI/xopat/tree/master/modules/webgl 
I do play converting that module into a WebGL renderer, but I don't have that much time :/ I have a student working on this, though.

**Comment by adriandarian** [comment]
> > I am using directly this plugin https://github.com/thejohnhoffer/viaWebGL.
> 
> 
> 
> Have you cross-posted over at the repo for viaWebGL? I'm not sure your issue can/should be fixed directly here in OpenSeadragon (but I haven't really dug into it, so I could be wrong).

I have not asked there as the plugin has been dead for several years now. And even with the upcoming release of v5 of osd. This plugin is the only one that brings WebGL Shader technology in.

**Comment by Aiosa** [comment]
> This plugin is the only one that brings WebGL Shader technology in.

Please, feel free to check the link I've shared. That's second one - though I did not officially published it in its own repository.

**Comment by pearcetm** [comment]
> And even with the upcoming release of v5 of osd. This plugin is the only one that brings WebGL Shader technology in.

Since we now support webgl via the `WebGLDrawer`, it will be easier to integrate custom shaders moving forward. The goal with the initial implementation was just to get the tile composition pipeline working and tested. The next step will be adding a mechanism to allow users to provide custom fragment shaders. I think there are reasonable ways to approach this that won't be too difficult and won't add too much complexity to the OpenSeadragon codebase. Happy to talk about what such a mechanism might look like if you're interested...

**Comment by adriandarian** [comment]
> RationAI/xopat@`master`/modules/webgl

Sorry for the delay, I pulled the code you abstracted from the original webgl plugin and tried it and was able to reproduce the error with CORS and a tainted Canvas on my application, but without adding either plugin to OSD I do not get the errors. Also these errors only occur while on a cloud deployment where there is a difference in the domain and we need to perform a cross-site request. 

> Also I had to change the usage from your link to "use-credentials" and pass in some dummy credentials for testing. "Anonymous" will not work in my application

**Comment by adriandarian** [comment]
> > And even with the upcoming release of v5 of osd. This plugin is the only one that brings WebGL Shader technology in.
> 
> Since we now support webgl via the `WebGLDrawer`, it will be easier to integrate custom shaders moving forward. The goal with the initial implementation was just to get the tile composition pipeline working and tested. The next step will be adding a mechanism to allow users to provide custom fragment shaders. I think there are reasonable ways to approach this that won't be too difficult and won't add too much complexity to the OpenSeadragon codebase. Happy to talk about what such a mechanism might look like if you're interested...

while I agree and would love to continue talking about this, unfortunately the OSD version my team is using for this application is 2.4.2. yes that is very old but this application is a legacy application where the OSD was not installed via NPM or a CDN it was downloaded and loads the .min via a file path, but I can see changes to it. Meaning we cannot upgrade the version so easily.

**Comment by Aiosa** [comment]
>  I pulled the code you abstracted from the original webgl plugin and tried it and was able to reproduce the error with CORS and a tainted Canvas on my application, but without adding either plugin to OSD I do not get the errors

Then it seems the problem is really loading the texture to a GPU. If you do not use these plugins, you do not use GPU (at least directly) and therefore you don't see any errors. As I¨ve already noted:

> IMHO image objects can be transformed into a canvas and can be still tained, the issue shows up once you try to load it to a GPU

From MDN:

> A tainted canvas is one which is no longer considered secure, and any attempts to retrieve image data back from the canvas will cause an exception to be thrown.

OSD will just use the tained canvas to render into another canvas so that seems to be OK (does not leave the same context..?), but if you try reading the data for textures, it internally tries to pull the data out of the canvas.
So you need to ensure the canvas is not tained. This can be done as far as I know in two ways, either the crossorigin which you cannot use, or properly setting `Access-Control-Allow-Origin` headers on the server side.

**Comment by pearcetm** [comment]
> This can be done as far as I know in two ways, either the crossorigin which you cannot use, or properly setting `Access-Control-Allow-Origin` headers on the server side.

I agree with @Aiosa - this is all about whether the data is tainted or not.

Regardless of your client-side settings, the server **must** set the `Access-Control-Allow-Origin` header appropriately if you want access to the pixel data. So if that isn't configured correctly and you don't control it, you're out of luck. If `Access-Control-Allow-Origin` isn't set, the image data is considered "tainted" and pixel access is not allowed. The upshot is that the "basic" viewer can display the pixels but as soon as you try to access the pixel data there will be problems. WebGL textures provide access to pixels, so the browser won't let you do this for tainted data. That's why it isn't a problem until you try to use a plugin that uses webgl.

**Comment by iangilman** [comment]
I suppose you could do the old-school trick of proxying all of your image data from the foreign server to your local server and then up to the client. Obviously that's not ideal, but if you have no other option...

**Comment by Aiosa** [comment]
I completely forgot about this option! Good point. 

If you don't know much about it, you are looking for 'reverse proxy', e.g. in apache you need to enable relevant modules (`mod_proxy`, `mod_proxy_http`... etc). In apache, you would do:

        ProxyPass / http://proxied.server:port/ 
        ProxyPassReverse / http://proxied.server:port/ 

If you need to proxy to a https (e.g. amazon), you have to configure your server with a valid certificate though...

**Comment by adriandarian** [comment]
So I played around with and did a bunch of verification;

- the backend services run through AWS and are all certified, as well the application is hosted there as well and credentials are all passed correctly
- all backend api services utilize a cookie for credentials which means the crossOrigin policy must be set to "use-credentials"

So I wiped up a little alteration to the viaWebGL code

```
"tile-loaded": function (e) {
    var img = new Image();
	img.width = e.tiledImage.source.tileWidth;
	img.height = e.tiledImage.source.tileHeight;
	img.crossOrigin = this.osd.crossOriginPolicy;
	img.onload = function () {
		var output = this.viaGL.toCanvas(img);
		e.image.onload = e.getCompletionCallback();
		e.image.src = output.toDataURL();
	}.bind(this);
	img.src = e.image.src;
 }
```

After these changes I no longer get any taintedCanvas errors or CORS errors. However, when I look at pyramid level 0 I can see the tiles processed by the webGL plugin, but when I zoom in to level 1 I see the original tiles. Then zooming in further to levels all the way up to i.e. 8, I am seeing some of the tiles as original tiles and some as processed webGL tiles. But there are no errors, there are no failed api requests. I can even see in the network tab each level is properly fetching the tiles and passing them to the webGL canvas and processing into a base64 image correctly, it will just not redraw them into OSD canvas for some of the tiles.

**Comment by pearcetm** [comment]
> e.image.onload = e.getCompletionCallback();

I'm just guessing here, but could this line be leading to a race condition of some kind, where some tiles are calling the completion callback with the original data and others with the processed data?

**Comment by Aiosa** [comment]
You have a bug there. Completion callback must be called in synchronous way in the event handler, else the handler might think you've finished your processing already. Calling it inside loaded event is too late.


    "tile-loaded": function (e) {
        var img = new Image();
	    img.width = e.tiledImage.source.tileWidth;
	    img.height = e.tiledImage.source.tileHeight;
	    img.crossOrigin = this.osd.crossOriginPolicy;
            const finished = e.getCompletionCallback(); 
	    img.onload = function () {
		    var output = this.viaGL.toCanvas(img);
		    e.image.onload = finished;
		    e.image.src = output.toDataURL();
	    }.bind(this);
	    img.src = e.image.src;
     }

**Comment by Aiosa** [comment]
Note that you should probably also do something `onerror` and `onabort` and call the finish handler in all the cases, else it will get stuck and the event will never complete. I guess we could include the event in the tile loading timeout...

**Comment by adriandarian** [comment]
oh! that worked, I had no idea about the `getCompletionCallback` being synchronous and throwing a race condition thank you guys so much.

@Aiosa I will make sure to place in error handlers as well, thank you

**Comment by Aiosa** [comment]
Completion callback does not 'throw' (have) any race conditions. If you get the callback function synchronously, the tile load event will wait for you to call it. If you get the callback inside onload function which gets possibly called after the tile load event finished, no completion callback will help you. How is the event supposed to know whether you've finished? The race condition here is whether you manage to retrieve the completion callback before the event ends.

**Comment by adriandarian** [comment]
@Aiosa another small follow up question to get better understanding what happens if the original tile is slow to fetch from an api when this function gets called? Won't the completionCallback fire prematurally? Is there any tricks or process to make it wait?

**Comment by pearcetm** [comment]
> @Aiosa another small follow up question to get better understanding what happens if the original tile is slow to fetch from an api when this function gets called? Won't the completionCallback fire prematurally? Is there any tricks or process to make it wait?

`getCompletionCallback()` just returns the callback function - it doesn't call the callback right away.

What's happening here is that you need to **get** that callback immediately (synchronously), but only call it once you're done with fetching and processing the data. By binding it to the `e.image.onload` you're setting the image itself to call the callback once the `dataURL` is loaded by the image element.
