### ISSUE TITLE
QUnit Testing Headless on Mac

### ISSUE THREAD

**Issue by msalsbery** [openseadragon/openseadragon#2552]
Related to #1680 possibly

Testing using the 'grunt test' command on a mac, I get the following output:

<img width="698" alt="Screen Shot 2024-06-22 at 12 49 49 PM" src="https://github.com/openseadragon/openseadragon/assets/4570990/ffce0fb6-37cf-4559-a033-fb8bcbf1f22b">

I'm pretty sure I've figured this out a long time ago, but failing right now 😜

**Comment by pearcetm** [comment]
Hmm... when I run the tests on my mac I also get these 404 errors, but ultimately the tests succeed and I end up with this:
<img width="572" alt="image" src="https://github.com/openseadragon/openseadragon/assets/12499997/19631c49-608f-4572-96cc-284fdc78ba8a">

Not sure why "Chrome timed out" on your system.

**Comment by pearcetm** [comment]
@msalsbery is this a clean install of the directory? Does `npm rebuild` help?

**Comment by msalsbery** [comment]
@pearcetm yeah it's the last part the timeout.

And I don't think I have done npm in a while, good call thank you!

**Comment by msalsbery** [comment]
Looks like I broke something in XHR handling. It even says so in my original screenshot 🙄 

cc @pearcetm

**Comment by msalsbery** [comment]
All fixed now, thank you @pearcetm  😅

**Comment by pearcetm** [comment]
@msalsbery In case this crops up again, what did it take to fix it? Glad it is working again regardless...

**Comment by msalsbery** [comment]
> @msalsbery In case this crops up again, what did it take to fix it? Glad it is working again regardless...

I thought you might ask. 😉 

I mentioned it above. It was an OSD runtime error (in my changed branch) clearly logged in my original screenshot here. The very type of bug I was hoping to catch by running the tests.

I just needed to post a question so I could see it 😅

**Comment by pearcetm** [comment]
> I [mentioned it above](https://github.com/openseadragon/openseadragon/issues/2552#issuecomment-2184496325). It was an OSD runtime error (in my changed branch) clearly logged in my original screenshot here. The very type of bug I was hoping to catch by running the tests.

Haha yes, always nice when tests work as intended! I was unclear on whether you were seeing this problem when building from master (which would indicate a broken dependency or something like that), versus a development branch where the code changes themselves could be the cause. Sounds like it was the latter :)
