### ISSUE TITLE
Cache behavior question

### ISSUE THREAD

**Issue by pearcetm** [openseadragon/openseadragon#2560]
This issue will track the discussion started by @msalsbery in https://github.com/openseadragon/openseadragon/pull/2407#issuecomment-2234955429

~~I think I've found the issue and will be creating a PR shortly.~~

~~I think we should take care of this before 5.0.0 comes out.~~

**Comment by msalsbery** [comment]
@pearcetm awesome thank you! I'm away from office today so I didn't get too far, appreciate it!!

**Comment by pearcetm** [comment]
Actually, digging even deeper, I don't think this requires a PR after all.

I thought there might be a problem here:
https://github.com/openseadragon/openseadragon/blob/980deca107df92205e14bea684372ffe2dc41500/src/tiledimage.js#L1433-L1439

...because the code is checking for `tile.context2D` (which is not typically set), but not checking for `tile.cacheImageRecord` which is actually set. However, this never really comes into play because of other parts of the logic in `TiledImage`.

@msalsbery I tried what you said, i.e. zooming in and out of the same part of an image repeatedly, and I saw in the network tab that new requests were being triggered each time (as you described). However, it is actually different tiles each time that are being fetched. This is because not all tiles at a given zoom are fetched before we've zoomed past that level and/or covered it by higher-res tiles. Every time we pass through that zoom, the next "best" tile which hasn't been previously loaded is fetched. So the viewer is building the full pyramid slowly, a few images at a time, during each zoom in/out. Eventually when all the tiles for all the levels are in the cache, no more images get fetched during the zooming.

So, I don't think there's actually a problem that needs to be fixed. If you agree @msalsbery I will close this issue. Of course if the behavior I described above isn't what you were noticing that's a different story!

**Comment by msalsbery** [comment]
@pearcetm  So is it just my expectation (or assumption) of what's being cached that's wrong?

Without scroll zooming, just loading the initial image, I'm seeing network requests for duplicate tiles (I can post screenshots when I get back to my office). Obviously, the browser cache would catch a lot of those but I have that turned off at the moment.

Is it because a blurred version of the tiles are being cached as a canvas by OSD so a new network request is being made to get the image data when a tile is rerendered and cached?

**Comment by pearcetm** [comment]
@msalsbery I'm not sure why that would be happening.

In a test environment, I modified `ImageLoader` to have a property `requestCount = {}` and within `addJob` I added the following:

```
        if(this.requestCount[options.src]){
            this.requestCount[options.src]++;
        } else {
            this.requestCount[options.src] = 1;
        }
```

I've tested with the constrained pan demo, which uses the Duomo image: http://localhost:8000/test/demo/constrainedpan.html

When I set a breakpoint on the line with the increment, it is never hit, and when I inspect that object, I don't see any duplicate calls. You haven't turned the navigator back on since last posting your config options, right? Because that would definitely cause some tiles to be fetched twice (once for each viewer).

**Comment by msalsbery** [comment]
@pearcetm Thank you for that.

I just got back in the office so I'll be digging in, but no I didn't put the navigator back 😉

**Comment by msalsbery** [comment]
@pearcetm 

I'm good with closing this. I've dug into the code and played around enough and I don't see anything that concerns me 😅 

Let's get 5.0.0 released!

I really appreciate the help, thank you!

**Comment by pearcetm** [comment]
Ok, sounds good, closing this - on to 5.0.0!
