### ISSUE TITLE
Using WebGL context to create interesting scenes

### ISSUE THREAD

**Issue by oblak1** [openseadragon/openseadragon#2571]
Hello,

Since OSD 5.0 has been out I've been thinking about using the webGL renderer to enrich the viewing experience. For example, would the current setup allow using the GL context itself or together with Three.js to create 3D scenes? 

Could someone nudge me in the right direction for example to show the images/textures in a 30 degree angle from the viewing point?

**Comment by pearcetm** [comment]
A nice feature about the current design is that you can pass in the constructor of a class that inherits from `DrawerBase` and OSD will use it. So you can definitely create custom implementations, including with Three.js, that do neat things!

My first attempt at creating a webgl-based renderer was actually based on three.js - you can [view that implementation here](https://github.com/pearcetm/openseadragon/blob/8a4c95ef4b435088933f1e82b80de4a70a77ac97/test/demo/threejsdrawer.js). There was quite a bit of work that happened after I moved away from this approach, so it may not work correctly anymore, but perhaps you can use it as a starting point.

Another approach would be to inherit from the current `WebGLDrawer` and override specific methods. I'm not exactly sure what it would look like for this to with Three.js though.

**Comment by oblak1** [comment]
Thanks! Btw Is there a reason drawer is using webGL v1? I see the warning from three.js they aren't supporting v1 anymore when using the context

**Comment by pearcetm** [comment]
> Thanks! Btw Is there a reason drawer is using webGL v1? I see the warning from three.js they aren't supporting v1 anymore when using the context

Since WebGL v1 had the needed functionality and was more widely supported by browsers (even if marginally) it didn't seem necessary to use v2. It shouldn't be too hard to change to using v2 though, or even use v2 when available and fall back to v1 if not.
