### ISSUE TITLE
how to  calculate the level and scale relation?

### ISSUE THREAD

**Issue by chengdonglin** [openseadragon/openseadragon#2575]
how to  calculate the level and scale relation?

**Comment by iangilman** [comment]
Do you mean correlating the levels of the tile pyramid with the zoom? We don't really expose that information, as much of the point is to be able to ignore such implementation details. I'm curious, what are you hoping to use the information for?

One approach is to convert the viewport zoom value to an image zoom value, like so:

```
const viewportZoom = viewer.viewport.getZoom();
const imageZoom = viewer.viewport.viewportToImageZoom(viewportZoom);
```

If your imageZoom is 1, you're at the base level of the pyramid (what the number is depends on how big the pyramid is, but let's say 13 for example). If your imageZoom is 0.5, you're at the next level up (e.g. 12). If it's at 0.25, level 11, etc.

Of course in practice one is rarely exactly on a level... If your image zoom is 0.75 you're somewhere between the base level and the next level up.

As for what number the base level of the pyramid is, you can potentially get that like so:

```
const baseLevel = viewer.world.getItemAt(0).source.maxLevel;
```

**Comment by chengdonglin** [comment]
> Do you mean correlating the levels of the tile pyramid with the zoom? We don't really expose that information, as much of the point is to be able to ignore such implementation details. I'm curious, what are you hoping to use the information for?
> 
> One approach is to convert the viewport zoom value to an image zoom value, like so:
> 
> ```
> const viewportZoom = viewer.viewport.getZoom();
> const imageZoom = viewer.viewport.viewportToImageZoom(viewportZoom);
> ```
> 
> If your imageZoom is 1, you're at the base level of the pyramid (what the number is depends on how big the pyramid is, but let's say 13 for example). If your imageZoom is 0.5, you're at the next level up (e.g. 12). If it's at 0.25, level 11, etc.
> 
> Of course in practice one is rarely exactly on a level... If your image zoom is 0.75 you're somewhere between the base level and the next level up.
> 
> As for what number the base level of the pyramid is, you can potentially get that like so:
> 
> ```
> const baseLevel = viewer.world.getItemAt(0).source.maxLevel;
> ```

my function args read the region image by scanScale, x, and y an tileSize, such as:
def GetImageStreamPassageway(path :str,fScale: float,nImagePosX,nImagePosY: int, tileSize: int), openSeadragon getTileSource support level, x, y , so I think the level and scale has the relation?  and how to convert?

**Comment by iangilman** [comment]
Can you explain to me what your variables mean? 

What is fScale in relation to? If we're looking at the entire image, is it 1? If you're zoomed in so you can only see the upper left quadrant of the image, is it 2?

What are the X and Y for? Is that a location inside the image? Or is it where the image is located? What units are they in? The original pixels of the image?

What is tileSize for? What units is it in?

**Comment by chengdonglin** [comment]
> Can you explain to me what your variables mean?
> 
> What is fScale in relation to? If we're looking at the entire image, is it 1? If you're zoomed in so you can only see the upper left quadrant of the image, is it 2?
> 
> What are the X and Y for? Is that a location inside the image? Or is it where the image is located? What units are they in? The original pixels of the image?
> 
> What is tileSize for? What units is it in?

scale means scan multiplier，for example, 1,2,5,10,20,40, x， y means the coordinate, tilesize means the image size

**Comment by iangilman** [comment]
I'm sorry, I still don't understand what you're trying to accomplish. I assume you have an image and it has certain dimensions. And then you have a region within that image described by those variables? And you want to navigate to that region? Is that correct?

**Comment by msalsbery** [comment]
@chengdonglin 

I see you closed this, but are you working with image data that has different tiles from actual scans at different objectives?

Or do you just want to simulate objectives with zoom...?
