### ISSUE TITLE
About the problem of pictures disappearing automatically in the viewer?

### ISSUE THREAD

**Issue by Whao510** [openseadragon/openseadragon#2579]
When I use Google Chrome to open two pages at the same time, one is YouTube and the other is the page after the project is started. When switching between the two windows, the pictures in the viewer will be automatically hidden and will only be displayed after some manual operations. I don't know what causes this. If I don't switch windows, everything is normal. I hope someone can help me solve this problem.

**Comment by pearcetm** [comment]
This sounds like a duplicate of https://github.com/openseadragon/openseadragon/issues/2577, but includes more information in the issue so I'll respond here.

It sounds like Chrome is clearing the draw buffer on your viewer for some reason when the tab is inactive. I'm not able to reproduce this on my machine (Macbook Pro, latest Chrome) with the openseadragon.github.io demo page and youtube. Do those two sites reproduce the issue for you, or do you have to do something different with your viewer? If so, what configuration is needed to reproduce?

One thing you could try is using the `drawer: 'canvas'` option to see if this only affects the `WebGL` drawer, which may help narrow the problem down.

**Comment by Whao510** [comment]
Thanks for your reply. The problem I'm having is that when I open two windows in Google Chrome, after I switch between the two, the viewer image in the openseadragon project will automatically hide. I'm not sure if I'm the only one who has this problem.
I tried to test it with Safari browser, switching between the tabs in the two windows, and everything worked fine. It seems that this is a problem with the browser.
Currently using Google Chrome version: Version 124.0.6367.158 (official version) (arm64)
macOs OS Ventura version 13.1

> This sounds like a duplicate of #2577, but includes more information in the issue so I'll respond here.
> 
> It sounds like Chrome is clearing the draw buffer on your viewer for some reason when the tab is inactive. I'm not able to reproduce this on my machine (Macbook Pro, latest Chrome) with the openseadragon.github.io demo page and youtube. Do those two sites reproduce the issue for you, or do you have to do something different with your viewer? If so, what configuration is needed to reproduce?
> 
> One thing you could try is using the `drawer: 'canvas'` option to see if this only affects the `WebGL` drawer, which may help narrow the problem down.

**Comment by Whao510** [comment]
> This sounds like a duplicate of #2577, but includes more information in the issue so I'll respond here.
> 
> It sounds like Chrome is clearing the draw buffer on your viewer for some reason when the tab is inactive. I'm not able to reproduce this on my machine (Macbook Pro, latest Chrome) with the openseadragon.github.io demo page and youtube. Do those two sites reproduce the issue for you, or do you have to do something different with your viewer? If so, what configuration is needed to reproduce?
> 
> One thing you could try is using the `drawer: 'canvas'` option to see if this only affects the `WebGL` drawer, which may help narrow the problem down.

It is now normal. I upgraded the Google browser to solve it. Thank you for your reply. It helps me a lot.
