### ISSUE TITLE
Confusing variable names in unit test assertions

### ISSUE THREAD

**Issue by BeebBenjamin** [openseadragon/openseadragon#2583]
I am spending time debugging the unit tests for #2582 and I have found that the way the variables are named is confusing...

For example in `Overlays size in pixels` we have the following:

```javascript
Util.assessNumericValue(assert, actPosition.left, expPosition.x, epsilon,
                "X position mismatch " + contextMessage);
```

If you follow the test back to it's declaration the args for act and exp are reversed...

```javascript
assessNumericValue: function ( assert, value1, value2, variance, message ) {
            assert.ok( Util.equalsWithVariance( value1, value2, variance ), message + " Expected:" + value1 + " Found: " + value2 + " Variance: " + variance );
        }
```
I suggest this be refactored and these brought in line to make it less confusing to work with unit tests...

E.g. Found renamed to Actual and swapped with Expected

**Comment by iangilman** [comment]
Oh man... Good catch! Definitely would be good to clean up.

**Comment by BeebBenjamin** [comment]
This is a one line change I think.

Something like:

```javascript
     assert.ok( Util.equalsWithVariance( value1, value2, variance ), message + " Actual:" + value1+ " Expected: " + value2+ " Variance: " + variance );
```

**Comment by iangilman** [comment]
Sounds right. Just need to also check every place that calls it to make sure it's lined up properly.

**Comment by ATH42** [comment]
hey friends i opened a [PR](https://github.com/openseadragon/openseadragon/pull/2601) for this. checked all references of that test too. hope this helps.

**Comment by parvarish-code** [comment]
@ATH42 is work on this issue complete?

**Comment by Osank31** [comment]
Is this issue still open??

**Comment by iangilman** [comment]
@Osank31 It doesn't appear to be. Are you encountering it?
