### ISSUE TITLE
Finer adjustments to scroll zoom

### ISSUE THREAD

**Issue by ShashanKV98** [openseadragon/openseadragon#2584]
I was wondering if there could be some modifications made to the scrollToZoom so that a simple mouse wheel doesn't zoom, but wheel + pressing a key (like shift or Ctrl) does zooming? Thanks!

**Comment by pearcetm** [comment]
@msalsbery Could `MouseTracker` be used on the entire viewer to intercept and prevent this event unless there's a modifier key pressed?

**Comment by msalsbery** [comment]
@ShashanKV98 

The easiest way to do this is to add a [canvas-scroll](https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#.event:canvas-scroll) handler to the viewer. 

For legacy reasons, the event object passed to that handler only passes the shiftKey property from the originating DOM event (as 'shift'), but you could look at the originalEvent.ctrlKey and/or originalEvent.altKey properties as well.

If you wish to prevent the default wheel zoom behavior in your canvas-scroll handler, you can set the preventDefaultAction to true on the passed event object.

(Note: there's also a preventDefault property you could set to false to let the browser do its default wheel event handling, but that would probably never be useful on an OpenSeadragon viewer)

Example:
```
    viewer.addHandler('canvas-scroll', (event) => {
        //
        // Only zoom if user presses ctrl key while using wheel
        //
        if (!event.originalEvent.ctrlKey) {
            event.preventDefaultAction = true;
        }
    });
```

**Comment by msalsbery** [comment]
> @msalsbery Could `MouseTracker` be used on the entire viewer to intercept and prevent this event unless there's a modifier key pressed?

Definitely could, but since there's already two  MouseTrackers on the full viewer elements, and most if not all gesture handlers are available for override at the Viewer level, it's generally only necessary in extreme cases. The Viewer 'canvas-xxx' events are a friendly user level place to do these simpler overrides

**Comment by pearcetm** [comment]
> > @msalsbery Could `MouseTracker` be used on the entire viewer to intercept and prevent this event unless there's a modifier key pressed?
> 
> Definitely could, but since there's already two MouseTrackers on the full viewer elements, and most if not all gesture handlers are available for override at the Viewer level, it's generally only necessary in extreme cases.
> 
> The Viewer 'canvas-xxx' events are a friendly user level place to do these simpler overrides

Ah, that makes sense, thanks!

**Comment by msalsbery** [comment]
@ShashanKV98 @pearcetm 

I woke in the middle of the night thinking wait, that example won't work, but there's a plugin for that. I'll be back with a better solution...

**Comment by msalsbery** [comment]
@ShashanKV98 

Never mind, the original example will work. Apparently I was dreaming at a different level of the event chain  🤦

**Comment by ShashanKV98** [comment]
Thanks @msalsbery @pearcetm ! The `addHandler` approach worked for me. I used preventDefault() though, since I wanted the browser scrolling too.
