### ISSUE TITLE
how to change navigation map shape?

### ISSUE THREAD

**Issue by chengdonglin** [openseadragon/openseadragon#2592]
<img width="458" alt="fl" src="https://github.com/user-attachments/assets/6540bea2-d621-40e0-b2e0-35ede3473b16">
 default navigation map is red rectangle， how to change like cross shape (+)? like below:
  
 
<img width="109" alt="image" src="https://github.com/user-attachments/assets/821b6a91-5f22-45ed-a577-a4a8b8ee65db">

**Comment by iangilman** [comment]
There's no API for customizing the navigator shape. You could potentially do it by adding some more elements to the navigator's `displayRegionContainer` and updating their position when the viewer raises "animation" events. For reference, here's where the navigator's `displayRegion` is updated: 

https://github.com/openseadragon/openseadragon/blob/8bdc0a414649ba7085ea3f9bdf7c932a705196d0/src/navigator.js#L407
