### ISSUE TITLE
tile-loaded event `image` vs `data` differences

### ISSUE THREAD

**Issue by BeebBenjamin** [openseadragon/openseadragon#2595]
Ever since we swapped over to using `data` vs `image` in the custom `tile-loaded` event handler of our Mirador plug-in.  We have been having an initial black screen when passing these images into a threejs renderer that requires clearing the cache to get the images to show again.  There is some difference about the way event `data` works in comparison to event `image` that means the images are not available for threejs at the time of rendering if the application has been sat a while.

The code for the custom handler we're using is this:

```javascript
 this.props.viewer.addHandler('tile-loaded', (event) => {
          this.setState({ loadHandlerAdded: true });
          this.tileLevels[event.tile.level] = event.tile.level;
          this.tileLevel = event.tile.level;
          const sourceKey = event.data.currentSrc.split('/')[5];
          const canvas = document.createElement('canvas');
          const tileTexture = new THREE.Texture(event.data);
          const key = event.tile.getUrl();

          canvas.width = event.data.width;
          canvas.height = event.data.height;
          event.tile.context2D = canvas.getContext('2d');
          event.tile.context2D.drawImage(event.data, 0, 0);

          tileTexture.needsUpdate = true;

          if (this.map_ids.includes(sourceKey)) {
            // only keep tile textures we are interested in
            if (!(key in this.images)) {
              this.images[key] = tileTexture;
              this.threeCanvasProps.images = this.images;
            }
            this.setState({
              threeCanvasProps: this.threeCanvasProps,
            });
          }
        });
      }
    }
```
If I swap data for image (the deprecated property) everything works again.  I just need a little help in making the changes necessary to use data appropriately, because I believe I am not handling it correctly...

**Comment by iangilman** [comment]
@Aiosa @pearcetm Any thoughts?

@BeebBenjamin is this in 5.0.0 or 4.x.x?

**Comment by Aiosa** [comment]
From what I remember the difference is that one throws a warning, the other not. But I will have a look. The idea was to rename the property, since 'image' hinted on a certain property of the data item, while 'data' was more generic, as we wanted to be able to consume anything.

**Comment by Aiosa** [comment]
Also please note that 'context2d' will be in future deprecated too.

**Comment by pearcetm** [comment]
I think we probably need some more information to figure out what is going on here. Like @Aiosa mentioned, `image` is just a deprecated alias for `data`, and has been for a while (this change happened in 4.0.0). Here is the relevant source code:

https://github.com/openseadragon/openseadragon/blob/8bdc0a414649ba7085ea3f9bdf7c932a705196d0/src/tiledimage.js#L2110-L2124

So, I don't understand how swapping `data` for `image` could make a difference here, unless the OSD version is 3.1 or earlier (in which case I don't see how `data` would ever work, since it would be undefined). Setting a breakpoint in this event handler and inspecting the event object may shed some light.

**Comment by BeebBenjamin** [comment]
I was mistaken and realised eventually that data and image point to the same thing.  I also tested for difference in function and rightly couldn't find any.  I am going to try downgrading to before this code was changed i.e. before image was deprecated and see if there is any difference in functionality.  I will also provide more information as to the nature of the problem I am facing. Apologies for the confusion.

**Comment by Aiosa** [comment]
You might want to check Advanced Data Pipeline page at the documentation, that explains how the data is being created and managed. This might give you a hint at what could be wrong and where to debug. Also, knowing the OSD version you are using would help a lot. Just heads up, that 'advanced' pipeline will also get deprecated, and replaced by much more powerful system.

**Comment by BeebBenjamin** [comment]
Solved.  I have thoroughly tests 3 versions of OSD, the problem is not here.  It was a bug in Chrome browser that means content negotiation for cached info.json responses at the same URI do not work reliably, so you can end up with v2 and v3 IIIF image API conflicts, especially if you're using the `preferredFormats` option with OSD.  Closing.
