### ISSUE TITLE
WebGL does not respect viewportMargin option provided

### ISSUE THREAD

**Issue by cincospenguinos** [openseadragon/openseadragon#2599]
When instantiating OpenSeadragon on OpenSeadragon 5, if I select `drawer: 'webgl'` and provide viewport margins, I don't see the viewport margins like I do with `drawer: 'canvas'`. I've gone ahead and duplicated the issue as a demo the PR #2598.

**Comment by iangilman** [comment]
@cincospenguinos Good catch! Thank you for the repro.

@pearcetm Could you take a look at this?

**Comment by pearcetm** [comment]
Hmm, that's strange. I actually don't really know how the margins are handled by the canvas drawer. I would have thought it would be handled at the level of either the `viewport` or `tiledImage` which should be the same regardless of which drawer is used. Clearly there's more going on than I currently understand. I'll have to look into it. @iangilman if you have any pointers about how this is/was implemented in the old canvas pipeline that would be helpful!

**Comment by pearcetm** [comment]
I still have no idea how the canvas drawer is accounting for this (though obviously it is), but I figured out an easy fix for the webgl drawer. I've opened a PR that fixes this issue (https://github.com/openseadragon/openseadragon/pull/2600).

**Comment by iangilman** [comment]
@pearcetm Honestly I'm not entirely sure how `viewportMargins` works anymore, even though I think I was the one who implemented it! I'm glad you figured out a solution :)

**Comment by iangilman** [comment]
We generally try to save up the patches for a bit before releases, but it's probably about time for another...

**Comment by cincospenguinos** [comment]
I believe this bug still exists for a corner case, wherein one of the viewport margins is not equal to the value of the others causes the image to shift outside of what is defined by the debug mode. I'm not an expert on your library so take this guess with a grain of salt, but it looks to me like WebGL is applying the margins at a different rendering/displaying stage (before/after drawing) than the canvas drawer.

I've added another demo, #2605, that shows this issue. Let me know if you'd like me to open another issue to keep track of it.

**Comment by iangilman** [comment]
@cincospenguinos Thank you for catching this! Good to make sure it's really solid. 

@pearcetm Can you take a look?

**Comment by pearcetm** [comment]
> @cincospenguinos Thank you for catching this! Good to make sure it's really solid.
> 
> @pearcetm Can you take a look?

Luckily this wasn't too hard, and is fixed by https://github.com/openseadragon/openseadragon/pull/2606.

The issue boiled down to the fact that `viewport.getCenter()` does NOT return the center of the drawn region if margins are not symmetric. Calculating the true center point from the bounds returned by `viewport.getBoundsNoRotateWithMargins()` solves the issue.

**Comment by cincospenguinos** [comment]
#2606 works on my end.
