### ISSUE TITLE
has any way quick to convert mouse coordinates to image coordinates 

### ISSUE THREAD

**Issue by chengdonglin** [openseadragon/openseadragon#2626]
has any way quick to convert mouse coordinates to image coordinates ? below is code:

```js
      that.viewer.canvas.addEventListener('mousemove', function(event) {
        var pointer = new OpenSeadragon.Point(event.clientX, event.clientY);
        console.log("canvas-mousemove",pointer)
        const imagePoint = that.viewer.viewport.viewportToImageCoordinates(pointer);
        console.log('Image coordinates:', imagePoint);
}
```
I found is not correct, tif file maxWidth and maxHeight less than 30000,  the log see below
```js
canvas-mousemove $.Point {x: 1252, y: 54}
Image coordinates: $.Point {x: 92948480, y: 4008960}
```

**Comment by iangilman** [comment]
The event's coordinates will be in web coordinates relative to the window, not viewport coordinates, so you need to use `windowToImageCoordinates`. For more information on the coordinate systems, see https://openseadragon.github.io/examples/viewport-coordinates/.

**Comment by chengdonglin** [comment]
> The event's coordinates will be in web coordinates relative to the window, not viewport coordinates, so you need to use `windowToImageCoordinates`. For more information on the coordinate systems, see https://openseadragon.github.io/examples/viewport-coordinates/.

I use the method to get the coordinates below, but the imagePoint  not correct

that.viewer.canvas.addEventListener('mousemove', function(event) {
        if(that.twod) {
          var pointer = new OpenSeadragon.Point(event.x, event.y);
          var viewportPoint = that.viewer.viewport.pointFromPixel(pointer);
          var imagePoint = that.viewer.viewport.viewportToImageCoordinates(viewportPoint);
          const currentZoom = that.viewer.viewport.getZoom();
        }
    });`
`

**Comment by pearcetm** [comment]
In development mode (follow the [instructions here](https://github.com/openseadragon/openseadragon/blob/master/CONTRIBUTING.md#first-time-setup), and run `grunt dev`) you can check out the 'coordinates' demo to get a good idea of what is going on: http://localhost:8000/test/demo/coordinates.html 

You can also check out the source code for that demo to see how to convert mouse position into image coordinates.
