### ISSUE TITLE
overlay position when the tilesource is loaded with the degrees option.

### ISSUE THREAD

**Issue by sbarex** [openseadragon/openseadragon#2629]
Let's say I want to create an overlay at position 0,0 with size 50% of the width and height:

<img width="288" alt="Screenshot 2024-12-09 alle 17 39 25" src="https://github.com/user-attachments/assets/9b2a55b8-7827-47e8-80d6-d485a07cbbf7">

```js
let viewer = OpenSeadragon({
    // ... 
    tileSources: {
       tileSource: "https://openseadragon.github.io/example-images/highsmith/highsmith.dzi",
       degrees: 0 // <-
    }
});

viewer.addHandler('open', (eventInfo) => {
    const dim = viewer.source.dimensions;
    const ratio_y = dim.y / dim.x;
    viewer.addOverlay({
        // ...
        location: new OpenSeadragon.Rect(0, 0 * ratio_y, .5, .5 * ratio_y),
    });
});
```

If the image have a tilesource loaded with a 90 degrees options, the overlay is not put on the origin but shifted on x and y, and also the size is not 50% of width and height. 

<img width="494" alt="Screenshot 2024-12-09 alle 18 22 58" src="https://github.com/user-attachments/assets/c90b52ef-da04-48b2-89db-029fbac87e7f">

I also try to load the tilesource with 0 degree, add the overlay and then rotate the image (with `viewer.world.getItemAt(0).setRotation(90, true)` with the same result.

Source code at this link:

https://codepen.io/sbarex/pen/GgKqZgq

**Comment by iangilman** [comment]
Looks like this has been discussed in #2631.
