### ISSUE TITLE
Too many active WebGL contexts

### ISSUE THREAD

**Issue by w5c17** [openseadragon/openseadragon#2630]
Hi, I found the following problem while browsing multiple images, my requirement is this: I want to display 9 images under one page at the same time, and then I created 9 openseadragon objects, but I found`showNavigator: true`Will affect the number of my WebGL drawer.However, I have learned that the browser supports a limited number of WEBGL contexts at the same time, the default is 16. When exceeded, previously created objects are lost.
So by the time I create the eighth object, it has reached the maximum of 16, is there any way to fix it
Or I can separately change the rendering method of the navigation map to canvas

**Comment by pearcetm** [comment]
Once a viewer with a navigator has been created, you can change the drawer for the navigator like so: `viewer.navigator.requestDrawer('canvas')`
