### ISSUE TITLE
invalid viewport coordinate for rotated tilesource

### ISSUE THREAD

**Issue by sbarex** [openseadragon/openseadragon#2631]
I have a rotated tilesource (for example 90 degree) with not a square ratio. 

When I convert mouse coordinates to the viewport, the conversion does not take into account the rotation applied to the tile source. So screen coordinates outside the image can have viewport coordinates between 0 and 1 (recognized as internal of the picture), and other times internal image mouse coordinates can be translated with values ​​less than 0 or greater than 1 (external of the picture).

<img width="613" alt="Screenshot 2024-12-10 alle 12 13 44" src="https://github.com/user-attachments/assets/44bac8d2-e37b-453e-8e14-e2bb41789ded">

On this screenshot, the pointer in inside the image, but the mouse coords are traslated to the viewport coords outside (the x is less than zero)

This cause the bug #2629.

See this example:

https://codepen.io/sbarex/pen/GgKqZgq

**Comment by pearcetm** [comment]
Viewport coordinates are essentially arbitrary, and TiledImages can be outside of the 0 to 1 range (as you can specify when giving the x and y coordinates, or a width greater than 1 for example). In your screen shot, it looks like what is happening here is that the tiled image is being rotated 90 degrees about the centerpoint of the image, and since the aspect ratio is not 1:1 that means the top left corner (after rotation) is not at the origin of the viewport coordinates anymore.

**Comment by sbarex** [comment]
Thanks to the replay. 

The fact that the viewport coordinates do not respect the TileSource rotation seems counterintuitive to me (and I'm not referring to the rotation applied to the view with the toolbar buttons, but to the rotation defined during loading).

Referring to the issue #2629, how should I then specify the coordinates of an overlay so that it is positioned at the vertex of the image with the dimensions of 50% width and 50% height regardless of whether the image is rotated or not?

**Comment by pearcetm** [comment]
> Referring to the issue #2629, how should I then specify the coordinates of an overlay so that it is positioned at the vertex of the image with the dimensions of 50% width and 50% height regardless of whether the image is rotated or not?

`TiledImage.getBounds()` should give you the coordinates and width/height values you need for this.

**Comment by sbarex** [comment]
thank you very much, that actually works.
So if the behavior of the viewport coordinates is wanted I can close the issue.

**Comment by sbarex** [comment]
Thank you very much. In fact the experience with a single unrotated image made me think that the viewport originated on the image. Now it seems clearer to me how it works.
