### ISSUE TITLE
Navigator setWidth Error

### ISSUE THREAD

**Issue by w5c17** [openseadragon/openseadragon#2632]
Hello, I found an error occurred when I tried to modify the width of the navigator after modifying the navigator drawer when I created the viewer, is this normal.Here's how I created it,my version is 5.0.0
```
    this.viewer = OpenSeadragon({
      id: 'seadragon-viewer',
      crossOriginPolicy: 'Anonymous',
      showNavigationControl: false,
      maxTilesPerFrame: 50,
      showNavigator: true,
    });
    this.viewer.navigator.requestDrawer('canvas')
    this.viewer.navigator.setWidth(300);
```

**Comment by iangilman** [comment]
It seems like it should work. What's the error? 

One thought: what if you wrap it in `this.viewer.addHandler('open', () => { ... })`? 

Also, if you just wanted to have a specific width at the beginning, you might as well use `navigatorWidth: 300` in your viewer options instead.

**Comment by w5c17** [comment]
The error is this
![企业微信截图_17339619936355](https://github.com/user-attachments/assets/188d9151-527d-4945-b654-f0bd25d9d146)
I think it would be easy to reproduce it, maybe you could give it a try

**Comment by w5c17** [comment]
Fortunately, after I upgraded the version to 5.0.1, this bug disappeared, can I find out what happened to it

**Comment by w5c17** [comment]
I have another problem when I make the navigation chart invisible, like this`viewer.navigator.setVisible(visible)`,Why is its border still visible, which is not what I want to see
