### ISSUE TITLE
Button display issue with IE8 / Win XP

### ISSUE THREAD

**Issue by adversor** [openseadragon/openseadragon#272]
The 'Zoom out' button (-) and 'Home buttom' seem to be overwritten by the 'page back' and 'page forward' buttons if all buttons are in one block. On this example
http://openseadragon.github.io/examples/ui-reference-strip/ the upper one has the problem in IE8/XP, the second is fine.

Correct display with Firefox 24 on Win XP:
![buttons_firefox24](https://f.cloud.github.com/assets/5862021/1515547/7bc2e0fc-4b04-11e3-9e88-0270697869c1.jpg)

and the problem with IE8 on Win XP:
![buttons_ie8](https://f.cloud.github.com/assets/5862021/1515554/ae7174be-4b04-11e3-90de-be5ecebb01d6.jpg)

**Comment by msalsbery** [comment]
Fast-forward to August 2020...anyone still using IE8 that can't work around this? ;)

**Comment by iangilman** [comment]
Yeah, I believe we've officially drop support for IE 8, so I suppose we can close this now.
