### ISSUE TITLE
Reflection effect in openseadragon

### ISSUE THREAD

**Issue by shipon-eye** [openseadragon/openseadragon#275]
Many many thanks for the great contribution in such tool development.
By the way, my observation regarding the reflection effect in chrome browser is sometimes annoying. So, I am requesting you to build a control mechanism so that we can tell seadragon whether it should show the reflection or not. 
An extra parameter to control reflection effect will most appreciable.

regards

Habib

**Comment by iangilman** [comment]
This is no longer an issue, thanks to #386.
