### ISSUE TITLE
How do you create your zooming image data?

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#307]
I'm finally getting around to writing up a page on how to create zooming image data for use with OpenSeadragon. I've got a start, but I'd love to hear what techniques people use so I can add them to the list!

To see what I have so far, check out https://github.com/iangilman/site-build/blob/home/www/creating-zooming-images.html, part of https://github.com/openseadragon/site-build/pull/41.

**Comment by iangilman** [comment]
Closing this thread, but hit me up if/when you run across more ways to create your tiled images!

**Comment by iangilman** [comment]
BTW, here's the page we built on the topic: 

http://openseadragon.github.io/examples/creating-zooming-images/

**Comment by iangilman** [comment]
@avandecreme I've just been contacted by someone who wants to create DZI via Java, and we still don't have a good option to point to for that. Have you published your library yet? If not, would you be up for it?

**Comment by avandecreme** [comment]
Unfortunately, no. I won't have time to publish it for now.
However, you can redirect the person to https://code.google.com/p/deepjzoom/ and let him know that there is this easily fixable bug: https://code.google.com/p/deepjzoom/issues/detail?id=1

**Comment by iangilman** [comment]
Cool, I have done so. Thanks!
