### ISSUE TITLE
Improve IIIF 1.1 TileSource (3 enhancements)

### ISSUE THREAD

**Issue by azaroth42** [openseadragon/openseadragon#313]
1. The IIIF 1.1 TileSource should not require both tile height and width, and should default to a sensible tile size if not provided.
```javascript
    if ( this.tile_width ) {
        options.tileSize = this.tile_width;
    } else if ( this.tile_height ) {
        options.tileSize = this.tile_height;
    } else {
        options.tileSize = 512;
    }
```

2. TileSource should check @context field first in supports
```javascript
    supports: function( data, url ){
        return (
            data['@context'] && 
            data['@context'] == "http://library.stanford.edu/iiif/image-api/1.1/context.json") ||
            (data.profile && (
              "http://library.stanford.edu/iiif/image-api/1.1/compliance.html#level0" == data.profile ||
              "http://library.stanford.edu/iiif/image-api/1.1/compliance.html#level1" == data.profile ||
              "http://library.stanford.edu/iiif/image-api/1.1/compliance.html#level2" == data.profile ||
              "http://library.stanford.edu/iiif/image-api/1.1/compliance.html" == data.profile
            )
        );
    },
```

3.  TileSource should use lower compliance level method of obtaining images, either w, or ,h but not w,h
```javascript
iiif_size = Math.ceil(iiif_tile_w * scale) + ",";
````

Backports to the 1.0 TileSource would also be useful, though hopefully unnecessary given current deployments.

**Comment by iangilman** [comment]
@azaroth42 @jpstroop  I know there's been some work on the IIIF tile source… Has this issue been resolved?

**Comment by jpstroop** [comment]
@azaroth42 should confirm, but I believe this is ancient history now :smiley:.

**Comment by iangilman** [comment]
Cool. I'll close it. We can reopen if @azaroth42 has concerns. Thanks!
