### ISSUE TITLE
Possible Style Error?

### ISSUE THREAD

**Issue by houseofyin** [openseadragon/openseadragon#326]
Folks,

We are finally getting around to working on our port to OSD.  We noticed a problem when we ran the minimized OSD binary through the Google Closure compiler.  The compiler complained about these two snippets in the minimized code:

i.float="left"
j.style.float="left"

I think these lines originate from:

https://github.com/openseadragon/openseadragon/blob/5a5447dfd36c93dd61a5413f6d07a6afdf94d72a/src/referencestrip.js#L188

https://github.com/openseadragon/openseadragon/blob/9ecb69e1d8cb30a70671fa5d50db66d829b72539/src/navigator.js#L154

The comments suggest that this was done for WebKit compatibility.  However, according to this reference: https://developer.mozilla.org/en-US/docs/Web/CSS/float you don't reference the object directly with float.

Note: If you're referring to this property from JavaScript as a member of the element.style object, you must spell it as cssFloat. Also note that Internet Explorer versions 8 and older spelled this styleFloat. This is an exception to the rule that the name of the DOM member is the camel-case name of the dash-separated CSS name (and is due to the fact that "float" is a reserved word in JavaScript, as with the need to escape "class" as "className" and escape <label>'s "for" as "htmlFor").

Both of the variants suggested here, cssFloat and styleFloat, are already present in the code.

I think the two offending lines can be removed from the source.

**Comment by msalsbery** [comment]
Fixed for v2.4.3

**Comment by msalsbery** [comment]
@houseofyin  Is Google Closure Compiler OK with this?
```
  someElement.style['float'] = ...
```
Or do those need to be removed as well?

**Comment by msalsbery** [comment]
Fixed for v2.5.0 (#1872)

Feel free to reopen if issue persists!
