### ISSUE TITLE
Why textareas? ReferenceStrip causes showing of virtual keyboard on iphone.

### ISSUE THREAD

**Issue by georgy7** [openseadragon/openseadragon#335]
I have no idea know how to prevent this behavior.

**Comment by lhenze** [comment]
Hi, I see there is still a textarea inside the referenceStrip which causes iphone to open its keyboard on focus -- curious, has anyone found a workaround to prevent this behavior? 
Many thanks, enjoying exploring OpenSeaDragon!

**Comment by iangilman** [comment]
I'm not convinced that textarea is even necessary. Theoretically maybe it has something to do with keyboard support, but we support key commands in the main viewer without a textarea. It's possible we can just replace it with a div. Here is where it is created: 

https://github.com/openseadragon/openseadragon/blob/master/src/referencestrip.js#L439

@lhenze Would you be up for giving that a try?

**Comment by avandecreme** [comment]
This has been fixed in de29b56c59ca0f7713d9248a5d111959de60b0bb
