### ISSUE TITLE
Medical image viewer

### ISSUE THREAD

**Issue by pablanco** [openseadragon/openseadragon#34]
Hi, 

I´m working in the development of a medical image viewer with some extra functionality. If you take a look to this demo http://devxtend.com/dsense/seadragon/ms_seadragon/ (built on original seadragon) you will see some tools like "bright and contrast", image overlay, etc.

I would like to make this job with OpenSeadragon instead of seadragon because of the improvements and the support of the proyect but I have some problems when I try to update the viewer. I have read the documentation at http://openseadragon.github.com/docs/symbols/OpenSeadragon.Viewport.html but when I try to update the Drawer or the Viewport I recieve some js errors.

Could you give me any idea about this?
Many Thanks.
Pablo.

**Comment by apricea4** [comment]
@pablanco if you are still around, how are you drawing your lines/what plug in are you using?  I wish I could have been here when your demo was up.  I am trying to do something very similar, draw lines and take measurements of whole slide images.  
Thanks!

**Comment by pablanco** [comment]
Hi @apricea4, it's been a long time since I worked on this but I have a working demo that it could be useful for you if check the code. [http://www.devxtend.com/dsense/DICOM_V107/index.html?objectUID=prueba6](url)

**Comment by apricea4** [comment]
@msalsbery I have been trying to glean what I can from your comments about measuring and pablanco's code but, I am still off.  I convert the web pixels of both points to absolute using pointFromPixel, then I multiply the y coordinates by the aspect ratio of the image like you said and convert the points to imagePoints using viewportToImageCoords.  Finally I use the distance formula and divide that number(distance in pixels) by your zoomFactor expression.  As I zoom in or out I can find a sweet spot where the measuring is almost spot on, but all other zoom levels it is way off.  Is there anything in this process that raises an eyebrow, or any tips you might have?   Cheers

**Comment by iangilman** [comment]
@apricea4 Seems like once you've got image coordinates (which should just be converting straight from viewport to image via viewportToImageCoords, no need for any extra handling with the y coordinate) you should be set at any zoom. You just need to know how to convert from image coordinates to whatever sort of measurement unit you need (e.g. how many pixels per millimeter).

**Comment by apricea4** [comment]
@iangilman Thank you for your reply, I have the microns per pixel for the image so I am multiplying the euclidean distance in image coordinates by that metric(.499 microns per pixel).  pixels * microns/pixel = microns.  At different zoom levels the same distance gives me very different measurements.  But, you are saying that I shouldn't have to worry about my current zoom level?  I am using the fabric js mouse listener to give me the mouse position in web coordinates (I assume).

**Comment by iangilman** [comment]
If you're getting a position in web coordinates relative to the viewer element (where the upper left corner of the viewer is 0, 0), you should just need `viewer.viewport.viewerElementToImageCoordinates` to convert to image pixel coordinates. Then you can convert from there to microns. 

This is assuming you have just a single image per viewer; if not, you need to convert the coordinates for each image separately.

**Comment by sbalci** [comment]
> By the way, I'm compiling a list of sites that use OpenSeadragon... once you folks have something you'd like shared with the world (at least this corner of it), please let me know!

I convert svs images with vips to make a pathology atlas
https://www.patolojiatlasi.com/EN/
See template https://github.com/pathologyatlas/template and instructions https://github.com/pathologyatlas/make-html-WSI

**Comment by iangilman** [comment]
@sbalci Great! Would you like to add your site to https://openseadragon.github.io/examples/in-the-wild/? If so, you can make a pull request on https://github.com/openseadragon/site-build/blob/master/www/in-the-wild.html. Thank you!
