### ISSUE TITLE
Use Tile Source Collections to create composite images

### ISSUE THREAD

**Issue by rsinghal** [openseadragon/openseadragon#344]
I am trying out the collection mode and I want to be able to use that to combine individual images that create a larger image.  Right now, the collection mode always forces a gap between images, even when the collectionTileMargin is set to 0.  So there should be a way to have images line up next to each other without a border or gap.  Also, collection mode by default adds a reflection.  There should be an option to disable this (because simply disabling that in drawer.js seems to affect the zoom levels and prevents deep zooming).

**Comment by iangilman** [comment]
This issue is obsolete now that we have #386
