### ISSUE TITLE
Left and right arrows should be hidden in collection mode

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/openseadragon#362]
Reproducible here: http://openseadragon.github.io/examples/tilesource-collection/

If clicked, the collection is re-opened and warnings are printed in the console.

**Comment by iangilman** [comment]
@rsinghal do you have a patch for this?

**Comment by iangilman** [comment]
@rsinghal Any word on a patch?

**Comment by rsinghal** [comment]
Unfortunately, I can't find the fix anymore - it's been over a year!

**Comment by iangilman** [comment]
Aha! I didn't notice the year on the posting...actually, I don't see the issue now on: 

http://openseadragon.github.io/examples/tilesource-collection/

...so it looks like it's already been fixed. :) 

I'll go ahead and close this; @avandecreme please reopen if you can repro.
