### ISSUE TITLE
Add OpenSeadragon to jsdelivr?

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#372]
@acdha has spotted this:

https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/

Seems like an easy way to get OpenSeadragon on CDN, if there's any interest in that.

**Comment by jedateach** [comment]
for setting up demos - yes there is interest!

**Comment by iangilman** [comment]
Cool...I'll look into it.

**Comment by iangilman** [comment]
Here is another one to consider: https://cdnjs.com/

I'm not sure how best to evaluate the pros and cons...seems like we should pick one rather than being on both?

**Comment by acdha** [comment]
CDNJS is the one I use for simple static demos – CloudFlare's performance tends to be excellent – but since both of them appear to have automatic npm / github update mechanisms, perhaps it'd simply make sense to publish to both so someone who's already using one can stick with it?

**Comment by iangilman** [comment]
Fair enough :)

**Comment by mekarpeles** [comment]
Is/has this been done?

**Comment by iangilman** [comment]
@mekarpeles Not yet...thanks for the nudge!

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

**Comment by iangilman** [comment]
@jimaek Good to know! 

Btw, here's the issue for cdnjs: https://github.com/cdnjs/cdnjs/issues/8811

**Comment by jimaek** [comment]
https://cdn.jsdelivr.net/npm/openseadragon@2
https://cdn.jsdelivr.net/npm/openseadragon@2/

Let me know if you have any feedback :)

**Comment by iangilman** [comment]
@jimaek That looks fantastic! Everything's there as far as I can tell. Did you make this happen? Thank you :)

Will it automatically update for new releases? Is there any ongoing maintenance we need to keep in mind?

We should add it to the download section here: 

http://openseadragon.github.io/#download

What sort of instruction should we give? What's the best practice for linking to the library (e.g. always include the version number)?

I can update the page with the proper info, but you're also welcome to; it's in the site-build repository here: 

https://github.com/openseadragon/site-build/blob/master/www/index.html#L204

Thanks again!

**Comment by jimaek** [comment]
>That looks fantastic! Everything's there as far as I can tell. Did you make this happen? Thank you :)

Its my project if that is what you mean. My team and I worked hard on this :)

>Will it automatically update for new releases? Is there any ongoing maintenance we need to keep in mind?

Yes, it will automatically pull new releases with 1 minute delay. No maintenance needed.

>What sort of instruction should we give? What's the best practice for linking to the library (e.g. always include the version number)?

It depends on your project what version to use. If there could be breaking changes between minor releases then I recommend using full versions in the URL. If you only include bug fixes then you can alias to `/2/` and make all users get the latest 2.x.x version automatically.

**Comment by iangilman** [comment]
Wonderful! Thank you again :)

Our breaking changes are always accompanied by a change to the second version value (e.g. from 2.2.0 to 2.3.0), so I guess I'll link to: 

https://cdn.jsdelivr.net/npm/openseadragon@2.2/build/openseadragon/openseadragon.min.js

...and have people point to here for the UI images:

https://cdn.jsdelivr.net/npm/openseadragon@2.2/build/openseadragon/images/

Btw, if we just use this link for the script:

https://cdn.jsdelivr.net/npm/openseadragon@2.2

...does it serve up the `.map` file appropriately?

**Comment by jimaek** [comment]
>...does it serve up the .map file appropriately?

Unfortunately no, you will need to use the full path for map to work. But its not needed in production and wont be loaded at all by default. So I don't think thats a problem.

**Comment by iangilman** [comment]
Good point. Great, I think I have all the info I need!

**Comment by iangilman** [comment]
Okay, I've updated the page: 

http://openseadragon.github.io/#download

...and tweeted:

https://twitter.com/openseadragon/status/862726010294251520

Thanks again!
