### ISSUE TITLE
Sunsetting IE8

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#373]
As discussed in #106, we're planning to drop support for IE8 when Microsoft does. That date (April 8th, 2014) is rapidly approaching, and we have a patch (#369) which will drop support for IE8 mouse events. 

I'm posting this issue as a heads-up and an opportunity for any discussion.

**Comment by msalsbery** [comment]
*bump*

We've given this an extra 9 months, and I discovered today with version 1.2.0 we are fairly broken on IE 8. DZI tile sources no longer work, the pointer capture fix (mentioned above) which worked great on all IE versions was inconsistent in other browsers so it was removed a couple versions ago, making MouseTracker broken again on IE 8. There's probably more....I just noticed these again today.

So are we ready to drop IE 8 support at this point? Should we patch the latest code to work on IE 8? Should we find the last version that works on IE 8 and document that as the only IE 8 OSD solution?

Discuss! :)

**Comment by benjamind** [comment]
Personally I need IE8 support, so either I'll be sticking with what I'm currently running, or I'll have to figure out how to patch this one way or another!

**Comment by msalsbery** [comment]
@benjamind Which OpenSeadragon version are you using?

**Comment by benjamind** [comment]
I'm currently using 1.2, but I've not delved into IE8 compatibility testing yet. I know its on the horizon however as all our apps have to run on IE8 (lots of Chinese users). So either I'll be reverting to the earlier 1.1.x builds or fixing this. :-)

**Comment by msalsbery** [comment]
@benjamind  We're not close to making a big decision here, but just curious - would you be ok with having to use a plugin (add another script file after openseadragon.js) to have IE8 support?

**Comment by benjamind** [comment]
That would be fine by me and if it frees up the main library all the better. I compile everything down to a single file anyway so its no overhead at all as far as loading is concerned.

**Comment by mscheper** [comment]
So I've just been handed the unenviable task of making an OSD-based app work in IE8. It's been years since I've had to worry about IE at all, so it's encouraging to read here that even M$ may no longer support IE8.

However, this blog post, by the director of IE, suggests this won't actually be true until January 2016: http://blogs.msdn.com/b/ie/archive/2014/08/07/stay-up-to-date-with-internet-explorer.aspx?utm_medium=referral&utm_source=pulsenews I'll therefore have to wait until the end of next summer before I can really push back. :-(

In the meantime, am I to understand that the latest OSD 1.x should work in IE8? (I've found an old Windows box to try it on... just waiting for IE8 to finish installing on it...)

**Comment by iangilman** [comment]
@mscheper My understanding is that the core OSD still works on IE8. Some of the newer features may not work (like viewport rotation), of course. Please let us know how it goes! We rely on folks like you and @benjamind, who are actually working with IE8, to keep that area shipshape.

**Comment by iangilman** [comment]
It's been two years since we last discussed this... @benjamind, @mscheper are you still needing IE8 support? Anyone else?

**Comment by iangilman** [comment]
No response... maybe it's time to finally let IE8 support go?

**Comment by acdha** [comment]
👍 On the sites I use, IE8 is currently under 0.1% and that seems like a perfectly reasonable place to say anyone who still cares about it can either continue to use an older release or contribute to maintenance.

**Comment by msalsbery** [comment]
Let it go!

**Comment by iangilman** [comment]
Cool. Well, I think we'll make 2.3.0 the official last IE8 compatible release, then :)

**Comment by msalsbery** [comment]
#*Yay!*

**Comment by mscheper** [comment]
@iangilman: Sorry, I went through a period of not watching my notifications properly. It's moot now, but I really appreciate you checking.

**Comment by iangilman** [comment]
@mscheper Moot as in we've already made our decision, or as in you no longer need to support IE8?

**Comment by iangilman** [comment]
2.4.0 has shipped, so I'm closing this. What remains to be done is document the fact, which is covered in https://github.com/openseadragon/openseadragon/issues/106.

**Comment by iangilman** [comment]
FYI, for anyone paying attention here, we are now planning to no longer support IE 9 and IE 10 in OpenSeadragon 2.5.0 (still supporting IE 11).
