### ISSUE TITLE
Links as overlays

### ISSUE THREAD

**Issue by philipgiuliani** [openseadragon/openseadragon#401]
I have added some links as overlays like this:

``` javascript
var buttonViewport = new OpenSeadragon.Rect(viewportPosX, viewportPosY, viewportWidth, viewportHeight);

var buttonElement = document.createElement("a");
buttonElement.target = "_blank";
buttonElement.href = button.href;
buttonElement.className = "button " + button.type

myImage.viewer.addOverlay(buttonElement, buttonViewport, OpenSeadragon.OverlayPlacement.CENTER);
```

If i click now with the mouse on the button, its not triggering the a#href action, its just zooming into the button. Its possible to prevent the zooming and following the link of the button? I also could create an event which will handle the button click, but im sure there is a better solution.

Thanks!

**Comment by dyablohunter** [comment]
Hi guys,

Does anyone know if the links overlayed can be generated in such a way to be indexed by search engines?

Thanks.

**Comment by iangilman** [comment]
I'm not up on the latest SEO; I know it used to be that the search engines only looked at what HTML was originally in your page, not anything added later via JavaScript. This may not be true anymore. At any rate, even if it is, you could build the overlays onto the page and then attach them to OSD as needed. 

Other than that, I don't know enough about SEO to help.
