### ISSUE TITLE
Why are aspect ratios of layers required to match?

### ISSUE THREAD

**Issue by jcoyne** [openseadragon/openseadragon#425]
/cc @avandecreme

Regarding this commit: https://github.com/openseadragon/openseadragon/commit/d43b6d86b50e2b0cbd527345a3c7aa1e65467f8f

Can you help me to understand why OSD validates that the aspect ratios of all the layers match?  From a users perspective, it seems reasonable to want to create two layers, one that holds a portrait image and the other that has a landscape image.

**Comment by iangilman** [comment]
By the way, #386 has landed (though not yet released), so this restriction is no longer the case.
