### ISSUE TITLE
Double Tap v. Double Click?

### ISSUE THREAD

**Issue by gechols** [openseadragon/openseadragon#433]
I would like to have OpenSeadragon treat the Double Tap gesture on my phone a bit different than the Double Click on my PC.

The current behavior of Double Click (once you enable it) seems to follow the current standard of zooming in one level each time you double click. This fits the mouse user model really well.

It seems like the industry standard behavior on a phone for Double Tap is to toggle the zoom between max and min zoom levels. This gives a phone user a quick way to drill down on an element by double tapping the screen, and then return to the 'home view' by double tapping again.

I see that double click has been implemented (THANK YOU) and was wondering if there is a plan or ability to differentiate between double click and double tap.

Am I explaining this clearly? Is there any interest in having this a part of OpenSeadragon?

**Comment by valnub** [comment]
Works like a charm! Thanks for the sharing.
