### ISSUE TITLE
How to open a DZI?

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#438]
This issue is for a continuation of the conversation that starts at https://github.com/openseadragon/site-build/issues/5#issuecomment-47459553.

**Comment by terenceingram** [comment]
@iangilman I am wondering if the OpenSeadragon examples that mention Deep Zoom should have a snippet showing how to have multiple images and also setting the property sequenceMode : true. For example from above: 

tileSources: [
                    data[0].dzi,
                    data[1].dzi,
                    data[2].dzi
                ]

It took me a while to actually find some code that did what I wanted. Even though the examples are great, I had to look at the source code for quite a few before actually figuring out how it worked.

**Comment by iangilman** [comment]
@terenceingram Sorry to hear that! We have exactly that here: 

http://openseadragon.github.io/examples/tilesource-sequence/

What example were you finding that led you astray?
