### ISSUE TITLE
Openseadragron and frame/iframe

### ISSUE THREAD

**Issue by nagame-net** [openseadragon/openseadragon#464]
I have a problem with mouse tracking, on Webkit, when OpenSeadragon is in an iframe / frame.

You can easily reproduce : http://jsfiddle.net/ye6t05xm/
- test code < iframe src="http://openseadragon.github.io/" width="700" height="700" > < /iframe >,
- drag the image and move the mouse pointer outside the iframe,
- release the mouse button and return to the image,
- the tracking is blocked.

The bug exists only with Webkit. No problem with Firefox/IE.

I can detect the mouse exit of the iframe, but OpenSeadragon library don't have a public method to force stop the tracking.

Apologies for my broken English :)
Thank you!

**Comment by iangilman** [comment]
I believe this is fixed by #790

**Comment by iangilman** [comment]
...note, however, that #790 only applies if the iframe and the containing window are on the same domain.
