### ISSUE TITLE
Brightness and contrast

### ISSUE THREAD

**Issue by selko** [openseadragon/openseadragon#475]
Someone can help or show an example how it works a function with brightness and contrast. I would like to put into my viewer.

THx!!!!!!

**Comment by selko** [comment]
there is a contrast function made in some place? Thanks! I made brightness using CSS3 filters but contrast i didnt!

**Comment by iangilman** [comment]
No one's written a contrast plugin for OpenSeadragon that I'm aware of, but it should be possible using one or another of the techniques above.

**Comment by borowiak** [comment]
i would like to help in that , I have external code for OSD that do this effects, can you explain me how to start to include this as a core feature.

**Comment by suxonca** [comment]
I know how implement this features, it's done, I did the external code for a OSD canvas, even works for all browsers, but i dont know how to start for include this in the core of OSD. could you help me ?

**Comment by avandecreme** [comment]
This is actually now implemented with the [OpenSeadragon Filtering plugin](https://github.com/usnistgov/OpenSeadragonFiltering).

**Comment by iangilman** [comment]
@avandecreme Good point, thanks for pointing it out!

@suxonca Does the filtering plugin do everything your implementation does? If not, perhaps you can contribute to it?

Closing this as resolved.

**Comment by suxonca** [comment]
@avandecreme thank you, it works perfect.

@avandecreme yes do everything and more, I dont think my code can help, it is a very good plugin. I did it in the hard way because i dont found nothing about, but I think that this comment is going to be help for someone else.
thanks for your reply guys.

**Comment by suxonca** [comment]
and I think that will be useful a link in the main examples page on the OSD website

**Comment by iangilman** [comment]
It's listed in the plugins section of the main page:

http://openseadragon.github.io/#plugins

Good to hear it serves your needs!
