### ISSUE TITLE
Download and print images?

### ISSUE THREAD

**Issue by estockwellalpert** [openseadragon/openseadragon#477]
I'm using openseadragon in a project and my client wants me to add buttons to download and print the images. I'm hoping you can help me, because I really have no idea where to start. There's two major steps here:
(1) Add custom buttons to the viewer nav. I'm opening the viewer as follows:

    var viewer = OpenSeadragon({
                    id: "databaseviewer",
                    prefixUrl: "../../Scripts/openseadragon/images/",
                    tileSources: url,
                    maxZoomLevel: 20
                });

Is there a place in that call that I could specify new nav images? I really don't know what i need to do here.

(2) Create the download/print functionality. If I had a simple .jpg I could figure this out myself, but I obviously can't print a dzi tile source. What would I need to do to print the image being displayed in the viewer?

If you can help me at all with this I'd really appreciate it.

**Comment by nikhilagastya** [comment]
hey i have a query ,I made annotations with recognito/annatorious and now i want to download the area inside the annotations ,how do i do it ?

**Comment by iangilman** [comment]
@nikhilagastya You should be able to grab whatever's in the Drawer's canvas... That'll be the current view at the moment you grab it. You can then cut it down to just the area inside the annotation.
