### ISSUE TITLE
Mouse Right-button click default action

### ISSUE THREAD

**Issue by w3surfer** [openseadragon/openseadragon#479]
Just a couple of questions/suggestions from a newbie end-user who just started using version 1.1.1.  

Would it be possible to change the default action of a Mouse 'right-button click' and replace it with something else?  Right now a 'right click' brings up the 'context menu' (at least in windows).  I would like it to do a zoom-out centered on mouse location, thereby complementing the left-button and not requiring a Shift key depression.  This would make the mouse button actions symmetrical.  Maybe a specified start-up 'option' could be provided that would allow the change (ie: rightButton:  normal || zoomOut) for those inclined to use it.   

Additionally,  would like to see the 'middle-button' click to be used for something useful.  Right now it seems to do exactly the same as the left-button.  How about if middle-button is pressed the viewport re-centers on mouse's current location? 

OpenSeadragon looks extremely useful.  Now if only I can find some good examples of how to use overlays.  Would like to see samples of usage with a bit more detail than in  http://openseadragon.github.io/examples/ui-overlays/ .  Can the overlays have clickable links in them in addition to comments? Links that would open up in new tabbed windows, thereby not destroying the viewer window.

	Thanks,
			- Nat

**Comment by msalsbery** [comment]
#562 adds primitive exposure to alternate/auxiliary button events from MouseTracker through Viewer.

@w3surfer hope this helps a little. You'll still probably need to handle the contextmenu event somewhere to prevent the popup.
