### ISSUE TITLE
Number of overlays?

### ISSUE THREAD

**Issue by PetterRanefall** [openseadragon/openseadragon#480]
Are there any limitations regarding number of overlays, or is that just a memory issue? I have quite large images (30000x40000 pixels) and would like to put a lot of (>60000) small markers (9x9 or 18x18 pixels large) as overlays, but that does not seem to be possible, at least not on my computer with 24 GB of RAM.
I have also tried to create a single full size image for each marker type, but then I run into problems (in python) when creating such a large RGB image.

Do you have any suggestions on how to overcome this problem?

**Comment by zloysmiertniy** [comment]
Hello! a few years later. We are still trying to work on this. Is overlay canvas a plugin nowadays? If not, would it be too much to ask to see how it was implemented inside a project? so we could try and use it ourselves too? We were thinking of creating a big SVG, the problem with this is that even inside the big SVG each individual little marker has to keep its size.

**Comment by iangilman** [comment]
Yes, we now have canvas and SVG overlay plugins: 

https://github.com/altert/OpenSeadragonCanvasOverlay

https://github.com/openseadragon/svg-overlay

I think Canvas is probably the best choice for your needs.

**Comment by iangilman** [comment]
...I guess that means this issue can be closed, since those plugins now exist!
