### ISSUE TITLE
HTC "Internet" application touch issues.

### ISSUE THREAD

**Issue by crswll** [openseadragon/openseadragon#484]
I'm running Android 4.4.2, HTC Sense version 6.0, 

When I use use touch to zoom in I get a very weird effect. It seems to put a static version of the image over top of the zoomable part of the image. Here's a video of it: https://www.youtube.com/watch?v=tM3aiS-au6Q

**Comment by iangilman** [comment]
@crswll any news on this? Do we still care about it? :-)
