### ISSUE TITLE
Viewer pre-full-screen event not raised on Esc from full screen

### ISSUE THREAD

**Issue by jstevensonhoare** [openseadragon/openseadragon#487]
The <code>Viewer</code> event <code>pre-full-screen</code> is not raised when Esc is used to exit full screen mode, but is if the 'Toggle full page' toolbar button is used to exit.

**Comment by avandecreme** [comment]
Unfortunately, I don't think it is possible.
The `fullscreenchange` event is only triggered once the change has happened, which is too late to trigger the pre-full-screen event.
We are always triggering the full-screen event though.

**Comment by iangilman** [comment]
Good point. I guess we should at least document this issue in the documentation for `pre-full-screen`.
