### ISSUE TITLE
Custom location navigator position is changed from 'fixed' to 'relative'

### ISSUE THREAD

**Issue by jstevensonhoare** [openseadragon/openseadragon#496]
I am trying to use a custom location navigator that is fixed. I styled my div with <code>position: fixed;</code>. After creating an instance of the OpenSeadragon class using the <code>navigatorId</code> option, my div has an element style of <code>position: relative;</code>.

Is this expected behaviour? I have to override the styling in an open event handler to reset it back to <code>position: fixed;</code>.

Also, why does a custom location navigator get hidden when going to full screen but not the toolbar?

**Comment by AditSaxena** [comment]
Hi
I would like to work on this issue.

**Comment by iangilman** [comment]
@AditSaxena Wonderful! Please do :) Here are our contribution guidelines:

https://github.com/openseadragon/openseadragon/blob/master/CONTRIBUTING.md

I assume the thing you're wanting to work on is making sure it doesn't go `position: relative` if it's already something other than `position: static`? Let me know if you need any pointers :)

**Comment by AditSaxena** [comment]
@iangilman yes I'm willing to give this a try. Please assign it to me.

**Comment by iangilman** [comment]
@AditSaxena Great! You're assigned :) Let me know if you need anything else!

**Comment by jetic83** [comment]
@AditSaxena , I do have a related problem... I use an own div with an ID for the navigator.
With OSD 2.x, this works very well. But with OSD 4.x, the navigator is a blurred window and the minimap is completely screwed.
<img width="436" alt="image" src="https://user-images.githubusercontent.com/11157551/214309102-83fd4691-5209-40bc-a03e-5a8e4f8ed03b.png">
I could solve it with an additional viewer.navigator.updateSize() after page loading.

**Comment by iangilman** [comment]
@AditSaxena Are you still interested in working on this? @jetic83 If we don't hear back from him, would you like to take it on?

**Comment by VIRAT9358** [comment]
Hey @iangilman  
I would like to work on this issue
Could you assign me if no one else if working

**Comment by iangilman** [comment]
@VIRAT9358 Great! No one else is working on it... I've assigned you :)

**Comment by VIRAT9358** [comment]
@iangilman Hey can you help me finding the exact line of code where I need to work .
I tried going into fullscreen.js

**Comment by iangilman** [comment]
@VIRAT9358 Sure! The `position: relative` issue is here: 

https://github.com/openseadragon/openseadragon/blob/ffbd8f985a4dab4fdde855458383f50f6973eb7a/src/navigator.js#L165

I suggest just focusing on that issue. The other thing mentioned here (creating a mechanism for exceptions to the fact we hide everything when we go to fullscreen) is a much bigger project and shouldn't really be considered part of this issue.

**Comment by VIRAT9358** [comment]
Sorry for the delay I was busy with exams.
I have made changes in the code .
`
     style.position      = 'static';
`
![image](https://github.com/openseadragon/openseadragon/assets/74507238/787d940c-c996-40b1-b21f-31ea4ede0f4b)

**Comment by VIRAT9358** [comment]
![image](https://github.com/openseadragon/openseadragon/assets/74507238/30fa78ad-3797-4244-be3e-6cc08d02f224)

**Comment by VIRAT9358** [comment]
Please update me if further changes are need or else can I request for a merge ?

**Comment by iangilman** [comment]
@VIRAT9358 Thank you for working on this! As mentioned in https://github.com/openseadragon/openseadragon/issues/496#issuecomment-58685122 the task is to make it so we only set the `position` to `relative` if the position is already `static`; otherwise leave it alone. Does that make sense?

**Comment by VIRAT9358** [comment]
`if (style.position === 'static') {
    style.position = 'relative';
}
`
ok is this correct then

**Comment by iangilman** [comment]
@VIRAT9358 Yup, that should do it! Please make a pull request with it 😄

**Comment by VIRAT9358** [comment]
I made my own branch and tried to push but it shows permission denied .
Can u help me to that I can create a pull request .

**Comment by iangilman** [comment]
Great! You'll need to fork this repository and copy your changes to the fork. Then you can make a pull request. Here's more info: https://github.com/openseadragon/openseadragon/wiki/Making-a-Pull-Request

**Comment by VIRAT9358** [comment]
Created a PR.

**Comment by VIRAT9358** [comment]
Created a new PR again.
With keeping all your points in mind.

**Comment by VIRAT9358** [comment]
Updated all changes ready to merge.

**Comment by iangilman** [comment]
Fixed by #2393
