### ISSUE TITLE
Compress static images

### ISSUE THREAD

**Issue by acdha** [openseadragon/openseadragon#50]
Using the simple script at https://gist.github.com/acdha/5239224#file-compress-images-sh trims the contents of `images/` down from 160KB to 100KB. Think it's worth adding a Grunt target to do this?

It also feels like it would be worth looking into a maintainable spriting system since that would let the compressors benefit from seeing more data.

**Comment by iangilman** [comment]
We've now manually compressed the images with #1134. I think I'll close this for now and we can revisit the idea of an automatic compression as part of our build if/when we start taking more changes to our UI images.
