### ISSUE TITLE
Canvas blocks mouseup events on itself.

### ISSUE THREAD

**Issue by aeschylus** [openseadragon/openseadragon#502]
Calling `jQuery(viewer.canvas).on("mouseup", function() { console.log("mouseup"); });` does not work. Neither does using openSeadragon's `.addEvent` method for "mouseup".

**Comment by this-vidor** [comment]
@msalsbery 

> For overlays, aside from bug fixes as mentioned above, I'm going to do some advanced documentation on event handling so it's understood how the viewer handles events and how it can affect overlayed elements.

Where does this documentation exist?

**Comment by iangilman** [comment]
Unfortunately I think it still does not. Do you have specific questions?

**Comment by this-vidor** [comment]
I posed the question trying to resolve a conflict between React's event delegation system, and OpenSeadragon's. I was able to implement a workaround by toggling capture using the `viewer.setMouseNavEnabled` method. It would be easier to target specific events given better documentation— `setMouseNavEnabled` itself receives no explanation in [the current docs](https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#setMouseNavEnabled).

The particular issue arises when a React application is mounted to a viewer overlay element; I was unable to find another approach that allows React to handle `mousedown` and `mouseup` events.

**Comment by iangilman** [comment]
Interesting. The general procedure is to use OpenSeadragon.MouseTracker to handle events on overlays, but I guess maybe that wouldn't hook into React very well.

Under the hood setMouseNavEnabled calls the setTracking function of the viewer's MouseTrackers... at the moment there's no mechanism to be more specific than all on or all off. 

Anyway, MouseTracker is where to look if you want to dig in more.

**Comment by this-vidor** [comment]
@iangilman Thank you. I see that the method `setMouseNavEnabled` calls `setTracking`, which calls `startTracking`, which maps the function `OpenSeadragon.addEvent` over an Array called `MouseTracker.subscribeEvents`.

It appears that `MouseTracker.subscribeEvents` is just an Array of strings naming events. While it seems plausible to simply replicate the functionality of those methods using a modified Array of event names, it is unclear how eliminating `mousedown` and `mouseup` from the viewer's `innerTracker` and `outerTracker` would affect functionality. Indeed, it is unclear the difference in purpose between those two MouseTrackers.

While `MouseTracker.setMouseNavEnabled` works for my immediate purposes, it seems there is interest in overriding the "swallowing" of `mouseup` and `mousedown`. This has been articulated as a purposeful design decision. Is the swallowing actually necessary for gestures to work properly? Where does this `stopPropagation` happen in the source? Is this the right venue for me to be asking these questions?

**Comment by iangilman** [comment]
Hopefully @msalsbery can weigh in because he understands the gesture handling better than anyone. My understanding is that the swallowing was necessary in order to properly handle gestures on devices that handle more than one kind of gesture. OSD supports mouse, touch, and pen gestures, and some devices, like the Microsoft Surface support all three simultaneously. I believe it's keeping all those straight that means we need to stop the events from propagating. @msalsbery can weigh in though.

If you want to dig in deeper, look for `stopEvent` and `stopPropagation` in the MouseTracker source. Maybe there's a way to keep everything straight without stopping the events...
