### ISSUE TITLE
custom buttons aren't working

### ISSUE THREAD

**Issue by chriseugenerodriguez** [openseadragon/openseadragon#516]
just want to add id's to 2 buttons, here is code:

var viewer = OpenSeadragon({
    id: "heaven1",  
    prefixUrl: "/assets/images/manuscripts/heaven/",
    toolbar: "navigation-pane",
    zoomInButton:   "zoom-in",
    zoomOutButton:  "zoom-out", 
    showNavigator: true, 
    panHorizontal:  true,
    defaultZoomLevel:   1,
    minZoomLevel:   1,
    maxZoomLevel:   3,
    visibilityRatio:    1,
    constrainDuringPan: true,
    tileSources: [{
        type: 'legacy-image-pyramid',
        levels: [{
        url: "assets/images/manuscripts/heaven/heaven4.jpg",
        height: 2133,
        width: 1500
                }],}]
    });

This doesn't add  the IDs to the buttons and shows all normal buttons.

**Comment by liekeheijne** [comment]
I am still having this problem. 
These are my custom zoom in and out buttons 
```
<div class="plotMap__zoom-controls">
     <button id="ZoomIn">+</button>
     <button id="ZoomOut">-</button>
</div>
```

And in OpenseaDragon I add them like this 
```
OpenSeadragon({
    id: "example-xmlhttprequest-for-info-json",

    prefixUrl: "https://static.zoomhub.net/openseadragon-images/",
  
    tileSources: {
      type: "image",
      url: "imgurl",
    },
  
    visibilityRatio: 1,
    constrainDuringPan: true,
  
    showNavigator: true,
    showNavigationControl: false,
    navigatorAutoFade: false,
    navigatorPosition: "ABSOLUTE",
    navigatorTop: "24px",
    navigatorLeft: "24px",
    navigatorHeight: this.navigatorImgHeight,
    navigatorWidth: "145px",
    zoomPerClick: 1,
  
    defaultZoomLevel: 1,
    minZoomLevel: 1,
    zoomInButton: "ZoomIn",
    zoomOutButton: "ZoomOut",
});
```


But when I click my custom buttons, nothing happens. I added a video of clicking the buttons.
https://gyazo.com/1b278ab8f8cdc3336cb7f5f2bce7d11c

**Comment by iangilman** [comment]
@liekeheijne This isn't well documented, but the zoom buttons use `zoomPerClick` to know how much to zoom. Since you've set it to 1 it's not zooming at all. I assume you set it that way to disable click to zoom? An alternate way to do so is with `gestureSettingsMouse: { clickToZoom: false }`.
