### ISSUE TITLE
setMouseNavEnabled causes sticky mouse

### ISSUE THREAD

**Issue by ricochet2200** [openseadragon/openseadragon#518]
Calling viewer.setMouseNavEnabled(false) while the mouse is pressed causes all mouse movement to act as if the mouse is pressed.  Once in this state, the only way I've found to fix this is to reload the page.

**Comment by r03ert0** [comment]
Hello,
I may have a new case of sticky mouse.
I'm writing an app to draw vectorial annotations (using Paper.js) on top of openseadragon.
It used to work only in Firefox until some weeks ago, but now it has the same bug in Firefox, Safari and Chrome: After setting setMouseNavEnabled(false), I configure Paper.js to handle mouseDown, mouseDrag and MouseUp, but only mouseDown is properly handled. MouseUp is never fired, and MouseDrag is fired when the mouse moves but the button is not pressed...
I have tried to find the source of the error without much success. The only strange thing I have found is that the removeEvent function is being called on mousemove and mouseup even though setMouseNavEnabled has been set to false (is it probably removing my Paper.js events?).

You can see my app bugging (with a super nice high resolution slice of a human brain) here: http://siphonophore.org/microdraw

all the best,
roberto

**Comment by r03ert0** [comment]
the issue was solved for me by commenting out everything inside the stopEvent function:
```
        stopEvent: function( event ) {
        /*
            event = $.getEvent( event );
            if ( event.stopPropagation ) {
                // W3C for stopping propagation
                $.stopEvent = function( event ){
                    event.stopPropagation();
                };
            } else {
                // IE for stopping propagation
                $.stopEvent = function( event ){
                    event = $.getEvent( event );
                    event.cancelBubble = true;
                };
            }
            $.stopEvent( event );
        */
        }
```

is there any drawback to this?

thanks,
roberto

**Comment by iangilman** [comment]
@msalsbery knows better than I what the problems with commenting out OpenSeadragon's stopEvent function are, but it's probably not a good long term solution for you. 

When doing event handling on top of OpenSeadragon, we recommend using OpenSeadragon.MouseTracker. It works well with the OpenSeadragon viewer, and it handles events for mouse, touch, and stylus. My recommendation is to not use the Paper.js events but instead use MouseTracker events and pipe them into Paper as needed.

**Comment by msalsbery** [comment]
@r03ert0 Ian's recommendations are correct.

Seems most frameworks assume they're used on top of elements that ignore pointer input, so they work just fine. The Openseadragon viewer uses pointer events heavily so elements on top (in z-order) of the viewer must take care to prevent the viewer's default handling of pointer events that are allowed to bubble up.

**Comment by r03ert0** [comment]
thank you!

**Comment by b-ha** [comment]
I think the issue I am having is similar to the issues seen here with sticky mouse press.  I am using version 2.1 version.  When I zoom and pan the image out of the viewer port, the mouse becomes sticky as if the mouse-click is still on.  If I drag it out again, it longer pans.  Here's the link http://peoplespottery.com/nanorosetta.php.  

	var viewer = OpenSeadragon({
	id: "_zoom",
	prefixUrl: "/openseadragon/images/",
	tileSources: "/sarahha/zoom/carla/dzc_output.xml",
	showNavigator: false,
	constrainDuringPan: true,
	visibilityRatio: 1
	});

**Comment by r03ert0** [comment]
in my case the problem was that I had 2 different ways of handling
mouse/touch events.
What solved the issue in my case was to use these hooks:

    viewer.addViewerInputHook({hooks: [
        {tracker: 'viewer', handler: 'clickHandler', hookHandler:
clickHandler},
        {tracker: 'viewer', handler: 'pressHandler', hookHandler:
pressHandler},
        {tracker: 'viewer', handler: 'dragHandler', hookHandler:
dragHandler},
        {tracker: 'viewer', handler: 'dragEndHandler', hookHandler:
dragEndHandler}
    ]});

I have a global variable navEnabled to control whether i let openseadragon
handle the events or my alternative handlers, like this

function dragHandler(event){
    if( !navEnabled ) {
        event.stopHandlers = true;

mouseDrag(event.originalEvent.layerX,event.originalEvent.layerY,event.delta.x,event.delta.y);
// my alternative function
    }
}

hope this helps,
roberto

**Comment by b-ha** [comment]
Thanks Roberto.  I'm only a casual programmer so not really sure how hooks work.  I will dig into this approach more.  Thanks!

Bruce
