### ISSUE TITLE
From .ndpi to OpenSeaDragon

### ISSUE THREAD

**Issue by UneFrite** [openseadragon/openseadragon#530]
Hi!

I'm a little bit lost in all the new thing I have to learn. I have a lot of source-images in .ndpi extension, some have huge size (up to 3gb). I'd like to make them viewable online, using OpenSeaDragon, as I saw it was the most convenient. I managed to make it work for small images by exporting the .ndpi files to .tif files then using Deep Zoom Composer (as recommended) in order to have something usable by OpenSeaDragon.

The problem is that Deep Zoom Composer won't take any big .tif, so I have to split my .ndpi files to multiple .tif images in order to recompose them in DZC. Which is veeeery slow. 

I don't know if there is anything I do in a bad way (excepting my English :D) and I'm currently blocked... And  that sucks. 

I hope someone will help me :)

Thanks a lot!

**Comment by KempWatson** [comment]
Our image server and cloud service support NDPI directly, and outputs a "virtual" Zoomify folder, which works well with OpenSeadragon as well as Zoomify. No need to convert anything at all. I see people going through these unnecessary conniptions all the time...

And we also have prebuilt tools to convert NDPI to pretty much anything you'd like as well.

https://www.objectivepathology.com

**Comment by Saqib92** [comment]
how can i view `.ndpi` files directly in OpenSeaDragon? My files are about 200 mb to 5 gb.

**Comment by KempWatson** [comment]
You can't, at least not without an incredible amount of effort and custom
coding. You'll need to write your own custom TileSource, and will need to
make a new version of libjpeg with some custom alterations to the C code,
and package it as a WASM file for delivery alongside OSD.
If you mean more generically is there a way to view .ndpi files with OSD,
then yes, if you use a backend server that can convert .ndpi into a form
that OSD can digest. We do this for .ndpi and all other digital pathology
formats, you can see examples at

*https://the.pathology.network*
<https://the.pathology.network/default.aspx?global=/Supported%20Formats> in
the "Hamamatsu" folder. The files are stored in their original .ndpi format
on the back-end, and you can serve millions of slides if you like,
data-resident in 30 countries, on your own premises, or in a hybrid
configuration.

To minimize the "salesy" aspect here, do note that there are also several
other vendors providing similar services, but you would need to check with
them about the details of their products.
Also, you could ask your question directly to Hamamatsu and they may have a
solution suitable for you.

Kemp Watson
Objective Pathology Services
