### ISSUE TITLE
High pixel density (retina) support

### ISSUE THREAD

**Issue by wesleyfok** [openseadragon/openseadragon#541]
On various high-density screens (most often smartphones, but potentially elsewhere), browsers tend to render canvas elements at a relatively low pixel density. [Here's an overview of the issues.](http://www.html5rocks.com/en/tutorials/canvas/hidpi/) In OpenSeadragon, what that means is that there's a significant difference in how images are displayed when useCanvas is set to true or false.

Setup: I've set the tileSize of my source to 256px, but am secretly feeding 512x512 images via getTileUrl(). In theory, this should allow the OpenSeadragon viewport to render images sharply on high-dpi screens.

*useCanvas set to false: everything looks fine*
![usecanvasfalse1](https://cloud.githubusercontent.com/assets/3732772/5445170/a6ea5020-847f-11e4-94fd-995f59e1c70f.png)
![usecanvasfalse2](https://cloud.githubusercontent.com/assets/3732772/5445168/a6e62e46-847f-11e4-93c7-823018f73b6d.png)

*useCanvas set to true: pixelated images*
![usecanvastrue1](https://cloud.githubusercontent.com/assets/3732772/5445171/a6eaf21e-847f-11e4-8038-76073f7008eb.png)
![usecanvastrue2](https://cloud.githubusercontent.com/assets/3732772/5445169/a6e9d71c-847f-11e4-8fe7-29ee3113f67f.png)

**Comment by wesleyfok** [comment]
Hope I'm doing this right, I'm still new to github collaboration. I forked the repo and added in the changes from the patch above (modified as per iangilman's suggestions) and applied it to more areas. The canvas now uses the full viewport area to display images, and there don't seem to be any weird issues with tiles disappearing prematurely from the viewport or anything like that.

The major issue so far is getting mouse/touch interactions to take the device's pixel density into account. Everything still works fine on desktop screens at normal pixel density, but devices with higher pixel densities are off. For example, pinching to zoom on an iPad Mini 2 (pixel density ratio of 2) in the bottom-right corner of the screen will set the center of the zoom to be the middle of the canvas, instead of the bottom-right corner like I'd expect.

There's also a weird issue where the viewport will no longer default to fitting images inside the available space, but I'm not sure if that's due to my code, other changes to the collections branch, or possibly even a misconfiguration on my part.

**Comment by iangilman** [comment]
Fixed by #583

**Comment by boskar** [comment]
Is it really fixed?
I've got a problem here: After installing new monitor chrome/firefox(iceweasel) differ. Chrome zooms more (imho without preserving mixPixelRatio). Canvas are on. 
On the other hand - in chrome everything is bigger anyway. 

Maybe I don't understand css pixels well enough, but it still looks like an issue.

My settings:

        blendTime: 0.1,
        constrainDuringPan: true,
        maxZoomPixelRatio: 1,
        minPixelRatio: 1,
        minZoomLevel: 1,
        visibilityRatio: 1,
        zoomPerScroll: 2,

**Comment by iangilman** [comment]
@boskar Have you verified that neither of the browsers are set to zoom in or out? For instance, on Firefox, go to View > Zoom > Reset. 

It would be interesting to know what OSD thinks the pixel densities of the two browsers are. On each, just call `OpenSeadragon.pixelDensityRatio()`. You can also take a look at its code to see what it's doing: 

https://github.com/openseadragon/openseadragon/blob/master/src/openseadragon.js#L847

**Comment by boskar** [comment]
Iceweasel:
OpenSeadragon.pixelDensityRatio
1


Chrome: 
OpenSeadragon.pixelDensityRatio
1.2000000476837158

**Comment by iangilman** [comment]
Interesting; it looks like Chrome has determined that your 117dpi monitor counts as HDPI and is giving you a `window.devicePixelRatio` greater than 1. It's also compensating with all of the text sizes. 

I suppose it can be argued whether Chrome is making the right choice here, but given that Chrome has gone that way, it seems OSD is doing the right thing.
