### ISSUE TITLE
Allow XHR's withCredentials for authenticated requests

### ISSUE THREAD

**Issue by azaroth42** [openseadragon/openseadragon#543]
_Use Case:_  
Images and JSON or XML technical descriptions may require authentication to read, such as basic auth or cookies.  Without authentication, the response may be degraded or simply not permitted (403)

_Current Situation:_
AjaxRequests from OSD do not have the withCredentials flag set, and hence do not pass through credentials.

_Solution:_
To implement across the board, add to makeAjaxRequest in openseadragon.js:
```javascript
            request.withCredentials = true;
```
But would probably be better to have a setting on the viewer that triggers the addition, rather than doing it always in case it's needed. (I guess it hasn't been yet!)

_Test Case:_

http://dlss-dev-azaroth.stanford.edu/services/iiif/f1rc/info.json will redirect to a degraded form with a link to an authentication service (that uses Google OAuth).  Once authenticated, re-requesting the tilesource info will get the full image if the credentials (a cookie) are successfully being sent.

**Comment by iangilman** [comment]
@azaroth42 yeah, was kind of convoluted! I'm happy with the result, though. Please give it a try (#553) and let me know if it works. Then I can merge.

**Comment by iangilman** [comment]
@azaroth42 ping! Are you still interested in this? Please take a look at #553 and give it a try.

**Comment by azaroth42** [comment]
Sorry, yes, still essential let alone just interested! Haven't had a chance
to test, apologies for that.  Will try and get it set up on my development
server and report by COB tomorrow.  Thanks!

**Comment by azaroth42** [comment]
Now using the ajax branch on the demo above and works perfectly. Thanks for the work Ian!  +1 from me for merging up.

**Comment by iangilman** [comment]
Excellent. Merged!
