### ISSUE TITLE
thanks, and demo of a neat project

### ISSUE THREAD

**Issue by jrochkind** [openseadragon/openseadragon#546]
Not really an issue, I just wanted to share with you openseadragon devs a project that was just released, that I think is really neat, based on openseadragon. 

http://beehivecollective.org/posterViewer/?poster=mr

It's an online viewer, with a tour, of an enormous poster (a 10-year project by a collection of artists) illustrating capitalism/globalization and resistance in Central America, via metaphorical scenes of wildlife. I think it turned out really well. 

OpenSeadragon is of course doing the heavy lifting here, the project would not have been possible without it. In general, OSD was pretty delightful to work with, it's solid, well-organized, flexible code. Thanks very much for sharing your code! 

If anyone is curious about some of the problems I did run into (including some I still haven't quite solved to my satisfaction), I'd be happy to share (and will probably do so eventually in other tickets where I ask for advice eventually :) ). 

All the code for this project is open source and available at https://github.com/jrochkind/beehive_poster_viewer.  (The JS is pretty messy and poorly organized, I'm a bit embaressed, but sharing it anyway. :) I don't mainly work in JS in my day job, and realized I lacked the understanding of how to keep JS well organized, heh).

**Comment by jrochkind** [comment]
@iangilman if you're curious to see the UI -- I added a feature where when you pan/zoom around the canvas on your own, the narrative text box will automatically update to describe the scene that your current viewport comes closest to matching. Works pretty well, no need for any clicks (since click still zooms).

**Comment by iangilman** [comment]
Beautiful...that's a great solution. I could get lost in that image for hours!

**Comment by jrochkind** [comment]
Thanks! Yeah, I've spent hours lost in it myself, I think the OSD-based viewer is a really great presentation of it!
