### ISSUE TITLE
Custom TileSource is not working properly to load initial level image.

### ISSUE THREAD

**Issue by dotnetexpert86** [openseadragon/openseadragon#547]
Hello,

I am trying to make custom tile source, I have simple copy paste the code from here : https://openseadragon.github.io/examples/tilesource-custom/ 
But i can see the Output as per here : http://screencast.com/t/j7Qvh4URsX

and for the Images related output here.. http://screencast.com/t/nPSGdRRbkn

Here questions are :
----------------------------------------- 
1) what is the correct way to load images properly..i cant see there are much documentation for it. if any specific info please provide me..

2) why there is (level-8)... ?

3) How can i make it dynamic.. for example if i  want to make load images from my PC related folders dynamically with ajax call using asp.net mvc.. is there any examples...

4) I have much read about but not exact info for custom tile source to load the images to show the output as on Demo page...

I am using below code currently, it will go later based on ajax call to load local folders - level0,1,2,3,4,5,6 etc

        var viewer = OpenSeadragon({
            id: "example-custom-tilesource", showNavigator: true,
            wrapHorizontal: true,
            tileSources:   {
                height: 512*256,
                width:  512*256,
                tileSize: 256,
                minLevel: 8,
                getTileUrl: function (level, x, y)
                {
                    console.log("URL::->"+ "http://s3.amazonaws.com/com.modestmaps.bluemarble/" +(level-8) + "-r" + x + "-c" + y + ".jpg")
                    return "http://s3.amazonaws.com/com.modestmaps.bluemarble/" +
                            (level-8) + "-r" + x + "-c" + y + ".jpg";

                }
            }
        });

**Comment by dotnetexpert86** [comment]
@msalsbery : No, it is not working as with giving proper image from server sider... I have added break point in action of controller :  public string image(int level, int x, int y), but showing wrong level values, thats why not showing the div fill with images....

I have added as per you have said..tested code with both cased on substracting -8 and without substracting

       public string image(int level, int x, int y)
        {
            return "http://s3.amazonaws.com/com.modestmaps.bluemarble/"+level + "-r" + x + "-c" + y + ".jpg";
        }
'''javascript
       getTileUrl: function (level, x, y)
        {
                    return root + 'DeepZoom/image?level=' + level + '&x=' + y + '&y=' + x + '';
        }
    ```

**Comment by dotnetexpert86** [comment]
Later i would like to read the images from the different levels of directories : with making server call / ajax call.

**Comment by dotnetexpert86** [comment]
Another try with following : here main concern is that getTileUrl passing wrong level... according to me in comparision with console.log in JS

  public FileResult image(int level, int x, int y)
        {

            //string ImageName = (level - 8) + "-r" + x + "-c" + y;
            //return "http://s3.amazonaws.com/com.modestmaps.bluemarble/"+level + "-r" + x + "-c" + y + ".jpg";

            //var ImageName = Directory.GetFiles(Server.MapPath("~/Images/customtilesource/level" + level + "/"+ImagePattern), "*.jpg").Select(Path.GetFileName);

            var image = GetImageFromUrl("http://s3.amazonaws.com/com.modestmaps.bluemarble/" + level + "-r" + x + "-c" + y + ".jpg");
            var bitmap = image as Bitmap;

            return new FilePathResult(bitmap.ToString(), "jpg");
            
        }

       public static Image GetImageFromUrl(string url)
        {
            HttpWebRequest httpWebRequest = (HttpWebRequest)HttpWebRequest.Create(url);

            using (HttpWebResponse httpWebReponse = (HttpWebResponse)httpWebRequest.GetResponse())
            {
                using (Stream stream = httpWebReponse.GetResponseStream())
                {
                    return Image.FromStream(stream);
                }
            }
        }

**Comment by dotnetexpert86** [comment]
Hello, Please check previous messages + i can see that at the last time server call made from getTileURL, i can see client side with level - 10, 9, 8 ... in debugger... but when the level value is 8 then only the server call made that means during level 10 and level 9 there is not action of controller is called..

**Comment by dotnetexpert86** [comment]
It seems server side function not call one by one....level ....!!!

**Comment by msalsbery** [comment]
Sorry, since I have no knowledge of the image you're working with I can't give precise code examples. It's your tile source and your image so you'll have to code the getTileUrl and server controller correctly :)

Why not use the 1000x1000 OpenSeadragon sample image to start? It's a simple DZI image with all levels.

**Comment by dotnetexpert86** [comment]
I just want to load this URL from the server controller : http://s3.amazonaws.com/com.modestmaps.bluemarble/" + Math.max(0, level - 8) + "-r" + y + "-c" + x + ".jpg but still not loading levels properly.... it make the call at last not one by one...

**Comment by dotnetexpert86** [comment]
I am still want to load the image which are mentioned in Custom Tiles for Openseadragon but want to load from server call...

**Comment by msalsbery** [comment]
In that case you should use the client getTileUrl code as-is (except for your server URL) since that works, then you can work on getting the server side working. 

All tile requests are asynchronous HTTP requests so there's no guarantee what order they'll arrive at your server. The server just needs to return the requested tile image.

**Comment by msalsbery** [comment]
What do you mean by " it is not calling one by one"?

**Comment by dotnetexpert86** [comment]
1) is it possible to load tiles / imagename from the database ///// server call?

2) What do you mean by " it is not calling one by one"?
[Comment] : 
when there is level = 2 on clients side it needs to call server call but not calling server function 
where there is level = 1 on clients side it needs to call server call but not calling server function 
where there is level = 0 on clients side then at last time it calls server function.... not call server function during the level = 2,

3) All tile requests are asynchronous HTTP requests so there's no guarantee what order they'll arrive at your server. The server just needs to return the requested tile image.
[Comments] : here first main concern about that when the server call ----> level values not showing properly order i mean  if level = 2 then the call is not made, at last level =0 or 1 then call made for the custom tiles for the openseadragon.

**Comment by dotnetexpert86** [comment]
I can't see any examples which are related to server call, even with Google Map getTileURL...

**Comment by dotnetexpert86** [comment]
All tile requests are asynchronous HTTP requests so there's no guarantee what order they'll arrive at your server. The server just needs to return the requested tile image.
[Comment]: I can see different order on server with adding debug point, I mean if there is level = 2 from client side, on server debug, I can see level = 1...!!!

**Comment by msalsbery** [comment]
>I can see different order on server with adding debug point, I mean if there is level = 2 from client side, on server debug, I can see level = 1

How do you guarantee you're looking at the same request on the server after seeing it on the client? :) You can't reliably do that - the client doesn't necessarily make the request immediately after asking for a tile URL...maybe it does but you can't rely on that.

**Comment by msalsbery** [comment]
If you want to synchronize debugging on client and server then you'll need a breakpoint at the tile request on the client, not in getTileUrl

**Comment by dotnetexpert86** [comment]
Ok, BUT there is not returning proper level related image if i do with server call from getTileURL

**Comment by msalsbery** [comment]
You can't do server calls from getTileUrl. That function MUST only immediately return a string containing the URL for the tile image (x,y,level)

**Comment by msalsbery** [comment]
OpenSeadragon makes the server requests, not getTileUrl

**Comment by dotnetexpert86** [comment]
Ok, If i want to load the Images / tiles from my folders and database how i can make the server call... It is clear now the from getTitleURL i can returning URL of the image with using the data from the server ....

**Comment by dotnetexpert86** [comment]
I got that, getTileURL is for only returning ImageURL, not make server call, if i want to load images from folders / database how could i ?

**Comment by msalsbery** [comment]
You don't have to make the call on the client side - OpenSeadragon will request tiles using the URLs you provide. All you have to do is the server side - return tile images in JPEG or PNG format. How you do that is up to you...I've done many tile servers that extract tiles on-the-fly from single images, or simply returning existing tile images from a database or the file system. You can even draw new tile images on the server and return them :)

**Comment by dotnetexpert86** [comment]
That i can't  see working.

 public FileResult image(int level, int x, int y)
        {

            return new FilePathResult("http://s3.amazonaws.com/com.modestmaps.bluemarble/" + level + "-r" + x + "-c" + y + ".jpg", "jpg");
            
        }

**Comment by dotnetexpert86** [comment]
Here issue is level values if you put break points, you will get what i was trying to say....

**Comment by msalsbery** [comment]
That's way outside the scope of OpenSeadragon ;) but at a glance I don't think that will work for two reasons:

1) I'm not familiar with FilePathResult...does it allow server request URLs like that?
2) The content type should be "image/jpeg"

**Comment by msalsbery** [comment]
Can you please post the current code you're trying, both the client (tile source) and the server side?

**Comment by dotnetexpert86** [comment]
Here this is not any case for FilePathResult...

Here big concern about level values... which are wrong.. you can try with string type function.. i have tried with "image/jpeg" but if you take a look at the below 2 screenshots i think you get idea what i was trying to say... forget temporary to return the URL / image / datatype - Filepathresult / string

http://screencast.com/t/1BkisjKm7c
http://screencast.com/t/okhxYHSnu

**Comment by dotnetexpert86** [comment]
```javascript
function Init()
    {

        var viewer = OpenSeadragon({
            id: "example-custom-tilesource",
            //debugMode: true,
            navigatorSizeRatio: 0.25,
            wrapHorizontal: true,
            showNavigator: true,
            tileSources: {
                height: 512 * 256,
                width: 512 * 256,
                tileSize: 256,
                //minLevel: 8,
                //getTileUrl: chronicling_america_example()
                getTileUrl: function (level, x, y)
                {
                    return root + 'DeepZoom/image?level=' + Math.max(0, level - 8) + '&x=' + y + '&y=' + x + '';
                }
            }
        });

    }
    OpenSeadragon.addEvent(window, "load", Init);

server side
-------------------

        public FileResult image(int level, int x, int y)
        {

            return new FilePathResult("http://s3.amazonaws.com/com.modestmaps.bluemarble/" + level + "-r" + x + "-c" + y + ".jpg", "jpg");
            
        }

**Comment by iangilman** [comment]
http://screencast.com/t/okhxYHSnu shows that OpenSeadragon is asking for the tiles with the correct levels. http://screencast.com/t/1BkisjKm7c shows that your FileResult's level argument is 0, which is one of the correct levels. Do you also see levels 1 and 2? 

At any rate, OpenSeadragon appears to be doing the right thing, so somehow something is going wrong in your server-side component (which includes FileResult). @msalsbery and I are not going to be able to help you debug your server-side component, as it's outside of our scope of knowledge and has nothing to do with OpenSeadragon. You just need to make sure that the arguments that are coming in from the URL are making it properly into your function.

**Comment by msalsbery** [comment]
I don't see anything wrong in the screenshots except your server isn't returning images =

**Comment by dotnetexpert86** [comment]
@iangilman  : No, I can not see levels = 1 and 2 values.. that i want to say, the getTileURL does not pass the level = 1 , and 2 related values..

I know filepathrestul is outside of your scope thats why i have made this screenshot : http://screencast.com/t/1BkisjKm7c it does not showing the proper values... like lelvel = 2 and 1, it direct calls with level = 0....

**Comment by dotnetexpert86** [comment]
I don't see anything wrong in the screenshots except your server isn't returning images =

it never shows the level = 2 , http://screencast.com/t/1BkisjKm7c ;)

**Comment by dotnetexpert86** [comment]
You can try with simple server call, String as an DataType of fnction... and retrun PNG / JPEG images as well, here main issue is level related values... it shows only level = 0 and level = 1 only ... Never seen level = 2, since last many hours... ;)

**Comment by dotnetexpert86** [comment]
Can you please compare level related orders + x and y coords orders in both screen shot (one is for console.log and second for server call related in console): http://screencast.com/t/w2X1dzjLfSh9 and http://screencast.com/t/okhxYHSnu

**Comment by msalsbery** [comment]
@dotnetexpert86 Thanks for posting the code!

Ok, first you can put the client side back to the original since you're using the demo code from the first post. Forget about removing the "- 8" thing for now:
```javascript
    tileSources:   {
        height: 512*256,
        width:  512*256,
        tileSize: 256,
        minLevel: 8,
        getTileUrl: function( level, x, y ){
             return root + 'DeepZoom/image?level=' + (level - 8) + '&x=' + x + '&y=' + y + '';
        }
    }
```
Now you should get x, y, and level values at the server that can be passed directly to the s3.amazonaws.com server:
```
"http://s3.amazonaws.com/com.modestmaps.bluemarble/" +
                    level + "-r" + y + "-c" + x + ".jpg";
```
Note the 8 was subtracted on the client so don't do it again on the server!

Your next issue is downloading the image from s3.amazonaws.com and returning it from your server. FilePathResult isn't going to do that for you I don't think - that requires calling the server with the above URL, waiting for the response (image) and sending that image from your server.

Instead, before going through all that, try putting a 256x256 jpeg image on your harddrive. Then do something like this on your server:
```csharp
        public FileResult image(int level, int x, int y)
        {

            return new FilePathResult("c:\\pathtomy256x256image\\myimage.jpg", "image/jpeg");

        }
```
You should now see that same image used for all tiles when displayed on the client, with no errors on the client or the server.

**Comment by msalsbery** [comment]
>Can you please compare level related orders + x and y coords orders 
Can't do that - there's nothing that says the requests will get handled by the server in the same order OpenSeadragon requests URLs for tiles or the order the requests are made. HTTP requests don't work that way :)

**Comment by dotnetexpert86** [comment]
this way i can see the image in Openseadragon : of the 0 level, if i want to use level, x , y values from client side to server, then causes the issue might be : return new FilePathResult("D:\\0-r0-c0.jpg", "image/jpeg"); 

over there you can see proper levels related images, here main concern about the orders of the level according to me ...

**Comment by dotnetexpert86** [comment]
please change over there this line : return root + 'DeepZoom/image?level=' + (level - 8) + '&x=' + x + '&y=' + y + ''; to return root + 'DeepZoom/image?level=' + (level - 8) + '&x=' + y + '&y=' + x + ''; as per updated documentation ....

**Comment by msalsbery** [comment]
That's fine - my point was to return to the original sample code so there's no client-side issues. Any issues should be on the server side.

**Comment by dotnetexpert86** [comment]
The issues on server side, but the levels related values passing from the client side... !!! ;)

**Comment by msalsbery** [comment]
All the current OpenSeadragon tile sources work fine, as does the example custom tile source you're trying to use in your original post above. I'm not sure what you're expecting to see but your screenshots show normal tile requests.

**Comment by dotnetexpert86** [comment]
to return the tiles for the levels are not working properly, you can check over there, or if you have made  before how to read files / or pass images  from server, can you please share..

well, the level which are passing from client to server does not make the proper output for the customtilesource demo... it showing nothing to seadragon div.

**Comment by dotnetexpert86** [comment]
Screenshots showing normal tilerequests, but when you return the JPG image with dynamic levels you can see the issue... according to me the levels values passing are wrong from client to server... please correct me if i am wrong..

**Comment by msalsbery** [comment]
I'm not sure why you're trying to use a complicated image from a third party server. The most basic custom tile source with a custom tile server would look something like this...
client:
```javascript
    tileSources:   {
        height: 512*256,
        width:  512*256,
        tileSize: 256,
        getTileUrl: function( level, x, y ){
             return root + 'DeepZoom/image?level=' + level.toString(10) + '&x=' + x.toString(10) + '&y=' + y.toString(10);
        }
    }
```
server:
```javascript
        public FileResult image(int level, int x, int y)
        {

            return new FilePathResult("c:\\pathtomy256x256image\\myimage.jpg", "image/jpeg");

        }
```
That should work with zero issues. Then you can work from there...

**Comment by dotnetexpert86** [comment]
well, if you use .. level, x, y related thing in  return new FilePathResult("c:\\pathtomy256x256image\\myimage.jpg", "image/jpeg"); if levels are dynamically passed then i must use the level, x, y in returning the images.

**Comment by msalsbery** [comment]
>but when you return the JPG image with dynamic levels you can see the issue... according to me the levels values passing are wrong from client to server... please correct me if i am wrong..

Perhaps, but I haven't seen any screenshots showing that, and if there is an issue it's not in OpenSeadragon. The issue has to be in the URL returned by your custom tile source getTileUrl. That's why I keep recommending starting with the simplest tile source and working from there.

**Comment by dotnetexpert86** [comment]
You are returning static image thats why you can not see the issue, if you try to use level,x, y in returning image you can see the issue...

**Comment by dotnetexpert86** [comment]
I am returning URL only which are in customtile for openseadragon, different is that i want to return from server side with using level, x, y. and getTileURL is not sending proper level value according to me as there is not any image i can see in the openseadragon div.

**Comment by msalsbery** [comment]
> if you use .. level, x, y related thing in return new FilePathResult("c:\pathtomy256x256image\myimage.jpg", "image/jpeg"); if levels are dynamically passed then i must use the level, x, y in returning the images.

Correct, and it's working fine on the demo page at https://openseadragon.github.io/examples/tilesource-custom/ . If you intend to use that image in your tile server then your tile server will need to pass level,x,y directly in a request to the Amazon server using URL I showed above, wait for the response image, then return that image in a response to your client.

**Comment by msalsbery** [comment]
You haven't shown a working server yet. FilePathResult("http://s3.amazonaws.com/com.modestmaps.blue...  is not going to work. It has nothing to do with levels. You're not retuning images from your server.

**Comment by dotnetexpert86** [comment]
so i can not use like here : return new FilePathResult("http://s3.amazonaws.com/com.modestmaps.bluemarble/" + level + "-r" + x + "-c" + y + ".jpg", "image/jpeg");?

i need to make request to Amazon server from the function which is in server?

**Comment by msalsbery** [comment]
Yes. That's a URL to an Amazon server, not a file path

**Comment by dotnetexpert86** [comment]
Ok, I have just made the script to read the files from the server and added all the images in to my directory, now i have returned the image path not the URL... :) it is working fine...:)

Actually the in the documentation the server call is different ... i was returning the image url instead of path... what was happened with me...!!!

Thanks for your time and explanation....

**Comment by msalsbery** [comment]
Ohhh haha Glad you got it :)

**Comment by dotnetexpert86** [comment]
:+1:

**Comment by dotnetexpert86** [comment]
The custom Tiles for the openseadragon is call for server to get the images / tiles from database / direcotries....

From the server side, always return the file path with the image / tile name .. do not return the URL.

```javascript
function Init()
    {
        var viewer = OpenSeadragon({
            id: "example-custom-tilesource",
            //debugMode: true,
            navigatorSizeRatio: 0.25,
            wrapHorizontal: true,
            showNavigator: true,

            tileSources: {
                height: 512 * 256,
                width: 512 * 256,
                tileSize: 256,
                //minLevel: 8,
                //getTileUrl: chronicling_america_example()
                getTileUrl: function (level, x, y)
                {
                    return root + 'DeepZoom/image?level=' + Math.max(0, level - 8) + '&x=' + y + '&y=' + x + '';

                }
            }
        });

    }
    OpenSeadragon.addEvent(window, "load", Init);

Server sode
====================
public FileResult image(int level, int x, int y)
        {

            return new FilePathResult(Server.MapPath("~/Images/customtilesource/level" + (level) + "/" + level + "-r" + x + "-c" + y + ".jpg"), "image/jpeg");
            
        }

**Comment by msalsbery** [comment]
That looks better ;)

**Comment by dotnetexpert86** [comment]
I am trying to get the coordinates with below code : 
```javascript
viewer.addHandler('canvas-click', function (target, info) {
            var viewportPoint = viewer.viewport.pointFromPixel(info.position);
            var imagePoint = viewer.viewport.viewportToImageCoordinates(viewportPoint.x, viewportPoint.y);
            console.log(imagePoint.x, imagePoint.y);
        });

If i am clicking on the canvas click to grab the X and Y position : showing me  console error :  Uncaught TypeError: Cannot read property 'position' of undefined

**Comment by dotnetexpert86** [comment]
This way, I can remove the canvas-click related - position of undefined error : https://github.com/openseadragon/openseadragon/issues/318

For the Openseadragon (1.0.0), please updated the code as per below.
```javascript
viewer.addHandler('canvas-click', function (event)
        {
            console.log(event);
            var viewportPoint = viewer.viewport.pointFromPixel(event.position);
            var imagePoint = viewer.viewport.viewportToImageCoordinates(viewportPoint.x, viewportPoint.y);
            console.log(imagePoint.x, imagePoint.y);
        });

**Comment by dotnetexpert86** [comment]
Hello, Can you please check th

it is x and y coordinates with pixels for the canvas of X and Y : console.log("X:" + viewportPoint.x, "Y:" + viewportPoint.y); 

It is making Latitude and Longitude ? -->  console.log(imagePoint.x, imagePoint.y); 

What exact viewportToImageCoordinates is doing, i am assuming it is making Lat / Long, please correct me, if i am wrong..

**Comment by msalsbery** [comment]
viewport coordinates are 0.0 to 1.0 relative to the image's native dimensions. I believe image coordinates are pixel coordinates relative to the image's native dimensions. Is that what you're seeing?

**Comment by dotnetexpert86** [comment]
hmm.. actually i want to know that, about what is the use for ViewportCoordinates and ViewPortToImageCoordinates?

See : http://screencast.com/t/oLInfLwP , i have made console.log for 1) X and Y position 2) ViewPort x and y coordinates 3) Image Coordinates for x and y...

Question was what is the use for ViewPort and Image related coords ?  Both have the X , Y values like Lat / Long...?

**Comment by msalsbery** [comment]
> There is no lat/Lon in OpenSeadragon.

The uses are for the user to decide. Internally 0.0 to 1.0 coordinates are used. In image analysis or perhaps css/elements pixel coordinates are needed. That's the purpose of the conversion functions.

If you need lat/lon you'll need to calculate those yourself.=

**Comment by dotnetexpert86** [comment]
ok,

**Comment by dotnetexpert86** [comment]
https://openseadragon.github.io/docs/OpenSeadragon.Drawer.html using it i can add icons / marker image and display them at the certain zoom levels?

**Comment by msalsbery** [comment]
You should use the Viewer class. Drawer is used internally and generally never needs to be used directly.=
