### ISSUE TITLE
how to dynamically generate/create dzi on every image added to the folder, or in every 24 hrs.

### ISSUE THREAD

**Issue by naldjb** [openseadragon/openseadragon#554]
Hi everyone, i a newbie here and i only got here due to this project that its main function is to get users profile pic from social media like fb and twitter when they share our post or website and then with all the images we have gathered we will generate it as a dzi.. i have tried using silverlight dzi composer but its a manual build, what we need is to compose dzi image dynamically. I'm not really sure where to start and what things is needed. can anybody tell me the server type and requirements to dynamically build dzi image and is it possible?

i have found http://www.codeproject.com/Articles/33146/Silverlight-Database-Deep-Zoom however i am getting a error on cn.Open();  

error msg "System.NullReferebceException"

private DzDbAccess GetAccessDb()
        {
            // Read connection string from the property settings and open the database
            string connectString = Settings.Default.ConnectionString;
            var cn = new OleDbConnection(connectString);
            cn.Open();

            // Create the MS Access database object and pass it the connection object.
            var accessPersistence = new DzDbAccess();
            accessPersistence.DbConnection = cn;
            return accessPersistence;
        }

it would really be a life saver if somebody can share me theyre code that creates dynamic dzi, if there is one..

**Comment by msalsbery** [comment]
Here's our reference for image creation...

http://openseadragon.github.io/examples/creating-zooming-images/

**Comment by iangilman** [comment]
Sounds like you're taking all of the profile pics and combining them into a single large DZI? Generally you would do this in two steps... first, combine the images into a regular JPG, PNG, etc., and then use one of the tools listed on the link @msalsbery gave to convert into DZI.
