### ISSUE TITLE
Preserve Overlay after viewer.open()

### ISSUE THREAD

**Issue by ShadOoW** [openseadragon/openseadragon#557]
Hello again!

I was wondering if there is a way to preserve the overlays after calling viewer.open a second time.
something that could work similar to viewer.preserveViewport but for overlays.

Right now I have to manually reinsert the overlays in the open event.

the insertion code: this.viewer.addOverlay(overlay, point, placement);

**Comment by iangilman** [comment]
There is not at this time. We could add a `preserveOverlays` option. It might be as simple as just not clearing the overlays in Viewer.close: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L542

**Comment by ShadOoW** [comment]
Please check this changes and let me know if you think I may have broken something (loadOverlays( _this ); maybe?), It seem to be working all right for now.

function openTileSource( viewer, source ) {
...
    if( _this.preserveOverlays ){
        _this.source.overlays = _this.currentOverlays;
    }
    else
    {
        _this.source.overlays = _this.source.overlays || [];
    }
...
}
close: function ( ) {
...
    if( ! this.preserveOverlays)
    {
       this.clearOverlays();
       this.overlaysContainer.innerHTML = "";
    }
...
}

Thanks you very much!

**Comment by ShadOoW** [comment]
Please check this changes and let me know if you think I may have broken something (loadOverlays( _this ); maybe?), It seem to be working all right for now.

function openTileSource( viewer, source ) {
...
    if( _this.preserveOverlays ){
        _this.source.overlays = _this.currentOverlays;
    }
    else
    {
        _this.source.overlays = _this.source.overlays || [];
    }
...
}
close: function ( ) {
...
    if( ! this.preserveOverlays)
    {
       this.clearOverlays();
       this.overlaysContainer.innerHTML = "";
    }
...
}

Thanks you very much!

**Comment by iangilman** [comment]
That looks like the general idea. On the "open" side, what happens if you don't do `_this.source.overlays = _this.currentOverlays`? Since you didn't delete them during close, maybe they're still there? We don't want to add them a second time if they already exist.

Would you be up for making a pull request out of this?

**Comment by ShadOoW** [comment]
Yo,

Without _this.source.overlays = _this.currentOverlays the Overlays panning will get stuck and will no longer move with the viewport.

Yes, i will make a pull request in few hours.

**Comment by ShadOoW** [comment]
Pull request added, go easy on me it my first time :p
