### ISSUE TITLE
MouseTracker should start with tracking on

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#558]
Currently the MouseTracker doesn't do anything until you call `setTracking(true)` on it. This is a poor default behavior.

**Comment by msalsbery** [comment]
:+1:

**Comment by msalsbery** [comment]
I'll wait a bit in case there's any strong objections to this change...

**Comment by msalsbery** [comment]
@iangilman 

I don't think anyone's going to notice this change.

We do have at least one place in OpenSeadragon that can defer tracking, so I'll make the default on but add then look for a startDisabled flag in the creation options.

Sound ok?

**Comment by iangilman** [comment]
Sounds great :-)

**Comment by msalsbery** [comment]
Fixed by #576
