### ISSUE TITLE
How to load only tiles of image piece shown in viewport

### ISSUE THREAD

**Issue by osk386** [openseadragon/openseadragon#560]
Hi, 

I am trying to load a big collection of deepzoom images disposed vertically, each image has 11000 pixels of heigth and 1100 pixels of width. There is no problem with this, the problem comes when I make zoom, all tile images from collection tile are loaded, so it takes too much time to render, even loading just one image.

I've been testing with two modes (normal dzi and collection) with just one image. When a simple dzi is loaded, tile images at the zoom level are loaded only at the zoom area shown. But when load the same image in collection mode, all tiles of zoom level are loaded, causing delay to render (tested with chrome debugger).

This is the way how viewer are loaded:

    var testSource = [];
    var numberOfImages = 1;
    var nameOfFile = "pozo100/720c.dzi";

    for (var i = 0; i < numberOfImages; i++) {
        testSource.push(nameOfFile)
    }

    var viewer = OpenSeadragon({
        id: "openseadragon1",
        prefixUrl: "images/",
        tileSources: testSource,
        collectionMode: true,
        collectionRows: 1,
        collectionTileSize: 8096,
        collectionTileMargin: -1,
        collectionLayout: 'vertical',
        imageLoaderLimit: 20,
        maxImageCacheCount: 200,
        timeout: 30000,
        useCanvas: false,
        showZoomControl: false,
        showHomeControl: false,
        showFullPageControl: false
    });
    
I've been searching for any solution to this but no success. I've tested the openseadragon collection branch git, but still with this issue. I appreciate your help.

**Comment by iangilman** [comment]
You should definitely use the "collections" branch (#446) for this. Odd that you're seeing the issue even there. This demo is very similar to your scenario:

http://iangilman.com/osd/test/demo/item-animation.html

...and it doesn't have the issue you describe (as far as I know). 

Could you share a demo that shows the issue (using the collections branch) or point out how my demo has that issue?

**Comment by osk386** [comment]
Thanks a lot!, your demo fits to my needs and solve my problem.

I see that old concept of collection in OSD were no necesary.


Thank you again.

**Comment by iangilman** [comment]
Glad to hear it!
