### ISSUE TITLE
Arrow keys don't work in Chrome/Safari

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#565]
...as stated here:

https://openseadragon.github.io/examples/ui-keyboard-navigation/

The thing is, arrow keys do work in other webapps, so what's special about OpenSeadragon? Is it the fact that we're using a `textarea` rather than a regular div? Why are we doing that? Is there some other way to get that effect without compromising the arrow keys?

**Comment by msalsbery** [comment]
Haven't looked yet, but may just be the event we're using (keypress vs keydown/keyup).

A quick Bing search tells me it should work everywhere these days.

Assigning to me...

**Comment by iangilman** [comment]
fixed by #568
