### ISSUE TITLE
Check for MSPointerEvent is not sufficient

### ISSUE THREAD

**Issue by ckuetbach** [openseadragon/openseadragon#571]
There is following code within openseadragon, to check for MSPointerEvent-Capabilities:

mousetracker.js: 

    } else if ( window.MSPointerEvent ) {

This code will work in most, but not all cases. We use an embedded webBrowsercontrol in a C# application. MouseEvents wasn't working, so I searched for the problem:

There are combinations, where the browser is capable of these Events, but they aren't activated (like our embedded browser). In this case

`window.MSPointerEvent` returns an object (truthy)

MS decided to create a flag to lookup for these events. 

`window.navigator.msPointerEnabled` returns false (in our case or true, if really enabled)

Please check for `window.MSPointerEvent && window.navigator.msPointerEnabled` instead. This is mentioned as best way to check for the new feature at MSDN:

http://msdn.microsoft.com/en-us/library/ie/hh673557(v=vs.85).aspx

I am not sure, if there are other situations, where this bug may appear, but the complete viewer with all click and mouse events is not working at all

The same problem seems to exist in version 1.1.1 and 1.2

**Comment by msalsbery** [comment]
Excellent, thank you for reporting!

Never ceases to amaze me how MS doesn't read their own docs. I'm pretty sure I used their sample code for the capabilities check :)=

**Comment by msalsbery** [comment]
I'll fix this one right away. Maybe I can get it in the 1.2.1 build!

**Comment by msalsbery** [comment]
Fixed by #574

**Comment by ckuetbach** [comment]
Ohh, I just encountered, that there is also an navigator.pointerenabled

;(

I think I now, know, why my embedded IE webbrowser only works in IE10 mode.

Tomorrow at work, I will check, if there would also be a need to check for window.PointerEvent && (window.pointerEnabled "or not IE") 

If you dislike IE, just think I need an embedded control of this thing, which has different behavior and other UserAgent and navigator.appname

**Comment by ckuetbach** [comment]
I checked the condition for IE11:

    if ( window.PointerEvent && (window.navigator.pointerEnabled  ||  $.Browser.vendor !== $.BROWSERS.IE  ) ) {

I think MS will not remove the pointerEnabled flag in IE11

**Comment by msalsbery** [comment]
I like, I'll add it to the pull request

**Comment by msalsbery** [comment]
@ckuetbach  Added your IE 11 check to #574
