### ISSUE TITLE
Disable navigation on the navigator

### ISSUE THREAD

**Issue by rleonard04** [openseadragon/openseadragon#572]
I need to temporarily disable navigation on the navigator. From the documentation I have read that I can invoke 'setMouseNavEnabled(enabled)' on the navigator class. This method works as expected for the viewer but not it's navigator. Inspecting the navigator does show that 'mouseNavEnabled' is false however I am still able to navigate via the navigator.

**Comment by msalsbery** [comment]
Thanks for reporting. Will get that fixed right away.

**Comment by rleonard04** [comment]
After looking at the navigator object I found that currently the navigator can be disabled by:
viewer.navigator.element.innerTracker.setTracking(false);

and likewise it can be re-enabled by:
viewer.navigator.element.innerTracker.setTracking(true);

Cheers!

**Comment by msalsbery** [comment]
Fixed by #575

**Comment by msalsbery** [comment]
@rleonard04  
This should work with the new patch:
```javascript
viewer.navigator.setMouseNavEnabled(enabled)
```
