### ISSUE TITLE
navigate a predefined path

### ISSUE THREAD

**Issue by sharmaashish** [openseadragon/openseadragon#578]
Is it possible to configure the viewer so that it moves along a predefined path that takes a user to specific points of interest? My use case is one where I would like to override the mouse-scroll to move along this predefined path?

**Comment by msalsbery** [comment]
One way is to use the [OpenSeadragonViewerInputHook plugin](https://github.com/msalsbery/OpenSeadragonViewerInputHook). Then you can override a viewer's default handling of touch, mouse (and possibly keyboard) input, something like:
```javascript
    var viewer = OpenSeadragon({...});

    viewer.addViewerInputHook({hooks: [
        {tracker: 'viewer', handler: 'dragHandler', hookHandler: onViewerDrag},
        {tracker: 'viewer', handler: 'dragEndHandler', hookHandler: onViewerDragEnd}
    ]});

    function onViewerDrag(event) {
        // Do your own custom drag handling here...

        event.preventDefaultAction = true;
    }

    function onViewerDragEnd(event) {
        event.preventDefaultAction = true;
    }
```

**Comment by iangilman** [comment]
There's no mechanism in OpenSeadragon to define such a path, but if you have a path, you can move the viewport wherever you want via `panTo(point, true)` and `zoomTo(zoom, null, true)`.

**Comment by sharmaashish** [comment]
Thanks. I think panTo might do the trick.

**Comment by boskar** [comment]
That's how I did it, with jquery json polling. 
fitBounds might be an option too.
