### ISSUE TITLE
Custom Mouse Scrolling on Viewer

### ISSUE THREAD

**Issue by gkdagk** [openseadragon/openseadragon#581]
Hello to everyone. Can you please guide me how to implement scroll up/down the viewer using my own button in custom tool bar

**Comment by msalsbery** [comment]
The viewer uses code like this to move the viewport up and down in response to the up/down arrow keys:
```javascript
// up arrow
viewer.viewport.panBy(new OpenSeadragon.Point(0, -0.05));

// down arrow
viewer.viewport.panBy(new OpenSeadragon.Point(0, 0.05));
```
Is that what you meant or did you need help with OpenSeadragon buttons?

**Comment by gkdagk** [comment]
It solved my issue. Thanks iangilman

**Comment by macarthy** [comment]
You might need to add this also :
  viewer.viewport.applyConstraints();
