### ISSUE TITLE
Zooms fail in IE9 with 1.2.0

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#582]
I try to support back to IE9, and heard recently from some IE9 users that they couldn't see zoomable images anymore.
I know I'm missing something as the demo pages work under 1.2 in IE9, however, I found that all 'zooms' on my site fail to load tilesources under IE9 with 1.2.

Examples:
http://deepzoomchattanooga.com/1938dam.php  (this loads 1.1.1 at path openseadragon/openseadragon.min.js)
http://deepzoomchattanooga.com/test.php  (this loads 1.2 at path openseadragon/openseadragon.min2.js)

All else on these two pages is the same.

Note:  I use the following method for zooms:
Example:
tileSources:   "/zoom/1938dam/dzc_output.xml"

Suggestions?

**Comment by msalsbery** [comment]
Try the code from #563 (or a build of the master branch). 

That fix isn't released yet but will be in 1.2.1 coming very soon!

**Comment by SamHall** [comment]
Very good to know.  Thanks for the quick response!
