### ISSUE TITLE
Load new tilesource and completely remove the old one

### ISSUE THREAD

**Issue by gkdagk** [openseadragon/openseadragon#587]
var viewer = OpenSeadragon({                    
                    id: 'viewerDiv1',
			tileSources: tileSources1
});

While opening another tilesource in the same div, openseadragon throws error.

viewer = OpenSeadragon({                    
                    id: 'viewerDiv1',
			tileSources: tileSources2
});
Hash viewerDiv1 has already been used.The old one and  new are messed up.

Anyway to completely clear the old tilesource and to load the new tilesource.

**Comment by jorntx** [comment]
Try using the open function instead of creating a new viewer instance with the same id:

viewer.open(tileSource)

This should load the new source and discard the old one.

**Comment by gkdagk** [comment]
Thanks...jorntx ... It's working fine

**Comment by makoychan** [comment]
Can you this with jpeg? because nothing is happening on my end. i loaded the image using the code
  tileSources: {
                            type: 'image',
                            url: '\\images\a.jpg'
                        }

but when i tried to change the image
viewer.close()
viewer.open('\\images\b.jpg')

nothing happens and the current image is just static, you cant move it or anuthing

**Comment by iangilman** [comment]
You're correctly specifying the full tile source (which includes both the type and url) at first, but you need to do the same with `open`, like so: 

```
viewer.open({
  type: 'image',
  url: '\images\b.jpg'
});
```

**Comment by ayamany224** [comment]
@iangilman  when I use viewer. open annotations are no longer working can u help me, please?

**Comment by iangilman** [comment]
@ayamany224 it doesn't sound like your question has anything to do with this issue... can you please file a new one? Also, can you please provide more detail? What is "open annotations"? And were you using it with OpenSeadragon? What does it mean when you say they are no longer working?

**Comment by yowzadave** [comment]
Calling `viewer.open()` always zooms to the extents of the viewport; Is there a way to update the tile source in-place, without affecting the current pan/zoom? This is especially janky if we're viewing pages in `collectionMode`--I may be zoomed to a particular page and not want to lose that location when a tileSource is updated.

**Comment by iangilman** [comment]
@yowzadave If you use `addTiledImage` instead, it doesn't trigger the pan/zoom.
