### ISSUE TITLE
Ability to set opacity on individual TiledImages

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#591]
Potential follow-up to #446. 

I believe what's necessary is to create a new off-screen canvas for each TiledImage that isn't completely opaque (or completely transparent) and compose all the tiles needed into that canvas and then draw the canvas to the viewer with the proper opacity. If we try to compose the tiles directly onto the viewer with semi-transparency, we'll get seams where they overlap.

**Comment by avandecreme** [comment]
>If we try to compose the tiles directly onto the viewer with semi-transparency, we'll get seams where they overlap. 

Why?
Can't global alpha work? http://www.w3schools.com/tags/canvas_globalalpha.asp

**Comment by iangilman** [comment]
The picture at the top of that page is an excellent illustration of why it won't work: see the places where the colored rectangles overlap? See how they're darker than the rest of the rectangle? We'll get the same effect if we paint two partially-overlapping image tiles with semi-transparency. 

The way OpenSeadragon renders, it's always overlapping tiles. For instance, if there's a low res tile that covers the entire image, and we have a couple of high res tiles but not enough to completely cover the low res tile. Even when the high res tile arrives, we take a few frames to fade it in (during which time they're still overlapping). For that matter, the DZI format has a tile overlap built into it to avoid drawing seams. 

I suppose another way to handle opacity would be to figure out how to clip all of the tiles so there is no overlapping when drawing with semi-transparency. This may affect how the result looks, and it'll mean we can't do tile fading, but it might be worth it if it's a lot more performant than the off-screen canvas technique.

**Comment by avandecreme** [comment]
Ok, makes sense now. Thanks for the clarification.

**Comment by iangilman** [comment]
Come to think of it, we wouldn't necessarily need a separate offscreen canvas for every semi-transparent TiledImage; just a single offscreen canvas the size of the Viewer would do it. We could then draw the semi-transparent ones into that canvas fully opaque, and copy from that canvas with the appropriate transparency.

**Comment by iangilman** [comment]
Implemented by #644
