### ISSUE TITLE
Precise control over zomming

### ISSUE THREAD

**Issue by tollr** [openseadragon/openseadragon#599]
Hi,

I don't really know if it's the good section to ask this but anyway : 

We've been messing around with OpenSeaDragon for a few weeks working on an artist website. The idea is to enable the user to zoom inside a drawing. We disabled the button control for we want the user to click to begin and end the zoom. 

Basically on the first click the zoom begins, on the second it stops and on the third it would zoom out. 

We are clearly inspired by this use of seadragon : http://www.chrisjordan.com/gallery/rtn/#cigarettes

We also couldn't figure out how to get that smooth zoom. 

Sorry if this is not the right section. 

Thank you !

**Comment by iangilman** [comment]
Sure, this is a fine place to ask. 

You'll want to disable click to zoom (setting zoomPerClick to 1 works), and then capture clicks yourself: 

```
viewer.addHandler('canvas-click', function(event) {
  // check event.quick to verify it's not a drag
});
```

For the zooming, you'll need to manage the animation yourself. For each frame, adjust the zoom with `viewer.viewport.zoomTo(newZoom, null, true)`. That third parameter is important; it means you're taking care of the animation yourself. 

Zooming happens on an exponential scale, so you'll want to keep that in mind. It's convenient to convert the scale to linear for your tweening and then back for the zoom itself. 

```
var zoomStart = 1;
var zoomEnd = 8;
var zoomStartLog = Math.log(zoomStart);
var zoomEndLog = Math.log(zoomEnd);

// And then each frame 
var newZoom = Math.exp(zoomStartLog + ((zoomEndLog - zoomStartLog) * completion));
viewer.viewport.zoomTo(newZoom, null, true);
```

Finally, you might want to ease in and ease out of your zoom at the beginning and end. You can run your tween counter through a cubic bezier, something like:

http://www.netzgesta.de/dev/cubic-bezier-timing-function.html
https://github.com/arian/cubic-bezier

I hope this helps!
