### ISSUE TITLE
On-screen navigation controls and Selenium WebDriverJS click issue

### ISSUE THREAD

**Issue by fractos** [openseadragon/openseadragon#600]
Hi,

I am writing some tests using Selenium WebDriverJS via Protractor on a website using OpenSeaDragon. A test scenario I am looking at involves causing OSD to zoom into the image. Although I can get the WebElement object for the Zoom In button, it looks like it is ignoring the click event generated from WebDriverJS.

Any ideas or experience with this?

Thanks,

Adam.

**Comment by msalsbery** [comment]
The click event isn't handled by OpenSeadragon. Can you generate a mouse down then a mouse up instead? That's what our tests do.

**Comment by fractos** [comment]
Hiya, thanks for the very fast reply!

I tried mouseDown/mouseUp before, with the same result. Just tried it again. Here's a snippet of my code:

element(protractor.By.css('.zoomIn')).then(
    function(canvasZoomInButton) {
        browser.actions().mouseDown(canvasZoomInButton).mouseUp().perform();
        browser.sleep(5000).then(protractorCallback);
    });

Note: A script has decorated the appropriate div in the openseadragon-container with the "zoomIn" class during the web page setup.

The effect is that the zoom in div is highlighted as if selected, but no zoom occurs. This is a zoomable image and using the mouse or keys to zoom works fine normally.

**Comment by iangilman** [comment]
@fractos are you still having trouble with this? Have you looked at how we trigger clicks in our tests?

**Comment by fractos** [comment]
@iangilman Hi Ian, I had to abandon that method of approach. Instead, we put a reference to the osd instance into the window object and accessed the viewport object directly from there in order to zoom. I did look at how you trigger clicks in your tests but I could not get that working in situ.

**Comment by iangilman** [comment]
@fractos Interesting; sorry it didn't work out the way you wanted, but I'm glad you got something to work. 

I think I'll close this ticket now.

**Comment by fractos** [comment]
Okay, thanks Ian.
