### ISSUE TITLE
Update tile sources in Angular app

### ISSUE THREAD

**Issue by somentelucas** [openseadragon/openseadragon#605]
Hi,

I am working on an Angular project in which the tiles are regenerated (with the same name) and the view should be updated. I have even tried to destroy my viewer and generate another one but even though the image is the old one from the last page refresh.

Thanks!

**Comment by iangilman** [comment]
I wonder if the browser is caching the images and that's why you're not seeing new versions? Is it possible to change the tile names for each new revision?

**Comment by msalsbery** [comment]
>Is it possible to change the tile names for each new revision?

...or set cache control headers appropriately?
