### ISSUE TITLE
Get currently viewable overlays(viewed by user)  while scrolling

### ISSUE THREAD

**Issue by gkdagk** [openseadragon/openseadragon#606]
While scrolling it's possible to get overlays which are viewed by the user. Generally i want to display annotation outside of the viewer about the currently viewed overlays while scrolling. Hope you got the issue.

Thanks
Ganesh

**Comment by iangilman** [comment]
You'll want to keep track of your overlays and where they are located in viewport coordinates. Then, whenever the user pans or zooms, you can update based on that. Something like so:

```
var update = function() {
  var bounds = viewer.viewport.getBounds();
  // loop through your overlays, comparing their location to the bounds 
};

viewer.addHandler('pan', update);
viewer.addHandler('zoom', update);
```

**Comment by gkdagk** [comment]
function Update(event)
{
    var viewer = event.eventSource;
    if (viewer.currentOverlays.length > 0 && viewer.viewport != null) {
        var bounds = viewer.viewport.getBounds();
        for (var i = 0; i < viewer.currentOverlays.length; i++) {
            if (viewer.currentOverlays[i].bounds.y >= bounds.y && viewer.currentOverlays[i].bounds.y <= bounds.y+bounds.height) {                
                console.log("came in:-" + bounds.y + " overlay.y:" + viewer.currentOverlays[i].bounds.y)
            }

        }
    }
    
}
Can you correct me, if i am wrong...
Thanks
Ganesh

**Comment by iangilman** [comment]
Sure, that's the general idea. How you do the check depends on what you want to count. As you've written it, it'll detect whether the overlay's top edge is at the same height as the current viewport. This doesn't guarantee that you can see the overlay, as it might be off the left or the right side. Here's a test to make sure the overlay is entirely within the viewport: 

```
var overlayBounds = viewer.currentOverlays[i].bounds;
if (overlayBounds.x >= bounds.x && overlayBounds.x + overlayBounds.width <= bounds.x + bounds.width && 
        overlayBounds.y >= bounds.y && overlayBounds.y + overlayBounds.height <= bounds.y + bounds.height) {
    console.log("found one!");
}
```

Here's a test to make sure that at least some portion of the overlay is visible: 

```
var overlayBounds = viewer.currentOverlays[i].bounds;
if (bounds.x + bounds.width > overlayBounds.x && bounds.x < overlayBounds.x + overlayBounds.width &&
        bounds.y + bounds.height > overlayBounds.y && bounds.y < overlayBounds.y + overlayBounds.height) {
    console.log("found one!");
}
```

**Comment by gkdagk** [comment]
Thanks  iangilman. It solved my issue.

Thanks
Ganesh
