### ISSUE TITLE
TileCache issue with image sequences since 1.2.1

### ISSUE THREAD

**Issue by MartinPluta** [openseadragon/openseadragon#607]
The issue described here does not seem to be present in version 1.2.1, but in the current master branch state:

Compare these two urls both using the same tile sources, but different openseadragon versions (1.2.1 and current), by clicking through the sequence for about 30 to 50 images and then going back to the first image again: 

http://www.zoosphere.net/seadragoncurrentgitclone/ <-- Thros notification the tiles could not be loaded from cache and contains blank files. At least the first image will by completely blank. Changing the zoom level brings back the tiles, so probably a reloading issue?

http://www.zoosphere.net/seadragonv121/ <-- non of the described issues

The current version was built by me using grunt as described and not performing any modifications.

![tilecacheissue](https://cloud.githubusercontent.com/assets/4223317/6265155/3f06f5f0-b82b-11e4-8ae4-604b89e7dfa6.png)
If you need additional information on this, please let me know, or if you know where to start, I would also look into the code myself.

Thanks and Greetings

Martin

**Comment by avandecreme** [comment]
It is probably unrelated but in the first link the scalebar plugin script does not load correctly.
Also, it should be loaded after OpenSeadragon.

**Comment by MartinPluta** [comment]
Thanks fpr the quick response. Removed the scalebar plugin script. Issue still persists.

**Comment by avandecreme** [comment]
Yep, I reproduce the issue now. @iangilman will hopefully look at it.

**Comment by MartinPluta** [comment]
Alright, thanks a lot :) If I can be of any help, let me know.

**Comment by iangilman** [comment]
Do you stop and let each image fully load before going to the next one, or do you just click through as fast as possible? I tried the latter and got your results; it seems that we're not clearing out stale tile requests, so it's got a huge backlog if you go through too quickly. 

One possible test might be to set the `imageLoaderLimit` to something small like 1.

One thing we should be doing is calling `item.destroy()` at both these spots:

https://github.com/openseadragon/openseadragon/blob/master/src/world.js#L185
https://github.com/openseadragon/openseadragon/blob/master/src/world.js#L201

We should also add `this.imageLoader.clear()` to the Viewer.close function: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L657

Can you give those things a try?

**Comment by MartinPluta** [comment]
Thanks for the response, I'll try adding this to the code. The issue is independent of the loading state of the images. Clicking through them waiting for each image to load gives the same reslut, as can be tested on 

http://www.zoosphere.net/seadragoncurrentgitclone/

**Comment by MartinPluta** [comment]
I'll do a bit more testing, but it seems the destroy and clear methods and do the trick.

**Comment by MartinPluta** [comment]
This is the modified version, but it seems to be loading fluently now since adding the two destroy and the clear method calls as suggested:

http://www.zoosphere.net/seadragoncurrentgitclonedev/

It now displays notifications on tiles that are ignored before reset, which I think may be as intended.

![ignoringtileloadedbeforereset](https://cloud.githubusercontent.com/assets/4223317/6283148/61b258e6-b8e0-11e4-91f7-059369b9129d.png)

**Comment by iangilman** [comment]
Awesome, and yes, I believe that is intentional. 

Can you make a pull request with these fixes? Thank you for trying it out!

**Comment by MartinPluta** [comment]
Added a pull request: https://github.com/openseadragon/openseadragon/pull/608
Greetings

**Comment by iangilman** [comment]
Fixed by #608

**Comment by AsmaAq** [comment]
I've a case in which if user zoomed to high levels, I don't want the handlerURL to be send a request to server to get new tiles, like below: 

![image](https://user-images.githubusercontent.com/14885860/36834296-195224ec-1d3b-11e8-9898-857d1507a3de.png)

But when i return "" in line 320. I got this error in console and it causes the UI to stuck in old versions of Firefox. 

![image](https://user-images.githubusercontent.com/14885860/36834503-be4a902e-1d3b-11e8-93ca-a81d50076301.png)


So how can I stop loading tiles in this case? what should i return or add in this case (line 320)

I need a solution to prevent browser stuck :| 

Thanks in Advance, 
Asma

**Comment by iangilman** [comment]
You can just include `maxLevel: parent.MaxAvailableLevel` as part of your tilesource definition.

If you need a more nuanced way to say which tiles exist, you could include `tileExists: function(level, x, y) { /* return true or false */ }` instead.

**Comment by AsmaAq** [comment]
Thanks Ian, 

How can I use this function ? (tileExists) in my case? I couldn't find an example regarding using it while loading tiles.. 
 Is there any reason to get the error shown in the screenshot rather than not returning a URL?

**Comment by iangilman** [comment]
I can show you an example using your code if you drop it here in the thread as text (rather than just a screenshot).

**Comment by AsmaAq** [comment]
Hi Ian, 

Please find below my code: 

tileSources: {
                height: parseInt(parent.height),
                width:  parseInt(parent.width),
                tileSize: parent.tileSize,
                Overlap: parent.overlap,
                defaultZoomLevel:9,
                getTileUrl: function( level, x, y ){
                    level = (level > 9) ? level : 9;
                    if(parent.pendingLevel == 0){
                        if( level > parent.MaxAvailableLevel && parent.MaxAvailableLevel < parent.MaxLevel && level <= parent.MaxLevel){
                            parent.waitForTilesReady(level,x,y);
                        }
                        else if(level <= parent.MaxAvailableLevel){
                            handlerURL = parent.prefixUrl + parent.Url + parent.separations + "/" + parent.spreads + ".1" + "/" + level + "/" + x + "_" + y + "." + parent.format;
                            return handlerURL;
                        }
                        //this is the case I want to handle
                        else if (level > parent.MaxLevel) 
                                return "";
                        }
                    }
            }

Thanks for the help

**Comment by iangilman** [comment]
Thanks! This is how you would include `tileExists`:

```
tileSources: {
  height: parseInt(parent.height),
  width:  parseInt(parent.width),
  tileSize: parent.tileSize,
  Overlap: parent.overlap,
  defaultZoomLevel:9,
  getTileUrl: function( level, x, y ) {
    level = (level > 9) ? level : 9;
    if(parent.pendingLevel == 0){
      if( level > parent.MaxAvailableLevel && parent.MaxAvailableLevel < parent.MaxLevel && level <= parent.MaxLevel){
        parent.waitForTilesReady(level,x,y);
      }
      else {
        handlerURL = parent.prefixUrl + parent.Url + parent.separations + "/" + parent.spreads + ".1" + "/" + level + "/" + x + "_" + y + "." + parent.format;
        return handlerURL;
      }
    }
  },
  tileExists: function( level, x, y ) {
    return level <= parent.MaxLevel;
  }
}
```

**Comment by AsmaAq** [comment]
Thanks Ian :)
