### ISSUE TITLE
Release OpenSeadragon 2.0

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#611]
This is going to be a big one, with the new multi-image support. I think we're probably ready, though. 

Anything else to take care of first? We should do a multi-image example page on the site, at least.

**Comment by avandecreme** [comment]
Should that be a 2.0.0?
For my use case, I will be missing the layer transparency so I will hold on 1.2 for a while.

**Comment by iangilman** [comment]
Sure...maybe 2.0.0 makes sense. I'm open to either way. 

We really haven't been following http://semver.org/ ... I've generally been bumping the middle number for breaking changes and the last number for compatible changes, and just letting the first number roll over after the middle number hits 9. 

On the other hand, this is a major upgrade, with a lot of breaking changes, so maybe it's worth going to 2.0.0. 

Regarding layer transparency, good to know you need that...maybe I'll bump up the priority on that feature. Is that the only thing keeping you from upgrading?

**Comment by avandecreme** [comment]
Yeah, I kind of had semver in mind when suggesting 2.0.0. The current scheme looks good to me as well.

>Regarding layer transparency, good to know you need that...maybe I'll bump up the priority on that feature. Is that the only thing keeping you from upgrading? 
Yes, I think so. However, I do not need the new features for now so staying on 1.2 is fine.

**Comment by iangilman** [comment]
Cool. I won't let it hold up the release, but I'll keep it on the radar.

**Comment by iangilman** [comment]
I think I'll go with 2.0.0 after all; it does feel like a significant upgrade. Also I think I'm ready to do it... :)

**Comment by avandecreme** [comment]
:+1:

**Comment by iangilman** [comment]
Done! https://github.com/openseadragon/openseadragon/releases/tag/v2.0.0
