### ISSUE TITLE
Cross origin policy not always working

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/openseadragon#612]
I put together a demo there: http://avandecreme.github.io/openseadragon-debug-site/

Display your browser console and click on "Log data URL".
Sometimes it works, sometimes you get a cross origin security error (both on Firefox and Chrome).

The error is quite random. You need to refresh without cache between tests.

**Comment by iangilman** [comment]
Any idea how to fix?

**Comment by avandecreme** [comment]
Not really, I am wondering if that could be because the image might be paint into the canvas before it got the response from the server (with the CORS headers) hence, tainting the canvas.
Do you know if OSD could be doing that?

**Comment by iangilman** [comment]
Seems highly unlikely that we would make a blank canvas for a tile image that hasn't loaded. 

I suppose we could check to make sure that the image always gets the correct `crossOrigin` value. Maybe stick a console.log in `ImageJob.start`?

**Comment by iangilman** [comment]
Fixed by #613
