### ISSUE TITLE
Restrict Zoom out and dragging image

### ISSUE THREAD

**Issue by gkdagk** [openseadragon/openseadragon#614]
How to set Minimum zoom level(like should not zoom out beyond zoom level 1). And also image boundaries should exactly fit with container. Zoom out or dragging should not make the image to move outside of the viewport. Hope you understand. Thanks for guidance.

**Comment by avandecreme** [comment]
I think all the options you need are documented here: http://openseadragon.github.io/examples/ui-zoom-and-pan/

**Comment by gkdagk** [comment]
Thanks iangilman. It helped me to resolve my issue.

**Comment by iangilman** [comment]
Excellent! Thanks go to @avandecreme :-)

**Comment by gkdagk** [comment]
sorry.. unexpectedly i am facing other issues...
My osd viewer settings is
OpenSeadragon({
        // debugMode: true,
        id: idContainer,
        tileSources: ImageInfo.ImageURL,
        showNavigator: true,
        constrainDuringPan: true,
        autoResize: false,
        useCanvas: true,
        visibilityRatio: 1,
        defaultZoomLevel:1,
        minZoomLevel: 1,
        maxZoomLevel: 10,
        zoomPerClick: 1.4,
        toolbar: idToolbarDiv,
        panHorizontal: false,
        wrapVertical:true
    });
viewer.addHandler("open", function (event) {
        ViewerLoad(event);
    });
   
function ViewerLoad(event)
{   
    event.eventSource.viewport.fitBounds(new OpenSeadragon.Rect(0.0, 0.0, 1, 1));
}
issues are
1. My containers are differ in size. The image top-left not exactly fit into the container. some gab above the image is visible and in some of the container the image little moved up.
2.While dragging down of the top-left of the image, then bottom part of the image is coming on top and it's cyclic

Any Help..Please

Thanks
Ganesh

**Comment by avandecreme** [comment]
I am not sure to understand your first point.

For 2, you should set wrapVertical: false (or just don't set it to true).

**Comment by iangilman** [comment]
@gkdagk For issue number 1, it sounds like you mean that your viewer is a different shape than your image, and therefore the image has some white gaps around it. Is that correct? If so, that's just how it works. If you want it to be the exact same shape, you have to make your viewer whatever shape the image is. 

Unless you don't mind the image being cropped some? If so, use the `homeFillsViewer` option.

**Comment by gkdagk** [comment]
Thanks for your time.It Solved both issues.
Issue 1: As you said i am resizing both containers
Issue 2: wrapVertical: false helped me

Thanks
Ganesh

**Comment by iangilman** [comment]
Happy to help!
