### ISSUE TITLE
Canvas quality very bad compared to non-canvas?

### ISSUE THREAD

**Issue by philipgiuliani** [openseadragon/openseadragon#615]
OpenSeadragon without canvas:
![bildschirmfoto 2015-03-02 um 12 43 07](https://cloud.githubusercontent.com/assets/5446019/6440228/43368b46-c0db-11e4-9365-aa77b979e652.png)

OpenSeadragon with canvas:
![bildschirmfoto 2015-03-02 um 12 43 38](https://cloud.githubusercontent.com/assets/5446019/6440236/4d4af4be-c0db-11e4-9bfa-452ffedf68c6.png)

Is there a trick to get the canvas image quality better? The pixelDensity is 1 on my PC.

Im using the master branch.

**Comment by iangilman** [comment]
Interesting. The two viewers are otherwise identical? Have you tried playing with `minPixelRatio`?

**Comment by philipgiuliani** [comment]
Yes all i changed was the `useCanvas: false`. No i haven't tried that out, didn't knew about that option. Im not in office now, i will try it out tomorrow.

*Offtopic*
I also optimized the image queue to discard unused tiles! I will make a PR tomorrow with my first try. Its working very well so far for me.

**Comment by philipgiuliani** [comment]
I really had to set the `minPixelRatio`, its extremely sharp now for me!

**Comment by iangilman** [comment]
Cool. The default `minPixelRatio` is, I think, a decent compromise between network/memory usage vs. sharpness, but of course for certain uses, you want it sharper. 

Thanks for the image loader PR! I'll take a look at it soon.
