### ISSUE TITLE
Zoom out to bring the overlay to certain top

### ISSUE THREAD

**Issue by gkdagk** [openseadragon/openseadragon#617]
Hi

Just need an idea to how this can be acheived. I have two overlays.
1. { overlay.bounds.y -> 0.2567,page.y->50px}
2. { overlay.bounds.y -> 0.8567,page.y->150px}

i want to bring the second overlay to document top of 100px and keep the first overlay at the same top of 50px by zoom out . I tried to do with viewport.fitBounds and viewport.pixelFromPoint, but it's not perfectly coming. Do you have any idea..

Thanks
Ganesh

**Comment by iangilman** [comment]
I'm not quite sure I understand. You want to move the overlay? Or you want to zoom/pan the viewer?

**Comment by gkdagk** [comment]
Yes..iangilman.. I want to move the overlay by zoom/pan the viewer.

I have 2 overlays in a viewer. 
$("#Container").find("overlay=1st").position().top->-50px
$("#Container").find("overlay=2nd").position().top->-150px


I want to keep the first overlay still at the top of 50px and but second one top should be 100px by doing zoom/pan. 
Finally...
$("#Container").find("overlay=1st").position().top->-50px
$("#Container").find("overlay=2nd").position().top->-150px
Hope you clear now..

Thanks
Ganesh

**Comment by iangilman** [comment]
Probably the easiest is to do `viewport.fitBounds()` on the overlay's bounds in viewport coordinates, which you should have from when you created the overlay. Can you show me how you create the overlays?
