### ISSUE TITLE
How to get viewport.bounds.y per 0.01 zoom

### ISSUE THREAD

**Issue by gkdagk** [openseadragon/openseadragon#618]
Hi
How to calcultate what'll be the viewport.bounds.y after zooming of   (viewport.getZoom()+  0.01 )

Thanks
Ganesh

**Comment by iangilman** [comment]
`viewport.getBounds().y` is the top edge of the bounds. First step is to figure out what the new bounds height will be. Something like this: 

```
var oldZoom = viewport.getZoom();
var oldHeight = viewport.getBounds().height;
var normalizedHeight = oldHeight * oldZoom;
var newZoom = oldZoom + 0.01;
var newHeight = normalizedHeight / newZoom;
```

Then figure out the `y` based on the center and the new height: 

```
var centerY = viewport.getBounds().y + (oldHeight / 2);
var newY = centerY - (newHeight / 2);
```

Just out of curiosity, why are you wanting to calculate this?

**Comment by gkdagk** [comment]
I want to bring two overlays with difference of 100px with respect to document. 
Thanks for your help

**Comment by iangilman** [comment]
Cool. I'll be curious to see what you're building when you're ready to share!
