### ISSUE TITLE
Is it possible to Stretch image horizontally?

### ISSUE THREAD

**Issue by gkdagk** [openseadragon/openseadragon#619]
Hi ..
I have an big vertical overlay. By Zoom out of below 0.09 can be viewable. At this time viewport occupies less space in container. So i want to stretch it horizontally.
But Viewport should be in same bounds..No change in bounds.y and bounds.height.
 i.e zoom should apply to width and stretch the image to fit to container.
If i am increasing the width of ($("#Container1").find(".openseadragon-canvas canvas")[0]), then i am able to achieve this(Image looks bad...No worries)..which is not correct way....   Do you have any other idea

Thanks
Ganesh

**Comment by iangilman** [comment]
So you want to stretch the actual zooming image, not the overlay, right? This is not yet possible; the issue to add this feature is #592.

**Comment by gkdagk** [comment]
I planned to put one more canvas over .openseadragon-canvas and do a copy and stretch it.. Expecting soon the feaure..
Thanks iangilman.

**Comment by iangilman** [comment]
Well, that feature is currently in the backlog; no one has volunteered to take it on, so I don't know when it will happen.

**Comment by NSV1991** [comment]
I also have the same requirement, is it any way possible now to change the aspect ratio of the image or to Stretch the image?

**Comment by iangilman** [comment]
There appears to have been no recent action on https://github.com/openseadragon/openseadragon/issues/592. If you're up for it, we would welcome a pull request; I'm happy to answer questions about the code as you get into it.

**Comment by NSV1991** [comment]
@iangilman Thanks for acknowledgment, I will surely look into the issue and try to solve the problem. I will update you regarding that.

**Comment by NSV1991** [comment]
I have gone through code for checking from where the height and width of TiledImage are set, before I make any changes I need to know
1. How does the flow of setting or overriding height and width of Tiledimage work?
2. What are usage of scale, normHeight, spring and contentAspectX?

If I got wrong please correct me, Image is loaded using aspect ratio so that it does not look stretched while loaded on canvas and that's why height is neglected if both are provided

**Comment by iangilman** [comment]
Apologies for the delayed response! I've now answered these questions here: https://github.com/openseadragon/openseadragon/issues/592#issuecomment-875979435
