### ISSUE TITLE
How to tell if a viewer belongs to a navigator?

### ISSUE THREAD

**Issue by adamaskew** [openseadragon/openseadragon#620]
I was wondering if  there is a way to tell if a viewer object is a navigator or a normal viewer?

I have a drawer and can get the the viewer by doing drawer.viewer but just need to know if it is a navigator or not.

**Comment by msalsbery** [comment]
How did you get the drawer?

**Comment by adamaskew** [comment]
Im currently in the drawTiles function and it gets passed in.

**Comment by iangilman** [comment]
I think `viewer instanceof OpenSeadragon.Navigator` should work.

**Comment by adamaskew** [comment]
Yes that worked a treat!

Thanks
