### ISSUE TITLE
Ability to present tilesources at different depths?

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#622]
Forgive the duplication if this has been answered.  I would like to present some images with foreground and backgrounds set at different depths.  This would provide a parallax view - simulating a 3D effect.

Is there a a way to present 2 tilesources like this at once?

**Comment by iangilman** [comment]
Neat idea! We don't have a feature like that. You could make it happen using the multi-image feature in the master branch, I suppose, if you don't mind manually moving the two layers. For starters you'd need to make your top tile source out of PNG tiles with appropriate transparency (so you could see the background through them), and then you'd need to detect pan and move the background layer appropriately. 

Since this could all be done on top of the OSD that exists in the master branch, maybe it's good candidate for a plug-in?

**Comment by SamHall** [comment]
I'll investigate the multi-image feature, but will leave the plug-in development to those with such skills.  Multi-image will open up a lot of neat options.

Thanks.

**Comment by iangilman** [comment]
Cool. I'd love to see what you come up with! We need some good demos for the multi-image feature.

**Comment by SamHall** [comment]
I couldn't agree more on the need for demos.  I'm not 100% clear where to start... downloaded the Master Branch but need to know where to focus on building such a demo.  So many pieces.  Do they all need to be loaded as is shown in the demo html or just the multi-image.js?

Any helpful starting tips would be greatly appreciated.

**Comment by iangilman** [comment]
This is probably the simplest multi-image example code we have at the moment: 

https://github.com/openseadragon/openseadragon/blob/master/test/demo/item-animation.html

Take a look at that and let me know what questions you have!

**Comment by SamHall** [comment]
How would I use that example with XML tilesources?
```
var viewer = new OpenSeadragon.Viewer({
id:"openseadragon-canvas",
        prefixUrl: "/openseadragon/images/",
        toolbar:   "toolbarDiv",
        
tileSources: [
"/zoom/1979/dzc_output.xml",
 "/zoom/1979b/dzc_output.xml"
 ],
```
I attempted it and didn't get very far.  In the above example I have two selectable zooms.

**Comment by iangilman** [comment]
Something like this: 

```
var viewer = new OpenSeadragon.Viewer({
    id:"openseadragon-canvas",
    prefixUrl: "/openseadragon/images/",
    toolbar:   "toolbarDiv",
    tileSources: [
        {
            x: 1, 
            y: 1, 
            width: 2,
            tileSource: "/zoom/1979/dzc_output.xml"
        },
        {
            x: 4, 
            y: 1, 
            width: 2,
            tileSource: "/zoom/1979b/dzc_output.xml"
        }
    ]
});
```

...would set them next to each other. You want them stacked on top, so maybe you'd make the coordinates the same for starters. And then as you pan around you would shift the background one a little, like so: 

```
viewer.world.getItemAt(0).setPosition(new OpenSeadragon.Point(newX, newY), true);
```
