### ISSUE TITLE
Force loading of a tilelevel

### ISSUE THREAD

**Issue by philipgiuliani** [openseadragon/openseadragon#623]
Hi, its already possible to force the loading of a given tile level (e.g. 3) already at the beginning as soon as the viewer is open?

*Idea*
We could rewrite the queue a bit, so that jobs has a priority, and the current tiles have a higher priority than the preloading of a level (clearing the queue before every draw wont work anymore with this approach).

**Comment by iangilman** [comment]
We don't have such a feature. What do you see using it for?

**Comment by philipgiuliani** [comment]
I have a very long image with 100 tiledImages for example and they are all next to each other. When you open the page you see the first TiledImage. When you scroll to the next TiledImages it sometimes takes a while to load and in the meantime it is transparent which is very ugly.

I send you a link via E-Mail so you can check it out. Its not public yet!

**Comment by iangilman** [comment]
Gotcha. So it's about preloading TiledImages that are offscreen. I like the idea of loading a single tile level when there is nothing else to load. Ideally it would be whatever tile level is the largest where the image still fits in a single tile. For that matter, I've been thinking that we should default to that for all images (start with the largest tile that fits the entire image) if we're not already. 

In terms of which offscreen TiledImage to preload, of course it should be based on proximity to the viewport, so the nearby ones load sooner. 

On the other hand, if you have 100 images, it seems like a waste of bandwidth to preload all 100 every time the user opens the page (even if they aren't loading other things, we still have to think about people's data caps and batteries). So maybe it should preload within a certain radius or something. Of course this could be customized. 

Another possibility is we could designate a "not yet loaded" color or image we use, so for TiledImages that don't have anything loaded yet, we still draw a rectangle with that color or image, so you don't have the "where are the pages?" experience.

**Comment by philipgiuliani** [comment]
Thanks for your answer. I totally agree with the data usage that the user needs and haven't thought about that.

I really like your idea to tint the tiled image in a background color! It would seem a lot smoother with that.

**Comment by iangilman** [comment]
Cool. Maybe that's a good place to start. Should be relatively easy...basically in tiledimage.js, if there are no loaded tiles, ask the Drawer to paint a white rectangle.

**Comment by iangilman** [comment]
Btw, a patch for that would probably follow a similar path as #627 in terms of where the code changes. Also the math in that patch for how to translate from tiledImage to Drawer coordinates would be similar.

**Comment by philipgiuliani** [comment]
Sorry for the late answer, today i started looking a little bit over the source, and how i could accomplish this. I wasn't able to find out where the best way is to check if tiles are loaded, and how i check if it has tiles. Should i check isCovered?

Thanks a lot :)

**Comment by iangilman** [comment]
This is for drawing a white or colored rectangle when there are no tiles, right? How about right at: 

https://github.com/openseadragon/openseadragon/blob/master/src/tiledimage.js#L1174

...check if `lastDrawn.length === 0` and draw a rectangle then. The rectangle math would be similar to the clipping rectangle math just above that line, except it would be based on `tiledImage.getBounds(true)` rather than `tiledImage.imageToViewportRectangle(tiledImage._clip, true)`. Perhaps that "convert a Viewport rectangle into a Drawer rectangle" math should be encapsulated into its own function in Drawer. 

Sound reasonable?

**Comment by philipgiuliani** [comment]
Thanks a lot, I really did not undestood what lastDrawn is, i will try it out and open a PR as soon as i make some progress :)

**Comment by iangilman** [comment]
Yeah, lastDrawn is probably not the best name for that array. At any rate, it's just the tiles to draw.
