### ISSUE TITLE
Overlay events being intercepted(?) on mobile

### ISSUE THREAD

**Issue by jamesdoc** [openseadragon/openseadragon#625]
I've been exploring using overlays as hotspots to allow visitors explore a piece of art, eg click on an overlay and hear the artist talking about what inspired them while creating that section, etc.

Getting this up and running on standard desktop browsers has been pretty simple; create the overlay with a class, then add a bit of jQuery to watch for click events. However when I go to test on mobile devices I get no reaction to the click event. I've made a [JsBin](http://jsbin.com/putegeruha/3/edit?html,js,output) with an example. I'm wondering if the click event is being intercepted somewhere?

http://jsbin.com/putegeruha/3/edit?html,js,output

Would love to know if anyone has any thoughts... Thanks.

**Comment by msalsbery** [comment]
Yes the viewer captures the down/up events.

Your overlay should catch down events and prevent them from bubbling with stopPropagation.

**Comment by jamesdoc** [comment]
Hi Mark. Thanks for the quick response.

I've switched my code to look more like this:
```
$(".pin").live('mousedown', function(e) {
	e.stopPropagation();
	alert('Call function');
});
```

This causes neither desktop or mobile browsers to register the click. Replacing `mousedown` with `click` resolves this issue in the desktop. Could you point out what I am missing please?

**Comment by iangilman** [comment]
@msalsbery Is this a case where @jamesdoc should be using MouseTracker instead of jQuery?

**Comment by msalsbery** [comment]
> I misread click event sorry. 

The viewer ignores click events but eats 'up' events on the capture phase so click events won't generate on an overlay.

The best way to handle events on  overlays is with the OpenSeadragon.MouseTracker class, since it handles three event models so you don't have to.

**Comment by msalsbery** [comment]
@ian yes, makes it way easier since there's three event models to account for...handling the fallback mousexxx events isn't sufficient.

**Comment by jamesdoc** [comment]
Okay, I think I understand the idea behind this, however I am entirely failing at the implementation. Is there a live example of MouseTracker?

**Comment by msalsbery** [comment]
Something like this perhaps (borrowed from Ian :))...

```javascript
new OpenSeadragon.MouseTracker({
    element: 'overlay-id',
    clickHandler: function(e) {
        // do stuff;
    }
});
```

**Comment by iangilman** [comment]
Note that (assuming you're using 1.2.1) there's an issue where the overlay doesn't actually appear in the DOM until the first draw after it's been added. Assuming you're creating the overlay with the options as you create the viewer (and assuming your viewer is named `viewer`), you'd do something like so: 

```
viewer.addHandler('open', function() {
    setTimeout(function() {
        new OpenSeadragon.MouseTracker({
            element: 'overlay-id',
            clickHandler: function(e) {
                // do stuff;
            }
        });
    }, 100); 
});
```

This issue is fixed on the master branch of OpenSeadragon, but not yet released.

**Comment by jamesdoc** [comment]
Ahh ha. Thank you both very much. That has solved it.

Many thanks.
James

**Comment by this-vidor** [comment]
@msalsbery Is it possible to make the viewer element transparent to events, under certain conditions?This "eating up events" behavior does not seem to jive with React's event delegation system (in this case, React is mounted to the overlay element), and it would be nice to have a workaround.
