### ISSUE TITLE
Accessibility of Thumbnail Strip

### ISSUE THREAD

**Issue by terenceingram** [openseadragon/openseadragon#628]
Is there anyway of making the thumbnail strip in the viewer accessible so that screen readers for those with limited vision can "see it" and navigate to it using the keyboard.

**Comment by iangilman** [comment]
We don't have accessibility built in to the thumbnail strip yet, but we would certainly welcome it. Would you be up for adding it in?

**Comment by terenceingram** [comment]
@iangilman I would be happy to. Can you point me to the area of code where I might changes? I have looked over the code but haven't come to grips with this part. Also I am not a canvas expert, so I am not sure if I can insert the appropriate tags for the canvas elements?

**Comment by iangilman** [comment]
Looks like the ReferenceStrip uses separate elements for each thumbnail. Here is where the container is created: 

https://github.com/openseadragon/openseadragon/blob/master/src/referencestrip.js#L77

...and here is where the individual thumbnails are created: 

https://github.com/openseadragon/openseadragon/blob/master/src/referencestrip.js#L185

There's also this element, that might be something to do with an earlier attempt at accessibility? I'm not sure what it's for. Anyway: 

https://github.com/openseadragon/openseadragon/blob/master/src/referencestrip.js#L439

**Comment by terenceingram** [comment]
@iangilman I had a look but don't have the time to change it. I eventually implemented an external thumbnail strip. Here's our example: http://nladom-test.nla.gov.au/nla.obj-41292842/view

**Comment by iangilman** [comment]
@terenceingram Looking good! Probably a better approach anyway. 

Btw, we have multi-image support on master, soon to be released. If you want you can do things like this with it: 

http://iangilman.com/osd/test/demo/m2/
