### ISSUE TITLE
titles / labels for image sequence?

### ISSUE THREAD

**Issue by wpegden** [openseadragon/openseadragon#634]
Is there a simple way to have titles or labels for images in a tilesource sequence?

For example, if viewing book pages, one might want to display the page number somewhere that was always visible regardless of zoom level.

 Thanks for any help,
Wes

**Comment by iangilman** [comment]
We don't have a mechanism for that. It's probably better done in your own code; you can put it outside the viewer or even have it hover on top. Keep an array of titles that matches the array of images, and watch the "page" event: 

```
viewer.addHandler('page', function(event) {
    $('.my-title-div').text(myTitleArray[event.page]);
});
```

**Comment by meeximum** [comment]
Hi, this seems to work for the actual picture, is there also a way for all shown images in the reference strip?

regards
Meex
