### ISSUE TITLE
Pointer events on transparent parts of canvas

### ISSUE THREAD

**Issue by EmilyReif** [openseadragon/openseadragon#638]
Is there a way to have pointer events pass through the transparent parts of the canvas (and on to divs behind) while still correctly manipulating the image when they are within the image bounds?

Thanks!

**Comment by iangilman** [comment]
I'm not aware of such a thing, but perhaps you could do the transparency detection yourself and marshal the events across as needed? Any thoughts, @msalsbery? 

Just out of curiosity, @EmilyReif, what sort of transparency shapes do you have?

**Comment by EmilyReif** [comment]
I just meant the transparent parts of the viewport that are outside of the image bounds. That is, if the image is zoomed out far enough to not take up the entire viewport, the parts around the outside. 

I know I can detect whether or not I'm within bounds  with something like:

		var clickP = _viewer.viewport.pointFromPixel(new OpenSeadragon.Point(evt.x, evt.y))
		if ((clickP.x < 1) &&
			(clickP.x > 0) &&
			(clickP.y <  _viewer.viewport.contentAspectY) &&
			(clickP.y > 0)){
			return true
		} else{
			return false
		}

But I was more wondering if there was a way to automatically have events propagate only if they are not in bounds (basically have the outer canvas have pointer-events: none, and the actual image have pointer-events: auto). This might just not be possible though!

 (Does that make sense?)

Thank you so much!

**Comment by iangilman** [comment]
Yes, that makes sense. I'm not aware of any way to do that, since it's all a single canvas. There might be a way to capture the events and then trigger them on the underlying element though. Of course if you are in control of the underlying element it might be more robust to talk to it directly without going through the DOM event chain.

**Comment by EmilyReif** [comment]
Ah, that makes sense. Yeah, we were considering that too but we weren't sure if there was a more direct way.

Thanks!
