### ISSUE TITLE
iiiftilesource.js only fetches jpg images regardless of format quality

### ISSUE THREAD

**Issue by cgoines** [openseadragon/openseadragon#641]
Hi all,

I noticed that iiiftilesource.js is hardwired to grab only a jpg representation of an image, regardless the actual format(s) specified in the "qualities" attribute from info.json.  

see lines 235-8: https://github.com/openseadragon/openseadragon/blob/dfe465f79e8b45f4522a747d5ac5627230825c6b/src/iiiftilesource.js#L235 

is this a known issue?  we are able to work around it if necessary.

thanks,

-c

**Comment by iangilman** [comment]
I don't think it's known. Would you be up for writing a fix for it? 

@jpstroop @azaroth42 Any thoughts?

**Comment by cgoines** [comment]
@azaroth42 mentioned last night in another thread that IIIF doesn't support other formats, so I'll just close this bug. Thanks, though!

**Comment by azaroth42** [comment]
It's a known non-issue, as all IIIF compliant systems are required to support the jpg format (along with other non-mandatory formats).

References:
 * http://iiif.io/api/image/2.0/compliance.html#format
 * Discussion issue in IIIF:  https://github.com/IIIF/iiif.io/issues/449
 * iiif-discuss post: https://groups.google.com/forum/?hl=en#!topic/iiif-discuss/3VDEu1rFIEs
 * Original mirador issue: https://github.com/IIIF/mirador/issues/517
