### ISSUE TITLE
Newbie Question: Focusing defaultZoomLevel

### ISSUE THREAD

**Issue by jeffreycwitt** [openseadragon/openseadragon#642]
I quite new at using open seadragon, but I've successfully got a demo working. Now I am wondering if there is a way to set the default load of a tiled image zoomed into a certain set of coordinates at the initial load. I think this is something different than merely loading a cropped version of the image, because loading a cropped image only lets you zoom in and out of that portion of the image. I would like the user to be able to back out of the section of the image I initially pointed them to.

I noticed for example the OpenSeadragon property `defaultZoomLevel`, which seems close to what I want, but it doesn't seem like it will allow me to specify the precise coordinates of the larger image that will be framed by that zoom.

Let me know if my question doesn't make sense and I'll try to clarify.

**Comment by philipgiuliani** [comment]
You could do the following:
```javascript
viewer.addHandler("open", function() {
     var point = @viewer.viewport.getBounds().getCenter();
     var zoomLevel = 1.5;

    viewer.viewport.panTo(point); // should be an instance of OpenSeadragon.Point()
    viewer.viewport.zoomTo(zoomLevel); // here the zoom
});
```

This code is untested, just an example.

**Comment by iangilman** [comment]
Yes, sounds like that's what you're looking for… I would recommend `fitBounds(myBounds, true)`  though… If you have specific coordinates, fitBounds is easier to work with than pan/zoom. Also, bypassing in `true` you skip the animation.

**Comment by jeffreycwitt** [comment]
Ok, thanks for your help. I think I'm making progress, but I'm definitely still learning.
If I can beg for further guidance.

Let's say I wanted to focus in on the illuminated initial in this image. 
http://images.scta.info:3000/pg-lon/L1r.jpg/full/full/0/default.jpg

I fairly confident that x component is 0.22 and y component is 0.17. 

here's my initial viewer: 
<div id="openseadragon1" style="width: 297; height: 271px; border: 1px solid black;"></div>

I would like the viewer to fill with just the illuminated initial -- basically zooming in on initial so that just the initial shows. 

I have something like this

    var rect  = new OpenSeadragon.Rect(0.22, 0.17, width, height);
    var myBounds = viewer.viewport.fitBounds(rect, true);

I have more trouble calculating width and height. 

The raw picture In terms of pixels is w2070 x h2862. And at that pixel size the height and width of the illuminated initial are w297xh271. (I've made the dimensions of the div container identical to this). 

But I'm unclear of how to convert this to vector height and width.

Thanks for your thoughts.

**Comment by iangilman** [comment]
In viewport coordinates, the entire width of the image is just 1. Halfway across the image is 0.5. 

297 / 2070 is 0.14347826086957, so that's the width you're looking for. It's square, so the height would be the same.

Make sense?

**Comment by jeffreycwitt** [comment]
yes, I'm so close, the zoom level is now perfect. But it seems like my calculation of the x and y component is just slightly off.

I was adding the pixel length of the "left offset" + ("the width" divided by 2) then divided by the width of the image. 

So I thought this would be: (260.42 + (397.3/2))/2070 = 0.22. 

Does that sound right? If so, maybe I need to recount my left offset. (Though I just rechecked this and it seems correct.).

I was doing the same for y, except I was multiplying the result by the aspect ratio of the image 1.38. Since the height of the image is longer than its width. The top offset is 233.5 and the height is 271 so for this I was getting ((233.5 + (271/2))/2862))*1.38 = 0.177

So this rectangle is spot on: new OpenSeadragon.Rect(0.14, 0.11, 0.143478, 0.143478);

But 0.22, 0.177 is just a little bit off.

I appreciate you babying me through this.

**Comment by philipgiuliani** [comment]
It seems that you calculated the center of the rect at x and y. You need the top left point of it.

**Comment by jeffreycwitt** [comment]
Maybe its the addition of half the the height and width that is causing the problem. X and Y components must refer to top right corner of rectangle rather than center.

**Comment by jeffreycwitt** [comment]
@philipgiuliani thanks, just figure that out :)
