### ISSUE TITLE
Distorted tile when rendering at lower zoom with DZI files

### ISSUE THREAD

**Issue by meihuisu** [openseadragon/openseadragon#647]
I am using openseadragon to display some dzi files and as new
user using very minimum configuration to have it running.

While trying it out, I have noticed that at the lowest zoom
level, the right most tile's image is distorted when rendered.
I have attached one that is zoomed out and the other that is
zoomed one level further in.

Perhaps I need to configure additional hints to openseadragon?

thanks,

mei

---------------------------------
![bad](https://cloud.githubusercontent.com/assets/9042455/7264715/b3336c36-e843-11e4-85f0-49f70bfd8669.png)
![good](https://cloud.githubusercontent.com/assets/9042455/7264718/b9ec1708-e843-11e4-8dda-b2b6baaff3e7.png)

**Comment by avandecreme** [comment]
How did you generate your dzi pyramid?
It looks similar to #234

**Comment by iangilman** [comment]
Indeed...looks like your tiles are padded rather than cropped. They need to be cropped instead.

**Comment by meihuisu** [comment]
Thanks for quick response. We have modified a tool that used to generate input files for Zoomify to
generate DZI files for Openseadragon instead. Looking at the code, it writes varying number of bytes into
each tile jpg files. 

----- Original Message -----

**Comment by iangilman** [comment]
Can you modify the tool to crop the tiles so there is no extra padding on edge tiles?

**Comment by meihuisu** [comment]
There is another tool earlier in the pipeline that creates tiled tif file that this
tool uses to generate the DZI files. It could be that the actual padding is done there. 
I need to check into that. Thanks. 


----- Original Message -----

**Comment by meihuisu** [comment]
I hand cropped couple of edge tiles and no more distortion. Thanks.

----- Original Message -----

**Comment by iangilman** [comment]
Good to hear :)

**Comment by iangilman** [comment]
We now have a potential fix for this, if it's still relevant to you: https://github.com/openseadragon/openseadragon/pull/1426

**Comment by meihuisu** [comment]
Thanks.  This opens up more option for accepting incoming data.
