### ISSUE TITLE
Lag between tilesource open event and tiles appearing

### ISSUE THREAD

**Issue by edsilv** [openseadragon/openseadragon#648]
Something I've noticed a lot when loading IIIF manifests from other domains is the lag between the tilesource open event being fired, and the tiles actually appearing.

I'm using the tilesource open event to hide a "please wait" spinner, but then there's often quite a wait until any images appear.

Is there another event I can listen for?

**Comment by iangilman** [comment]
You can use the `tile-drawn` event for that: 

```
var tileDrawnHandler = function(event) {
  viewer.removeHandler('tile-drawn', tileDrawnHandler);
  stopSpinner();
};

viewer.addHandler('tile-drawn', tileDrawnHandler);
```

**Comment by fgrs** [comment]
not quite a solution as this will get fired every time image is dragged around tho

**Comment by avandecreme** [comment]
Not with @iangilman's code because it removes the handler the first time the tile-drawn event is fired.
