### ISSUE TITLE
Determine the current tile source

### ISSUE THREAD

**Issue by r03ert0** [openseadragon/openseadragon#653]
Hello,
I'm displaying multiple .dzi images using an array for tileSources and the referenceStrip. On top of the .dzi images I'm using paper.js to draw annotations. I am saving the annotations to a database. How can I determine the url of the .dzi image that is currently displayed? I need that url to be able to associate specific annotations to their corresponding .dzi image.
thank you in advance!

**Comment by iangilman** [comment]
Keep track of your array of tileSources, and when you want to know what page you're looking at, use `viewer.currentPage()` to index into it.

**Comment by r03ert0** [comment]
thank you !

thanks to your response I found this method in the openseadragon website,
which I'm using now:

viewer.addHandler("page", function (data) {
            console.log(myParams.tileSources[data.page]);
        });

**Comment by iangilman** [comment]
Excellent :)
