### ISSUE TITLE
IIPImage and Openseadragon error:  Unable to open [object Object]: HTTP 0 attempting to load TileSource

### ISSUE THREAD

**Issue by softmasters** [openseadragon/openseadragon#654]
Hello,
I'm trying to display some images from IIPImage in Openseadragon using the deepzoom protocol.
I've setup a simple page with the viewer loading a single image, but I get the error in the subject.
If I call the url of the dzi manually, I get the following application/xml response, which seems correct:

```
<?xml version="1.0" encoding="UTF-8"?>
<Image xmlns="http://schemas.microsoft.com/deepzoom/2008"
TileSize="256" Overlap="0" Format="jpg"><Size Width="3680" Height="5520"/></Image>
```

This is the javascript used to configure Osd, where image is a .tif filename wih path (e.g.: /images/001/0001.tif):

```
        function loadPlayer() {
            viewer = OpenSeadragon({
                id: "container",
                prefixUrl:"images/" ,
                tileSources: server + "?DeepZoom=" + image + ".dzi"
            });
        }
        $(document).ready(function() {
            loadPlayer();
        });
```

May you help me please?
Thank you.

**Comment by iangilman** [comment]
I don't know enough about IIPImage to know the issue. Perhaps @jpstroop or @azaroth42 would know.

**Comment by azaroth42** [comment]
Not sure either. @softmasters, could you try the IIIF interface from IIPImage, rather than the DZI, and see if that works?

**Comment by softmasters** [comment]
Hello, thank you for your reply.
I'm not sure I can use the IIIF interface because I'm using IIPImage 0.9.9 stable in a production environment and this version does seem to support IIIF. IIIF is supported only in the development version.
A difference I've seen between my server's response and other examples on the web is that my server returns an inline response with application/xml mime type, whereas other examples return the response as a binary attachment. May this be the problem?

**Comment by terenceingram** [comment]
I had the same error. The issue is to do with cross site scripting. I downloaded a Chrome plugin to get around it for now. My plan is to have a proxy url within my app that then performs the IIP server query. Not sure if that helps or if you have sorted your problem by now.

**Comment by azaroth42** [comment]
Oh, if IIP isn't sending the right CORS headers, that would indeed be a problem. And not one that OpenSeadragon could solve.  Have you filed a bug against IIP for Ruven to fix?

https://github.com/ruven/iipsrv

**Comment by terenceingram** [comment]
@azaroth42 interesting point. I just assumed it's something that I had to work around. However, we don't publicly expose the IIP server, so my app has to have a proxy that openseadragon will query.

**Comment by terenceingram** [comment]
@azaroth42 I got the same problem when using a proxy locally in my app. The trick was to use a relative URL when declaring the tile sources i.e.

This didn't work - tileSources: "http://localhost:8080/myappath/images.dzi"
But this did - tileSources: "/myappath/images.dzi"

Not sure why.

**Comment by azaroth42** [comment]
I think an issue for @iangilman, if it still doesn't work with the CORS headers in place.

**Comment by iangilman** [comment]
If there is something we need to fix inside OSD, please let me know! I don't know enough about CORS to know what needs to be done, but if you provide a repro and info for a fix, we can make it happen. Even better, a patch! :)

**Comment by softmasters** [comment]
Hello,
I've setup a sample page where the problem occurs. Please let me know if you need anything further.
Thank you.

**Comment by softmasters** [comment]
Sorry, forgot the link: http://www.softmasters.net/iip.html

**Comment by iangilman** [comment]
@softmasters Thank you. So on that page I get `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://188.164.128.9/img?DeepZoom=/images/052/00001.tif.dzi. (Reason: CORS header 'Access-Control-Allow-Origin' missing).` Do you know that that server has the correct CORS header?

**Comment by softmasters** [comment]
@iangilman Indeed, the server wasn't sending a CORS header. I've configured the web server to send the header and now it's working.
Thank you for your precious help.
Regards.

**Comment by iangilman** [comment]
@softmasters Glad to hear you got it sorted out!

**Comment by peterlitvak** [comment]
I get the same problem with DZI files hosted on S3 that is enabled for web access and has CORS policy configured as follows:
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <ExposeHeader>ETag</ExposeHeader>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```
The web app itself runs on a separate EC2 host.
If I load the page with OSD (incognito mode) the first time it gives me the error described here if I refresh the page the viewer loads fine.
This is very strange, anyone observed anything like this?

**Comment by peterlitvak** [comment]
Actually I take it back it fails all the time if I don't have Chrome dev tools opened if I do it succeeds, this is really puzzling...

**Comment by peterlitvak** [comment]
Is there any special XHR configuration that OSD uses? Our app is AngularJS and we have to problems with any other XHR requests made by the app itself

**Comment by peterlitvak** [comment]
Ok, I think I found the problem. Will probably be useful to others who suffers the same issue.
Basically the XHR requests were getting cached so the solution is to add a random (GUID is the best) URL param to bust the cache

**Comment by peterlitvak** [comment]
Maybe makes sense to do it automatically in OSD itself for the tile source?

**Comment by peterlitvak** [comment]
Oh, yeah, and the reason it was working with dev tools open is that I had "Disable caching" ON there :)

**Comment by terenceingram** [comment]
@peterlitvak Thanks for adding your experience. Was the caching happening on the server side or in your angular app that is making the call? I don't know much about Angular but it's something I will keep in mind if we move away from our current platform.

**Comment by peterlitvak** [comment]
I think caching happens automatically in XHR, I've seen people complaining about the same issue (caching of XHR GET requests) with just JQuery apps.

**Comment by msalsbery** [comment]
It shouldn't be complained about. The server should use cache headers properly in responses.

Cache-busting should not be automatically done by OSD. If you can't count on your server/service to use cache headers properly and you want to make sure you get a fresh fetch from the server, _then_ you can use a nonce or whatever :)

**Comment by peterlitvak** [comment]
I'd imaging that S3 Web hosting handles headers just fine otherwise that would be a major problem, don't you think?

**Comment by leesei** [comment]
Are you accessing the image server in the same browser from two domains (say `localhost` and `prod.server`)?
You have to clear browser cache manually if this is the case.
