### ISSUE TITLE
Full width canvas with shadow

### ISSUE THREAD

**Issue by humbertorodrigues** [openseadragon/openseadragon#656]
Hi guys!

I would like to add a shadow to the image and set the canvas width to 100%. Do you have any idea how can I do it? I tryed to use the autoResize option and set the shadow to the div, however, the canvas is not resizing with the zoom

**Comment by iangilman** [comment]
You want to have the viewer fill the window? That should be as simple as setting the containing div to `width: 100%`. Or you want it to be full width but not full height? 

And you want a shadow on the viewer, or on the image within the viewer? The former should work just by putting a `box-shadow` on the containing div. The latter is trickier...you'd have to draw it into the canvas, and we don't currently have a mechanism for that. If you're interested in pursuing it, I can give you some pointers.

**Comment by qikkeronline** [comment]
@iangilman i'm looking to add a shadow to the image within the viewer; could you give me some pointers?

**Comment by iangilman** [comment]
I'd recommend using the https://github.com/altert/OpenSeadragonCanvasOverlay plugin, and drawing the shadow as appropriate with that.

Here's an example of how to draw a shadow with Canvas (code modified from http://www.html5canvastutorials.com/advanced/html5-canvas-shadow-offset-tutorial/):

```
<!DOCTYPE HTML>
<html>
  <head>
    <style>
      body {
        margin: 0px;
        padding: 0px;
      }
    </style>
  </head>
  <body>
    <canvas id="myCanvas" width="578" height="200"></canvas>
    <script>
      var canvas = document.getElementById('myCanvas');
      var context = canvas.getContext('2d');

      context.rect(188, 40, 200, 100);
      context.shadowColor = '#999';
      context.shadowBlur = 20;
      context.shadowOffsetX = 15;
      context.shadowOffsetY = 15;
      context.fill();
      context.clearRect(188, 40, 200, 100);
    </script>
  </body>
</html>      
```

To figure out where to draw the rectangle, you'll need to find the image bounds and convert them to pixels, something like so:

```
var image = viewer.world.getItemAt(0);
var bounds = image.getBounds(true);
bounds = viewer.viewport.viewportToViewerElementRectangle(bounds);
```

You also might want to adjust the width of the shadow blur based on how zoomed in you are:

```
var zoom = viewer.viewport.getZoom(true);
```

I hope that gets you started in the right direction... let me know if you have further questions!

**Comment by qikkeronline** [comment]
@iangilman thanks a lot; great pointers. I'm using https://github.com/altert/OpenseadragonFabricjsOverlay myself; so I'll use fabricJS to draw the rectangle. I was hoping for a solution that would draw the shadow on the actual openseadragon canvas; but I'm sure this will be sufficient as well 👍 thanks again!

**Comment by iangilman** [comment]
If you want to draw it on the actual OSD canvas, that's fine too... you would watch for `update-viewport` events and draw directly on viewer.drawer.canvas using the same technique described above.

Don't forget to share what you've built when it's ready! :)
