### ISSUE TITLE
Newbie Question - Image collection support

### ISSUE THREAD

**Issue by friarpat** [openseadragon/openseadragon#657]
First - is there a better place to drop questions for OpenSeaDragon?

Second - I've pulled the latest code from GIT and built it.  I attempted to load a dzc collection which there doesn't seem to be support for - just individual dzi's.  Is support for a dzc collection in GIT yet?  Maybe I'm missing what is considered a collection of images?  Is it what's implemented here?

https://openseadragon.github.io/examples/tilesource-collection/

I am trying to display a collection of dzi's (all different images) similar to what is in that tilesource-collection page.   Some images may be wider/narrower than others.   

Thanks in advance

**Comment by iangilman** [comment]
@friarpat Welcome! Here is a fine place for questions. 

As it happens, we've just released a major improvement to our multi-image support, which is a big step toward handling DZCs directly. Take a look here for info: 

http://openseadragon.github.io/examples/multi-image/

Unfortunately you can't yet load a DZC directly. The issue for that is #67. No one is working on it at this point; you're welcome to take a look if you'd like. 

On the other hand, if you just want to get your DZC displaying, it shouldn't be too hard to pull the DZI info out of the DZC and pipe that into OpenSeadragon. Basically you just want to load the info for each image out of the DZC and create an array of objects you can pass to `viewer.open()` in the "Inline Configuration for DZI" format shown here: 

http://openseadragon.github.io/examples/tilesource-dzi/

I know that may all be a bit much...let me know if you have questions!

**Comment by friarpat** [comment]
Thanks for the quick response - and the new release.   We'll see where this project takes me, but I may need to take you up on the offer to work on the DZC collection functionality. I'll play with the new functionality and see if that will be enough for now.    ...and yes, there may be another question or two!

**Comment by natelawrence** [comment]
Glad to see progress being made, Ian.

I was about to ask you about DZC support but this thread answers that question.
