### ISSUE TITLE
Remote DZI related question

### ISSUE THREAD

**Issue by friarpat** [openseadragon/openseadragon#658]
I've pulled the latest (2.0) version and was in the process of trying out the multi-image functionality using DZI files served by a web server (localhost, in this case).  I looked at issue #8 and https://github.com/thatcher/openseadragon/issues/21, for hints on how to handle the jsonp request.   Since I don't have the option to alter the DZI to be jsonp, I decided to try the inline configuration suggested on the examples/tilesource-dzi/  page.

The contents of the DZI xml file that I'm working with:

```
<?xml version="1.0" encoding="utf-8"?><Image TileSize="256" Overlap="1" Format="jpg" ServerFormat="Default" xmlns="http://schemas.microsoft.com/deepzoom/2009"><Size Width="3096" Height="1741" /></Image>
```

The viewer call that I'm using:

```
    var viewer = OpenSeadragon({
        id: 'foo',
        debugmode:false,
        prefixUrl: 'openseadragon/images/',
        tileSources: {
            Image: {
                xmlns: "http://schemas.microsoft.com/deepzoom/2009",
                Url: "http://localhost/StaticFilesApp/PSE~251A1120~DWG~0003~A_files/",
                Format: "jpg",
                Overlap: "1",
                TileSize: "256",
                Size: {
                    Height: "3096",
                    Width: "1741"
                }

            }
        }
    });
```

OpenSeaDragon loads the image - but:
a.) it sorta displays some of the image, but it doesn't look right
b.) in firebug, it's blowing all sorts of console errors fussing that it can't load specific tiles.   Example of one of the errors:

Tile [object Object] failed to load: http://localhost/StaticFilesApp/PSE~251A1120~DWG~0003~A_files/9/0_1.jpg

...and no, that jpg does not exist.

If I change the Viewer call to the following:

```
    var viewer = OpenSeadragon({
        id: 'foo',
        debugmode:false,
        prefixUrl: 'openseadragon/images/',
        tileSources: [
            { tileSource: 'http://localhost/StaticFilesApp/PSE~251A1120~DWG~0003~A.xml', x: 0, y: 5 }
        ]
    });
```

...everything displays fine, and FireBug has no errors.  Keep in mind that it's not an option to store the images locally - they will be accessed remotely and across different domains.

What am I doing wrong with the Image declaration?   Seems like that will be an acceptable solution if I can get it to calculate the tiles that it needs properly.

Thanks again!

**Comment by friarpat** [comment]
Trying the contents of that DZI xml file again: 

&lt;Image TileSize=&quot;256&quot; Overlap=&quot;1&quot; Format=&quot;jpg&quot; ServerFormat=&quot;Default&quot;
 xmlns=&quot;http://schemas.microsoft.com/deepzoom/2009&quot;&gt;&lt;Size Width=&quot;3096&quot; Height=&quot;1741&quot; /&gt;&lt;/Image&gt;

**Comment by iangilman** [comment]
Everything looks good, except you have your Width and Height transposed. 

And yes, using the inline configuration like this is the recommended way to deal with cross site issues.

**Comment by friarpat** [comment]
That was it. Argh!   

At the risk of hijacking my own thread...a couple of more questions which aren't popping out of the examples and documentation for me. 
I need to provide a menu/tree of the images that are displayed.   Click on an image - highlight the item in the tree.  Click on a tree item, pan/scroll to the appropriate image.   Along the same lines, I would need to provide right click functionality to present a context menu for an image.

a.)  How do I find out what image has been clicked?   

b.) Can I store metadata with the image or do I need to assign an ID that I can use to map to/from the tree?

c.) How do I go about extending the events to capture a right click (or in the case of gestures, something like a long press) to present a context menu for a specific image?

Thanks again.

**Comment by iangilman** [comment]
Cool, glad that fixed it. To answer your questions: 

a.) We don't yet have a "what image was clicked" function built in. You'll need to get the click location in viewport coordinates and compare it with all of the image bounds. Here is an example: 

```
viewer.addHandler('canvas-click', function(event) {
  if (!event.quick) {
    return;
  }

  var pos = viewer.viewport.pointFromPixel(event.position);
  var count = viewer.world.getItemCount();
  var i, box, tiledImage;
  for (i = 0; i < count; i++) {
    tiledImage = viewer.world.getItemAt(i);
    box = tiledImage.getBounds(true);
    if (pos.x > box.x && pos.y > box.y && pos.x < box.x + box.width && pos.y < box.y + box.height) {
      // this is the one! 
      break;
    }
  }
});
```

b.) It's JavaScript so there's nothing stopping you from saying `viewer.world.getItemAt(0).mySpecialProperty = 'whatever'`, but we don't have a special mechanism for that. I generally prefer to create my own structure outside of OpenSeadragon to keep track of my metadata, and then that structure includes links to the associated tiledImages. Either way is probably fine, though. 

c.) We don't have a right click event (actually I'm not sure exactly why... @msalsbery would know), but we do have press and release for the non-primary (i.e. right) button: 

http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#event:canvas-nonprimary-press

We also have primary press and release, which you could use to track long press. 

Btw, you might want to check out the "m2" demo, as it may have some ideas for what you're working on: 

https://github.com/openseadragon/openseadragon/tree/master/test/demo/m2
http://iangilman.com/osd/test/demo/m2/
