### ISSUE TITLE
2.0 issues with previously working onClick events and tileSources

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#660]
Many pages on my site utilize multiple tileSources, 
toggled by click(function) viewer.goToPage(<source number>)

This breaks on 2.0.  Example code pasted below.

Also, one page in particular has over 38 tileSources, but now appears to be loading all in a sequence or collection.  I tried setting suspect attributes to false.
Working page using 1.2.1:  http://deepzoomchattanooga.com/newspapers.php
Broken page using 2.0:  http://deepzoomchattanooga.com/newspapers_2.php

EXAMPLE CODE FOR THE CLICK FUNCTION (1.2.1 works - 2.0 broken):

```
    var viewer = new OpenSeadragon.Viewer({
      id:"openseadragon-canvas",
      prefixUrl: "/openseadragon/images/",
      toolbar:       "toolbarDiv",

      tileSources: [
        "/zoom/1979/dzc_output.xml",
        "/zoom/1979b/dzc_output.xml"
      ],

      nextButton:     "next",
      previousButton: "previous",
      fullPageButton: "full-page",
      showNavigator: true,

      defaultZoomLevel: 1.0,
      maxZoomPixelRatio: 2.5,
      controlsFadeDelay: 3500

    }
                       );

    $('.pg00').click(function() {
      viewer.goToPage(0);
    }
                    );
    $('.pg01').click(function() {
      viewer.goToPage(1);
    }
                    );
```

**Comment by avandecreme** [comment]
I think you now need to set sequenceMode to true.
See the release notes: https://github.com/openseadragon/openseadragon/releases/tag/v2.0.0

**Comment by SamHall** [comment]
Much appreciated.  That seems to have resolved both issues.

I guess I was confused in that setting it to 'true' seemed counter intuitive.
So sequenceMode is more of a 'there are multiple tileSources here' setting than it is directing how they are displayed?

Thanks again.
Sam

**Comment by iangilman** [comment]
@SamHall Sorry for the confusion! The default behavior now when you pass multiple tile sources is that they will all be displayed at once and that you are expected to lay them out however you want. If you want them to be displayed one at a time, you have to set sequenceMode to true. If you want them to be laid out automatically for you, you have to set collectionMode to true. If you don't set either of those to true, you can lay them out however you want, for example: 

http://iangilman.com/openseadragon/flickr/
