### ISSUE TITLE
reference strip not working?

### ISSUE THREAD

**Issue by hmeine** [openseadragon/openseadragon#663]
Hi, I have just looked at OpenSeaDragon for the first time, yet I tried three different browsers, and with none of them https://openseadragon.github.io/examples/ui-reference-strip/ seemed to work. I expect there to be an obvious possibility to change between different images, but I only see this (no difference between horizontally and vertically configured examples):
![screenshot of what I see](https://cloud.githubusercontent.com/assets/462802/8108923/ddef8242-1053-11e5-86c1-937cfe2870d3.png)

The good news is that it shows exactly the same in all three browsers. ;-)

**Comment by iangilman** [comment]
@hmeine Thanks for spotting this! Now with OpenSeadragon 2.0.0 the reference strip doesn't work without `sequenceMode: true`. I've now updated that page with fixed code and new info. It should be working now.
