### ISSUE TITLE
'display: none' gets reset on overlays on drawHTML()

### ISSUE THREAD

**Issue by ricochet2200** [openseadragon/openseadragon#667]
There does not seem to be a way to properly hide overlays.  I am able to hide the `div` I created for the overlay, but as soon as I pan or zoom it gets displayed again.

I have narrowed this behavior to the following line in drawerHTML() in overlay.js:285:

style.display  = 'block';

My guess that the intent of this line is to make sure things aren't displayed `inline` or something other than `block`.  However, it would be nice if that line were skipped if  `style.display = 'none';`  Is there a reason the code is as written, or can it be changed to preserve hidden overlays.

Thanks!

**Comment by iangilman** [comment]
Fixed by #668
