### ISSUE TITLE
Non-square tiles

### ISSUE THREAD

**Issue by MereHappyJaZZ** [openseadragon/openseadragon#670]
Hi all,

I wonder if OpenSeadragon somehow support non-square tiles? So far I can only find a single keyword describing tilesize in the API. Even the "getTileSize" function seems to only return a single number.

https://openseadragon.github.io/docs/OpenSeadragon.TileSource.html#getTileSize

Any ideas on wether it is possible? I make my own tilesources (in the DZI style), but it would make life easier if tiles were not constricted to being square.

Thanks!

**Comment by iangilman** [comment]
Yes, OpenSeadragon always assumes tiles are square (except for edge tiles of course, which may be cut off partially). 

How would non-square tiles makes life easier for you?

**Comment by MereHappyJaZZ** [comment]
I'm stitching collections of microscope images (in regular arrays), which by default are in 4:3 ratio. If tiles could be non-square, my deepest level of the tileSource could be the raw images, and then simply generate the other levels by pasting four adjacent images and do a 1:2 resizing. 

I got working code as it is, but It would save a lot of processing if the highest level didn't need any further processing, due to the log2 nature of the image pyramids. 

Thanks for the input though!

**Comment by iangilman** [comment]
Cool, makes sense. 

The assumption that tiles are square is pretty deeply embedded in the code, and adding non-square tiles would add a good deal of complexity I think, so I think we should keep it as it is.

**Comment by MereHappyJaZZ** [comment]
Fair enough =)
I'll keep an eye on the code, maybe it changes in the future! 

Thanks for the effort!

**Comment by iangilman** [comment]
@MereHappyJaZZ As it turns out, someone has just submitted a pull request for this self-same feature: #673
