### ISSUE TITLE
Tainted Canvas Prevents Getting ImageData

### ISSUE THREAD

**Issue by aeschylus** [openseadragon/openseadragon#671]
I am attempting to extract pixels for an experimental aural representation of IIIF resources. I cannot seem to extract the pixel data from the canvas despite cross origin being allowed (or else the requests wouldn't finish in the first place). It seems possible to get around this by filtering the actual image requests and [setting the crossorigin property](http://stackoverflow.com/a/19869402/564684) on the way to the canvas. I can probably test this, but just wanted to record it here in case others wanted to discuss the approaches and implications of this.

```
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at Error (native)
    at <anonymous>:2:3
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

**Comment by avandecreme** [comment]
> despite cross origin being allowed (or else the requests wouldn't finish in the first place)

That is not true. Cross origin is always allowed for images but the images get tainted preventing you from reading it content from javascript.
If the server hosting your pyramid has CORS enabled, you can set crossOriginPolicy to "Anonymous". See https://openseadragon.github.io/docs/OpenSeadragon.html

**Comment by aeschylus** [comment]
Aha! I will try out this option. Very nice to see that this has been thought of. I will test this today to verify that this ticket is indeed superfluous.

**Comment by aeschylus** [comment]
Setting to anonymous did not resolve the issue. I still need to test this with some different CORS headers on the server, but I am fairly sure this is a bug.

**Comment by iangilman** [comment]
Cool...if there's something we can do inside OSD to fix it, please let us know. I don't know enough about CORS to recommend any course of action.

**Comment by iangilman** [comment]
@aeschylus Any word on what we need to do in OSD to fix this?
