### ISSUE TITLE
How to override sequence functions.

### ISSUE THREAD

**Issue by osk386** [openseadragon/openseadragon#676]
Hi, I just want to know how can I hide the original sequence (next, back) controls and use my own controls.

I'm going to use a slider so I need to do this.

So the question is, exist any way to simply call a function to call the next image in sequence.

Thank you

**Comment by avandecreme** [comment]
> I just want to know how can I hide the original sequence (next, back) controls and use my own controls.

You need to set showSequenceControl to false: http://openseadragon.github.io/docs/OpenSeadragon.html#Options

>So the question is, exist any way to simply call a function to call the next image in sequence.

Yes, you need to use viewer.goToPage and viewer.currentPage methods

http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#goToPage
http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#currentPage

**Comment by osk386** [comment]
Thanks a lot, this works perfectly.
