### ISSUE TITLE
Progressively Enhance to WebGL When Available

### ISSUE THREAD

**Issue by natelawrence** [openseadragon/openseadragon#68]
Without [Deep Zoom Collections support](https://github.com/openseadragon/openseadragon/issues/67), this is less necessary, but given that they are implemented in the future I'd love to see the original ability to arbitrarily filter/reorganize/spatially arrange a Deep Zoom Collection in hardware accelerated 3D space.

Until this happens, you're not real Seadragon... and yes, I'd also say this to Silverlight Deep Zoom's face.

Basically, I'm looking for you to get to the point where it is trivial to add point cloud rendering and hook into [the Photosynth webservice](http://photosynth.net/photosynthws/PhotosynthService.asmx) and implement [a few transition options and camera coordinates to match the Photosynth viewer Javascript API](http://photosynth.net/api/docs/default.html) and have a WebGL Photosynth viewer that rivals the original Direct3D Photosynth viewer.

Also, given that the original Seadragon application was written in OpenGL, this would be a fitting tribute.

Bonus points if you get the original text browsing demos to work (with a DZI for thumbnails and live queryable/copyable/pastable HTML text) and give people a simple set of tools for apps that render to a Seadragon viewer like the Mandelbrot set browser in the original Seadragon demos.

**Comment by iangilman** [comment]
Possibly relevant to this issue, @karin-toth posted in https://github.com/openseadragon/openseadragon/issues/1683#issuecomment-574162070 a link to her stab at a WebGL renderer for OpenSeadragon:

https://github.com/karin-toth/openseadragon/tree/kato-webgl

Her comments:

> I've been working on a webGL renderer for quite some time now, but as many other things, it's more complex that it seems. I got something to work, but taking it from a seems to work-state to the type of fail-safe production code that is required takes more time than I thought. So I would have loved to contribute, but I just don't have the time to complete this.
> 
> I'm of course open for answering questions and other help in the future if someone wants to continue.

**Comment by iangilman** [comment]
Guess what? This is now fixed, by https://github.com/openseadragon/openseadragon/pull/2310!

**Comment by petersibley** [comment]
Great to see this closed all these years later. It looks like the refactoring in that PR, would make adopting something like webGPU or other lower level APIs -  a lot easier in the future.

**Comment by iangilman** [comment]
@petersibley Absolutely! It's good to have the drawer architecture opened up like this. @pearcetm did a great job!

**Comment by iangilman** [comment]
BTW, as @pearcetm points out, #2310 doesn't implement everything suggested in this issue, but it certainly opens the door for it. If there are any particular items of interest in here that we want to pursue next, let's file new issues for them.
