### ISSUE TITLE
Rotation works improperly on retina display (device pixel ratio != 1.0)

### ISSUE THREAD

**Issue by serge-markin** [openseadragon/openseadragon#683]
Hi,

I discovered this issue only after migrating to Retina Macbook Pro. Looks like something is wrong with rotation function. Centre of rotation is shifted.

If I change device pixel ratio in Chrome emulation settings to 1.0 from 2.0 rotation works properly.

Issue can be reproduced on non-retina display by setting device pixel ratio to 2.0 in chrome device emulation setting.

Thank you.

Regards,
Serge.

**Comment by iangilman** [comment]
Good catch! Presumably we need to introduce `$.pixelDensityRatio` into: 

https://github.com/openseadragon/openseadragon/blob/master/src/drawer.js#L489-516

Would you be up for giving it a try?

**Comment by serge-markin** [comment]
Yes, I will try to fix it. Thanks for pointing to exact location.
Going to fork and create pull request after fix.

**Comment by iangilman** [comment]
Excellent, thank you!

**Comment by serge-markin** [comment]
I just created pull request https://github.com/openseadragon/openseadragon/pull/707

**Comment by serge-markin** [comment]
Sorry, first pull request was wrong. Ignore that.

**Comment by iangilman** [comment]
Fixed by #708
