### ISSUE TITLE
Publish to the npm registry

### ISSUE THREAD

**Issue by Emigre** [openseadragon/openseadragon#686]
Somebody might want to install OpenSeadragon with npm.

**Comment by iangilman** [comment]
Indeed. I suppose when we do it we should make it clear that it's still only a client side library (since npm hosts a lot of server side libraries). 

Note that we do already support Bower.

**Comment by dzucconi** [comment]
+1 Would very much like to do this (using Browserify)

**Comment by iangilman** [comment]
@dzucconi Thanks for the vote! Btw, @Emigre just added AMD module support (https://github.com/openseadragon/openseadragon/pull/719); hopefully that will work with Browserify.

**Comment by homerjam** [comment]
+1

Also the AMD module support (#719) hasn't yet made it on to Bower BTW

**Comment by iangilman** [comment]
Yes, #719 will come with the OpenSeadragon 2.1.0 release.

**Comment by avandecreme** [comment]
Looks like we should really focus on that now that [bower is no longer maintained](https://twitter.com/nachocoloma/status/663622545162280960).

**Comment by iangilman** [comment]
@avandecreme Whoa. Ok, I've added it to the 2.1.1 milestone so we don't forget it. I think it's not too hard...just a matter of getting around to it.

**Comment by avandecreme** [comment]
Here is the doc on how to publish: https://docs.npmjs.com/getting-started/publishing-npm-packages
My understanding is that we should add a package.json inside build/openseadragon (or a copy of it to not interfere with the zip building) and then run `npm publish`.
This package.json should contains the version number.

I can start a PR for that and let you publish once merge.

**Comment by homerjam** [comment]
I think you can use the package.json at the route and ignore the source
files using glob syntax so only the build files are published. I think
that'd be easier and less confusing than maintaining two separate
package.json files.

**Comment by avandecreme** [comment]
Good point on using only one package.json.
I am not sure about using globs to ignore source files.

Wouldn't that require people to do things like
```
<script src="node_modules/openseadragon/build/openseadragon/openseadragon.js"></script>
```
instead of
```
<script src="node_modules/openseadragon/openseadragon.js"></script>
```

**Comment by homerjam** [comment]
Right now thats exactly what I'm doing:

```
bower_components/openseadragon/built-openseadragon/openseadragon/openseadragon.js
```

Once on npm and after adding the appropriate code to export the module anyone using browserify/webpack should be able to do:

```
require('openseadragon');

**Comment by iangilman** [comment]
@avandecreme Thank you for taking this on! 

I'm wondering if this should be in site-build, since that's where we keep the latest official build.

**Comment by iangilman** [comment]
@Emigre Good to know!

**Comment by avandecreme** [comment]
I made a PR about that: #781 
If any one has experience with npm publishing, please review :)

**Comment by iangilman** [comment]
And published! 

http://npmjs.com/package/openseadragon

Thank you @avandecreme for the PR!
