### ISSUE TITLE
How to change tilesource AND THEN zoom to boxed region?

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#688]
This is a JQuery question -  
I can target click classes to switch tilesources or zoom to a boxed region on the currently displayed tilesource, but cannot manage to have both done in succession.

``` javascript
$('.pg00').click(function() {
    viewer.goToPage(0);
  });

$('.loc1').click(function() {
    viewer.viewport.fitBounds(box1);
  });
```

I've searched and tried many combinations but cannot seem to get it functioning - and would greatly appreciate what is likely a simple answer.

Thank you,
Sam

**Comment by avandecreme** [comment]
You might need to do something like this:

```javascript
$('.button').click(function() {
   viewer.addHandler('open', openHandler);

   function openHandler() {
      viewer.removeHandler('open', openHandler);

   }
});
```

**Comment by iangilman** [comment]
Well, as of 2.0.0 it doesn't create a new viewport, but it does reset the viewport. Another option would be to use the `preserveViewport` option when you create the viewer.
