### ISSUE TITLE
Question: Implementing Custom Tile Source

### ISSUE THREAD

**Issue by susanmonnelly** [openseadragon/openseadragon#690]
I'm new to  OpenSeadragon and have been trying to implement a custom tile source implementation.  We  have our own service that will cut up images into tiles and return them in a json format.

I discovered that if I set the tileSources to the json request url then the getImageInfo method is called.   But I am getting an error that the No TileSource was able to open this request. 
Here's my request:
`
      var viewer = OpenSeadragon({
                id: "openseadragon1",
        toolbar: "toolbarDiv",
               constrainDuringPan: true,
               visibilityRatio: 1,
               prefixUrl: "/scripts/images/",
           showRotationControl: true,
               tileSources: tile_json_request
      });
`

How would I be able to set the TileSource data type?   I have an implementation of TileSource that I think may work but when the code hits my "supports" method the data type is null.   How would I set that data type in the above situation?    Or am I trying to implement this incorrectly?

I've also tried to implement my own TileSource and initialize it like this:

`
var viewer = OpenSeadragon({
        id: "openseadragon1",
    toolbar: "toolbarDiv",
        constrainDuringPan: true,
        visibilityRatio: 1,
        prefixUrl: "/scripts/images/",
    showRotationControl: true,
     tileSources: [{
        type: 'nbtileservice',
        width: srcWidth,
            height: srcHeight,
            tilesUrl: tile_json_request
     }]
});
`

And I was able to get the 'supports' and 'configure' to fire but the 'getImageInfo' request would not fired.   If this is the path I should take to make this work then I will focus on that and post that code.

Thanks for any help you can offer.

Susan

**Comment by avandecreme** [comment]
Have you considered using this: http://openseadragon.github.io/examples/tilesource-custom/ ?
You would just need to implement the proper `getTileUrl` function.

@iangilman & @ConnerMan  With the new non square tiles support, has the tileSize parameter be changed to tileWidth and tileHeight in this use case? I believe the doc will need to be updated if that is the case.

**Comment by susanmonnelly** [comment]
Yes I have used `getTileURL` and that works okay but since your documentation suggests other solutions that appear cleaner, I would like to implement them that way.  Meaning instead of making our ajax request outside of the OpenSeadragon setup, I would like to implement it as is described here: https://openseadragon.github.io/docs/OpenSeadragon.TileSource.html

**Comment by iangilman** [comment]
@susanmonnelly To have your "supports" method called, you have to have made a class that extends TileSource and that is attached to the OpenSeadragon namespace with a name that ends in "TileSource", e.g. `OpenSeadragon.MyCoolTileSource`. Have you done this? If so, and your "supports" method is getting called with null data, sounds like there is something happening with the retrieval code in getImageInfo. I'd be happy to take a look if you want to post a link to your project. 

@avandecreme good point about that example page. With the new code, using tileSize as a parameter will still work, but we might as well add mention of tileWidth/tileHeight. I've started a ticket for this:

https://github.com/openseadragon/site-build/issues/76

**Comment by susanmonnelly** [comment]
Thanks @iangilman.

Here's my TileSource implementation.  I've put console.log statements in the code as you can see and I am not seeing the getimageinfo fire or the gettileurl.   'supports' and 'configure' are fired.

 I kind of stole it from the OSD code where the TmsTileSource is defined:


```
(function( $ ){

  /**
   * @class NBTileSource
   * @classdesc A tilesource implementation for NewsBank.
   *
   * @memberof OpenSeadragon
   * @extends OpenSeadragon.TileSource
   * @param {Number} width - the pixel width of the image.
   * @param {Number} height
   * @param {Number} tileSize
   * @param {String} tilesUrl
   */
  $.NBTileSource = function( width, height, tileSize, tilesUrl ) {
    var options;
    console.log('NBTileSource function ');

    if ( $.isPlainObject( width ) ){
        options = width;
    } else {
      options = {
        width: arguments[0],
        height: arguments[1],
        tileSize: arguments[2],
        tilesUrl: arguments[4]
      };
    }

    numTiles= new Object();
    numTiles.x = srcWidth % options.tileSize == 0 ? srcWidth/options.tileSize : Math.floor(srcWidth/options.tileSize) + 1 ;
    numTiles.y = srcHeight % options.tileSize == 0 ? srcHeight/options.tileSize : Math.floor(srcHeight/options.tileSize) + 1 ;

    options.width = numTiles.x*options.tileSize;
    options.height = numTiles.y*options.tileSize;
    options.maxLevel = 1;
    options.tileSize = 256;

    console.log('NBTileSource this ' + this);
    console.log('NBTileSource options.tilesUrl ' + options.tilesUrl);
    $.TileSource.apply( this, [ options ] );

  };

  $.extend( $.NBTileSource.prototype, $.TileSource.prototype, /** @lends OpenSeadragon.NBTileSource.prototype */{

    /**
     * Determine if the data and/or url imply the image service is supported by
     * this tile source.
     * @function
     * @param {Object|Array} data
     * @param {String} optional - url
     */
    supports: function( data, url ){
      console.log('NBTileSource supports ' + data.type); 
      return ( data.type && "nbtileservice" == data.type );
    },

    /**
     *
     * @function
     * @param {Object} data - the raw configuration
     * @param {String} url - the url the data was retreived from if any.
     * @return {Object} options - A dictionary of keyword arguments sufficient
     *      to configure this tile sources constructor.
     */
    configure: function( data, url ){
      console.log('NBTileSource configure ' + data.tilesUrl);
      return data;
    },


    /**
     * @function
     * @param {Number} level
     * @param {Number} x
     * @param {Number} y
     */
    getTileUrl: function( level, x, y ){
      console.log('NBTileSource getTileUrl ');
      id =  'tile_' + x + '_' + y + '_' + (level);
      console.log('id' + id);
      console.log('tileLocations[id.toUpperCase()] ' + tileLocations[id.toUpperCase()]);
      return tileLocations[id.toUpperCase()];
    },          
    // /**
    //  * @function
    //  * @param {Number} level
    //  * @param {Number} x
    //  * @param {Number} y
    //  */
    getImageInfo: function (data) {
      console.log('NBTileSource getImageInfo ' + data);
      $.ajax({ 
        url: data.tilesUrl, 
        dataType: "json",
        async: true,
        success: function(data, text) {
          for (var tile in data.tiles) {
            tileLocations[tile] = data.tiles[tile];     
          } 
        },
        error: function(request, status, error) {
          alert("Error : " + request.responseText + "\n" + status + "\n" + error);
        }
      });
    }
  });
}( OpenSeadragon ));

```

**Comment by iangilman** [comment]
Looks reasonable to me. After "supports" you should get the "NBTileSource function" log...is that happening?

**Comment by susanmonnelly** [comment]
Yes - it is.

When I look at the OSD code,  it looks like the getImageInfo method will only fire when the first argument is a string.   Here's the code from version 1.2

```
console.log(arguments[ 0 ]);
    if( 'string' == $.type( arguments[ 0 ] ) ){
        //in case the getImageInfo method is overriden and/or implies an
        //async mechanism set some safe defaults first
        this.aspectRatio = 1;
        this.dimensions  = new $.Point( 10, 10 );
        this.tileSize    = 0;
        this.tileOverlap = 0;
        this.minLevel    = 0;
        this.maxLevel    = 0;
        this.ready       = false;
        //configuration via url implies the extending class
        //implements and 'configure'
        this.getImageInfo( arguments[ 0 ] );

    } else {
```
That indicates that the tileSources parameter needs to be a string in order for getImageInfo to fire.   

How is that accomplished in this scenario?

**Comment by iangilman** [comment]
You don't need getImageInfo to fire on your NBTileSource...the way the system works is when you pass in a URL to the `tileSources` option, a generic TileSource is created with that URL and its getImageInfo is called to load the data. Once that data is loaded it's passed through the `supports` of all the available TileSource subclasses (including NBTileSource), and when a match is found, a new object is created (in this case an NBTileSource) and the data is passed into it. 

Do you have this code running anywhere I can look at?

**Comment by susanmonnelly** [comment]
interesting  -  I have a console.log statement in the getimageinfo in the OSD code and I don't see that happening.   From what you are saying the getImageInfo method is called before supports.   I will debug the OSD code to see if I can find the issue.     I can't make the code available because we are developing behind a firewall.

**Comment by iangilman** [comment]
That's assuming you're still using `tileSources: tile_json_request` and that `tile_json_request` is a URL to some data. At any rate, that's my reading of https://github.com/openseadragon/openseadragon/blob/master/src/tilesource.js#L409-L431

**Comment by susanmonnelly** [comment]
I'm somewhat confused now.   If I define tileSources as you describe, then I how do I define the 'type' for `supports` ?  This is how 'supports' was passing.

```
	    tileSources: [{
	    	type: 'nbtileservice',
	      width: srcWidth,
        height: srcHeight,
        tilesUrl: tile_json_request
	    }]

```

I can hardcode my 'supports' method to return true to get around that issue.

So if getImageInfo is used by setting TileSources to the json request, why doesn't getTileUrl fire?

**Comment by iangilman** [comment]
Gotcha. Sure, you can specify the data directly, and then you don't need to worry about getImageInfo. If you did go the getImageInfo route (by specifying a JSON URL), the JSON that gets returned would have to include the `type` property in order for `supports` to work. 

At any rate, I think we're on the same page now...sorry for the confusion. So the remaining mystery is why doesn't getTileUrl fire. Unfortunately everything looks good to me, so I'm not sure why it isn't. Have you tried swapping in something like a dzi tilesource (there are some sample files in the OpenSeadragon repository) to make sure it's loading? 

I suppose one way to look is to start from where getTileUrl is called and figure out why the code isn't getting there: 

https://github.com/openseadragon/openseadragon/blob/master/src/tiledimage.js#L988

Of course you can also take a look at the resulting tiled image and make sure it's properly positioned in the viewport and that the contents of its `source` property look like the NBTileSource you're looking for. 

Sorry this is proving to be challenging! We don't get a lot of people writing new tile sources...

**Comment by susanmonnelly** [comment]
So with the help of a colleague,  we have solved the issue for our custom tile source implementation.  
We set tileSources in the OpenSeadragon declaration to be my custom TileSource object like this:
```
var myTileSource = new OpenSeadragon.NBTileSource(srcWidth, srcHeight, tileSize, tile_json_request);
	   
var viewer = OpenSeadragon({
        id: "openseadragon1",
	toolbar: "toolbarDiv",
        constrainDuringPan: true,
        visibilityRatio: 1,
        prefixUrl: "/scripts/images/",
  	showRotationControl: true,
	tileSources: myTileSource
     });
  });

```
Then in the constructor of my TileSource, I  explicity calling getImageInfo. 

```
  $.NBTileSource = function( width, height, tileSize, tilesUrl ) {
    var options;
    console.log('NBTileSource function ');

.... do some other stuff here ...

    this.getImageInfo( tilesUrl );
    $.TileSource.apply( this, [ options ] );

  };
```

It seem like  OpenSeadragon should allow getImageInfo to be triggered in this kind of situation.  It appears that getTileURL and getImageInfo are mutually exclusive.   But perhaps I'm misunderstanding  the use of these methods.

**Comment by iangilman** [comment]
Ah! I'm sorry I didn't see this before...you're overriding getImageInfo, so of course it's not behaving the way I expect it to. `configure`, `supports`, `getTileUrl` are all expected to be overridden, but `getImageInfo` is not. 

It looks like part of the confusion is that you have potentially two files that you need to load? One for the width/height/tilesize and one with the tile locations? Can those be combined into a single call to the server? If not, what you're doing seems to work, so you can run with it. You might want to change the name of your `getImageInfo` because its purpose is different than the built in `getImageInfo` (i.e. yours gets secondary info, whereas the built in one is for getting primary info). 

Anyway, glad you found something that works; apologies for not noticing the issue sooner!

**Comment by susanmonnelly** [comment]
Well I wasn't overriding getImageInfo before.  This is what I was required to do in order for things to work.  As I said in my last comment, when I set ` tileSources: "url_string" ` then getImageInfo would fire but getTileUrl would not.   Is there something else I need to send back in the json request for getTileUrl to fire when using getImageInfo ?

**Comment by iangilman** [comment]
Well, if what you've got works, you can just run with it. That said, if you want to try to get to the bottom of this, I'm happy to help. 

If you don't override getImageInfo, then it should do the sequence I outlined in https://github.com/openseadragon/openseadragon/issues/690#issuecomment-126391633. The data it fetches needs to be whatever you're going to need for your tilesource, including whatever identifying information your `supports` will need to know that it's the right kind of tilesource. If you then need to make an additional call for additional information, you can write your own helper function for that (that doesn't override getImageInfo). This all assumes you're creating the OpenSeadragon viewer with `tileSources: someDataUrl`.

Am I correct in thinking that you have to make two calls to the server to get the info you want? If you have any control over that, it would be great to get it down to one call. 

For that matter, I generally find being able to load the data myself however I need (perhaps batched with other images or with metadata) and then pass that into OpenSeadragon, much like you are with your latest, is actually quite a good way to go. 

Anyway, it's a pretty flexible system, so I'd say the solution you have is reasonable, assuming it's just for use in your project. If you were planning on publishing this tilesource as an OpenSeadragon plugin, I'd probably want to clean its API up a little so people can be flexible about how they use it.

**Comment by susanmonnelly** [comment]
I would like to get to the bottom of the problem and I appreciate the help.  

I did try what you suggested and I could not get the getTileUrl to fire.   I only need to make one request to the server to get the data which is using that 'tiles_json_request'.  It brings back the data looking like this:

```

{"imageserver":{"tiles":{"tile_0_0_0":"http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_0_0_0.5_256.jpg","tile_1_0_0":"http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_512_0_0.5_256.jpg","tile_0_0_1":"http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_0_0_1_256.jpg","tile_0_1_1":"http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_0_256_1_256.jpg","tile_1_0_1":"http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_256_0_1_256.jpg","tile_1_1_1":"http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_256_256_1_256.jpg","tile_2_0_1":"http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_512_0_1_256.jpg","tile_2_1_1":"http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_512_256_1_256.jpg","tile_3_0_1":"http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_768_0_1_256.jpg","tile_3_1_1":"http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_768_256_1_256.jpg"}}}

```
And I can add more data to that request as needed so I could add the supports info to it if that is what is needed.   But you can see I have the tile paths for each zoom level and each tile location which I then calculate in the getTileURL function like so:

```
    getTileUrl: function( level, x, y ) {
      id =  'tile_' + x + '_' + y + '_' + (level);
      return this.tileLocations[id];
    }   
```

Clearly I'll need to access the data structure differently than this function is with the tileLocations array but I'm not even getting far enough to see getTileUrl to fire.    But you say it should just happen correct?

**Comment by iangilman** [comment]
Well, I played with the code in this thread to see what I could make happen. I don't know the details of your format, and the URLs you gave don't seem to work (at least outside your network), but I got all the right things to fire. 

I went with specifying the data directly, rather than loading from JSON, since it's more flexible and potentially more efficient. Here is the data I used: 

```
var data = {
  type: 'nbtileservice',
  width: 1000,
  height: 1000,
  tileLocations: {
    tile_0_0_0: 'http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_0_0_0.5_256.jpg',
    tile_1_0_0: 'http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_512_0_0.5_256.jpg',
    tile_0_0_1: 'http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_0_0_1_256.jpg',
    tile_0_1_1: 'http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_0_256_1_256.jpg',
    tile_1_0_1: 'http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_256_0_1_256.jpg',
    tile_1_1_1: 'http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_256_256_1_256.jpg',
    tile_2_0_1: 'http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_512_0_1_256.jpg',
    tile_2_1_1: 'http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_512_256_1_256.jpg',
    tile_3_0_1: 'http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_768_0_1_256.jpg',
    tile_3_1_1: 'http://ihw10.newsbank.com/cache/ean/display/105661d58ddc5fd5/tile_105661d60a0f265a_768_256_1_256.jpg'
  }
};
```

...and I just passed it into the viewer upon creation like so: 

```
  tileSources: data
```

Here is my version of the NBTileSource code (with comments removed for brevity): 

```
OpenSeadragon.NBTileSource = function( options ) {
  console.log('NBTileSource function ');

  options.tileSize = 256;
  options.maxLevel = 1;

  var numTiles= {};
  numTiles.x = options.width % options.tileSize == 0 ? options.width/options.tileSize : Math.floor(options.width/options.tileSize) + 1 ;
  numTiles.y = options.height % options.tileSize == 0 ? options.height/options.tileSize : Math.floor(options.height/options.tileSize) + 1 ;

  options.width = numTiles.x*options.tileSize;
  options.height = numTiles.y*options.tileSize;

  console.log('NBTileSource this ' + this);
  console.log('NBTileSource options.tilesUrl ' + options.tilesUrl);
  OpenSeadragon.TileSource.apply( this, [ options ] );
};

OpenSeadragon.extend( OpenSeadragon.NBTileSource.prototype, OpenSeadragon.TileSource.prototype, {
  supports: function( data, url ){
    console.log('NBTileSource supports ' + data.type);
    return ( data.type && "nbtileservice" == data.type );
  },

  configure: function( data, url ){
    console.log('NBTileSource configure ' + data.tilesUrl);
    return data;
  },

  getTileUrl: function( level, x, y ){
    console.log('NBTileSource getTileUrl ');
    id =  'tile_' + x + '_' + y + '_' + (level);
    console.log('id' + id);
    console.log('tileLocations[id] ' + this.tileLocations[id]);
    return this.tileLocations[id];
  }
});
```

Btw, what's the deal with `numTiles` and changing the width/height? Because it needs to be an even multiple of tiles?

**Comment by susanmonnelly** [comment]
Thanks Ian.

It looks like we have a bit of a disconnect.    You created the  structure that contains the JSON data.   I was hoping that OpenSeadragon would make the JSON request to retrieve the data with its getImageInfo method and then call the supports, configure and getTileUrl methods like you have defined.    Perhaps that is not how things work and I'm trying to do something that's not possible.

The deal with `numTiles` is that our Tile service returns the tiles in even numbered tiles based on the tile size requested.  So it fills in the edges of an image with a background color when those tiles are not the exact  size of the tile.   Does that make sense?   We probably need to adjust our Tile service to send back the odd sized tiles on the edges since OpenSeadragon will handle that scenario.

Also the reason those images are not available is because we create the tiles dynamically when the JSON request is made and they are  cached them for about three days.   We have a very, very large number of historical documents so this is most efficient for us.

**Comment by iangilman** [comment]
The code above should be able to handle the JSON request version as well, assuming the result from the JSON request matches the contents of the `var data` above, then you would just initialize your viewer with: 

```
  tileSources: 'http://foo.com/data.json'
```

...or whatever. Otherwise no change needs to be made to the NBTileSource. 

Thanks for explaining the numTiles thing. If your service can produce partial tiles, OSD is fine with that. If you need to go with the padding, that's fine too, and OSD can even crop it on the client side if you want (though you'll have to do some math).

**Comment by susanmonnelly** [comment]
@iangilman you mentioned in the previous comment that "OSD can even crop it on the client side".   How would I do that with OSD?   These are tiles that are padded on the image edges to create even sized tiles and I need to undo that.

**Comment by iangilman** [comment]
Take a look at the `clip` parameter for `Viewer.addTiledImage()`: 

http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#addTiledImage

You can also use the same parameter in `Viewer.open()` or in the `tileSources` option when creating the Viewer.

**Comment by linruicheng1997** [comment]
Is there any back-end source code, or is there no need for back-end source code?

**Comment by iangilman** [comment]
@linruicheng1997 OSD does not require any backend... You can use it on a purely static site. The DZI format is just XML and standard image tiles (often JPG), so any web server should be able to serve them.
