### ISSUE TITLE
Wrap in UMD

### ISSUE THREAD

**Issue by Emigre** [openseadragon/openseadragon#691]
The application could be rewritten using UMD modules.

It could still be used as a browser global but this way it would also work as CommonJS or AMD. Require.js users could require it instead of having to write a shim.

I could do this in a fork, if this is something that we would like to attempt. I feel like trying it. : )

**Comment by iangilman** [comment]
I don't think we want to convert over to UMD internally, but I'd be interested to know what's involved in making OSD easily plug into things like require.js.

**Comment by Emigre** [comment]
When using an UMD module the module returns a different type of module depending on what you are using to require it, so internally the project would still be relying on a browser global, and a user that added the library with a `<script>` tag in the header would receive a browser global too. But a user that required the library with Require.js or Browserify, on the other hand, would receive an AMD module or an CommonJS module instead, which is the useful thing about it.

Internally this would involve changing this...
```javascript
(function( $ ){
  // ...
}( OpenSeadragon ));
```
...with the slightly longer UMD version, and setting up the dependencies inside the project.

I guess you could instead surround everything with an UMD wrapper after the concat step in the build, there are plugins that do it. I think the bad side of that would be that in your project you would not be stating internal dependencies of a module to another module, which sounds like an interesting thing to have I guess.

But all this is just an idea, anyway... I was thinking about it and it occured to me that it would be an interesting thing to try. It could be that there are circular dependency problems and it's not possible to do it.

**Comment by msalsbery** [comment]
What about ES6?

**Comment by Emigre** [comment]
You could do that and transpile to UMD but it seems like a bigger change.

**Comment by msalsbery** [comment]
Right, thanks. I was just mentioning that as well, since I'm playing with Aurelia framework where ES6/7 is supported and I have to make a shim for OSD (don't "have" to) :)

**Comment by Emigre** [comment]
@msalsbery that sounds interesting

@iangilman now that I think about it, you are totally right, UMD shouldn't be used internally, it's an external wrapper.

**Comment by iangilman** [comment]
@Emigre Cool. Are you up for making a patch with the wrapper?

**Comment by Emigre** [comment]
@iangilman yeah, I'll take a look at it during the weekend

**Comment by iangilman** [comment]
Sounds good :)

**Comment by Emigre** [comment]
I've been a little bit confused about how to achieve this and this is what I think could be done.

I think that we want it to do what jQuery does, to register itself as an AMD module if required but also to always be available in the window as a global. 

I was thinking on surrounding the code with something like [this](https://github.com/umdjs/umd/blob/master/amdWebGlobal.js). It could be done with a new step in the build process. But I think I'd rather not to complicate your build just for this.

A simpler option would be to put this...

```javascript
if (typeof define === 'function' && define.amd) {
   define(function () {
       return (window.OpenSeadragon);
   });
}
```

...after [this line](https://github.com/openseadragon/openseadragon/blob/master/src/openseadragon.js#L688) in openseadragon.js. It seems like a minimal change and it would essentially do the same.

But I'm not entirely sure if this all is worth it or if it's a good idea.

cheers

**Comment by iangilman** [comment]
I agree we want it both ways. If those few lines will take care of it, sounds good to me. Have you tested it in a UMD/AMD environment?

**Comment by Emigre** [comment]
I've tried it in a repo and it seems to be all right: https://github.com/Emigre/openseadragon-requirejs
I have this in a fork, I can do a MR if you want to use it.

**Comment by iangilman** [comment]
Yes please :)

**Comment by Emigre** [comment]
I've thought about this lately and I think it was a big mistake to have done it. Modules are supposed to guarantee execution order. First the module loader will inspect all the code of all files to see the modules that are being defined, then it will load the modules in the order needed by the dependencies.

With the code we have at the moment what happens is that during the first step when the code is checked OpenSeadragon is executed and is put in the browser global. Then during the module loading phase dependencies are analysed and executed in order, but when the time comes to serve OpenSeadragon, its module just delivers a reference to the global that was already there.

This is bad... Imagine that somebody needs to run some code **before** OSD runs... He would state the dependencies in its code and expect that OSD runs not before the time he is expecting, while in reality it will always be loaded the first. Therefore we are deceiving the user by offering this functionality when OSD does not really export itself as a module. In my opinion we should roll back this change -  it was a big slip-up on my part to have proposed it.

**Comment by iangilman** [comment]
Interesting point! What would it take to go one step further and make it properly support module loading order?

Also, forgive my lack of experience on this subject, but since OSD does nothing but define its classes until you actually call, what sort of thing would you need to do before then?

**Comment by iangilman** [comment]
@emigre Any thoughts on my questions above? I'm happy to roll back the change, but would like to know a little more about the situation.

**Comment by Emigre** [comment]
Hey @iangilman, sorry, I completely forgot about this thread... I have been busy lately.

> What would it take to go one step further and make it properly support module loading order?

My impression is that ideally the end result should be that after the build the whole plugin ends up being wrapped in the UMD module; so I imagine that the build has to be modified to output it like that. Then it would have to be tested with the different module loaders to check that it is behaving as expected, and I think with plugins to see that it all works as expected with no ugly surprises.

I think that inside inside OpenSeadragon we work with the global object, right? I imagine that it's ok for that code to define the global object and this means that the UMD probably does not have to output a browser global as one of its choices - it has already been created in the code. I'm not sure how jQuery handles this exactly, haven't taken a look at it in a while.

We currently don't offer a CommonJS module, but since this issue was created we have made available OpenSeadragon as a npm package, so perhaps we want to offer it now, for Browserify.

> Also, forgive my lack of experience on this subject, but since OSD does nothing but define its classes until you actually call, what sort of thing would you need to do before then?

I guess that you are right, I can't imagine anything right now. I guess it's a matter of... well... offering something that is not really behaving as the user would expect it to behave. I can't think of anything at the moment, to be honest.

Well, that's it, I think.  I'm sorry as I don't have a lot of time lately to take a look into this, I think it's an interesting subject and making it work as a module seems like a nice enhancement.

**Comment by Emigre** [comment]
Oh! I've just seen #984 about outputting a CommonJS module

**Comment by iangilman** [comment]
Oh! Funny, I'd gotten the much more recent #984 mixed up with your #719. Okay, less confused now.

So maybe we're good with #984, or is there more that you would suggest doing?
