### ISSUE TITLE
Question: Openseadragon as viewer for multiple remote IIIF services?

### ISSUE THREAD

**Issue by DavidHaskiya** [openseadragon/openseadragon#692]
At Europeana we're investigating the possibility to in our portal display images from those of our partners who support IIIF. We would like to do so without having a IIIF-server of our own, basically pulling in the IIIF-manifests directly from the IIIF-servers of our partners. 

Is that possible with OpenSeadragon or is it limited to reading IIIF-images from a local server?

**Comment by iangilman** [comment]
Should be fine. The only issue is the browser's cross-domain restrictions. This can be dealt with via CORS, or a local proxy. @jpstroop or @azaroth42 might have more thoughts. Let me know if you need help setting up one of these strategies.

**Comment by DavidHaskiya** [comment]
Hi Ian,
And thanks! I'm just doing the "desktop research" right now. Next week we should get started more hands on with OpenSeadragon.  We may get in touch if we run into any issues.

Cheers,
David

**Comment by azaroth42** [comment]
To be clear, the OpenSeadragon IIIF TileSource supports the IIIF Image API (http://iiif.io/api/image/) but does not support the IIIF Presentation API (http://iiif.io/api/presentation/) which is what defines a Manifest.  A client that has a Manifest that uses images which have a IIIF Image API service can use OpenSeadragon to render them beautifully, regardless of where the images are served from, so long as the correct CORS (e.g. http://iiif.io/api/annex/notes/apache.html) headers are on the responses.

**Comment by DavidHaskiya** [comment]
What we'd have from one of our partners (provided to us in the metadata they make available to us or derived from their identifiers) would be the URI to a IIIF manifest. Two real examples that we would like to render in the Europeana portal:

French National Library/Gallica:
http://gallicalabs.bnf.fr/ark:/12148/btv1b84238966/manifest.json

Bodleian Library:
http://iiif.bodleian.ox.ac.uk/iiif/manifest/9fb27615-ede3-4fa0-89e4-f0785acbba06.json

Would that suffice for OpenSeadragon to display the image(s)? Proxying and handling any CORS issue would be OK but what we'd like to avoid is having a IIIF-server of our own in order to display images from partners who have IIIF-services of their onw.

Apologies if this is a naive question.

**Comment by azaroth42** [comment]
David, are you on the iiif-discuss@googlegroups.com?  As this relates more to the Presentation API, that would be a better venue for the conversation, if possible :)  The short answer is no, OpenSeadragon doesn't handle manifests directly, you need something further that uses OSD to render the images referenced from the manifests.

**Comment by DavidHaskiya** [comment]
I am, yes. Will ask the question there. Thanks!
