### ISSUE TITLE
Portrait Image issue

### ISSUE THREAD

**Issue by CockyAmoeba** [openseadragon/openseadragon#695]
Greetings 

I have an image that i deepzoom with a size of `<Size Width="2368" Height="4208"/>`

When viewed in the seadragon control it looks like only the upper left hand quadrant is available.

If i then rotate the image and re-deepzoom it works just fine.

Is there a known bug with seadragon that it does not like portrait images? am I doing something wrong?

Regards

**Comment by iangilman** [comment]
No, this should work just fine. Can you share how you're adding the image? Do you have a link to this I can see?

**Comment by CockyAmoeba** [comment]
Greetings Ian

you can use this dzi:
https://mediastoreproduction.blob.core.windows.net/78d6cdca-9466-4e26-a965-60f957359068/deepzoom/deepzoom.dzi

Thanks you kindly

**Comment by avandecreme** [comment]
http://codepen.io/anon/pen/vOvGLQ

From the console, it looks like a lot of tiles are missing.
How did you generate the pyramid?

**Comment by CockyAmoeba** [comment]
I generated them by myself - and I assure you all the tiles are there. It is just that seadragon is not referencing them.

eg here is the tile fro level 12 and a column/row  that is never referenced:
https://mediastoreproduction.blob.core.windows.net/78d6cdca-9466-4e26-a965-60f957359068/deepzoom/deepzoom_files/12/8_4.jpg

attached is the original image

Thank again for your assistance!
![78d6cdca-9466-4e26-a965-60f957359068](https://cloud.githubusercontent.com/assets/1725653/9010765/3d6ab260-37a9-11e5-906e-c3461bcf3b5d.jpg)

**Comment by avandecreme** [comment]
I regenerated a pyramid from your image.
Here is the result in OSD: 
![osd](https://cloud.githubusercontent.com/assets/465389/9011301/69a2fe52-377a-11e5-94aa-4a90cf371d67.png)

You can download the pyramid here: https://drive.google.com/file/d/0BzAcRIdakTF0bGVDUnJRUUJNNW8/view?usp=sharing

**Comment by CockyAmoeba** [comment]
Greetings avandecreme 

would you mind giving the pseudo-code for the algorithm to generate the tiles that you used?

I only generated 12 levels (0-12) is that maybe my error? - just strange that i have no erros with images that are in landscape....

Regards, and thank you all for your investigation, time and assistance.

**Comment by CockyAmoeba** [comment]
Thank you all for your help I had a bug in my tile generation that caused an incorrect amount of levels to be generated for portrait images.

It is now working wonderfully.

Regards.

**Comment by iangilman** [comment]
Glad you were able to get it sorted out!
