### ISSUE TITLE
Question about resizing the browser and images no longer filling the viewer.

### ISSUE THREAD

**Issue by friarpat** [openseadragon/openseadragon#699]
When I create the OpenSeaDragon instance, I have the homeFillsViewer option set to true, autoResize is set to its default.  

I'm using the multiImage functionality.  Multiple items on the web page - one of which is OpenSeaDragon.

Once I load the images, I call viewport.fitHorizontally(true).   This centers the display and allows the images to fill the viewer horizontally with some images above and below the viewer that are not displayed. This fills the viewer top to bottom, left to right.  All is good!

If I expand the browser horizontally (grab the right border with the mouse and drag it right), the viewer still contains the images that were previously displayed, but no longer fills the viewer horizontally.  Subsequent calls to viewport.fitHorizontally don't seem to fit the viewer horizontally anymore.   Clicking on the Home button rezooms things, all is well, until I expand the browser again.  Shrinking the browser does the same thing until I run out of images vertically.  Calling viewport.goHome(true) kinda' works...but if the user is already zoomed in on the viewer, it obviously brings them back to the home view.   If the user IS zoomed on the view, I can expand the view until I get to some magical point where I run out of horizontal images again.  

A zoomed image performs in a somewhat similar fashion (as would be expected I guess).  It pretty much appears to maintain the image centered in the view, shrinking it as I reduce the width of the browser and not expanding it as I increase the width of the browser.

Is there some way I can maintain what is currently displayed in the viewer as the browser is resized?  Do I need to be calling something when the browser is resized?  Right now, I adjust the size of the container (div) OpenSeaDragon is contained in when there is a window. resize event.  At some point, you'll obviously run out of images to display...but as long as there are images outside of the current view, how do I keep presenting those?

Thanks again!

**Comment by friarpat** [comment]
FWIW - I've got a work around that mostly works. It's ugly, and not exactly inspiring, but with the exception of some race conditions, it works well enough for now.

When I added tracing to the OpenSeaDragon code, I noticed that the zoom level was gradually shrinking as I repeatedly maximized the browser (or resized the browser).

The ugly work around - when the $(window).resize event fires, I grab the current zoom level from OpenSeaDragon, recalculate and change the size of the container for OpenSeaDragon, then restore the zoom level using the zoomTo() call.   If the user is zoomed in at all, this maintains the zoom level.

 I tracked where the zoom size was being recalculated down to resizeViewportAndRecenter.   There's a call to viewport.resize - which the zoom size is fine yet, but when it recalculates the newBounds and calls fitBounds with it - that's when the zoom gets changed.

If I've missed a setting that causes the zoom to not be adjusted at this time, please let me know.

**Comment by iangilman** [comment]
Sounds like you're running into the constraints that affect how far you can zoom in or out. Try including these options when you create your viewer: 

```
minZoomImageRatio: 0, 
maxZoomPixelRatio: Infinity
```

...and see if that helps.
