### ISSUE TITLE
Simple Toolbar Icons Share

### ISSUE THREAD

**Issue by peterthomet** [openseadragon/openseadragon#700]
I was in need to create simple flat design toolbar buttons. Maybe someone else can use this.
![toolbar](https://cloud.githubusercontent.com/assets/5383762/9150698/70f23bfe-3de8-11e5-961e-5239fa67e94e.png)
Download Photoshop files included:
http://shop.getyournet.ch/Content/images/uploaded/OpenSeadragon%20Simple%20Icons.zip
Demo here:
http://droneservices.getyournet.ch/fliegen

**Comment by iangilman** [comment]
@peterthomet Awesome! These are lovely. 

What would you think about posting these as a project on your GitHub account and linking to it from http://openseadragon.github.io/#plugins ?

**Comment by peterthomet** [comment]
Sure :)
Done: https://github.com/peterthomet/openseadragon-flat-toolbar-icons

**Comment by iangilman** [comment]
Beautiful! Added: http://openseadragon.github.io/#plugins

**Comment by iangilman** [comment]
Also tweeted: https://twitter.com/openseadragon/status/632234094714187778
