### ISSUE TITLE
Preserving different Viewport Zoom Level and Position for each Image Sequence

### ISSUE THREAD

**Issue by Kampii** [openseadragon/openseadragon#703]
Is there a setting that would preserve the Viewport Zoom Level and Position for each image? For example, if user zooms into the upper left corner of the picture and then goes to the next image, and then zooms into the lower right corner of that image. And, when the user clicks back to the previous image, then the user would see the upper left corner of that image.

**Comment by iangilman** [comment]
Yes, use `preserveViewport: true` when creating the viewer.

**Comment by Kampii** [comment]
Right.. but that does not store the viewport zoom level and position for each image separately. In this case if I would go back to the previous image, then I would see the lower right corner of that image instead of the upper left corner. I hope you understand what I mean.

**Comment by iangilman** [comment]
Oh, gotcha. You'd have to do that yourself. Watch for `page` events on the viewer, and reset to the zoom/pan you've stored for the new image. To update the stored location, you can watch zoom/pan events.
