### ISSUE TITLE
Question: centering on an highlighted search term ( overlay)

### ISSUE THREAD

**Issue by susanmonnelly** [openseadragon/openseadragon#705]
I have an image that I am highlighting using overlays and I want to be able put the highlighted text in the viewing area when loading the image.   I have the rectangle values for the highlighted term.   How do I move to that area?   

```
// this is code in my addHandler open function
//  overlay is the highlighted search term
      overlay = viewer.viewport.imageToViewportRectangle(highlights.x, highlights.y, highlights.width, highlights.height);
      elt = document.createElement("div");
      elt.id = "example-overlay";
      elt.className = "NBViewerHighlight";
      viewer.addOverlay({
         element: elt,
         location: overlay
      });
// There are newspaper articles that are very large images
//  I want to zoom in a bit closer so the user can start reading right away
      if (imageHeight > 600) {
        imageHeightRect = imageHeight / 3;
        imageRectangle = viewer.viewport.imageToViewportRectangle(0, 0, imageWidth, imageHeightRect);
        viewer.viewport.fitBounds(imageRectangle, true);
// I thought this would put the highlighted term in the center of the viewing area
// but that doesn't seem to be the case
        viewer.viewport.panTo(overlay.getCenter()); 
      }

```

Is panTo doing what I think it should be doing?    

Here's how the image looks without the panTo

![without panto](https://cloud.githubusercontent.com/assets/12297503/9364503/a92cf014-467a-11e5-88a6-85c9cbb45b24.png)

This is the image with the  panTo

![with panto](https://cloud.githubusercontent.com/assets/12297503/9364522/bedffc76-467a-11e5-8831-f35f3c5c5a20.png)

This is what I want to happen:

![ideal centering](https://cloud.githubusercontent.com/assets/12297503/9364530/c881941a-467a-11e5-8577-070eace3e01d.png)

**Comment by iangilman** [comment]
Your use of panTo looks good. I think the problem you're running into is calling fitBounds and panTo back to back like that; I believe they're fighting with each other. If you want to fitBounds, you should factor into that call the location you want to end up panned to, and then skip the panTo call.

**Comment by susanmonnelly** [comment]
Thanks .   Looks like I will need to do additional calculations. 
Appreciate the quick response.

**Comment by susanmonnelly** [comment]
I've fixed this problem. thanks
