### ISSUE TITLE
Question of calling DZI files

### ISSUE THREAD

**Issue by SonicsQ** [openseadragon/openseadragon#709]
Hi, 
I have a question about calling the dzi file in OpenSeaDragon. That's how I wrote in the html file.
![image](https://cloud.githubusercontent.com/assets/13908369/9416917/5a6bb738-4816-11e5-9a9a-7b65960dfd63.png)
I've changed the tileSources address from .xml to.dzi, or changed the dzc_ouput file (Generated from Windows deep zoom composer) from .xml to .dzi but it still doesn't work.
In addition, I download the github project of website to my desktop, but what it shows in the openseadragon is that: "Unable to open [object, object]: HTTP 404 attempting to load TileSource."
That's how it looks like in the browser.
![osd](https://cloud.githubusercontent.com/assets/13908369/9416898/417a379a-4816-11e5-90b1-8b514253a88f.PNG)
I know it's a really simple question but I try all those methods above and still can't figure out.
Could anybody please help me to solve it?

Thanks,

**Comment by Pin0** [comment]
Is your html file in the same directory as the UntitledProject4 directory?

(I'm no expert just starting with openSeadron myself)

**Comment by iangilman** [comment]
Indeed...sounds like you've got your paths wrong somehow. Can you share your folder structure? Or can you put it on a server somewhere to share?
