### ISSUE TITLE
Can image tiles be created by web workers?

### ISSUE THREAD

**Issue by eriksjolund** [openseadragon/openseadragon#716]
Has anyone tried creating image tiles with web workers?
Instead of having OpenSeadragon downloading the image tiles,
it could let web workers create the image tiles in other threads.

The use case for this could be: Annotating a photo with some vector
graphics that might take long time to draw.

Disclaimer: I am new to JavaScript and OpenSeadragon so I am trying
to understand how it all works.

**Comment by iangilman** [comment]
There is some discussion of this sort of thing in https://github.com/openseadragon/openseadragon/issues/119. 

That said, if you want to add vector graphics, you may be better off with https://github.com/openseadragon/svg-overlay.

**Comment by eriksjolund** [comment]
Yes, if the svg-overlay plugin is fast enough that would be the best and most simple solution. I'll need to try things out. Doing it with web workers would be a more complex solution.
