### ISSUE TITLE
Server-side annotation of image tiles on the fly

### ISSUE THREAD

**Issue by eriksjolund** [openseadragon/openseadragon#717]
Has anyone tried annotating image tiles on a web server on the fly?
Let us say we have pre-generated image tiles of a photo stored on a web server and we would like to annotate the photo with some vector graphics.
Of course, often the best approach would be to annotate the photo directly on the client (see my questions #716 and [svg-overlay issue 8](https://github.com/openseadragon/svg-overlay/issues/8)) but here I would like to discuss the idea of having the web server modifying the image tiles on the fly before sending them to the web browser.

It would be easy to achieve parallelization:
HTTP requests for different image tiles could be distributed to different web servers by an HTTP reverse proxy like for instance [nginx](http://nginx.org/). Another way could be to make use of the combination [AWS Lambda](https://aws.amazon.com/lambda/) and [AWS API Gateway](https://aws.amazon.com/api-gateway/). That combination has a lot of promises but these services are new and the speed is not quite there yet, at least if I think their [example web page](http://squirrelbin.com) is a bit slow. See also their blog post [SquirrelBin: A Serverless Microservice Using AWS Lambda](https://aws.amazon.com/blogs/compute/the-squirrelbin-architecture-a-serverless-microservice-using-aws-lambda/) .

I have nothing to show yet but I did some minimal experiments by modifying
[node-opencv](https://github.com/peterbraden/node-opencv) and creating a wrapper function for my own C++ function (that makes use of [OpenCV](http://www.opencv.org)).
I used it together with [Express](http://expressjs.com/) and let the web browser access a locally running
[Node.js](https://nodejs.org)   server. The speed that I saw on my laptop was a bit laggy but I hope it could be fixed by having the Node.js server running on a machine with more horse power or by distributing the HTTP requests to different computers.

Do you have comments about the idea of modifying the image tiles on the web server on the fly?

**Comment by boskar** [comment]
The first question is - what's the source of tiles? Are they static?

**Comment by eriksjolund** [comment]
The photo that is going to be annotated is not changing so its image tiles have been
created in advance with the command

vips dzsave bigphoto.jpg outparam --layout dz

The vector graphics annotation that will be painted on top of the photo, will be dependent of some changeable parameters in a web form. This web form will be on the same web page as the OpenSeadragon window.

**Comment by eriksjolund** [comment]
This is not the complete code for the Node.js experiment I did, but at least it shows a sketch of it.  I also added the function my_cpp_wrapper_function
to the node-opencv module, but that code is not presented below:

    var app = express();
    var cv = require('../lib/opencv');
    
    app.get('/bigphoto.dzi', function (req, res, next) {
      res.sendFile('/tmp/test/bigphoto.dzi');
    });
    
    app.get('/index.html', function (req, res, next) {
      res.sendFile('/tmp/test/index.html');
    });
    
    app.get('/bigphoto_files/:dzi_level(\\d+)/:dzi_x(\\d+)_:dzi_y(\\d+).jpeg', function (req, res, next) {
    cv.my_cpp_wrapper_function(Number(req.params.dzi_level),Number(req.params.dzi_x),Number(req.params.dzi_y), function(err, im) {
      res.writeHead(200, {'Content-Type': 'image/jpeg'});
      res.write(im.toBuffer(), 'binary');
      res.end();
    })

**Comment by iangilman** [comment]
It certainly seems like it could be done, though I don't know of anyone who has done it. It seems like drawing the annotations on the client side would be more appropriate. 

Do you have an example of the sort of annotations you're trying to add? That might help me understand what the best approach could be.

**Comment by msalsbery** [comment]
I've had good success on Windows Server platform using an IHttpServer tile server and .NET System.Drawing to do offscreen drawing (which is no longer recommended).

To help performance, good use of etags and other caching headers along with caching anywhere you can is a huge plus. Setup and tear down of graphics/drawing stuff can take the longest, so caching there can help as well. Easier on node :)

**Comment by eriksjolund** [comment]
It's about showing measurement points on top of a microscope photo. It's not clear how many measurement points I need to handle. Right now I am just trying things out. 
If it is possible doing it on the client side, it would simplify things. I know there is a SVG plugin.

Just a comment about my idea of using [AWS Lambda](https://aws.amazon.com/lambda/) and [AWS API Gateway](https://aws.amazon.com/api-gateway/)
to draw the image tiles on the fly:

It is currently not possible to return an image by those techniques but there may be a workaround:
http://stackoverflow.com/questions/31972624/how-do-i-respond-with-a-raw-buffer-instead-of-tostring-in-amazon-api-gateway-l
