### ISSUE TITLE
working "ready" event needed

### ISSUE THREAD

**Issue by fgrs** [openseadragon/openseadragon#722]
I'm pulling my hairs trying figure out why safari and ios have issues with this handler

viewer.addHandler('open', function() {
  var bounds = scope.viewer.viewport.getHomeBounds();
  var point = new OpenSeadragon.Point(0.5, scope.bounds.height / 2);
  scope.viewer.viewport.panTo(point, true);
});

it's working fine on chrome and i can reposition the image but for some reason this gets fired too early on ios, now I'm on a different path trying to listen when tiles source are ready but this doesn't seem to work

var ts = new OpenSeadragon.LegacyTileSource(tiles);

ts.addHandler('ready', function(event) {
  alert('hello world')
})

viewer.open(ts)

**Comment by avandecreme** [comment]
>it's working fine on chrome and i can reposition the image but for some reason this gets fired too early on ios, 

What do you mean by too early? If I remember correctly, there is no need to wait for the tiles to be loaded to pan the viewport. So your first code should work. Do you have any error message?
