### ISSUE TITLE
Openseadragon 2.1.0

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#726]
It's probably time to release a new version! We still have a few items on the 2.1.0 milestone that would be nice to get taken care of; some are already in progress. Anyway, coming down the home stretch.

**Comment by iangilman** [comment]
Don't forget to merge this in after the release: https://github.com/openseadragon/site-build/pull/87

**Comment by iangilman** [comment]
Ok, we've finished all the tickets I had tagged with 2.1.0...unless anyone has any objections, we can publish the new version next week sometime.

**Comment by avandecreme** [comment]
:+1:

**Comment by iangilman** [comment]
Done! https://github.com/openseadragon/openseadragon/releases/tag/v2.1.0
