### ISSUE TITLE
Overlays positions when rotate

### ISSUE THREAD

**Issue by art-eltyshev** [openseadragon/openseadragon#729]
When I call `viewport.setRotation` and image rotates, overlays positions aren't changing and if you start to drag image, their position changes incorrectly.

**Comment by iangilman** [comment]
Good point! Looks like we're kind of making an attempt; the position changes, and panning even seems to work (when I tried it) but zooming is totally wrong, and the size of the overlay changes incorrectly. Should definitely be looked into.

**Comment by avandecreme** [comment]
Fixed by #896

**Comment by MMtechnolab** [comment]
i am working with openseadragon and fabric js canvas when , zoom is working perfectly for fabricjscanvas but rotate doesnt please check belowe link .download and run the demo.html then click on draw then draw on canvas then click rotate 

https://github.com/MMtechnolab/OpenseadragonfabricjsDemo

**Comment by iangilman** [comment]
@MMtechnolab Does this help? https://stackoverflow.com/questions/45456171/fabric-canvas-changing-position-when-openseadragon-image-is-rotated

**Comment by MMtechnolab** [comment]
@iangilman i have tried it but not working

**Comment by iangilman** [comment]
Hmm... it looks like Fabric itself doesn't really support rotation, according to https://github.com/altert/OpenseadragonFabricjsOverlay/issues/9. Btw, have you tried the suggestions in that issue? At any rate, you might need to follow up on that plugin or Fabric itself.
