### ISSUE TITLE
Can't run from file:///

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#73]
Opening your OpenSeadragon HTML file with file:/// instead of off of a local web server causes the tile paths to be wrong. If you try https://github.com/CanOfBees/osd-test in that way, you'll see errors like:

`Tile 8/0_1 failed to load: file:///example-images/sanborn_knoxville1884_0001_files/8/0_1.png`

Note that the path it's looking for is at the root of my hard drive, whereas it really should be the folder I ran from (in my case file:///Users/iangilman/projects/openseadragon/pulls/canofbees-osd-test/osd.html).

At first I thought this was due to #70, but I'm not so sure anymore.

**Comment by avandecreme** [comment]
This has been fixed.

**Comment by iangilman** [comment]
Good catch!
