### ISSUE TITLE
Issue with display of long skinny image 

### ISSUE THREAD

**Issue by susanmonnelly** [openseadragon/openseadragon#731]
![screen shot 2015-09-18 at 8 13 57 am](https://cloud.githubusercontent.com/assets/12297503/9959173/9f210ae8-5ddf-11e5-8174-500b3db9b713.png)

This image is not loading the tiles in the right column and not fully loading the bottom half of the image.   The tiles created for this image at zoom level 0 are 2 x 10 and OSD is loading 1 x 5 or half of that. 

image width is 1024 px, height is 5120 px

**Comment by iangilman** [comment]
What format are you using? Do you have it up somewhere you can link to?

**Comment by susanmonnelly** [comment]
What do you mean by format?    This is in a dev environment behind our firewall so not easy to give you access.   I'm using a custom tile source, if that's what you mean by format.    I can see all the tiles are created but OpenSeadragon is not pulling all them in.    Have you tested with images at this width and height?

**Comment by iangilman** [comment]
Yes, I meant what sort of tile source. I can't say for sure we've done exactly 1024x5120, but we've certainly done many tall narrow images like that. The problem is likely in your custom tile source somehow. To verify, you could convert the same image to DZI and try that. 

I assume you're not seeing any errors in the console? And is it consistent as you zoom in and out?

**Comment by susanmonnelly** [comment]
I tested this as you suggested and it works fine with DZI.  I'm confused.  I have the appropriate tiles created, converted to DZI,  but for some reason the tiles are not loaded.   I have other image types and sizes working fine with the custom tile source.

There are no errors in the console and consistent with zoom in and out.

Any other hints?

**Comment by iangilman** [comment]
Can you post the code for your custom tile source? Perhaps it's in the logic there.

**Comment by susanmonnelly** [comment]
I posted some of it in this thread https://github.com/openseadragon/openseadragon/issues/690.
I haven't had a chance yet to implement your solution but that was to trigger getImageInfo.

I changed my zoom ratio so the number of tiles created for each zoom level has bee changed to make this work.  


here's the update of my custom tile source:

```

  /**
   * @class NBTileSource
   * @classdesc A tilesource implementation for NewsBank.
   *
   * @memberof OpenSeadragon
   * @extends OpenSeadragon.TileSource

   */

   // need to try rewriting to this latest example to see if it will work:
   //  https://github.com/openseadragon/openseadragon/issues/690
  OpenSeadragon.NBTileSource = function(  ) {

    var options;

    // this will change to a relative link
   // var baseRequest = '/SiteLinks/tileviewer/osdtiles/';
    var baseRequest = 'http://iw.devvm23.newsbank.com/SiteLinks/tileviewer/osdtiles/';
    // decide here whether full page or tiles and size of tiles? not yet implemented so not needed.  defaults to tiles
    var imageDelivery = 'tiles';
    var tileSize = 256;
 
    var srcWidth = tvSettings.image.srcWidth;
    var srcHeight = tvSettings.image.srcHeight; 
    var siteLinksPath = [];
    var docID;

    siteLinksPath.push(tvSettings.request.params['DB']);
    siteLinksPath.push(tvSettings.request.params['RELEASE']);
    siteLinksPath.push(tvSettings.request.params['ISSUE_ID']);
    siteLinksPath.push(tvSettings.request.params['OSD_PAGE_ID']);
    siteLinksPath.push(tvSettings.request.params['IMAGE_SIZE']);
    siteLinksPath.push(tvSettings.request.params['DST_IMAGE_TYPE']);

    docID = tvSettings.request.params['OSD_DOC_ID'] ? tvSettings.request.params['OSD_DOC_ID'] : undefined;

    var queryString = ['doc_id=', docID, '&source_width=',srcWidth,'&source_height=',srcHeight, '&tile_size=',tileSize,'&user_id=',user_id,'&rem=',rem,'&image_delivery=',imageDelivery, '&search_term=',search_term].join('');
    var tileRequest = [baseRequest,siteLinksPath.join('/'), '/index.json?',queryString].join('');

    // this is done because the tiles returned to us are padded with a background color when the tile edges have a 
    // to create an even number of tiles.
    numTiles= new Object();
    numTiles.x = srcWidth % tileSize == 0 ? srcWidth/tileSize : Math.floor(srcWidth/tileSize) + 1 ;
    numTiles.y = srcHeight % tileSize == 0 ? srcHeight/tileSize : Math.floor(srcHeight/tileSize) + 1 ;

    this.width=numTiles.x*tileSize;
    this.height=numTiles.y*tileSize;

    options = {
      width: this.width,
      height: this.height,
      tileSize: tileSize,
      tileOverlap: 0,
      minLevel: 0,
      maxLevel: 1
    }

    this.getNBImageInfo( tileRequest );
    OpenSeadragon.TileSource.apply( this, [ options ] );

  };

  OpenSeadragon.extend( OpenSeadragon.NBTileSource.prototype, OpenSeadragon.TileSource.prototype, {

    getNBImageInfo: function (tilesUrl) {
      var tilePaths = new Array();
      var highlights = new Array();
      var zones = new Array();

      jQuery.ajax( { 
        url: tilesUrl, 
        dataType: "json",
        async: false,
        success: function(data, text) {
          if (data.imageserver.tiles != null)
            tilePaths = data.imageserver.tiles;
          if (data.imageserver.highlights != null)
            highlights = data.imageserver.highlights.highlight;

          if (data.imageserver.zones != null)
            zones = data.imageserver.zones.zone;
        },
        error: function(request, status, error) {
          alert("Error : " + request.responseText + "\n" + status + "\n" + error);
        }
      });
      this.tileLocations = tilePaths;
      this.highlights = highlights;
      this.zones = zones;
    },

    /**
     * @function
     * @param {Number} level
     * @param {Number} x
     * @param {Number} y
     */
    getTileUrl: function( level, x, y ) {
      id =  'tile_' + x + '_' + y + '_' + (level);
      return this.tileLocations[id];
    }   

  });
```

**Comment by susanmonnelly** [comment]
I have an update to this issue.  When I changed the tile size to 512, the image displayed correctly at both zoom levels.   Interesting.

**Comment by iangilman** [comment]
Interesting. I suppose one test might be to put a console.log in your getTileUrl to see exactly which levels and x and y are being called for. 

It does seem like it may have something to do with your levels. I believe OSD assumes that each level is twice as large as the level preceding it; is that how your files are structured? Note that with DZI, level 0 is 1 pixel wide, level 2 is 2, level 3 is 4 (approximately, depending on aspect ratio). I see that you have a minLevel of 0 and a maxLevel of 1; I assume those levels aren't 1 pixel and 2 pixel wide. If your lowest tile level is approximately 256 pixels wide, that would translate to OSD tile level 8, so you'd want to subtract 8 from the level OSD gives you in getTileUrl, just like we do in the OSM tile source: 

https://github.com/openseadragon/openseadragon/blob/master/src/osmtilesource.js#L140

...and you'd want to make your minLevel 8 and your maxLevel 9.
