### ISSUE TITLE
sequenceMode index

### ISSUE THREAD

**Issue by jprocess** [openseadragon/openseadragon#733]
Hello. I have a grid of images that I'm loading as OSD images from an array. I currently have them set in sequenceMode. When I select any of them they default to the first in the sequence. How would I pass the index of the tileSources array to OSD so that it would start on the selected image in the array/gird.

Thanks much!

**Comment by iangilman** [comment]
Hmm...that should work. How are you selecting them? Do you have a link you can share?

**Comment by jprocess** [comment]
No, I'm afraid I don't have a link I can share. Are you saying that, as is, the selected image should open within the sequence of images, and not go to the first in the array?

**Comment by iangilman** [comment]
Well, depends on how you are selecting it. Is this in response to some user event, or is it when you first launch the viewer? And are you using `viewer.goToPage(index)`? And by sequenceMode, you mean you're passing `sequenceMode: true` when you create the viewer?

**Comment by jprocess** [comment]
It is in response to a user event; selecting an image preview which launches the viewer. And yes, sequenceMode: true

**Comment by iangilman** [comment]
So it sounds like you're trying to do it when you first launch the viewer. Just pass in the page index for the `initialPage` property when creating the viewer.

**Comment by jprocess** [comment]
Actually, no, I'm doing it in response to a user event. Would I pass viewer.goToPage(index) in that case?

**Comment by iangilman** [comment]
Yes, if the viewer is already launched and you already have the sequence open, viewer.goToPage(index) should work. The only challenge might come if you're trying to do it too soon after launching the viewer.

**Comment by jprocess** [comment]
Ah, okay. Yes, if the user selects an image preview from the grid, that would be launching the viewer. So, it would, in fact, be soon after launching the viewer. I tried passing the index to  initialPage and it still defaults to the first in the sequence.

**Comment by iangilman** [comment]
Hmm...I just tried: 

```
        var viewer = OpenSeadragon({
            id: "contentDiv",
            prefixUrl: "../../build/openseadragon/images/",
            tileSources: ["../data/testpattern.dzi", "../data/tall.dzi"],
            sequenceMode: true,
            initialPage: 1
        });
```

...and it loaded the second page just fine. I also tried: 

```
        var viewer = OpenSeadragon({
            id: "contentDiv",
            prefixUrl: "../../build/openseadragon/images/",
            tileSources: ["../data/testpattern.dzi", "../data/tall.dzi"],
            sequenceMode: true
        });

        viewer.goToPage(1);
```

...and that worked as well. 

Neither of those work for you? (Note those paths are relative to test/demo in the OSD repo...change to your paths as you see fit.) If not, can you make a CodePen that reproduces your issue?

**Comment by jprocess** [comment]
Ian - Thanks for the help. This was user error... initalPage did, in fact, work. Thanks again

**Comment by iangilman** [comment]
:+1: Thanks for letting me know!
