### ISSUE TITLE
Support tile-less IIIF as per LegacyTileSource

### ISSUE THREAD

**Issue by azaroth42** [openseadragon/openseadragon#737]
It is possible to have a IIIF (http://iiif.io/) compliant system that does not support tiles, but instead uses the `sizes` list to give a set of complete images at different sizes.  This is practically identical to the Legacy Tile Source pattern (https://openseadragon.github.io/examples/tilesource-legacy/).  It would be great to have a fallback for the IIIF Tile Source to use the Legacy code when only sizes are available.

```json
{
  "@context" : "http://iiif.io/api/image/2/context.json",
  "@id" : "http://www.example.org/image-service/img1234",
  "protocol" : "http://iiif.io/api/image",
  "width" : 6000,
  "height" : 4000,
  "sizes" : [
    {"width" : 150, "height" : 100},
    {"width" : 600, "height" : 400},
    {"width" : 3000, "height": 2000}
  ]
}
```
Would trivially map to:

```json
{
    "type": "legacy-image-pyramid",
    "levels": [{
        "url": "http://www.example.org/image-service/img1234/full/3000,/0/default.jpg",
        "height": 2000,
        "width":  3000
    },{
        "url": "http://www.example.org/image-service/img1234/full/600,/0/default.jpg",
        "height": 400,
        "width":  600
    },{
        "url": "http://www.example.org/image-service/img1234/full/150,/0/default.jpg",
        "height": 100,
        "width":  150
    }]
}
```

Note in the example above width 6000 / height 4000 is intentionally left out of the sizes array as unavailable.  It should not be assumed that full/full is available without authentication, so only the entries in the sizes array should be used by the TileSource.

#enhancement #iiif #tilesource

**Comment by iangilman** [comment]
@azaroth42 Is this a scenario that's not currently supported by the IIIFTileSource? In other words, if the current one got that result from the server, would it not know what to do? 

I don't know that having the IIIFTileSource delegate to the LegacyTileSource would necessarily be the right way to go about it...it might be better to keep the IIIFTileSource self contained but also support this scenario.

**Comment by azaroth42** [comment]
Hi @iangilman.  Yes, it's not currently supported.  I'm not sure what the current implementation would do, but likely just error out.  I can try to look at how Legacy works and port the functionality over to the IIIFTileSource.  I'll post any questions as I get to the implementation on this issue?  (And if anyone else wants to have a go before I get to it, please feel free!)

**Comment by iangilman** [comment]
@azaroth42 Sounds good!

**Comment by tomcrane** [comment]
Hi @iangilman - I have a possible solution to this that makes the IIIFTileSource emulate the legacyTileSource when only the sizes list is available in the IIIF info.json:

https://github.com/openseadragon/openseadragon/compare/master...tomcrane:iiif-sizes

All the changes are in IIIFTileSource.js, there's probably a more elegant way of combining the functionality of the two tilesources.

**Comment by iangilman** [comment]
@tomcrane Excellent! Looks reasonable to me (assuming you'll remove all of the console.log calls). I love that you've added demos and tests!

@azaroth42 Would you mind taking a look at the patch?

**Comment by tomcrane** [comment]
I'll tidy this up and put in a pull request tomorrow. Do you want the large test images in the PR? If so I'll compress them some more.

**Comment by tomcrane** [comment]
Hi @azaroth42, @jpstroop - do you agree with that canBeTiled(..) function?

https://github.com/openseadragon/openseadragon/compare/master...tomcrane:iiif-sizes#diff-8687fada024051e6abce230abcacc2aaR385

I'd like to remove the hard coded profile.

**Comment by jpstroop** [comment]
@tomcrane I think you're going to need to hard-code more to support 1.0 and 1.1. :disappointed: 

http://iiif.io/api/image/1.0/#info

http://iiif.io/api/image/1.1/#image-info-request

Specifically, I think you need to add more possible values (or not-values) to the `profile` condition.

**Comment by tomcrane** [comment]
@jpstroop Would it be too dirty to have a test for "is a URI" && "contains 'level0'" ? That or hard-code the three possible level0 profiles. The former assumes that vFuture level0 never supports tiles. There are currently no hard-coded profiles above 1.1 in the source.

**Comment by jpstroop** [comment]
That seems a little opaque to me. I think I'd prefer to see the two or
three disallowed URIs spelled out explicitly.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by tomcrane** [comment]
OK - maybe revisit at IIIF 7...

**Comment by iangilman** [comment]
@tomcrane Yes, please include the images (assuming there are no rights issues).
