### ISSUE TITLE
Rectagle Y position

### ISSUE THREAD

**Issue by sreejayam2000** [openseadragon/openseadragon#739]
```
            var boundBoxRect = CybercomDFAII.ReportView.OpenSeaDragon.viewer.viewport.imageToViewportRectangle( x     ,  y   , diffX ,   diffY);
            var boundBoxOverlay = $("<div id=\"overlay-boundbox-colony"+"\"></div>");
            boundBoxOverlay.css({
                border: "2px solid black"
            });
          viewer.addOverlay(boundBoxOverlay.get(0), boundBoxRect);
```

Here I can draw rectagle but my requirement is i should start Y axiz from bottom left but it takes top left . for eg : if Y is 10 to 15 then it should start to draw from bottom left 10 to 15. but here it is happening opposite. 
My requirement is possible ? 
I thought i will give 15 to y and diffY= -5. but it is not working.

**Comment by avandecreme** [comment]
Having y top to bottom is the standard in imagery.
To convert, you need to do `imageHeight - y`.

If you don't know imageHeight beforehand, you should be able to retrieve it with:
```javascript
var imageHeight = viewer.world.getItemAt(0).source.height;
```

**Comment by sreejayam2000** [comment]
Thank u for the respose. i got  image height. problem is i need to draw overlay 
eg. Image Heght : 1000  y= 500 y1:200  . ineed to draw bottom to top that 500->200.
I cant able to  mention height: -300.   This image is drawn bottom to top. so i need draw rectagle y bottom to top.
Please correct  my code
  var imageHeight =  viewer.world.getItemAt(0).source.height;
             y=     imageHeight - y;
       var boundBoxRect =   .viewer.viewport.imageToViewportRectangle(x,y ,diffX ,-300);

**Comment by avandecreme** [comment]
I think it should be:
```javascript
var imageHeight = viewer.world.getItemAt(0).source.height;
var boundBoxRect = viewer.viewport.imageToViewportRectangle(x, imageHeight - y, diffX , diffY);
```
