### ISSUE TITLE
Multi-image mode with imaginghelper

### ISSUE THREAD

**Issue by mdcorriveau** [openseadragon/openseadragon#748]
Hi,

I'm currently working with the latest released version of openseadragon to date (2.0.0) and the imaginghelper plugin. I currently have some problems with it like : the zoomlevel is incorrect and the result of physicalToDataPoint is not right. My guess is that the imaginghelper doesn't support the new true multi-image mode of openseadragon. I just want to know if anyone had this issue before and if there is a solution right now. If not I'll keep on debugging 

Thanks !

**Comment by msalsbery** [comment]
You're correct, I need to update that plugin!!

Trying to squeeze some time...

**Comment by msalsbery** [comment]
You're welcome to patch it if you'd like ;)

**Comment by mdcorriveau** [comment]
Perfect, I'll look into that this monday, I'll try to do a patch. It's my first time on github :P

**Comment by iangilman** [comment]
Closing in favor of https://github.com/msalsbery/OpenSeadragonImagingHelper/issues/8
