### ISSUE TITLE
How to force reload of tile's ImageData

### ISSUE THREAD

**Issue by meihuisu** [openseadragon/openseadragon#749]
I  have DZI data in both RGB and multiple greyscale channels.  I want to make a viewer that allows
user selectively show different channel at  a time or composition of multiple.  I have tried the layering
of multiple DZI with  addTiledImage. That did not work because  I could not alter each layer independently except their opacity. Now, after consulting issue #389, I have worked out a solution with
a tile-drawing handler.  I created a new ImageData space, copied the the original into it without
one of the channel data and successfully altered the display by calling putImageData. Now if the user
want the channel back, I need to be able to force a reload of the ImageData from tiles because the ImageData in the context has been altered permanently by the putImageData call.

**Comment by meihuisu** [comment]
Found the answer,  viewer.world.resetItems()

**Comment by avandecreme** [comment]
Just so you know, I just published a filtering plugin which might help you: https://github.com/NIST-ISG/OpenSeadragonFiltering
It already handles the restoration of the original ImageData.

**Comment by avandecreme** [comment]
Note that it requires OSD 2.1 which is not yet released. So you have to checkout the master branch for it to work.

**Comment by meihuisu** [comment]
thanks @avandecreme, I will check it out.

**Comment by meihuisu** [comment]
I have checked out your code. It is indeed very helpful. One of the requirement of our filter is
to blend data from multiple tiledImages into a mergedImageData. For example, if we load several
grey scale DZI data, we want to be able to colormap one of them to Red(colorization filter) and 
then other to Blue(colorization filter) and blend them into a merged result(blending filter). 
How to access other matching tiledImage tile with the current event's is something I need. Is it
possible?

**Comment by boskar** [comment]
I support this feature, I'll need it sooner or later (fluorescence microscopy scans)

**Comment by avandecreme** [comment]
For such a use case, I believe it would be easier with virutal images #119 

However it may be possible using the filtering plugin if the filters accepted a tile as argument:
`function(tile, context, callback)`
The filters could then fetch the other channels tiles and blend them together.

**Comment by jetic83** [comment]
Another possibility is e.g. if your viewer has the tilesource: 'file.dzi', you convert it to 'file.dzi?' + new Date().getTime();
and replace the old tiledImage with the new one. Then OSD is forced to redraw the tiles.
