### ISSUE TITLE
OpenSeadragon browser extension

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/openseadragon#750]
I am often frustrated when viewing big images in a browser by the fact that I can't properly zoom and pan.
So I just created a chrome extension which allows to fire up openseadragon via a right click on an image:
![osd-extension](https://cloud.githubusercontent.com/assets/465389/10718108/f13f3d26-7b40-11e5-9c59-c035437ca014.png)

It then loads it in a legacy tile source:
![osd-extension2](https://cloud.githubusercontent.com/assets/465389/10718120/2e41ae16-7b41-11e5-8193-3b3c3c59fee4.png)

I was wondering if there is any interest in officially supporting it? Or should I just go ahead and publish it in my own git repository?
Ideally I would like to port it to other browsers as well (at least Firefox).

**Comment by iangilman** [comment]
I think this is an awesome idea! Here is the new repository: 

https://github.com/openseadragon/browser-extension
