### ISSUE TITLE
Poor downsampling quality with legacy tilesource

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/openseadragon#751]
I am not sure whether we can do something about it but I reproduce the issue on both Chrome and Firefox.
Left with OSD, right without:
![downsampling](https://cloud.githubusercontent.com/assets/465389/10718235/56488620-7b44-11e5-94e7-50bc004175df.png)

**Comment by avandecreme** [comment]
Maybe we should consider doing stuff like this: http://stackoverflow.com/questions/17861447/html5-canvas-drawimage-how-to-apply-antialiasing

**Comment by iangilman** [comment]
Interesting...in effect, that would mean making an image pyramid in the browser for the legacy tile source. Seems like a decent idea.

**Comment by iangilman** [comment]
This is fixed by #760, or rather, that patch introduces a new tile source that addresses this issue. Since that leaves LegacyTileSource to just work on pyramids, I don't think we need to do anything special for it.
