### ISSUE TITLE
Free draw on the canvas of openSeadragon ? 

### ISSUE THREAD

**Issue by nikitochak** [openseadragon/openseadragon#752]
Hello, I am working on mirador which uses openSeadragon. My main task is to find a way for the user to draw any kind of figure and afterwards to annotate them. Using [fabric js](http://fabricjs.com/) it is easy to enable free draw on canvas and it also supports appropriate event system. Unfortunately the openSeadragon system seems to block the fabrics. 

```
   var x = 0, y = 0, width = 0.8, height = 0.8;
   this.rectangle2 = new OpenSeadragon.Rect(x, y, width, height);
   this.osdOverlay2 = document.createElement('canvas');
   this.osdOverlay2.className = 'djena';//'osd-select-rectangle';
   this.osdOverlay2.style.border = '2px solid green';

   //here i'm initializing the fabric 
   this.canvas= new fabric.Canvas(this.osdOverlay2);
   //and adding it as an overlay 
   this.osdViewer.addOverlay({
      element: this.osdOverlay2,
      location: this.rectangle2
   });
```

 After that I remove the openSeadragon handlers for canvas-click and  set the event handlers of the fabric's canvas.

```
    this.osdViewer.removeAllHandlers('canvas-click');
    this.canvas.on('mouse:click', function(e){
          console.log('vutre');
          getMouseCoords(e);
    });
    function getMouseCoords(event)
    {
          var pointer = this.canvas.getPointer(event.e);
          var posX = pointer.x;
          var posY = pointer.y;
          console.log(posX+", "+posY);    // Log to console
    }
```

But the method is never invoked and when I click on the canvas it zooms in. Am I doing something wrong ? Is there a better way for enabling free draw ?
Some help will be highly appreciated. :+1:

**Comment by iangilman** [comment]
In order to handle all the interaction events, OSD does eat some of the events before they can make it to your overlay. I'm not familiar with fabric...is it possible to capture the events via OSD and then pass them into fabric, rather than having fabric capture the events? 

Incidentally, besides that, how is it working to have fabric be an overlay? Does it do the right thing when you pan and zoom?
