### ISSUE TITLE
Programmatically enable and disable panning, but still capture mouse events

### ISSUE THREAD

**Issue by davepruitt** [openseadragon/openseadragon#759]
The normal behavior of OpenSeaDragon when the user clicks-and-drags is to pan around the image, as expected.  I would like to allow the users of my program to switch to a "drawing" mode, where panning is temporarily disabled, and they can draw an overlay on the canvas.

I noticed that the viewer has a setMouseNavEnabled function.  When I use this function it successfully enables/disables panning around the image, but it also makes it so I can't listen to mouse events anymore.  I was listening to "canvas-click" events using this line of code:

viewer.addHandler('canvas-click', handleCanvasClickEvent);

But now my function handleCanvasClickEvent does not get called.  How can I turn off panning, but still listen for mouse events so that I can properly react to the user "drawing" an overlay on the canvas?

I am hoping to use openseadragon svg-overlay to do my overlays:  

https://github.com/openseadragon/svg-overlay

One example of an overlay that I would like the user to be able to do is to simply draw a rectangle on the canvas to define a bounded region that may be of importance to the user.

In my internet search, I also found this issue from just a few days ago that is somewhat related:

https://github.com/openseadragon/openseadragon/issues/752

Thanks for any help!

**Comment by avandecreme** [comment]
You should checkout the [selection plugin](https://github.com/picturae/openseadragonselection).

**Comment by davepruitt** [comment]
Just checked it out.  It may work, but at the moment it doesn't seem like the perfect fit for my needs yet.  I'll keep playing with it to see if it works, but in the meantime, the above question still applies. :)

**Comment by dgutman** [comment]
Dave I have something that does that... but basically I "enable" drawing
mode and set the ZoomsPerClick = 1;  once I am done drawing, I toggle it
back

Check out:

http://node15.cci.emory.edu/DSA_LiveDev/

And click an image... once selected the drawing toolbar will pop up and you
can draw all of the shape primitives.  I haven't checked to see if the code
will work on the latest OSD version.... I am hoping to have some time in
the next few weeks to port over the code though....  feel free to email me
if you have any questions.

**Comment by davepruitt** [comment]
dgutman, that is actually almost exactly what I am looking to do.  In fact, my application will also be dealing with histological tissue, haha.  Basically, we have very large images containing tissue on microscope slides.  I want the user to be able to draw an outline around each individual tissue section (using a rectangle), and then mark features in the tissue using some homegrown annotations.  I hope you don't feel offended if I dive into your code to see how it works.  Thanks for the assistance.

**Comment by dgutman** [comment]
No please email me dagutman@gmail.com asap  and we can coordinate

I just got a grant to build our a digital histology platform...    I just
need to document  the annotation format...

**Comment by dgutman** [comment]
Also I'll split out the annotation code I write into a separate repo
similar to some of the other osd plugins.... I just haven't had time to fix
whatever breaks when I update to the latest osd version

**Comment by iangilman** [comment]
@dgutman Sounds great...I look forward to it!
