### ISSUE TITLE
Access original tileImages in tile-drawing handler

### ISSUE THREAD

**Issue by meihuisu** [openseadragon/openseadragon#762]
I have multiple greyscale images that were added via addTiledImages.  Is there a way to access
a  tiles  from different images  that were used to create the rendered context in tile-drawing handler?

**Comment by avandecreme** [comment]
I am not sure whether you want the tile or the tiledImage but you can get both:

```javascript
this.viewer.addHandler("tile-drawing", function(event) {
   var tile = event.tile;
   var tiledImage = event.tiledImage;
});
```

**Comment by meihuisu** [comment]
I need access to all other tileImages that are being 'drawn' into
the canvas. We want to try out different ways of blending various
channels into one canvas. I am not sure if this is the right handler
to use either. I need to find where and how various layers are being
drawn into the canvas in openseadragon.

----- Original Message -----

**Comment by meihuisu** [comment]
After traced some code and look into tutorial for html5 canvas, in order to get the additive blending
of composite images, we need to set globalCompositeOperation to "lighter" mode in
blendSketch function.

**Comment by meihuisu** [comment]
I am going to close this question because it is a wrong solution for my blending problem

**Comment by iangilman** [comment]
@meihuisu Btw, have you seen https://github.com/NIST-ISG/OpenSeadragonFiltering ?

**Comment by meihuisu** [comment]
Yes. I am using it to manage my filters. Since filters
are being invoked in tile-loading handler. Filters are
single tileImage based.

----- Original Message -----
