### ISSUE TITLE
How to change blending mode for composite images in layering

### ISSUE THREAD

**Issue by meihuisu** [openseadragon/openseadragon#765]
We want to have additive color blending  of multiple microscopy channel datas.  It looks like we
need to be able to set globalCompositeOperation option to "lighter' in blendSketch function.

**Comment by avandecreme** [comment]
To check if I understand correctly:
* You have 3 greylevels channels that you want to merge.
* You plan to use the filtering plugin to set each greylevel image to its corresponding color and then set the globalCompositeOperation?

Have you tested it (by hardcoding the parameter)?

**Comment by iangilman** [comment]
Yes, sounds like a quick test would be a good start. 

If we do add something like this, seems like it would go in TiledImage, like setOpacity. Maybe setCompositeOperation or something.

**Comment by meihuisu** [comment]
I have tested it with our viewer and it does work as we expected except that when opacity is 1 for
all channels. The resulting image should still have some color but the 'opaqueness' of the last
tiledImage seems to be special-cased into the result.

mei

**Comment by iangilman** [comment]
@meihuisu Yes, with opacity of 1, we don't go through the blendSketch function. The new setCompositeOperation would have to make sure that changes when the composite is something other than straight copy. 

Would you be up for writing a patch to add this in?

**Comment by meihuisu** [comment]
Got okay to go ahead.


----- Original Message -----

**Comment by iangilman** [comment]
Awesome :)

**Comment by meihuisu** [comment]
@iangilman, just want to confirm about the special handling of the original logic.
When compositeOperation is 'source-over' (the default) and opacity is 1, useSketch is false, otherwise, useSketch is true.

**Comment by iangilman** [comment]
@meihuisu Yes, that would be correct.

**Comment by avandecreme** [comment]
This can be closed :)
