### ISSUE TITLE
Incorrect Images or No Images Appear

### ISSUE THREAD

**Issue by AndrewRunion** [openseadragon/openseadragon#766]
Hello All,
I am dynamically loading the main image for OpenDragon using ASP.NET server side tags to assign the main image url and the image shows up properly for some images, shows the incorrect image for some images or shows nothing at all in the viewer. My javascript code is as follows:
  var highsmith = {
            Image: {
                xmlns: "http://schemas.microsoft.com/deepzoom/2008",
                Url: "<%=Session("dczPath")%>",
                Format: "jpg",
                Overlap: "1",
                TileSize: "256",
                Size: {
                    Width: "<%=Session("ImageWidth")%>",
                    Height: "<%=Session("ImageHeight")%>"
                }
            }
        };
 Any assistance would be appreciated.
Thank you,
Andrew

**Comment by avandecreme** [comment]
Did you check that the server return the correct url, width and height?

**Comment by AndrewRunion** [comment]
Antoine,
Yes I did, thank you for the suggestion though.
Best regards,
Andrew

**Comment by avandecreme** [comment]
Do you have any error message in the browser's console?
Could you paste the javascript generated by the server?

**Comment by AndrewRunion** [comment]
Antoine,
Here it is, thank you for your assistance.

Image: {


xmlns: "http://schemas.microsoft.com/deepzoom/2008",


Url: "http://xxxxxx.com/Images/ProductImages/AM3/",


Format: "jpg",


Overlap: "1",


TileSize: "256",


Size: {


Width: "6928",


Height: "5510"


}


}


};



var viewer = OpenSeadragon({


id: "osd1",


prefixUrl: "http://xxxxxx.com/openseadragon/images/",


tileSources: highsmith,


showNavigationControl: true,


homeFillsViewer: true,


mouseNavEnabled: true,


autoResize: true


});



window.addEventListener('resize', function () {


var newSize = new OpenSeadragon.Point(window.innerWidth, window.innerHeight);


viewer.viewport.resize(newSize, false);


viewer.viewport.goHome(true);


viewer.forceRedraw();


});


Andrew

**Comment by AndrewRunion** [comment]
Antoine,
I just wanted to check in and see if I could provide and other information.
Would it help if I sent you the code with the full path instead of xxxxxx.com?
Let me know please.
Thank you,
Andrew

From: Andrew Runion
Sent: Thursday, November 5, 2015 3:36 PM
To: 'openseadragon/openseadragon' <reply@reply.github.com>; openseadragon/openseadragon <openseadragon@noreply.github.com>
Subject: RE: [openseadragon] Incorrect Images or No Images Appear (#766)

Antoine,
Here it is, thank you for your assistance.

Image: {


xmlns: "http://schemas.microsoft.com/deepzoom/2008",


Url: "http://xxxxxx.com/Images/ProductImages/AM3/",


Format: "jpg",


Overlap: "1",


TileSize: "256",


Size: {


Width: "6928",


Height: "5510"


}


}


};



var viewer = OpenSeadragon({


id: "osd1",


prefixUrl: "http://xxxxxx.com/openseadragon/images/",


tileSources: highsmith,


showNavigationControl: true,


homeFillsViewer: true,


mouseNavEnabled: true,


autoResize: true


});



window.addEventListener('resize', function () {


var newSize = new OpenSeadragon.Point(window.innerWidth, window.innerHeight);


viewer.viewport.resize(newSize, false);


viewer.viewport.goHome(true);


viewer.forceRedraw();


});


Andrew

**Comment by avandecreme** [comment]
> Would it help if I sent you the code with the full path instead of xxxxxx.com?

I don't think so. Can you reproduce it on a small example without any server side magic?

**Comment by AndrewRunion** [comment]
Antoine,
Here is what it does for one I am having trouble with when there is no server code.
What do you think?
http://artifactmaps.tgabs.com/
Andrew

**Comment by avandecreme** [comment]
On that link, I get a 404 for all tiles.
If you open the developer console in your browser you should see lines like this:

```
"Tile 9/0_0 failed to load: http://artifactmaps.tgabs.com/Images/ProductImages/AM57/9/0_0.jpg" openseadragon.min.js:37:4077
"Tile 8/0_0 failed to load: http://artifactmaps.tgabs.com/Images/ProductImages/AM57/8/0_0.jpg" openseadragon.min.js:37:4077
"Tile 9/1_0 failed to load: http://artifactmaps.tgabs.com/Images/ProductImages/AM57/9/1_0.jpg" openseadragon.min.js:37:4077
"Tile 9/0_1 failed to load: http://artifactmaps.tgabs.com/Images/ProductImages/AM57/9/0_1.jpg" openseadragon.min.js:37:4077
```

You need to figure out what the correct URLs are.

**Comment by AndrewRunion** [comment]
Antoine,
I made a complete rookie mistake.
My file structure was different for all of the images I was having an issue with.
Thank you for helping me figure this out.
Have a great weekend.
Best regards,
Andrew
