### ISSUE TITLE
Openseadragon preview mode ? 

### ISSUE THREAD

**Issue by nikitochak** [openseadragon/openseadragon#767]
Is there some kind of preview mode for the openseadragon? I need it to stop handling events, stop moving, stop anything just like a simple image in img tag ? The main goal is to block the current openseadragon event system so I can write and use my own event handlers ?

**Comment by msalsbery** [comment]
Try setting mouseNavEnabled to false in the creation settings.

**Comment by nikitochak** [comment]
Thanks, I did it but still when I click on the image it zooms in. When I print the viewer I see its mouseNavEnabled property to be false. It seems that either this is not a solution or I am wrong somewhere.

**Comment by avandecreme** [comment]
I am not sure whether this is the best solution, but you can entirely constrain the viewer.
If you look at the second example [here](http://openseadragon.github.io/examples/ui-zoom-and-pan/), adding `panVertical: false` should do the trick.

OpenSeadragon({
    ...
    panHorizontal: false,
    panVertical: false,
    defaultZoomLevel: 1,
    minZoomLevel: 1,
    maxZoomLevel: 1,
    visibilityRatio: 1,
    ...
});

**Comment by iangilman** [comment]
Odd that mouseNavEnabled isn't fixing it. What if you call `viewer.setMouseNavEnabled(false)` after it's created?

**Comment by msalsbery** [comment]
Indeed...it works on the navigator viewer

**Comment by nikitochak** [comment]
Yes, when I use the viewer.setMouseNavEnabled(false) it solves the problem :) Thanks.
