### ISSUE TITLE
Scroll screen instead zoom image?

### ISSUE THREAD

**Issue by diegopolido** [openseadragon/openseadragon#768]
How could I scroll the screen instead zoom the image?

**Comment by diegopolido** [comment]
I already disabled the zoom with the config below:

      gestureSettingsMouse: {
        scrollToZoom: false
      }

but I still need to scroll the page when my mouse pointer is on the image. Is it possible?

**Comment by avandecreme** [comment]
This works for me. What version are you using?

**Comment by avandecreme** [comment]
I just noticed it does not work hover the navigator though.

**Comment by diegopolido** [comment]
OpenSeadragon 1.1.1

I will try to update and test again.. Thanks!

**Comment by diegopolido** [comment]
Yeah.. It didn't work on the latest version also.

**Comment by avandecreme** [comment]
Do you mean it still doesn't work on 2.0?

**Comment by diegopolido** [comment]
yeah

**Comment by avandecreme** [comment]
Does it work for you [here](http://codepen.io/anon/pen/vNQzVY)?

**Comment by diegopolido** [comment]
Sorry man! My browser cached the older version!

It works on the 2.0!

Thanks a lot!!!!!
