### ISSUE TITLE
Can DZITileSource take varying sized tiles

### ISSUE THREAD

**Issue by meihuisu** [openseadragon/openseadragon#770]
We have converted our  images from czi to dzi and it contains tiles of various size even within
the same layer.  They have starting points and shape size info instead of rows and columns

**Comment by avandecreme** [comment]
>We have converted our images from czi to dzi and it contains tiles of various size even within
the same layer.

Doesn't sound like DZI to me :)
However you could write a [custom tile source](http://openseadragon.github.io/examples/tilesource-custom/).

>They have starting points and shape size info instead of rows and columns

This part might be problematic because you won't be able to know the URL of a tile  for a given level, x and y coordinates. One option would be to have an extra file with all the mapping I guess (the same way the dzi format has an xml file giving the tile size and image dimensions).

Any reason to use such a pyramid type? How did you generate it?

**Comment by meihuisu** [comment]
The pyramid structure is in the czi file already. We just extracted the info and tiles into dzi conforming
structure.

**Comment by meihuisu** [comment]
It looks like it might still requires a fixed sized tile per level

**Comment by avandecreme** [comment]
I don't even think we support different tile sizes per level.
Maybe you can try to build a DZI pyramid with [pyramidIO](https://github.com/NIST-ISG/pyramidio).
Apparently, the czi format is supported by imageio which is used by pyramidIO. So it may work.

**Comment by meihuisu** [comment]
pyramidIO does not have any info on whether it can read the CZI pyramid format.

Our tiles have start positions and shape size info. The last thing would be to reprocess all tiles
into fixed sized tiles but it is rather hairy because there are overlap and alignment problem among them.

----- Original Message -----

**Comment by avandecreme** [comment]
>pyramidIO does not have any info on whether it can read the CZI pyramid format.

Yes, I don't have any CZI to test it but it might be as simple as running:
```
java -jar pyramidio-cli-0.0.3.jar -i your-image.czi -o your-output-folder
```
You can download the jar from here: https://github.com/NIST-ISG/pyramidio/releases

**Comment by meihuisu** [comment]
I failed to make it work.

Error while building the pyramid.
java.io.IOException: No codec found for image a.czi
	at gov.nist.isg.pyramidio.BufferedImageReader.<init>(BufferedImageReader.java:35)
	at gov.nist.isg.pyramidio.cli.Main.main(Main.java:153)

**Comment by avandecreme** [comment]
Hum, after making some more research, it looks like the czi reader is in another jar.
This is out of the scope of openseadragon so if you would like to continue pursuing this, you can create an issue on https://github.com/NIST-ISG/pyramidio and I will be glad to help. I am quite confident that we can get it working but I might need a czi file example.
