### ISSUE TITLE
Prevent right click download of image?

### ISSUE THREAD

**Issue by terenceingram** [openseadragon/openseadragon#771]
Is there a way to prevent the right click download of the image in the viewer?

**Comment by Bragolgirith** [comment]
You could add an '[oncontextmenu](http://www.w3schools.com/jsref/event_oncontextmenu.asp)' event handler to the image container element, like this:

    <div id="image-container" oncontextmenu="return false;"></div>

This will disable right-clicking on most browsers.

**Comment by iangilman** [comment]
...but it's not a feature we directly support in OSD. 

Note that if you right click download, you get just what's showing in the viewer at the moment, not the entire high resolution image.

**Comment by terenceingram** [comment]
Thanks @Bragolgirith. It works.
