### ISSUE TITLE
Global overlays with existing elements + sequenceMode = lost overlays

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#774]
If you specify global overlays in the options while creating your viewer, and if those overlays reference existing DOM elements (rather than creating new ones), and if you're using sequenceMode, the overlays are lost when you switch pages. 

This is because when we switch pages we call Viewer.close() which clears out the overlays including destroying their elements. For overlays that create new elements each time, this isn't a problem, but for ones that rely on existing elements, it is. 

The solution might be to convert the initial overlay specification into actual overlay objects and store that between pages. 

Keep in mind that we're planning on moving sequenceMode into a plugin (#649). 

To see this issue in action, you can go to the "overlaying complex html" example on: 

http://openseadragon.github.io/examples/ui-overlays/

...and switching pages (with the arrow buttons in the viewer). 

Note that the "viewport overlays" section has sequenceMode with global overlays that create new elements, and it has no trouble.

**Comment by boskar** [comment]
Please note that the element is NOT destroyed, yet it is not visible. 

Related with https://github.com/openseadragon/openseadragon/issues/434

**Comment by iangilman** [comment]
Indeed...it's removed from the DOM here: 

https://github.com/openseadragon/openseadragon/blob/master/src/overlay.js#L187

...so it shouldn't be too hard to add back in if we keep track of the Overlay object.

**Comment by imoutsatsos** [comment]
Is there any progress on this? I dynamically create tileSources and overlays that I would like to preserve while the user is browsing in sequence mode. Right now they dissappear once the user moves to the next page. Reading through the issues and reviewing the DOM, it seems that OSD adds the style with ```display: none``` to the div I'm using for the ovelay. Are there any workarounds?

**Comment by iangilman** [comment]
It doesn't look like there's been any progress on this... you're welcome to pick it up if you'd like!

As for workarounds, I suppose you could listen for `page` events and remove the `display: none` from your overlays.

**Comment by iangilman** [comment]
Fixed by https://github.com/openseadragon/openseadragon/pull/1865
