### ISSUE TITLE
Get position (coordinates) of mouse in current Tile (Image)

### ISSUE THREAD

**Issue by Sityle** [openseadragon/openseadragon#776]
Hallo,

how can i get the position on the current Tile (Image) in image-coordinates. So let me explain a little bit more.
I have a big image and when you zoom they get replaced by other images. Imagine the mouse is on the Tile (Image) 13_34.png which is 320x320pixel (x=0 and y=0 is on the bottom left of this image) and the mouse is for example in the middle left of this image so than i want to get x=0 and y=160.

Hope you understand what i mean.

**Comment by iangilman** [comment]
We don't currently have a direct API for this, but you can figure it out by examining the `lastDrawn` property of your TiledImage. It's an array of Tile objects, and they all know their locations (in web coordinates, I believe; the same as the mouse event). For instance, take a look at the debug info drawing code: 

https://github.com/openseadragon/openseadragon/blob/master/src/tiledimage.js#L1378

**Comment by Sityle** [comment]
I can't figure it out how i will use this. Do i have to set the param debugMode: true to see this debugInfos ? Sry.

Is there no way to get this information ? OpenSeadragon knows on which image im moving. I only want the image coordinates of this tile.

**Comment by iangilman** [comment]
@Sityle You don't need to turn debug mode on; I was just saying you could use that code for reference. At any rate, here is the idea: 

```
viewer.addHandler('canvas-click', function(event) {
    console.log('click', event.position);
    var tiledImage = viewer.world.getItemAt(0);
    var tile, tileRight, tileBottom;
    for (var i = 0; i < tiledImage.lastDrawn.length; i++) {
        tile = tiledImage.lastDrawn[i];
        tileRight = tile.position.x + tile.size.x;
        tileBottom = tile.position.y + tile.size.y;
        if (event.position.x >= tile.position.x && event.position.x < tileRight &&
                event.position.y >= tile.position.y && event.position.y < tileBottom) {
            console.log('clicked on tile ' + tile.x + ',' + tile.y + '; relative coordinates: ' +
                (event.position.x - tile.position.x) + ',' + (event.position.y - tile.position.y));
        }
    }
});
```

Let me know if that works for you. 

Btw, I'm curious what you're working on that needs this info; I'd love to know more about your use case.

**Comment by Sityle** [comment]
@iangilman first of all thank you for your fast answer. This works for the moment so far that there is one problem with that. The problem the tile size changing by zoom, so that i cant get the right position in this image  The more i zoom the bigger the coordinates. For example the image is in truth 420x420 but when i zoom in and click on the bottom right i get 760x760. Normally this would be out of range by his image. Is there any possibility to normalize ?

OK let me tell you a little bit about my project, a little bit because its really secret at this time. The project is about placing objects in a big image. For this i need the position of the mouse on the current image so that i can place an object at this position.

**Comment by Sityle** [comment]
@iangilman i did it by this steps:

1. Getting image dimensions
2. Calulating the factor between img.width and tile.size.x, img.height and tile.size.y

And with it i can scale into my original picture dimensions.

Thank you !

**Comment by iangilman** [comment]
@Sityle Glad to hear you got a solution that works! And thank you for the info about the project. Please share it when it's no longer secret; I'd love to see it in action and add it to our "in the wild" page.
