### ISSUE TITLE
next button click pops up virtual keyboard on mobile devices

### ISSUE THREAD

**Issue by michaelw3** [openseadragon/openseadragon#777]
hi
i implemented the opeanseadragon with tilesource option and found out that when pressing the next button in navigator it pops up the keyboard.

thank in advance for any help

**Comment by iangilman** [comment]
Hmm...I thought we'd fixed this. What version of OSD are you using? What mobile device? Is it just the "next" button or all the other buttons? What if you tap on the image?

**Comment by michaelw3** [comment]
Thanks for the fast reply.
I'm using version - 2.1.0
I've checked it on Chrome(45.0.2454.94)  and on Firefox(will check v. later) for android running on lollipop and kitkat.
It happens every time touching next and back button and the reference strip images.
On the +, - , home, fullscreen it doesn't all the time but most of it.
When taping on the image itself it doesn't occur.

**Comment by iangilman** [comment]
I see...looks like it just has to do with the ReferenceStrip. For some reason we're still creating a `textarea` there (even though we removed the textarea from the main viewer a while ago). Fixing this is probably just a matter of changing `textarea` to `div` on this line: 

https://github.com/openseadragon/openseadragon/blob/master/src/referencestrip.js#L439

@michaelw3 Would you be up for giving that a try?

**Comment by msalsbery** [comment]
There may be an alignment issue if switching elements. Maybe review the patch that removed it from the main viewer...

**Comment by michaelw3** [comment]
@iangilman I'm supposed to download that file?
right now i just have the openseadragon.js file

**Comment by iangilman** [comment]
@msalsbery Good point...here is that PR for reference: https://github.com/openseadragon/openseadragon/pull/569

@michaelw3 Actually I was pointing out where in the code the modification could be made. It would require pulling down this repository and following the build instructions in the README. This is in case you're up for making a patch to fix this issue. If not, the information is here in case someone else wants to come fix it.

**Comment by michaelw3** [comment]
@iangilman  OK thanks iwll give it a try.
will let you know when i did.

**Comment by TMUND** [comment]
PR for suggested fix: #779
