### ISSUE TITLE
Difference between onclick and mousemove 

### ISSUE THREAD

**Issue by Sityle** [openseadragon/openseadragon#786]
Why i get difference positions between onclick and mousemove ?
I have 2 function first:

viewer.addHandler('canvas-click', function(event) {

second function:

var $viewerElement = $('#container').on('mousemove', function(event) {...

if i try this event.clientX int the canvas-click method i get undefined i have to use event.position.x but in the second function i cant use event.position.x here i have to use event.clientX - why ?

And when i say it doesnt matter it is just important that these positions are the same i get difference outputs. The event.position.x in the canvas-click method is 8 position less then the event.clientX from the onmousemove Method. But im always in one and the same position. So im frustrated.

Hope you can help me ones more ...

**Comment by msalsbery** [comment]
canvas-click is an OpenSeadragon event, mousemove is a DOM event.

If you use mousemove then you'll need to use event.originalEvent in your canvas-click handler to get at the DOM event coordinates.

Better is to add a moveHandler to the viewer's MouseTracker...its handler will have an event.position that matches the one in canvas-click.

**Comment by Sityle** [comment]
Ok can you give me a code example for this ?
