### ISSUE TITLE
Overlay to Image Rectangle

### ISSUE THREAD

**Issue by jerblsdll** [openseadragon/openseadragon#787]
Is there a way to get the relative size of an overlay in pixels compared to the original image?  For example, I can create an overlay by doing this:

<code>var overlay = viewer.viewport.imageToViewportRectangle(2686, 968, 584, 36);</code>

I'd like to be able to grab an overlay, and convert it back to the original pixel dimensions? I'd like to be able to pass the pixels back to allow for cropping, etc.

I've tried viewer.viewport.viewportToImageRectangle but that doesn't seem to be doing what I think it should.  This is what I'm doing and what it's returning:

<code>var x = $(this).css('left').replace("px", "");</code>
<code>var y = $(this).css('top').replace("px", "");</code>
<code>var w = $(this).css('width').replace("px", "");</code>
<code>var h = $(this).css('height').replace("px", "");</code>
<code>var rect = viewer.viewport.viewportToImageRectangle(x,y,w,h);</code>

<code>height: 270137
width: 749768
x: 2166609
y: 209494</code>

I also tried

<code>var overlay = viewer.viewport.imageToViewportRectangle(x, y, w, h);</code>
<code>var rect = viewer.viewport.viewportToImageRectangle(overlay);</code>

but that doesn't work either.

Thanks in advance.

**Comment by avandecreme** [comment]
The x, y, w, h returned by jQuery are in browser coordinates.
By the way I would recommend using this instead of the css:
```javascript
var x = $(this).offset().left;
var y = $(this).offset().top;
var w = $(this).width();
var h = $(this).height();
```
The offset method will give you windows coordinates.
You can then use [`viewport.windowToImageCoordinates`](http://openseadragon.github.io/docs/OpenSeadragon.Viewport.html#windowToImageCoordinates) to convert to image coordinates.
Note that OSD does not provide a windowToImageRectangle method. Here is what you can do:

```javascript
var topLeft = viewer.viewport.windowToImageCoordinates(x, y);
var bottomRight = viewer.viewport.windowToImageCoordinates(x + w, y + h);
var rect = new OpenSeadragon.Rect(
    topLeft.x,
    topLeft.y,
    bottomRight.x - topLeft.x,
    bottomRight.y - topLeft.y);
```

**Comment by jerblsdll** [comment]
Thanks!  I had to modify your solution to work because I was getting an a.minus is not a function error, so I fixed it by doing this:

<pre>var Point1 = new OpenSeadragon.Point(x, y);
var Point2 = new OpenSeadragon.Point(x + w, y + h);

var topLeft = viewer.viewport.windowToImageCoordinates(Point1);
var bottomRight = viewer.viewport.windowToImageCoordinates(Point2);</pre>

**Comment by leesei** [comment]
I suppose this can be closed?

**Comment by iangilman** [comment]
Sure. I should probably go through and close a bunch of old questions.
