### ISSUE TITLE
Zoom on touch devices at center of touch contacts instead of center of canvas.

### ISSUE THREAD

**Issue by nmengers** [openseadragon/openseadragon#788]
Hello,

I'm not sure if this question has been asked before but I could not really find it using the search function.

When I pinch to zoom in on an OpenSeaDragon canvas the zooming always seems to happen on the center of the canvas instead of the centerpoint between the touch contacts as I'm used to when I'm using native zooming on my touch device.

Would it not be a nice feature to be able to also zoom in on the place between the touchcontacts by for example setting an option?

**Comment by iangilman** [comment]
Good point! This would be a great enhancement. Would you be interested in looking into implementing it? @msalsbery might have some thoughts to add.

**Comment by msalsbery** [comment]
It used to work that way. I noticed it was broken a while back and it's on my todo list

**Comment by nmengers** [comment]
I could give it a try. Where do you suggest I start searching for the problem @msalsbery ? Could you give me some tips. Or do you prefer to solve this yourself?

**Comment by illtud** [comment]
This is being addressed in #800 ?

**Comment by iangilman** [comment]
Yes, I believe fixing #800 should fix this.

**Comment by iangilman** [comment]
#800 has been fixed by #1184, so I believe that fixes this as well.

**Comment by cavenel** [comment]
Hello,

Is this still fixed in 3.0.0? By default it still seems to zoom to center of canvas instead of center of touch contacts. Or is there an option to change this behavior?
