### ISSUE TITLE
Converting coordinates Viewportpoint and pixel and back

### ISSUE THREAD

**Issue by Sityle** [openseadragon/openseadragon#789]
Hi

i have tried over 6 hours i dindt get it done. So im getting crazy. The problem:
I convert a pixel into a viewportPoint this way: "viewer.viewport.pointFromPixel(pixel);" in my OnMouseOver function. After that i save the coordinates of this viewportPoint (x and y).

Later in my MouseClick i want to do it backwards. So from the coordinates of the viewportPoint (x and y) that i have saved i want to get a pixel. I found "pixelFromPoint" method but this method need a viewportPoint-Object and i dont know how to create it. I just have the coordinates of the viewportPoint but not the Object at all.

**Comment by avandecreme** [comment]
You can create it like this:
```javascript
var point = new OpenSeadragon.Point(x, y);
```

**Comment by Sityle** [comment]
Are you sure ? Is this the way i get a pixel from a viewportPoint ?

**Comment by Sityle** [comment]
I want to convert not to create just a pixel. Converting a viewportpoint coordinate. Like when i convert a event.position.x to a viewportpoint. So i want this only backwards

**Comment by avandecreme** [comment]
> Is this the way i get a pixel from a viewportPoint ? 

No, what I mean is that if you have x,y coordinates of a viewport point, you can create the point and call pixelFromPoint like this:

```javascript
var point = new OpenSeadragon.Point(x, y);
var pixel = viewport.pixelFromPoint(point);
```

Let me know if this is not what you are looking for.

**Comment by Sityle** [comment]
Thanks that works for me.
