### ISSUE TITLE
Rotation and overlays

### ISSUE THREAD

**Issue by boskar** [openseadragon/openseadragon#791]
Question about https://github.com/openseadragon/openseadragon/pull/782

Will added overlays rotate with the picture? I don't have any demo at the moment, 
@avandecreme  "The global idea that I have, is that every time a user call a viewport method with viewport coordinates, those coordinates should already have been rotated."

So adding overlays to rotated pictures == means we'll have to add them rotated too?

**Comment by avandecreme** [comment]
>Will added overlays rotate with the picture? 

I did not work on that yet but the plan is for it to be an option. See #193 

>So adding overlays to rotated pictures == means we'll have to add them rotated too? 

No, you would still provide (x,y) in viewport coordinates (or image coord with (px, py)) like now. The difference is that the computed location here: https://github.com/openseadragon/openseadragon/blob/master/src/overlay.js#L222 will now adjust for rotation.

**Comment by avandecreme** [comment]
Fixed by #896
