### ISSUE TITLE
How to change tilesource other than using gotopage()

### ISSUE THREAD

**Issue by myyan92** [openseadragon/openseadragon#797]
I have a lot of embeddings(large tiled images), say 100, organized into 20 groups. I want to have a drop down menu that let user choose a group, and only load embeddings in that group as tilesources. I have tried viewer.tilesource="path to new images" and it don't seem to work. What's the correct way to do it?

**Comment by avandecreme** [comment]
You should reopen every time: `viewer.open('path');`
