### ISSUE TITLE
zoomTo/zoomBy ignore refPoint if immediately is true

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#800]
The refPoint handling is done in `update` (where it's called zoomPoint): 

https://github.com/openseadragon/openseadragon/blob/master/src/viewport.js#L908-L920

...but since `immediately` calls `reset` on the spring: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewport.js#L777

...that part of update doesn't get exercised.

**Comment by iangilman** [comment]
Anyone want to tackle this?

**Comment by illtud** [comment]
I can't help with the coding, but I can confirm that this is an issue I'd like to see fixed!

**Comment by iangilman** [comment]
Fair enough; good to know.

**Comment by iangilman** [comment]
Note: Fixing this should fix #788.
