### ISSUE TITLE
Runtime overlays not working on github example.

### ISSUE THREAD

**Issue by horseatingweeds** [openseadragon/openseadragon#802]
The runtime overlay isn't working on the example.

https://openseadragon.github.io/examples/ui-overlays/

I've tried running the example code locally but it doesn't seem to work either.

**Comment by avandecreme** [comment]
Thanks for spotting this.
I made a PR for it.

**Comment by avandecreme** [comment]
In the mean time you can test on the http version: http://openseadragon.github.io/examples/ui-overlays/

**Comment by iangilman** [comment]
Good catch!

**Comment by horseatingweeds** [comment]
Thanks for the quick response. This is a really nice project!
