### ISSUE TITLE
Interactive change opacity of tilesource

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#804]
I've positioned two tilesources on top of each other and can set variables for opacity of each.
I want to change the opacity of a tilesource via click on a button id, or even add a transition upon the click to fade the object in or out.

Code below and page here:  http://deepzoomchattanooga.com/theboulevard.php

In this case, when the button is clicked I want the tilesource's opacity set by the value of op2 to change from 1.0 to 0.2.

What am I missing?  Thank you.

```
<button id="pg01">Change Opacity</button></div>
```
```
var op1 = 0.6;
var op2 = 1.0;

$("#pg01").click(function (){
var op1 = 0.1;
});

var viewer = new OpenSeadragon.Viewer({
    id: "openseadragon-canvas",
    prefixUrl: "/openseadragon/images_TEST/",
    navigationControlAnchor: OpenSeadragon.ControlAnchor.TOP_RIGHT,
    showHomeControl: false,
    showZoomControl: false,

    tileSources: [{
            x: 0.883,
            y: 1,
            width: 1,
            opacity: op2,
            tileSource: "/zoom/boulevard1/dzc_output.xml",
        },

        {
            x: 1,
            y: 1,
            width: 0.61,
            opacity: op1,
            tileSource: "/zoom/boulevard4/dzc_output.xml"

        }
   ] 
	
});

```

**Comment by avandecreme** [comment]
There are multiple issues with your code:

1. In the click handler, you are defining a new variable op1 which is local to that function.
To avoid that you should remove `var` and just have `op1 = 0.1`.

2. Even with the above fix, this code wouldn't work for 2 reasons:
  - javascript passes variables by value which means that even if you update op1, the opacity property in the tileSources array won't be updated
  - even if that value was updated by calling something like `tileSources[1].opacity = op1;`, OSD does not support updating the opacity this way.

So, what you should do is change your click handler like this:

```javascript
$("#pg01").click(function (){
   viewer.world.getItemAt(1).setOpacity(0.1);
});

```
The `viewer.world.getItemAt(1)` call retrieves the tiledImage on top and `setOpacity` changes the opacity.
See [the world](http://openseadragon.github.io/docs/OpenSeadragon.World.html) and [tiledImage](http://openseadragon.github.io/docs/OpenSeadragon.TiledImage.html) documentations.

**Comment by SamHall** [comment]
Antoine - Thank you for the solution and the details.
JavaScript is obviously not my strong point.  I tried many different attempts, and had actually at one time fixed issue #1 (the variable would show changed in the console) and narrowed the next part down to something that began with viewer.xxxx.

But alas, the API is a sea of possibilities and I look for / learn by examples vs. the API.

Your info will no doubt get me past the temporary block.

Thanks again,
Sam

**Comment by avandecreme** [comment]
>Can you suggest a way to apply CSS transitions to the opacity change or does it all have to occur within the js?

It has to be in JS. You will need to look into [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) (you can use OpenSeadragon.requestAnimationFrame to handle the browser compatibility for you)

**Comment by SamHall** [comment]
That's what I suspected.  Thanks again!

**Comment by iangilman** [comment]
@SamHall Here is an example of some code for doing an opacity fade with OSD: 

http://codepen.io/iangilman/pen/YXRLea

**Comment by SamHall** [comment]
Fantastic! That's a great working example.

Question - 
for setOpacity can the value be a variable set external to the script on the same page?
I'm thinking of using a data slider to allow interactive opacity.
Such as:  https://github.com/loopj/jquery-simple-slider

   viewer.world.getItemAt(1).setOpacity('variable and or ID');

I'll experiment...

Thanks again.
Sam

**Comment by avandecreme** [comment]
You can and we have an example for using the [jQuery UI slider](https://jqueryui.com/slider/) to set the rotation here: http://openseadragon.github.io/examples/ui-rotation/

For opacity it would be:
```javascript
$("#slider").slider({
    min: 0,
    max: 100,
    slide: function(event, ui) {
        viewer.world.getItemAt(1).setOpacity(ui.value / 100);
    }
});
```

**Comment by SamHall** [comment]
Opacity slider works!
Now to finish the content.
Thanks again for the fast responses.

 http://deepzoomchattanooga.com/theboulevard.php

**Comment by iangilman** [comment]
@SamHall Beautiful page! I love this idea of fading into the future/past. Really cool.
