### ISSUE TITLE
Injecting complex html element in world view

### ISSUE THREAD

**Issue by robhicks** [openseadragon/openseadragon#808]
Is it possible/recommended to use the world view to build a grid of images with functionality similar to the following graphic? Currently, we are building a grid of images outside of Openseadragon and when the user selects an image (view image in the dropdown menu), using Openseadragon to display the deep zoom image. 

<img width="1327" alt="screen shot 2015-12-28 at 5 36 52 am" src="https://cloud.githubusercontent.com/assets/719152/12018826/59c29d3c-ad25-11e5-8026-c3f2e83e5409.png">

**Comment by avandecreme** [comment]
Building a grid is definitely possible. Here is [an example](https://familysearch.org/search/film/005454739?i=4&wc=QZXP-6T4%3A790104201%2C790172601%2C795602301%2C951977601%3Fcc%3D2000219&cc=2000219) (click on the icon under the + and - signs to view the grid).
There is also the [m2 demo](https://github.com/openseadragon/openseadragon/tree/master/test/demo/m2).

Regarding the complex html, that will be more complicated. You will need to use [overlays](http://openseadragon.github.io/examples/ui-overlays/).

I am curious, what is the reason to change your current implementation?

**Comment by robhicks** [comment]
@avandecreme, our current implementation doesn't scale past 3000 images. I have tried adding using the familysearch common image viewer and adding overlays to the cells but that didn't scale either and really confused angular. The overlays are compiled and attached to the DOM before adding them to the cells.

**Comment by avandecreme** [comment]
With that many images, I guess they don't all fit in the screen so maybe you could have some sort of pagination?

**Comment by iangilman** [comment]
This is another project that's mixing an OpenSeadragon grid with HTML: https://github.com/sul-dlss/iiifManifestLayouts

It can certainly be done, but some care is necessary to marry the OSD image with the HTML content. Also, if you're dealing with something like 3000 images, you'll need to be dynamic about how you load and manage the HTML content; OpenSeadragon will load just the images it needs to display what's on screen at the moment, but you'll still run into slowdowns if you build 3000 overlays. You'll want to be smart about which overlays are on the screen at the moment. It may also help to constrain so you can't zoom out far enough to see all of the images at once, or disable the overlays once you've zoomed out that far.

**Comment by robhicks** [comment]
@iangilman Thanks for the response. I'll have to work on it according to your advice.

**Comment by iangilman** [comment]
Sounds good. Keep us posted on your progress :)
