### ISSUE TITLE
Trying to use the Viewport Coordinates example: Cannot read property 'minus' of undefined

### ISSUE THREAD

**Issue by BenjW** [openseadragon/openseadragon#809]
I'm trying to set a canvas-click event handler on the viewer so I can capture where the user clicks on the image. When I use the code from the example here: http://openseadragon.github.io/examples/viewport-coordinates/

I get an error: Uncaught TypeError: Cannot read property 'minus' of undefined

Coming from openseadragon.js line 17190

Here is the code I'm using. My viewer is called viewer. Thanks. 

//Assuming we have an OpenSeadragon Viewer called "viewer", we can catch the clicks 
//with addHandler like so:
viewer.addHandler('canvas-click', function(target, info) {
 // The canvas-click event gives us a position in web coordinates.
 var webPoint = event.position;

 // Convert that to viewport coordinates, the lingua franca of OpenSeadragon coordinates.
 var viewportPoint = viewer.viewport.pointFromPixel(webPoint);

 // Convert from viewport coordinates to image coordinates.
 var imagePoint = viewer.viewport.viewportToImageCoordinates(viewportPoint);

 // Show the results.
 console.log(webPoint.toString(), viewportPoint.toString(), imagePoint.toString());
});

**Comment by BenjW** [comment]
*sigh*  I figured it out just now. event.position was coming up undefined, obviously because event wasn't coming is. I replaced "target, info" with "event" for the params in the addHandler function. I'm capturing the coords now.

**Comment by iangilman** [comment]
Good catch! The example code should be fixed.

**Comment by avandecreme** [comment]
Can be closed as well.

**Comment by iangilman** [comment]
@avandecreme Thanks for spotting all these! Thank goodness for blizzards ;)
