### ISSUE TITLE
MIT license in copypasted code

### ISSUE THREAD

**Issue by bgilbert** [openseadragon/openseadragon#81]
1. OpenSeadragon contains some code attributed to jQuery and some code attributed to [mattsnider.com](http://mattsnider.com/).  Both of these are MIT licensed, so we won't be able to get rid of MIT altogether.  However, I suggest we move those pieces to a separate source file with separate copyright blocks, and keep the remainder of the project clearly under BSD.
2. In the mattsnider.com case, we also need to document this better.  The [About page](http://mattsnider.com/blog/about/) of the blog and the text of the [cited reference](http://mattsnider.com/cross-browser-and-legacy-supported-requestframeanimation/) do make the license very clear, but those may disappear from the Internet someday.
3. Are there any other copypasted fragments that are not attributed?

**Comment by msalsbery** [comment]
Are we good on this? Can we close?

**Comment by jpstroop** [comment]
No concerns here, FWIW

**Comment by bgilbert** [comment]
Yeah, I think we've done as well as we can here.

**Comment by iangilman** [comment]
Looks good… Closing :-)
