### ISSUE TITLE
Inaccurate overlay position

### ISSUE THREAD

**Issue by bschoenfeld** [openseadragon/openseadragon#810]
http://portsolutionintegrators.github.io/openseadragon-overlay-issue/

In this example, the overlay is close to the correct position, but offset slightly from where it should be. Below the OpenSeadragon window, I've included a screen shot of where GIMP says the overlay should be.

I thought this might be an issue with the tile source, but I've added an overlay for the entire image and it is perfect.

Any idea what could be causing this?

Here's a screenshot, in case the demo goes down.
![screen shot 2015-12-30 at 3 33 56 pm](https://cloud.githubusercontent.com/assets/565347/12057020/ed78274a-af0a-11e5-941c-6b89e57f8f0c.png)

**Comment by avandecreme** [comment]
It looks like a bug.
 Do you reproduce it with OSD 2.0?
I am wondering if I have broken something with https://github.com/openseadragon/openseadragon/pull/741

To debug, you could also display the cursor coordinates and check that they match the overlay position.

**Comment by bschoenfeld** [comment]
I was able to reproduce it in every version back to 1.1.0. I'll add the cursor coordinates to the example now.

**Comment by bschoenfeld** [comment]
We finally figured out that it is indeed a problem with our tiles. I think we have some errant pixel overlap setting or some such. The result is that our image is stretched and slightly cropped in the viewer, hence the offset. Thanks for the quick response. Sorry to bother you before digging further on our side first. This is a terrific project.

**Comment by avandecreme** [comment]
Glad you figured it out.
It looks like a new use case for OpenSeadragon compared to what we already have here http://openseadragon.github.io/examples/in-the-wild/
So don't hesitate to share a link when you have something ready :)

**Comment by bschoenfeld** [comment]
Sure thing.

A warning to anyone who might find this. The bug is actually in our Deep Zoom tile generator, VIPS. The documentation says that the default overlap setting is 0, but it is actually 1. You have to specify and overlap of 0. We will reach out to that team and let them know about the bug.

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-VipsForeignSave.html#vips-dzsave

![pasted image at 2015_12_31 12_02 pm](https://cloud.githubusercontent.com/assets/565347/12066526/152c3464-afb7-11e5-8a29-953968746ed2.png)

**Comment by bschoenfeld** [comment]
The documentation error was fixed a couple weeks ago. Yay open source :smile: 

https://github.com/jcupitt/libvips/commit/bf7bca18515983b6547deb3c09359c3a6d0dbdbc
