### ISSUE TITLE
copying parts of canvas with getImageData

### ISSUE THREAD

**Issue by altert** [openseadragon/openseadragon#811]
I'm trying to copy part of picture shown in viewer with current zoom level. I use getImageData on canvas element that is used by OSD, but it seems that only one of the tiles data is copied that way, so parts of image is missing. Is there another way to do it?

**Comment by avandecreme** [comment]
This should work. Do you have any code/demo to share?

**Comment by altert** [comment]
Unfortunately I can't show demo at the moment, but code is like this (I'm copying part of screen to another div:

    ctx=jQuery(".openseadragon-canvas").children()[0].getContext("2d");
    imgData=ctx.getImageData(x,y,w,h);
    ctx2=jQuery("#pinnedcanvas")[0].getContext("2d");
    ctx2.putImageData(imgData,0,0);

Resulting image pinnedcanvas div gets part of the selection, usually top part (on high zoom levels more parts are mising from resulting image)

**Comment by avandecreme** [comment]
Where are x,y,w,h coming from?
Do you reproduce the issue with:
```javascript
var canvas = jQuery(".openseadragon-canvas").children()[0];
var ctx = canvas.getContext("2d");
imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);
```

**Comment by altert** [comment]
x,y,w,h come from another div I use for selecting part of the image. 
Yes, I can reproduce the issue with your code as well.

**Comment by iangilman** [comment]
This certainly seems like it should work. How about if you use `var ctx = viewer.drawer.context`? Also, when are you doing this? If you're only getting part of the image, maybe you're in the middle of a draw call? Seems unlikely, but had to ask. 

At any rate, a simplified repro would definitely help.

**Comment by altert** [comment]
Thanks for the answers, I've prepared test case to show it here, but couldn't reproduce the issue there. After further investigation I've found out that the actual problem with my orginal code was the target canvas size (div with canvas I've copied data to was created dynamically) Sorry for confusion and thanks again. The issue can be safely closed.

**Comment by iangilman** [comment]
Good to hear you got it sorted out!
