### ISSUE TITLE
Blank navigator when viewer canvas becomes too small

### ISSUE THREAD

**Issue by rleonard04** [openseadragon/openseadragon#812]
Hi,

I'm having an issue when using the "navigatorMaintainSizeRatio" attribute. The solution enables a user to add multiple image viewers to the window. As each additional viewer is added the existing viewers are resized. This works perfectly for 2 viewers (with the screen split vertically), however, when I add subsequent viewers, the existing navigators will resize, but will become blank. This can be avoided by dramatically increasing the navigatorSizeRatio (from 0.2 to 0.4). I have noticed that this can also be replicated by having one viewer take up the entire window, then resizing the window to a point which the nvaigator will become blank.

Thanks!

**Comment by iangilman** [comment]
Interesting. What are you trying to accomplish? You're putting multiple viewers on the screen and each has a navigator?

**Comment by rleonard04** [comment]
Yes, that's exactly it. I have noticed that if you create the viewer at a size you know the navigator is blank it will appear fine. I did try to clear the navigator cache, but that didnt seem to solve the issue. Are there any steps that I could take detroy the navigator and re-instantiate?

**Comment by iangilman** [comment]
Not that I know of; they're pretty tightly coupled. Sounds like another reason for #492. 

Do you have a repro you can share a link to?

**Comment by rleonard04** [comment]
Hi, Just an update on this. I was able to solve this in a resize event listener which checked to see if the navigator canvas had become blank (comparing "DataURL" values of a blank canvas of equal size). If so, I remove the old (blank navigator) from the DOM, $('#'+this.openSeaDragonViewer.navigator.id).remove(); and re-instantiate using the openseadragon navigator constructor method "new OpenSeadragon.Navigator" wilst setting the "id" attribute to "false" or "null" forcing a redraw.

**Comment by iangilman** [comment]
Sorry you had to hack it like that, but I'm glad you found something that works. 

If you get a chance it would still be great to have a repro to help someone fix the underlying issue.
