### ISSUE TITLE
imageToViewportRectangle data from db

### ISSUE THREAD

**Issue by ozgunlu** [openseadragon/openseadragon#817]
I get a rect using selection plugin :

selection =viewer.selection({
    onSelection: function(rect) {
        console.log(rect.x);
        console.log(rect.y);
        console.log(rect.width);
        console.log(rect.height);
        var elt = document.createElement("div");
        elt.id = "runtime-overlay";
        elt.className = "highlight";    
        viewer.addOverlay({
                element: elt,
                location: viewer.viewport.imageToViewportRectangle(rect)
            });

        input = "rect_x="+rect.x+"&rect_y="+rect.y+"&rect_w="+rect.width+"&rect_h="+rect.height+"&plink=<?=$plink?>&case_id=<?=$case_id?>&mode=add";
        $.ajax({
            url : "handlers/H_AnnotationHandler.php",
            data : input,
            type : "post",
            dataType : "json",
            success : function(response) {
                if (!response.error)
                    alert("success");
                else 
                    alert("failed");
            }
        });
    }
});

And i store the rect in mysql via H_AnnotationHandler.php. After that, when i try to use this data like that :

$.ajax({
    url : "handlers/H_AnnotationHandler.php",
    data : "case_id=<?=$case_id?>&plink=<?=$plink?>&mode=get",
    type : "post",
    dataType : "json",
    success : function (response) {
        if (!response.error) {
            for (var i = 0; i < response.annots.length; i++) {
                var elt  = document.createElement("div");
                elt.id = "runtime-overlay" + i;
                elt.className = "highlight";
                viewer.addOverlay({
                    element: elt,
                    location : viewer.viewport.imageToViewportRectangle(parseInt(response.annots[i].rect_x), parseInt(response.annots[i].rect_y), parseInt(response.annots[i].rect_w), parseInt(response.annots[i].rect_h))
                });
            }
        }               
    }
});

it create a runtime-overlay division but left, top, height and width seems very wrong. (27094e+04 etc.)

note : i am sure, sql data is true. i compare it before take.

**Comment by avandecreme** [comment]
See my comment there: http://stackoverflow.com/questions/34744842/openseadragon-imagetoviewport

**Comment by avandecreme** [comment]
@iangilman This can be closed (resolved on SO).
