### ISSUE TITLE
How to restrict image visible area?

### ISSUE THREAD

**Issue by zeleniy** [openseadragon/openseadragon#829]
I have an image similar to this one - http://bl.ocks.org/mbostock/1557377 - set of circled objects on one big canvas. I want to restrict user with only one object. For this i do next steps:

1). Set appropriate zoom level to see only one entire object in viewport.
```
viewer = OpenSeadragon({
  ..,
  minZoomLevel: 9.375,
  ..
});
```

2). Move viewport to required object:
```
var rect = new OpenSeadragon.Rect(0.05, .73, .08, .08);
viewer.addHandler("open", function() {
  viewer.viewport.fitBounds(rect, true);
});
```

3). And finally add my own drag handler to restrict user:
```
viewer.addViewerInputHook({hooks: [
  {tracker: 'viewer', handler: 'dragHandler', hookHandler: function(event) {
    event.stopHandlers = true;
    var center = viewer.viewport.viewerElementToViewportCoordinates(event.position);
    viewer.viewport.panTo(center, true);
  }}
]});
```

But when i drag an image it moves almost random. So how i can implement my own correct drag handler?

**Comment by iangilman** [comment]
Do you want to disable all panning? If so, you can use the `mouseNavEnabled` option (set it to false).

**Comment by zeleniy** [comment]
No. I want to write my own drag handler which will disallow to move images beyond required area. For example area restricted by `rect` variable

**Comment by iangilman** [comment]
Ok, we do something similar in this demo: 

http://iangilman.com/osd/test/demo/m2/

...when you go into Page mode. The code for that is here: 

https://github.com/openseadragon/openseadragon/blob/master/test/demo/m2/js/main.js#L296

That doesn't use ViewerInputHook...if you want help with that plugin, you might file an issue on its repo: 

https://github.com/msalsbery/OpenSeadragonViewerInputHook

**Comment by zeleniy** [comment]
Looks like this is it. Thank you!
