### ISSUE TITLE
dzi url without extension

### ISSUE THREAD

**Issue by gaetano-guerriero** [openseadragon/openseadragon#832]
Greetings,
what a great library !

Back to the point,
I need to expose my generated dzi xml with a url like ``http://example.com/A123``, so without .dzi extension. My files are in ``http://example.com/A123_files``

The missing extension somewhat confuses tiles url building, and the browser try to retrieve urls like ``http://example.com/A1239/0_0.jpg`` instead of ``http://example.com/A123_files/9/0_0.jpg``.

I tried to change the regex that builds ``tilesUrl`` in dzitilesource.js line 142 this way and it seems to work

```javascript
options.tilesUrl = url.replace(/([^\/]+)(.(dzi|xml|js))|\?|\/?$/, '$1_files/');
```

**Comment by iangilman** [comment]
Good point! I think you'll actually want to change the regex to `([^\/]+)(\.(dzi|xml|js))?(\?.*|$)` though. 

Would you be up for making a pull request with this?

**Comment by gaetano-guerriero** [comment]
Sure,

I've come with these cases:

Data url | Tiles root url
------------ | -------------
/path/my.dzi|/path/my_files/ 
/path/my|/path/my_files/ 
/my/|/my_files/ 
my.xml|my_files/ 
/p/foo.dzi?a=1&b=2|/p/foo_files/


If the cases are OK, the pull request implementing this is #835

**Comment by altert** [comment]
this breaks the case:
`/iipsrv?DeepZoom=/my.dzi`

**Comment by altert** [comment]
I would suggest changing regex to `/([^\/]+?)(\.(dzi|xml|js))?(\?[^\/]*)?\/?$/`
that seem to cover mentioned cases as well as mine
