### ISSUE TITLE
The `overlays` property in `Viewer` constructor ignores the onDraw callback.

### ISSUE THREAD

**Issue by Darker** [openseadragon/openseadragon#836]
From documentation: https://openseadragon.github.io/docs/OpenSeadragon.html#Options

There's property `overlays` which should presumably contain array of overlay definitions. If those definitions include `onDraw` callback, it's ignored.

Sample code:

    window.viewer = viewer = OpenSeadragon({
      id: "map",
      tileSources: t,
      debugMode: DEBUG,
      overlays: overlays
    });

**Comment by iangilman** [comment]
How are you defining your overlays? This works for me: 

```
var overlays = [
    {
        x: 0,
        y: 0,
        onDraw: function() {
            console.log('!!!');
        }
    }
];
```

**Comment by Darker** [comment]
It works indeed. I'm not sure what caused the issue. As an excuse I can only say I wasn't working with my own code so I was a little bit confused. Thanks for help :)

**Comment by iangilman** [comment]
:+1:
