### ISSUE TITLE
Multiple image reference strip questions

### ISSUE THREAD

**Issue by Kampii** [openseadragon/openseadragon#841]
I looked at the documentation and I was not able to find the answers to the following:
1. Is it possible to hide the image under the image reference strip so that the image would not go under the strip.
2. Is it possible to change the setting of how much the image strip is left visible when hovered away from it?
3. Is it possible to have it completely hidden when user works with the image.
4. Is there any way to track the sequence of images that user picked from the strip? I would like to implement a back/forward button that would go back/forward to the image user viewed (not the one in the sequence).

**Comment by iangilman** [comment]
Unfortunately the reference strip has not gotten as much programming love as it could use. I think it should be turned into a plugin so it can evolve on its own, and there can become multiple versions for different needs. The issue for that is #649. 

In answer to your questions: 

1. It seems like you could do that with the `viewportMargins` option (see http://openseadragon.github.io/docs/OpenSeadragon.html#Options) 
1. There is no setting for that. This is where it happens: https://github.com/openseadragon/openseadragon/blob/master/src/referencestrip.js#L506
1. There is no mechanism for that, but you can use regular JavaScript or jQuery to find the reference strip element and hide it and show it as you want. It's got class `referencestrip` and it's inside the viewer.element. 
1. You can watch the `page` event from the viewer (http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#event:page) and keep track that way.

**Comment by Kampii** [comment]
Thank you Ian!
