### ISSUE TITLE
Draw overlay directly on canvas during rendering (performance issue)

### ISSUE THREAD

**Issue by Darker** [openseadragon/openseadragon#842]
I wanted to render huge amount of points on map. It's all the zombies loaded in projct zomboid game:

![image](http://i.imgur.com/oav08nD.jpg)

Those points are just DOM SVG overlays. Also, to make them centered around their location, I use custom `onDraw` callback. The result is that the whole map is completelly lagged.

For such a high amount of points (up to 1000 with single chunk loaded) I need more efficient API than DOM absolutely positioned elements.

What I need is to render the circles when map is rendering, on the same canvas. Is it possible to hook onto map rendering?

**Comment by iangilman** [comment]
Cool! 

Yes, you can draw directly onto the OpenSeadragon canvas; it's `viewer.drawer.canvas` (and its 2D context is `viewer.drawer.context`). You'll want to watch the `update-viewport` event on the viewer; it's fired after every draw. 

Btw, there are a couple of related plugins: 

https://github.com/altert/OpenseadragonFabricjsOverlay

https://github.com/openseadragon/svg-overlay

Neither of them are probably quite right for your needs, but they're worth being aware of; some of their code might be helpful.

**Comment by altert** [comment]
You can also try this https://github.com/altert/OpenSeadragonCanvasOverlay

**Comment by Darker** [comment]
Hello, I tried `update-viewport` but that's apparently being called BEFORE the canvas redraw as my changes take no effect. Executing the drawing algorithm manually produces expected result, so the algorighm isn't broken:

![image description](http://i.stack.imgur.com/UDWhM.png)

The yellow sigh is added in mspaint, but the rest is genuine. I was not able to find an event better suited for this purpose. As a test case, could you please try this function that simply tries to frame the OSD viewport with red frame:


```
RemotePOIRenderer.prototype.drawPointsOnCanvas = function() {
  var canvas = // Get OSD canvas somehow
  var ctx = canvas.getContext("2d");
  ctx.strokeStyle = 'red';
  ctx.lineWidth = 10;
  ctx.strokeRect(2,2, canvas.width-4, canvas.height-4);
}
```

Try to asign this function as `update-viewport` viewport callback. It will not work. Running it manually causes red frame around the viewport until next update.

**Comment by Darker** [comment]
I could workaround the problem by using `setTimeout(..., 0)` but it has multiple problems:

 - Flickering when paning or zooming
 - Performance issues as firefox has to redraw canvas twice
 - ugly code

**Comment by iangilman** [comment]
Strange. `update-viewport` is working fine for me:

http://codepen.io/iangilman/pen/ZQNWbo

Does that Codepen work for you? If so, how are you getting the canvas in your version? If not, what browser are you on? I've tested in Mac Firefox and Chrome.

**Comment by Darker** [comment]
Hi, I can confirm that your example works perfectly. But the same code applied to the PZMap project, even if I run their original code doesn't work. By setting a getter on `drawer.context` I was able to produce some stacktraces from where does draw *probably* happen.

I used sync AJAX request to slow down the execution to see the order in which things happen:
```
viewer.addHandler('update-viewport', function() {
    var canvas = viewer.drawer.canvas;
    var ctx = viewer.drawer.context;
    ctx.strokeStyle = 'red';
    ctx.lineWidth = 10;
    ctx.strokeRect(2,2, canvas.width-4, canvas.height-4);
 
});
var ctx = viewer.drawer.context;
Object.defineProperty(viewer.drawer, "context", {
  get: ()=>{
    console.trace();
    $.ajax({url: "http://127.0.0.1:9898",async: false,timeout: 5000});
    return ctx},
  set: ()=>{throw new Error("no set!");}
});
```
This is the best I could do for debugging so far.

**Comment by Darker** [comment]
Updating to 2.1 fixed the issue.

**Comment by iangilman** [comment]
Excellent :)
