### ISSUE TITLE
getZoom for fabricjs overlay and zoom synchronization 

### ISSUE THREAD

**Issue by Kampii** [openseadragon/openseadragon#843]
Hi folks!

I am struggling with this (http://www.c-ev.com/osdragon/dragonfabric1.html) test of mine. What I am trying to do is to sync fabricjs canvas with openseadragon. If you scroll with a mouse you will see how both get zoomed in/out.
1. When I open browser console and run viewer.viewport.getZoom(), it returns 0.0013750000000000001 when the image is fully zoomed in and I am not understanding that number. In this example (http://msalsbery.github.io/openseadragonimaginghelper/index.html) it shows 15 when fully zoomed in. The reason why I was looking at the getZoom, is because I was hoping to sync both canvas.
2. Somewhere I read that it is possible to change some z value in order to make one or another element active. Under what class I should look for.
3. Any suggestions of how to achieve this would be highly + highly appreciated, otherwise it looks like I have to big of a bite.

Kindly

**Comment by avandecreme** [comment]
> When I open browser console and run viewer.viewport.getZoom(), it returns 0.0013750000000000001 when the image is fully zoomed in and I am not understanding that number. In this example (http://msalsbery.github.io/openseadragonimaginghelper/index.html) it shows 15 when fully zoomed in. The reason why I was looking at the getZoom, is because I was hoping to sync both canvas.

The value is a viewport zoom. To convert to image zoom, see http://openseadragon.github.io/examples/viewport-coordinates/

> Somewhere I read that it is possible to change some z value in order to make one or another element active. Under what class I should look for.

Are you refering to the z-index [CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index)? It does not make an element active but defines which element should be on top.

**Comment by Kampii** [comment]
Thank you avandecreme! You posted on issue [#844](https://github.com/openseadragon/openseadragon/issues/844#issuecomment-182905561) and that looks like is what I was trying to do my self. I'll research! Thank you sooo much!

**Comment by iangilman** [comment]
@Kampii Are you using https://github.com/altert/OpenseadragonFabricjsOverlay by @altert? If not, it might be helpful...

**Comment by Kampii** [comment]
@iangilman Ill test this https://github.com/altert/OpenseadragonFabricjsOverlay as it allows to select the element. Thanks.
