### ISSUE TITLE
issue with mix-blend-mode on canvas element

### ISSUE THREAD

**Issue by baptistebriel** [openseadragon/openseadragon#847]
Hi,

I came across an issue using `mix-blend-mode: multiply` on the `canvas` element. Everything works fine except for the first seconds. Here's a quick .GIF to show the issue:

![44ab54ebd82ef3c8b9d33f0cef113fbc](https://cloud.githubusercontent.com/assets/2464663/13010243/1d430e64-d1a1-11e5-8f0c-cff16c352030.gif)

Pretty strange, I have to admit.. After some time (like a few seconds without dragging) or at the end of the first drag, the `mix-blend-mode` takes effect and the white is being removed. Then we don't have this `clearRect` 'looking-like' issue.

Any ideas? Thank you a lot!

**Comment by iangilman** [comment]
I don't know about putting `mix-blend-mode` on the canvas, but it seems to work fine when you put it on the containing div you give to OpenSeadragon. Here is a Codepen: 

http://codepen.io/iangilman/pen/GoLxdX

Works great for me from the first moment (tested on Mac Chrome and Firefox).

**Comment by baptistebriel** [comment]
Thank you for your quick answer! Figured out to make it work by applying the CSS property with JS.
I'm going to close this as I think it might be a bug that's maybe not related to OpenSeadragon...
Thank you :)
