### ISSUE TITLE
When drawing a transparent tiled image on top of another one, the bottom one get cleared.

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/openseadragon#849]
See #844 for a workaround (setting opacity to 0.99) which force using the sketch canvas.
Using the sketch canvas is necessary because of this: https://github.com/openseadragon/openseadragon/blob/master/src/tile.js#L283

@iangilman what do you think we should test to use the sketch canvas?
I guess we should use the sketch canvas when the tiled image is not the bottom one and does support transparency (png tiles).
A more accurate approach would be to test that the image is overlapping another one but that could be quite expensive to compute if there are a lot of tiled images in the world.

**Comment by iangilman** [comment]
Yeah, testing for PNG tiles and not being the bottom one seems pretty good. I figure a false positive isn't that big of a deal. The only reason to do a more accurate test would be if we can do it more efficiently than the extra time it takes to use the sketch canvas.
