### ISSUE TITLE
ReferenceStrip not displaying correctly if viewer is 0 height on creation

### ISSUE THREAD

**Issue by t-anh** [openseadragon/openseadragon#851]
Hello, I'm newbie with OpenSeadragon. I'm try to update from v1.2.1 to v2.1.0. My problem is ReferenceStrip not display correctly. 

In v1.2.1, i create div "openseadragon1" without css, and call OpenSeadragon as follow.
`	OpenSeadragon( {
		id: "openseadragon1",
		prefixUrl: "./images/",
		tileSources: ["./dzi/file1.dzi","./dzi/file2.dzi","./dzi/file3.dzi","./dzi/file4.dzi","./dzi/file5.dzi",],
		showNavigator: true,
		showReferenceStrip: true,
	} );`

ReferenceStrip is displayed correctly(width: 27897px; height: 106.2px).
In function Viewer.openTileSource(), viewer.element has clientWidth=1581px and clientHeight=531px (in my case) before creating ReferenceStrip.

But in v2.1.0, with below code
`	OpenSeadragon( {
		id: "openseadragon1",
		prefixUrl: "./images/",
		tileSources: ["./dzi/file1.dzi","./dzi/file2.dzi","./dzi/file3.dzi","./dzi/file4.dzi","./dzi/file5.dzi",],
		showNavigator: true,
		sequenceMode: true,
		showReferenceStrip: true,
	} );`

ReferenceStrip isn't displayed correctly(width: 35275px; height: 0px). 
In function Viewer.open(), viewer.element has clientWidth=2015px, clientHeight=0px.

After debug, I see
In v1.2.1: The first  time getImageInfo() function is called before creation of  ReferenceStrip.
In v2.1.0: ReferenceStrip is created before calling getImageInfo() function.

But i'm not sure this is problem.
How to display ReferenceStrip correctly with v2.1.0 as v1.2.1 without setting height to div "openseadragon1"

**Comment by iangilman** [comment]
Interesting...this may be a bug in the reference strip (that it doesn't work if the viewer has no height to start with). Why is it important for your viewer to not have a specified height? 

One possible workaround would be to use the `referenceStripWidth` and `referenceStripHeight` properties (looks like you need to use both or it won't work) when creating OpenSeadragon. 

Otherwise, fixing the bug would involve having the reference strip watch for changes in the viewer size and resize the reference strip's `element.style.width`, `element.style.height`, `panelWidth`, and `panelHeight`, if you want to look into that.

**Comment by t-anh** [comment]
> Why is it important for your viewer to not have a specified height?
Div don't have specified height because I want ReferenceStrip resize base on Browser's size. It worked in v1.2.1. 
I try to use referenceStripWidth and referenceStripHeight, it affect ReferenceStrip but in viewerSize.y = 0 and panelHeight=8. So, height of images in ReferenceStrip just only 8px .

**Comment by iangilman** [comment]
Yes, having it resize based on the browser size would be lovely. I'm sorry to hear that has broken. Seems to me like your options are: 

* Debug ReferenceStrip and fix the issue (with my suggestion above); I'm happy to answer questions and point you in the right direction. 
* Use a fixed viewer size, at least at the start while it's loading. 
* Go back to OSD 1.2.1. 
* Write your own referenceStrip plugin. 
* Hope someone comes along to fix this bug. 

> And other abnormal, the size of image in the first open is not same the size of image when home button is clicked.

This is unrelated to the reference strip, but part of moving from 1.2.1 to 2.1.0? Can you share a link to this in action?

**Comment by t-anh** [comment]
Thanks for your suggestion. Finally, I use a fixed viewer size. Now it works perfectly.

> And other abnormal, the size of image in the first open is not same the size of image when home button is clicked.

This abnormal occurred when i cheat to display reference strip.

**Comment by iangilman** [comment]
Good to hear!
