### ISSUE TITLE
Edge smoothing causes blank spots with large images

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#854]
I have an 88560px square image (viewable at http://chrisjordan.com/gallery/epu/#e-pluribus-unum, though you won't see this issue there), and when I zoomed in to twice 1:1 resolution, the edge smoothing introduced with #764 caused tiles to partially draw. I believe this is due to rounding errors.  

Here is a screenshot...the grey areas are the background showing through. 

<img width="817" alt="screen shot 2016-02-18 at 4 22 49 pm" src="https://cloud.githubusercontent.com/assets/338989/13162768/f04c1ec2-d65b-11e5-9d68-e4787a30373c.png">

If I use `smoothTileEdgesMinZoom: Infinity` I don't get this artifact. 

Here is the repro code (meant to go into /test/demo/basic.html in this repository): 

        var tileSource = {
            "Image": {
                "xmlns": "http://schemas.microsoft.com/deepzoom/2008",
                "Url": "http://chrisjordan.com/dzi/e-pluribus-unum_files/",
                "Format": "png",
                "Overlap": "1",
                "TileSize": "254",
                "Size": {
                    "Height": "88560",
                    "Width": "88560"
                }
            }
        };

        var viewer = OpenSeadragon({
            debugMode: true,
            id: "contentDiv",
            prefixUrl: "../../build/openseadragon/images/",
            tileSources: tileSource
        });

        viewer.addHandler('open', function() {
            var containerWidth = $('#contentDiv').width();
            var maxZoom = (tileSource.Image.Size.Width / (containerWidth * 0.5));
            viewer.viewport.panTo(new OpenSeadragon.Point(0.5, 0.75), true);
            viewer.viewport.zoomTo(maxZoom, null, true);
        });

@mindfreeze any thoughts?

**Comment by MindFreeze** [comment]
Tried this and it looks a lot like the issues I had when trying to fix rotation and edge smoothing to work together. @avandecreme was the one that finally cracked it so maybe he will be of more help here.

**Comment by avandecreme** [comment]
I submitted a PR. It was easier than I feared :)

**Comment by iangilman** [comment]
Yeah, nice catch!
