### ISSUE TITLE
Slow scroll on page

### ISSUE THREAD

**Issue by ilvitous** [openseadragon/openseadragon#855]
Hello i have an issue when scrolling the page.

OpenSeadragon({
        id:"opere-image",
        prefixUrl:"/pinacoteca/wp-content/themes/mybrera/js/openseadragon/images/",
        showNavigator:  true,
        navigatorPosition:   "BOTTOM_RIGHT",
        gestureSettingsMouse: {
        scrollToZoom: false
        },
        tileSources: {
        type: 'image',
        url:  '<? echo $image_full[0] ?>',
        }
   });

This is the page:
http://brerabeni.upprovider.it/pinacoteca/collezione-online/opere/madonna-con-il-bambino/
If you notice when you scroll with the mouse wheel inside the canvas the scroll is very slow.
But when you scroll outside or use the scroll bar everything run smooth.
Any hints about that?

Thank you

**Comment by iangilman** [comment]
Interesting! Looks like an unintended consequence of #754. Basically this line at the bottom of onCanvasScroll: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2850

...needs to be changed so it takes the gesture settings into account (not swallowing it if scrollToZoom is false). 

@ilvitous Would you be up for writing patch? Or perhaps @gechols (author of #754)?

**Comment by iangilman** [comment]
@ilvitous Also, may we add your site to http://openseadragon.github.io/examples/in-the-wild/ ?

**Comment by gechols** [comment]
That doesn't sound too difficult. Let me take a stab at it.

**Comment by ilvitous** [comment]
Hello Ian.
Sure you can add my website but is not finished yet and we are going to change the url. I will write you the final url in a couple of weeks.
Unfortunately I don’t have the competence to patch it.
We found another issue on safari 6.1.6 with OS X 10.7.5.
Should i open a new thread or i can write here?

Thank you for your help.





Have a Great Day!

Andrea Vitale  I  Designer

[cid:image001.png@01D10C9D.62A19350]

Pride Group, LLC  I  www.PrideGroup.us<http://www.pridegroup.us>
O. 480.663.3911  I  F. 480.383.6474

Please check out our new Promotional Products website – www.PrideGroup.us/promos<http://www.pridegroup.us/promos>
Pride Group represents over 7,000,000 products that we can put our Client’s logo on supported by a dynamic Creative Team that can create corporate brands, apparel and websites.

This email message, including any attachments, is confidential and intended solely for the use of the individual or entity to which they are addressed.
Any unauthorized review, disclosure, copying, or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

On Feb 22, 2016, at 11:37 AM, Grant Echols <notifications@github.com<mailto:notifications@github.com>> wrote:


That doesn't sound too difficult. Let me take a stab at it.

**Comment by gechols** [comment]
https://github.com/openseadragon/openseadragon/pull/858

**Comment by ilvitous** [comment]
Thank you Grant.
I change the code in opendragon.js on my website but i have the same issue.

http://brerabeni.upprovider.it/pinacoteca/collezione-online/opere/madonna-in-maesta/




Have a Great Day!

Andrea Vitale  I  Designer

[cid:image001.png@01D10C9D.62A19350]

Pride Group, LLC  I  www.PrideGroup.us<http://www.pridegroup.us>
O. 480.663.3911  I  F. 480.383.6474

Please check out our new Promotional Products website – www.PrideGroup.us/promos<http://www.pridegroup.us/promos>
Pride Group represents over 7,000,000 products that we can put our Client’s logo on supported by a dynamic Creative Team that can create corporate brands, apparel and websites.

This email message, including any attachments, is confidential and intended solely for the use of the individual or entity to which they are addressed.
Any unauthorized review, disclosure, copying, or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

On Feb 22, 2016, at 12:02 PM, Grant Echols <notifications@github.com<mailto:notifications@github.com>> wrote:


#858<https://github.com/openseadragon/openseadragon/pull/858>

**Comment by ilvitous** [comment]
Sorry i have make a mistake, now it works.
Thank you!
http://brerabeni.upprovider.it/pinacoteca/collezione-online/opere/sposalizio-della-vergine/

**Comment by iangilman** [comment]
@gechols Awesome, thanks! 

@ilvitous Please file a new issue for the other thing you found, and do please let us know when the site is on its official URL!

**Comment by ilvitous** [comment]
I will! Thank you again.

Have a Great Day!

Andrea Vitale  I  Designer

[cid:image001.png@01D10C9D.62A19350]

Pride Group, LLC  I  www.PrideGroup.us<http://www.pridegroup.us>
O. 480.663.3911  I  F. 480.383.6474

Please check out our new Promotional Products website – www.PrideGroup.us/promos<http://www.pridegroup.us/promos>
Pride Group represents over 7,000,000 products that we can put our Client’s logo on supported by a dynamic Creative Team that can create corporate brands, apparel and websites.

This email message, including any attachments, is confidential and intended solely for the use of the individual or entity to which they are addressed.
Any unauthorized review, disclosure, copying, or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

On Feb 23, 2016, at 10:07 AM, Ian Gilman <notifications@github.com<mailto:notifications@github.com>> wrote:


@gechols<https://github.com/gechols> Awesome, thanks!

@ilvitous<https://github.com/ilvitous> Please file a new issue for the other thing you found, and do please let us know when the site is on its official URL!

**Comment by iangilman** [comment]
Fixed by #858

**Comment by ilvitous** [comment]
Hello Ian.
our website is on the final url if you want to add to your page the link is:
http://pinacotecabrera.org/
Thank you for your support and the super Openseadragon!




Have a Great Day!

Andrea Vitale  I  Designer

[cid:image001.png@01D10C9D.62A19350]

Pride Group, LLC  I  www.PrideGroup.us<http://www.pridegroup.us>
O. 480.663.3911  I  F. 480.383.6474

Please check out our new Promotional Products website – www.PrideGroup.us/promos<http://www.pridegroup.us/promos>
Pride Group represents over 7,000,000 products that we can put our Client’s logo on supported by a dynamic Creative Team that can create corporate brands, apparel and websites.

This email message, including any attachments, is confidential and intended solely for the use of the individual or entity to which they are addressed.
Any unauthorized review, disclosure, copying, or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

On Feb 23, 2016, at 11:26 AM, Ian Gilman <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed by #858<https://github.com/openseadragon/openseadragon/pull/858>

**Comment by dwrogers** [comment]
Nice site! FYI, it looks like panning has an issue if you start the pan below the level of the #metacontainer on a page such as this: http://pinacotecabrera.org/en/collezione-online/opere/pala-di-arcevia/?frompage=altissima

David

--
David W. Rogers
Software Developer / Collaborative Data Services / 206.667.7089 / drogers&#64;fredhutch.org / Fred Hutch / Cures Start Here

**Comment by ilvitous** [comment]
Thank you!
For that pages we don’t use Openseadragon. An external company give us the hi-res images already embedded in krpano.
We use the openseadragon in all the others pages like that:
http://pinacotecabrera.org/collezione-online/opere/madonna-col-bambino-madonna-della-mela/



Have a Great Day!

Andrea Vitale  I  Designer

[cid:image001.png@01D10C9D.62A19350]

Pride Group, LLC  I  www.PrideGroup.us<http://www.pridegroup.us>
O. 480.663.3911  I  F. 480.383.6474

Please check out our new Promotional Products website – www.PrideGroup.us/promos<http://www.pridegroup.us/promos>
Pride Group represents over 7,000,000 products that we can put our Client’s logo on supported by a dynamic Creative Team that can create corporate brands, apparel and websites.

This email message, including any attachments, is confidential and intended solely for the use of the individual or entity to which they are addressed.
Any unauthorized review, disclosure, copying, or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

On Mar 8, 2016, at 10:33 AM, David Rogers <notifications@github.com<mailto:notifications@github.com>> wrote:

Nice site! FYI, it looks like panning has an issue if you start the pan below the level of the #metacontainer on a page such as this: http://pinacotecabrera.org/en/collezione-online/opere/pala-di-arcevia/?frompage=altissima

David

--
David W. Rogers
Software Developer / Collaborative Data Services / 206.667.7089 / drogers&#64;fredhutch.org<http://fredhutch.org> / Fred Hutch / Cures Start Here

**Comment by iangilman** [comment]
@ilvitous Awesome! I've added an issue to add it to the site: 

https://github.com/openseadragon/site-build/issues/128
