### ISSUE TITLE
Masking 2 images in same Viewport?

### ISSUE THREAD

**Issue by joris-rotteveel** [openseadragon/openseadragon#856]
Hi there,

First of all, OpenSeaDragon is really awesome. I was wondering if I am overlooking (thus creating a slightly complex solution) the following.

![mask_example](https://cloud.githubusercontent.com/assets/13443917/13205231/67b914e4-d948-11e5-85d5-eada16c86c44.png)

I'd like to have 2 images on top of each other and revealing the other image by sliding a mask to left/right. At the moment I am playing around with "[viewer.open](https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#open)" or with the thought of creating another canvas and start copying pixels. I was hoping you guys could point me in the right direction.

**Comment by joris-rotteveel** [comment]
After a little more investigating:
I have added an extra TiledImage on top with the `addTiledImage()` function instead of `open()`. Using `setClip()` will give me the masking functionality I need.
`this.tiledImage.setClip(new OpenSeaDragon.Rect(0,0,[% of image-width),imageHeight)` .

**Comment by iangilman** [comment]
Awesome :)
