### ISSUE TITLE
OpenSeadragon.Viewport does not return true coordinates when animating

### ISSUE THREAD

**Issue by Darker** [openseadragon/openseadragon#864]
Finally I have an issue that can be clearly reproduced. I wanted to draw point on ISD canvas, relative to the image/map position.

Consider a case when you want to make a point at `[0, 0]` of the image coordinates (not the canvas or viewport but the actual image. The code should - probably - look like this (**[`CODEPEN`](http://codepen.io/MXXIV/pen/rxXopx)**):

```
viewer.addHandler('update-viewport', function() {
    var ctx = viewer.drawer.context;
    // Point at 0 0 - convert real map/image offset to current local canvas coordinate
    var px = viewer.viewport.pixelFromPoint(
         new OpenSeadragon.Point(0,0)
    );
    // Draw circle
    var radius = 4;
    ctx.fillStyle = 'rgba(255,0,0,0.5)';
    ctx.strokeStyle = 'yellow';
    ctx.lineWidth = 1;
    ctx.beginPath();       
    ctx.arc(Math.round(px.x), Math.round(px.y), radius, 0, 2 * Math.PI, false);
    ctx.stroke();
    ctx.fill();
});
```

The problem is that as the map is animated, there's certain lag - the map reaches the display location mich later than the rendered point. The only way to overcome this seems to be to disable animation (I much prefer UI without animations anyway):
```
var viewer = OpenSeadragon({
    ... stuff stuff stuff ...
    animationTime: 0
});
```

I wonder what is the way of dealing with this. For me personally, means of disabling the animation at load time would be enough, but generally getting the correct coordinates is also important.

**Comment by avandecreme** [comment]
You need to call `pixelFromPoint` with immediately set to true:
```javascript
    var px = viewer.viewport.pixelFromPoint(
         new OpenSeadragon.Point(0,0),
         true
    );
```
The current doc is confusing, but we updated it for the next version: https://github.com/openseadragon/openseadragon/blob/master/src/viewport.js#L1000-L1009

**Comment by Darker** [comment]
Awesome! Thanks a lot!
