### ISSUE TITLE
What is the relation between viewer.viewport.getZoom() value and image pixel size?

### ISSUE THREAD

**Issue by Darker** [openseadragon/openseadragon#865]
Intuitively, I'd expect the zoom value to express current size of one map pixel, that is `1` when the map is zoomed to 1:1 ratio and numbers smaller than one as you zoom out.

Although zooming out really does make the zoom value smaller, the value at full zoom seems to be around 400.
My question is how to calculate pixels size (of the original big image) ratio to screen pixel (on the current canvas). That is get `1` when the map is at 1:1 and less when user zooms out.

The reason to do this is to scale custom canvas features properly.

**Comment by avandecreme** [comment]
You want to look at http://openseadragon.github.io/docs/OpenSeadragon.Viewport.html#viewportToImageZoom
Hopefully, that answers all your questions :)
