### ISSUE TITLE
Change TileSource, clear cache and redraw

### ISSUE THREAD

**Issue by htmllancer** [openseadragon/openseadragon#866]
Hi,

I'm using OSD with custom tile source, and through params after images src I send additional params om image:
for example: .....jpg?param1=value&param2=value

Can you show me the best way to clear OSD cache and redraw it with new tileSorce params?

**Comment by iangilman** [comment]
`viewer.world.resetItems()` clears all of the current tiles and sets it to reload.

**Comment by htmllancer** [comment]
Hi

Thanks. But after this action world update and receive images on old url.
I'm getting images by new url only if I changed zoom

Can you help me to solve problem this old images

`      var getTileUrl = viewer.source.getTileUrl,
          stamp = new Date().getTime();

      viewer.source.getTileUrl = function() {
        return getTileUrl.apply(this, arguments) + '?v=' + stamp;
      };

      viewer.world.resetItems();
      viewer.imageLoader.clear();
      viewer.world.update();`

**Comment by iangilman** [comment]
Hmm, in that case you're probably better off removing the tiledImage and replacing it with a new copy, like so:

```
var oldImage = viewer.world.getItemAt(0);
var oldBounds = oldImage.getBounds();
var oldSource = oldImage.source;

// Modify tile source as needed

viewer.addTiledImage({
    tileSource: oldSource,
    x: oldBounds.x,
    y: oldBounds.y,
    width: oldBounds.width, // It'll do height automatically based on aspect ratio
    success: function() {
        viewer.world.removeItem(oldImage);
    }
});
```

**Comment by htmllancer** [comment]
Ian,

Thanks a lot. You make me happy )
Best regards

**Comment by Aiosa** [comment]
I would like to share a much better way of doing this. I was struggling with a similar scenario: the user has direct control on values that control how the tiles are being drawn. Going every time to the server for the original images took a bit of time, but attached on a slider and updating `onchange` it was pretty cumbersome.

You can instead remember a timestamp when last the tile was drawn:

```
...addHandler( 'tile-loaded', function(e) {
                ... //draw first tile as seen fit from e.image data, and set appropriately e.tile.context2D so that it will be used

                // Save the original image for furture use and its url
                e.tile.origData = e.image;
                // Note when the tile was last rendered and re-draw if too old
                e.tile.lastDrawnTStamp= Date.now();
        }
```
so once a tile is loaded, you first draw the output tile based on default parameters, and then:

```
... addHandler('tile-drawing', function(e) {
            if (e.tile.lastDrawnTStamp <= this.upToDateTStamp) {

                e.tile.lastDrawnTStamp= this.upToDateTStamp + 1;
            
                // Render an image as seen fit using new parameters, use e.tile.origData as the original image
                output = drawfrom(e.tile.origData, ...)
          
                // Clear the tile canvas in case the layer uses transparency, or don't otherwise
                e.rendered.clearRect(0, 0, e.tile.sourceBounds.width, e.tile.sourceBounds.height);
                // Give OSD new image data 
                e.rendered.drawImage(output, 0, 0, e.tile.sourceBounds.width, e.tile.sourceBounds.height);
            }
        }

```

and finally, to reset the canvas do

```

//we will be resetting layerIndex - index of tile source
var imageTile = world.getItemAt(layerIndex);

// Raise tstamp to force redraw
this.upToDateTStamp = Date.now();

//force clear context, pretty dirty to touch private attributes but sorry, calling public member functions does not work, maybe there is better way to do this, you can let me know :)
imageTile._drawer.context.clearRect(0, 0, imageTile._drawer.context.canvas.width, imageTile._drawer.context.canvas.height);

//reqest draw event
world.draw();
```

**Comment by prakashroy** [comment]
Thanks @iangilman it was life saving solution. Makes my day.

**Comment by prakashroy** [comment]
> Hmm, in that case you're probably better off removing the tiledImage and replacing it with a new copy, like so:
> 
> ```
> var oldImage = viewer.world.getItemAt(0);
> var oldBounds = oldImage.getBounds();
> var oldSource = oldImage.source;
> 
> // Modify tile source as needed
> 
> viewer.addTiledImage({
>     tileSource: oldSource,
>     x: oldBounds.x,
>     y: oldBounds.y,
>     width: oldBounds.width, // It'll do height automatically based on aspect ratio
>     success: function() {
>         viewer.world.removeItem(oldImage);
>     }
> });
> ```

Thanks @iangilman it was life saving solution. Makes my day.

**Comment by iangilman** [comment]
Great! I'm glad it's working :)

**Comment by prakashroy** [comment]
@iangilman the solution working for one slide image in viewer. When we have two images in viewer it is not working. it override tiles on first image.

**Comment by Aiosa** [comment]
@prakashroy of course when you don't specify _which_ image should be overridden, how is OSD supposed to know...?
```
viewer.addTiledImage({
                    index: <index>,
                    replace: true,
                    ...
});
```

**Comment by prakashroy** [comment]
> @prakashroy of course when you don't specify _which_ image should be overridden, how is OSD supposed to know...?
> 
> ```
> viewer.addTiledImage({
>                     index: <index>,
>                     replace: true,
>                     ...
> });
> ```

@Aiosa i tired this solution and not working for me.  Actually i have two Images to zoom in and zoom out. Let say i am zoom in second image and add few attributes to imgUrl while addTileImage to second image by triggering some action by cliking check box or button and removed old image with reloading but i if switch to first image and do same action i can see second image tiles on first image. Hope explained my best. Attaching screenshot for reference

![image](https://user-images.githubusercontent.com/799764/150387954-9989b6a6-5408-4a69-a017-18ddb61462f4.png)

**Comment by prakashroy** [comment]
@Aiosa scenario is i have two slides with images. I can zoom in and zoom out slide one slide at a time. When i select a check box with some option that will add attribute to imgUrl in tile source while adding Tile Image  and remove old tile image for selected slide and the code i posted working fine for single image. 

If switch to second slide image at same zoom and select check box to add same attibute to imgUrl now refreshing tile image to first and second slide as well

![image](https://user-images.githubusercontent.com/799764/150390185-3ef111fa-aa5d-44b0-a3d0-0c0f742f55dd.png)

**Comment by iangilman** [comment]
@prakashroy looking at your code above, one issue I'm seeing is that the `oldImage` variable will keep getting overwritten by each successive iteration of the loop, so when `success` is called, it'll only do the last one. Take a look at "for loops and closures" if you're not familiar with the issue I'm talking about. Anyway, you can fix it by having the loop call a function instead:

```
function swap(t) {
  var oldImage = viewerWindow.getItemAt(t);
  var oldBounds = oldImage.getBounds();
  var oldSource = oldImage.source;

  // Modify tile source as needed

  oldSource.imgUrl = oldSource.imgUrl + '&tileCaheKey=3245435';

  viewer.addTiledImage({
    tileSource: oldSource,
    x: oldBounds.x,
    y: oldBounds.y,
    width: oldBounds.width, // It'll do height automatically based on aspect ratio
    success: function () {
      viewer.world.removeItem(oldImage);
    }
  });
}

for (var t = 0; t < viewer.world.getItemCount(); t++) {
  swap(t);
}
```

That issue won't necessarily cause the problem you are describing, though. Do you have updated code you can share?

**Comment by prakashroy** [comment]
@iangilman below is actual code. Please have a look btw i will try your suggestion.

` var viewer = osdViewerService.getActiveOSDViewer();
                var selectedTileImage = viewer.world.getSlideAtIndex(slideSelectionFactory.getSelectedSlideIndex());
                    if (selectedTileImage) {
                        var ssf = angular.element(document.body).injector().get('slideSelectionFactory')
                            var viewerWindow = ssf.getViewer()
                            for( var t=0; t<viewerWindow.world.getItemCount(); t++) {
                                var oldImage = viewerWindow.world.getItemAt(t);
                                var oldBounds = oldImage.getBounds();
                                var oldSource = oldImage.source;
        
                                // Modify tile source as needed
                                if ( oldSource.tag == "overlay" ){
                                    if( oldSource.imgUrl.includes("tileCacheKey") ){
                                        oldSource.imgUrl = oldSource.imgUrl.replace(/(tileCacheKey=)[^\&]+/, '$1' + overlaytilecachekey);
                                    } else {
                                        oldSource.imgUrl = oldSource.imgUrl+"&tileCaheKey="+overlaytilecachekey;
                                    }
                                    viewerWindow.addTiledImage({ 
                                        tileSource: oldSource,
                                        x: oldBounds.x,
                                        y: oldBounds.y,
                                        width: oldBounds.width, // It'll do height automatically based on aspect ratio
                                        success: function() {
                                            viewerWindow.world.removeItem(oldImage);
                                        }
                                    });
                                }
                            }    
                    
                    }`

**Comment by iangilman** [comment]
Cool. The actual code has the same "closures and for loops" issue, so it's definitely worth sorting that out.

**Comment by prakashroy** [comment]
@iangilman  it worked well after sorting loops but i have one more issue.
I rotated a slide image to some degree ex: 10 degree and after refresh the overlay tiles loading with 0 degree angle.

**Comment by prakashroy** [comment]
@iangilman i tired degrees while adding new tile but it is not working. Can you please help me on this? 

function swap(t) {
  var oldImage = viewerWindow.getItemAt(t);
  var oldBounds = oldImage.getBounds();
  var oldSource = oldImage.source;

  // Modify tile source as needed

  oldSource.imgUrl = oldSource.imgUrl + '&tileCaheKey=3245435';

  viewer.addTiledImage({
    tileSource: oldSource,
    x: oldBounds.x,
    y: oldBounds.y,
    degrees: oldBounds.degrees,
    width: oldBounds.width, // It'll do height automatically based on aspect ratio
    success: function () {
      viewer.world.removeItem(oldImage);
    }
  });
}

for (var t = 0; t < viewer.world.getItemCount(); t++) {
  swap(t);
}

**Comment by iangilman** [comment]
@prakashroy Interesting. Have you tried doing a `console.log` on the `oldBounds.degrees` to make sure it's the right number? Have you checked the new image in the `success` function to find out if it thinks it's rotated? 

One possible thing would be to try rotating the image after it's loaded. You might also try getting the old image's rotation via `oldImage.getRotation()` to see if it's different than what you get from the bounds. 

If it turns out there is a bug here, can you please file a new issue with that bug?

**Comment by prakashroy** [comment]
@iangilman, i tired setRotation after tiled image added successfully in success function and it is rotated but giving margin left and moved a bit to top and every refresh this margin left getting added.

`viewerWindow.addTiledImage({
                    tileSource: oldSource,
                    x: oldBounds.x,
                    y: oldBounds.y,
                    width: oldBounds.width, // It'll do height automatically based on aspect ratio
                    success: function(tileimage) {
                        viewerWindow.world.removeItem(oldImage);
                        //console.log("present rotation:"+tileimage.getRotation());
                        //console.log("set rotation:"+tileimage.setRotation(7, true));
                        console.log(tileimage.item.getBounds());
                        console.log(tileimage.item);
                       
                        tileimage.item.setRotation(7, false)
                    }
                });`
The current OSD version we are using is 2.4.0. Does latest version will help us?

**Comment by prakashroy** [comment]
@iangilman i fixed it and worked well

```
viewer.world.removeItem(oldImage);
                viewer.addTiledImage({
                    tileSource: oldSource,
                    x: oldBounds.x,
                    y: oldBounds.y,
                    width: oldBounds.width, 
                    degrees: 10,
                    replace: true,
                    preload: true
                });
```
