### ISSUE TITLE
What would be the best way to use OSD with password accessed images?

### ISSUE THREAD

**Issue by michaelw3** [openseadragon/openseadragon#867]
Hello everyone,

i was thinking of a way i could use OSD to fetch images from server that are in a folder with password access.
right now im using OSD in a way where the folder is hidden but nor password protected, a php script checks user access and the image url's are returned as an json array to the tilesource and then used by OSD, that works fine, 
however it doesn't prevent people from typing in the url of the image and this way everyone with the url could just view the image.

would it be a good idea and is it possible to maybe use a websocket and that way send the image directly to the OSD?

does anyone have a better solution?

**Comment by iangilman** [comment]
If you're on an Apache server, you could try putting the images behind a .htaccess restriction so the browser asks you for the password.

**Comment by michaelw3** [comment]
@iangilman thanks for the answer.
i will try it this way, but do you know if the browser saves the password for a session or do i have to enter for every image?

**Comment by iangilman** [comment]
Yes, it should save it for the session.
