### ISSUE TITLE
Can't scroll after a couple of rotations and zooms on iPad

### ISSUE THREAD

**Issue by AlexSmelov** [openseadragon/openseadragon#869]
The following issue was encountered during openseadragon usage: at some point scrolling stops workin on iPad (I used iPad Pro). Steps to reproduce are the following:
1. Zoom from default view
2. Rotate image to random angle
3. Move to some point of the image
4. Rotate one more time to random angle
5. Scroll to the top

Expected result:
Scoll works

Actual result:
Image is scroll a bit but then returned back, it looks like something blocks scrolling. 
The issue looks similar to https://github.com/openseadragon/openseadragon/issues/833
Video of the issue is here: http://monosnap.com/file/FUNT0zBSxoVE1NaNb06iY0nA6ilYB4
Please let me know if you need any details

**Comment by iangilman** [comment]
@AlexSmelov Have you tried with the latest code from master? #833 was fixed since the last official release.

**Comment by AlexSmelov** [comment]
@iangilman yes, I tried the latest code from master with #833 fixed

**Comment by iangilman** [comment]
Ok, thank you. @avandecreme Any thoughts?

**Comment by avandecreme** [comment]
Does it only happen on iPad?

**Comment by AlexSmelov** [comment]
@avandecreme I saw it on iPad only

**Comment by AlexSmelov** [comment]
@avandecreme it happens on desktop too in case touchscreen is used

**Comment by alexbornn** [comment]
@avandecreme, this is reproducible in Chrome on Windows 10 with touch screen.

**Comment by avandecreme** [comment]
Unfortunately I don't have any touch screen I can debug with.

**Comment by alexbornn** [comment]
@avandecreme, I can help with testing.

**Comment by avandecreme** [comment]
Is it reproducible on 2.1? Or is it a regression on master?

**Comment by alexbornn** [comment]
Not reproducible with 2.1.
I took version from downloads: https://openseadragon.github.io/#download

**Comment by avandecreme** [comment]
Ok, my guess would be that the issue is somewhere in here: https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2501-L2587
Maybe some calls to pixelFromPoint/pointFromPixel should actually call the NoRotate versions.

**Comment by avandecreme** [comment]
Sorry, I can't reproduce on my desktop by using the touch gesture settings. I also tried my crappy phone but can't reproduce there either. That is my only touch device.

**Comment by iangilman** [comment]
@AlexSmelov Are you up for poking around at the lines @avandecreme suggested might be the problem?

**Comment by AlexSmelov** [comment]
@iangilman, @avandecreme the issue is not reproducible if flickEnabled is set to false

**Comment by iangilman** [comment]
That's a good clue! @msalsbery might have some thoughts.

**Comment by avandecreme** [comment]
I think I fixed it in the above PR.
@AlexSmelov and @alexbornn could you test it?

**Comment by alexbornn** [comment]
@avandecreme, tested in Chrome on Windows 10 - works well!

**Comment by AlexSmelov** [comment]
@avandecreme checked in iPad Pro with Safari and Chrome - works fine. Thanks a lot!

**Comment by avandecreme** [comment]
Thanks for testing! :+1:
