### ISSUE TITLE
How to use custom tileSources in Viewer

### ISSUE THREAD

**Issue by MartinPyka** [openseadragon/openseadragon#875]
hi, 
I am trying to understand how I can add a custom tileSources to the Viewer. I want to create a zoomable map, in which after a certain zoomlevel the render changes from images to interactive UI elements (e.g. buttons). Does anybody know of a good example how create such a custom tileSource function?
How would you do that?

Thanks for any help,
Martin

**Comment by iangilman** [comment]
You may not want a tileSource for that...you can use overlays instead and turn them on and off based on the zoom level. To watch the zoom level, you can do something like: 

```
viewer.addHandler('zoom', function() {
  var zoom = viewer.viewport.getZoom();
});
```

**Comment by MartinPyka** [comment]
Hi Iangilman, thanks for your response. I will try to go in this direction.

Best,
Martin
