### ISSUE TITLE
BUG: When using viewer.addOverlay, the passed OverlayPlacement is ignored until a redraw is forced

### ISSUE THREAD

**Issue by kevin-at-corista** [openseadragon/openseadragon#876]
Creating a new overlay with addOverlay properly sets the value for the associated Overlay placement, but does not use it to correctly draw/place the overlay. Calling forceRedraw immediately after creation causes the overlay to display correctly.

updateOverlay, however, works correctly, perhaps because it sets  THIS[ this.hash ].forceRedraw = true; and addOverlay does not?

**Comment by iangilman** [comment]
Interesting...I would think that the overlay draw we do here: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L1819

...would be enough. At any rate, replacing that with a `forceRedraw` might be more robust. Would you be up for giving it a try and possibly making a patch?

**Comment by kevin-at-corista** [comment]
Yeah, I was confused by that as well. Just as a quick test, tried re-running the drawHTML command again immediately after the addOverlay was called, and it redrew the overlay in a different but still wrong position.

Adding a ```this.forceRedraw``` to line 1816 (before the drawHTML is called) seems to fix the problem and render the overlay correctly.

I'm not 100% sure how to interpret that. I'd be hesitant to make a patch for a solution I don't understand, and to be honest I don't understand this bit. But it does seem to work.

**Comment by iangilman** [comment]
Cool, I appreciate you digging into it. I don't fully understand why it's not working either. That said, I'd be fine with removing the drawHTML call and replacing it with forceRedraw. Anyway, let me know what you find!

**Comment by avandecreme** [comment]
To be confirmed, but it might be fixed inside #896.

**Comment by leesei** [comment]
I'm using overlay with placement in 2.2 without problem.
I suppose this can be closed.

**Comment by iangilman** [comment]
@leesei Thank you for verifying!
