### ISSUE TITLE
Ready() function like $(document).ready()

### ISSUE THREAD

**Issue by bayucandra** [openseadragon/openseadragon#878]
I need something like $(document).ready() for openseadragon. I mean an event which will emitted after the openseadragon finish doing everything in the first setup and wait for further user interaction. Like when openseadragon finish adjust to fit image to the viewer for first initial setup (if we set the option with defaultZoomLevel = 0). Is it currently possible?

**Comment by iangilman** [comment]
You can use `viewer.addHandler('open', callback)` for this purpose.

**Comment by bayucandra** [comment]
Great, it is work. Thanks for the answer.
