### ISSUE TITLE
OSD stop $(document).mousemove() event when panning

### ISSUE THREAD

**Issue by bayucandra** [openseadragon/openseadragon#879]
I need to capture "mousemove" event of whole HTML document. But i just realize that OSD stop "mousemove" event of $(document) when i do panning on the viewer. Why must OSD interrupt "mousemove" event when do panning? can i tell OSD to not stop "mousemove" event of $(document) ?

**Comment by iangilman** [comment]
I suppose we need to put the answer to this in an FAQ somewhere... @msalsbery what do you think? Basically, it's because of how we handle distinguishing mouse, touch, and pen events. I don't believe there is a way to disable this, and I think disabling it would disrupt our event mechanism. 

You can get mouse move events by adding an OpenSeadragon.MouseTracker to the viewer. I realize that's a little more complicated than just tabbing the single mouse move handler, but that's the best I know.

**Comment by bayucandra** [comment]
Seem i have to do some coordinate conversion based on the viewer coordinate for that. Am i right?

**Comment by iangilman** [comment]
If you use OpenSeadragon.MouseTracker's moveHandler, the `event.position` it gives you is already in web pixel coordinates, so you shouldn't need to do any coordinate conversion (unless you want to convert it into the viewer's viewport coordinates for some reason).

**Comment by bayucandra** [comment]
Thanks for the answer. Will try it soon.

**Comment by bayucandra** [comment]
Hi @iangilman , i have tried catching mousemove event trough OpenSeadragon.MouseTracker() as your advice. But, it still stop do mousemove event when i click & drag OSD viewport. My code look like this:

	    var tracker = new OpenSeadragon.MouseTracker({
	    	    element:'osd1',
	    	    moveHandler: mousemove,
	    	    dragHandler: mousemove //Try to add dragHandler also not work***********************
	    });
	    tracker.setTracking(true);

	    function mousemove(event){
	    	    var point = new OpenSeadragon.Point( event.position.x, event.position.y );
	    	    console.log(point); //Nothing is happen when click and drag**************************************
	    }

Do you see something wrong with my code? Thanks in advance.

**Comment by iangilman** [comment]
Hmm, I may have steered you wrong... if you want the move events that happen during a drag, you may have to use the `canvas-drag` event: 

http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#event:canvas-drag

Something like: 

```
    viewer.addHandler('canvas-drag', function(event) {
            var point = new OpenSeadragon.Point( event.position.x, event.position.y );
            console.log(point);
    });
```

Hopefully that works... sorry for the confusion!

**Comment by bayucandra** [comment]
Great, it is works. Thanks a lot.
