### ISSUE TITLE
timeout with IIF tilesource

### ISSUE THREAD

**Issue by hossam707** [openseadragon/openseadragon#880]
I am trying to load a jp2 file using IIIFserver with openseadragon but some tiles failed to load with exceeded timeout exception occured.

Another thing is about performance I feel panning and zooming is slow some how when using IIF tile source.

**Comment by iangilman** [comment]
Do you have an example you can link to? Have you filed an issue with the IIIF folks? 

The people here who know things about IIIF (as far as I know) are @azaroth42 and @jpstroop... maybe they have thoughts.

**Comment by jpstroop** [comment]
@hossam707 yes, a link would help. It might help to know which IIIF server you're using as well.

**Comment by hossam707** [comment]
I am using this server http://www.iiifserver.com/ .

**Comment by iangilman** [comment]
@hossam707 Can you provide a link to the data you're using? And do you have an example of your code running that you can link to as well?

**Comment by hossam707** [comment]
you can follow this steps:
1-) download windows version of this server from here : http://www.iiifserver.com/download/
2-) put this image in the folder created by the server : https://www.dropbox.com/s/y5ufvzmspfukxvr/188.rar?dl=0
3-) run this script : https://www.dropbox.com/s/acv9w98vorug7gc/jp2page.htm?dl=0
you can change your port number according to your configuration.
--------------------------------------------------------------
The problem as I said is a performance issue for panning and zooming and sometimes throw exception (failed to load exceeded timeout).

**Comment by iangilman** [comment]
@hossam707 So you're just running it locally? We'll see if anyone wants to install the server themselves to help you out. You may have more luck with the IIIF folks. 

At any rate, the loading timeout seems like it would be entirely due to something on the server side (unrelated to OpenSeadragon). It's interesting that it's affecting panning and zooming performance as well, though. Have you tried loading a DZI with OpenSeadragon to compare performance?

**Comment by hossam707** [comment]
yes I am using it locally. Actually it is something related to server and openseadragon because I tested the same server with another viewer (IIIF viewer) and its performance is much better another thing to be noted is that I increased the timeout period more than 30000 so the timeout exception disappeared.

Concerning DZI I know it is much better than IIF tile source but my input files is jpeg2000 format and it will be wasting time if I tried to convert jpeg2000 files to DZI format.

**Comment by iangilman** [comment]
I was just curious if you had tried DZI for comparison sake on this issue, not that you should switch over to it.

Anyway, hopefully someone will have some suggestions based on the info you've provided. If you ever do get it up somewhere people can try directly (without them having to install stuff locally), let us know... it's more likely people would look into it then.
