### ISSUE TITLE
Question: Is there a way to snap the mouse cursor to a grid or specific coordinates?

### ISSUE THREAD

**Issue by Kampii** [openseadragon/openseadragon#882]
The question says it all! :)

**Comment by avandecreme** [comment]
There is no way to change the position of the cursor in Javascript so you are probably out of luck.
There is a new [pointer locking API](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock) you might experiment with but I don't see how that would work for you.

**Comment by avandecreme** [comment]
One workaround is suggested here though: http://stackoverflow.com/a/4752667/1440403

**Comment by iangilman** [comment]
How does this relate to OpenSeadragon? What would you want the effects to be? If you want panning that snaps to a grid, you could watch for pan events and then re-pan to the grid, something like so:

```
viewer.addHandler('pan', function() {
  var pan = viewer.viewport.getCenter();
  pan.x = Math.round(pan.x * 10) / 10; // quantize to 0.1 increments
  pan.y = Math.round(pan.y * 10) / 10; // quantize to 0.1 increments
  viewer.viewport.panTo(pan);
});
```

**Comment by Kampii** [comment]
Thank you for suggestions!

@iangilman I would use it for snapping to corners of svg objects or fabricjs elements. Or, for example, I would like to draw straight lines and snap to a gird or other lines. I hope this clarifies the purpose. The fabricjs library didn't have any methods as far as I researched.

**Comment by iangilman** [comment]
Gotcha. I'm not familiar with fabric, but you might try asking them. At any rate, it'll probably come down to filtering the graphic objects along the lines of the code I wrote above, perhaps after they've been initially created.

**Comment by Kampii** [comment]
Thanks Ian!
