### ISSUE TITLE
openseadragonselection and svg-overlay combined

### ISSUE THREAD

**Issue by DanielMekotron** [openseadragon/openseadragon#883]
Hi, 

I have some issues using both svg-overlay and openseadragonselection at the same time. 

If i do not use the svg-overlay, the selection works fine, but when i enable the svg-overlay i can no longer use the selection.

Any hints on how I can get both svg-overlay and openseadragonselection to work at the same time?

Best Regards
Daniel

**Comment by iangilman** [comment]
Hmm... I don't know enough about openseadragonselection to know what might be causing it. Could you share a link to the issue in action?

**Comment by DanielMekotron** [comment]
Hi, 

Thanks for your answear. Unfortuantely I do not have a quick solutions to add a link. 
But it is only a few lines of code so i think I describe it here. 

It is when I add the line "var overlay = viewer.svgOverlay();" the selection function from the openseadragonselection stops working.

Best Regards
Daniel


<script>

    var viewer =  OpenSeadragon({
        id: "views-container",
        prefixUrl: "openseadragon/images/",
            tileSources: [{
            tileSource: "../Tiles/dzc_output_files.xml",
        }]
    });

viewer.selection();

// With the line below added, the selection function does not work
var overlay = viewer.svgOverlay();

</script>


<script src="openseadragon/openseadragon.js"></script>  
<script src="openseadragon/openseadragon-svg-overlay.js"></script> 
<script src="openseadragon/openseadragonselection.js"></script>

**Comment by iangilman** [comment]
When you say the selection function doesn't work, you mean you can turn on the selection button, but when you drag, nothing appears?

I imagine it has something to do with event handling, like the two plug-ins are fighting with each other over who's on top or something. One thing to try would be: 

```
$(viewer.canvas).find('svg').css('pointer-events', 'none');
```

... and see if that makes a difference.

**Comment by DanielMekotron** [comment]
That solved it!

Thank you so much for the assistance and a great library!

**Comment by iangilman** [comment]
Glad to hear it! I've filed an issue to possibly follow up: https://github.com/openseadragon/svg-overlay/issues/16
