### ISSUE TITLE
Can I set animationTime per clickable zoom location?

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#886]
Related to my other post, I'm looking for the best way to provide a smooth slow transition between locations in the viewer.  (I use the fitBounds method to target a rectangle location).  I've played around with animationTime and springStiffness.  Those options are set for all events on the page.

Is there a way to set per clickable event?

Question 2:
Is there a better way to provide a slow / smooth transition between points?
(as referred to in another post - 'the Ken Burns effect'?

```
<script type="text/javascript">
    var box1 = new OpenSeadragon.Rect(0.12, 0.05, 0.06, 0.02);
    var box1 = new OpenSeadragon.Rect(0.22, 0.18, 0.03, 0.01);
	
    var viewer = new OpenSeadragon.Viewer({
      id: "openseadragon-canvas",
      prefixUrl: "/openseadragon/images_TEST/",
      toolbar:       "toolbarDiv",
      tileSources: [
        "/zoom/Chattanooga1909/GeneratedImages/dzc_output.dzi",
      ],
        animationTime: "5.0",
        springStiffness: "5.0",
        showNavigator:  true,
        showHomeControl: true,
        showReferenceStrip:  false,
        autoHideControls: false
        });
        
        $('.loc1').click(function() {
        viewer.viewport.fitBounds(box1);
        });
		
        $('.loc2').click(function() {
        viewer.viewport.fitBounds(box1);
        });
  </script>
```

**Comment by iangilman** [comment]
Unfortunately, we don't have a more nuanced mechanism for changing the animationTime and springStiffness, beyond reaching into the viewport's springs directly, like so:

```
$('.loc1').click(function() {
    viewer.viewport.zoomSpring.animationTime = 4.0;
    viewer.viewport.zoomSpring.springStiffness = 4.0;
    viewer.viewport.centerSpringX.animationTime = 4.0;
    viewer.viewport.centerSpringX.springStiffness = 4.0;
    viewer.viewport.centerSpringY.animationTime = 4.0;
    viewer.viewport.centerSpringY.springStiffness = 4.0;
    viewer.viewport.fitBounds(box1);
});

$('.loc2').click(function() {
    viewer.viewport.zoomSpring.animationTime = 6.0;
    viewer.viewport.zoomSpring.springStiffness = 6.0;
    viewer.viewport.centerSpringX.animationTime = 6.0;
    viewer.viewport.centerSpringX.springStiffness = 6.0;
    viewer.viewport.centerSpringY.animationTime = 6.0;
    viewer.viewport.centerSpringY.springStiffness = 6.0;
    viewer.viewport.fitBounds(box1);
});
```

BTW, you should passing them as numbers, not strings.

As for creating your own animations, we don't have any helpers for that, but you can set up your own animation code and move things directly via `viewer.viewport.zoomTo(zoom, refPoint, true)` with each frame. The `true` at the end bypasses the springs and moves it directly to that new location. You can also use `viewer.viewport.panTo(center, true)` in the same way. This is how I do the stately zooms on Chris Jordan's site, for instance: 

http://chrisjordan.com/gallery/rtn/#silent-spring

**Comment by SamHall** [comment]
Thanks for the set of options - I'll experiment with these.
And - yes, I caught the strings after posting.  Thanks.
