### ISSUE TITLE
When a tiled image is clipped, entirely clipped out tiles should not be loaded

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/openseadragon#889]
Maybe this is done somewhere, but I don't see any logic about that in the code.
It should probably be somewhere around here: https://github.com/openseadragon/openseadragon/blob/master/src/tiledimage.js#L668

Unrelated, but it looks like those lines: https://github.com/openseadragon/openseadragon/blob/master/src/tiledimage.js#L713-L723 could be replaced by 
```javascript
viewportBounds = viewportBounds.rotate(degrees).getBoundingBox();
```

**Comment by iangilman** [comment]
Agreed, there isn't any logic for that and it would be great. 

On the rotate code, that's probably true... those lines were written long before the rest of rotation was sorted out.
