### ISSUE TITLE
Image not centered and bouncing back and forth on zoom-out

### ISSUE THREAD

**Issue by adgoncal** [openseadragon/openseadragon#890]
I found a bug where image is not centered and bounces back and forth when zooming out.

Requirements:
* `visibilityRatio:` 1
* `minZoomLevel` smaller than 1
* `animationTime` smaller than 0.1

Test case: http://plnkr.co/edit/4WjlBDKLGSv0eUJPsDcI?p=preview

**Comment by iangilman** [comment]
Good catch! Appears to be an edge case in our constraint code. 

Anyone who wants to look into this should probably start here: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewport.js#L448

**Comment by MrP** [comment]
Hello,
I'm going to give fixing this bug a shot, if that's all right.
I've also encountered this bug on my project, and want to squash it.

This is what I have after investigating for a while: It happens also on pan, always when the image is smaller than the viewport, and with a high enough visibilityRatio something funky happens in the constraint function.

**Comment by iangilman** [comment]
@MrP Awesome, please squash away! Your observations so far seem right on.
