### ISSUE TITLE
Store tiles in the local storage for offline use

### ISSUE THREAD

**Issue by Kampii** [openseadragon/openseadragon#892]
Is that doable?

**Comment by dwrogers** [comment]
I think you would need to create a “caching tile source” or come up with a caching decorator for all of the current tile sources. One challenge I see is that you might often end up caching the entire image pyramid - unless the viewing pattern was extremely limited and/or predictable. 

On the other hand, if you were on a low speed connection, never having to re-download an image tile might be an extremely attractive improvement. 

Interesting idea… It seems like it might be doable on most browsers with some caveats ([http://caniuse.com/#feat=namevalue-storage]). What is your use case?

**Comment by Kampii** [comment]
So this would go together with the annotation part for my viewer. I want users to be able to annotate the pictures while being offline. So my thinking was to somehow sync all the tiles with the user's local storage when the he/she is connected to the wifi. However, since every user will have different pictures, then I guess I can't use the manifest file and list the file names there. I did found [this File System API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Introduction), however, I have never worked with this and I was wondering whether OSD framework would allow something like this, or maybe there is something built in.

**Comment by iangilman** [comment]
OSD does not yet have support for such a thing, but it does seem possible (as long as your users don't mind how much storage space it may take). As @dwrogers mentions, you might need to write a new tileSource that knows how to access the offline files. 

As for retrieving and caching the files in the first place, do you want to cache all the tiles, or just the ones the user has already gone to? If the former, you'll probably need to write something that can loop through all the tiles in a tileSource. 

Of course both of these tasks are easier if you limit yourself to a specific format (e.g. DZI). By the way, how big are your files typically, in pixels?

**Comment by Kampii** [comment]
Thank you for the "tileSource" keyword! That helps to figure out where to dig.

I do want to cache all the files. I just checked one of the pictures and it's size is 10800 × 7200.

**Comment by iangilman** [comment]
Okay, that seems like a reasonable size for this sort of thing... big enough you wouldn't want it to be a single tile, but not so big it would be crazy to store it locally.

**Comment by Kampii** [comment]
Thanks Ian!
