### ISSUE TITLE
Clip fails on type: "image"

### ISSUE THREAD

**Issue by IllyaMoskvin** [openseadragon/openseadragon#894]
I haven't dug too deep into the code yet, but this seems like a straight-forward bug. I'm referring to the [Image Tile Source](https://openseadragon.github.io/examples/tilesource-image/) as per the docs. Clipping fails regardless of `buildPyramid`'s value.

I'm using the OpenSeadragon v2.1.0 official release.

**Comment by iangilman** [comment]
@IllyaMoskvin Can you try the latest from master to see if that makes any difference?

@avandecreme Any thoughts? I figure you're familiar with both of those elements :)

**Comment by avandecreme** [comment]
@IllyaMoskvin do you have any error/crash or it just doesn't clip?

**Comment by IllyaMoskvin** [comment]
@avandecreme Actually, no errors or crash at all. It just doesn't clip. I tried throwing in some `console.log` calls here and there. It's almost as if the `clip` option doesn't get set, but don't quote me on that.

@iangilman Will do! I don't have time to figure out how QUnit works at the moment, so I can't write a failing test, but I did create a codepen with v2.1.0 to illustrate the fail case:

http://codepen.io/imoskvin/pen/zqzJoj

It's retrieving resources from my server. Unfortunately, I don't have SSL configured for it yet, so you will have to access the pen through `http`, not `https`. I'll create a second pen once I build from master. Hope this helps!

**Comment by iangilman** [comment]
Aha! You need to specify inline tileSources as separate objects from the clip property, like so:

http://codepen.io/iangilman/pen/WwOmEV

I know knowing what to pass into `open` can be a bit confusing, considering how flexible it is.

**Comment by IllyaMoskvin** [comment]
Ah! Thank you! This makes future testing so much easier. Perhaps the [Image Tile Source](https://openseadragon.github.io/examples/tilesource-image/) example should be updated to clarify this point?

**Comment by iangilman** [comment]
Good point... I've started #898 to discuss.
