### ISSUE TITLE
download overlays with the viewer canvas

### ISSUE THREAD

**Issue by meihuisu** [openseadragon/openseadragon#895]
I am using,  osd.drawer.canvas.toDataURL("image/jpeg",1),
to get a snapshot of what is on the viewport and downloading it.  Is there a way to
include the overlays (scalebar from scalebar plugin, annotations from annotorious) in the
snapshot?

**Comment by meihuisu** [comment]
Able to do it with scalebar plugin with its getAsCanvas(). Would be good to able to store the
overlays with the underlying image.

**Comment by iangilman** [comment]
We don't have any explicit feature for this, but you could loop through the `viewer.currentOverlays` array and serialize what you need.

**Comment by meihuisu** [comment]
found html2canvas.js and it worked. (http://html2canvas.hertzen.com)

**Comment by iangilman** [comment]
Nice! Looks like a cool library.
