### ISSUE TITLE
defaultZoomLevel meaning

### ISSUE THREAD

**Issue by hossam707** [openseadragon/openseadragon#897]
I need to open the viewer with a specific zoomlevel (e.g. 17) so I use _**defaultZoomLevel**_ property but it doesn't work so I want to know how can I use this property?

**Comment by O-Zone** [comment]
Works fine for me, but 17 is pretty well zoomed in? Have you tried with other values.
Do you specify minZoomLevel and maxZoomLevel too?

**Comment by hossam707** [comment]
minZoomLevel and maxZoomLevel restrict the viewer zoom levels range but I need when opening the viewer to open with a specific zoom level.
I don't know what defaultZoomLevel represent?

**Comment by O-Zone** [comment]
That's exactly what defaultZoomLevel is for. And it works perfectly for me?

**Comment by hossam707** [comment]
In dzi image format if I want the viewer to open with dzi level 17 for example how can I do that?

**Comment by iangilman** [comment]
defaultZoomLevel uses the same zoom values as the Viewport, i.e. ratio of the displayed image's width to viewport's width. 1 means identical width, 2 means image's width is twice the viewport's width. A defaultZoomLevel of 17 would mean the image is being displayed at 17X the size of the Viewport. 

This is not the same as DZI's levels. I'm not sure exactly what the right conversion would be. At any rate, DZI level 0 is approximately 1 pixel across, level 1 is approximately 2, level 3 is ~ 4 pixels, etc. 

Of course if you don't need it to be exact, one approach is just to manually zoom to the area you're looking for and then use `viewer.viewport.getZoom()` to find out what the value is and then stick that in your code as the defaultZoomLevel.

BTW, keep in mind that the defaultZoomLevel is not just for when you first open, but also every time you hit the home button. If you just want it for when you open, you can do: 

```
viewer.addHandler('open', function() {
  viewer.viewport.zoomTo(zoom, null, true);
});
```

**Comment by hossam707** [comment]
Actually I have only two dzi levels (16 and 17) and I want to open the viewer with dzi level 17 and when click home button also so how can I get the zoom value of view port to achieve this?

**Comment by avandecreme** [comment]
Because 17 is your highest level, I think `defaultZoomLevel = yourImageWidth / yourViewerWidth` should work.

**Comment by hossam707** [comment]
Thank very much It has worked for me defaultZoomLevel = yourImageWidth / yourViewerWidth

**Comment by haehn** [comment]
Is there a way to avoid loading lower zoomlevels when defaultZoomLevel is set? We set it to 5 and OSD still tries to load tiles of lower zoomlevels as a kind of prefetching.

Thanks!

**Comment by iangilman** [comment]
OSD just loads what it needs to show what's on screen. If you're between levels, it might load the next higher level, depending on your minPixelRatio setting. 

Keep in mind that defaultZoomLevel is set in terms of the viewport's zoom value, which doesn't map directly to the zoom levels of your tile source.
