### ISSUE TITLE
Return to home on click when max zoom reached

### ISSUE THREAD

**Issue by discgolferusa** [openseadragon/openseadragon#900]
Is there anyway to make it so that if you click on the image when at the maximum zoom level it returns you back to the home zoom level?

**Comment by iangilman** [comment]
That's not a feature we directly support, but it should be easy enough to add a click handler that checks the zoom level and calls the home function if it's big enough. Let me know if you need a code example.

**Comment by discgolferusa** [comment]
A code example would be awesome.

**Comment by iangilman** [comment]
```
viewer.addHandler('canvas-click', function() {
  var zoom = viewer.viewport.getZoom();
  if (zoom > viewer.viewport.getMaxZoom() * 0.9) {
    viewer.viewport.goHome()
  }
});
```

Something like that... I haven't tested it, so it may need some tweaking.
