### ISSUE TITLE
Relative tilesource sizing

### ISSUE THREAD

**Issue by edsilv** [openseadragon/openseadragon#901]
Hi,

When displaying tile sources in "paged" (two-up) mode, the UV is positioning the pages next to each other, which raises a problem around their relative sizes. As you can see from this example:

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb13266330%2Fmanifest

Here, the right-hand-side images were scanned at a different width to the left-hand-side. This means when arranged next to each other in OSD, the rhs image is normalised to the width of the lhs image, which reduces its height.

Here's an extreme example of the problem:

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb19689755%2Fmanifest

(you can toggle paged mode using the pages icon in the top right corner of the viewer).

We'd like to be able to preserve the image dimensions (not scale to a normalised width).

Here is the code that loads the tile source array:

https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts#L295

and here's the code that positions the pages:

https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts#L334

Is there a setting I can use to override this behaviour? I'm not using collectionMode, so collectionTileSize wouldn't seem to be appropriate.

Is multi-image mode something I should look at?

https://openseadragon.github.io/examples/multi-image/

Or can this be achieved with a small change to the existing system?

**Comment by iangilman** [comment]
Looks like you're already using multi image, which is indeed what I suggest for this situation. You just need to adjust the images so they share the same height (and the width will take care of itself). It could be as simple as adding this: 

```
rightPage.setHeight(leftPageBounds.height);
```

...at the bottom of this code block: 

https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts#L334-L340

... and other blocks like it.

**Comment by edsilv** [comment]
Looks good!

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb13266330%2Fmanifest

Thanks!
