### ISSUE TITLE
jQuery-ui draggable overlays

### ISSUE THREAD

**Issue by harlet** [openseadragon/openseadragon#904]
Hi guys,

I'm struggling to make the overlay draggable.

The problem is on mouseup or canvas-release.

Can you help me with a hint on how to make this work?
Thank you!

```
var  $preview_container = $('#project_viewer'),
      preview_img = $preview_container.find('#project_thumb'),
      preview_src = $preview_container.find('#project_thumb').data('src'),
      preview_remove = $preview_container.find('#project_thumb').remove(),
      project_viewer = OpenSeadragon({
          immediateRender: true,
          prefixUrl: 'assets/openseadragon/images/',
          id: "project_viewer",
          tileSources: {
            type: 'image',
            url: preview_src,
            buildPyramid: false
          },
          toolbar:        "preview_options",
          zoomInButton:   "zoom-in",
          zoomOutButton:  "zoom-out",
          homeButton:     "home",
          fullPageButton: "reset"
      })

      var addingOverlayMode = true,
      hasTaskOpen = false,
      allreadyHasTask
      // Load the task template.
      load_task()

      $(document).on('mousedown', '#project_viewer', function(event) {
        alert('asdasd')
      }) // this doesn't work :(


      project_viewer.addViewerInputHook({hooks: [
          {tracker: 'viewer', handler: 'dragHandler',   hookHandler: onHookViewerDrag},
          // {tracker: 'viewer', handler: 'enterHandler',  hookHandler: onHookViewerEnter},
          // {tracker: 'viewer', handler: 'moveHandler',   hookHandler: onHookViewerMove},
          // {tracker: 'viewer', handler: 'exitHandler',   hookHandler: onHookViewerExit},
          // {tracker: 'viewer', handler: 'scrollHandler', hookHandler: onHookViewerScroll},
          {tracker: 'viewer', handler: 'clickHandler',  hookHandler: onHookViewerClick}
      ]})

      function onHookViewerClick(event) {
        // Check if the task mode is active.
        if (addingOverlayMode && !hasTaskOpen) {
          // Get point of event
          var pos = project_viewer.viewport.pointFromPixel(event.position)
          // Add the task with point position
          addTask(pos)

          // Stop the event from spreading.
          event.stopBubbling = true
          event.preventDefaultAction = true
        }else if (hasTaskOpen){
          // Stop the event from spreading.
          event.stopBubbling = true
          event.preventDefaultAction = true
        }
      }
      function onHookViewerDrag(event) {
          if (hasTaskOpen) {
              event.stopBubbling = true
              event.preventDefaultAction = true
          }
      }

      // INFO: Add the task...
      function addTask(pos) {
        var div = document.getElementById('task_template'),
        clone = div.cloneNode(true),
        nextID = project_viewer.currentOverlays.length+1
        clone.id = "task_"+(nextID)

        // Add the task
        project_viewer.addOverlay(clone, new OpenSeadragon.Point(pos.x, pos.y), 'CENTER')

        // Make settings with the new task
        $('#'+clone.id).removeClass('hide')
        $('#'+clone.id).find('.task_number').html(nextID)
        $('#'+clone.id+'>div').addClass('openish')

        hasTaskOpen = true
        $('#'+clone.id).draggable()

      }
$(document).on('pointerdown mousedown touchstart', '#task_1', function(event) {
          event.preventDefault()
          event.stopPropagation()
          $(this).remove()
}) // this works with right mouse click (contextmenu) - didn't tested on mobile..
```

**Comment by iangilman** [comment]
Paging @msalsbery (author of ViewerInputHook) ... any thoughts?

I know using the OpenSeadragon.MouseTracker is more effective than using jQuery events. I don't know how the ViewerInputHook relates to all this, though presumably it uses MouseTracker as well.

**Comment by harlet** [comment]
Do you suggest to create a new MouseTracker every time i create an overlay. And with MouseTracker dragHandler to move the element? And updateOverlay on dragEndHandler ? I just found this wonderfull tool. I'm still learning. :)

**Comment by msalsbery** [comment]
@harlet Yes I would use a MouseTracker attached to every overlay object. You'll get the benefit of mouse/touch/pen support without having to re-write it all, plus events won't bubble to the viewer. You can use the ViewerInputHook plugin on your overlay MouseTrackers if you need to, to control what/when events bubble up to the viewer (see https://github.com/msalsbery/OpenSeadragonViewerInputHook).

**Comment by msalsbery** [comment]
BTW, I've been so busy I haven't updated this code in quite some time, so I may be a bit slow with help/examples...I really need to catch up :)

**Comment by harlet** [comment]
Thanks alot! I'll came back with some code that may be usefull to ohers as well. Have a beautifull day!

**Comment by harlet** [comment]
I'm back with some questions.
This is my code:

`        var traker= new OpenSeadragon.MouseTracker({
            element: clone.id,
            clickTimeThreshold: 200,
            clickDistThreshold: 100,
            // stopDelay: 0,
        })
        project_viewer.addViewerInputHook({hooks: [
          {tracker: traker, handler: 'dragHandler',   hookHandler: onHookTaskDrag},
          {tracker: traker, handler: 'dragEndHandler',   hookHandler: onHookTaskDragEnd},
          {tracker: traker, handler: 'clickHandler',   hookHandler: onHookTaskClick}
        ]})
      }

      function onHookTaskDrag(event){
        // $('.conversatii').html(JSON.stringify(event))

        var webPoint = event.position
        var viewportPoint = project_viewer.viewport.pointFromPixel(webPoint) // This is not working
        var imagePoint = project_viewer.viewport.viewportToImageCoordinates(viewportPoint)
        $('.conversatii').html(viewportPoint)

        var $selection = $('#task_1'),
            pos = viewportPoint

        $selection.css({
            'top': pos.y,
            'left': pos.x
        })
      } // On Drag

      function onHookTaskDragEnd(event){
        
      } // On DragEnd


      function onHookTaskClick(event){
        $(this).remove() // This is not working
      }`

How can i get the element i'm dragging on. And how to convert the position of event in viewport position.

Thank you very much!

**Comment by iangilman** [comment]
Interesting... looks like you're doing the right thing. I guess I don't know what coordinate system the viewerInputHooks  use. In what way is it not working? Can you tell what coordinates event.position is in?

**Comment by harlet** [comment]
Is using the overlay coordinates. So, if my mouse is on top of the overlay, it gives me -10 , 0,
And i have another question about form defaut events. I mean i have a textarea in that overlay. But i can get to make it focus or if i do, i can't type. 

And i have e.preventDefaultAction = true; on keyHandler. 

Thanks alot for answering!

**Comment by iangilman** [comment]
So maybe if the viewerInputHook is already using viewport coordinates, you don't need to convert it?

I'm afraid I don't know why the keys aren't working. Have you tried it without preventDefaultAction?

If @msalsbery isn't able to help with viewerInputHook, you might try digging into its code to see what it's doing. You might also try removing it temporarily to see if any of your issues go away, to isolate where the problem is coming from.

**Comment by tamarmot** [comment]
Hi I'm working on the same functionality and what I have discovered is that when you use a mouse tracker and give it an element, the event position is RELATIVE TO THAT ELEMENT.  It is not in the canvas as a whole.  
https://openseadragon.github.io/docs/OpenSeadragon.MouseTracker.html#dragHandler

**Comment by tamarmot** [comment]
This is the code I ended up using to update my overlay from the event.  I had to add some strange offsets -- the overlay image is drawn with bottom placement, and is 25 x 25.  There is an initial jump because clearly hardcoding that offset is not a good idea.

```
var windowCoords = new OpenSeadragon.Point(event.originalEvent.x + 12.5, event.originalEvent.y - 50.0);
var viewportCoords = viewer.viewport.windowToViewportCoordinates(windowCoords);
markerOverlay.update(viewportCoords, OpenSeadragon.Placement.BOTTOM);
markerOverlay.drawHTML(markerOverlay.element.parentNode, viewer.viewport);

```
