### ISSUE TITLE
How to get overlay's child to scale with overlay

### ISSUE THREAD

**Issue by ricochet2200** [openseadragon/openseadragon#906]
I want to put a little red box in an overlay so that when it get's clicked the overlay is deleted. I have this working, but when you manually change the zoom the overlays size is scaled but the `remove` box does not.  If you zoom out, the remove box gets bigger than the overlay in which it is supposed to reside.  Here is the code below:    

```
var rect = new OpenSeadragon.Rect(x, y, width, height);
var overlay = document.createElement("div");
overlay.style.border = "1px solid green"; // Just so you can see it

var remove = document.createElement("div"); // button inside overlay to remove it
remove.style.border = "1px solid red"; // Just so you can see it
overlay.appendChild(remove);  //put remove in overlay
viewer.addOverlay(overlay, rect);
```

I would have expected all child elements to scale, but as I've thought more about it, that would be bad for `<select>`s and perhaps other elements.  However, changes that #896 made with scaling options could specify those overlays not to scale.  How can I get nested elements in overlays like:

```
<div class="overlay">
    <div class="removeButton"></div>
</div>
```

have all of its children scale?

**Comment by ricochet2200** [comment]
I should mention the actual code uses bootstrap, so maybe that is forcing the size when drawing the x.  

    <div class="overlay">
        <div class="removeButton glyphicon glyphicon-remove"></div>
    </div>

Either way, the fix would need to scale the image.  Are there any examples where this is done somewhere?

**Comment by avandecreme** [comment]
First a minor comment. Consider using `overlay.style.outline` instead of `overlay.style.border`. Using border will offset the overlay.

For your inner html element to scale, you want to use the usual CSS techniques. Setting it size in percentages should work (providing there is no conflict with bootstrap):
```javascript
remove.style.width = "100%";
remove.style.height = "100%";
```

**Comment by boskar** [comment]
Not exactly what You need, but it works: http://www.lekarski.katowice.pl/preparat.php?szkielko_guid=EA8AB491C67B479280E6C20E421619D0

the solution was a viewBox parameter in svg.

**Comment by ricochet2200** [comment]
Thanks for the response.  I got a bit side tracked on this, but I'll investigate this further soon.
