### ISSUE TITLE
Dynamically toggle navigator?

### ISSUE THREAD

**Issue by bdrichards** [openseadragon/openseadragon#907]
I know this must be very basic, but what would be the syntax in a button onclick event to dynamically toggle the navigator?

```
    function toggleNav(){
        if (viewer.showNavigator){
            viewer.showNavigator = false;}
        else {viewer.showNavigator = true;}
    }

```

**Comment by harlet** [comment]
I don't think you can do that. 
But you cand destroy and recreate a navigator on button click.

See [OpenSeadragon.Navigator](http://openseadragon.github.io/docs/OpenSeadragon.Navigator.html)

**Comment by avandecreme** [comment]
Another option is to change the visibility of the navigator:

```javascript
            var viewer = OpenSeadragon({
                // debugMode: true,
                id: "contentDiv",
                prefixUrl: "../../build/openseadragon/images/",
                tileSources: "../data/testpattern.dzi",
                showNavigator: true
            });

            var navigatorShown = true;
            function toggleNavigator() {
                navigatorShown = !navigatorShown;
                viewer.navigator.element.style.display = navigatorShown ? 'block' : 'none';
            }
```
There is a small issue with that, the red rectangle indicating the current position of the viewport will sometimes be misplaced after a toggle.

**Comment by bdrichards** [comment]
Thanks for the ideas to investigate. 
Simply hiding the navigator could work; however, my motivation to have the ability to completely turn off the navigator in order to collect some performance stats. I need to check how much of a performance hit the Navigator imposes.....

**Comment by adgoncal** [comment]
This might be helpful: 
https://github.com/openseadragon/openseadragon/issues/713
