### ISSUE TITLE
Open Seadragon for inline image

### ISSUE THREAD

**Issue by psomanhumana** [openseadragon/openseadragon#908]
is there anyway we can make openseadragon work for inline image specified as( 'data:image/png;base64,' + data)

When I'm trying tileSources: 'data:image/png;base64,' + data then I receive Access Denied Error

**Comment by avandecreme** [comment]
This should work with the simple image tile source by specifying the data-URL as URL:

```javascript
        var viewer = OpenSeadragon({
            id: "contentDiv",
            prefixUrl: "openseadragon/images/",
            tileSources: [{
                    type: "image",
                    url: "data:image/png;base64," + data
            }]
        });
```
See http://openseadragon.github.io/examples/tilesource-image/ and http://openseadragon.github.io/docs/OpenSeadragon.ImageTileSource.html for the image tile source documentation.

**Comment by psomanhumana** [comment]
Tried this. But image is not getting rendered

**Comment by avandecreme** [comment]
What version of OSD are you using? Image support has been added in 2.1.

Here is an example: http://codepen.io/avandecreme/pen/QNaGvG

**Comment by dwrogers** [comment]
Image looks fine here. But, on this example, if you click and drag the cursor off of the image, you end up stuck in panning mode, even though the cursor is no longer over the image. Is this a usage issue or an OSD bug?

**Comment by avandecreme** [comment]
This is a bug with iframes see #579
