### ISSUE TITLE
Overlays calculation not working after recent update ( imageToViewportCoordinates )? 

### ISSUE THREAD

**Issue by boskar** [openseadragon/openseadragon#909]
That's probably just because of my dirty hacks:

Currently:
![przechwycenie obrazu ekranu_2016-04-09_09-03-55](https://cloud.githubusercontent.com/assets/3456185/14402327/c19356e6-fe32-11e5-94f9-4fa91bf96832.png)
It was, and it is supposed to be:
![przechwycenie obrazu ekranu_2016-04-09_09-09-00](https://cloud.githubusercontent.com/assets/3456185/14402328/c193df9e-fe32-11e5-8275-6b8b022a57b7.png)

imageToViewportRectangle is not working?  What could have changed here? 

Thank You in advance

**Comment by avandecreme** [comment]
What version of OpenSeadragon is it? What version are you updating from?

Could you try to replace `viewer.viewport.imageToViewportRectangle` by `viewer.world.getItemAt(0).imageToViewportRectangle`?

**Comment by boskar** [comment]
Working ( http://www.lekarski.katowice.pl/working/index.php?szkielko_guid=EA8AB491C67B479280E6C20E421619D0 ) 
//! OpenSeadragon 2.1.0
//! Built on 2015-11-12
//! Git commit: v2.1.0-3-b2c17b5


Not working ( http://www.lekarski.katowice.pl/notworking/index.php?szkielko_guid=EA8AB491C67B479280E6C20E421619D0 ) 
//! openseadragon 2.1.0
//! Built on 2016-04-08
//! Git commit: v2.1.0-194-aeb5f0c-dirty

With v.iewer.world.getItemAt(0).imageToViewportRectangle: 
overlay = $.Rect {x: 0, y: 0, width: 0, height: 0, degrees: 0}, absx = "51023", absy = "35458", abswidth = "2399", absheight = "3379"

**Comment by avandecreme** [comment]
Ha thanks for making this easily reproducible.
For some reason, it was previously ok to pass strings to `imageToViewportRectangle`.
What you need to do, is parse your strings first:

```javascript
    function count_overlay(toid) {
    var absx = Number($('#' + toid).attr('absx'));
    var absy = Number($('#' + toid).attr('absy'));
    var abswidth = Number($('#' + toid).attr('abswidth'));
    var absheight = Number($('#' + toid).attr('absheight'));
    var overlay;
    if (abswidth !== 1 && absheight !== 1) {
//    overlay = viewer.viewport.imageToViewportRectangle(absx, absy, abswidth, absheight);    
    overlay = viewer.world.getItemAt(0).imageToViewportRectangle(absx, absy, abswidth, absheight); 
    }  else {
    overlay = viewer.viewport.imageToViewportCoordinates(absx, absy);
    }
    return overlay;
    }
```

**Comment by boskar** [comment]
Thanks a lot! As I supposed it's because of my not-elegant-enough code ; ) 

Actually I used current commit because of rotation of overlays - they work (almost) perfectly, it's awesome!
