### ISSUE TITLE
How to repalce the red frame with an image in the navigator?

### ISSUE THREAD

**Issue by SpecialM2580** [openseadragon/openseadragon#914]
Also....if I want to use another image as the navigate image, how?

**Comment by iangilman** [comment]
Neither of those features are supported by the current navigator, though you could probably make such a thing by modifying the source. By the way, we've been thinking it might be a good idea to pull the navigator out and turn it into a plug-in (#492) to make it easier to create custom versions of it.

**Comment by SpecialM2580** [comment]
Looking forward to it : )

**Comment by iangilman** [comment]
Well, it depends on someone grabbing the task... all of the work here is volunteer driven.
