### ISSUE TITLE
Browser compatibility (ie7)

### ISSUE THREAD

**Issue by hossam707** [openseadragon/openseadragon#920]
I am using web browser control in visual studio and navigate to openseadragon viewer but pan and zoom features are not working

**Comment by iangilman** [comment]
Could you be more specific about what's happening? Are you experiencing the same issues on http://openseadragon.github.io?

**Comment by hossam707** [comment]
when using web browser control from c# it uses IE version 7 and in openseadragon code 
   
     case "Netscape":
                if( !!window.addEventListener ){
                    if ( ua.indexOf( "Firefox" ) >= 0 ) {
                        $.Browser.vendor = $.BROWSERS.FIREFOX;
                        $.Browser.version = parseFloat(
                            ua.substring( ua.indexOf( "Firefox" ) + 8 )
                        );
                    } else if ( ua.indexOf( "Safari" ) >= 0 ) {
                        $.Browser.vendor = ua.indexOf( "Chrome" ) >= 0 ?
                            $.BROWSERS.CHROME :
                            $.BROWSERS.SAFARI;
                        $.Browser.version = parseFloat(
                            ua.substring(
                                ua.substring( 0, ua.indexOf( "Safari" ) ).lastIndexOf( "/" ) + 1,
                                ua.indexOf( "Safari" )
                            )
                        );
                    } else {
                        regex = new RegExp( "Trident/.*rv:([0-9]{1,}[.0-9]{0,})");
                        if ( regex.exec( ua ) !== null ) {
                            $.Browser.vendor = $.BROWSERS.IE;
                            $.Browser.version = parseFloat( RegExp.$1 );
                        }
                    }
                   }
it fails to enter any condition and browser version not set which is the problem

**Comment by avandecreme** [comment]
We do not support IE7 however it looks like you can set the version of IE to use: https://blogs.msdn.microsoft.com/patricka/2015/01/12/controlling-webbrowser-control-compatibility/

I would recommend to set it to `edge`.
