### ISSUE TITLE
Viewport.getBounds and Viewport.fitBounds don't take rotation into account

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/openseadragon#924]
By adding a `getBoundsNoRotate` method in addition to `getBounds`, this shouldn't be to hard.

**Comment by iangilman** [comment]
Sounds good. I assume the new `getBounds` will return a rotated rectangle? If the code isn't expecting the rotation, it can still treat it like a regular rectangle, right? It won't be correct, but it won't throw any exceptions?

**Comment by avandecreme** [comment]
Yes correct.
I guess it would be nice to have that in the next release as well because it is related to all the other work on rotation.

**Comment by iangilman** [comment]
Sounds good... I assume you'll take a whack at it?

**Comment by avandecreme** [comment]
Yes I will try to do that this week.
