### ISSUE TITLE
Optimise sketch canvas clearing/blending

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/openseadragon#926]
Currently, whenever the sketch canvas is used, it is entirely cleared and then blended in the main canvas even if just a small portion of it is drawn.
This have a big performance impact especially when the canvas is big.

This is noticeable when I have about 300 zoomed out tiled images. The sketch canvas get used because they are png images (introduced by #861, but in my case they actually are opaque and never overlap).

**Comment by iangilman** [comment]
What do you propose? Clearing and copying just the portion that's used?

**Comment by avandecreme** [comment]
Yes hopefully that would improve the performance.
Also, it might be more correct for some composite operations (I am not sure, I'm a bit lazy to check/understand all of them).
