### ISSUE TITLE
Tiled images jump when zoomed out

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/openseadragon#928]
I am not sure whether there is something we can do about it.
Here is a video showing the effect: https://drive.google.com/file/d/0BzAcRIdakTF0dFFndmFHZkh2djg/view

**Comment by avandecreme** [comment]
At first I thought I introduced that with #927 but it happens on master as well.

**Comment by iangilman** [comment]
I'm not sure what I'm looking at there... is it a little stutter or something? Hard to tell if that's from the screen capture or your mousing or OSD.

**Comment by avandecreme** [comment]
Tiled images seem to be jumping back and forth by 1 pixel.
Similar to the issue we had with edge smoothing.

**Comment by iangilman** [comment]
Interesting. Looks like rounding, like it used to look before we had Canvas. Can you narrow down when it happens? Is it only at certain zoom levels? Does it happen on the last release, or was it introduced since then?

**Comment by avandecreme** [comment]
Some discoveries:
-Happens in Chrome, not Firefox
-Happens with the latest release as well
-Happens at all zoom levels except when edge smoothing is on (on master)

Repro: http://codepen.io/avandecreme/pen/reRgQm

**Comment by avandecreme** [comment]
It turns out that it is a known issue with chrome not doing subpixel rendering when rescaling an image: https://bugs.chromium.org/p/chromium/issues/detail?id=7508

Here is a codepen reproducing our particular issue: http://codepen.io/avandecreme/pen/WwBXPo
Note how the image jumps from one pixel to another (not even keeping a constant width) in Chrome but not in Firefox.

**Comment by iangilman** [comment]
Interesting! That's unfortunate of Chrome, especially considering that bug dates back to 2009! I mostly use Firefox, so I guess that's why I haven't noticed. 

Anyway, I guess there's nothing we can do. Shall we close this issue? Thank you for digging into it!

**Comment by avandecreme** [comment]
Yeah I didn't find any good workaround.
This is a minor issue anyway. It just get noticeable when zoomed out a lot (because the images size change).
