### ISSUE TITLE
Resize viewer

### ISSUE THREAD

**Issue by hossam707** [openseadragon/openseadragon#929]
I want to resize OSD viewer according to browser size so how can I do this?

**Comment by iangilman** [comment]
By default the viewer automatically resizes itself to the div that contains it. You can resize that containing div however you normally would. For instance, if it's the only thing in your window, you can give it this CSS: `width: 100%; height: 100%;`

**Comment by hossam707** [comment]
Actually I need to resize my OSD viewer according to browser size while preserving same DZI level which means that if I open my viewer with DZI level 14 for example so I would like to keep the same zoom level.

**Comment by adgoncal** [comment]
I think you want to use `preserveImageSizeOnResize`.
See the options at: http://openseadragon.github.io/docs/OpenSeadragon.html#Options
