### ISSUE TITLE
Safari 9.1 and history update/replaceState

### ISSUE THREAD

**Issue by meihuisu** [openseadragon/openseadragon#931]
This is not really an issue of openseadragon but want to log it for others and maybe other group has
different method.  We saved the current viewer position on 'viewport-change'  event and used
history.replaceState() to track it  and it is being consumed and saved as context part of an overlay
annotation.  We run into a freezing problem on Safari9.1 after  some zooming and panning around.  This worked on Chrome and Firefox and older version of Safari. After digging around, found this reported feature, https://forums.developer.apple.com/thread/36650. Essentially,  we can only update the 
history 100 times and then no more.

**Comment by iangilman** [comment]
I suppose you could use the hash fragment instead; perhaps it doesn't have the same limitation.
