### ISSUE TITLE
fitBounds() based fabric js overlay coordinates & size

### ISSUE THREAD

**Issue by bayucandra** [openseadragon/openseadragon#932]
I need to zoom in the OSD viewport to fit a fabricjs overlay coordinates & sizes. I have tried using fitBounds() by using OpenSeadragon.Rect() as the parameter with x = fabricobject.left, y= fabricobject.top, width= fabricobject.width, height= fabricobject.height. But it is give me unexpected result, even the OSD image go to the top of viewport and disappear.

When i test a call to getBounds() to get the value of bounds, seem the definition of bounds coordinate is too far compared with fabricobject coordinate and size.

I have tried to get value of getBounds() after zooming the viewport approximately match to drawn fabric rect object. The fabric object made with coordinate : left = 957, top = 2582, width = 8890, height = 2002. But the value of getBounds() give me: x = 0.0898168043184071, y = 0.1856698413064116, width = 0.8208990743349929, height = 0.25840893262375325. Seem something strange and unexpected to me.

Please help me to solve my problem. Thanks in advance.

**Comment by iangilman** [comment]
Looks like your fabric and your OpenSeadragon viewport aren't using the same coordinate system. You might want to brush up on how OpenSeadragon handles coordinates: 

http://openseadragon.github.io/examples/viewport-coordinates/

When you create your viewer and load your image, you can specify a size for it... by default it's one unit wide, but you could make it 8,890 units wide instead to match your fabric object. 

The other option is to leave things the way they are but convert between the fabric and OpenSeadragon coordinates.

**Comment by bayucandra** [comment]
@iangilman thanks a lot for more of OSD learning for me. Seem i have succeed with coordinate conversion as follow:

	var x= parseInt(o.get('left')); var y= parseInt(o.get('top')); //Fabric object left and top coordinate
	var width=parseInt(o.get('width')); var height= parseInt(o.get('height')); // Fabric object width & height

	var bound_coordinate_start = self.viewer.viewport.imageToViewportCoordinates( x, y ); // convert starting point of fabric object
	var bound_coordinate_end =  self.viewer.viewport.imageToViewportCoordinates( x + width, y + height );// convert end point of fabric object

	var bound_rect = new OpenSeadragon.Rect( bound_coordinate_start.x, bound_coordinate_start.y,  bound_coordinate_end.x, bound_coordinate_end.y);//Rect based on converted coordinate


I am using the bound_rect as viewport.fitBounds() parameter. 

However i am curious what if i want to set my viewport width and height to match the image width & height like your first option mentioned? I still not have idea how to make it based on the documentation. There is no function of viewport related to 'setWidth()' or something like that.

Folowing is the script for image opening:


	SOSD.viewer.open({
		tileSource:{
			width: data.width, height: data.height,//comes from ajax data
			tileOverlap: 2,
			tileSize: 250,
			getTileUrl: function( level, x, y ){
				return "/drawing/tiles/"+page_number+'/'+level+"_"+x+"_"+y;
			}
		}
	});

**Comment by iangilman** [comment]
@bayucandra Apologies for the delayed response!

To set the image's width in the viewport, do like so:

```
SOSD.viewer.open({
    width: data.width, // the height will be set automatically based on the image aspect ratio
    tileSource:{
        width: data.width, height: data.height,//comes from ajax data
        tileOverlap: 2,
        tileSize: 250,
        getTileUrl: function( level, x, y ){
            return "/drawing/tiles/"+page_number+'/'+level+"_"+x+"_"+y;
        }
    }
});
```

That outer width specifies the image's size in the viewport, whereas the inner one that you already had specifies how many pixels are in the image.

**Comment by bayucandra** [comment]
@iangilman  Wow, that is cool. New learning for me, just add 'width' property. Much easier than coordinate conversion. Thanks a lot for your help.
