### ISSUE TITLE
Restrict zoom levels

### ISSUE THREAD

**Issue by hossam707** [openseadragon/openseadragon#937]
I have two only dzi levels (17 and 16) and I want openseadragon to view these two levels only so I use

  tileSources:   {
                 --------------
                 minLevel: 16,
                maxLevel : 17,
               --------------------
}
but I need to restrict zoom levels to (17 and 16) only and initially I want to open viewer with level 17.
How can I do this?

**Comment by iangilman** [comment]
This should do it: 

```
viewer.addHandler('open', function() {
    var maxZoom = viewer.viewport.getMaxZoom();

    // zoom to level 17 
    viewer.viewport.zoomTo(maxZoom, null, true);

    // make the minimum zoom level 16
    viewer.viewport.minZoomLevel = maxZoom / 2;
});
``` 

You'll want to update the minZoomLevel every time the viewer resizes as well.
