### ISSUE TITLE
Fabric js overlay multi select object

### ISSUE THREAD

**Issue by bayucandra** [openseadragon/openseadragon#941]
According to fabric JS sample at their home page ( http://fabricjs.com ), it should be able to do multiple select on the objects by pres and hold shift key + left click.

However when i have fabric js overlay on top of OSD, i can't have multi select object with same way. Is there any settings with OSD that make me able to do that?

**Comment by iangilman** [comment]
I don't know of anything in OSD that would limit this... you should ask @altert in the project for the Fabric plugin:

https://github.com/altert/OpenseadragonFabricjsOverlay/issues

**Comment by bayucandra** [comment]
@iangilman , thanks for your advice. Will re post my question there.
