### ISSUE TITLE
Any examples of using OpenSeadragon together with React and Redux?

### ISSUE THREAD

**Issue by eriksjolund** [openseadragon/openseadragon#942]
Do you know of any open source licensed web projects that makes use of
OpenSeadragon together with [React](http://facebook.github.io/react/) and [Redux](https://github.com/reactjs/redux)?

I'm contemplating if it would be a workable approach to use OpenSeadragon together with React and Redux. The immutable state could be stored in [Immutable](https://github.com/facebook/immutable-js/) and it could for instance contain the x and y coordinates of the tiled images I would like to have in the OpenSeadragon window.

[A Stackoverflow answer](http://stackoverflow.com/a/21943949/757777) about d3.js mentions that it is possible to build a _black-box component that you never let React update_. 

I'm curious if anyone tried using OpenSeadragon together with React and Redux?
Or do you before-hand think it is a bad combination of web technologies?

**Comment by iangilman** [comment]
I'm not aware of someone doing this, but it seems like a reasonable thing to try. I agree you would want to protect it from React updates, since you wouldn't want the OSD viewer to be constantly re-initializing itself. 

In a way the navigation for OSD is already a little React-like in that you just tell it where you want it to be and it handles the work of getting there from wherever it happens to be at the moment. You just need a little bridge between React and OSD to translate between the two ways of doing things.

You might also ask in the Gitter room: 

https://gitter.im/openseadragon/openseadragon

... and I'd love to hear how it goes if you pursue it!

**Comment by ashraffayad** [comment]
I'd like to use OpenSeadragon in my next react project. So, I prepared a basic component here. http://jsfiddle.net/ashraffayad/074navyp/ 
All you have to do is provide the image source as props and it will initialize itself after the image loads. 
You could easily protect it from react updates using 
```
 shouldComponentUpdate(nextProps, nextState){
        return false
    }
```

I hope it will help you

**Comment by iangilman** [comment]
Very cool, thank you!

**Comment by eriksjolund** [comment]
Thanks! Would it be possible for you to release your code under an open source license? 
(for instance the MIT license)

Another thing I stumbled upon:
This MIT-licensed software project combines Leaflet and React:
https://github.com/PaulLeCam/react-leaflet

**Comment by ashraffayad** [comment]
@eriksjolund  unfortunately, this project is not open source. 
But please feel free to use the example I posted in any way you like.

**Comment by LiguidCool** [comment]
Hi,
I just use 
`import OpenSeaDragon from 'openseadragon';

  componentDidMount() {
    Axios.get(this.props.params.id + '/index.json').then(res => {
      viewer = OpenSeaDragon({
        id: "openseadragon1",
        prefixUrl: "/img/openseadragon/",
        tileSources: {
          type: 'image',
          url: res.data.src
        },
        debugMode: true,
      });
    }).catch(err => console.log(err));
  }`
... and that work is well. But how use plugins (like [that](https://github.com/picturae/openseadragonselection)).

**Comment by iangilman** [comment]
I guess you might have to package the plugin so it works in webpack?

**Comment by besarthoxhaj** [comment]
Hey @ashraffayad thanks for the example!:)

**Comment by ashraffayad** [comment]
@besarthoxhaj You're welcome. Happy to help.
@iangilman actually all you have to do is require Openseadragon or import it. Webpack will package it automatically.
