### ISSUE TITLE
Html Overlay on iphone don't fire event.

### ISSUE THREAD

**Issue by ilvitous** [openseadragon/openseadragon#943]
Hello,
I have use openseadragon to create this map:
http://parkingjuju.com/event/cardinals-vs-patriots/

The map have some html overlay with this link inside:
<a onclick="scrollToTicket('25')">

Everything works well on desktop but on iphone when i click on the overlay the event don't get fire.
Can someone help me with that?

Thank you.

**Comment by iangilman** [comment]
How are you capturing the click event? Have you tried using OpenSeadragon.MouseTracker?

**Comment by ilvitous** [comment]
No i haven’t try but i will.

This is my  overlay content
<div id="'.$parkingid.'">

<div class="juju-tickets-container">
<div class="juju-ticket-overlay">
<a onclick="scrollToTicket(\''.$parkingid.'\')">'.
'<span class="juju-map-ticket-price">'.$price.'</span>'.
'<span class="juju-map-ticket-name">'.$ticket->name.'</span>'.
'<span class="juju-map-ticket-qty">Available: '.$product->get_stock_quantity().'</span></a>'.
'</div>
</div>

</div>



I am capturing the event using onclick


Have a Great Day!

Andrea Vitale  I  Designer

[cid:image001.png@01D10C9D.62A19350]

Pride Group, LLC  I  www.PrideGroup.us<http://www.pridegroup.us>
O. 480.663.3911  I  F. 480.383.6474

Please check out our new Promotional Products website – www.PrideGroup.us/promos<http://www.pridegroup.us/promos>
Pride Group represents over 7,000,000 products that we can put our Client’s logo on supported by a dynamic Creative Team that can create corporate brands, apparel and websites.

This email message, including any attachments, is confidential and intended solely for the use of the individual or entity to which they are addressed.
Any unauthorized review, disclosure, copying, or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

On May 18, 2016, at 9:35 AM, Ian Gilman <notifications@github.com<mailto:notifications@github.com>> wrote:


How are you capturing the click event? Have you tried using OpenSeadragon.MouseTracker?

**Comment by ilvitous** [comment]
Hello Ian.
I try to use this handler:

zoomViewer.addHandler('canvas-click', function(event) {


});

Now I can fire the click also on iPhone but how can i get the id of the overlay clicked on the map?




Have a Great Day!

Andrea Vitale  I  Designer

[cid:image001.png@01D10C9D.62A19350]

Pride Group, LLC  I  www.PrideGroup.us<http://www.pridegroup.us>
O. 480.663.3911  I  F. 480.383.6474

Please check out our new Promotional Products website – www.PrideGroup.us/promos<http://www.pridegroup.us/promos>
Pride Group represents over 7,000,000 products that we can put our Client’s logo on supported by a dynamic Creative Team that can create corporate brands, apparel and websites.

This email message, including any attachments, is confidential and intended solely for the use of the individual or entity to which they are addressed.
Any unauthorized review, disclosure, copying, or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

On May 18, 2016, at 9:35 AM, Ian Gilman <notifications@github.com<mailto:notifications@github.com>> wrote:

OpenSeadragon.MouseTracker

**Comment by iangilman** [comment]
You should be able to get the original target like so:

```
zoomViewer.addHandler('canvas-click', function(event) {
	var target = event.originalEvent.target;
});
```
