### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by gonsagh** [openseadragon/openseadragon#945]
hi i'm from argentina.
i'm using xampp as a test server and  I can´t intall openseadragon to make it running well.
i was reading the install guide, but i cant make it work.
thanks in advance

**Comment by iangilman** [comment]
Sure, what problem are you having? Can you share  your folder structure and code?

**Comment by gonsagh** [comment]
Yes, I'm trying to understand wich thing I have to intall previously.
I'm having a Xampp lamp server under windows7 pro.

thanks Ian!

**Comment by iangilman** [comment]
Well, I can't help you set up XAMPP. Are you able to see a regular web page with it? If so, that's all you need to get started with OpenSeadragon beyond what's described on the front page of http://openseadragon.github.io/docs/.

If you can see a regular web page in your XAMPP and you've followed the instructions on http://openseadragon.github.io/docs/ and you're encountering problems, please describe the specific problem you're having.

**Comment by gonsagh** [comment]
hi.
I've found the solution here:

http://scalar.usc.edu/works/guide/creating-and-importing-tiled-images

deep zoom composer dosn´t create a .DZI image, so I've to change the file
extension as said in the above link.


   1. In the newly created folder, change the extension of the
   dzc_output.xml file to dzc_output.dzi.

I've made this and it began to work.

thanks

**Comment by iangilman** [comment]
Glad to hear you got it sorted out! OpenSeadragon actually supports DZI files that have a .xml extension... I wonder why it wasn't working for you. At any rate, at least it's working now!

**Comment by gonsagh** [comment]
I was not working because it seems that did not read the file with .xml
extension. just changing the extensiona .dzi, began to work

**Comment by iangilman** [comment]
Fair enough. Glad it worked!
