### ISSUE TITLE
Drawing grid in viewer (overlay/canvas)

### ISSUE THREAD

**Issue by SasNaw** [openseadragon/openseadragon#949]
I'm trying to put a grid on top of a medical image. There is also a toggle switch to turn the grid on/off (or visibile/invisible). Each cell in that grid needs to be clickable.
 I tried to realize that with overlays, but the amount of cells in the grid is way too big (>30.000) to make this a viable solution. Then I learned that it is a better approach to draw such a grid directly on the canvas of the viewer. For this purpose I tried two plugins, but each comes with its own issues:
- [OpenseadragonFabricjsOverlay
  ](https://github.com/altert/OpenseadragonFabricjsOverlay)

Adding works fine, but I can't clear the canvas afterwards. The .clear()-method from the fabricjsOverlay object throws the following exception: 
`Uncaught TypeError: this._fabricCanvas.clearAll is not a function`
- [OpenSeadragonCanvasOverlay](https://github.com/altert/OpenSeadragonCanvasOverlay)

Adding once works fine, removing too. But I was not able to add more than one overlay at any given time nor add one after removing the first. There is no message or exception.

Am I overlooking something? Or is there a better approach to what I'm trying to do I haven't thought of yet?

Edit: I'm doing this for my thesis and there was a misunderstanding with my supervisor. A grid is not wanted anymore, so this can be closed/ignored.

**Comment by iangilman** [comment]
I see this as a moot question now, but I'll go ahead and throw my 2 cents in for posterity. 

You shouldn't have to add more than one canvas overlay... just draw the entire grid on the one. As for clicking, listen on the OSD viewer for `canvas-click` events and do the math to figure out which grid square you're in.

**Comment by Pin0** [comment]
Basically this code draws a set of rectangles on the viewer, you might find this of use for your use-case.
```
viewer.viewer.addHandler('open',function(){

            if(raster.length>0) {

                //prefix is image path of viewer
                var prefix = viewer.viewer.prefixUrl;

                //create button to add to viewer
                var button = new OpenSeadragon.Button({
                    element:    button ? OpenSeadragon.getElement( button ) : null,
                    clickTimeThreshold: viewer.viewer.clickTimeThreshold,
                    clickDistThreshold: viewer.viewer.clickDistThreshold,
                    tooltip:    OpenSeadragon.getString('Tooltips.ShowOverlays') || 'Show overlays',
                    srcRest:    prefix + 'hotspots_rest.png',
                    srcGroup:   prefix + 'hotspots_grouphover.png',
                    srcHover:   prefix + 'hotspots_hover.png',
                    srcDown:    prefix + 'hotspots_pressed.png',
                    onRelease:  function (){
                        //hide or show class as defined when adding raster elements
                        jQuery('.sd-overlay').toggle();
                    }
                });

                //add button to viewer
                viewer.viewer.buttons.buttons.push(button);
                viewer.viewer.buttons.element.appendChild(button.element);

                for (var i = 0; i < raster.length; i++) {
                    var line = raster[i];
                    //console.log(line);

                    var elt = document.createElement("div");
                    elt.innerHTML = line.label;
                    elt.style.cssText = "outline: 1px solid #3F7D96; text-align: center; color: white; font-weight: bold; background-color: rgba(0, 0, 0, 0.2);";
                    elt.id = "runtime-overlay" + i;
                    elt.className = "sd-overlay";

                    var x = Number(line.left);
                    var y = Number(line.top);
                    var w = Number(line.width);
                    var h = Number(line.height);

                    var rect = viewer.viewer.viewport.imageToViewportRectangle(x, y, w, h);

                    viewer.viewer.addOverlay({
                        element: elt,
                        location: rect
                    });

                }
            }
        }, raster);

        this.raster = raster;
    }
```

Where raster is an array of objects like so:
```
[{"id":"1","raster_id":"1","label":"Rij 1","top":"620","left":"420","width":"5350","height":"200"},{"id":"19","raster_id":"1","label":"Rij 19","top":"4105","left":"420","width":"5350","height":"200"},{"id":"20","raster_id":"1","label":"Rij 20","top":"4105","left":"420","width":"5350","height":"200"}]);
```

Codestyle could be better but is was implemented in a legacy project

**Comment by iangilman** [comment]
@Pin0 Awesome, thank you for sharing this!
