### ISSUE TITLE
[Q] How to find the image clip rect in the original image coordinates?

### ISSUE THREAD

**Issue by peterlitvak** [openseadragon/openseadragon#951]
Let say I have an image 1000x500.
When image is displayed fully inside the viewport I want to get clip rect === {0, 0, 1000, 500}
When the image is say centered zoomed to be twice the size I want to get clip rect === {250, 125, 250, 125} meaning the center crop of the original image.
When image panned so that, say, only a half of it is visible (say moved to the top left corner), I want to get clip rect === {500, 250, 500, 250}

It should be possible with available methods, I just cannot figure exactly which ones.

**Comment by iangilman** [comment]
TiledImages have a clipping feature, but it sounds like you're just asking to know what part of the image is currently visible in the viewport. If so, and if you're dealing with just a single image, this should work:

```
viewer.viewport.viewportToImageRectangle(viewer.viewport.getBounds());
```

If you have multiple images, you'd get the specific image, for instance like so:

```
var tiledImage = viewer.world.getItemAt(0);
```

... and then call the same thing on it:

```
tiledImage.viewportToImageRectangle(viewer.viewport.getBounds());
```

**Comment by peterlitvak** [comment]
This was my inclination but it doesn't work as expected unfortunately.
In my case I have an image with aspect 1.5 and the viewport is embedded in a DVI that has aspect 1.8.
This naturally produces a letter box and the viewport bounds (for 2584x1734 image) are: 
-0.1, 0, 1.19, 0.67
Which in turn produces "incorrect" conversion, say in the case of "home'ed" image the im rect comes as (rounded):
-249, 0, 3082, 1734

Apparently I'm missing something here.

**Comment by avandecreme** [comment]
Looks good to me except when there is no intersection. Do you really want to return the whole image in that case?

Also, in case you want to support multi-images in the future, you might prefer to retrieve the image bounds like this:
```javascript
let imageInViewport = dziViewer.world.getItemAt(0).getBounds(true); //or .getClippedBounds(true)
```

**Comment by peterlitvak** [comment]
Thank you, yes in my case I do want to return the whole image.
