### ISSUE TITLE
getBounds() give different value compared to fitBounds() parameter

### ISSUE THREAD

**Issue by bayucandra** [openseadragon/openseadragon#953]
Hi,
I am trying to save bounds of visible area of OSD viewport for load later to restore. But i found problem with getBound(), the detail step i have tried as follow:

1. I do fitBounds( param ), the param have been made by converting area of an object coordinate and size at fabric overlay using imageToViewportCoordinates(). At this point, the fitBounds working fine as expected.
2. save new bounds area by get getBounds() instead get the converted one at fitBounds parameter. I must do that for consistency, since there is another scope which need saving bound area but not using fabric object overlay as the bounds area. At this point i have problem that the getBounds() value is very different compared to the fitBounds() parameter that i have made by converting fabricjs object coordinate. Must i also converting getBounds() value with some conversion technique?

Here is the coordinate sample in my case:

**The one that i got by converting fabric js object coordinate & size ( i make this as fitBounds() parameter )  :**
{"x":0.36,"y":0.24370370370370373,"width":0.22101851851851853,"height":0.16712962962962963}

**The one that i got by calling getBounds() after fitBounds() finish. I even put timeout at 5000 on it:**
{"x":-0.015233451536643183,"y":0.24370370370370376,"width":0.9714854215918046,"height":0.16712962962962963}

Any help will be appreciated. Thanks in advance.

**Comment by avandecreme** [comment]
This happen because the aspect ratio of the rect you are passing to fitBounds is different than the aspect ratio of your viewport.

When calling fitBounds, OpenSeadragon makes sure that the bounds are displayed but the displayed area might be bigger than what provided.
GetBounds returns the exact bounds displayed.

**Comment by bayucandra** [comment]
Hi @avandecreme : Thanks for the answer, that make a sense. Seem you are right, could be i have done something wrong about make another fitBounds() based on those generated last getBounds().
