### ISSUE TITLE
smoothTileEdgesMinZoom performance degradation on LegacyTileSource

### ISSUE THREAD

**Issue by adgoncal** [openseadragon/openseadragon#956]
After updating to version 2.2.0 I noticed a major performance degradation on a page that uses LegacyTileSource with `buildPyramid: false`. Just to be clear, the performance hit was not apparent on the OpenSeadragon viewer itself, but on other (angularjs) components on the same page. Setting `smoothTileEdgesMinZoom: Infinity` solved the problem, so I thought I should post an issue here as reference for anyone with similar problems in the future. 

Maybe this should be added to the documentation. Does LegacyTileSource even benefit from smoothing tile edges?

**Comment by avandecreme** [comment]
> Does LegacyTileSource even benefit from smoothing tile edges?

Definitely not. The legacy tile source has just one tile per level.
We should probably disable it if the tile source has only one tile.

**Comment by iangilman** [comment]
Good catch! Same goes for ImageTileSource as well, right? Is there a good general way to know if the tile source consists of one tile per level?
