### ISSUE TITLE
[Q] Is there a standard OSD way to change cursor when panning?

### ISSUE THREAD

**Issue by peterlitvak** [openseadragon/openseadragon#958]
I'd like to change cursor to an open hand (standard pan cursor) when panning is available.
I think canvas-press and canvas-release are the events to handle.
I can add my own logic for the cursor but was wondering if this is something that was already done in OSD.

**Comment by iangilman** [comment]
OSD doesn't have a facility for this, but it should be easy enough for you to add like you suggest.

**Comment by peterlitvak** [comment]
ok, thanks!
