### ISSUE TITLE
[Q] Any handlers for HTTP-errors during tile loading

### ISSUE THREAD

**Issue by Gruntar** [openseadragon/openseadragon#959]
Hello! We've been using your wonderful app for some time, it's amazing, really.

Here's the deal: the server-side part of our service could return response with 401 status code during a tile uploading. But, as I could see, there is no error handler for such case (maybe it's because tile-request is not an XHR-request), although there is a handler for a tile-upload error in general ('tile-load-failed', I suppose). 

So, could you please show me, how I can handle 401 tile responses?

Thanks in advance!

**Comment by iangilman** [comment]
As far as I know there's no way in the browser to find out why an image load failed; you just know that it failed. I just ran this test: 

```
        var image = new Image();
       
        image.onerror = function(){
          console.log('!!!', arguments);
        };

        image.src = 'http://foo.com/bar2.jpg';
```

... and the error event is quite generic. 

So, you just need to listen for `tile-load-failed` and do whatever you need to from there. 

I guess if you really need to know the difference between a 401 and something else, when you get the tile failure you could then do an AJAX call to the same URL and see what the error you get from that is.

**Comment by Gruntar** [comment]
Yes, It seems, that the only way is to send some quick request indeed. Thanks, Ian!
