### ISSUE TITLE
Event when loading tiles is finished

### ISSUE THREAD

**Issue by KTGLeiden** [openseadragon/openseadragon#960]
Hi there, I want to make a plugin for the viewer to be able to take a screenshot at any given resolution (including maximum resolution), but I'm kinda stuck trying to find out where I can find if all tiles are loaded. I am nearly finished with the plugin actually, but right now I am exporting immediately after enlarging the this.viewer.element.style.width/height properties, and requesting an animation frame in javascript. This means that the size is correct but the tiles are not loaded, which basically returns an image with the resolution of your viewport, enlarged to the specified resolution. You'd help me a great deal, and I'll submit the plugin right after I finished it, if you are interested.
- PS: this application is awesome. Seriously, I'm now able to view my 100K by 80K images as I would want it :) Thanks a lot!

~
Koen

**Comment by iangilman** [comment]
I actually started this in this pull request: 

https://github.com/openseadragon/openseadragon/pull/837

... but have been distracted with other things. If you're interested, you could take it over. Otherwise thanks for the reminder!

**Comment by KTGLeiden** [comment]
That's awesome and exactly what I need. Shame the PR is not merged yet ;) I adapted the code from the 2.2.0 release and did notice that whenever you are zooming in with animation, say, the event is fired 60 times per zoom-in action. However if I zoom in at once, which I obviously will, it works perfectly. Thanks a lot. First, I'll try and finish up my plugin and maybe later add to this PR. However for me this is already enough so you might want to specify exactly to which elements you would like the event to be fired. 
Thanks again!
~
Koen

**Comment by iangilman** [comment]
Glad it helps!

**Comment by KTGLeiden** [comment]
Hi there, (again)
I am working in a scientific environment, which is why I have multiple plugins (scalebar, and a self-made annotation plugin (see image below, you can place the arrows yourself and rotate and drag them around)). I am able to make screenshots with the overlays of these plugins.

My question is: do you have a suggestion on how to handle multple plugins? 
The scalebar has a scalebarInstance object which contains the function getAsCanvas(), however I simply draw my arrows directly on a new canvas, on which the current viewport image is drawn.
If every plugin would have an instance which contained a function drawOnCanvas(canvas), I could loop through the list I have of all the instances and call that function, which would make you have to call it like this:
```
openseadragon.screenshot({
  ...,
  instances: {
    viewer.scalebarInstance,
    viewer.annotationInstance,
    ...
  },
});
```

Which one would be better; drawOnCanvas(), getAsCanvas(), or is there another, more generic way to be able to draw only the overlay elements on the screenshot canvas?

Thanks in advance!

~Koen 

![screenshot 5](https://cloud.githubusercontent.com/assets/19836989/18585605/33dde99c-7c18-11e6-9084-088ad352a9e1.png)

**Comment by avandecreme** [comment]
If the plugins all have a `getAsCanvas` method, you should be able to create a `drawOnCanvas` method by using [`context.drawImage`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage). This method can take a canvas as parameter.

Does it answer your question?

**Comment by KTGLeiden** [comment]
That is exactly how I do it right now ;)
I will use the Overlay objects' position for determining where I would place this canvas, and if someone would want to add his/her own plugin to the screenshot, they would just add that method and add the instance to the list.

Thanks!
