### ISSUE TITLE
Maintain zoom level and center on window / viewer resize

### ISSUE THREAD

**Issue by bayucandra** [openseadragon/openseadragon#963]
Is it possible to maintain zoom level and center of viewport when we scaling browser window / viewer size? I have an application which need to keep zoom level and center remain same even when users resize the window, because my application synchronize OSD viewport to all connected users trough socket.io. It is look strange when there is user who resize window then send signal zoom and pan in OSD `resize` event way and will give unnecessary  disrupt other users viewport.

**Comment by iangilman** [comment]
You can try using `preserveImageSizeOnResize: true` to see if that helps. Otherwise you can use `autoResize: false` and manage it yourself.

**Comment by bayucandra** [comment]
Seem i have to do in `autoResize: true` way, since the `preserveImageSizeOnResize: true` still changing the zoomlevel and center position. Thank you for your help as always :).

**Comment by bayucandra** [comment]
Hi @iangilman i have tried to digging inside openseadragon.js source to handle `resize` event but still no success. I am trying to look into `function updateOnce( viewer )` and adopt it to custom window resize event, am i looking to wrong section? My image still look stretched after the window resized.

**Comment by avandecreme** [comment]
The relevant code is here https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2988-L3009

It doesn't look like there is a good event you can listen to to tweak the behavior.
For now, you can try to modify that code like this and see if that works for you. We can figure out a better approach afterward.

```javascript
    if (viewer.autoResize) {
        var containerSize = _getSafeElemSize(viewer.container);
        var prevContainerSize = THIS[viewer.hash].prevContainerSize;
        if (!containerSize.equals(prevContainerSize)) {
            var viewport = viewer.viewport;
            var center = viewport.getCenter();
            viewport.resize(containerSize, false);
            viewport.panTo(center, true);
            THIS[viewer.hash].prevContainerSize = containerSize;
            THIS[viewer.hash].forceRedraw = true;
        }
    }
```

**Comment by bayucandra** [comment]
Hi @avandecreme thanks for your help. I have tried your code and seem it is works great for maintain the `center` coordinate. But it's still not maintain the zoom level as i need. Although i have tried to add following code too:
    var zoom = viewport.getZoom();
    viewport.zoomTo(zoom);

**Comment by iangilman** [comment]
Yeah, I suppose we could create a resize event. Typically what I've done in the past is just watch for window resize events with jQuery (ignoring OSD) and then handle things as needed in that event handler. Here's an example:

https://github.com/openseadragon/openseadragon/blob/master/test/demo/m2/js/main.js#L158

As for maintaining the zoom, the challenge there is that our zoom is in relation to the viewport width, so it changes when the container changes. A zoom of 1 means the image exactly fits the viewer. A zoom of 2 means you can see half of the image width in the viewer. 

One way to deal with this would be to convert to the "image zoom" which is the zoom relative to the original image pixels. Something like this:

```
var zoom = viewport.viewportToImageZoom(viewport.getZoom());
viewport.resize(containerSize, false);
viewport.zoomTo(viewport.imageToViewportZoom(zoom));
```

(The above code is assuming you just have a single image in your viewport at a time.)

**Comment by avandecreme** [comment]
This should be equivalent to what is done when `preserveImageSizeOnResize == true` so I am not sure what behavior @bayucandra need.

**Comment by msalsbery** [comment]
I thought I did that already....preserving zoom factor and position was always a requirement for my apps :)

**Comment by bayucandra** [comment]
Hi all, thanks for your attention.

@iangilman : although seem what @avandecreme  code now is works, will try your advice too, thanks.

@avandecreme  : sorry for the confusion, It is now works by my add of `viewport.zoomTo(zoom);`. I was linking to wrong library when test with my small modification from your code :) . Thanks a lot for your help. 
about the `preserveImageSizeOnResize == true` it is still doing `zoom` and `pan` event right? seem it is only trying to maintain the image size on screen but change the `zoom` level and `center` position. May be it is related to what @iangilman said about relative to viewport width. 

Actually i am not only looking for maintain the zoom and center on OSD view. In additional I am trying to avoid OSD from triggering `zoom` and `pan` event on window resize event. Because i put `socket.io` signal at `zoom` and `pan` event to be synchronized with all connected users. So, `zoom` and `pan` which produced by window `resize` event is an unexpected event in my application.

@msalsbery : can you tell me how to achieve that? because based on @avandecreme code i must change OSD library. If it is already exist i think it could be more stable than the hack version :).

**Comment by iangilman** [comment]
Hmm, I don't know that there's any way to avoid triggering the events, but one approach would be to set a flag when you start your resize process, and if that flag is set and you get a pan or zoom event, just ignore it. Then of course unset the flag when your resize process is done.

**Comment by avandecreme** [comment]
I wonder if the best approach for you could be to keep the original OSD code and set `preserveImageSizeOnResize = true`.
When listening to the `resize` event, instead of passing the viewport zoom, pass the image zoom (you can use [viewport.viewportToImageZoom](http://openseadragon.github.io/docs/OpenSeadragon.Viewport.html#viewportToImageZoom) to retrieve it).
On your other clients, you would then call `zoomTo(viewport.imageToViewportZoom(imageZoom))`

**Comment by bayucandra** [comment]
@iangilman yes, you are right. It could be another alternative solution for my problem.
@avandecreme that sounds good, it is new for me about `viewportToImageZoom`. Will make some experiment about that.

Thanks a lot for both of you.
