### ISSUE TITLE
Question about addTiledImage

### ISSUE THREAD

**Issue by dgutman** [openseadragon/openseadragon#964]
Is there any way to inject a class to a specific tile layer so I can apply filters/colors only to the layer?

I started exploring the viewer.world._items .... but I wasn't sure if there's any way to access/modify the tile layer via css/jquery/etc....

**Comment by iangilman** [comment]
Unless you're on IE8 or otherwise have unusual needs, all OSD rendering is done with Canvas, so there are no DOM elements to style. We do have various mechanisms for manipulating the Canvas and the tiles drawn to it... take a look at the `tile-loaded` event and the `compositeOperation` option for a start.

**Comment by dgutman** [comment]
Ok thanks----!

On Tue, Jun 14, 2016 at 1:22 PM Ian Gilman <notifications@github.com> wrote:

> Unless you're on IE8 or otherwise have unusual needs, all OSD rendering is
> done with Canvas, so there are no DOM elements to style. We do have various
> mechanisms for manipulating the Canvas and the tiles drawn to it... take a
> look at the tile-loaded event and the compositeOperation option for a
> start.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openseadragon/openseadragon/issues/964#issuecomment-225953127>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AArhzivKkOGn9PCK8Gg4o-okv-YDPWlCks5qLuNOgaJpZM4I1dJZ>
> .
>
-- 
David A Gutman MD PhD
Assistant Professor of Neurology, Psychiatry & Biomedical Informatics
Emory University School of Medicine
Staff Physician, Mental Health Service Line
Atlanta VA Medical Center

**Comment by dgutman** [comment]
Would any of these allow me to apply any color/image filters on the tiles
prior to actually injection into the canvas?



On Tue, Jun 14, 2016 at 1:22 PM Ian Gilman <notifications@github.com> wrote:

> Unless you're on IE8 or otherwise have unusual needs, all OSD rendering is
> done with Canvas, so there are no DOM elements to style. We do have various
> mechanisms for manipulating the Canvas and the tiles drawn to it... take a
> look at the tile-loaded event and the compositeOperation option for a
> start.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openseadragon/openseadragon/issues/964#issuecomment-225953127>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AArhzivKkOGn9PCK8Gg4o-okv-YDPWlCks5qLuNOgaJpZM4I1dJZ>
> .
>
-- 
David A Gutman MD PhD
Assistant Professor of Neurology, Psychiatry & Biomedical Informatics
Emory University School of Medicine
Staff Physician, Mental Health Service Line
Atlanta VA Medical Center

**Comment by dgutman** [comment]
At one point , since each layer had a DIV associated with it, I could apply
a filter to each div to recolor it.... I see the opacity can get adjusted
prior to insertion into the canvas.... so I am curious if there's a simple
"easy" way to apply some sort of pixel level operation on the tile prior to
it being copied in to the canvas...


On Tue, Jun 14, 2016 at 1:48 PM David Gutman <dagutman@gmail.com> wrote:

> Would any of these allow me to apply any color/image filters on the tiles
> prior to actually injection into the canvas?
>
>
>
> On Tue, Jun 14, 2016 at 1:22 PM Ian Gilman <notifications@github.com>
> wrote:
>
>> Unless you're on IE8 or otherwise have unusual needs, all OSD rendering
>> is done with Canvas, so there are no DOM elements to style. We do have
>> various mechanisms for manipulating the Canvas and the tiles drawn to it...
>> take a look at the tile-loaded event and the compositeOperation option
>> for a start.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/openseadragon/openseadragon/issues/964#issuecomment-225953127>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AArhzivKkOGn9PCK8Gg4o-okv-YDPWlCks5qLuNOgaJpZM4I1dJZ>
>> .
>>
> --
> David A Gutman MD PhD
> Assistant Professor of Neurology, Psychiatry & Biomedical Informatics
> Emory University School of Medicine
> Staff Physician, Mental Health Service Line
> Atlanta VA Medical Center
>
-- 
David A Gutman MD PhD
Assistant Professor of Neurology, Psychiatry & Biomedical Informatics
Emory University School of Medicine
Staff Physician, Mental Health Service Line
Atlanta VA Medical Center

**Comment by avandecreme** [comment]
You need to look into the filtering plugin. You can find a link to it on http://openseadragon.github.io

**Comment by dgutman** [comment]
Thanks Antoine--- I started playing around with the filter plugin last
night and it seemed to answer my problem....  Thanks for this nice work..

On Wed, Jun 15, 2016 at 10:23 AM Antoine Vandecreme <
notifications@github.com> wrote:

> You need to look into the filtering plugin. You can find a link to it on
> http://openseadragon.github.io
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openseadragon/openseadragon/issues/964#issuecomment-226202867>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AArhzrKbg0KPCOwKpKQ7dm_FzRn4VEbSks5qMArggaJpZM4I1dJZ>
> .
>
-- 
David A Gutman MD PhD
Assistant Professor of Neurology, Psychiatry & Biomedical Informatics
Emory University School of Medicine
Staff Physician, Mental Health Service Line
Atlanta VA Medical Center
