### ISSUE TITLE
Is it possible to exactly position an image in the viewport

### ISSUE THREAD

**Issue by Pin0** [openseadragon/openseadragon#968]
We have a viewer with hotspots. I would like to left align the image to that hotspot in the viewer by using javascript.

I already found viewport.panTo() But that uses viewport coordinates and uses the center of the viewer. I would like to not use the center but the top left corner.

Any thought on this are welcome!

**Comment by iangilman** [comment]
Certainly. The preferred technique for doing this is viewport.fitBounds(). Keep in mind that it uses viewport coordinates.

**Comment by Pin0** [comment]
Thanks that put me on the right track!

giving image coordinates posx, and posy

To go to that coordinate left aligned I used the following code:
```javascript
var bounds = viewer.viewport.getBounds(true);
var currentRect = viewer.viewport.viewportToImageRectangle(bounds);
var rect = viewer.viewport.imageToViewportRectangle(posx, posy, currentRect.width, currentRect.height);
viewer.viewport.fitBoundsWithConstraints(rect);
```

**Comment by qudratullah1061** [comment]
Can we add animation when calling this method "fitBoundsWithConstraints"? So we have animation when setting coordinates to fit in view?
