### ISSUE TITLE
Avoid zoom caused by procedures on open image

### ISSUE THREAD

**Issue by bayucandra** [openseadragon/openseadragon#972]
I am trying to avoid zoom which caused by OSD procedures when open an image. Hence i am trying to set viewer property with `preserveViewport = true` . It was works as expected when i am not set the `width` on `viewer.open()` properties at the parameter. It was like follow :

	    self.viewer.open({
		tileSource:{
		    width: data.width, height: data.height,
		    tileOverlap: 2,  tileSize: 250,
		    getTileUrl: function( level, x, y ){
			return "/drawing/tiles/"+page_number+'/'+level+"_"+x+"_"+y;
		    }
		}
	    });

But if i add `width` properties at the parameter as follow, sometimes it will add at least 3 times of zoom event ( 3 step zooming until reach the last zoom level ) :

	    self.viewer.open({
		width: data.width,
		tileSource:{
		    width: data.width, height: data.height,
		    tileOverlap: 2,
		    tileSize: 250,
		    getTileUrl: function( level, x, y ){
			return "/drawing/tiles/"+page_number+'/'+level+"_"+x+"_"+y;
		    }
		}
	    });

Is it possible to avoid `zoom` event in any other way after `viewer.open()`? Although i am not sure what causing the slight zooming after open an image. Thanks in advance.

**Comment by iangilman** [comment]
I imagine the zoom is just changing the viewport from its default to something that matches your new coordinates. I'm not sure why there would be three of them, though.

Anyway, probably your best bet is to detect this circumstance and suppress handling of the events, just like the other scenario we discussed. Do the events happen before or after the open event is fired?

**Comment by bayucandra** [comment]
Sorry, seem it was my mistakes. I have Viewport.goHome() which i was thought it will not producing zoom in animation. But it does give me 3 step zooming for animation.
