### ISSUE TITLE
Tiles do not fill canvas after rotation

### ISSUE THREAD

**Issue by leesei** [openseadragon/openseadragon#973]
Clone [this repo](https://github.com/leesei/test-osd-rotate) and serve it via HTTP server (e.g. `ecstatic`, `python -m SimpleHTTPServer`).  
Visit the page and enter the following snippets in console.

These are exposed to `window`:
- viewer
- viewport
- tiledImage
### Fail case

``` js
viewport.zoomTo(tiledImage.imageToViewportZoom(2.0))
// wait for 'view-updated'
viewport.setRotation(0)
// wait for 'view-updated'
viewport.setRotation(44)
```

The tiles do not fill canvas these operations (the white canvas background  can be seen).
![screenshot-2016-06-28-130943](https://cloud.githubusercontent.com/assets/544400/16404449/aee9dc2a-3d31-11e6-8365-ea403f4e9c3f.png)

Resizing the window will fix the issue, and subsequent calls to rotation will not trigger the issue.

OSD 2.1.0 does not have this issue (change the `<script>` in `index.html`).
### Success case

Single paste and execute, without waiting for `view-updated`

``` js
viewport.zoomTo(tiledImage.imageToViewportZoom(2.0))
viewport.setRotation(0)
viewport.setRotation(44)
```
### Success case

Without `setRotation(0)`

``` js
viewport.zoomTo(tiledImage.imageToViewportZoom(2.0))
// wait for 'view-updated'
viewport.setRotation(44)
```

**Comment by avandecreme** [comment]
Good catch and thanks for the detailed bug report. I suspect a timing error when creating (or extending) the sketch canvas here: https://github.com/openseadragon/openseadragon/blob/master/src/drawer.js#L319-L339

Would you be up to trace that down?

**Comment by leesei** [comment]
Verified the fix.
Actually I'm also skipping `setRotation(0)` in my app as a hotfix.

**Comment by iangilman** [comment]
@leesei Thank you for verifying!
