### ISSUE TITLE
[Q] Converting percent of an image coordinates to the viewport coordinates

### ISSUE THREAD

**Issue by peterlitvak** [openseadragon/openseadragon#974]
I have some old (non DZI) images with custom overlays that have % of an image coordinate system. When migrating to OSD I need to convert the overlay's coordinates and dimensions in to OSD viewport coordinate system.
For landscape images it is pretty straightforward and can be done like so (Java):
```
// Our DZI viewport always uses 1 for the width scale. 
// The height scale needs to be calculated based on the aspect ratio. 
// This is per https://openseadragon.github.io/examples/viewport-coordinates/
double imageAspectRation = width / height;
double dziViewportXScale = 1.0;
double dziViewportYScale = dziViewportXScale / imageAspectRation;

// convert markup image coordinates to DZI viewport coordinates
double newMarkupTop = oldMarkup.getTop() * dziViewportYScale;
double newMarkupLeft = oldMarkup.getLeft() * dziViewportXScale;
double newMarkupWidth = oldMarkup.getWidth() * dziViewportXScale;
double newMarkupHeight = oldMarkup.getHeight() * dziViewportYScale;
```
This does the right thing.
I expected the same to work for the portrait images but the X coordinate and WIDTH seems to be calculated incorrectly. I think I'm missing something simple here but cannot quite get it.

Is there any special handling when portrait image is displayed in OSD.

The viewport is always in landscape orientation so I guess that could be a contributing factor and some adjustment needs to be made in regards to this.

**Comment by iangilman** [comment]
The default viewport coordinates are indeed 1 for width no matter whether it's portrait or landscape. With the percentage coordinates, is it always a percentage of the width or is it a percentage of the longest dimension? If the latter, then you'll have to adjust your math to account for that, mapping 100% to whatever the viewport height happens to be.

**Comment by peterlitvak** [comment]
thank you, this seems to be a problem with the way the old ones were originally captured, so user error :)
