### ISSUE TITLE
Problems with overlays

### ISSUE THREAD

**Issue by edsilv** [openseadragon/openseadragon#975]
Hi,

I've been trying to fix this:

https://github.com/UniversalViewer/universalviewer/issues/201

It looks like using the normalised coordinate space associated with viewer.open() causes overlays to be misaligned.

![normalised](https://cloud.githubusercontent.com/assets/1334393/16491727/fb63abe8-3ed6-11e6-9823-9b61ec008dd6.jpg)

I have experimented with using viewer.addTiledImage instead, which uses an absolute coordinate space. This fixes the alignment issue.

![absolute](https://cloud.githubusercontent.com/assets/1334393/16491751/15b44160-3ed7-11e6-8c75-3267fccafb2e.jpg)

However, it means that OSD isn't firing the 'open' event, which I listen for in order to then call viewer.viewport.fitBounds. This enables users to share a given zoom. I also don't seem to be able to use goHome() programmatically without using a setTimeout (presumably this can't happen until everything has loaded?).

Is there an alternative to the 'open' event that might work? Or perhaps I can keep using viewer.open() and fix the overlay positioning another way?

Also, https://github.com/UniversalViewer/universalviewer/issues/328

![rotated](https://cloud.githubusercontent.com/assets/1334393/16491774/2cdc6872-3ed7-11e6-82d8-1282f80e340a.jpg)

It seems like whether using normalised or absolute coordinates, OSD has a problem with rotated overlays. Any advice on how to proceed gratefully received...

**Comment by iangilman** [comment]
You can specify the coordinate system with `open` just like with `addTiledImage`:

```
viewer.open({
  width: 1000,
  tileSource: foo
});
```

On the other hand, if you prefer addTiledImage, you can use its `success` property to get a callback, or wait for the World's "add-item" event which is akin to the open event:

```
viewer.world.addHandler('add-item', handler);
```

Regarding rotated overlays, are you using the latest version of OSD? @avandecreme did a lot of work on rotation and overlays in the recent release.

**Comment by edsilv** [comment]
I'm using addTiledImage and counting the `add-item` events until they match the number I added, then adding the overlays. Seems to be working well.

After updating to v2.2.1 the rotation bug was fixed.

Many thanks!
