### ISSUE TITLE
viewport.contentSize returns a null object

### ISSUE THREAD

**Issue by lucalianas** [openseadragon/openseadragon#977]
When trying to retrieve x and y sizes of an image using viewport.contentSize I got the following error

`Uncaught TypeError: Cannot read property 'x' of null`

I experienced the same problem in the problem in both my scripts and in the [fitboundswithconstraints.html](https://github.com/openseadragon/openseadragon/blob/master/test/demo/fitboundswithconstraints.html) example.

**Comment by avandecreme** [comment]
This variable has been removed in 2.2.0.
See https://github.com/openseadragon/openseadragon/blob/master/changelog.txt#L15

What are you trying to retrieve?
The size of the image in pixel? If so, you can use `viewer.world.getItemAt(0).source.dimensions`
If you want the world bounds in viewport coordinates, you can use `viewer.world.getHomeBounds()`

**Comment by lucalianas** [comment]
Yes, I was trying to retrieve the size of the image in pixel, I fixed using the method you suggested, thanks!
