### ISSUE TITLE
Image starting position

### ISSUE THREAD

**Issue by forestwow** [openseadragon/openseadragon#979]
Hello,
i could not find it in documentation. So is there any way to show top of image after Openseadragon starts working? Currently after Openseadragon initialize, it starts in the middle of image(when i use defaultZoomLevel=1). My container for viewer is really small, and the entire image does not fit. So i want start showing the image from the top, not from the middle. 

edit:
Finally i end up with this:

```
var oldBounds = viewer.viewport.getBounds(); 
var newBounds = new OpenSeadragon.Rect(0, 0, 1, oldBounds.height / oldBounds.width); 
viewer.viewport.fitBounds(newBounds, true);
```

But i'm still not sure, how to make this works after Openseadrgon starts running.

edit2:
Ok, sorry for this post. Finally, i make it working ;):

```
viewer.addHandler("open", function(){
    var oldBounds = viewer.viewport.getBounds();
    var newBounds = new OpenSeadragon.Rect(0, 0.2, 1, oldBounds.height / oldBounds.width);
    viewer.viewport.fitBounds(newBounds, true);
});
```

**Comment by iangilman** [comment]
That's exactly what I would have recommended! Glad you got it figured out. :)

**Comment by tenielg** [comment]
Thank you. Your solution was useful for me. I had exactly the same issue
