### ISSUE TITLE
Unique overlay for one zoom in a sequence

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#983]
I'm presenting several zooms in a sequence, one at a time. The format works well.
But now I want to utilize an overlay - but only on one of the zooms.
I'm the first to admit my novice js skills are showing here.
I tried to addClass / removeClass on click but cannot drill down to the overlay properties.

Page under development is here: http://deepzoomchattanooga.com/gpn_set4dev.php
You'll see the overlay remains on every image.

Ideally, I would like to add the overlay on click - or simply hide it on all other 'pages'.
Any guidance would be greatly appreciated!

**Comment by avandecreme** [comment]
I am not sure to understand what you are trying to achieve.
To display/hide an overlay depending on the zoom level, I would listen to the `zoom` event and set the appropriate class, as you suggested, depending on whether you are in the correct zoom interval or not.

To add an overlay on click, you can check out the runtime overlay example on this page: http://openseadragon.github.io/examples/ui-overlays/

**Comment by iangilman** [comment]
How are you switching between images? Are you just calling `open` or are you using sequence mode? Mostly just curious... fwiw I think `open` is your best bet here, but whatever works...

At any rate, I think the runtime overlays (`viewer.addOverlay`) that @avandecreme suggests are the way to go.

**Comment by SamHall** [comment]
Here's some simplified relevant code from that link.
Yes, switching the source images in the viewer - via clicking on matching class.
My tilesources are lined up in a series and I call the matching 'page'.

What I'm trying to do is tie an overlay specifically to one of the pages/zooms.
As the overlays code is placed now, it applies to every zoom in viewer.
I have not successfully managed to assign it the same way I'm switching pages, but it may be a matter of knowing javascript better than I do.
I attempted to addClass & removeClass on click but could not affect the embedded styling of the overlay.

Thanks.



```javascript
 var viewer = new OpenSeadragon.Viewer({
            id: "openseadragon-canvas",
            prefixUrl: "/openseadragon/images/",
            tileSources: [
              "/zoom/set1/dzc_output.xml",  
              "/zoom/set2/dzc_output.xml",
              "/zoom/set3/dzc_output.xml",
              "/zoom/set4/dzc_output.xml"
            ],
            sequenceMode: true,
            showSequenceControl: false,
            showReferenceStrip:  false,
            
			overlays: [{
              id: 'example-overlay',
              x: 0.1213, 
              y: 0.4354, 
              width:  0.1020, 
              height: 0.0602,
              className: 'highlight',
            }
                      ]
          }
                       );

          $('.pg01').click(function() {
            viewer.goToPage(1);
            $('.openseadragon').addClass('vert');
            $('.openseadragon').removeClass('horz');
            $("#div1").text("Front Porch Courting");
          }
                          );
          $('.pg02').click(function() {
            viewer.goToPage(2);
            $('.openseadragon').addClass('vert');
            $('.openseadragon').removeClass('horz');
            $("#div1").text("Photo in a Photo");
          }
                          );
						  
          $('.pg03').click(function() {
            viewer.goToPage(3);
            $('.openseadragon').addClass('horz');
            $('.openseadragon').removeClass('vert');
            $("#div1").text("Snow Day on Lindsay Street");
          }
                          );
```

**Comment by SamHall** [comment]
UPDATE:
I've managed to accomplish this via runtime overlay. 
Next challenge - link to a new tilesource 'page' on click of that overlay.

```javascript
          $('.pg02').click(function() {
              viewer.goToPage(2);
              if (overlay) {
                  viewer.removeOverlay("runtime-overlay");
              } else {
                  var elt = document.createElement("div");
                  elt.id = "runtime-overlay";
                  elt.className = "highlight";
                  viewer.addOverlay({
                      element: elt,
                      location: new OpenSeadragon.Rect(0.1210, 0.4392, 0.0881, 0.0498)
                  });
              }
          });
```

**Comment by iangilman** [comment]
Looks good. What issue are you having with clicking on the overlay?

**Comment by SamHall** [comment]
I can add a class, but it doesn't react to click(function) assignment as expected. Does this have to do with default action on click on an overlay? I only want to do this for one of zooms.

Example:
User selects the page with the overlay - and it loads.
If the user clicks in the overlay I want to load a different page.
 
_$('.pg07').click(function() {
viewer.goToPage(4);
});_

I can add the class **pg07** to the highlight overlay, but it's not clickable.

Also - the overlay is not visible on an iPhone. Not sure why - but I'll recheck my breakpoint CSS rules.

**Comment by iangilman** [comment]
Okay, to get the overlay clickable it's recommended to use OpenSeadragon.MouseTracker instead of jQuery click functions; this is because of the complicated mouse handling code we have.

I don't have any thoughts on the overlay disappearing on mobile except maybe your CSS like you say.
