### ISSUE TITLE
Save Openseadragon canvas after all images are loaded.

### ISSUE THREAD

**Issue by lwjason** [openseadragon/openseadragon#997]
I want to let user save the canvas  like a kind of screenshot function. So I use toDataURL to save the canvas:
 `var osd_img = App.viewer.drawer.canvas.toDataURL("image/png");`

but it will save immediately so that some parts of my image are still blur like the lower part of this image:
![image](https://cloud.githubusercontent.com/assets/8266796/17470745/5eb99e7e-5d71-11e6-83f5-4e549d28bbb7.png)

Is there any function that I can handle my save image function event after the all of the images are loaded?

**Comment by iangilman** [comment]
That functionality (knowing when the view has fully loaded) is in #837, which I've been slacking on... you're welcome to grab that patch as is, or help finish it up so we can land it, or bug me to do so...

**Comment by lwjason** [comment]
I'm not quite familiar with JS, but I'll try it maybe in a few weeks later. Thanks for the response!

**Comment by KTGLeiden** [comment]
If you want this kind of functionality in the form of a button, might you be interested in a screenshot plugin? If so, I will notify you when that's done, but that will be after the merge + some time. If you are content with a few weeks, I might make you happy ;P
