### ISSUE TITLE
Beginners question:  serving 'some.xml' and 'some_files'  folder  from a different server

### ISSUE THREAD

**Issue by comrade2sun** [openseadragon/openseadragon#998]
Some advise needed
Case I
I am trying to load the XML-file and the TileSource from a faster server and using 
openseadragon 2.2.1 (Built on 2016-06-21)
with this simple setup:

```
...
id: "someID",
prefixUrl: "http://absolute.path.to/other/server/img/",
tileSources: ["http://absolute.path.to/other/server/some.xml"]
...
```

The result:

> Unable to open [object Object]:HTTP 0 attempting to load TileSource

As I can see in the browser cache: all 'nav_img.png' are loaded, but no XML-file ---> no images can be loaded and displayed.

Case II
A simple workaround via 'iframe' works like a charm,<strike> as you can see on this test.html (with both cases):
comrade2sun.bplaced.net/artville/test.html</strike> 
<strike>Caveat: </strike>'Toggle full page' does <strike>not</strike> work now

Simple questions: <code>all solved!</code> (read next comment  s.v.p.)
Case I - Do I miss something in my setup? 
Case II - Is there a way to circumvent the limitations of the 'Toggle full page' button in this iframe workaround?

If anybody can spare a minute for this "problems", I would appreaciate any hint to solve them, preferable a solution for Case I. But please bare in mind, I haven't the slightest idea of javascript , it just looks to me like arabian or japanese calligraphy - I can't read nor write it , but I can see the beauty in it.
Thanks for your patience

**Comment by iangilman** [comment]
For Case I you're probably running into cross-domain restrictions. If you have access to the server to set up CORS, that can fix it. Otherwise you'll have to load your tile source differently by copying the XML out of it directly onto your page and interpreting it properly. Here is an example:

http://codepen.io/iangilman/pen/gpejpJ

For Case II, it may be as simple as adding the `allowfullscreen` attribute to your iframe.

**Comment by comrade2sun** [comment]
@iangilman 
Case I
All roads lead to Rome but sometimes I manage to end up in Κωνσταντινούπολις.
Thankfully both provided solutions work as promised and once you get the idea it's as easy as pie.
Thanks for pointing me in the right direction.

Case II
Oooops! ... at least I should owe you a drink in this case.
<code>allowfullscreen</code>
Simply forgotten, shame on me. I apologize for my sloppiness :zzz: and wasting your time with this silly question. But be aware there might be some more naive questions like that in the future  :sparkles:

Anyway, thanks again for your quick response and patience

**Comment by iangilman** [comment]
@comrade2sun Happy to help! Glad you got it sorted out. I look forward to that drink ;)
